### ISSUE TITLE
Mutate and Transmute Should Create Subqueries for Remote Sources

### ISSUE THREAD

**Issue by cosinequanon** [hadley/dplyr#1000]
`mutate` and `transmute` are supposed to be lazy so you can reference previously created columns. This does not work correctly when translating the query to SQL, we need to create subqueries after each statement to make this work.

In MySQL this fails with an error

    > my_db <- src_mysql("test")
    > remote_iris <- copy_to(my_db, iris)
    > remote_iris %>%
    +     transmute(sepal_length = Sepal.Length,
    +               length_plus_one = sepal_length + 1)
    Source: mysql 5.6.22 [root@localhost:/test]
    Error in .local(conn, statement, ...) :
      could not run statement: Unknown column 'sepal_length' in 'field list'

SQLite is worse, it silently does the wrong thing.

    > remote_iris %>%
    +     transmute(sepal_length = Sepal.Length,
    +               length_plus_one = sepal_length + 1)
    Source: sqlite 3.8.6 [my_db.sqlite3]
    From: iris [150 x 2]

       sepal_length length_plus_one
    1           5.1               1
    2           4.9               1
    3           4.7               1
    4           4.6               1

This is sort of related to #983

**Comment by hadley** [comment]
Now works post-massive write of SQL internals:

```R
memdb_frame(x = 1:5) %>% 
  mutate(y = x + 1) %>% 
  mutate(z = y + 1)
```

**Comment by cosinequanon** [comment]
Sweeeeeeet
