### ISSUE TITLE
[ in grouped_dt

### ISSUE THREAD

**Issue by kismsu** [hadley/dplyr#1003]
Hi, I've noticed that you can't use `[` with grouped_dt object. You'd expect that in example bellow the result should be the same, but it's not. 
```r
f <- function(x) {
    return(data.frame(first_element = x[1,"mpg"]))
}

mtcars %>% 
    tbl_dt() %>%
    select(mpg, cyl) %>%
    group_by(cyl) %>%
    do(f(.)) 
```

```r
Source: local data table [3 x 2]
Groups: cyl

  cyl first_element
1   6           mpg
2   4           mpg
3   8           mpg
```

```r
mtcars %>% 
    select(mpg, cyl) %>%
    group_by(cyl) %>%
    do(f(.)) 

```

```r
Source: local data frame [3 x 2]
Groups: cyl

  cyl  mpg
1   4 22.8
2   6 21.0
3   8 18.7
```

**Comment by pimentel** [comment]
Hi @kismsu. This is a nuance with `data.table` and not `dplyr`. `data.table` expects the column select statement (second argument in square braces) to be quoted. For example, the following code will generate what you expect with `data.table`:

```{r}
f <- function(x) {
    return(data.frame(first_element = x[1,mpg]))
}
```

Result:
```{r}
Source: local data table [3 x 2]
Groups: cyl

  cyl first_element
1   6          21.0
2   4          22.8
3   8          18.7
```

You can give `data.table` a character string by telling it not to use non-standard evaluation with the "with" argument in the third space like: `x[1, "mpg", with = FALSE]`.
