### ISSUE TITLE
Feature Req: Include "missing=" in join functions.

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/dplyr#1004]
This is an idle request for a feature which I would find handy, but probably weird/difficult/obscure.

When joining tables (e.g. left_join(x, y)), if there is a non-present value, it currently gets included as "NA" - so, very much behaving like SQL joins.  After doing such an operation, I then have to do a mutate() with an ifelse() to convert these NA values into a sensible default.

To make it a little more flexible, would it be possible to specify what these missing values should be replaced with?
e.g.
left_join(x, y) is really left_join(x, y, missing=NA)

but you could then have:
left_join(x, y, missing=0.0) or left_join(x, y, missing="Not avail")

**Comment by pimentel** [comment]
+1

**Comment by hadley** [comment]
I don't see how this could work because you'd need to specify at least four values: one for logical, integer, double, and character. What about factors? Dates? ...

**Comment by coolbutuseless** [comment]
Yeah, sorry. It makes more sense to do a join + custom mutate(ifelse(is.na())) since this idea is going to make little sense when there are multiple columns of multiple types.
