### ISSUE TITLE
Can't connect to Views in PostgreSQL

### ISSUE THREAD

**Issue by Quiri** [hadley/dplyr#1007]
I have a postgres database with some views in it, when I connect to the database via src_postgres, the connection only shows the "real" tables and no views. When I try to query a view, I get a table not available error.

**Comment by HarlanH** [comment]
at some point I found that this is the workaround:

```r
v_asdf <- tbl(con, sql("SELECT * FROM schema.v_asdf"))

v_asdf %>%
  select(whatever...)
```

**Comment by Quiri** [comment]
Is there also a fix?

**Comment by currymj** [comment]
It doesn't look like RPostgreSQL is actually getting views in its implementation of `dbListTables`. Relevant line here from PostgreSQL.R in that package:

```{R}
out <- dbGetQuery(conn, paste("select tablename from pg_tables where schemaname !='information_schema'",  "and schemaname !='pg_catalog'", ...))
```

On my Postgres (9.4.1) `pg_tables` doesn't include views, only "real" tables.

**Comment by koseri** [comment]
+1

**Comment by dlebauer** [comment]
+1

**Comment by mbojan** [comment]
Definitely +1.

See also here http://stackoverflow.com/questions/26755281/can-dplyr-access-a-postgres-9-3-5-view

**Comment by hadley** [comment]
This is probably a bug in RPostgreSQL, but I'll see if dplyr can do better

**Comment by krlmlr** [comment]
Should be fixed by https://github.com/rstats-db/DBI/issues/24.
