### ISSUE TITLE
top_n doesn't play well with desc

### ISSUE THREAD

**Issue by HarlanH** [hadley/dplyr#1008]
It looks like `top_n` is a wrapper around `filter(min_rank(desc()))`, which means that `top_n(x, 1, desc(col))` causes a SQL syntax error, and of course there's no way to do `top_n(x, 1, asc(col))`. 

Perhaps a `bottom_n` function that does the same thing, but without the hard-coded `desc`?

Workaround is trivial, of course, but the symmetric API would be handy!

Thanks!

**Comment by klmr** [comment]
I think it also doesn’t work on `data.frame`s but I might misunderstand the semantics. I’ve got a table with a column of p-values, and doing `x %>% top_n(100, desc(pval))` returns a different set of of rows than `x %>% arrange(pval) %>% head(100)`.

**Comment by hadley** [comment]
I didn't check this with SQL, but I think using `-n` to indicate that you want the bottom n values is a reasonable compromise between concision and expression.
