### ISSUE TITLE
Build variable interpolation into hybrid evaluator

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#1012]
I see a lot of code that does something like this: 

```
f <- function(data, variable, value ){
   filter_( data, interp( ~ var == value, var = as.name(variable) ) )
}
f( iris, "Species", "setosa" )
```

which I find kind of verbose and perhaps not so easy to read. 

I was thinking of something like this: 

```
filter( data, column(variable) == value )
```

`column` would take a string like `"Species"` and substitute it to the associated name, i.e. `Species` so that eventually it is just like we were doing `filter(data, Species == value )`. 

I think it would be fairly easy to do internally, and the code would be IMO much more readable. @hadley what do you think ?

**Comment by hadley** [comment]
I like that idea. It's a generalised form of `one_of()` for all verbs.

**Comment by romainfrancois** [comment]
Not closed yet because I'd like it to work for `group_by`too.

**Comment by hadley** [comment]
As I mentioned via twitter it would be useful if this worked in conjunction with the opposite of `global()`, too so that it would only ever evaluate in the columns of the data frame, not the parent environment (if this is actually possible given the constraints of disambiguating function from variables).

I'm also not sure that `column()` is the right verb. Maybe `interp()`? Or maybe we should have `global_()` and `global()`, and `var_()` and `var()`? You'd use `var()` to force interpretation as a variable name, and if the variable didn't exist, dplyr would throw an error. You could either do `var(cyl)` or `var_("cyl")` by analogy with the other SE/NSE pairs. Does that make sense?

@kevinushey any ideas?

**Comment by hadley** [comment]
I'm mostly thinking about what people will want to do with this function. I'd imagine you'd want to write something like:

```{r}
filter_even <- function(df, my_var) {
  filter(df, var_(my_var) %% 2 == 0)
}

cly <- 2
filter_even(mtcars, cly)
```

It would be nice if that could throw a clean error if `my_var` was supplied incorrectly, instead of sometimes working if a variable of that name existed in a parent scope.

**Comment by lgautier** [comment]
An alternative is to have the local/current data frame referred to with a specific symbol, and use an already an existing idiom to pick a column in data frame (for example `[[`): 

It would look like:

```R
filter_on_value <- function(df, my_var, value) {
  filter(df, _[[my_var]] > value)
}
#or
filter_on_value <- function(df, my_var, value) {
  filter(df, this[[my_var]] > value)
}
#or
filter_on_value <- function(df, my_var, value) {
  filter(df, self[[my_var]] > value)
}
```

**Comment by hadley** [comment]
@lgautier that would also work, but then you need to carefully pick a data frame pronoun that isn't likely to conflict with an existing variable name. Maintaining the function/variable separation like the rest of R seems more elegant to me.

@romainfrancois can you please also make sure all three forms work:

```R
filter(mtcars, column("cyl") == 4)
filter(mtcars, column(quote(cyl)) == 4)
filter(mtcars, column(~ cyl) == 4)
```

For the one-sided formula, you can throw an error if the call to `~` has more than 2 components, or the second element is not a symbol.

**Comment by romainfrancois** [comment]
I get this: 

```
> filter(mtcars, column("cyl") == 4)
    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
1  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
2  24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
3  22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
4  32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
5  30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
6  33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
7  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
8  27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
9  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
10 30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
11 21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
> filter(mtcars, column(quote(cyl)) == 4)
Erreur : column must return a single string
> filter(mtcars, column(~ cyl) == 4)
Erreur : column must return a single string
```

I'll make the 2 others work.

**Comment by romainfrancois** [comment]
Now, all the forms above are supported, and `group_by` also supports `column`. 
I think this can be closed now. @hadley anything else on `column` ?

I think I like `column` better over `var` because of `stats::var` and also because `var` would be an abbreviation of `variable`. I prefer explicit. No strong feeling either way though.

**Comment by hadley** [comment]
I'm not a big fan of `column()` just because I think of matrices having columns and data frames having variables. Let me think about it for a bit

**Comment by romainfrancois** [comment]
In trying to support `column` (or whatever we'll call it) in `group_by`, I've added this in `group_by_prepare` : 

```r
  new_groups <- resolve_vars(new_groups, names(.data))
```

The problem is `names(.data)` does not give me what I want on sql data sets, e.g. : 

```
> df <- data.frame(x = rep(1:3, each = 10), y = rep(1:6, each = 5))
>
> srcs <- temp_srcs(c("df", "dt", "sqlite", "postgres"))
> tbls <- temp_load(srcs, df)
>
> names( tbls$sqlite )
[1] "src"       "from"      "select"    "summarise" "mutate"    "where"
[7] "group_by"  "order_by"  "query"
> str( tbls$sqlite )
List of 9
 $ src      :List of 3
  ..$ con :Formal class 'SQLiteConnection' [package "RSQLite"] with 5 slots
  .. .. ..@ Id                 :<externalptr>
  .. .. ..@ dbname             : chr "/var/folders/7n/w26z7wqn16526tp2n2d664s40000gn/T//Rtmp9Pauvz/file16e245b558cd"
  .. .. ..@ loadable.extensions: logi TRUE
  .. .. ..@ flags              : int 6
  .. .. ..@ vfs                : chr ""
  ..$ path: chr "/var/folders/7n/w26z7wqn16526tp2n2d664s40000gn/T//Rtmp9Pauvz/file16e245b558cd"
  ..$ info:List of 2
  .. ..$ serverVersion: chr "3.8.6"
  .. ..$ results      : logi FALSE
  ..- attr(*, "class")= chr [1:3] "src_sqlite" "src_sql" "src"
 $ from     :Classes 'ident', 'sql', 'character'  chr "tbfgqoqtwf"
 $ select   :List of 2
  ..$ : symbol x
  ..$ : symbol y
 $ summarise: logi FALSE
 $ mutate   : logi FALSE
 $ where    : NULL
 $ group_by : NULL
 $ order_by : NULL
 $ query    :Classes 'Query', 'R6' <environment: 0x7fea51113430>
 - attr(*, "class")= chr [1:3] "tbl_sqlite" "tbl_sql" "tbl"
```

Is there a generic way to grab the column names ? @hadley ?

**Comment by romainfrancois** [comment]
I've added this (not exported)

```
column_names <- function(x){
  UseMethod( "column_names" )
}
column_names.data.frame  <- function(x) names(x)
column_names.tbl_sql <- function(x) x$query$vars()
```

Just let me know if there is a better way.

**Comment by romainfrancois** [comment]
Nevermind. I found `tbl_vars` 😎

**Comment by hadley** [comment]
Yeah I keep forgetting about `tbl_vars()` too

**Comment by matthieugomez** [comment]
Would it be possible for `column` to also work in the lhs of `=` (#1205)?

**Comment by romainfrancois** [comment]
No. That's not syntactically valid. Unless we woule use the := operator or some dedicated %something% operator

**Comment by matthieugomez** [comment]
Or a formula sign `~` right? thanks!

**Comment by hadley** [comment]
@romainfrancois I'm coming around to @lgautier's view on this - I think it would be better to add a couple of extra pronouns that referred to either the local data frame or the parent environment.  I'm not sure I have the names right yet, but it would be nice to be able to write:

```R
big_x <- function(x, threshold) {
  filter(df, .this$x < .parent$threshold)
}
```

This would throw an informative error message if `x` did not exist in `df`, and it would never silently return the incorrect result if `df` contained a variable called `threshold`.

This generalises column, because you could also do `.this[var_name_as_string]`.  This needs some thinking about exactly what names the pronouns should have, and what restriction should apply. For example, should you be able to do this:

```R
dplyr::frame_data(
  ~ x, ~ y, ~ var,
  1, 2, "x",
  2, 3, "y"
) %>%  mutate(.this[var])
```

?

**Comment by hadley** [comment]
@romainfrancois And now I think you'll need both so you can flexibly use either column names as variables or as formulas. 

Here's another scenario:

```{r}
new_x <- function(df, x) {
  mutate(df, x = column(x))
}
new_x(mtcars, ~ cyl + mpg)
```

Maybe it would be useful to combine all these scattered issues/scenarios into one.

**Comment by hadley** [comment]
The other advantage of the pronoun approach is that it's easy to implement for other packages:

```R
my_eval <- function(expr, data, parent = parent.frame()) {
  env <- new.env(parent = parent)
  env$.data <- data
  env$.parent <- parent
  
  eval(expr, env)
}
```

It would be nice to be able to use the same approach across ggplot2, dplyr, tidyr, etc etc.

**Comment by lgautier** [comment]
Originally the suggestion of using a pronoun was intended to be an extension of the implicit search path in such callbacks: symbols are looked first in the "main object" of the function (that is the `data.frame`/`data.table`), so why not add a pronoun to refer to that main object (as this lets write code that could iterate over all column names for example) whatever it is. The use of a pronoun would hopefully mean a lower cognitive load for writers and readers than new function names such as "column".

Now the above is going beyond that, and in a rather exciting way, by outlining something akin to an interface for functions. I am picturing it as a contract for the context in which the function will be executed. I suspect that if this was shared across the ecosystem `ggplot2`, `dplyr`, `tidyr`, etc... common pattern designs will be identified (reducing further the cognitive load). R's "base" functions such as `with()` or `attach()`, or rather their use, might also be transformed or replaced with this.

**Comment by krlmlr** [comment]
This should be also available for `local()` calls (https://github.com/hadley/dplyr/issues/1452#issuecomment-249410911).
