### ISSUE TITLE
Support for `labelled` class type from haven

### ISSUE THREAD

**Issue by sjPlot** [hadley/dplyr#1016]
The `labelled` class type from haven might be supported to directly start data wrangling with dplyr after reading a data set, without the need to prior conversion to factors or other classes.

**Comment by malexan** [comment]
The same problem for Hmisc::label():
```R
library(dplyr)
library(Hmisc)
df <- data.frame(year = rep(2011:2012, 2), milk = 1:4)
label(df$year) <- "Label for year column"
class(df$year)
```
> [1] "labelled" "integer"

```R
df %>%
  group_by(year) %>%
  mutate(milk = sum(milk))
```
> Error: column 'year' has unsupported type : labelled, integer

BTW, plyr supports this:
```R
plyr::ddply(df, ~year, function(x) sum(x$milk))
```
>    year V1
> 1 2011  4
> 2 2012  6

**Comment by hadley** [comment]
Now part of #1105
