### ISSUE TITLE
Unable to use aaply 

### ISSUE THREAD

**Issue by Narutoxyy** [hadley/dplyr#1018]
Hi,
 
This is Yayun Xie from Satmap, I would like to report an issue about aaply. 
Here is the error I got:
 
aaply(ozone, 1, mean)
Error in laply(.data = pieces, .fun = .fun, ..., .progress = .progress,  : 
  .fun is not a function.
 
And I wrote a function include aaply:
fakeAgents <- function(nAgents = 20, nSkills = 3, multiNomDist = c(0.98,0.02))
{
  fakeA = aaply(1:nAgents, 1,
                function(thisAgent)
                {
                  out = aaply(1:nSkills, 1,
                        function(thisSkill)
                        {
                          out = aaply(seq_along(multiNomDist), 1, 
                                function(thisLev)
                                {
                                  rbinom(1, 50, multiNomDist[thisLev])
                                }
                          )
                          names(out) = paste(0:(length(multiNomDist) - 1), 'RGU')
                          out
                        }
                  )
                  names(out) = paste('Skill', 1:nSkills)
                  out
                }
                )
  fakeA = aperm(fakeA, c(1,3,2))
  fakeA
}
 
Whenever I run this function, R session abortion.
 
I have install the latest version, could you please help me with this issue?

**Comment by cosinequanon** [comment]
Hey, thanks for reporting, I think you have the wrong project though. `aaply` is not part of the dplyr package, instead you want to report your issue here https://github.com/hadley/plyr

**Comment by Narutoxyy** [comment]
Thank you for your note!

Best,
Yayun

2015-03-13 12:26 GMT-04:00 Sergey Goder <notifications@github.com>:

> Hey, thanks for reporting, I think you have the wrong project though.
> aaply is not part of the dplyr package, instead you want to report your
> issue here https://github.com/hadley/plyr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/dplyr/issues/1018#issuecomment-79100408>.
>



-- 
Yayun Xie
Master Program 2011-2013
Department of Statistics and Mathematics
Georgetown University
Cell: 202-431-8595
yx46@georgetown.edu

**Comment by cosinequanon** [comment]
@Narutoxyy do you mind closing this issue?

**Comment by Narutoxyy** [comment]
Sure! Sorry about that!
