### ISSUE TITLE
New function idea: add_row()

### ISSUE THREAD

**Issue by smach** [hadley/dplyr#1021]
From an exchange on Twitter: An idea for an add_row() function that would make it easy to add a row to a data frame when the columns are of a different class. As you then suggested:

you could make it like add_row(mtcars, cyl = 4, disp = 7) and it filled in the other values with missings

I took a first stab at writing such a function for myself here:

https://github.com/smach/rmiscutils/blob/master/R/add_row.R

Code that's a bit more elegant and efficient would be a nice addition to dplyr!

**Comment by hadley** [comment]
@kevinushey @jennybc any thoughts on what this should look like?

**Comment by jennybc** [comment]
I've always found the way `rbind.data.frame` handles factors to be a minor miracle. It actually expands the levels of the new factor! By default! So that would be a nice feature.

I guess I'd expect `add_row()` to just be slicker version of this:

``` r
library(dplyr)
mtcars2 <- mtcars %>%
  add_rownames()
new_row <- data_frame(rowname = "novel", cyl = 4, disp = 7)
mtcars2 %>%
  full_join(new_row) %>% 
  tail(3) %>% 
  select(-rowname)
#> Joining by: c("rowname", "cyl", "disp")
#> Source: local data frame [3 x 11]
#> 
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl)
#> 1  15.0     8   301   335  3.54  3.57  14.6     0     1     5     8
#> 2  21.4     4   121   109  4.11  2.78  18.6     1     1     4     2
#> 3    NA     4     7    NA    NA    NA    NA    NA    NA    NA    NA
```

I wonder if you would ever want the ability to *insert* a row, i.e. specify a row number? Or to make the new row the first row instead of the last?

**Comment by hadley** [comment]
To me, silently expanding the levels of a factor just seems like the wrong thing to do - the levels of a factor represent a predefined set of values that you already known.

**Comment by jennybc** [comment]
Your factors are not like my factors. Mine have ... one level per gene or other genomic feature, so lots of levels. During exploration the set that survive various steps of analysis is very fluid.

But OK, it seems like a row-inserting user should be content to get the usual  `dplyr` behavior re: joining when it comes to same-name factors with different levels, same-name factor + character var, and same-name vars of incompatible type.

**Comment by hadley** [comment]
@jennybc so why do you use factors instead of strings?

**Comment by jennybc** [comment]
Some is probably habit? All the pieces of your `stringsAsFactors = FALSE` ecosystem haven't been in place for that long.

But also: I tend to be fitting models with fixed gene effects and I need to control the reference level. Also I make lots of facetted plots where facets/genes need to be `reorder()`ed in a principled way. That all feels easier with factor.

**Comment by hadley** [comment]
@jennybc ok, that makes sense. I think we're missing a variable type that's a string + custom ordering.

**Comment by jennybc** [comment]
I didn't appreciate that `bind_rows()` would do this! I.e. that it will cope with missing vars. Nice.

But this `add_row()` business brings it home to me that it going to be hard to hold on to a factor (e.g. #1485). Feels like there's a really strong pull towards character. Change is hard 😕.
