### ISSUE TITLE
implicit arrange in group_by

### ISSUE THREAD

**Issue by rubenarslan** [hadley/dplyr#1026]
In some cases I think it would make sense if group_by %>% summarise automatically sorted by the grouping variables.

At the moment I write

    swed.1 %>% group_by(paternalage.factor) %>% arrange(paternalage.factor) %>% 
    summarise(ever_married = mean(ever_married))

Without the arrange dplyr keeps the data in some order, probably after the first occurrence of each level. I think this rarely is the desired behaviour. I'm not sure what the heuristic would be as to when an implicit arrange would be nice, but I'm pretty sure it always makes sense when you group by one variable and then summarise.

**Comment by hadley** [comment]
Sorting is expensive, so we can't do it automatically on large data. And in your case it would be faster to arrange after the summary.

**Comment by rubenarslan** [comment]
Oh, you're of course right about sorting after the summary. I wanted to suggest doing it automatically only if a summary leads to small data, not in every case.

**Comment by krlmlr** [comment]
I think this somehow became the default now, which was rather unexpected to me. I'm not sure this is desired, because a NEWS entry for `dplyr` 0.4.0 reads:

> group_by() on a data table preserves original order of the rows (#623)

and there are no relevant news items that suggest the opposite in more recent versions.

Test with CRAN version (0.4.3):

```
> data_frame(a = rev(letters[1:3])) %>% group_by(a) %>% ungroup
Source: local data frame [3 x 1]

      a
  (chr)
1     c
2     b
3     a
> data_frame(a = rev(letters[1:3])) %>% group_by(a) %>% summarize() %>% ungroup
Source: local data frame [3 x 1]

      a
  (chr)
1     a
2     b
3     c
> data_frame(a = rev(letters[1:3])) %>% group_by(a) %>% do(data_frame(b=1)) %>% ungroup
Source: local data frame [3 x 2]

      a     b
  (chr) (dbl)
1     a     1
2     b     1
3     c     1
```
