### ISSUE TITLE
Dropping a column used in a preceding group_by

### ISSUE THREAD

**Issue by millerjef** [hadley/dplyr#1030]
What is the intended behavior of dplyr when dropping a column used in a preceding group_by statement? Please refer to the following example:

    grouped <- mtcars %>% group_by(cyl,gear,am) %>% summarise(avgMpg = round(mean(mpg)))
    grouped

Yields:

        cyl gear am avgMpg
     1    4    3  0     22
     2    4    4  0     24
     3    4    4  1     28
     4    4    5  1     28
     5    6    3  0     20
     6    6    4  0     18
     7    6    4  1     21
     8    6    5  1     20
     9    8    3  0     15
     10   8    5  1     15

If one attempts to drop the cylinder column with `dplyr::select`, then the dataset is returned without giving an error and without removing the column:

    select(grouped, -cyl)

This is in contrast to dropping the column with `subset`.

    subset(grouped, select=-cyl)

I can imagine that someone might argue that it is inappropriate to drop the cylinder column after calculating average mpg because the average is misleading without knowing that it represents the mean among cars grouped by `gear`, `am` AND `cyl`. Nonetheless, this behavior caught me by surprise. 

Would it make sense to add a warning and fail to remove the column? Would it make sense to issue a warning and drop the column? Is it possible/desirable to prevent `subset` from dropping a grouped_by column in a `grouped_df` structure?

**Comment by voxnonecho** [comment]
Simply use ```ungroup()```

```grouped %>% ungroup() %>% select(-cyl)```

**Comment by millerjef** [comment]
Thank you. I missed ungroup. Nonetheless, for the uninitiated, would
including a warning message about why the column was not removed (and a
suggestion to ungroup the data) be more robust?

**Comment by voxnonecho** [comment]
I agree.

Maybe the same type of error message used when trying to ```mutate()``` on grouping variable would be a good idea. Something like:

```Error: cannot unselect grouping variable```

**Comment by hadley** [comment]
It used to be a warning (I think), but that was also painful in other situations.
