### ISSUE TITLE
Small bug: can't use magrittr with fully namespaced bind_rows without trailing ()

### ISSUE THREAD

**Issue by daattali** [hadley/dplyr#1032]
This is not a big issue, but wanted to report for completeness.

As everyone knows, when using magrittr, if the function only takes one argument then it's allowed to drop the trailing `()` like so

```
cars %>% head()
cars %>% head
```

When I try to do that with `dplyr::bind_rows`, I get an error 

```
> cars %>% dplyr::bind_rows
Error in .::dplyr : unused argument (bind_rows)
```

Note that these two do not produce an error:

```
cars %>% dplyr::bind_rows()   # adding the ()
cars %>% bind_rows  # not namespacing
```

---
Windows 7, R 3.1.3, dplyr 0.4.1

**Comment by kiyoto** [comment]
I believe this issue is for magrittr and not dplyr per se. Here is a purely magrittr example to produce the same issue:

```R
c(1,2,3,4,5) %>% stats::sd   # throws the same error as you described
c(1,2,3,4,5) %>% stats::sd() # works fine
c(1,2,3,4,5) %>% sd          # works fine too
```

**Comment by romainfrancois** [comment]
Yes please file it in the magrittr repo
