### ISSUE TITLE
mysql filter error when using %in% and only one element

### ISSUE THREAD

**Issue by williamjwest** [hadley/dplyr#1034]
Error in .local(conn, statement, ...) : 
  could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxxxxxxx') AS `master`' at line 3

res = tbl(dcon,"my_table") %>%
    filter(dealer_name %in% input$x )
res
This works without issue when input$x has more than 2 values and throws the error above when input$x has 1 value.

**Comment by hadley** [comment]
Duplicate of #511
