### ISSUE TITLE
a synonym for mutate()?

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#1035]
IIRC, you discussed on Twitter that `mutate()` was not the best name for that function. I think `define()` may be better at conveying the idea that you create or redefine columns as a function of other columns:
```r
mtcars %>%
  define(sum = disp + cyl) %>%
  group_by(am) %>%
  summarise(mean(sum))
```

Maybe `define()` could be added as a synonym of `mutate()`?

**Comment by hadley** [comment]
I think that ship has sailed and adding aliases will now increase net confusion.
