### ISSUE TITLE
new verb to reduce hierarchical data

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#1037]
When working with hierarchical data, it is often useful to reduce group-level variables. These variables are repeated over individual values and there is often a need to save the unique values to a separate data frame. `distinct()` is good for that but it lacks in two things:

* It does not select only the requested variables
* It does not issue an error when the variables differ within groups

The latter is especially important to detect mistakes during data cleaning. So here is `squeeze()`:

```r
squeeze <- function(.data, ...) {
  squeeze_(.data, .dots = lazyeval::lazy_dots(...))
}

squeeze_ <- function(.data, ..., .dots) {
  UseMethod("squeeze_")
}

squeeze_.data.frame <- function(.data, ..., .dots) {
  dots <- lazyeval::all_dots(.dots, ...)
  if (length(dots) > 0) {
    .data <- select_(.data, .dots = dots)
  }

  distincts <- unique(vapply(.data, n_distinct, numeric(1)))
  res <- distinct_(.data)
  if (length(distincts) > 1 || nrow(res) != distincts) {
    stop("values are not unique within groups", call. = FALSE)
  }
  res
}
```

```r
data <- mtcars %>% mutate(other_cyl = cyl * 3)

data %>% squeeze()
## Error: values are not unique within groups

data %>% squeeze(cyl, other_cyl, am)
## Error: values are not unique within groups

data %>% squeeze(cyl, other_cyl)
##   cyl other_cyl
## 1   6        18
## 2   4        12
## 3   8        24
```

It probably needs a bit more work with sql datasets. Let me know if you're interested.

**Comment by hadley** [comment]
I think maybe that's the same goal as https://github.com/hadley/tidyr/issues/14 ?
