### ISSUE TITLE
Should dplyr commands gobble empty last argument?

### ISSUE THREAD

**Issue by rpruim** [hadley/dplyr#1039]
It would be nice to allow a trailing comma in commands like the example below.  That would make it easier to rearrange the order or to comment out lines without needing to figure out whether the commas need adjusting.

```
diamonds %>%
  group_by(color, clarity) %>%
  summarise(
    depth = mean(depth),
    price = mean(price),
    carat = mean(carat),  #  <-- trailing comma here currently causes errors
  )
```

I'm imaging a function that could be called at the top of a function definition that would gobble this empty argument.  Or perhaps a wrapper function a la `Vectorize()` that could be used to convert any function into a function with this behavior.  Seems like this could be useful for many functions both within `dplyr` and elsewhere.

**Comment by romainfrancois** [comment]
Hmm, I don't think I would like that. `dplyr` is still R code.

**Comment by rpruim** [comment]
I don't see how this would violate being R code.  Is it substantially different from
```
x[2, ]
```
which is standard R usage?

Of course, you would be free not to use this feature.

**Comment by romainfrancois** [comment]
well `x[2, ]` is not the same as `x[2]`

**Comment by rpruim** [comment]
True.  But it is an example where an empty argument doesn't cause things to break and is useful.  So I think there is no prohibition on writing functions that allow empty arguments.

I have often wished that c() and list() had this behavior.  It would make code maintenance easier.

**Comment by hadley** [comment]
I see this as a small violation of R's usual rules, in the service of making a common error less common. I don't see any major downsides (except that people might come to expect this in all R functions).

I remember when this wasn't an error in R, and I still miss those days :(

**Comment by romainfrancois** [comment]
In that case, we are probably looking at a change in `lazy_dots` or perhaps how we use it here.

**Comment by hadley** [comment]
@lionel- can you take this on as part of tidyeval conversion?
