### ISSUE TITLE
Strange bug with unicode strings in group_by

### ISSUE THREAD

**Issue by vzemlys** [hadley/dplyr#1041]
I've encountered a weird bug, which I can reproduce on my system, but I am struggling to create a simple reproducible example. This is how I encounter the bug.

1. I have several tables, which have one character column, having unicode characters in some of the column elements.

2. I do multiple joins on these tables and perform various dplyr tasks. But in the end I have two tables on which I do ```full_join```

3. Finally I do a ```group_by``` and ```summarise``` on the character column. Strings with unicode characters get special treatment. If I do ```dt$column %>% unique ``` I get unique strings. But after ```group_by``` and ```summarise```, unicode strings are split. I get one set of results for the rows corresponding to the unicode string from the first table in step 2, and the second set of results for the rows corresponding to the unicode string from the second table in step 2.  

I cannot post the data with which I am working, but here is the code illustrating the problem:

Here is what I essentially do:
```
> cc <- data.frame(a="ąžščš",c=1,d=3)
> bb <- data.frame(a="ąžščš",b=2,d=4)
> dd <- full_join(bb,cc) 
Joining by: c("a", "d")
> dd
      a  b d  c
1 ąžščš  2 4 NA
2 ąžščš NA 3  1
> dd %>% group_by(a) %>% summarize(s=sum(c))
Source: local data frame [1 x 2]

      a  s
1 ąžščš NA
```
The result is entirely expected. However I get the following result instead:

```
> dd %>% select(a,s=c)
      a  s
1 ąžščš NA
2 ąžščš  1
```
Here the code is purely illustrative, I get this result after ``` dd %>% group_by(a) %>% summarize(s=sum(c))```. If I save the result to a variable and do ```res$a %>% unique``` then I see only one string, instead of two. If I save the data to file and then read it again, then the problem disappears. It also disappears if I convert the data to data.table, but unlisting and using as_data_frame, or simply using data.frame does not help.

How should I debug this?

**Comment by romainfrancois** [comment]
I don't understand what the problem is. Can you explain more @vzemlys please.

**Comment by vzemlys** [comment]
When using `group_by` and `summarize` I sometimes get two different results for the same Unicode string. However I fail to create a reproducible example with generated data. So I can only suspect that something is wrong with my data, but I cannot pin down what it is. If I write the offending data frame to the disk and read it again, the `group_by` and `summarize` works as expected.

**Comment by romainfrancois** [comment]
If you do manage to get a reprex, this would be very valuable to us. Otherwise, not much I can do on my end.

**Comment by vzemlys** [comment]
Ok. I managed to track that this probably related to this message:

```
Message d'avis :
In bmerge(i <- shallow(i), x, leftcols, rightcols, io <- haskey(i),  :
  A known encoding (latin1 or UTF-8) was detected in a join column. data.table compares the bytes currently, so doesn't support *mixed* encodings well; i.e., using both latin1 and UTF-8, or if any unknown encodings are non-ascii and some of those are marked known and others not. But if either latin1 or UTF-8 is used exclusively, and all unknown encodings are ascii, then the result should be ok. In future we will check for you and avoid this warning if everything is ok. The tricky part is doing this without impacting performance for ascii-only cases.
```

I get this on several joins, although I can swear, I use only unicode. After the join with this message in my code, the problem appears, i.e. the data.table before that does not have the problem, but after the join it develops the problem. But again, I did not manage fo reproduce it. 

Sorry for bothering, this seems some weird corner case.
