### ISSUE TITLE
full_join does not preserve data.tables

### ISSUE THREAD

**Issue by jcfisher** [hadley/dplyr#1042]
Hi,

I'm trying to merge two data.tables with full_join, and unfortunately the result is a data.frame.  There are simple workarounds -- use the data.table merge functions, pipe the result to data.table(), etc. -- but it would be great if full_join also worked for data.tables.

This issue is described in more detail on StackOverflow <a href=http://stackoverflow.com/questions/29280752/how-can-i-get-full-join-in-dplyr-to-preserve-data-tables>here</a>.

Thanks!

Jake

**Comment by hadley** [comment]
Can you please provide a minimal reprex inline?

**Comment by jcfisher** [comment]
set.seed(90088)
    dt1 <- data.table(id = 1:10, var1 = sample(20:30, 10, replace = T), key = "id")
    dt2 <- data.table(id = 1:10, var2 = sample(40:50, 10, replace = T), key = "id")
    
    both <- full_join(dt1, dt2)
    class(both)  # should be data.table
    # [1] "data.frame"
