### ISSUE TITLE
dplyr CRASHES R when joining on empty data frame. Error: not compatible with STRSXP

### ISSUE THREAD

**Issue by wsurles** [hadley/dplyr#1043]
Reproducible example:

```s
library(dplyr)
test <- data.frame() %>%
  left_join(data.frame(), by = 'id')
```
My real example is more complicated because I am joining in a database but this example will demonstrate the crash with no error message. 

It actually happens very naturally when using a selectize input to choose a filter value. When using the type ahead feature to find the correct value to filter on, the selectize input passes "" into R. My dplyr chain involves filtering a table and then joining another table to it for more info. So for a moment I have a zero length data frame and this crashes R. 

I'd be happy to change the way the selectize input passes data, or will probably add a validate statement. But this is still an issue worth noting. There is no error message when this happens as R is totally unresponsive. 

When my app is deployed on a linux server, I see 'Error: not compatible with STRSXP" while using the type ahead and then when a legit value is selected the chart shows up fine.  It does not crash when deployed, but while developing and testing its a big problem.

I have noticed other dplyr problems causing R to crash lately. Any advice on how to avoid this would also be helpful.

**Comment by AjarKeen** [comment]
When I run your example, I get:

    Error: cannot join on columns 'id' x 'id': index out of bounds

**Comment by wsurles** [comment]
Interesting. 

I am on dplyr 0.4.1 which is the latest release. And Mac OS X 10.9.4 (13E28) if that matters.

I get this lovely message in my Rstudio. 

![screen shot 2015-03-26 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/926795/6855234/13f2c3f6-d3bc-11e4-82c1-3f33f618196f.png)

**Comment by AjarKeen** [comment]
I can't reproduce your error with dplyr 0.4.1 or 0.4.1.9000 (installed from GitHub) on either Linux (CentOS 6.6) or Windows (Win7 SP1). Maybe post your SessionInfo so that someone can take a closer look. I'm not a dplyr dev, just a fellow user.

**Comment by romainfrancois** [comment]
I can confirm I'm getting the same results as @AjarKeen with the devel version: 

```
> library(dplyr)
> test <- data.frame() %>%
+   left_join(data.frame(), by = 'id')
Erreur : cannot join on columns 'id' x 'id': index out of bounds
```

@wsuries please open other issues about 

```
I have noticed other dplyr problems causing R to crash lately. Any advice on how to avoid this would also be helpful.
```

**Comment by wsurles** [comment]
I am on OS X 10.9.4

```s
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tidyr_0.2.0        rCharts_0.4.5      shinyStore_0.1.0   shiny_0.10.2       httr_0.5           dplyr_0.4.1        data.table_1.9.4   markdown_0.7.4     scales_0.2.4       RColorBrewer_1.0-5 ISOweek_0.6-2     
[12] lubridate_1.3.3    reshape2_1.4       devtools_1.6.1     RPostgreSQL_0.4    RMySQL_0.9-3       DBI_0.3.1          ggplot2_1.0.0     

loaded via a namespace (and not attached):
 [1] assertthat_0.1   chron_2.3-45     colorspace_1.2-4 digest_0.6.4     grid_3.1.2       gtable_0.1.2     htmltools_0.2.6  httpuv_1.3.2     lattice_0.20-29  lazyeval_0.1.10  magrittr_1.0.1   MASS_7.3-35     
[13] memoise_0.2.1    mime_0.2         munsell_0.4.2    parallel_3.1.2   plyr_1.8.1       proto_0.3-10     R6_2.0.1         Rcpp_0.11.3      RJSONIO_1.3-0    stringr_0.6.2    tools_3.1.2      whisker_0.3-2   
[25] xtable_1.7-4     yaml_2.1.13    
```
