### ISSUE TITLE
Error in UseMethod("group_by_") :    no applicable method for 'group_by_' applied to an object of class "character"

### ISSUE THREAD

**Issue by chriswweibo** [hadley/dplyr#1044]
I used the "COUNT" function when running my own examples, but this appeared.

I also randomly selected an embedded data set "CO2" for testing,  the same thing happened.

Actually,I updated some packages yesterday, which I think leads to this result.

My local updated info,which seems to be completely compatible with stated in the dplyr website:
R: 3.1.3(≥ 3.0.2)
Rcpp: 0.11.5(≥ 0.11.3), 
BH: 1.55.0-3(≥ 1.51.0-2)

Any suggestions?

**Comment by detournement** [comment]
same issue. just updated packages
