### ISSUE TITLE
Add possibility to create multiple tbls at once

### ISSUE THREAD

**Issue by tomasgreif** [hadley/dplyr#1047]
I frequently need to work with multiple tables in database. Instead of using `tbl(...)` for each table, I have  created a simple wrapper that creates `tbl` for each specified table and assigns a variable with the same name as database table to global environment (this is inspired by Oracle R Enterprise approach).

```
#' @export
#' @rdname tbls
#' @param src
#' @param tables
#' @param envir
#' @param tolower
tbls <- function(src, ..., tables, envir = globalenv(), tolower = TRUE) {
  lapply(tables, function(table) {
    table_name <- if (tolower) tolower(table) else table
    assign(table_name, tbl(src, ..., table), envir = envir)
  })
  TRUE
}
```

**Comment by hadley** [comment]
I think using `assign()` in this way is a bad idea - you're better off with `lapply()` plus a list.
