### ISSUE TITLE
distinct, top_n(1) different?

### ISSUE THREAD

**Issue by jzen188** [hadley/dplyr#1055]
Hi, 
I am not quite sure whether this has been mentioned before...

trial = data.frame(Group = c("BAS15664", "BAS15670","BAS15670","BAS15677","BAS1568"), NUM = 1:5)

I thought top_n(1) return the top number of rows given a parameter 1, which means each group first observation.

trial %>% group_by(Group) %>% top_n(1) 
trial %>% group_by(Group) %>% distinct()

**Comment by hadley** [comment]
I think this is because `distinct()` doesn't use the grouping vars: #1110.
