### ISSUE TITLE
Join without expansion

### ISSUE THREAD

**Issue by dougmitarotonda** [hadley/dplyr#1056]
In about 99% of my join use cases, I am left-joining two data frames together where if the resulting data frame has more rows than the original `x`, then there is something wrong with the `y` data. I have created a wrapper function that I call `safeJoin`, which checks for the number of rows before and after the join and errors if they are different. It has been really helpful defensive programming. I don't love having to have my own utils function outside of `dplyr` so I am wondering if this concept would be useful to others by having a `stop_expansion` argument added to the joins (default to `FALSE` to not break backward compatibility).

**Comment by matthieugomez** [comment]
I agree. I like the Stata syntax a lot: http://www.stata.com/manuals13/dmerge.pdf

The idea would be a new option that could take the following values:

~1 : each row in the master dataset matches at most one row in the using dataset.
1~ : each row in the using dataset matches at most one row in the master dataset.
1~1 : each row in the master dataset matches at most one row in the using dataset, and vice-versa.
~ : no restriction (default)

**Comment by krlmlr** [comment]
In addition, it would be great to be able to check if the join succeeded for each row in `x`, similar to `1~1` in @matthieugomez's suggestion but allowing `y` to have extra rows. (Assume that you filtered something but want to pull in attributes from a related table afterwards.) I asked a related question on SO but got no answer so far: http://stackoverflow.com/q/27940083/946850.

Integration into `dplyr` would be helpful if this operation was supported natively by the different back-ends. I don't see a way to translate these restrictions to SQL, and for data frames and data tables it essentially boils down to checking row counts. If the desired functionality can be implemented by using the public API of `dplyr` exclusively, there seems to be no compelling reason to integrate it *into* `dplyr` itself. I can't speak on behalf of the maintainers, though.

Another thing: If you insist on checking the validity of the join by counting rows, it must be materialized; normally `dplyr` does this only if necessary. I'm not sure if and how this affects query performance if any operations follow the join.

**Comment by matthieugomez** [comment]
If I understand correctly, you could check all rows in x are matched by starting with an anti join first and check that you obtain en empty dataset.
The way Stata handles these cases is by creating a variable, _merge, equal to 1 for rows in the master dataset only, 2 for rows in the using dataset only, and 3 for rows in both dataset.

**Comment by hadley** [comment]
I'd rather stick with the SQL definitions of joins (since that behaviour is well known) and encourage people to use `anti_join()`/`semi_join()` to check their work.

**Comment by matthieugomez** [comment]
I'm not arguing with the sql definition. an option to check 1m 11 mm m1 matching is orthogonal to the definition of sql join. Sorry to insist.

**Comment by matthieugomez** [comment]
Maybe dplyr could return a message with the name on variables matched + "the join turned out to be 1:m" (or m:1 1:1)
