### ISSUE TITLE
dplyr and redshift idiosyncrasies 

### ISSUE THREAD

**Issue by mtreadwell** [hadley/dplyr#1059]
This issue is similar to another open issue I have which is issue #962. It seems to stem from small differences between the query sent by dplyr when using the PostgreSQL driver and what is expected by Redshift.

ann %>% group_by(col1,col2,col3) %>% mutate(r = min_rank(desc(col4)))

gives this error:

RS-DBI driver: (could not Retrieve the result : ERROR:  cache lookup failed for operator 0

Using show_query(), I see this line in the select statement
rank() OVER (PARTITION BY ("col1", "col2", "col3") ORDER BY "col4" DESC) AS "r"

If you visit the Redshift documentation page you can see that the problem is caused by the parentheses around the expressions list after PARTION BY:

 PARTITION BY ("col1", "col2", "col3")

The parentheses are not needed and when I send the query without the parentheses around the expressions there is no error and the result is correct.

Is there a planned fix for these differences since you seem to plan on supporting Redshift as laid out in issue #15? Is there some workaround I could find in the meantime?

**Comment by hadley** [comment]
Unfortunately I don't have the resources to support more database backends. But there's a vignette that describes how to create your own, and I'm happy to help out.
