### ISSUE TITLE
filter, slice, arrange dropping attributes

### ISSUE THREAD

**Issue by DavisBrian** [hadley/dplyr#1064]
I'm not sure if this is by design or a bug.

I would expect that since filter and slice are subsets of the original data frame that all of the original data frames attributes would go along with it.  Similarly since arrange is a reordering of the data I would expect it to keep attributes, much like group_by and select do.

```R
library(dplyr)

dat <- as_data_frame(iris)
attr(dat, "meta") <- c("This is important")

# drops meta attributes
dat %>% filter(Species == "setosa") %>% attributes
dat %>% slice(1:50) %>% attributes
dat %>% arrange(Sepal.Width) %>% attributes


# keeps meta attribute
dat %>% group_by(Species) %>% attributes
dat %>% select(Petal.Length, Petal.Width, Species)  %>% attributes
```

**Comment by hadley** [comment]
@romainfrancois can we also preserve all data frame attributes? 

@DavisBrian do you expect `summarise()` to keep attributes too?

**Comment by DavisBrian** [comment]
@hadley I would not expect summarise() to keep attributes.  In my mind summarise() represents different data.  The other functions are more or less just subsets and orderings of the same data.  Or at least thats my use case.

**Comment by eamcvey** [comment]
In my experience, this issue often creates problems using lubridate and dplyr together, which is a thing I'm always wanting to do!

**Comment by hadley** [comment]
Should be fixed the dev version

**Comment by hadley** [comment]
Oops, wrong issue.

**Comment by romainfrancois** [comment]
Ah. Might have closed it too soon. So @hadley do we want to keep attributes for `summarise` too ?

**Comment by hadley** [comment]
Hmmmmmmmm, for summarise I think we should be able to rely on the summary function doing the right thing. (So that might require preserving attributes in the hybrid handlers)

**Comment by romainfrancois** [comment]
Sure, but this only concerns attributes of the columns right ?
This is more about some meta attributes of the data frame itself, should they be propagated to the resulting data frame. 
Or perhaps I did not understand you.

**Comment by hadley** [comment]
Oh, sorry yes :/ So summarise should preserve these attributes.
