### ISSUE TITLE
RStudio crashes on inner_join()

### ISSUE THREAD

**Issue by jwpestrak** [hadley/dplyr#1066]
A work colleague's RStudio session crashes after he attempts to use `inner_join()`. 

Here's the screenshot:
![inner_join_rstudio_crash_screenshot](https://cloud.githubusercontent.com/assets/3246445/7098767/6a1f8d74-df9a-11e4-8c5c-f591b8f54e70.png)

Let me know if I can provide any additional information of potential use.

**Comment by kevinushey** [comment]
You'll need to update Rcpp.

**Comment by jwpestrak** [comment]
That did the trick. Thanks.
