### ISSUE TITLE
Put columns to front 

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#1068]
It would be nice to have a function that puts certain columns to front. For instance, 

```
movefirst(iris, starts_with("Petal"))
```

would put all columns with names that starts with Petal to front, leaving untouched the order of the remaining variables

**Comment by abresler** [comment]
Agree!

**Comment by romainfrancois** [comment]
You can do this: 

```
select( iris, matches( "Petal" ), everything() )
```

**Comment by matthieugomez** [comment]
That's good, thanks.

**Comment by romainfrancois** [comment]
Could be as simple as : 

```
movefirst <- function(data, ...) select( data, ..., everything() )
```

Perhaps slightly more involved if you also want `movefirst_`

**Comment by kioja** [comment]
Yes I agree, but, by the same argument, `rename` should not exist:
    iris %>% select(Sepal.Length2 = Sepal.Length, everything())

**Comment by matthieugomez** [comment]
I agree, but, by the same argument, rename should not exist:

    iris %>% select(Sepal.Length2 = Sepal.Length, everything())
