### ISSUE TITLE
enable replacement of values

### ISSUE THREAD

**Issue by stefanfritsch** [hadley/dplyr#1078]
Hi,

currently dplyr is not really convenient if you want to replace specific values in a data.frame based on a condition on the obs. Let's say you want to set variable b to -a if variable a is <0.

```R
dt[a<0, b := -a]
```

AFAIK there is no easy way in dplyr. Using `ifelse` in mutate works but becomes really unwieldy if there is more than one column, e.g.

```R
dt[a<0, 
   `:=`(b=-a, 
        d=sqrt(-a+d))]
```

This would be helped immensely by a "where" (I know, that's not a verb; you were brave enough to change override in MASS, so perhaps "subset"?) analogue to group_by, that instead limits effects to a subset of the table.

```R
dt %>%
  subset(a<0) %>%
  mutate(b=-a,
         d=sqrt(-a+d)) %>%
  unsubset
```

Is that a realistic possibility or is it an absolute no-go? :)

Ciao,
Stefan

**Comment by hadley** [comment]
See #631
