### ISSUE TITLE
Copy parameter for tbl_sqlite and left/right_join

### ISSUE THREAD

**Issue by akaever** [hadley/dplyr#1085]
Hi,

I would like to perform a left_join for a small local data.frame (x) and a large tbl_sqlite table (y). For this purpose, the smaller table needs to be copied into the SQLite backend. 

However, copy=TRUE allows only to copy the contents of the second table (y) into the first backend (if I am not mistaken), which is very inefficient here. And right_join is not supported by SQLite. 

There are some workarounds, but it would be very useful to have a copy-parameter which allows to automatically copy from x to y or vice versa (e.g. copy="x" or copy="y").

Thanks for your efforts!

**Comment by hadley** [comment]
Just do a right join?

**Comment by hadley** [comment]
Ooops, finished reading your issue.

**Comment by hadley** [comment]
Hmmmm, I'd prefer not to implement this just to work around a lack in SQLite. It shouldn't be too hard to write your own wrapper that does the copy.
