### ISSUE TITLE
LIMIT and OFFSET for tbl_src

### ISSUE THREAD

**Issue by kismsu** [hadley/dplyr#1087]
Hi, I saw that this was already discussed in the context of ```slice()```, but it might be a good idea to have  ```LIMIT``` and ```OFFSET``` option. This nothing more than 

```r
dbSendQuery(data$query$con, paste(data$query$sql, "LIMIT", length, "OFFSET", start))
```
as an additional method (or an arguments) for Query class.

**Comment by hadley** [comment]
Unfortunately LIMIT and OFFSET variable is rather variable across databases.
