### ISSUE TITLE
Add Support For Presto

### ISSUE THREAD

**Issue by cosinequanon** [hadley/dplyr#1089]
Since we now have DBI support for Presto with https://github.com/prestodb/RPresto, we should integrate this with dplyr. I have working code but I need to clean it up before sending a PR which should happen later this week.

**Comment by hadley** [comment]
I was going to file exactly the same issue on the prestodb repo ;)  There's a vignette on how to get started at http://cran.r-project.org/web/packages/dplyr/vignettes/new-sql-backend.html

**Comment by cosinequanon** [comment]
@hadley would the code go in this repo or somewhere else? I noticed not all the supported backends are contained in dplyr, e.g. MonetDB

**Comment by hadley** [comment]
All new backends should go in their own packages - it makes testing easier since (e.g.) you have the infrastructure to test with a running prestodb instances and I don't.

**Comment by cosinequanon** [comment]
Got it, thanks. Seems like this is the wrong place to track this issue then.
