### ISSUE TITLE
Using unnamed arguments in do() results in undesirable type coercion of complex outputs

### ISSUE THREAD

**Issue by stephen-frank** [hadley/dplyr#1090]
The documentation in `?do` includes a neat example where `do` is used to create and compare several linear models:

```r
by_cyl <- group_by(mtcars, cyl)
models <- by_cyl %>% do(mod = lm(mpg ~ disp, data = .))
models
models[[2]]
```

This works great (and is awesome!) as long as named arguments are used in `do`. But if unnamed arguments are used (the "build your own output data frame" approach), undesirable type coercion of the embedded models causes loss of data when the data frame is reassembled. Example:

```r
by_cyl <- group_by(mtcars, cyl)
models <- by_cyl %>% do({
  out <- list(mod= lm(mpg ~ disp, data = .))
  attr(out, "row.names") <- .set_row_names(1L)
  class(out) <- c("tbl_df", "data.frame")
  out
  # ok up to here; use print(out) within this code block to verify
})
models[[2]]
```
Note the loss of the "lm" class and associated loss of data.

(Note that I'm using the same approach that the `do` function uses to avoid type coercion when building the output data frame; see [this code](https://github.com/hadley/dplyr/blob/d2b7265d97b1f1eae9b95b8b5d4f9f59e40ed497/R/dataframe.R#L305-311).)

I *think* but can't be sure that I've traced the source of the type coercion back to a call to `rbind_all` within the `label_output_dataframe` function [here](https://github.com/hadley/dplyr/blob/9eb26fcd9076eb36ebb378a218c66294113d4318/R/do.r#L104). (Digging through the debug of `do` gets pretty involved for an outsider...) Maybe this is related to [issue 594](https://github.com/hadley/dplyr/issues/594)?

**Comment by stephen-frank** [comment]
In case you are wondering why the heck I would want to do this... the reason is that I have a chain of model fitting actions occurring for each subgroup of my data, and I want to be able to return relevant information about each action. A simple example is applying principle components analysis and then fitting a model: I want to return both the rotation matrix from PCA and the model. Such as...

```r
d <- data.frame(MODEL.GROUP = c(1,1,1,2,2,2), w = 1:6, x = 6:1) %>% mutate(y = x + 2*w)

# Doesn't work
m <- d %>%
  group_by(MODEL.GROUP) %>%
  do({
    # Data
    Y <- select(., y)
    X <- select(., -y, -MODEL.GROUP)
    
    # PCA rotation matrix
    rot <- prcomp(X)$rotation
          
    # Rotate X
    X <- (as.matrix(X) %*% rot) %>% as.data.frame() %>% tbl_df()
    
    # Assembled data
    Z <- cbind(Y, X)
    
    # Fit model
    mod <- do.call('lm', list(y ~ PC1 + PC2, data=Z))
    
    # Return
    out <- list(rotation=rot, model=mod)
    attr(out, "row.names") <- .set_row_names(1L)
    class(out) <- c("tbl_df", "data.frame")
    out
  })

cat('---Undesired Behavior---\n')
print(m)
print(m$rotation) # Notice undesired coercion from matrix with loss of data
print(m$model)    # Notice undesired coercion from class 'lm' with loss of data

# Works, but data frame has embedded data frames
m <- d %>%
  group_by(MODEL.GROUP) %>%
  do(mod = {
    # Data
    Y <- select(., y)
    X <- select(., -y, -MODEL.GROUP)
    
    # PCA rotation matrix
    rot <- prcomp(X)$rotation
          
    # Rotate X
    X <- (as.matrix(X) %*% rot) %>% as.data.frame() %>% tbl_df()
    
    # Assembled data
    Z <- cbind(Y, X)
    
    # Fit model
    mod <- do.call('lm', list(y ~ PC1 + PC2, data=Z))
    
    # Return
    out <- list(rotation=rot, model=mod)
    attr(out, "row.names") <- .set_row_names(1L)
    class(out) <- c("tbl_df", "data.frame")
    out
  })

cat('---Desired Behavior, Undesired Stucture---\n')
print(m)
print(m$mod[[1]]$rotation) # Notice class is preserved
print(m$mod[[1]]$model)    # Notice undesired coercion from matrix with loss of data
```

If I did this with named arguments to get output columns "rotation" and "model", it seems like I would have to repeat code blocks to re-create the relevant outputs, since I need the rotation matrix in the model fitting part of the code.

**Comment by hadley** [comment]
I'm pretty sure you actually want: `out <- list(mod= list(lm(mpg ~ disp, data = .)))` - i.e. you want one column to be a list containing linear models. It's a bit easier to do this with `data_frame()`:

```R
by_cyl <- group_by(mtcars, cyl)
models <- by_cyl %>% do(
  data_frame(mod = list(lm(mpg ~ disp, data = .)))
)
models[[2]]
```

To make it more clear:

```R
mod <- lm(mpg ~ wt, data = mtcars)
length(mod)
data_frame(x = 1, mod = mod)
data_frame(x = 1, mod = list(mod))
```

**Comment by stephen-frank** [comment]
Ah, I see. I missed the nested lists, but that does make sense.
