### ISSUE TITLE
data_frame(recycle(1:2),1:10) ?

### ISSUE THREAD

**Issue by nicolasCoutin** [hadley/dplyr#1093]
What if `data_frame` had a convenience function `recycle()` to allow for recycling?

```r
data_frame(recycle_aabb(1:2),1:10)    # equivalent to  rep(1:2, each = 5)
# 1  1  1
# 2  1  2
# 3  1  3
# 4  1  4
# 5  1  5
# 6  2  6
# 7  2  7
# 8  2  8
# 9  2  9
# 10 2 10
```

```r
data_frame(recycle_abab(1:2),1:10)    # equivalent to  rep(1:2, times = 5)  &  rep(1:2, length.out = 10)
# 1  1  1
# 2  2  2
# 3  1  3
# 4  2  4
# 5  1  5
# 6  2  6
# 7  1  7
# 8  2  8
# 9  1  9
# 10 2 10
```

This would be very friendly to future me in terms of code readability. I don't have to remember what kind of `rep` call does what etc.. It's clear that I recycle by filling-in serially (`aabb`) or alternating (`abab`). I think of this as an analogous helper to `dplyr::desc()`.

Now the cool bit is if it could be extendable to _any pattern_ you write after `recycle_`. That is if I could just write any pattern and it would just work:

```r
data_frame(recycle_3a2b(1:2),1:10)    # equivalent to  rep(c(rep(1,3),rep(2,2)),2)
# 1  1  1
# 2  1  2
# 3  1  3
# 4  2  4
# 5  2  5
# 6  1  6
# 7  1  7
# 8  1  8
# 9  2  9
# 10 2 10
```

This also means that you can check if the pattern makes sense relative to the maximum column length by factoring and throw an error if the pattern doesn't make sense otherwise it computes the result of recycling `1:2` with the `3a2b` pattern. I think this also generalizes to larger patterns: `3a2b1c7d9e`.

Wondering what @hadley & @romainfrancois think of this?

**Comment by romainfrancois** [comment]
ping @kevinushey

**Comment by kevinushey** [comment]
I don't like the idea of building some tiny meta-language into the name of the function called. I could see some argument for recycle wrappers, though, e.g.

    data_frame(
        x = recycle_each(1:2),
        y = recycle_whole(1:2),
        z = 1:10
     )

with this producing the same output as

    data_frame(
        x = rep(1:2, each = 5),
        y = rep_len(1:2, 10),
        z = 1:10
     )

**Comment by hadley** [comment]
I'm not in love with this idea, but we can iterate in the PR.
