### ISSUE TITLE
Creating a new tbl_df with the same syntax as data.frame()

### ISSUE THREAD

**Issue by rcorty** [hadley/dplyr#1096]
It might be useful if one could create a new tbl_df this way:

    x <- tbl_df(a = rnorm(10), b = rnorm(10))

rather than the existing way, which is:

    x <- tbl_df(data.frame(a = rnorm(10), b = rnorm(10))

**Comment by romainfrancois** [comment]
You just need `data_frame`, i.e.: 

```
> data_frame(a = rnorm(10), b = rnorm(10)) %>% str
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	10 obs. of  2 variables:
 $ a: num  0.2887 0.0439 -1.9195 -0.7672 0.2583 ...
 $ b: num  1.8049 0.5701 0.841 0.0542 0.5778 ...
```
