### ISSUE TITLE
select_vars

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#1100]
I'd like an extension of select_vars that accepts a dataframe as the first argument and returns a character vector.

`select_vars(iris, starts_with("Petal"))`

would be equivalent to 

`select(names(iris), starts_with("Petal"))`

**Comment by gwerbin** [comment]
Forgive me if I'm being slow, but isn't that just what `select` does?

**Comment by matthieugomez** [comment]
`select` accepts a dataframe and returns a dataframe while `select_vars` accepts a character vector and returns a character vector.

**Comment by hadley** [comment]
Doesn't seem like a big win to me - it only saves one character!
