### ISSUE TITLE
More descriptive error message needed if column names are NA

### ISSUE THREAD

**Issue by holgerbrandl** [hadley/dplyr#1101]
names(iris)[1] <- NA
    iris %>% filter(Species=="setosa")
    iris %>% arrange(Species)

Both calls give

    Error in if (any(names2(x) == "")) { 
    missing value where TRUE/FALSE needed

and it is not clear that the problem is a column which is not used at all in the method call. It should rather say something like
"Error: Column(s) with missing name(s) in input table. To use dplyr all columns are required to have a name."

The problem seems related to https://github.com/hadley/tidyr/issues/68

**Comment by romainfrancois** [comment]
And the error leads directly to `as_data_frame`: 

```
> traceback()
15: as_data_frame(data) at tbl-df.r#71
14: tbl_df(.data) at manip.r#24
13: filter_(tbl_df(.data), .dots = dots)
12: as.data.frame(filter_(tbl_df(.data), .dots = dots)) at dataframe.R#198
11: filter_.data.frame(.data, .dots = lazyeval::lazy_dots(...)) at manip.r#24
10: filter_(.data, .dots = lazyeval::lazy_dots(...)) at manip.r#18
9: filter(., Species == "setosa")
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: iris %>% filter(Species == "setosa")
> iris %>% filter(Species=="setosa") %>% str
Error in if (any(names2(x) == "")) { :
  valeur manquante là où TRUE / FALSE est requis
>
> as_data_frame(iris)
Error in if (any(names2(x) == "")) { :
  valeur manquante là où TRUE / FALSE est requis
```

**Comment by romainfrancois** [comment]
Now getting this: 

```
> names(iris)[1] <- NA
> iris %>% filter(Species=="setosa")
Error: All elements must be named
> iris %>% arrange(Species)
Error: All elements must be named
```

@holgerbrandl does that work for you.

**Comment by holgerbrandl** [comment]
Much better, although I personally find "elements" rather unspecific. Why not "columns"?

**Comment by romainfrancois** [comment]
Sure. Would you send us a pull request that @hadley can have a look at.

**Comment by holgerbrandl** [comment]
done with https://github.com/hadley/dplyr/pull/1271
