### ISSUE TITLE
Killing a query results in "close resultSet before continuing"

### ISSUE THREAD

**Issue by seandavi** [hadley/dplyr#1103]
I suspect that this is at the level of DBI/driver and not dplyr, but interrupting a query results in:

```r
Error in .local(conn, statement, ...) :                                                                                                    ...: optional arguments to ‘FUN’.
   connection with pending rows, close resultSet before continuing                                                                     
```

I did not find an obvious way to close the resultSet without reaching into the connection itself (and that didn't appear to do the trick, either).  Would it make sense to implement a dbClearResult on the src_XXX classes?

**Comment by hadley** [comment]
This is most likely a bug in the underlying DBI backend.

**Comment by yenusu** [comment]
try using dbGetQuery() insted of dbSendQuery(),

it works fine

`my_vin <- dbGetQuery(con, "SELECT V_IN from nodestatus where V_IN >0")`
