### ISSUE TITLE
numeric overflow might need warning

### ISSUE THREAD

**Issue by ajdamico** [hadley/dplyr#1108]
reproducible example

	library(dplyr)
	library(readr)

	tf <- tempfile()
	download.file( "http://downloads.cms.gov/FILES/HCRIS/HOSP10FY2013.zip" , tf , mode = 'wb' )

	z <- unzip( tf , exdir = tempdir() )
	nmrc <- read_csv( grep( 'NMRC' , z , value = TRUE ) , col_names = F )

	# Warning message:
	# In sum(nmrc$X5, na.rm = TRUE) : integer overflow - use sum(as.numeric(.))
	sum( nmrc$X5 , na.rm = TRUE )

	# now it works
	sum( as.numeric( nmrc$X5 ) , na.rm = TRUE )

	# this sum is missing despite the na.rm = TRUE
	nmrc %>% summarize( mean( X5 , na.rm = TRUE ) , sum( X5 , na.rm = TRUE ) )

	# here's the fix for this case
	nmrc$X6 <- as.numeric( nmrc$X5 )
	nmrc %>% summarize( mean( X6 , na.rm = TRUE ) , sum( X6 , na.rm = TRUE ) )

**Comment by hadley** [comment]
@romainfrancois could you please take a look? If it's a lot of work we can push off until 0.5

**Comment by hadley** [comment]
Need to get 0.4.2 out ASAP for CRAN, so lets push this off

**Comment by romainfrancois** [comment]
Now getting: 

```
> nmrc %>% summarize( mean( X5 , na.rm = TRUE ) , sum( X5 , na.rm = TRUE ) )
Source: local data frame [1 x 2]

  mean(X5, na.rm = TRUE) sum(X5, na.rm = TRUE)
1                7152239                    NA
Warning message:
In summarise_impl(.data, dots) : integer overflow - use sum(as.numeric(.))
```

The alternative would be I guess to automatically promote the result to a numeric vector. We do calculate the `double` anyway, but when we see that it can't fit an `int` we just go with `NA`.
