### ISSUE TITLE
distinct_.grouped_df selects only one instance of each combination of grouping variables

### ISSUE THREAD

**Issue by bergsmat** [hadley/dplyr#1110]
Consider:

```
> library(dplyr)
> library(magrittr)
> x <- data.frame(id=c(1,1),val=c('a','b'))
> x %>% group_by(id) %>% distinct
Source: local data frame [1 x 2]
Groups: id

  id val
1  1   a
> x %>% group_by(id) %>% unique
Source: local data frame [2 x 2]
Groups: id

  id val
1  1   a
2  1   b
```
The help for ```distinct``` just says it is an efficient version of ```unique```, but clearly they are different for ```grouped_df```, with ```distinct``` stripping repeats of keys not just records.  Seems surprising and possibly dangerous.  If intended, it is worth a mention in the help or in the vignette e.g. http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html .  

Using dplyr ref='c0b28a93dfbebee0a7e5f8aa17d2474ab773e132' on Windows 8.

**Comment by romainfrancois** [comment]
Hmm. That's because at least the ay it's implemented, passing no argument to distinct on a grouped data frame means get distinct values of the grouping variables, which is different from getting distinct values using all columns, which is what the non grouped version does. 

We'd need I guess to either change the logic in this function: 

```
distinct_.grouped_df <- function(.data, ..., .dots) {
  groups <- lazyeval::as.lazy_dots(groups(.data))
  dist <- distinct_vars(.data, ..., .dots = c(.dots, groups))

  grouped_df(distinct_impl(dist$data, dist$vars), groups(.data))
}
```

or internally here: 

```
    if( !vars.size() ){
        vars = df.names() ;
    }
    DataFrameVisitors visitors(df, vars) ;
```

**Comment by bergsmat** [comment]
Actually, the interpretation "get distinct values of the grouping variables" would be fine if only grouping variables were returned.  I like the broader understanding (analog to unique).  With either, there are quick ways to generate the other.  Thanks for considering.

**Comment by alexfun** [comment]
Please add this behaviour of distinct on grouped data frames to the helpfile. Thanks.

http://stackoverflow.com/questions/31259518/why-does-dplyrdistinct-behave-like-this-for-grouped-data-frames#31259587

**Comment by hadley** [comment]
Maybe distinct should only keep variables that are explicitly mentioned? I think keeping all the variables is confusing. We could have an option to revert to the old behaviour. Related to #1150
