### ISSUE TITLE
Make build_query a generic and implement methods

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/dplyr#1114]
`build_query()` calls `sql_select()` to pull together the SQL statement that is passed to a `Query` constructor. The `sql_select()` method is generic and can have connection specific methods. However, `build_query()` is not. Would it make sense to make this an exported generic function so that downstream dependencies are less problematic?

**Comment by hadley** [comment]
The point of this method is to do all the complicated NSE stuff so that database backends don't have to.  What would you need from the generic?

**Comment by imanuelcostigan** [comment]
I see you have deprecated `build_query` from master vs. v0.4.3 as well as making quite a few other changes. I will wait to see what you end up and if necessary, update request.
