### ISSUE TITLE
Feature Request: convert columns to classes 

### ISSUE THREAD

**Issue by kkmann** [hadley/dplyr#1115]
Hey,

I often end up manually converting single columns of my data because an Excel import did not recognize the types correctly (or a column is logical, which is not supported by readxl::read_excel()), i.e. doing something like data$var0 <- as.logical(data$var0) etc. 

Would it not be great, to have a verb like 'reclass' doing something like reclass(data, var0 = "logical", ...) where ... gets passed to each conversion function (think of the many options for dates etc.).

**Comment by hadley** [comment]
I think in this case it would be just better if readxl read logical columns correctly. Otherwise it's a fairly straightforward apply operation:

```R
df[c("var1", "var2")] <- lapply(df[c("var1", "var2")], as.logical)
```

A wrapper for this would seem more natural in purrr.
