### ISSUE TITLE
left_join by column that differs in type between joined data.frames crashes session

### ISSUE THREAD

**Issue by cezden** [hadley/dplyr#1119]
Simple test case:

t1 <- data.frame(a=1:10, b=LETTERS[1:10])
t2 <- t1 %>% mutate(a=as.character(a)) %>% rename(b_ = b)
left_join(t1,t2)

causes:

Joining by: "a"

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

Traceback:
 1: .Call("dplyr_left_join_impl", PACKAGE = "dplyr", x, y, by_x,     by_y)
 2: left_join_impl(x, y, by$x, by$y)
 3: left_join.tbl_df(tbl_df(x), y, by = by, copy = copy, ...)
 4: left_join(tbl_df(x), y, by = by, copy = copy, ...)
 
-------------------------------

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1

loaded via a namespace (and not attached):
[1] DBI_0.3.1      Rcpp_0.11.5    assertthat_0.1 magrittr_1.5   parallel_3.1.3
[6] tools_3.1.3

**Comment by romainfrancois** [comment]
This appears to have been fixed in the development version; Please reopen otherwise. 

```
> t1 <- data.frame(a=1:10, b=LETTERS[1:10])
> t2 <- t1 %>% mutate(a=as.character(a)) %>% rename(b_ = b)
> left_join(t1,t2)
Joining by: "a"
Error: cannot join on columns 'a' x 'a': Can't join on 'a' x 'a' because of incompatible types (character / integer)
```
