### ISSUE TITLE
dplyr do() crashes if it returns a complex value

### ISSUE THREAD

**Issue by jakeyeung** [hadley/dplyr#1120]
I want to use do() to transform data into complex values, but it is consistently crashing when I try to do so. 

Example:
```
library(dplyr)

ComplexFunction <- function(dat){
  x.trans <- exp(1i)
  return(data.frame(x.trans = x.trans))
}

test.df <- data.frame(x = seq(20), labs = rep(c("a", "b"), 10))

test.crashes <- test.df %>%
  group_by(labs) %>%
  do(ComplexFunction(.))
```

Running this causes RStudio to crash. It seems to crash when it tries to return a complex value.

Any suggestions on how to handle this?

**Comment by hadley** [comment]
This works for me. Can you please try the dev version?

**Comment by jakeyeung** [comment]
Thanks, running the code in the dev version solves it.

    dev_mode()
    
    devtools::install_github("hadley/lazyeval")
    devtools::install_github("hadley/dplyr")
    
    library(dplyr)
    
    ComplexFunction <- function(dat){
      x.trans <- exp(1i)
      return(data.frame(x.trans = x.trans))
    }
    
    test.df <- data.frame(x = seq(20), labs = rep(c("a", "b"), 10))
    
    test.crashes <- test.df %>%
      group_by(labs) %>%
      do(ComplexFunction(.))
    
    dev_mode()
