### ISSUE TITLE
full_join fill NA option similar to reshape2:::dcast fill argument

### ISSUE THREAD

**Issue by jwpestrak** [hadley/dplyr#1129]
*(possible) enhancement 

Apologies if this functionality exists already, but after reading through the `dplyr` source on GitHub and searching Google, I have not yet found a way to pass a non-NA value in place of NA for `full_join()`.

That is, for fields in the data frame which results from a `full_join()` call, it'd be great to pass in a different value for NAs; similar to `reshape2:::dcast(, fill = 0)` (for example).

**Comment by hadley** [comment]
Unfortunately it's not possible because there are many possible field types (character, integer, date etc)
