### ISSUE TITLE
Binary hybrid evaluation handlers

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#113]
We now have all the scaffolding to add binary hybrid handlers, e.g. `+`, `- `, `==` at least handling scalar values, so that we can hybridify something like this: 

`sum( x < 3 )`

We know how to handle `sum`, but since we can't hybrid `x<3` the hybrid version of `sum` is not used.

**Comment by hadley** [comment]
I'm going to close this for now. I think we should come back to again in the future if we look for potential performance gains.
