### ISSUE TITLE
all.equal(tbl_df, tbl_df) does not print newlines

### ISSUE THREAD

**Issue by daattali** [hadley/dplyr#1130]
When comparing two `tbl_df` objects, all their differences are listed as one continuous string without line breaks.

```
library(dplyr)
a <- data_frame(x = 1)
b <- data_frame(x = 2)
all.equal(a, b)
```

Output:

```
[1] "Rows in x but not y: 1Rows in y but not x: 1"
```

dplyr v0.4.1

**Comment by hadley** [comment]
This needs a few internal changes: BoolResult class needs to store a character vector rather than a std::string in order to return multiple differences.

**Comment by romainfrancois** [comment]
It does: 

```
> a <- data_frame( x = c(1,1,2,3,6) )
> b <- data_frame( x = c(1,2,3,4,5) )
> all.equal( a, b )
[1] "Rows in x but not y: 5Rows in y but not x: 5, 4Rows with difference occurences in x and y: 5, 4, 5, 1"
```

@daattali's point I guess is that it's hard to read because sentences are all stuck together. 

I've added a `.` now.

**Comment by hadley** [comment]
This seems good enough for now
