### ISSUE TITLE
do(data, fun) should drop value if fun returns NULL

### ISSUE THREAD

**Issue by antoine-lizee** [hadley/dplyr#1131]
This was a very handy feature of plyr::ddply, and it would be great to have it with do(). The main advantage is that you can do something like:
```
myFun <- function(dfi) {
  if (any(is.na(dfi$myVariable))) {
    return(NULL)
  }
  return(data.frame(...))
}
```
...without the need to build an empty data.frame in the first case.

**Comment by hadley** [comment]
(This is separate to `bind_rows()` issues as the check occurs in `do.data.frame()`)

**Comment by hadley** [comment]
The plan is to replace `do()` with a more general framework that uses tidyr and purrr.
