### ISSUE TITLE
A data.frame gives different results if it is formatted with `tbl_df` or not.

### ISSUE THREAD

**Issue by chasset** [hadley/dplyr#1139]
Hello Hadley,
I would like first to thank you for this great package. It saves me much more than time.
I notice that a command gives different results using `tbl_df` or not.
Suppose first that you use a data.frame like `iris`. Your purpose is to work on the first column: `Sepal.Length`. You have two ways to access this column, depending if you know the name of the column or not. Each command gives a vector of `numeric`s.
```
class(iris$Sepal.Length)
## "numeric"
class(iris[,1])
## "numeric"
```
But, now, you would like to take the advantage of playing with `dplyr` and you format your data.frame using `tbl_df`. Now, the two ways give different results. The first one gives you as usual a vector of `numeric`s, but the second one is different : it is a data.frame.
```
i <- iris %>% tbl_df
class(i$Sepal.Length)
## "numeric"
class(i[,1])
## "tbl_df"     "data.frame"
```
What do you think of it?
Best regards,
Pierre-Olivier

**Comment by hadley** [comment]
Use `iris[[1]]` to always get the first column.

**Comment by chasset** [comment]
Thanks
