### ISSUE TITLE
[dplyr] group_by%>%do

### ISSUE THREAD

**Issue by chang648** [hadley/dplyr#1140]
I keep getting the following error when I used group_by%>% but it works when I used the ddply.  Anyone knows if it is a bug?!
Error in is.data.frame(x) : 
  (list) object cannot be coerced to type 'double'
try<-function(x){
a<-sd(x[,"mpg"])
b<-sum(x[,"mpg"])
ha<-data.frame(b,a)
return(ha)
}
mtcars%>%group_by(cyl)%>%do(try(.))
ddply(mtcars,.(cyl),try)

**Comment by akhmed-u** [comment]
The following works for me:
```
try<-function(x)
{
  a <- sd(x$mpg) 
  b <- sum(x$mpg)
  ha <- data.frame(b,a)
  return(ha)
}
mtcars %>% group_by(cyl) %>% do( try(.) )
```
