### ISSUE TITLE
mutating, arranging, summarizing empty data frames fails with "not compatible with STRSXP"

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1142]
To reproduce:

```{r}
data.frame() %>% mutate()
## Error: not compatible with STRSXP

data.frame() %>% arrange()
## Error: not compatible with STRSXP

data.frame() %>% summarize()
## Error: not compatible with STRSXP
```
The `_` versions also fail.

`select`, `filter`, `group_by` work OK.

Related: [\[ fails inside mutate](https://github.com/hadley/dplyr/issues/912)

**Comment by romainfrancois** [comment]
I fixed `mutate` for the example above. Not sure though how to deal with this: 

```
data.frame() %>% mutate( x = 2L )
```

**Comment by hadley** [comment]
@romainfrancois shouldn't that be an error because the output is a different length to the input?

**Comment by hadley** [comment]
Another good test case would be `data.frame() %>% mutate(x = numeric())`

**Comment by romainfrancois** [comment]
Now I get: 

```
> data.frame() %>% mutate(x = 2L)
[1] x
<0 rows> (or 0-length row.names)
```

Because a length 1 result in `mutate` is recycled, so here recycled 0 times, but I can make this special case an error if that makes more sense.

**Comment by hadley** [comment]
Ah, I forgot about that principle. I think either way is probably ok, but recycling to length 0 is a little less frustrating for people.

**Comment by romainfrancois** [comment]
In that case I think we can close this.

**Comment by abresler** [comment]
I think this issue has returned with some of the new updates.  I have empty data_frames that I am trying to bind and it now returns the dreaded

```
not compatible with STRSXP 
```

**Comment by hadley** [comment]
@abresler could you please file a new issue with a minimal reprex
