### ISSUE TITLE
Find all unique combinations

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1150]
Something that's an efficient equivalent of

```R
mtcars %>% select(vs, am) %>% distinct() %>% arrange(vs, am)
```

(sorting should be optional)

@lionel- or is this what you were thinking of?

**Comment by lionel-** [comment]
hmm I don't think so. In this example you find all unique combinations of some variables.

But what I need is a function that checks that all selected variables have unique values in the same rows, and then make a data frame with the distinct values. A vector of identifiers could be given as an optional additional check.

With typical multilevel data, this would allow to separate group-level data (repeated over individual observations) into their own data frame.

**Comment by hadley** [comment]
Maybe this should be implemented with additional arguments to `distinct()`?

**Comment by lionel-** [comment]
> Maybe distinct should only keep variables that are explicitly mentioned?

That'd be great. I agree that the current behaviour is confusing.

In addition, how about a verb to select all columns who have the same pattern of distinctness as a given variable?

The following would return a df with cyl, cyl2 and cyl3:
```r
mtcars %>%
  mutate(cyl2 = 2 * cyl, cyl3 = 3 * cyl) %>%
  distinct(across(cyl))
```

**Comment by lionel-** [comment]
Maybe better named `within()` or `over()`.

**Comment by hadley** [comment]
I think this is handled in tidyr now
