### ISSUE TITLE
Renaming multiple variables prefixes column positions instead of names

### ISSUE THREAD

**Issue by holstius** [hadley/dplyr#1156]
It seems like `select()` has a great intention here. Per `?select`,

    # Renaming multiple variables uses a prefix:
    select(iris, petal = starts_with("Petal"))

This results in names `petal1` and `petal2`. Why not `petalPetal.Length` and `petalPetal.Width`?

If `select()` retained the column *names*, instead of column positions, I think it would be much more useful for prefixing prior to joins. For example:

    stopifnot(require("Lahman"))
    
    batting_df <- tbl_df(Batting)
    person_df <- tbl_df(Master) 
    
    # Prefix vars from `batting_df` with "batting_"
    batting_df %>% 
      select(playerID, batting_ = -matches("playerID")) %>% 
      inner_join(person_df, by = "playerID")

This might help work around the lack of a `suffixes = ` argument in the various `_join` functions. (To preserve uniqueness, just rename the otherwise-duplicated variables in each table before joining.)

**Comment by hadley** [comment]
I'd rather fix this by controlling the suffixes.

**Comment by tchakravarty** [comment]
Hadley, was not able to understand what the fix suggestion is. Could you please elaborate?

My ultimate aim here is to add a prefix to a set of variable names without leaving a chain.

```{r}
names(df_foo) = paste0("bar_", names(df_foo))
```
