### ISSUE TITLE
transmute can't use existing col as name

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1158]
I noticed the difference between these two queries

```
> transmute(batting_ssq, teamid, g,  n = 2*g)$query
<Query> SELECT "teamid" AS "teamid", "g" AS "g", 2.0 * "g" AS "n"
FROM "bdf"
<SQLiteConnection>
> transmute(batting_ssq, teamid, g,  h = 2*g)$query
<Query> SELECT "teamid" AS "teamid", "g" AS "g", "h" AS "h"
FROM "bdf"
<SQLiteConnection>
```
because the second discards the expression 2*g and produces what I think are incorrect results. The two expressions applied to a data frame produce the same results save for a different col name. Also, `mutate` seems to produce very similar queries and the correct results

```
> mutate(batting_ssq, teamid, g,  n = 2*g)$query
<Query> SELECT "playerid", "yearid", "stint", "teamid", "lgid", "g", "g_batting", "ab", "r", "h", "x2b", "x3b", "hr", "rbi", "sb", "cs", "bb", "so", "ibb", "hbp", "sh", "sf", "gidp", "g_old", "teamid" AS "teamid", "g" AS "g", 2.0 * "g" AS "n"
FROM "bdf"
<SQLiteConnection>
> mutate(batting_ssq, teamid, g,  h = 2*g)$query
<Query> SELECT "playerid", "yearid", "stint", "teamid", "lgid", "g", "g_batting", "ab", "r", "h", "x2b", "x3b", "hr", "rbi", "sb", "cs", "bb", "so", "ibb", "hbp", "sh", "sf", "gidp", "g_old", "teamid" AS "teamid", "g" AS "g", 2.0 * "g" AS "h"
FROM "bdf"
<SQLiteConnection>
```

**Comment by piccolbo** [comment]
it boils down to transmute_ using `select(table, one.of(keep))`. There are two cols with the same name (not possible with DFs AFAIK) and one.of goes for the first, at least not both. But I think this can be fixed because the ambiguity between columns can be resolved, with some pain. Imagine the new cols are temporarily named whatever_new, then the select happens, then they are renamed to whatever. Maybe not the best implementation, but a reference point.

**Comment by hadley** [comment]
Now works post massive internal SQL rewrite:

```R
memdb_frame(x = 1:5) %>% 
  transmute(y = x + 1) %>%
  transmute(z = y + 1)
```
