### ISSUE TITLE
print.tbl_df is very slow for wide datasets

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1161]
Printing wide datasets is very slow due to the printing of all the column names that weren't shown.

Here's an example dataset with 1 row and 1e5 columns.  (Many genomics datasets are much wider than this, so it isn't unrealistically large.)

```{r}
library(dplyr)
ncols <- 1e5
d <- structure(
  as.list(runif(ncols)), 
  class     = c("tbl_df", "tbl", "data.frame"),
  row.names = 1L,
  names     = make.names(rep.int("a", ncols), unique = TRUE)
)
```
Even if you limit the width of the printed content, the part where all the names are printed takes a long time.

```{r}
d                    # slow
print(d, width = 50) # still slow
```

**Comment by richierocks** [comment]
There are a couple of optimisations that can be made in `print.trunc_mat`.  If you add a call to `flush.console()` after `print(x$table)`, then at least the user is guaranteed to be able to see their data while the column name printing calculations are happening.

If you change 

```{r}
var_types <- paste0(names(x$extra), " (", x$extra, ")", collapse = ", ")
```

to 

```{r}
var_types <- toString(paste0(names(x$extra), " (", x$extra, ")"), width = 1000)
```

then (on my machine, with the example in the original issue comment) the printing time is reduced from about 60 seconds to 25.

There are likely further optimisations that could be made in `trunc_mat`, but I haven't looked at those.

**Comment by hadley** [comment]
Seems like it might be reasonable to print only the first 100 extra column names or so?

**Comment by richierocks** [comment]
Yeah, that sounds fine.  I don't think anyone will bother to actually read any more than that, and they can always use `colnames` if they really want to see the rest.

**Comment by hadley** [comment]
Now that we're printing column types too, the minimum width of any column is 4: that should make it possible to do a quick approximate first pass and speed the process up.
