### ISSUE TITLE
Feature request - rbind_all type coercion: 'Just do it' option?

### ISSUE THREAD

**Issue by brendan-R** [hadley/dplyr#1162]
With `rbind_all` on large amounts of data (many dfs, many cols), the ''incompatible type" messages can often be painful to diagnose. 

A *"Do whatever it takes, with warnings!"* option (with a default of `FALSE`), would be fantastic. 

I suppose this would mean potentially promoting any column to character (maintaining `NA`s). 

This would be amazing. It's often much easier to tidy up a variable with all the data together for context (for example, looking at the jumble of values you've ended up with, to figure out what class it should be, or to tidy up factor levels), than it is to get individual files or `data.frames` in order first.

(Apologies if this isn't the place for feature requests, or if this has come up before and I didn't see it.)

**Comment by daattali** [comment]
I came here to suggest this feature as well.  I'm concatenating together many small dataframes with user-submitted input, and a single numeric value in one row where the column is otherwise a string caused a big ugly failure.  
Sadly, I just changed my code from `dplyr::rbind_all(data)` to `do.call(rbind, data)` because I feel like in this case type coercion makes sense and base R just works.

**Comment by mattdowle** [comment]
Another option is `data.table::rbindlist`.  Has been around longer and promotes to the highest type. Did you know about it?

**Comment by daattali** [comment]
Yes, thank you, though ever since `readr` came out I tried eliminating my `data.table` usage unless it's necessary

**Comment by mattdowle** [comment]
Wow - you're so kind.

**Comment by daattali** [comment]
Sorry, I should clarify that I use `data.table` when I need the speed boost with large datasets, but on smaller datasets I find the `dplyr` syntax easier

**Comment by brendan-R** [comment]
Thanks Matt, I'll check it out.

For anyone googling themselves here,

```R
x[] <- lapply(x, as.character)
```

is an easy way to convert all columns of a `data.frame` to character.

**Comment by hadley** [comment]
@daattali I'd love to hear more about your specific problem - generally I'd be concerned about rbind creating columns with the wrong type, i.e. you accidentally have one df with a character column that corrupts everything.

**Comment by daattali** [comment]
I have a demo app [here](http://daattali.com/shiny/mimic-google-form/) that allows people to fill out a form and submit it. Each submission is a one-row dataframe. There is a datatable on the right that reads all the submissions and binds them all together. In the "name" field, one person decided to call themselves "1", so when reading the dataframe for that particular response that column was labeled as numeric, while all other responses had that column as string.  And bad things pursued.

I can arguably validate the input and make sure they enter a string, I haven't thought of that at time of development, but I still think I should be able to bind together all the little dataframes even if one of them thinks one of the columns is a different type.

**Comment by hadley** [comment]
How did a "1" in the text box become a 1 in the data frame? Something must have parsed it.

**Comment by daattali** [comment]
It was written to file using write.csv without quotes and then read back
with read.csv

So, yes, I could take preventative measures but I still feel like it should
be coerced , at least if I specifically add a "just do it" param.

**Comment by hadley** [comment]
I'm currently happy with the behaviour of `bind_rows()`, and if you'd prefer the `rbindlist()` behaviour, you're free to use that.

**Comment by brendan-R** [comment]
👍

**Comment by dmpe** [comment]
:+1: would like to see that too.
