### ISSUE TITLE
sql_quote assumes quoting character is same at beginning and end

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/dplyr#1164]
This is not necessarily the case. For example, the safest way to escape an identifier on SQL Server is to quote them as such `[SQL_IDENITIFIER]` rather than `"SQL_IDENTIFIER"`as the the use of `"` as delimiters for identifiers can depend on the whether the [`QUOTED_IDENTIFIER` option](https://technet.microsoft.com/en-us/library/aa224033(v=sql.80).aspx) as been set.

This is not a big deal as the default setting for `QUOTED_IDENTIFIER` is to use `""`

**Comment by hadley** [comment]
I think should be fixed upstream in DBI
