### ISSUE TITLE
introduction.Rmd uses an example data set that does not import to SQL

### ISSUE THREAD

**Issue by ajdamico** [hadley/dplyr#1166]
it has a bunch of illegal column names, which might be confusing to a beginner trying to get dplyr working on a database

**Comment by hadley** [comment]
That should all automatically be handled by dplyr. Do you have a specific problem?

**Comment by ajdamico** [comment]
ccing @hannesmuehleisen  

specific problem: i think your vignette only works cleanly for tables already loaded in ram.  i thought dplyr's database integration was a central feature of the package, so using an example table that doesn't import into a sql database as-is seems like it might throw off your more inexperienced users.  not a big deal

i don't understand how dplyr would "handle it" in the first place?  in order for dplyr to start working with a table, it already has to be written into the database that dplyr then connects to, right?  sorry if i'm overlooking a table-loading alternative.  thanks again

> dbWriteTable( db , 'flights' , flights )
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'CREATE TABLE flights (year INTEGER, month INTEGER, day INTEGER, dep_time INTEGER, dep_delay DOUBLE P...'.
Server says 'syntax error, unexpected YEAR, expecting FOREIGN or PRIMARY or UNIQUE in: "create table flights (year"' [#42000].
>

**Comment by hannesmuehleisen** [comment]
This issue is MonetDB.R's `dbWriteTable`. `YEAR` is a SQL reserved word, and should be escaped. Will fix this in the next release.

**Comment by ajdamico** [comment]
thanks hannes, sorry to bother you hadley

**Comment by hannesmuehleisen** [comment]
Will be fixed in 0.9.8 of MonetDB.R
