### ISSUE TITLE
many many lines of the introduction vignette do not work with monetdb.  here is a walk-through.

### ISSUE THREAD

**Issue by ajdamico** [hadley/dplyr#1167]
# start in an empty directory somewhere
	# setwd( "C:/My Directory/MonetDB" )

	# # # # # # # # # START OF SETUP - no editing required

	library(ggplot2)
	library(dplyr)
	library(MonetDB.R)
	library(nycflights13)

	batfile <-
		monetdb.server.setup(
			database.directory = paste0( getwd() , "/MonetDB" ) ,
			monetdb.program.path = 
				ifelse( 
					.Platform$OS.type == "windows" , 
					"C:/Program Files/MonetDB/MonetDB5" , 
					"" 
				) ,
			dbname = "test" ,
			dbport = 50000
		)

	pid <- monetdb.server.start( batfile )

	my_db <- src_monetdb( dbname = "test" , port = 50000 , wait = TRUE )
	db <- dbConnect( MonetDB.R() , "monetdb://localhost:50000/test" )

	# # # # # # # # # END OF SETUP

	# ERROR
	dbWriteTable( db , 'flights' , flights )

	# flights has FIVE columns that are illegal in SQL #

	flights$year_ <- flights$year
	flights$year <- NULL

	flights$month_ <- flights$month
	flights$month <- NULL

	flights$day_ <- flights$day
	flights$day <- NULL

	flights$hour_ <- flights$hour
	flights$hour <- NULL

	flights$minute_ <- flights$minute
	flights$minute <- NULL

	dbWriteTable( db , 'flights' , flights )

	rm( flights )

	flights <- tbl( my_db , 'flights' )

	dim(flights)
	head(flights)
	filter(flights, month_ == 1, day_ == 1)
	filter(flights, month_ == 1 | month_ == 2)

	# ERROR
	slice(flights, 1:10)

	arrange(flights, year_, month_, day_)
	arrange(flights, desc(arr_delay))
	select(flights, year_, month_, day_)
	select(flights, year_:day_)
	select(flights, -(year_:day_))
	select(flights, tail_num = tailnum)
	rename(flights, tail_num = tailnum)
	distinct(select(flights, tailnum))

	distinct(select(flights, origin, dest))
	mutate(flights,
	  gain = arr_delay - dep_delay,
	  speed = distance / air_time * 60)
	 
	# ERROR
	mutate(flights,
	  gain = arr_delay - dep_delay,
	  gain_per_hour = gain / (air_time / 60)
	)

	# ERROR
	transmute(flights,
	  gain = arr_delay - dep_delay,
	  gain_per_hour = gain / (air_time / 60)
	)

	# ERROR
	summarise(flights,
	  delay = mean(dep_delay, na.rm = TRUE))
	  
	# WORKAROUND FOR PREVIOUS ERROR
	summarise(flights,
	  delay = mean(dep_delay))
	  
	# THIS DOES NOT THROW AN ERROR BUT THE SAMPLING IS DEFINITELY WRONG
	# RUN IT TEN TIMES -- 
	# NOTICE THREE OR FOUR OF THE RESULTS ARE THE SAME
	sample_n(flights, 10)
	# THIS SAMPLING IS NOT CLOSE TO RANDOM

	# DOES THE ABOVE ISSUE AFFECT THIS COMMAND AS WELL?
	sample_frac(flights, 0.01)

	by_tailnum <- group_by(flights, tailnum)

	# ERROR
	delay <- summarise(by_tailnum,
	  count = n(),
	  dist = mean(distance, na.rm = TRUE),
	  delay = mean(arr_delay, na.rm = TRUE))

	# WORKAROUND  
	delay <- summarise(by_tailnum,
	  count = n(),
	  dist = mean(distance),
	  delay = mean(arr_delay))
	  
	delay <- filter(delay, count > 20, dist < 2000)

	# ERROR
	ggplot(delay, aes(dist, delay)) +
	  geom_point(aes(size = count), alpha = 1/2) +
	  geom_smooth() +
	  scale_size_area()

	  
	destinations <- group_by(flights, dest)

	# ERROR
	summarise(destinations,
	  planes = n_distinct(tailnum),
	  flights = n()
	)

	daily <- group_by(flights, year_, month_, day_)

	(per_day   <- summarise(daily, flights = n()))

	(per_month <- summarise(per_day, flights = sum(flights)))

	(per_yr  <- summarise(per_month, flights = sum(flights)))

	a1 <- group_by(flights, year_, month_, day_)
	a2 <- select(a1, arr_delay, dep_delay)

	# ERROR
	a3 <- summarise(a2,
	  arr = mean(arr_delay, na.rm = TRUE),
	  dep = mean(dep_delay, na.rm = TRUE))

	a3 <- summarise(a2,
	  arr = mean(arr_delay),
	  dep = mean(dep_delay))
	  
	  
	a4 <- filter(a3, arr > 30 | dep > 30)

	# ERROR
	filter(
	  summarise(
		select(
		  group_by(flights, year_, month_, day_),
		  arr_delay, dep_delay
		),
		arr = mean(arr_delay, na.rm = TRUE),
		dep = mean(dep_delay, na.rm = TRUE)
	  ),
	  arr > 30 | dep > 30
	)

	# WORKAROUND
	filter(
	  summarise(
		select(
		  group_by(flights, year_, month_, day_),
		  arr_delay, dep_delay
		),
		arr = mean(arr_delay),
		dep = mean(dep_delay)
	  ),
	  arr > 30 | dep > 30
	)

	# ERROR
	flights %>%
	  group_by(year_, month_, day_) %>%
	  select(arr_delay, dep_delay) %>%
	  summarise(
		arr = mean(arr_delay, na.rm = TRUE),
		dep = mean(dep_delay, na.rm = TRUE)
	  ) %>%
	  filter(arr > 30 | dep > 30)
	  
	  
	# WORKAROUND
	flights %>%
	  group_by(year_, month_, day_) %>%
	  select(arr_delay, dep_delay) %>%
	  summarise(
		arr = mean(arr_delay),
		dep = mean(dep_delay)
	  ) %>%
	  filter(arr > 30 | dep > 30)

**Comment by hadley** [comment]
I think it would be best to file this with MonetDB.R. cc @hannesmuehleisen

**Comment by hannesmuehleisen** [comment]
I would suggest to remove the `na.rm` parameters from the vignette, since the SQL translation does not support them anyway...

**Comment by hannesmuehleisen** [comment]
Added a corresponding test case to our CI: http://dev.monetdb.org/hg/MonetDB/file/a2b9e148eef0/clients/R/Tests/dplyr-flights.R
