### ISSUE TITLE
Documentation: remove some references to _q

### ISSUE THREAD

**Issue by Henrik-P** [hadley/dplyr#1169]
1. In the Index, there are entries for `mutate_each_q` and `summarise_each_q`. However, there are no such functions in the actual help text.

2. In the Argument section of `?summarise_each`, there is a reference to `_q` functions which needs to be rephrased: "For standard evaluation versions (ending in `_q`)"

3. In the Examples section of `?fun`, `funs_q` is mentioned in a comment ("# If you have a function names in a vector, use `funs_q`"). However, this function does not appear in the help text (nor in Index)

**Comment by hadley** [comment]
Would you like to try making a pull request? I suspect it would take as much time to make the changes as it does to precisely describe the problem.

**Comment by Henrik-P** [comment]
I would like to try, yes. However, I have never made a PR before, so please allow for some time to let me learn it properly.

**Comment by hadley** [comment]
I think these are all fixed now.
