### ISSUE TITLE
Hidden copy-making with tbl_df

### ISSUE THREAD

**Issue by Alectoria** [hadley/dplyr#1171]
Is there a way to avoid hidden copy-making with tbl_df()? I am processing large data frames and calling tbl_df() takes too long. Here a demo (with a much smaller data frame):

    df <- data.frame(x=rnorm(10^7), x=rnorm(10^7))
    library(dplyr)
    tracemem(df)
    [1] "<0x7feaf1e107c8>"

    t1 <- Sys.time()
    df <- tbl_df(df)
    tracemem[0x7feaf1e107c8 -> 0x7feaf1dcc6b0]: as.list.data.frame as.list vapply as_data_frame tbl_df 
    tracemem[0x7feaf1e107c8 -> 0x7feaf1dcc7c8]: as.list.data.frame as.list vapply unique as_data_frame     tbl_df 
    tracemem[0x7feaf1e107c8 -> 0x7feaf1dcc918]: as_data_frame tbl_df 
    tracemem[0x7feaf1dcc918 -> 0x7feaf1dcc950]: as_data_frame tbl_df 
    t2 <- Sys.time()

    difftime(t2,t1)
    Time difference of 0.503787 secs

**Comment by hadley** [comment]
What version of dplyr do you have? I get:

```R
df <- data.frame(x=rnorm(10^7), x=rnorm(10^7))
library(dplyr)

system.time(tbl_df(df))
#   user  system elapsed 
#      0       0       0 
```

**Comment by Alectoria** [comment]
I have v0.4.1. But just reinstalled R and all packages and the times haves improved. - Strange. But problem solved. Thanks!
