### ISSUE TITLE
select(): negation of non-match gives no vars, instead of all vars

### ISSUE THREAD

**Issue by gunapemmaraju** [hadley/dplyr#1176]
In dplyr, I want to exclude columns which contain the word "junk" but, there may not be any column that contain the word "junk". In that case, dplyr should return all columns. But it returns none. See unit test case below.

```R
df<-data.frame(name=paste("name",1:5), age=1:5)
str(df)
 'data.frame': 5 obs. of  2 variables:
 $ name: Factor w/ 5 levels "name 1","name 2",..: 1 2 3 4 5
 $ age : int  1 2 3 4 5
df1<-df%>%select(-contains("junk"))
str(df1)
 'data.frame': 5 obs. of  0 variables
```

More at

http://stackoverflow.com/questions/30496930/in-dplyr-select-with-a-drop-does-not-work

**Comment by blasern** [comment]
This is because `contains` returns `integer(0)` if it does not find any match. `-integer(0)` is still `integer(0)`. An easy fix would be to return `-seq_along(vars)` instead.  

    contains <- function (vars, match, ignore.case = TRUE) 
      {
        stopifnot(is.string(match), nchar(match) > 0)
        if (ignore.case) {
          vars <- tolower(vars)
          match <- tolower(match)
        }
        res <- grep(match, vars, fixed = TRUE)
        if (length(res) == 0) res <- -seq_along(vars)
        res
      }

The same problem occurs also in `starts_with`, `ends_with`, `contains` and `matches`.

**Comment by drewgendreau** [comment]
Just wanted to add that I tried doing this earlier today and was surprised to find that 

df %>% select(-contains("this_string_is_definitely_not_in_any_of_the_column_names") )

returns an empty data.frame.  The use case is that I'm running a program where I don't know all the column names ahead of time, but if there is one with a particular string I'd like to drop it.
