### ISSUE TITLE
unclear code from database.Rmd

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1178]
```
if (has_lahman("postgres")) {
  daily <- group_by(flights_postgres, year, month, day)
```

I may be dense, but what is the relation between aviation and baseball that motivates this? Like, baseball teams often travel by plane?  Not sure that's a strong enough connection

**Comment by hadley** [comment]
I think it's just that I didn't write a `has_flights()` function and `has_lahman()` suffices to figure out if postgres is active.
