### ISSUE TITLE
why rename function failed to give output when start_with option used

### ISSUE THREAD

**Issue by yifeizhang** [hadley/dplyr#1180]
The select function works fine when I try to rename variables according to certain conditions
```
select(iris, petal = starts_with("Petal"))
```
However when I try to keep all the other variables using
```
rename(iris, petal = starts_with("Petal"))
Error: Arguments to rename must be unquoted variable names. Arguments petal are not.
```
I have no idea why dplyr complains about this. If this behabior is intended, what is the right way to rename variables using starts_with (or contains) while keeping other variables there?

**Comment by yifeizhang** [comment]
I got reply from stackoverflow that the following code does the job
```
select(iris, petal = starts_with("Petal"), everything())
```

I am still wondering why rename is not supported in this case.

**Comment by hadley** [comment]
Because rename is for renaming single named variables.
