### ISSUE TITLE
get() function no longer working

### ISSUE THREAD

**Issue by jinsca** [hadley/dplyr#1182]
Hi all,
In version dplyr_0.4.1, the following code will not work but in version dplyr_0.4.0 it does work:

format1 <- function(dataset, grp, var){
    result.df <- dataset %>% 
      group_by(get(grp)) %>%
      summarise_each(funs(mean, max, min), get(var))
  
  return(result.df)
}

format1(mtcars, "cyl", "mpg")

The error I get when trying to run "format1" is:
Error in get("cyl") : object 'cyl' not found.

Any thoughts or work-arounds would be great. For now I plan to use the older version of dplyr but if anyone has ideas for version .1 they are much appreciated!

**Comment by hadley** [comment]
Use `group_by_` and see the NSE vignette.
