### ISSUE TITLE
hybrid handler for quantile 

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#1183]
It would be great to have an hybrid hander for quantile. For now it is orders of magnitude slower than mean:

``` R
df <- data_frame(
         id =  sample(1e5, 1e6, TRUE),                      
         v =  sample(5, 1e6, TRUE)                        
    )
df1 <- df %>% group_by(id)
system.time(summarize(df1,  mean(v)))
# user  system elapsed 
#  0.041   0.001   0.056 
system.time(summarize(df1,  quantile(v, 0.50, type = 1)))
#   user  system elapsed 
#15.080   0.060  15.157 
```

Since quantile has so many options, maybe a function called `qtile` which implements only one kind (the kind used for `ntile`).

**Comment by romainfrancois** [comment]
There is much more work to do to get a quantile (a sort essentially) than a mean (a sum). We could use some tricks to save data usage, etc ... but you definitely should not expect the same performance as mean.

**Comment by hadley** [comment]
@romainfrancois I think I have some C++ code somewhere that implements a reasonable efficient quantile. It won't be nearly as fast as mean, but should be faster than base R

**Comment by matthieugomez** [comment]
Cool. Simply getting the right indices after a full sort (which correspond to quantile type 1) would already be faster than the current quantile function (`arrange` only takes 0.651 on the example dataset).

**Comment by hadley** [comment]
Moved to vcrtrs
