### ISSUE TITLE
segfault 'memory not mapped' in R 3.2.0 for OS X 10.10.3

### ISSUE THREAD

**Issue by mtingley** [hadley/dplyr#1186]
I recently updated R to 3.2.0 and now I am having repeatable segfault crashes whenever I load a package. The error happens on package load. All packages (and dependencies) have been recently installed from CRAN, as was R. This happens with 'dplyr' (see below), but also any package in the 'gg' family, and a few others I have discovered (e.g., 'rgdal'). Other things ('sp', 'rjags', etc.) run fine. 

Segfault is as follows: 
![segfault](https://cloud.githubusercontent.com/assets/6967321/7898589/9bf0591e-06d2-11e5-9841-e65d2a96090a.png)

Session Info is as follows:
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by hammadsheikh** [comment]
Same problems here, same platform and OS, same locale.

**Comment by romainfrancois** [comment]
Not much to go on. Might be related to an update of Rcpp, e.g. if the binary you get from CRAN uses Rcpp version a and you have Rcpp version b, then things like this happen. 

I'm closing because I don't think there is much we can do about it.
