### ISSUE TITLE
Reorder variables in a data frame?

### ISSUE THREAD

**Issue by jjchern** [hadley/dplyr#1188]
Is there a way to order variables using dplyr's functions? That is, I was looking for an equivalent function of Stata's [`order` command](http://www.stata.com/help.cgi?order).

An example data frame:
```r
state = c("Alabama", "Alabama")
var = rnorm(2)
year = 2009:2010
df = dplyr::data_frame(state, var, year)
```

To reorder variables in `df`, one can use `df = df[, c(state, year, var)]`. But I was wondering if there is a dplyr single table verb to do the same thing.

**Comment by tonyfischetti** [comment]
```
select(df, year, var, state)   # reverses it

# if you only know you want var in the front and don't care about the order of the rest, you can do

df %>%
  select(var, everything())
```

like that?

**Comment by jjchern** [comment]
Excellent! Thank you!

Is this `everything()` a base R function? I can't find anything through `?everything` and `??everything` in my R Studio's console.

**Comment by tonyfischetti** [comment]
`everything()` is in dplyr's [select-utils.R](https://github.com/hadley/dplyr/blob/master/R/select-utils.R). I don't think the documentation is exported, though.

**Comment by LiNk-NY** [comment]
Why doesn't this support a variable at the end? 

```
df %>%
    select(everything(), var)
```

Sometimes you need variables at the end to create tables.

**Comment by yutannihilation** [comment]
@LiNk-NY
According to  https://github.com/tidyverse/dplyr/issues/3051#issuecomment-324646580, you can do this instead:

```r
df %>%
    select(-var, everything())
```

**Comment by LiNk-NY** [comment]
I guess so but this forces me to use two `select` calls:
```
df %>%
    select(-deleteme, -delete) %>%
    select(-var, everything())
```
Thanks!

**Comment by yutannihilation** [comment]
IIUC, using two `select()` is unavoidable in your case since `select()` doesn't actually "select" columns but sorts when used with `everything()`. So, if you want to "select" + sort columns, there must be two `select()`.
