### ISSUE TITLE
%<>% inside mutate

### ISSUE THREAD

**Issue by bramtayl** [hadley/dplyr#1189]
It would be convenient if %<>% worked inside mutate. E.g.

    library(dplyr)
    library(magrittr)

    data = data_frame(a = 1) %>%
       mutate(a %<>% add(1))

**Comment by romainfrancois** [comment]
I don't think it is compatible with how things work internally, and I find the default syntax clearer: 

```
data = data_frame(a = 1) %>%
   mutate(a  = a + 1)
```

I find it easier to figure out what is going on.

**Comment by bramtayl** [comment]
I agree to some extent that the syntax is clearer. That said, when I use mutate, I think about 50% of the time it looks like this:

    df %<>%
      mutate(a = a %>% some stuff,
                  b = b %>% some stuff)
