### ISSUE TITLE
R crashes when trying to bind_rows on malformed data frame - "unimplemented type (31) in 'obect.size'

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/dplyr#1191]
Hi, I had this crash of my R session when trying to bind two frames:

    data_all <- bind_rows(select(data_a, -thisColumn), 
                          select(data_b, -thatColumn))

Crashes with message:

    Error in structure(.Call(C_objectSize, x), class = "object_size") : unimplemented type (31) in 'object.size'

I can see that is due to one of my columns containing errors in their build:

    Source: local data frame [67 x 5]

             date        x                 y  type breakdown
    1  2015-03-01        3                 0 total <chr[67]>
    2  2015-03-01       12                 6 total    <NULL>
    3  2015-03-01        1                 1 total    <NULL>
    4  2015-03-01        1                 0 total    <NULL>

This came about as I tried to assign via data_a$anotherColumn  rather than with mutate() but perhaps it is desirable to have a more graceful fail.

Session info:

    R version 3.1.3 (2015-03-09)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.10.2 (Yosemite)

    locale:
    [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] dplyr_0.4.1     rga_0.8         httr_0.6.1      jsonlite_0.9.16 RCurl_1.95-4.6  bitops_1.0-6   

    loaded via a namespace (and not attached):
    [1] assertthat_0.1 DBI_0.3.1      magrittr_1.5   parallel_3.1.3 Rcpp_0.11.6    rstudioapi_0.2 stringi_0.4-1  stringr_1.0.0 
    [9] tools_3.1.3

**Comment by romainfrancois** [comment]
@MarkEdmondson1234 can you make this reproducible. I don't have `data_a` and `data_b`.

**Comment by MarkEdmondson1234** [comment]
I beg your pardon Romain, but I had a look for the code that produced this first time and I've edited it out, and the pre-condition (a dataframe with a character vector in one field and NULL in the rest), I can't reproduce.  I thought it worth reporting as the whole R session crashed when it happened, but since then perhaps dplyr has updated to not allow that situation occurred.  I'll close this, but at least you have a reference if similar occurred.
