### ISSUE TITLE
Cryptic error message in case of misused xxx_join(..., by=c(...))

### ISSUE THREAD

**Issue by petermeissner** [hadley/dplyr#1192]
*This is no bug report rather a request to give more informative error messages.*

If the following misuse of the join functions is undertaken the error messages are somewhat cryptic:

```r
     data2 <- data_frame(a=1:3)
     data1 <- data_frame(a=1:3, c=3:5)

     left_join(data1, data2, by=c("a","a"))

     ## Error in left_join_impl(x, y, by$x, by$y) : attempt to set index 0/0 in SET_STRING_ELT
```

While the input should have been ...

```r
     left_join(data1, data2, by=c("a"="a"))    

    ## Source: local data frame [3 x 2]
    ## 
    ##   a c
    ## 1 1 3
    ## 2 2 4
    ## 3 3 5
```

... a syntax error that is easy to do and hard to find.

**Comment by almartin82** [comment]
if this is at all helpful, here's where I ran into `attempt to set index 0/0 in SET_STRING_ELT`:  when trying to apply a function `rowwise()` on a zero-row df.

here was the offending call
```
df %>%
      rowwise() %>%
      mutate(
        cgp_label = cgp_labeler(n, cgp)  
      ) %>%
      as.data.frame
```
I added a defensive statement in my `cgp_labeler` function to make the error more informative.
