### ISSUE TITLE
Feature or bug? data_frame_ on a vector

### ISSUE THREAD

**Issue by JasonAizkalns** [hadley/dplyr#1194]
See this [SO post](http://stackoverflow.com/questions/30597522/what-is-the-dplyr-equivalent-of-plyrldplytapply-in-r/30597803#30597803) with specific attention to [this answer](http://stackoverflow.com/a/30598149/2572423).

Is this the intended behavior of `data_frame_`:

```{r}
probs = seq(0, 1, 0.1)
mtcars %>% 
  group_by(cyl) %>% 
  do(data_frame_(quantile(.$mpg, probs = probs)))
## Source: local data frame [3 x 12]
## Groups: cyl
## 
##   cyl   0%   10%   20%   30%   40%  50%   60%   70%   80%   90% 100%
## 1   4 21.4 21.50 22.80 22.80 24.40 26.0 27.30 30.40 30.40 32.40 33.9
## 2   6 17.8 17.98 18.32 18.98 19.40 19.7 20.48 21.00 21.00 21.16 21.4
## 3   8 10.4 11.27 13.90 14.66 15.04 15.2 15.44 15.86 16.76 18.28 19.2
```

**Comment by hadley** [comment]
Yes, I'm pretty sure that's expected by the semantics of SE functions
