### ISSUE TITLE
does top_n need a na.rm argument

### ISSUE THREAD

**Issue by mhpedersen** [hadley/dplyr#1201]
I have been surprised when top_n(1, X) leaves out records where X is NA. Perhaps this is intentional but not what I expected, and took a little while to debug.
It is easily resolved using top_n(1, pmax(X,0,na.rm=T)), assuming 0 makes since for the domain values of X. But perhaps more user-friendly would be an option to top_n to not remove NAs like this?

thx
Morten

**Comment by hadley** [comment]
It doesn't remove them - it just follows the R convention of sorting NAs to the bottom.
