### ISSUE TITLE
setNames in NSE 

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#1205]
When setting the names of new variable using the NSE functions, one needs to use setNames, which can make code hard to read.

Would it be possible to allow left hand side in formulas?

This would allow to write

```R
summarise_(mtcars,  mean ~ mean(mpg))
```

instead of 

```R
summarise_(mtcars, .dots = setNames(list(~mean(mpg)), "mean"))
```

**Comment by richierocks** [comment]
You can already do 

    summarise_(mtcars,  mean = ~ mean(mpg))

**Comment by matthieugomez** [comment]
My point was really about using `mutate_` or `summarise_` inside a program, where you don't know the variable names

For instance, to write a function that demean a variable given as an argument
```r
library(lazyeval)
f <- function(df, oldvar)
newvar = paste0(oldvar, "new")
action = interp(~mean(x), x = oldvar)
summarise(df, .dots = setNames(list(action, newvar)))
```

But it would look cleaner to write
```r
library(lazyeval)
f <- function(oldvar)
newvar = paste0(oldvar, "new")
action = interp(y~mean(x), x = oldvar, y = newvar)
summarise(mtcars, .dots = action)
```
