### ISSUE TITLE
Feature suggestion: write help documentation for the join functions similar to Stata

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1209]
I particularly like the pictures they have of the different merge types (page 6 onwards here: http://www.stata.com/manuals13/dmerge.pdf).

Hope this helps.

**Comment by voxnonecho** [comment]
Please have a look at the Data Wrangling Cheat Sheet (Combine Data Sets section): http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

**Comment by kendonB** [comment]
Great, this is pretty much what I meant. My only suggestion would be to add a column with repeated values in one of the merged datasets (like ``region`` in the Stata documentation). Thanks
