### ISSUE TITLE
data.table dim_desc printing cannot be suppressed

### ISSUE THREAD

**Issue by rubenarslan** [hadley/dplyr#1211]
I use data.table and dplyr together until dplyr gets a comparably elegant conditional mutate. 

I think the issues with undesired printing of data.table and tbl_dt because the various print functions don't deal with `:=` assignment are by now well-known and it sounds like they [won't be fixed](https://github.com/hadley/dplyr/issues/1054) (for me it has gotten worse over time).

So, to use the packages together and not have my knitr reports polluted, I use this:

if(!interactive()) {
  options(datatable.print.nrows=0)
  options(dplyr.print_max = 0)
  options(dplyr.print_min = 0)
}

This does suppress printing for data.table:::print.data.table, but not for dplyr:::print.tbl_dt.
But even with print_max = print_min = 0, dplyr keeps printing the dim_desc. 
I'd like to be able to suppress that too.

**Comment by hadley** [comment]
To be honest, I don't understand the issues with printing and `:=`. It doesn't seem like a dplyr issue to me.

**Comment by rubenarslan** [comment]
All else aside, I'd appreciate an option to turn off all printing. That's a crude solution, but it works and is useful for a variety of problems and might help people until dt and dplyr play nicely with each other.

My reasoning why this is a dplyr issue: You're extending data table with your classes tbl_dt etc. But one part of data.table is the `:=` assignment operator used like this `data[, new_var :=1]`. That operator requires a specific silencing procedure within the print method (since the print method is called when the `:=` is used without an explicit assignment like `data = data[, new_var :=1]`).

Data.table cannot put a specific silencing procedure in print.tbl_dt, only dplyr can. 
My understanding of extending data.table in dplyr would imply that your print.tbl_dt method should also handle the silencing.

I think dplyr should either support `:=` assignment (including the print suppression) or stop extending data.table.

Until then, the only way I can use data.table and dplyr together without losing my mind, I'd say, I am often forced to write code like this

```
options(datatable.print.nrows=0)
cars[1,1] = NA
cars = data.table(cars)
cars %>% 
    setDF() %>% # so that assignment in mutate() works without odd errors about typing in ifelse
    mutate(speed = ifelse(is.na(speed), NA, speed)) %>%
               data.table() -> # so that the tbl_dt class is removed, unnecessary copy
               cars

cars[dist>20, speed := 2] # currently this even prints with vanilla data.tables, because of https://github.com/Rdatatable/data.table/issues/1122 but at least I can suppress that using options
```

**Comment by hadley** [comment]
Oh I see - this is because data.table has chosen to implement non-standard semantics for `[`. This is an issue with trying to have reference objects in a language that is fundamentally functional. 

In your particular case, it would be better to just use the correct NA:

```R
library(dplyr)
cars[1,1] <- NA
cars %>% 
    mutate(speed = ifelse(is.na(speed), NA_real_, speed))
```

I personally don't think it's dplyr's responsibility to work around this issue.

**Comment by rubenarslan** [comment]
I see that and I'm perfectly happy switching to dplyr entirely once it's a bit more mature (handling missings in dates is driving me up the wall, I just can't wrap my head around the idiosyncrasies yet and there's problems I simply couldn't solve in dplyr).

But until then, I think it's not entirely right to say you're extending data.table, it's pretty unusable when extended by dplyr.
