### ISSUE TITLE
summarise_each() can't handle function with two parameters

### ISSUE THREAD

**Issue by voxnonecho** [hadley/dplyr#1213]
Consider the following data frame:

    data <- data.frame(n = c(1,1,1,2,2,2), 
                       x1 = c(4,5,4,7,5,5), x2 = c(7,10,9,NaN,11,12), 
                       w1 = c(0,1,1,1,1,1), w2 = c(1,1,1,0,0,1))

Is there a way to mimic `data.table` + `Map` with `summarise_each()` ?

    setDT(data)[,  Map(weighted.mean, 
                       mget(grep('x', names(data), value=TRUE)), 
                       mget(grep('w', names(data), value=TRUE))), by = n]

Something like:
 
    data %>% 
      group_by(n) %>% 
      summarise_each(funs(weighted.mean), starts_with("x"), starts_with("w"))

**Comment by hadley** [comment]
To me, that code looks very fragile, because it depends on the exact ordering of the variables. If something is messed up with your input data, you're unlikely to get an error message - it will work, but do the wrong thing.
