### ISSUE TITLE
anti_join error message improvement: x|y is not a data.table

### ISSUE THREAD

**Issue by helix123** [hadley/dplyr#1217]
For dplyr_0.4.1 I think "x" in the following error message should be a "y":

    library(data.table)
    set.seed(45L)
    DT <- data.table(V1=c(1L,2L),
                 V2=LETTERS[1:3],
                 V3=round(rnorm(4),4),
                 V4=1:12)
    set.seed(46L)
    DT2 <- data.table(V1=c(1L,2L),
                 V2=LETTERS[1:3],
                 V3=round(rnorm(4),4),
                 V4=1:12)

    DF2 <- as.data.frame(DT2)

    dplyr::anti_join(DT, DT2, by=("V1"))
    # works
    dplyr::anti_join(DT, DF2, by=("V1"))
    # Error in data.table::setkeyv(y, by$x) : x is not a data.table
    ## should be y instead of x?

    dplyr::anti_join(DF2, DT, by=("V1"))
    # V1 V2 V3 V4
    # <0 rows> (or 0-length row.names)
    ## However, with the parameters changed in order, no error is displayed

**Comment by richierocks** [comment]
Also applies to `left_join`.
