### ISSUE TITLE
Feature request: provide functionality to resize data frames in order to bind_cols

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1221]
If you try to `bind_cols` on two data frames with differing numbers of rows, you get an error.

    x <- data.frame(a = 1, b = "a")
    y <- data.frame(c = 2:6, d = letters[2:6])

    bind_cols(x, y)
    ## Error: incompatible number of rows (5, expecting 1)
    
Base R's `cbind` is sometimes smart enough to replicate the values in the shorter data frame to match the dimensions of the longer one.
    
    cbind(x, y)
    ##   a b c d
    ## 1 1 a 2 b
    ## 2 1 a 3 c
    ## 3 1 a 4 d
    ## 4 1 a 5 e
    ## 5 1 a 6 f
    
It doesn't work if `nrow(x) > 1` and `nrow(y) > 1` and the greatest common divisor of `nrow(x)` and `nrow(y)` is one.
    
    x2 <- data.frame(a = 7:8, b = letters[7:8])
    cbind(x2, y)
    ## Error: arguments imply differing number of rows: 2, 5
    
It would be nice if there was a function for matching the number of rows in data frames so that they can be bound together.  Here's a quick implementation for data frames:
    
    match_n_rows <- function(x, ...)
    {
      if (is.list(x) && !is.data.frame(x)) {
          match_n_rows_impl(x)
      }
      else {
          match_n_rows_impl(list(x, ...))
      }
    }

    match_n_rows_impl <- function(dots)
    {
      # Could use something like lapply(dots, assert_is_data.frame) 
      # if you don't mind having assertive as a dependency
      nrows <- vapply(dots, nrow, integer(1))
      lapply(dots, rep_data.frame, length.out = max(nrows))
    }

    rep_data.frame <- function(d, length.out)
    {
      d %>% 
        lapply(rep_len, length.out = length.out) %>%
        structure(class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA_integer_, length.out))
    }

    match_n_rows(x, y)
    ## [[1]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   a b
    ## 1 1 a
    ## 2 1 a
    ## 3 1 a
    ## 4 1 a
    ## 5 1 a
    ## 
    ## [[2]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   c d
    ## 1 2 b
    ## 2 3 c
    ## 3 4 d
    ## 4 5 e
    ## 5 6 f

     match_n_rows(list(x2, y))
    ## [[1]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   a b
    ## 1 7 g
    ## 2 8 h
    ## 3 7 g
    ## 4 8 h
    ## 5 7 g
    ## 
    ## [[2]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   c d
    ## 1 2 b
    ## 2 3 c
    ## 3 4 d
    ## 4 5 e
    ## 5 6 f
    
Now you can bind the output:

    match_n_rows(x2, y) %>% bind_cols
    ##   a b c d
    ## 1 7 g 2 b
    ## 2 8 h 3 c
    ## 3 7 g 4 d
    ## 4 8 h 5 e
    ## 5 7 g 6 f
    
List interface: 

    match_n_rows(list(x, y))
    ## [[1]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   a b
    ## 1 1 a
    ## 2 1 a
    ## 3 1 a
    ## 4 1 a
    ## 5 1 a
    ## 
    ## [[2]]
    ## Source: local data frame [5 x 2]
    ## 
    ##   c d
    ## 1 2 b
    ## 2 3 c
    ## 3 4 d
    ## 4 5 e
    ## 5 6 f
    
Let me know if you think that this is worth pursuing further (for example, extending to other `tbl` types, and considering the reverse case of binding rows).

**Comment by hadley** [comment]
I don't think this sort of repetition is that useful for `bind_cols()` - I'd rather people used the appropriate join instead
