### ISSUE TITLE
Feature request: Use n() on subgroup 

### ISSUE THREAD

**Issue by voxnonecho** [hadley/dplyr#1223]
Consider the following data frame:

    m = data.frame(pop = c(1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4), 
                   id = c(0,1,1,1,1,1,0,2,1,1,1,2,1,2,2,2))

If I want to divide the  `pop`, `id` group size by it's corresponding `pop` group size, I have to create a temporary variable `s` to store the `pop` group size first:

    m %>% 
      group_by(pop) %>% 
      mutate(s = n()) %>% 
      group_by(pop, id) %>% 
      mutate(f = n() / s)

Or

    m %>% 
      group_by(pop, id) %>% 
      summarise(s = n()) %>%
      mutate(f = s / sum(s)) %>%
  
Could there be a more efficient way to access group / subgroud size "on the fly" ? Something like:

    m %>% mutate(f = n(pop, id) / n(pop))

Here's the `data.table` way:

    setDT(m)[, {div = .N; .SD[, .N/div, keyby = id]}, by = pop]

**Comment by hadley** [comment]
I'm currently happy with having to do this explicitly.
