### ISSUE TITLE
Switch for showing progress bar

### ISSUE THREAD

**Issue by thomasp85** [hadley/dplyr#1226]
This is kind of in the same vein as #428. The progress bar shown when using do() is often unwanted if you use dplyr inside a function. If the dplyr operation is only part of the computation it signals a wrong message about the running time to users, as there is no indication that the progress bar is only related to part of the calculation. I would like to either have the possibility of switching it off as an argument in do, or only have it shown if it is used in the global environment.

**Comment by shrektan** [comment]
+1
