### ISSUE TITLE
Pass custom functions to select()

### ISSUE THREAD

**Issue by msjgriffiths** [hadley/dplyr#1229]
Right now, you're limited in column selection when using select() and magrittr.

Consider the situation where you have a table, and you want to select certain columns at an intermediate point in a transformation pipeline, but don't want to (i) use fixed column indexes and (ii) don't want to save out an intermediary variable and identify column names separately.

It would make sense to be able to define a custom function in the same format as `everything()` or `one_of()`, and have `select()` and `gather()` and other functions use a custom function for selection variables.

In principle the function you take in a list of column names (e.g. `names(data)`) and then output a list of integer positions (e.g. `c(1, 2, 7)`. 

Example usage:

``` r

# Pass in column that expects the first parameter to be a list of column names.
data %>% gather(key, value, function(vars) {
    vars[-grep("Drop", vars, fixed = TRUE)]
})

# Define a function that expect the first parameter to be column names, second to be matches.
not_contains <- function(vars, match){
    vars[-grep(match, vars, fixed = TRUE)]
}
data %>% select(not_contains("avoid"))
```

Less ideally, allow custom functions to be registered as [part of `select_funs`](https://github.com/hadley/dplyr/blob/master/R/select-vars.R#L67), e.g. something like:

``` r
not_contains <- function(vars, match){
    vars[-grep(match, vars, fixed = TRUE)]
}

dplyr::register_select_funs(not_contains)

data %>% select(not_contains("avoid"))
```

**Comment by hadley** [comment]
You can now use `select_if()` or implement your helper in the same way as `starts_with()` etc
