### ISSUE TITLE
slice for row 0

### ISSUE THREAD

**Issue by franknarf1** [hadley/dplyr#1234]
To be consistent with data.frame `slice(df,0)` should return an "empty" data.frame, like `df[0,]` does. Currently, it seems to act like -1..?

    df <- data.frame(a=1:3)
    slice(df,0)
    #   a
    # 1 2
    # 2 3
    
Not sure if this was fixed since I mentioned it here: http://stackoverflow.com/questions/30491740/weird-behavior-in-dplyr-slice-for-r#comment49063197_30491740 The same behavior seems to prevail for any index outside the range, like `slice(df,5)` as mentioned in that question. (Not sure how I can change the title of this issue to reflect that.)

**Comment by romainfrancois** [comment]
I think this has been fixed while working on #1235. I now get: 

```
> df <- data.frame(a=1:3)
> slice(df,0)
[1] a
<0 rows> (or 0-length row.names)
>
>
> slice(df,5)
[1] a
<0 rows> (or 0-length row.names)
```
