### ISSUE TITLE
broken dependency: radiant

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#1238]
http://www.stats.ox.ac.uk/pub/bdr/memtests/UBSAN-gcc/radiant/00check.log

**Comment by hadley** [comment]
I'm pretty sure this is the same as the mutate bug that's causing problems for people

**Comment by romainfrancois** [comment]
My thinking too. Let me have a look at some low hanging fruits and perhaps we can do another release around mid-july.

**Comment by vnijs** [comment]
Likely related ... dplyr segfault on travis. Log linked below.

```r
 *** caught segfault ***
address 0x30, cause 'memory not mapped'
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/74278534/log.txt

**Comment by vnijs** [comment]
Using `mutate_each` on a data.frame with missing values has been causing me lots of trouble. Silly example ... but the simplest one i've been able to find that consistently crashes R(studio) with dplyr 0.4.2 and Rcpp 0.12.0 on Mac

```r
library(dplyr)
dat <- matrix("", nrow = 1000, ncol = 50) %>% as.data.frame
rmiss <- function(x) ifelse(x == "", NA, .)
mutate_each_(dat, funs(rmiss), vars = colnames(dat)) 
```

**Comment by vnijs** [comment]
FYI the crash does not occur with the development version of dplyr (0.4.2.9002 on mac, R3.2.1 with Rcpp 0.12.0)
