### ISSUE TITLE
dplyr::function_name but not function_name directly

### ISSUE THREAD

**Issue by zhilongjia** [hadley/dplyr#1239]
Whenever I use a function in dplyr, I will use dplyr::function_name to avoid something strange caused by the same function name in another package. Many function names in dplyr is really common. Why not name it unique in dplyr? I believe dplyr::function_name is not as convenient as function_name alone. Thank you.

**Comment by romainfrancois** [comment]
You can put your code in a package and selectively `importFrom` dplyr. It is unlikely that function names will change now.
