### ISSUE TITLE
Support older versions of R

### ISSUE THREAD

**Issue by dnuffer** [hadley/dplyr#1240]
I just tried installing dplyr, and install.packages() gave me the rather uninformative message:
package ‘dplyr’ is not available (for R version 3.1.1)
After some digging and searching, I found that's because the latest dplyr requires R >= 3.1.2.
I've got R 3.1.1. I don't want to upgrade R, I use the version Ubuntu provides. I don't want to upgrade to the latest version of Ubuntu just to get a newer R, it doesn't work right with my hardware.
After some more searching and digging on CRAN, I found that I can install an older version of dplyr which will work. All that took me about 30 minutes just to be able to install the library so I can run some code. I'm sure you've got some excuse for not supporting older versions, but how many people will just give up using dplyr or also have to waste a bunch of time trying to get it installed?
The most commonly used version of Ubuntu (14.04 - the latest LTS) has R 3.0.2. http://packages.ubuntu.com/trusty/math/r-base
R 3.1.2 has only been out for 8 months. I'll bet that most Windows and Mac users don't have it installed either.

**Comment by hadley** [comment]
Unfortunately I don't have the time or resources to test dplyr with older versions of R.

**Comment by dnuffer** [comment]
What a shame that such a potentially useful library is in handicapped by your lack of desire to spend time to ensure it works in common installations. Since you don't appear to care much about users of your library, at least you should make your practices obvious so that people know what they are getting into when they decide to use it.

**Comment by hadley** [comment]
It seems a bit on the nose to complain about open source software.

**Comment by mattdowle** [comment]
I think you're a bit off mark here Hadley.  It doesn't take that much to
run "R CMD check" using an older version of R.  I know because I have
always done that for data.table.  I haven't had the resources of RStudio
and I managed it.  I just run using data.table's stated dependency
(currently R 2.14.0) before release to CRAN.

**Comment by rames72** [comment]
Is there anyway to run dplyr on 3.1.1?

**Comment by cronacronis** [comment]
You can download `dplyr` from CRAN archive and install it from `tar.gz`. Just take care of installing dependencies.

**Comment by gwaygenomics** [comment]
just ran into this issue myself when trying to run `dplyr` in an [anaconda3 docker image] (https://hub.docker.com/r/continuumio/anaconda3/ "anaconda3 docker hub"). I will post my work around here in case anyone is directed to this thread like I was:

``` bash
RUN apt-get update --fix-missing
RUN apt-get install r-base r-base-dev 
RUN apt-get install r-cran-rcpp

RUN echo "deb http://cran.irsn.fr/bin/linux/debian jessie-cran3/" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keys.gnupg.net --recv-key 381BA480
RUN apt-get update
RUN apt-get install r-base
```
