### ISSUE TITLE
update 0.4.1 to 0.4.2 introduces segfault

### ISSUE THREAD

**Issue by mplourde** [hadley/dplyr#1243]
After updating to 0.4.2 from CRAN, my application now generates segfaults in seemingly random situations. The application is complex so I'm unable to provide a minimal reproducible example, but I would be glad to test any updates and provide feedback as to whether the issue still occurs. This segfault happens on Windows 7 64bit and Ubuntu 14.1 64bit. My R version is 3.2.1. 

The output running in Ubuntu:

     *** caught segfault ***
     address 0x100000011, cause 'memory not mapped'

**Comment by romainfrancois** [comment]
Not much we can do without more information. Perhaps run it under gdb on the ubuntu version will give some clues.

**Comment by hadley** [comment]
Please try with the dev version. If it still crashes, a gdb stack trace would be very useful.

**Comment by r2evans** [comment]
I'm able to get it to consistently dump with this code:

```r
library(dplyr)
ign <- replicate(50000,
                 mtcars %>%
                     mutate(x=mpg-cyl,
                            y=disp/hp)
                 )

sessionInfo()
## R version 3.2.1 (2015-06-18)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 8 x64 (build 9200)
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## other attached packages:
## [1] dplyr_0.4.1 r2_0.4.15  
## loaded via a namespace (and not attached):
##  [1] compiler_3.2.1  lazyeval_0.1.10 magrittr_1.5    assertthat_0.1 
##  [5] parallel_3.2.1  DBI_0.3.1       tools_3.2.1     htmltools_0.2.6
##  [9] Rcpp_0.11.6     rmarkdown_0.7   digest_0.6.8   
```

The above code breaks under R-3.1.3, R-3.2.0, and R-3.2.1 using dplyr-0.4.2. When I downgrade to dplyr-0.4.1, all is good.

**Comment by mplourde** [comment]
@romainfrancois any suggestions for debugging this under Windows?
