### ISSUE TITLE
Running group_by and then do with R 3.2.1 and OS X Yosemite is spawning countless processes

### ISSUE THREAD

**Issue by ronert** [hadley/dplyr#1246]
Running group_by and then do with R 3.2.1 and OS X Yosemite is spawning countless processes that do not get cleaned up after computation.

Maybe related to this R news item: R is now trying harder to not cleanup child processes that were not spawned by
mcparallel() on platforms that provide information about the source process of the
SIGCHLD signal. This allows 3rd party libraries to manage the exit status of children
that they spawn without R interfering.

Screenshot: https://www.dropbox.com/s/1bainl9jwb8zl94/Screenshot%202015-07-03%2010.34.23.png?dl=0

Even after quitting the main R process, the child processes remain, hogging tons of memory.

**Comment by hadley** [comment]
Do doesn't do anything in parallel, so it's hard to believe it's dplyr that's causing that problem.

**Comment by ronert** [comment]
I am running fitdistr() from MASS within do (which in turn is running optim). Did not load any other libraries. Will investigate further.

**Comment by ronert** [comment]
Installing the latest version of dplyr from GitHub resolved the problem for me.
