### ISSUE TITLE
Build query - fix "AS"

### ISSUE THREAD

**Issue by tomasgreif** [hadley/dplyr#1247]
In `build_query` "AS" is used to generate subquery:

    from_sql <- build_sql("(", base_query$sql, ") AS ", ident(unique_name()),
          con = x$src$con)

This does not work for backends where "AS" cannot be used to name subquery. I believe that `sql_subquery` can be used easily instead.

**Comment by krlmlr** [comment]
Which specific DB backends does this apply to?

**Comment by tomasgreif** [comment]
This is specific to Oracle:

    select * from (select * from dual) x;
    select * from (select * from dual) as x; -- does not work

I tried to add Oracle backend to dplyr, and this was one of the major issues as `build_query` is burried pretty deep in the code.
