### ISSUE TITLE
Problem reading (many) NA's

### ISSUE THREAD

**Issue by Persican** [hadley/dplyr#1252]
The read_csv() guesses column type by reading the first xxx entries. If I try to read a csv file containing this data:

structure(list(V1 = 1:151, V2 = c(NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 141L, 142L, 143L, 144L, 145L, 146L, 147L, 
148L, 149L, 150L, 151L)), .Names = c("V1", "V2"), class = "data.frame", row.names = c(NA, 
-151L))

the function is not able to guess the second column type (V2) and throws an error:

> problems()
Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) : 
  argument "x" is missing, with no default

I guess this is probably because there are too many NA's at the beginning.

Cheers,
Phil

**Comment by mattdowle** [comment]
In case you weren't aware of data.table::fread, it uses a batch of rows in
the middle of the file and at the end, to guess column types.  Just for
this situation.  I suppose Hadley will port that idea to read_csv too and
that will take time.   It was a lot of effort to create fread and fix many
edge cases.  So I'm greatly saddened that Hadley and Romain decided to
create read_csv separately.

**Comment by hadley** [comment]
@mattdowle this is not the right venue for that sort of comment.

@Persican you need to call `problems(x)` where `x` is the object you created with `read_csv()`

**Comment by Persican** [comment]
> problems(t)
   row col       expected actual
1  141   2 T/F/TRUE/FALSE    141
2  142   2 T/F/TRUE/FALSE    142
3  143   2 T/F/TRUE/FALSE    143
4  144   2 T/F/TRUE/FALSE    144
5  145   2 T/F/TRUE/FALSE    145
6  146   2 T/F/TRUE/FALSE    146
7  147   2 T/F/TRUE/FALSE    147
8  148   2 T/F/TRUE/FALSE    148
9  149   2 T/F/TRUE/FALSE    149
10 150   2 T/F/TRUE/FALSE    150
11 151   2 T/F/TRUE/FALSE    151
