### ISSUE TITLE
Suggestion: totals() function

### ISSUE THREAD

**Issue by twolodzko** [hadley/dplyr#1253]
dplyr becomes more and more popular tool for data manipulation. In this area, for all kinds of sorting, re-arranging, filtering, subsetting etc. MS Excel is and was commonly used. One of the most commonly used Excel features are pivot tables - the functionality that is not directly availble in dplyr.

Simple way to compute "Totals" is: 

```r
mtcars %>%
   bind_rows(
      summarise_each(., 'sum')
   )
```

this is however clumsy since needs two other functions and possibly passing `.` arguments. It would be much better if there were `totals()` function with similar functionality, e.g.

```r
totals <- function(.data, ...) {
  if (missing(...)) {
    dots <- 'sum'
  } else {
    dots <- lazyeval::lazy_dots(...)
  }

  if (length(dots) > 1) {
    out <- dplyr::summarise_(.data, .dots = dots)
  } else {
    vars <- colnames(.data)[unlist(lapply(.data, is.numeric))]
    out <- dplyr::summarise_each_(.data, funs = dots, vars = vars)
  }

  dplyr::bind_rows(.data, out)
}
```

Alternatively some variants like `bind_summaries` or `bind_mutate` could be created instead.

This is just a suggestion of a simple function that could make dplyr even more marvelous.

**Comment by hadley** [comment]
Can you please provide a small example of expected output?

**Comment by twolodzko** [comment]
The general idea is to add "Total" row to data frame, that summarizes the columns:

```r
> mtcars %>% totals() %>% tail
# Source: local data frame [6 x 11]
# 
#     mpg cyl   disp   hp   drat      wt   qsec vs am gear carb
# 1  30.4   4   95.1  113   3.77   1.513  16.90  1  1    5    2
# 2  15.8   8  351.0  264   4.22   3.170  14.50  0  1    5    4
# 3  19.7   6  145.0  175   3.62   2.770  15.50  0  1    5    6
# 4  15.0   8  301.0  335   3.54   3.570  14.60  0  1    5    8
# 5  21.4   4  121.0  109   4.11   2.780  18.60  1  1    4    2
# 6 642.9 198 7383.1 4694 115.09 102.952 571.16 14 13  118   90
```

Example: in rows you have different factories and in columns some variables describing their performance, in this case `totals()` helps you to learn what is the total performance (say a sum on different factories). If you are interested only in summary statistics, then `summarise` or `summarise_each` can be used, however if you use your data frame as output (paste it directly into report), than it would be nice to have both individual and total values in single table. The idea of `totals()` is to provide a single function shortcut for both summarizing and binding the output to the initial data frame. This function may be thought as `mutate` working row-wise rather then column-wise as dplyr's `mutate` works. Hope my description is clear..?

**Comment by hadley** [comment]
Currently, I'd say this is out of scope for dplyr, since it's specifically about making output for publication, rather than further processing in R.
