### ISSUE TITLE
"Incompatible types" error in dplyr 0.4.2 on linux but not in Windows

### ISSUE THREAD

**Issue by ellisp** [hadley/dplyr#1254]
I have a complex Shiny app deployed to shinyapps.io.  With the upgrade to dplyr 0.4.2 the version deployed to shinyapps.io (hence on linux) stopped working, whereas the Windows versions on local machines is still OK.  The shinyapps log shows the error killing the app to be:
```
incompatible types, expecting a numeric vector
```
which Google shows comes from somewhere within dplyr (other people's past issues, now resolved; and the gatherer.h file in the dplyr code repo).

Rolling back to dplyr 0.4.1, with no changes to the code of the app, and both versions work fine.

Unfortunately, the app is large and complex and there are many parts of it that have group_by and mutate which might be the location of the problem so I can't do a minimal reproducible example.  Worse, it uses embargoed data, so I can't even publish the code and data of the problematic app just yet.  However I am confident:
* the problem is only in Linux, not Windows (although I don't know why - might be some quirk in my data and how it's read on different platforms, interacting with a weakness in dplyr)
* it is only in dplyr 0.4.2, not dply 0.4.1

Some time down the track when at work I can try going through it line by line on a linux machine with 0.4.2 on it to see where the actual error is and if you're interested I'll post the results here, but it might be a while off.  In the meantime, 0.4.1 works.

**Comment by hadley** [comment]
Should be fixed in the dev version.
