### ISSUE TITLE
filter doesn't behave as expected, possibly a non-standard evaluation issue

### ISSUE THREAD

**Issue by shntnu** [hadley/dplyr#1256]
P <- list(d1 = iris, d2 = iris, d3 = iris)

    # this gives an error
    # Error: invalid subscript type 'integer'
    dim(dplyr::filter(P$d1, Species %in% P$d2$Species))

    # this works fine
    x <- P$d2$Species
    dim(dplyr::filter(P$d1, Species %in% x))
    
    # this works fine
    names(P$d3) <- paste("d3", names(P$d3), sep = "_")
    dim(dplyr::filter(P$d1, Species %in% P$d3$d3_Species))

    # R version 3.2.1 (2015-06-18)
    # Package dplyr version 0.4.2

**Comment by hadley** [comment]
Another example of #1400
