### ISSUE TITLE
hybrid handling of `%in%`

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#126]
e.g. 

```
filter( ., a %in% c("a", "b", "c" ) )
```

We need a hybrid handler for `%in%`

**Comment by lsusatyo-gcmlp** [comment]
Regarding the handling of %in% for local environment. The following also caused an issue:

tmp <- new.env()
tmp$info <- data.frame(Id=c(1,2,3), Value=c('a', 'b', 'c'))

foo <- data.frame(Id=c(1,2,3))

# not working
foo %>% filter(Id %in% tmp$info$Id)

# working
foo %>% filter(Id %in% c(1,2,3))
