### ISSUE TITLE
the group_by&summarise behavior seems being affected by the global option stringsAsFactors

### ISSUE THREAD

**Issue by shrektan** [hadley/dplyr#1261]
Hi, I just installed your latest development version of `dplyr`. However, I notice an issue that is **the group_by&summarise behavior seems being affected by the global option stringsAsFactors**. 

With the **Mini Repro** that I provided below, I will get the correct output if I don't touch the `stringAsFactors`, but I will get this if I execute `options(stringsAsFactors = FALSE)` before the code.

### MINI REPRO

```r
library(dplyr)
options(stringsAsFactors = FALSE) 

tmp <- data.frame(a = c(1, 1, 1, 2, 2), b = NA_character_, value = 1:5)
tmp %>% group_by(a, b) %>% summarise(value = sum(value))
```

### The "wrong" result
```
Source: local data frame [5 x 3]
Groups: a

  a  b value
1 1 NA     1
2 1 NA     2
3 1 NA     3
4 2 NA     4
5 2 NA     5
```

### The wanted result

```
Source: local data frame [2 x 3]
Groups: a

  a  b value
1 1 NA     6
2 2 NA     9
```

I know, from hadley's adv-r that it's not a good practice to change the global option of `stringAsFactors`. But, I've made a lot of programs before reading the book and I haven't met anything unusual yet... So, it would be a pain not to set the global option before my existing code..

Also, I'm wondering if this is something you intentionally to do or just accidentally....

Thanks!

**Comment by hadley** [comment]
Yes, because `data.frame()` uses the global stringsAsFactors setting. That's one reason we wrote `data_frame()`

**Comment by hadley** [comment]
Ok, the real problem is unrelated to `stringsAsFactors` - something seems to be going wrong with grouping of character missing values:

```R
tmp <- data_frame(
  a = c(1, 1, 1, 2, 2), 
  b1 = NA_integer_ 
  b2 = NA_character_
)
str(tmp)

tmp %>% group_by(a, b1) %>% summarise(n())
#>   a b1 n()
#> 1 1 NA   3
#> 2 2 NA   2
tmp %>% group_by(a, b2) %>% summarise(n())
#>   a b2 n()
#> 1 1 NA   1
#> 2 1 NA   1
#> 3 1 NA   1
#> 4 2 NA   1
#> 5 2 NA   1
```

**Comment by hadley** [comment]
@romainfrancois can you please take a look when you back up and running?

**Comment by romainfrancois** [comment]
I seems it has been accidentally fixed.

```
>   tmp <- data_frame(
+     a = c(1, 1, 1, 2, 2),
+     b1 = NA_integer_,
+     b2 = NA_character_
+   )
>
> str(tmp)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	5 obs. of  3 variables:
 $ a : num  1 1 1 2 2
 $ b1: int  NA NA NA NA NA
 $ b2: chr  NA NA NA NA ...
> tmp %>% group_by(a, b1) %>% summarise(n())
Source: local data frame [2 x 3]
Groups: a

  a b1 n()
1 1 NA   3
2 2 NA   2
> tmp %>% group_by(a, b2) %>% summarise(n())
Source: local data frame [2 x 3]
Groups: a

  a b2 n()
1 1 NA   3
2 2 NA   2
```

 I pushed a regression test anyway.
