### ISSUE TITLE
ifelse loses posixct type

### ISSUE THREAD

**Issue by takje** [hadley/dplyr#1263]
Hi,

I am using ifelse in a mutate and noticed that it casts the datatype to numeric if the type is POSIXct.

Example:
```
> x <- as.POSIXct(now())
> class(x)
[1] "POSIXct" "POSIXt" 
> y <- ifelse(T,x,x)
> class(y)
[1] "numeric"
```

Therefore I have to manually cast the types which leads to more ugly code and possible mistakes. Maybe you could do a check to not cast it as numeric if both sides (TRUE/FALSE) are of the same type.

Don't know if it's a bug or a feature.

**Comment by romainfrancois** [comment]
This is not a dplyr problem. `ifelse` is a base R function.
