### ISSUE TITLE
Encoding in bind_rows

### ISSUE THREAD

**Issue by hughjonesd** [hadley/dplyr#1265]
Just came across this, possibly related to #1257.

```R
one <- data.frame(fü=1:3, bar=1:3)
two <- data.frame(fü=1:3, bar=1:3)
names(one) == names(two)
bind_rows(one, two)
Encoding(names(one)[1]) <- "UTF-8"
names(one) == names(two)
bind_rows(one, two) # three columns!
```

**Comment by hughjonesd** [comment]
A related point is that `select()` changes the encoding of names, when it encounters e.g. an umlaut.

**Comment by romainfrancois** [comment]
@hughjonesd can you open another issue, with a reproducible example about the behavior of `select` please.
