### ISSUE TITLE
Error when using coordinates in tbl

### ISSUE THREAD

**Issue by hmorzaria** [hadley/dplyr#1267]
Data is a set of species occurrences with 4 columns, species name, source, lat and lon
I am using readxl to read in excel sheets, so the data is automatically converted to tbl_df

In this command

```r
coordinates(mydata) <- c("Longitud", "Latitud") 

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘coordinates<-’ for signature ‘"tbl_df"’
```

**Comment by hmorzaria** [comment]
I dropped tbl_df to remove the error, but was wondering if there was another way of addressing this

**Comment by hadley** [comment]
Please provide a minimal reproducible example
