### ISSUE TITLE
slice(df, n) returns all rows if n > nrow(df)

### ISSUE THREAD

**Issue by sfirke** [hadley/dplyr#1269]
`slice()` does not behave as expected based on the description in `manip.R` which states that "Equivalent code using filter that will also work with databases" is:
`filter(mtcars, row_number() == 1L)`

But in the following example they differ.  I expected the output I got with `filter(row_number() == n))`

Using the mtcars data:

`mtcars %>%
  group_by(cyl) %>%
  tally()`
`# there are 7 cars with cyl == 4`

This produces the output I would expect, 2 records:
`mtcars %>%
  group_by(cyl) %>%
  filter(row_number() == 8)`

While this returns a confusing 8 records:
`mtcars %>%
  group_by(cyl) %>%
  slice(8)`

My use case was studying duplicates, using `group_by()` and then `slice(2)` or `slice(3)` but they returned the same result.  I expected and wanted a smaller N for `slice(3)`, omitting groups with no 3rd row.

**Comment by romainfrancois** [comment]
I'm getting: 

```
> slice_res <- mtcars %>% group_by(cyl) %>% slice(8)
> filter_res <- mtcars %>% group_by(cyl) %>% filter( row_number() == 8 )
> equal_data_frame( slice_res, filter_res )
TRUE
> slice_res
Source: local data frame [2 x 11]
Groups: cyl

   mpg cyl disp  hp drat    wt  qsec vs am gear carb
1 27.3   4   79  66 4.08 1.935 18.90  1  1    4    1
2 14.7   8  440 230 3.23 5.345 17.42  0  0    3    4
```

Did you test this on the dev version ?

**Comment by sfirke** [comment]
Ah I was not using the dev version, I have now installed it and I get the expected results.  Thanks!
