### ISSUE TITLE
Missing blanks in setequal's output

### ISSUE THREAD

**Issue by helix123** [hadley/dplyr#1278]
dplyr 0.4.2:

    df1 <- data_frame(x = as.numeric(1:2), y = as.numeric(c(1, 1)))
    df2 <- data_frame(x = as.numeric(1:2), y = as.numeric(c(1:2)))
    dplyr::setequal(df1, df2)

    ## FALSE: Rows in x but not y: 2Rows in y but not x: 2Rows with difference occurences in x and y: 2, 2

Two missing blanks spotted after output of row numbers (in the above example: "2Rows" (2x)).

**Comment by romainfrancois** [comment]
Now getting. 

```r
> dplyr::setequal(df1, df2)
FALSE: Rows in x but not y: 2. Rows in y but not x: 2.
```

So I believe this has been fixed elsewhere.
