### ISSUE TITLE
a problem related to translate_sql for %in% operator

### ISSUE THREAD

**Issue by shrektan** [hadley/dplyr#1282]
Hi, when I execute `translate_sql(x %in% c("a"))`, the expected result should be:

```
<SQL> "x" IN ('a')
```

However, in `dplyr 0.4.1` the result turns out to be:

```
<SQL> "x" IN 'a'
```
Notice that the `a` doesn't surrounded with `(`and `)`. Thus, this SQL can't be executed.

**Comment by hadley** [comment]
Duplicate of #511
