### ISSUE TITLE
segfault in mutate

### ISSUE THREAD

**Issue by bered** [hadley/dplyr#1292]
i am very new to r and if the errors are my fault, then my apologies.
here is a minimal example which produces often, but not always segfaults OR wrong results, depending on the size of myn. for myn=100 or 1000 it usually works, but for 10⁵ or 10⁶ it does not.
here the code:

library(dplyr)
myn <- 100000
df <- data_frame(x=rep(1:5,myn))
df <- df %>% mutate(infirst=ifelse(x==1,TRUE,FALSE),insecond=ifelse(x==1 | x==2, TRUE, FALSE), inthird=ifelse(x==1 | x==2 | x==3,TRUE,FALSE))
head(df)

system:
linux mint 17.2
latest rstudio
r 3.2.1
dplyr: latest version from cran, not tested on developer version (i dont know how to do that yet...)

thank you!
reinhard

**Comment by andeek** [comment]
I had a similar issue. It seems to be fixed in the version on github, or at least the problem went away for me.

To install from github using `devtools`, 

```
devtools::install_github("hadley/dplyr")
```

Hopefully that works for you too!

**Comment by bered** [comment]
thank you!!!
worked for me too!!!
