### ISSUE TITLE
Alternative for Standard 'apply' Function Which Does Not Coerce Column Data Types

### ISSUE THREAD

**Issue by amormachine** [hadley/dplyr#1294]
Consider using the standard R function *apply* as follows:

    # Your_Function Pseudo-Code
    if Your_DataFrame['Birthday'] in January {
        return("Happy January Birthday!")
    }
    
    # Your DataFrame Structure
    Your_DataFrame =
     Birthday      |   Name
     2015-01-01    |    Bob
     1996-03-05    |  Susie

     apply(Your_DataFrame, MARGIN = 1, FUN = Your_Function)

The problem here is that *apply* will coerce all columns in a dataframe to the least specific datatype (likely string).  In the above example, this will ensure that the Birthday value is no longer a date, but rather a string.  To account for this the user must re-cast the data-types in the function:

    # Your_Function Pseudo-Code
    if as.Date(Your_DataFrame['Birthday']) in January {
        return("Happy January Birthday!")
    }

This appears to be a relatively common problem (links below), and with larger data-frames and more complex problems an annoying one.  dplyr could potentially create a superior function which acts like apply, but passes a single-row-dataframe to the function.  This would allow the data types to be preserved.

* http://stackoverflow.com/questions/7303322/apply-function-to-each-column-in-a-data-frame-observing-each-columns-existing-da
* http://stackoverflow.com/questions/2288485/how-to-convert-a-data-frame-column-to-numeric-type

**Comment by hadley** [comment]
`rowwise()` + `do()` ?
