### ISSUE TITLE
`mutate` on non-small datasets sometimes crashes

### ISSUE THREAD

**Issue by daattali** [hadley/dplyr#1297]
Using the following code as an example:

```
df <- data.frame(a = 1:1e5, b = "b", c = "c")
lapply(1:50, function(x) {
  message(x)
  df2 <- dplyr::mutate(df, d = "d", e = "e", f = "f")
  NULL
})
```

Starting with a dataframe with 100,000 rows and 3 cols, use mutate to add another 3 cols. Repeat 50 times.  Sometimes it runs to completion. Sometimes the R session simply freezes at a random iteration.  A few times I got the error

```
Error in structure(.Call(C_objectSize, x), class = "object_size") : 
  unimplemented type (31) in 'object.size'
```

If I lower the initial number of rows to 10,000 nothing ever goes wrong.

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.1
```

Is this simply a matter of insufficient memory?  I'm very puzzled by the fact that the behaviour is inconistent

**Comment by romainfrancois** [comment]
Did you try on the dev version of dplyr ? I can't reproduce the problem. I 'm pretty sure this is part of the fixes from early july.

**Comment by daattali** [comment]
Yes you're right, using the dev version I don't get the error anymore. Wish I knew that yesterday, would have saved me 10 agonizing hours :)

**Comment by daattali** [comment]
Maybe "reopening" is not the correct action here, but I ended up going back to the old dplyr (0.4.2) because the dev version is exponentially slower. I haven't figured out where/what function exactly, but running my complex application just got extremely slow, after after removing the dev version and installing the CRAN version of dplyr, it went back to being fast.

**Comment by romainfrancois** [comment]
Do you have something I can use to help you. What is it slow on, can you spare some reprex please.
