### ISSUE TITLE
dev version 0.4.2.9002 exponentially slower

### ISSUE THREAD

**Issue by daattali** [hadley/dplyr#1298]
In reference from https://github.com/hadley/dplyr/issues/1297, after updating to the github version my app became many orders of magnitude slower, and reverting to 0.4.2 from CRAN fixed it.  It's a little hard to pinpoint exactly where the slowness is happening without spending too much time debugging, but I was able to find one function already that is much slower:

bind_rows appears to be very slow when the data.frames have character data that aren't factors.  I'm sure that's not the correct diagnosis, it's probably something else underlying the issue, but I was able to see a huge difference in time when `bind_rows` is used on data.frames that have character vs factor data.

Running the following on 0.4.2.9002 from August 1, 2015:

```
factored <- function() dplyr::bind_rows(lapply(1:100, function(x) data.frame(num = rep(x, 10000), foo = "n")))
nonfactored <- function() dplyr::bind_rows(lapply(1:100, function(x) data.frame(num = rep(x, 10000), foo = "n", stringsAsFactors = FALSE)))
microbenchmark::microbenchmark(factored(), nonfactored(), times = 50)
```

I get the following benchmark results:

```
Unit: milliseconds
          expr        min         lq       mean     median         uq        max neval
    factored()   56.74945   58.18734   80.52821   95.54773   96.05794   96.09862     50
 nonfactored() 1349.52833 1355.83228 1431.15372 1380.02105 1419.75325 1650.63368     50
```

If I run it again on version 0.4.2, there is no difference between the two versions.

I suspect there are other functions that are also much slower now because every single step in my pipelined app is much slower, but this is the first one I was able to pinpoint.

**Comment by hadley** [comment]
@romainfrancois I hope this isn't because of the encoding stuff :/

**Comment by romainfrancois** [comment]
Not according to my quick test of removing the call to `enc2native` in `bind.cpp`. And anyway the encoding stuff here is about the column names, so both versions would suffer from the problem. 

It seems even worse on my machine once I've taken out the confusion factor from the `lapply` call: 

```
factored_data <- lapply(1:100, function(x) data.frame(num = rep(x, 10000), foo = "n"))
nonfactored_data <- lapply(1:100, function(x) data.frame(num = rep(x, 10000), foo = "n", stringsAsFactors = FALSE))
microbenchmark(bind_rows(factored_data), bind_rows(nonfactored_data), times = 50)
Unit: milliseconds
                        expr       min        lq      mean    median        uq
    bind_rows(factored_data)  11.99075  13.13598  15.29068  13.73093  16.54874
 bind_rows(nonfactored_data) 383.25579 391.55444 396.70660 394.28897 396.70215
       max neval
  23.57433    50
 511.42802    50
```

**Comment by romainfrancois** [comment]
That's an odd one. We had this line : 

```
DataFrameVisitors visitors( df, df.names() ) ;
```

which apparently was causing the perf regression, but we just never used `visitors`. Now getting this: 

```
> microbenchmark(bind_rows(factored_data), bind_rows(nonfactored_data), times = 50)
Unit: milliseconds
                        expr      min       lq     mean   median       uq      max neval
    bind_rows(factored_data) 13.98436 15.24890 17.44338 16.46811 17.55896 26.34390    50
 bind_rows(nonfactored_data) 12.85788 14.28588 17.19788 15.05221 19.57517 28.36226    50
```

which is more to my taste. @daattali I've closed this now. Feel free to open other issues if you find other performance regressions. 

The reason why visitors over character vectors are slower is indeed related to encoding, i.e. : 

```
VectorVisitorImpl( const CharacterVector& vec_ ) : vec(vec_){
            Language call( "rank", vec, _["ties.method"] = "min" ) ;
            orders = call.eval() ;
        }
```

This is once again because C/R API does not give us a way to compare two individual strings. So we have this huge memory and time waste each time we make a visitor over a character vector.

**Comment by romainfrancois** [comment]
There are places however where visitors are only used for subsetting capabilities and not hashing, ordering, e.g. this call in `arrange.cpp`: 

```
DataFrame res = DataFrameVisitors( data, data.names() ).subset( master_index, data.attr("class" ) ) ;
```

So perhaps it's time to have a look back. 

This also cries for a more systematic tool for diagnosing performance regressions.

**Comment by daattali** [comment]
Thanks for the fast fix.  I'm still experiencing my app being much slower using today's version over CRAN... I'll try to see if I find another example that's reproducible, but yes I do think i'd be a great idea to have performance regressions tests in place

**Comment by daattali** [comment]
OK was able to get another reprex, this time `arrange_`, and similarly it happens when the df is not factored (I didn't understand any of the technical stuff you guys discussed so I'll ignorantly say it's related to nonfactored data):

```
factoreddf <- data.frame(x = 1:1e6, y = "a")
nonfactoreddf <- data.frame(x = 1:1e6, y = "a", stringsAsFactors = FALSE)
factored <- function() dplyr::arrange_(factoreddf, ~ x)
nonfactored <- function() dplyr::arrange_(nonfactoreddf, ~ x)
microbenchmark::microbenchmark(factored(), nonfactored(), times = 10)
```

Using dplyr from Aug 3, 2015 at 11am PST I get

```
Unit: milliseconds
          expr       min        lq      mean    median       uq       max neval
    factored()  137.1338  137.2456  174.2336  149.0118  180.579  349.3572    10
 nonfactored() 2094.7260 2114.0007 2162.2075 2135.4139 2188.226 2300.9723    10
```

Using 0.4.2 there is no difference between the two.

Again, I suspect there are more functions that are suffering from performance regression because every single step of my program is slower.

**Comment by romainfrancois** [comment]
I think i know what the problem might be, i've started to put things in place, needs a bit more work. 

Could you move it into another issue please.

**Comment by daattali** [comment]
One last example, this time `filter_` (I'm not going to try more functions, going back to my work after this):

```
factoreddf <- data.frame(x = rep(letters, 10000))
nonfactoreddf <- data.frame(x = rep(letters, 10000), stringsAsFactors = FALSE)
factored <- function() dplyr::filter_(factoreddf, ~ x == "d")
nonfactored <- function() dplyr::filter_(nonfactoreddf, ~ x == "d")
microbenchmark::microbenchmark(factored(), nonfactored(), times = 10)
```

dev version:

```
Unit: milliseconds
          expr        min         lq       mean     median         uq       max neval
    factored()   18.12856   18.51892   45.89027   19.67587   25.64279  243.4634    10
 nonfactored() 1409.14734 1449.10019 1477.18425 1456.73940 1496.66659 1608.2936    10
```

CRAN version: nonfactored is actually faster (maybe not significant though)
