### ISSUE TITLE
n_distinct(x) slower than length(unique(x))

### ISSUE THREAD

**Issue by dgrtwo** [hadley/dplyr#1304]
Contrary to the `n_distinct` documentation, the function seems to be slower than `length(unique(x))` for most numeric and character vectors up to length ~10,000. In particular, it is much slower for long vectors made up mostly of unique elements.

A simple example is:

```r
library(microbenchmark)
library(dplyr)

x <- 1:1e4

microbenchmark(length(unique(x)), n_distinct(x))
```

for which I find `length(unique(x))` about 4 times faster.

A more detailed simulation and graph exploring the effect of length and uniqueness is below, also shown [here](http://rpubs.com/dgrtwo/length_unique_vs_n_distinct).

```r
library(dplyr)
library(microbenchmark)

set.seed(2015-08-05)

time_distinct <- function(uniques, len, class) {
  x <- sample(uniques, len, replace = TRUE)
  x <- as(x, class)
  m <- microbenchmark(n_distinct(x),
                      length(unique(x)), 
                      times = 1000L)
  ret <- summary(m)
  ret$uniques <- length(unique(x))
  ret
}

timings <- expand.grid(uniques = round(10 ^ seq(0, 5, 1)),
                       len = round(10 ^ seq(1, 4, 1)),
                       class = c("numeric", "character"),
                       stringsAsFactors = FALSE) %>%
  group_by(uniques, len, class) %>%
  do(do.call(time_distinct, .))

library(ggplot2)

ggplot(timings, aes(uniques, median, color = expr, lty = class)) +
  geom_line() +
  scale_x_log10() +
  geom_errorbar(aes(ymin = lq, ymax = uq), width = .1) +
  facet_wrap(~ len, scales = "free") +
  xlab("Number of unique elements in vector") +
  ylab("Median time")
```

![image](https://cloud.githubusercontent.com/assets/994718/9093910/dd6bbc10-3b7c-11e5-9fde-610b81e9a6ef.png)

**Comment by romainfrancois** [comment]
Thanks, but this has been already filed. Perhaps you can add your analysis to the original issue.

**Comment by hadley** [comment]
How about a pointer to that issue??

**Comment by dgrtwo** [comment]
@hadley https://github.com/hadley/dplyr/issues/977
