### ISSUE TITLE
Feature request: make drop rows procedure memory efficient

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1305]
I'm not sure this is possible, but it would be good to be able to drop rows in a memory efficient way. This demonstrates the problem:

    library(dplyr)
    
    n <- 100000000
    x <- data.frame(val = rnorm(n))
    x$name = sample(c("A", "B", "C"), size = n, replace = TRUE)
    gc()
    # 1574MB used in task manager
    
    # Drop rows in dplyr
    x <- x %>% filter(name == "A")
    # Memory used jumps to 2847MB
    gc() # Down to 556MB
    
    x <- data.frame(val = rnorm(n))
    x$name = sample(c("A", "B", "C"), size = n, replace = TRUE)
    gc()
    # 1574MB used in task manager
    x <- x[x$name == "A",]
    # Jumps to 3355MB - base isn't better.
    gc() # down to 683MB

**Comment by hadley** [comment]
It's unlikely this is a real effect. Accurately collecting memory usage in R is hard, and just looking at os memory statistics is not adequate.
