### ISSUE TITLE
Feature request: add variable labels to the tbl_df class

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1307]
Variable labels are one of the few remaining features that are nicer in Stata. These are used for variable descriptions that are longer than appropriate for a title.

The call would be something like:

    my_tbl_df %>% select(my_var_1, my_var_2) %>% labels()

And the output would be a character vector of the variable labels for ``my_var_1`` and ``my_var_2``.

**Comment by hadley** [comment]
I don't see this as being key to dplyr, sorry.
