### ISSUE TITLE
R session crash with %>%

### ISSUE THREAD

**Issue by r2evans** [hadley/dplyr#1309]
This may be similar or the same bug as several other issues, but they all appear to be triggered by specific events/functions; this is generic enough that it may apply or be something completely different.

The R session crashes (or sometimes "hangs" busily) with just `mutate` or `transmute`. The "when" of a crash is unpredictable, but I can always crash it with enough replications:

```r
library(dplyr)
for (i in 1:10000) ign <- replicate(10, {ign=mtcars %>% mutate(a=c(NA,diff(hp)))})
```

Sometimes 100 times works, sometimes 50000 is needed multiple times to get a crash. The system is not otherwise task-saturated. (Though I am using a for-loop here, I initially played with `replicate` with similar results.)

It behaves the same with `transmute` in place of `mutate`, perhaps no surprise. If I use `mtcars %>% mutate(a=lag(hp))`, I have not seen it hang, nor have I seen it hang with `arrange(mpg)` or similar.

When it fails, it usually full-up crashes. Infrequently, it just hangs "busily"; I can see no appreciable change in CPU or memory usage. At one point, when I was repeatedly trying to crash it, I started timing things so I knew how long to do something else before coming back to check.

```r
system.time({for (i in 1:50000) ign <- mutate(mtcars, a=c(NA, diff(hp)))})
## Error in structure(NextMethod(), class = "lazy_dots") (from #1) : 
##   GC encountered a node (0x000000000c04b470) with an unknown SEXP type: BUILTINSXP at memory.c:999
## Timing stopped at: 15.28 0 15.44 
```

Does this help at all? (It doesn't always err like this, it occasionally just hangs here as well.) Even more interesting to me is that immediately after this error, I tried 

```r
system.time({for (i in 1:50000) ign <- mutate(mtcars, a=lag(hp))})
```

and it crashed, despite my previous statement that I never saw `lag` produce a crash.

Anecdotally, it seems to crash less often with `mutate(mtcars, a=c(NA,diff(hp)))` than it does with `mtcars %>% mutate(a=c(NA,diff(hp)))`, but I don't have hard numbers on it.

I cannot reproduce it on ubuntu-14.04, so I believe it's a windows thing.

R-3.2.1, dplyr-0.4.2 and dplyr-0.4.2.9002

**Comment by codref** [comment]
I experienced the very same issue (on windows), the only workaround was to revert to an older version of the library. Unfortunately the Access Violation exception seems to appear "randomly", I do not have the expertise to provide you further details, except the [ADplus log](https://gist.github.com/codref/97c8bd3bbd9f08f0ac62)

**Comment by romainfrancois** [comment]
I cannot reproduce it locally on OSX. I'd bet it's the same as #1231. 

(BTW 0.4.1.9002 does not clearly identify which version you mean, it just means it's a version after a given fix). 

Do you still see the problem with the dev version ?

**Comment by r2evans** [comment]
I just did a pull and cannot reproduce the problem, thanks Romain! I had read #1231 and thought it was perhaps different. I also had done a git pull, but apparently I didn't get it recent enough. Thanks.

**Comment by romainfrancois** [comment]
Symptoms were different, but the cause wzs the same i guess
