### ISSUE TITLE
`summarize_`,`filter_`,etc... not finding functions in GlobalEnv.

### ISSUE THREAD

**Issue by lgautier** [hadley/dplyr#1323]
The example below should be self-explanatory:

```r
> require("dplyr")
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> my_mean <- function(x) {
+   mean(x)
+ }
> mtcars %>% group_by(gear) %>% summarize(mean_hp=my_mean(hp))
Source: local data frame [3 x 2]

  gear  mean_hp
1    3 176.1333
2    4  89.5000
3    5 195.6000
> mtcars %>% group_by(gear) %>% summarize_(mean_hp="my_mean(hp)")
Error: could not find function "my_mean"
```

```r
> sessionInfo()
R version 3.2.2 Patched (2015-08-15 r69082)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.2

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.0        assertthat_0.1 
[5] parallel_3.2.2  DBI_0.3.1       tools_3.2.2     Rcpp_0.12.0  
```

**Comment by romainfrancois** [comment]
Works fine for me on the dev version.

```
> my_mean <- function(x) { mean(x) }
> mtcars %>% group_by(gear) %>% summarize(mean_hp=my_mean(hp))
Source: local data frame [3 x 2]

  gear  mean_hp
1    3 176.1333
2    4  89.5000
3    5 195.6000
```

**Comment by romainfrancois** [comment]
oops sorry about that. I can reproduce

**Comment by romainfrancois** [comment]
I guess it's a problem with the `lazy_dots` object created and the environment it wants to use. @hadley ?

```
> debug( summarise_.tbl_df )
> mtcars %>% group_by(gear) %>% summarize_(mean_hp="my_mean(hp)")
debugging in: summarise_.tbl_df(., mean_hp = "my_mean(hp)")
debug at /Users/romain/git/dplyr/R/tbl-df.r#187: {
    dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
    summarise_impl(.data, dots)
}
Browse[2]> n
debug at /Users/romain/git/dplyr/R/tbl-df.r#188: dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
Browse[2]> n
debug at /Users/romain/git/dplyr/R/tbl-df.r#189: summarise_impl(.data, dots)
Browse[2]> dots
$mean_hp
<lazy>
  expr: my_mean(hp)
  env:  <environment: base>  # <<<<<<-------- 

attr(,"class")
[1] "lazy_dots"
```

**Comment by lgautier** [comment]
Seems to confirm what I was observing empirically: only objects either in the `base` namespace or in the data frame/table are found.

Whatever `lazyeval::all_dots()` is supposed to do (the documentation is not too explicit about it),  it ends up with the following happening (the R debugger seems a little challenged here and unable to execute the code step by step):
```
> as.lazy_dots(list(mean_hp="my_mean(hp)"))
$mean_hp
<lazy>
  expr: my_mean(hp)
  env:  <environment: base>

attr(,"class")
[1] "lazy_dots"
```

Basically `as.lazy_dots()` is assuming that anything and everything is located in the base namespace:

```r
> lazyeval:::as.lazy_dots.character
function (x, env = baseenv()) 
{
    structure(lapply(x, as.lazy, env = env), class = "lazy_dots")
}
<environment: namespace:lazyeval>
```

It is tempting to recommend to change this default to `.Globalenv`.

**Comment by kevinushey** [comment]
A version of this issue should probably be filed in https://github.com/hadley/lazyeval, perhaps?

**Comment by lgautier** [comment]
I first thought so but after following a little what the code is doing (and trying to guess what it was meant to do):
- I am not quite sure about what `lazyeval` is really meant to be/do
- The issue might with `dplyr` and the way it is trying to handle strings as if they were language objects.

**Comment by kevinushey** [comment]
At least, my expectation is that the evaluation environment for a `lazy_dots` object should be the same environment where it's created (ie, whatever `environment()` returns).

That said, I imagine @hadley has thought about this a lot more carefully than I have, or it's possible that it's `dplyr`'s responsibility to explicitly choose the evaluation environment somewhere.

**Comment by lgautier** [comment]
`lazy_dots()` is not called, AFAIUI.

**Comment by lgautier** [comment]
Erratum:

My proposed fix seems correct:
```r
mtcars %>% group_by(gear) %>% my_summarise_(mean_hp="my_mean(hp)")
```

I had forgotten the quotes.

**Comment by lgautier** [comment]
I could put together a pull request...

**Comment by romainfrancois** [comment]
Please @lgautier do.

**Comment by lgautier** [comment]
I made a pull request for the package `lazyeval` as an initial step (seemed to fix an API issue within `lazyeval` independently of whether the fix I propose for `dplyr` is correct).

Now when looking at the details of what would be a proper fix for `dplyr`, there would be quite a bit to change. Basically all transformation functions are affected by the issue (not only `summarize`) and this would turn more into a fixing a design issue rather than a mere bug: an environment parameter would have to be added to all code paths upstream of calls to `lazyeval::all_dots` (which would mean the calling frame at the top level). And this might only be an initial fix.

A confirmation that, in the light of the above, this is really the way to seems necessary...

**Comment by hadley** [comment]
This is as documented. If you want to use something other than the global environment, use a formula or a lazy dots object, not a string.

**Comment by lgautier** [comment]
The current document can lead one to understand otherwise: 

> There are three ways to quote inputs that dplyr understands:
>
> With a formula, ~ mean(mpg).
> With quote(), quote(mean(mpg)).
> As a string: "mean(mpg)".

(see https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html#standard-evaluation-basics)

For example, the very same example would not work if changing `mean` to `mad` (as it is defined in the namespace `stats` rather than in `base`).

Does accepting string makes much sense if limited to the base namespace ?

**Comment by hadley** [comment]
Accepting a string is definitely a crutch, but some people need it.

**Comment by romainfrancois** [comment]
But it does not use the global environment, but the base environment. I would tend to agree that it is too restrictive. The way I've seen this feature being used, strings are constructed using things from global or local environment within a function. 

It is easy enough to use `interp` but people are usually more skilled with `paste` etc ...

**Comment by lgautier** [comment]
`lazyeval::interp.character` seems broken: https://github.com/hadley/lazyeval/issues/35

Could it be that the use of strings was mostly (solely ?) tested with the function `mean()`... which happens to be in the base namespace ?

**Comment by lgautier** [comment]
The use of `quote()` as advertised in the NSE vignette seems to confirm this:
https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html#standard-evaluation-basics
```
> dplyr::summarise_(mtcars,
+                   mad_hp=quote(mad(hp)))
Error: could not find function "mad"
> dplyr::summarise_(mtcars,
+                   mean_hp=quote(mean(hp)))
   mean_hp
1 146.6875
```

Explicitly specifying the namespace appears to help:
```
> dplyr::summarise_(mtcars,
                                 mad_hp=quote(stats::mad(hp)))
   mad_hp
1 77.0952
```

But this is also the case with strings. The benefit of trying to use `quote()` is unclear...

```
> dplyr::summarise_(mtcars,
                                 mad_hp="stats::mad(hp)")
   mad_hp
1 77.0952
```
