### ISSUE TITLE
Slice by group

### ISSUE THREAD

**Issue by zslastman** [hadley/dplyr#1331]
I often want to subset my data in such a way that groups of things are conserved, e.g. when testing code that will eventually run on a large dataset. I find the following function very useful.

```r
group_slice<-function(dt,v){
  stopifnot('data.frame'%in%class(dt))
  stopifnot(v>0,(v%%1)==0)
  if(n_groups(dt)>=2) warn('Only 1 group to slice')
  #get the grouping variables
  groups=
    unique(dt%>%select())%>%
    group_by()%>%
    slice(v)
 #subset our original data
  out=inner_join(dt,groups)
  out
}
mtcars%>%group_by(gear,carb)%>%group_slice(1:2)
```

There's probably a faster way of getting this done. Maybe worth including in the main package? I also have a version that takes a random number of groups.

**Comment by hadley** [comment]
I think the key to solving this is to provide more pronouns, like data.table does. Then you could do (e.g.) `filter(df, .group_id < 2)`. See #415
