### ISSUE TITLE
top_n enhancement

### ISSUE THREAD

**Issue by derekholmes** [hadley/dplyr#1333]
I found a case where top_n was returning counter-intuitive, but correct results.  I wanted _all_ of the rows with the top_n "wt"s instead of just the n top rows (which may not be n rows anyway).  This is an issue when the number of ties is more than n.

Can we get a switch/parameter in top_n to separate out the cases?

Here is an example and my solution.

```
> testdf=data_frame(key2=rep(1:3,3),value=1:9)
> testdf %>% top_n(2,key2)
Source: local data frame [3 x 2]

  key2 value
1    3     3
2    3     6
3    3     9

> xtop_n <-function (x, n, wt) 
{
  if (missing(wt)) {
    vars <- tbl_vars(x)
    message("Selecting by ", vars[length(vars)])
    wt <- as.name(vars[length(vars)])
  }
  call <- substitute(filter(x, min_rank(desc(wt)) <= sort(unique(min_rank(desc(wt))))[n]), list(n = n, wt = substitute(wt)))
  eval(call)
}
> testdf %>% xtop_n(2,key2)
Source: local data frame [6 x 2]

  key2 value
1    2     2
2    3     3
3    2     5
4    3     6
5    2     8
6    3     9
> 
```

**Comment by hadley** [comment]
I think if you want to use a different sort of ranking, it's fine to write your own wrapper. I suspect you can make your code simpler by swapping out `min_rank()` for a `dense_rank()`.
