### ISSUE TITLE
Interleave multiple function summarise_each() output [Feature Request]

### ISSUE THREAD

**Issue by bhive01** [hadley/dplyr#1335]
Currently if you have multiple functions in a summarise_each() call, you get the following:
(funs(mean, sd))
Group_by Column, Mean1, Mean2, SD1, SD2

An example:
```R
library(dplyr)

df <- data.frame(name=rep(LETTERS[1:3], each=20), weight=runif(60,60, 100), height=runif(60, 100, 150))

df %>%
group_by(name) %>%
summarise_each(., funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE)))
```
In many cases these tables are the final product for showing to others and/or a springboard for further exploratory analysis, but I usually find myself wanting to reorder the columns like so: 

Group_by Column, Mean1, SD1, Mean2, SD2

Dennis had a solution of the following and I believe it could be made more general, but I'm unsure of the best approach: 

```R
df %>%
group_by(name) %>%
summarise_each(., funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE))) %>%
`[`(., c(1, 2, 4, 3, 5))
```

Seems like you could isolate the grouped by columns subtract them from ncol(), divide by the number of functions, and interleave based upon that. Doesn't seem that simple, but someone must have already figured this out. Dennis said that plyr::colwise() did this, but it's been ages since I've used plyr.

**Comment by hadley** [comment]
Related to #154

**Comment by bhive01** [comment]
I realize this is low priority, but I think I've cracked how to do it, but it requires guts of dplyr because you need to know how many group_by's and how many funs() it has. 

n=columns submitted to summarise_each()
m= funs() submitted to summarise_each()
p = number of groups in group_by()

rep(1:n, each = m) + (0:m-1) * n + p

`[`(., c(1:p, rep(1:n, each = m) + (0:m-1) * n + p))
```r
n=8
m=3
p=2
c(1:p, rep(1:n, each = m) + 0:(m-1) * n + p)
# [1]  1  2  3 11 19  4 12 20  5 13 21  6 14 22  7 15 23  8 16 24  9 17 25 10 18 26
```
from: https://stackoverflow.com/questions/24576548/merge-interleave-dataframes-in-r

**Comment by hadley** [comment]
Unfortunately I don't think is going to happen - it's going to be quite a lot of work for minimal gain.

**Comment by bhive01** [comment]
10-4, thanks for looking.
