### ISSUE TITLE
bind_rows and list names

### ISSUE THREAD

**Issue by bramtayl** [hadley/dplyr#1337]
It seems like, at the moment, bind_rows, when applied to a list, disregards name information. I've been doing things like this:

```{r}
test = list(source_1 = data_frame(a = 1), 
            source_2 = data_frame(a = 1) )

1:length(test) %>%
  lapply(function(i)
  test[[i]] %>%
    mutate(name = names(test)[i]) ) %>%
  bind_rows
```

It seems like a straightforward solution would be to have extra argument which specifies the name of a column to contain list name information.

**Comment by hadley** [comment]
See also #825

**Comment by bramtayl** [comment]
A similar strategy might be used also be used for row names. Although list names might be more important because they often contain important information for joins etc.

**Comment by bramtayl** [comment]
Note also this is a feature of rbindlist from data.table

**Comment by hadley** [comment]
Dplyr will always discard row names because I think they're a bad idea
