### ISSUE TITLE
backend report: dplyr.spark

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1340]
Just a note to point to  a [report](https://github.com/RevolutionAnalytics/dplyr-spark/blob/master/docs/new-backend-report.md) (section II). The report covers the negatives but the fact is, here is a new backend, it's possible to write it, almost everything works and it wasn't the hardest thing. The negative side is that I had to use a lot of cut and paste of existing methods for small to medium differences, lots of access to dplyr private functions and even one monkey patch for `over`. All of these are potential maintenance burdens. There may be some ignorance on my side at play, some quirkiness in the backend and some dplyr rigidity, not sure in what proportions. So if there is an interest in reviewing a backend to see how to make backend writing easier, either with new extensibility features or maybe just documentation, here it is. Otherwise, this is not really a bug report and can be closed anytime.

**Comment by hadley** [comment]
Thanks Antonio. I'm ramping up for dplyr development at the moment, and will read thoroughly soon.
