### ISSUE TITLE
advertize that tbl_df subsetting behavior is different from data.frame

### ISSUE THREAD

**Issue by ijlyttle** [hadley/dplyr#1345]
I'll make a PR when I get a moment, but I just ran into this issue: 

https://github.com/hadley/dplyr/issues/587

It might be useful to note this difference in the documentation for tbl_df

**Comment by hadley** [comment]
Yes, definitely needs to be documented and included in the vignette. It was a bit of an experiment, but I'm happy with the results so the behaviour is here to stay

**Comment by ijlyttle** [comment]
Adds documentation in #1350
