### ISSUE TITLE
Return of STRSXP when binding to blank data_frames

### ISSUE THREAD

**Issue by abresler** [hadley/dplyr#1346]
This usually comes up in practice when binding to a master data frame for say scraping a list of urls that produce individual data frames.

```
library(magrittr)
library(dplyr)
all_properties <- 
  data_frame()
all_properties %<>%
  bind_rows(data_frame(property = "325 Fifth Avenue", value = 25000000))
```

Spits out 

```
Error: not compatible with STRSXP
```
I think it has to do with the bind_rows function works with regular data.frames

```
all_properties <- 
  data.frame()
all_properties %<>%
  bind_rows(data.frame(property = "325 Fifth Avenue", value = 25000000))
```

**Comment by hadley** [comment]
Even more minimal reprex:

```R
data_frame() %>% bind_rows(data_frame(x = "a"))
data.frame() %>% bind_rows(data_frame(x = "a"))
```

@romainfrancois can you please take a look?

**Comment by romainfrancois** [comment]
Hmm. Works for me on the `dev_during_release_phase` branch. 

```
> data.frame() %>% bind_rows(data_frame(x = "a"))
Source: local data frame [1 x 1]

  x
1 a
```

**Comment by romainfrancois** [comment]
I'm working on some other stuff in the branch, so I'll probably fix this in master now rather than merge the branch.

**Comment by hadley** [comment]
That'd be great. Otherwise everything is looking good for release. I'll submit on monday
