### ISSUE TITLE
top_n(10, -n) vs. btm_n(10, n)

### ISSUE THREAD

**Issue by npjc** [hadley/dplyr#1352]
I use `count(group) %>% top_n(10, -n)` type-of-thing lots... Future me would prefer if I could use `count(group) %>% btm_n(10, n)` instead as it is more easily understood at a glance.

From  `?top_n()`:
```r
# Find 10 players with most games
require("Lahman")
tbl_df(Batting) %>%
  group_by(playerID) %>%
  tally(G) %>%
  top_n(10)
```
I wish for:
```r

# to find the 10 players with least games
# currently
... %>% top_n(10, -n)
# wishful behaviour
... %>% btm_n(10, n)
```

Or perhaps it is easier to just document examples of how you'd get the bottom n of something under `top_n()`

**Comment by ybryan** [comment]
Agreed. I was just searching for how to do this and believe the alternative suggested (btm_n) would be preferred

**Comment by hadley** [comment]
But `top_n()` with a negative value doesn't work?

**Comment by hadley** [comment]
Ooooh, you're negating the variable `n`, not the argument `n`.

**Comment by hadley** [comment]
I think using `-n` to indicate that you want the bottom n values is a reasonable compromise between concision and expression.

**Comment by npjc** [comment]
I'm surprised. A quick survey of students learning R  2/15 were able to "read off"  what was going to happen. But thanks for considering.
