### ISSUE TITLE
filtering by multiple columns at once

### ISSUE THREAD

**Issue by tanerumit** [hadley/dplyr#1359]
I am trying to do some programming with filter(). What I am interested is to pass a set of column names and values without explicitly stating. In my case, the columns to be filtered is more than one and changes every time I run the code. 

For example, this does the job if I know the columns and their values in advance:

```
filter(mtcars, carb == 2, cyl == 4)
```

What about something like this: 

```
filter_names <- list(carb, cyl)         
filter_values <- list(2,4)
```

Then pass filter_names and filter_values to the filter():

```
filter(mtcars, filter_names == filter_values) 
```

which obviously won't work... Any ideas?

**Comment by romainfrancois** [comment]
See the [NSE vignette](https://github.com/hadley/dplyr/blob/master/vignettes/nse.Rmd) 
You need `filter_`


For example, you can do something like this: 

```
> filter_names <- c("carb", "cyl")
> filter_values <- c(2,4)
> .dots <- lapply( 1:2, function(i) interp( ~ variable == value, variable = as.name(filter_names[i]), value = filter_values[i] ) )
> .dots
[[1]]
~carb == 2
<environment: 0x7ff5d6dc6400>

[[2]]
~cyl == 4
<environment: 0x7ff5d6dbe098>
> filter_( mtcars, .dots = .dots )
```
