### ISSUE TITLE
distinct is not working with SQL

### ISSUE THREAD

**Issue by ignacio82** [hadley/dplyr#1360]
I'm not sure if this is a bug or if I'm doing something wrong.

    # get sample databases from: http://chinookdatabase.codeplex.com/
    library(dplyr)
    mydb <- src_sqlite("Chinook_Sqlite.sqlite")
    Album <- tbl(mydb, "Album") 
    ArtistIds <- Album  %>% select(ArtistId)  %>% distinct(ArtistId)  %>% collect()

    Error: Can't calculate distinct only on specified columns with SQL

I initially posted the question on [stackoverflow](http://stackoverflow.com/questions/32272865/cant-calculate-distinct-only-on-specified-columns-with-sql?noredirect=1#comment52425847_32272865), but I'm starting to think this could be a bug.

Thanks for the help!

**Comment by einarhjorleifsson** [comment]
not a bug:  omit `distinct(ArtistId) ` - the following seems to do the job:
```
tbl(mydb, "Album") %>%
select(ArtistId) %>%
distinct()
```
einar

**Comment by joelgombin** [comment]
Sorry but I don't understand how this is not a bug. You may want to select distinct lines with regard to one variable while retaining other columns. This works for `tbl_df` but does not with `tbl_sql`. If it is not possible to replicate this behaviour in SQL, at least it should be documented, shouldn't it?
