### ISSUE TITLE
Numerous warnings upon installation

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1362]
I successfully installed current version from GitHub (and successfully checked `googlesheets`). But I get a whole lot of compilation warnings upon installation. Here's output from `devtools::install_github("hadley/dplyr")`, `devtools::session_info()`, and `gcc -v`: https://gist.github.com/jennybc/60913146e88ea9e47635#file-dplyr-install-warnings-txt

**Comment by romainfrancois** [comment]
Can't reproduce this just yet. Trying to download Xcode 7 beta, as it looks you have a newer llvm than me.

**Comment by romainfrancois** [comment]
Just installed El Capitan and Xcode 7, getting those now. I'll see what I can do.

**Comment by jennybc** [comment]
Yes that worked. Zero warnings now.

**Comment by romainfrancois** [comment]
Great. That's a close then.
