### ISSUE TITLE
feature request:  A way to count missing/non-missing rows with n() or similar

### ISSUE THREAD

**Issue by rpruim** [hadley/dplyr#1367]
There is the tricky bit of deciding what missing means, but perhaps columns could be supplied and only rows which are complete in all of those columns would count as non-missing.  Possible syntax:

``` r
data %>% 
  summarise(
    n = n(),
    incomplete = n - n(col1 : col3, my_other_column)
  )
```

Since `n()` currently has not arguments, `...` could be used to specify the columns in the same way that we currently specify columns for `select()`.

Alternatively, this could be put into additional helper functions `complete()` and/or `incomplete()`.  

``` r
data %>% 
  summarise(
    n = n(),
    incomplete = incomplete(col1 : col3, my_other_column),
    complete = complete(col1 : col3, my_other_column)
  )
```

With no additional arguments, these would act much like 

``` r
nrow(data %>% filter(complete.cases(.)))
```

**Comment by matthieugomez** [comment]
+1

**Comment by hadley** [comment]
I'd prefer not to introduce "variable" ranges inside verbs - `n()` is already a little icky.

**Comment by matthieugomez** [comment]
I agree for column range btw. We juste need a faster
```R
count <- function(...){
    sum(complete.cases(...))
  }
```

**Comment by hadley** [comment]
I think there are two factors at play here:

1.  `n()` needs a convenient way to count non-missing values.

2.  All aggregation functions need a way to work across multiple columns.

I think there are two possible approaches:

1.  Define a series of aggregation functions that take `...` and work like select: `row_n(a:f)`, `row_mean(a:f)`, `row_sd(a:f)`. This would require coming up with a naming convention that doesn't clash with existing functions, and implementing row-wise aggregates ourselves.

1. Define a single function that gives you select style column selection and returns a data frame (or matrix?) that can be fed to other functions: `n(cols(a:f))`, `rowMeans(cols(a:f))`, ... 

Related to #968

**Comment by matthieugomez** [comment]
I like approach 2 because it keeps a clear separation between the function definition and its use within a `dplyr` chain. base R functions like `complete.cases` would work out of the box. Any user-defined function would work as long as it has a syntax similar to complete.cases :  ... a sequence of vectors, matrices and data frames.

Now, I'm not sure why we need to have a new verb `cols`. Why does not `select` work in this example?
``` 
df <- data_frame(
n1 = 1:5,
n2 = c(NA, 1:4),
n3 = c(1:4, NA),
n4 = 1:5
)
df %>% mutate(condition = complete.cases(select(., n1:n3)))
```

**Comment by lionel-** [comment]
That `cols()` function (or making the NSE version of `select()` work inside dplyr verbs) would be handy in combination with the `pmap()` family.

About `complete.cases()`, I've been using a custom verb `filter_na(.data, ...)` that has select semantics and filters all rows containing missing values in the mentioned columns. That is useful when modelling. Could be a good fit in dplyr / tidyr?
```r
# With parallelised is.na from #968
any_na <- partial(some, .p = is.na) %>% lift_ld()
p_any_na <- parallelise(any_na, .empty = FALSE)

filter_na <- function(.data, ...) {
  vars <- dplyr::select_vars(names(.data), ...)
  .data[!p_any_na(.data[vars]), ]
}

df <- tibble(
  ~x, ~y, ~z,
  NA, 1,  NA,
  2,  NA, NA,
  3,  3,  NA
)

df %>% filter_na(x, y)
#> Source: local data frame [1 x 3]
#>
#>       x     y     z
#>   (dbl) (dbl) (lgl)
#> 1     3     3    NA
```

**Comment by cdschaller** [comment]
Would be great if we could just do n(field, na.rm = TRUE).

**Comment by hadley** [comment]
Now at https://github.com/hadley/vctrs/issues/2 and https://github.com/hadley/vctrs/issues/9
