### ISSUE TITLE
Why would dplyr fail to compile using std=gnu++11?

### ISSUE THREAD

**Issue by aadler** [hadley/dplyr#1368]
When trying to compile dplyr from source (using an experimental GCC 4.9.2/3 based toolchain), if I pass `=std=gnu++11`, then dplyr fails with the error posted below. However, when not passing any standardization flag, it compiles without any problems. Any insight would be appreciated.

Thank you,

Avi

```
C:/MINGW64/gcc-4.9.2/bin/g++ -m64 -I"C:/R/RCurrent/R-32~1.2PA/include"
-DNDEBUG -I../inst/include -DCOMPILING_DPLYR
-I"C:/R/RCurrent/R-3.2.2patched/library/Rcpp/include"
-I"C:/R/RCurrent/R-3.2.2patched/library/BH/include"
-I"C:/R/RLocalSoft/extsoft/include"     -std=gnu++11 -O2
-march=ivybridge -mtune=ivybridge --param l1-cache-line-size=64
--param l1-cache-size=32 --param l2-cache-size=256 -pipe -c
RcppExports.cpp -o RcppExports.o
In file included from ../inst/include/dplyr/Result/all.h:25:0,
                 from ../inst/include/dplyr.h:141,
                 from RcppExports.cpp:4:
../inst/include/dplyr/Result/Name.h:51:16: error: specialization of
'template<class _Tp> struct std::hash' in different namespace
[-fpermissive]
         struct hash< dplyr::Name > {
                ^
In file included from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/bits/basic_string.h:3068:0,
                 from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/string:52,
                 from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/stdexcept:39,
                 from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/array:38,
                 from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/tuple:39,
                 from
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/unordered_map:41,
                 from
C:/R/RCurrent/R-3.2.2patched/library/Rcpp/include/Rcpp/platform/compiler.h:153,
                 from
C:/R/RCurrent/R-3.2.2patched/library/Rcpp/include/Rcpp/r/headers.h:48,
                 from
C:/R/RCurrent/R-3.2.2patched/library/Rcpp/include/RcppCommon.h:29,
                 from
C:/R/RCurrent/R-3.2.2patched/library/Rcpp/include/Rcpp.h:27,
                 from ../inst/include/dplyr.h:4,
                 from RcppExports.cpp:4:
C:/MINGW64/gcc-4.9.2/i686-w64-mingw32/include/c++/bits/functional_hash.h:58:12:
error:   from definition of 'template<class _Tp> struct std::hash'
[-fpermissive]
     struct hash;
            ^
In file included from ../inst/include/dplyr/Result/all.h:25:0,
                 from ../inst/include/dplyr.h:141,
                 from RcppExports.cpp:4:
../inst/include/dplyr/Result/Name.h:52:61: error: definition of
'std::size_t std::hash<dplyr::Name>::operator()(const dplyr::Name&)
const' is not in namespace enclosing 'std::hash<dplyr::Name>'
[-fpermissive]
             std::size_t operator()( const dplyr::Name & c ) const {
                                                             ^
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f
"C:/R/RCurrent/R-32~1.2PA/etc/x64/Makeconf" -f
"C:/R/RCurrent/R-32~1.2PA/share/make/winshlib.mk" -f
"//[REDACTED]/.R/Makevars"
SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)'
SHLIB="dplyr.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o address.o
arrange.o between.o bind.o combine_variables.o distinct.o dplyr.o
filter.o group_indices.o init.o join.o select.o strings_addresses.o
summarise.o test.o window.o"' had status 2
ERROR: compilation failed for package 'dplyr'
* removing 'C:/R/RCurrent/R-3.2.2patched/library/dplyr'
Warning in install.packages :
  running command '"C:/R/RCurrent/R-32~1.2PA/bin/x64/R" CMD INSTALL
--byte-compile -l "C:\R\RCurrent\R-3.2.2patched\library"
C:\R\temp\Rtmp0s39u5/downloaded_packages/dplyr_0.4.2.tar.gz' had
status 1
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
```

**Comment by kevinushey** [comment]
Are you able to reproduce this in the development version of `dplyr`? (I don't see a `Result/Name.h` anymore on master...)

**Comment by aadler** [comment]
I'll check as soon as I'm done recompilng a nearly vanilla R (must be the sixth time today already 8-); I had built a funky one for testing https://github.com/jeroenooms/Rbuild/issues/1 ).

**Comment by aadler** [comment]
Great. Now I'm getting a new error that I didn't get last week. Has anything changed in the past few hours?

```
* installing *source* package 'Rcpp' ...
** package 'Rcpp' successfully unpacked and MD5 sums checked
** libs
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include/    -I"C:/R/RLocalSoft/extsoft/include"     -std=gnu++11 -O2 -mtune=ivybridge -pipe -c Date.cpp -o Date.o
Date.cpp:1:0: error: bad value (ivybridge) for -mtune= switch
 // -*- mode: C++; c-indent-level: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-
 ^
make: *** [Date.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/R/R-PATC~2/etc/x64/Makeconf" -f "C:/R/R-PATC~2/share/make/winshlib.mk" -f "\\na.ad.guycarp.com\US_Users\MOR\AADLER00/.R/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="Rcpp.dll" WIN=64 TCLBIN=64 OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o"' had status 2
ERROR: compilation failed for package 'Rcpp'
* removing 'C:/R/R-patched/library/Rcpp'

The downloaded source packages are in
        ‘C:\R\temp\RtmpkbpD7D\downloaded_packages’
Warning messages:
1: running command '"C:/R/R-patched/bin/x64/R" CMD INSTALL --byte-compile -l "C:\R\R-patched\library" C:\R\temp\RtmpkbpD7D/downloaded_packages/Rcpp_0.12.0.tar.gz' had status 1 
2: In install.packages("Rcpp", type = "source", INSTALL_opts = "--byte-compile") :
  installation of package ‘Rcpp’ had non-zero exit status
```

**Comment by aadler** [comment]
Sorry about the off-topic discussions, but now I am very confused. Rebuilding R using the 4.9.2 toolchain, I can build Rcpp without difficulty, and I have built many packages from source that depend on Rcpp without difficulty (ggplot2, reshape2, plyr, and Delaporte as examples).

When I try to compile ddplyr from source, I get the error from the first comment (const not in namespace)

When I install devtools and try `install_github('hadley/dplyr')` I get an error similar to the comment above, specifically:
```
Installing dplyr
"C:/R/R-patched/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL "C:/R/temp/RtmpkXfPod/devtools2634475d6b90/hadley-dplyr-1405946"  \
  --library="C:/R/R-patched/library" --install-tests 

* installing *source* package 'dplyr' ...
** libs
g++ -m64 -I"C:/R/R-PATC~2/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR   -I"C:/R/R-patched/library/Rcpp/include" -I"C:/R/R-patched/library/BH/include" -I"C:/R/RLocalSoft/extsoft/include"     -std=gnu++11 -O2 -mtune=ivybridge -pipe -c RcppExports.cpp -o RcppExports.o
cc1plus.exe: error: unrecognized command line option '-std=gnu++11'
RcppExports.cpp:1:0: error: bad value (ivybridge) for -mtune= switch
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/R/R-PATC~2/etc/x64/Makeconf" -f "C:/R/R-PATC~2/share/make/winshlib.mk" -f "\\na.ad.guycarp.com\US_Users\MOR\AADLER00/.R/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dplyr.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o dplyr.o filter.o group_indices.o init.o join.o select.o strings_addresses.o summarise.o test.o window.o"' had status 2
ERROR: compilation failed for package 'dplyr'
* removing 'C:/R/R-patched/library/dplyr'
Error: Command failed (1)
```

I have no idea why; sorry.

**Comment by aadler** [comment]
PS. Same error for:
```
> install_github('hadley/dplyr@dev_during_release_phase')
Downloading github repo hadley/dplyr@dev_during_release_phase
```

**Comment by kevinushey** [comment]
Oh, could it be a PATH issue? Maybe older / wrong versions of `gcc` and friends are getting picked up.

Make sure the associated version of Rtools you want to use is first on the PATH.

**Comment by aadler** [comment]
That's almost surely not the issue, otherwise the CRAN-based installs would fail too. I'm almost certain it is a devtools setting, and that it is intentional. I've asked here for some advice: https://github.com/hadley/devtools/issues/908

**Comment by aadler** [comment]
@kevinushey @romainfrancois, cloning the repo, building a source package based on the dev branch (dplyr_0.4.2.9002.tar.gz), and installing locally from source passing `std=gnu++11` and `mtune=ivybridge` no longer has the `const` issue, but another.

```
g++ -m64 -shared -s -static-libgcc -o dplyr.dll tmp.def RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o dplyr.o filter.o group_indices.o init.o join.o select.o strings_addresses.o summarise.o test.o window.o -LC:/R/RLocalSoft/extsoft/lib/x64 -LC:/R/RLocalSoft/extsoft/lib -LC:/R/R-PATC~2/bin/x64 -lR
collect2.exe: error: ld returned 5 exit status
installing to C:/R/R-patched/library/dplyr/libs/x64
```

At first blush, I would have thought this was related to <https://stat.ethz.ch/pipermail/r-devel/2015-March/070814.html> and <http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2015-August/008920.html>. However, I am passing O2 in CXXFLAGS. Do I need to pass O2 in CPPFLAGS as well to capture the case when g++  is used to combine the .o files? Windows error box below

![Uploading Error.png…]()

**Comment by aadler** [comment]
For completeness (if it helps) -O2 in LFLAGS or CPPFLAGS does not help, but removing gnu++11 from CXXFLAGS allows dplyr_0.4.2.9002 to compile normally (as per the CRANversion).

**Comment by kevinushey** [comment]
IIRC `exit status 5` from `ld` implies it couldn't find some symbols it was expecting when linking. Why not use `std=c++11` instead of `gnu++11` anyway; do you really need the GNU extensions?

**Comment by aadler** [comment]
Because Rcpp crashed with c++11 in one of the previous dozen trials. Maybe
that too was a tool chain issue (may have been KK's seh version). I'll try
again tomorrow if time allows.

Thanks!

Avi

On Monday, August 31, 2015, Kevin Ushey <notifications@github.com> wrote:

> IIRC exit status 5 from ld implies it couldn't find some symbols it was
> expecting when linking. Why not use std=c++11 instead of gnu++11 anyway;
> do you really need the GNU extensions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/dplyr/issues/1368#issuecomment-136536821>.
>


-- 
Sent from Gmail Mobile

**Comment by romainfrancois** [comment]
Looks like this evolved to an Rcpp issue. Please have the discussion in the Rcpp repo.

**Comment by aadler** [comment]
@romainfrancois, I would respectfully differ as I would have expected dplyr to compile using std=gnu++11 also (everything else in the R ecosystem I have tried does, and that is scores of packages.

Are you making the explicit statement that we are not to expect dplyr to be able to be compiled using gnu++11, at least under Windows?

**Comment by romainfrancois** [comment]
The evidence you put there is about Rcpp. Until Rcpp compiles fine under these settings, nothing really can be said about any package that depends on it. 

I'm just saying that the Rcpp repo is a better place to have all those failures of compiling Rcpp. You'll have people there who actively maintain and develop Rcpp. It's only coincidental that you had @kevinushey replying here.

**Comment by romainfrancois** [comment]
When RcppCore/Rcpp#360 is fixed, feel free to reopen if you still can't build `dplyr`
