### ISSUE TITLE
Issue with filter and hybrid evaluation of max (I think)

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1369]
```R
df <- data_frame(x = 1:1000)
y <- 1:10
nrow(filter(df, x <= max(y)))
nrow(filter(df, x <= max(10)))
nrow(filter(df, x <= 10))
```

@romainfrancois can you please take a look ASAP?

**Comment by hadley** [comment]
Looks like there's a protection or initialisation problem because `nrow(filter(df, x <= max(10)))` returns different results (sometimes 0, 69, 100, 1000)

**Comment by hadley** [comment]
Just to be clear - the first result is also wrong (should be 10). And the random second result seems to be connected to the coercion: `nrow(filter(df, x <= max(10L)))` is consistently wrong.

**Comment by hadley** [comment]
Here's an better reprex:

```R
df <- data_frame(x = 1:1000)
summarise(df, max(y))
summarise(df, max(10))
```

**Comment by romainfrancois** [comment]
Committed a quick fix that only treats the expression hybridly when `max` is applied to a variable from the data. Anything else is handed back to R evaluation. 

I'm sure I can do better than this down the line, but at least that works for now.
