### ISSUE TITLE
Bigquery support?

### ISSUE THREAD

**Issue by dlsun** [hadley/dplyr#1371]
It seems like bigquery in dplyr is deprecated, but some of the documentation (e.g., the README, databases vignette) still refers to bigquery. Could you please check these and, if bigquery is in fact deprecated, what we should use instead? (It seems like the answer is bigrquery, but it's not quite clear to me how the two packages relate and why they are separate.) Thanks!

**Comment by hadley** [comment]
It's still supported but the code is now in the bigrquery package.
