### ISSUE TITLE
[Bug?] Different number of observations when I do collect before or after filter

### ISSUE THREAD

**Issue by ignacio82** [hadley/dplyr#1372]
Sadly, I cannot share my db so this may be a little hard to debug. This command:

    df1<- tbl(mydb, "table1") %>% filter(id %in% DM$id) %>% collect()

gives me 2358 observations. While this one:

    df2<- tbl(mydb, "table1")  %>% collect() %>% filter(id %in% DM$id) 

gives me 18755 observations. Is this a bug or am I missing something important?

Thanks!

**Comment by hadley** [comment]
Can't tell without a reproducible example, sorry.
