### ISSUE TITLE
Notice: new release of Lahman package

### ISSUE THREAD

**Issue by friendly** [hadley/dplyr#1373]
v4.0-0 of the Lahman package is under development at https://github.com/cdalzell/Lahman.
See: https://github.com/cdalzell/Lahman/issues/11

dplyr suggests Lahman and uses it in an example or two so it would be useful to check that 
nothing gets broken in dplyr.  The new version can be installed via

    devtools::install_github("cdalzell/Lahman", ref="feature/v4.0-0")

**Comment by hadley** [comment]
Thanks!
