### ISSUE TITLE
db_create_table fails with HIVE rjdbc

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1378]
db_create_table uses DBI::dbGetQuery, which uses DBI::dbSendQuery, which calls RJDBC::dbSendQuery which calls a java statement method executeQuery, which is not appropriate for DDL queries. I entered s-u/RJDBC#25 and @s-u's answer is that DDL statements should be submitted with sendUpdate, which is not yet available in DBI rstats-db/DBI#20. I run into this developing a dplyr backend. Thanks

**Comment by hadley** [comment]
I think you should temporarily fix this with your own `db_create_table` method, and it will eventually get fixed by improved `dbWriteTable()` methods in DBI backends.
