### ISSUE TITLE
Rowwise mutate gives unexpected result.

### ISSUE THREAD

**Issue by dkesh** [hadley/dplyr#1381]
Package Version dplyr: 0.4.3
R version 3.2.2

Running this code:

    library( dplyr )
    f  <- function( x ) ifelse( x < 2, NA_real_, x )
    data_frame( x = 1:3 ) %>% rowwise() %>% mutate( y = f(x) )

Expected result: data_frame( x = 1:3, y = c( NA, 2, 3))
Actual result: data_frame( x = 1:3, y = c( NA, 2, NA ) )

**Comment by dkesh** [comment]
Is this a duplicate of #958?

**Comment by romainfrancois** [comment]
Hmm. that's odd: 

```
> f  <- function( x ) { print(x); ifelse( x < 2, NA_real_, x ) }
> data_frame( x = 1:3 ) %>% rowwise() %>% mutate( y = f(x) )
[1] 1
[1] 1
[1] 2
Source: local data frame [3 x 2]
Groups: <by row>

      x     y
  (int) (int)
1     1    NA
2     2     2
3     3    NA
```
