### ISSUE TITLE
Problem loading the latest version of dplyr

### ISSUE THREAD

**Issue by blaquans** [hadley/dplyr#1384]
I've installed the latest dplyr version from github using `install_github('hadley/dplyr')`. There was no error but when I try to load `dplyr`, I've got the following error : 

    > library("dplyr")
    Error in get(method, envir = home) : 
      lazy-load database '/home/pac/R/x86_64-pc-linux-gnu-library/3.2/dplyr/R/dplyr.rdb' is corrupt

I run R 3.2.0 on Ubuntu 14.04 LTS. Do you have any solution to my problem ?

I've updated to version R 3.2.2 and it works !!

Maybe you should just add a message to the user to tell him to update R.

**Comment by hadley** [comment]
Restart R. Reinstall dplyr. Let me know if that doesn't work.

**Comment by blaquans** [comment]
It's too late for me. I've updated R to the 3.2.2 version and it works.
