### ISSUE TITLE
corrupt 'group_df'` error with dplyr 0.4.3

### ISSUE THREAD

**Issue by eipi10** [hadley/dplyr#1385]
I just installed the latest version of `dplyr` and began getting `corrupt 'group_df'` errors with code that used to work. Here's an example error message:

`Error: corrupt 'grouped_df', contains 657842 rows, and 657865 rows in groups`

My current workaround is to add `%>% ungroup()` on the end of the code that returns the corrupt data frame, but I'd like to figure out what's causing the error so I can implement a real fix. 

I'm working with data that I can't share and I haven't been able to recreate the error with fake data. I will update this post if I can manage to create a reproducible example.

**Comment by hadley** [comment]
Please provide a reproducible example

**Comment by eipi10** [comment]
I was able to reproduce the error with fake data, so here is a reproducible example:

    library(dplyr)

    set.seed(111)
    dat1 = data.frame(group=sample(LETTERS[1:3], 1000, replace=TRUE),
                                 y=rnorm(1000))
    dat1 = dat1 %>% group_by(group)

    dat2 = data.frame(group=sample(LETTERS[1:2], 100, replace=TRUE),
                                 y=rnorm(100))
    dat2 = dat2 %>% group_by(group)

    dat3 = rbind(dat1, dat2)

    dat3 %>% 
      summarise(n=n())

    Error: corrupt 'grouped_df', contains 1100 rows, and 1000 rows in groups

In my actual use case I don't just do, say, `dat2 = dat2 %>% group_by(group)`. After the grouping, I do filtering, mutating, etc., but I wasn't ungrouping after completing those operations. As a result, I ended up rbind-ing two data frames that had been separately run through `group_by`. 

This kind of thing never caused a problem with earlier versions of `dplyr` but is causing an error with the new version. For my own edification, is there something wrong (in the sense of good programming style) with separately grouping an rbind-ing, or is this just a bug in `dplyr`?

**Comment by hadley** [comment]
Use `bind_rows()` instead of `rbind()`.  Need to see if we can un-break `rbind()` for this use.

**Comment by eipi10** [comment]
Will do. Thanks Hadley.

**Comment by romainfrancois** [comment]
yep `rbind` grabs the attributes from `dat1`. Perhaps just : 

```
> rbind.tbl_df <- function( ..., deparse.level = 1 ) bind_rows(...)
```

**Comment by josiekre** [comment]
I'm getting the same error message without using `rbind()`. Following the above example,

```{r}
> data_frame(group=sample(LETTERS[1:2], 100, replace=TRUE), y=rnorm(100)) %>% 
    group_by(group) %>% 
    slice(1) %>% 
    select(y)
Error: corrupt 'grouped_df', contains 2 rows, and 100 rows in groups
```

If the `select()` is moved *before* the `slice()`, it works without error. Does this make sense?

**Comment by eipi10** [comment]
FWIW, I've been getting `corrupt 'grouped_df'` errors in a range of situations as well, rather than just with `rbind`. When this problem pops up, my fix for now is to just add an `ungroup` after the end of whatever chain of operations requires grouping.  If it would help, I can post examples when this happens in the future.

**Comment by Fablepongiste** [comment]
Any update on this issue ? I am doing exactly same code as @josiekre, have now hacked it byinverting slice() and select() but looks weird. 

Thanks in advance @hadley

**Comment by hadley** [comment]
@josiekre @eipi10 @Fablepongiste please file separate issues. It's easier for me to track if one github issue = one problem with dplyr

**Comment by hadley** [comment]
@krlmlr can you take this for tibble please?

**Comment by krlmlr** [comment]
For this particular issue, wouldn't it be enough to define `rbind.grouped_df()` here?

**Comment by hadley** [comment]
@krlmlr oh good point
