### ISSUE TITLE
bind_rows fails with Error: not compatible with STRSXP

### ISSUE THREAD

**Issue by safferli** [hadley/dplyr#1389]
I'm sorry if I'm just too much of an idiot, and am blind to boot. This might be related to #1346 but this is on non-empty data frames. What's plexing me is that `do.call` works, but `bind_rows` doesn't: 

```{r}
df <- lapply(1, function(x) data.frame(id=x, data=runif(5)))
df2 <- lapply(2:3, function(x) data.frame(id=x, data=runif(5)))

#doesn't work
bind_rows(df, df2)

#works
do.call(rbind, c(df, df2))
```
Am I doing something wrong here?

**Comment by npjc** [comment]
@safferli if you modify your `bind_rows()` call to the same as `do.call()` it works for me!

```r
bind_rows(c(df, df2))
#> Source: local data frame [15 x 2]
#> 
#> id       data
#> (dbl)      (dbl)
#> 1      1 0.54358302
#> 2      1 0.77075381
#> 3      1 0.21797273
#> 4      1 0.24802491
#> 5      1 0.39316823
#> 6      2 0.50702872
#> 7      2 0.60293241
#> 8      2 0.90589808
#> 9      2 0.50936390
#> 10     2 0.47979525
#> 11     3 0.07552338
#> 12     3 0.07655688
#> 13     3 0.71382495
#> 14     3 0.70129482
#> 15     3 0.97582166
```

**Comment by safferli** [comment]
Indeed it does! 

Is this always the case? If so, perhaps the documentation should be updated? It allows the simple supplying of dfs as arguments: 

```{r}
# You can either supply data frames as arguments
bind_rows(one, two)
```

**Comment by hadley** [comment]
You're not supplying two data frames - you're supplying two lists of data frames.  We do need a better error message though.

**Comment by ahcyip** [comment]
Has this error message been fixed? I just tried to bind lists of data frames and I got the STRSXP message.
I got the result I wanted by using sapply instead of lapply but it seems the error message is still confusing.

reprex:
```
listoflists<-list(list(data.frame(c(1,2,3),c("not","this","one")),data.frame(c(6,5,4),c("bind","this","one"))),
                  list(data.frame(c(1,2,3),c("not","this","one")),data.frame(c(3,2,1),c("bind","this","one"))),
                  list(data.frame(c(1,2,3),c("not","this","one")),data.frame(c(3,2,1),c("not","this","oneeither"))))
bind_rows(lapply(listoflists[c(1,2)],"[",2))
```
Error in bind_rows_(x, .id) : not compatible with STRSXP

**Comment by lionel-** [comment]
The proper reprex is:

```r
x <- list(
  list(data.frame(c(1, 2, 3), c("not", "this", "one"))),
  list(data.frame(c(1, 2, 3), c("not", "this", "one")))
)
bind_rows(x)
```

It now says: `Argument 1 can't be a list containing data frames`

**Comment by lionel-** [comment]
Which is not an entirely accurate message. It can't be a list containing a list of data frames.

**Comment by ahcyip** [comment]
Hi @lionel- 
> It now says: Argument 1 can't be a list containing data frames
I actually still get Error in bind_rows_(x, .id) : not compatible with STRSXP with your reprex.
I am using dplyr 0.5.0

**Comment by lionel-** [comment]
The relevant version for bug reports is the current master branch which will become dplyr 0.6. You can install it with `devtools::install_github("tidyverse/dplyr").

**Comment by ahcyip** [comment]
@lionel- Thanks for explaining!
