### ISSUE TITLE
Subset within summarise_each only works for columns prior to filtered column

### ISSUE THREAD

**Issue by ship561** [hadley/dplyr#1390]
When I was trying to get the mean of certain categories of data within my data frame, I found that I cannot get the mean of any column after the subset criteria. Here, instead of getting the mean, we are looking at the length of data returned.

data(mtcars)

When trying to subset the data on vs:
mtcars %>% summarise_each(funs(length(.[vs==1])))
  mpg cyl disp hp drat wt qsec vs am gear carb
1  14  14   14 14   14 14   14 14  0    0    0

When trying to subset the data on cyl shows that we can not calculate any values for any column after cyl:
mtcars %>% summarise_each(funs(length(.[cyl==6])))
  mpg cyl disp hp drat wt qsec vs am gear carb
 1   7   7    0  0    0  0    0  0  0    0    0

However, when we cycle cyl to the end of the data frame, we can get the values for all other columns which match the cyl==6 criteria:
 mtcars %>% select(mpg, disp, hp,drat, wt, qsec, vs, am, gear, carb, cyl) %>% summarise_each(funs(length(.[cyl==6])))
  mpg disp hp drat wt qsec vs am gear carb cyl
1   7    7  7    7  7    7  7  7    7    7   7

**Comment by hadley** [comment]
Yes, because you're modifying those columns.

**Comment by ship561** [comment]
Thanks for getting back to me so soon. Sorry, but I seem to be
misunderstanding the use of summarise_each in the case. I want to summarize
columns based on a criteria from another column in the data frame but it
seems I can only modify columns prior to the criteria. Is the intended
usage to always move the criteria column to the end?

**Comment by hadley** [comment]
`summarise_each()` is just a shortcut for `summarise`. You're effectively doing:

```R
mtcars %>% summarise(vs = 2, cyl = sum(cyl[vs == 1]))
```
