### ISSUE TITLE
Grouped do() with empty data frame

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1393]
```
data_frame(a=character()) %>% group_by(a) %>% do(stop("Hey!"))
```

throws an error. I wouldn't expect `do()` to be called at all in this case (there are no groups!), but even if this is desired behavior, I think it should be documented.

Slightly related: #341.

**Comment by hadley** [comment]
I think it has to get called so that these two have consistent types:

```R
data_frame(a=character(1)) %>% group_by(a) %>% do(x = list())
data_frame(a=character()) %>% group_by(a) %>% do(x = list())
```

**Comment by krlmlr** [comment]
Good point. I can update the documentation then.
