### ISSUE TITLE
summarise_each is slow if basic functions are copied to new function name

### ISSUE THREAD

**Issue by stanstrup** [hadley/dplyr#1395]
Make some data:
```R
   nvars <- 1000
   nsamples <- 50
   sample_groups <- 5
   data <- replicate(nvars, runif(n=nsamples))
   f <- rep_len(1:sample_groups, nsamples)
   f <- LETTERS[f]
```

Using summarise_each with ```mean```:
```R
library(dplyr)
system.time(    temp1 <- data.frame(class=f,data) %>% group_by(class) %>% summarise_each(funs(mean))     )
   user  system elapsed 
   0.23    0.00    0.24 
```

Using summarise_each with ```mean``` copied to another function name:
```R
library(dplyr)
aggr_FUN=mean
system.time(    temp2 <- data.frame(class=f,data) %>% group_by(class) %>% summarise_each(funs(aggr_FUN))    )
   user  system elapsed 
  28.85    0.00   28.86 
 ```

Is there a way to speed this up?

Using recast is also even faster:
```R
library(reshape2)
system.time(    temp3 <- recast(data.frame(class=f,data),class ~ variable,id.var="class",aggr_FUN)     )
   user  system elapsed 
   0.05    0.00    0.05 
```

Is there a better/faster way to do this with dplyr?

**Comment by hadley** [comment]
Unfortunately this is a fundamental limitation of the way dplyr does internal optimisations. Most people don't rename `mean()`.

**Comment by lionel-** [comment]
You can use purrr with `by_slice()` to apply a function within groups, and `lapply()` or `map()` to apply it in all columns.

It's even faster than dplyr with the original mean function, which is surprising. Maybe a bug with `summarise_each()`? cc @romainfrancois 
```r
library(purrr)
system.time(
  temp4 <- data.frame(class = f, data) %>%
    slice_rows("class") %>%
    by_slice(map, aggr_FUN)
)
```

**Comment by stanstrup** [comment]
Thanks for this suggestion. Seems purrr is ~5 times faster than dplyr in this case.
It is also ~1.5 times faster than reshape2. Purrr is unaffected by the "renaming".
