### ISSUE TITLE
Better $ hybrid support

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1400]
It would be nice if this worked:

``` R
library(boot)
library(dplyr)

df <- bind_rows(
  data_frame(t=1:10, ts="A", dat=1:10),
  data_frame(t=1:10, ts="B", dat=101:110)
)

bsdf <- group_by(df, ts) %>% 
  do(bs = boot(.$dat, R = 10, statistic = function(d, ind) mean(d[ind])))

bsdf %>% mutate(
  mean = bs$t0, # ok 
  var = var(bs$t) # fails
)
```

(which I'm pretty sure is because hybrid $ isn't quite right)

@romainfrancois can you take a look? If you point me to the hybrid implementation of `$` I can also think about improvements.

**Comment by sebschub** [comment]
It worked with dplyr 0.4.2. Just tested on another machine:
```R
> bsdf %>% mutate(
    mean = bs$t0, # ok 
    var = var(bs$t) # fails
  )
Source: local data frame [2 x 4]
Groups: <by row>

  ts        bs  mean      var
1  A <S3:boot>   5.5 0.616000
2  B <S3:boot> 105.5 1.411556
> var(bsdf$bs[1][[1]]$t)
      [,1]
[1,] 0.616
> var(bsdf$bs[2][[1]]$t)
         [,1]
[1,] 1.411556
```
With just dplyr updated to 0.4.3, the `var` line fails.

**Comment by romainfrancois** [comment]
I am due a revision of hybrid. I have several issues assigned to le related to that problem. I'll pick this up. 

Envoyé de mon iPhone

**Comment by hadley** [comment]
Related to #912, and also need to make sure `[[` works.

**Comment by hadley** [comment]
From #1067:

```R
tbl <- data.frame(id = c(1, 2, 3))
vals <- list(n = list(n = 2))

filter(tbl, id >= vals$n$n)
```

**Comment by antoine-lizee** [comment]
Related to #1491

**Comment by krlmlr** [comment]
Need a minor extension to `traverse_call()`.
