### ISSUE TITLE
Selecting 1 column of tbl_df with matrix indexing results in tbl_df not vector

### ISSUE THREAD

**Issue by grasshoppermouse** [hadley/dplyr#1415]
Feature or bug (or am I missing something)?

    library(dplyr)
    d = data_frame(A=1:3, B=4:6)
    class( d[,'A'] )  # "tbl_df"     "data.frame"

    d = data.frame(A=1:3, B=4:6)
    class( d[,'A'] )  # integer

**Comment by romainfrancois** [comment]
This is by design. You can use: 

```
> class( d[['A']] )
[1] "integer"
```
