### ISSUE TITLE
dplyr verbs removing additional classes

### ISSUE THREAD

**Issue by datalove** [hadley/dplyr#1429]
I'm building a package to work with objects that are a special case of a `tbl_df` in which there is 'interval' information in the columns (i.e. one column for `start` of interval and one column for `end` of interval). 

I have a constructor that adds a class to an existing `data.frame` or `tbl_df` (and some attributes too). But it seems that `dplyr` verbs like to remove any classes that I add. 

For example:

```{r}
add_class <- function(x,name) {class(x) <- c(class(x),name); x}
```
```{r}
df <- mtcars %>% add_class('something_new')
df %>% class()
[1] "data.frame"    "something_new"
```
But dplyr verbs strip the new class...

```{r}
df %>% arrange(mpg) %>% class()
[1] "data.frame"
> df %>% filter(mpg > 30) %>% class()
[1] "data.frame"
> df %>% tbl_df() %>% class()
[1] "tbl_df"     "tbl"        "data.frame"
```

I notice that dplyr 0.4.3 now preserves attributes, but it looks like classes are still getting eaten. 

Is this something that's on anyone's radar? I haven't been able to find an issue for it.

**Comment by hadley** [comment]
Did we do this deliberately? I think we should follow the same logic as preserving attributes of columns.

**Comment by eibanez** [comment]
Related to #553

**Comment by hadley** [comment]
Your class is incorrect - it should be `c("something_else", "data.frame")`.  

And I think doing this correctly is up to you - you need to define a method for your class for each dplyr method that correctly restores all the classes and attributes.  It's going to be extremely fiddly to do this in dplyr, and it doesn't seem like a huge benefit to me given that there's already a work around (which is arguably the correct thing to do anyway.

**Comment by datalove** [comment]
Thanks Hadley. That's how I've managed to get it to work so far, but was hoping there'd be an easier way.
