### ISSUE TITLE
Error in install.packages : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by my-katie** [hadley/dplyr#1433]
I have the following error when installing dplyr

************************
| Trying to install package ‘dplyr’ now...
also installing the dependency ‘BH’

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/BH_1.58.0-1.zip'
Content type 'application/zip' length 13846694 bytes (13.2 MB)
downloaded 13.2 MB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/dplyr_0.4.3.zip'
Content type 'application/zip' length 2552598 bytes (2.4 MB)
downloaded 2.4 MB

Error in install.packages : missing value where TRUE/FALSE needed

| Could not install package ‘dplyr’!
  |                                                                           |   0%
Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

******************

Can anyone help me understand what I'm missing?

**Comment by tentacles-from-outer-space** [comment]
Seems to be same issue: https://github.com/swirldev/swirl/issues/260

**Comment by my-katie** [comment]
Hi 'tentacles from outer space', thanks for your response. I was really happy to know I might have a solution to the problem above but after trying what was suggested... to install dplyr using R (and changing the mirror to another a few times), I still get the same error.

Any other ideas?

**Comment by tentacles-from-outer-space** [comment]
Try to run clean R session (no Rstudio, no other instances running, etc) and run following command:

```{r}
install.packages("dplyr", repos = c(CRAN="https://cran.r-project.org/"))
```

If this failed please provide results (from the same session) of `sessionInfo()`.

**Comment by robbionline** [comment]
Hi, I experience nearly the same issue when trying to install "maptools".

This is the history of a new R Session:

> install.packages("maptools", dependencies = TRUE, repos = c(CRAN="https://cran.r-project.org/"))
Installing package into ‘\\ABC/Daten/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘maps’, ‘raster’, ‘polyclip’

>versuche URL 'https://cran.r-project.org/bin/windows/contrib/3.2/maps_3.1.0.zip'
Content type 'application/zip' length 3610284 bytes (3.4 MB)
downloaded 3.4 MB

>versuche URL 'https://cran.r-project.org/bin/windows/contrib/3.2/raster_2.5-2.zip'
Content type 'application/zip' length 3075995 bytes (2.9 MB)
downloaded 2.9 MB

>versuche URL 'https://cran.r-project.org/bin/windows/contrib/3.2/polyclip_1.5-6.zip'
Content type 'application/zip' length 484745 bytes (473 KB)
downloaded 473 KB

>versuche URL 'https://cran.r-project.org/bin/windows/contrib/3.2/maptools_0.8-39.zip'
Content type 'application/zip' length 1814615 bytes (1.7 MB)
downloaded 1.7 MB

>Fehler in if (any(diff)) { : Fehlender Wert, wo TRUE/FALSE nötig ist

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] tools_3.2.3`

**Comment by Deleetdk** [comment]
In my case, the issue happened after installing 3.4.0 (win 10, 64-bit). I got a lot of similar errors, and could not find any working solutions. I ended up rolling back to 3.3.3.

**Comment by aymaliev** [comment]
Had the same problem. 
The solution, suggested by @Deleetdk worked. (ty)

**Comment by PabloGarciaPascual** [comment]
Same problems as commented after installed today version 3.4.0 (win 8.1, 64-bit).
Does the new name have something to do with this (R version 3.4.0 (2017-04-21) -- "**_You Stupid Darkness_**")

**Comment by shuom** [comment]
+1 to issues updating to 3.4.0

**Comment by tentacles-from-outer-space** [comment]
I had no problems - fresh R install, dplyr instalation. No Rstudio involved (important?).

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0
```

**Comment by shuom** [comment]
Yes, rstudio is involved. I can install packages fine in r.exe.

**Comment by hadley** [comment]
Can someone please file an new issue with a minimal reprex and `session_info()`. Adding comments on an old and likely unrelated issue is not a good way to get the problem fixed.

**Comment by dmenne** [comment]
No, it is not an RStudio problem, but shows there earlier. To simplifiy, try in RGui

```
install.packages("abind") # ok first time asks for server. Any package will do, this is small
# Try again
install.packages("abind") # Boom "file.exists()....")
```

In Rstudio this gives an error on the first run, but I assume it has to do with some background action



```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0   
> 

```

**Comment by dmenne** [comment]
The error is with file.mtime(lib) in installed.packages(): file.mtime(anydirectory) returns NA in my system.

**Comment by VoronDM** [comment]
I have the same problem after updating R to 3.4.0. Rolling back to 3.3.3. This is the only solution.

**Comment by jan-glx** [comment]
It is a bug in R 3.4.0, already reported and fixed (but there is no new release) see https://www.mail-archive.com/r-help@r-project.org/msg243256.html

**Comment by VoronDM** [comment]
**Object not found!**
https://cran.r-project.org/bin/windows/base/R-3.4.0patched-win.exe

**Comment by PabloGarciaPascual** [comment]
Thank you, jan-glx.
The pachted version of R-3.4.0 works, once I copied manually the packages from the old library 3.3. On the other hand, the current version 3.4.0 (not patched) doesn't update the packages.

**Comment by cqneosun** [comment]
I ended up rolling back to 3.3.3 too

**Comment by dmenne** [comment]
Please do not post the problems with R 3.4.0 here. This is tidyverse/dplyr, and dplyr is totally innocent!

**Comment by pcluo** [comment]
same here. had this problem with 3.4. rolling back to 3.3.3, too

**Comment by sajjadphd** [comment]
I had the same error. I used R not RStudio to install the package. The problem was solved.

**Comment by alexunder** [comment]
In 2018, I occurred this problem, Need I roll back to 3.3.3? Now my R version is 3.4.4.

Actually I have already installed the ggplot2, but every time when I wanted to learn the statistical  course, it let me install "ggplot2" again, it's forever failed, so I can't access the courser material.

**Comment by batpigandme** [comment]
@alexunder Since it's unlikely that this is a bug in ggplot2, this sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer, it will help you to create a reproducible example, because currently you don't give enough information for us to troubleshoot.)
