### ISSUE TITLE
Support for Bioconductor DataFrame class?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/dplyr#1435]
The Bioconductor project has their own implementation of data.frame in S4 called DataFrame, which basically works like a regular data.frame except that it can hold Bioconductor's S4 vector types such as Rle, List, and GRanges that cannot be stored as columns an ordinary data frame. What would be required to add support for the DataFrame class to dplyr operations? I would be willing to try my hand at it if it's not too complicated.

The following works as a quick an dirty implementation of mutate for DataFrame objects, but it only works if the conversion from DataFrame to data.frame succeeds. This would prevents it from working on any DataFrame containing S4 vector columns, which kind of defeats the point. 

```R
mutate_.DataFrame <- function(.data, ..., .dots) {
    .data %>% as.data.frame %>% mutate_(.data=., ..., .dots=.dots) %>% as("DataFrame")
}
```

(Technically, this will succeed for some S4 vector columns that define coercions to primitive vectors/lists on conversion to a data.frame, but this is suboptimal because those columns would not be converted back to their original class by `as("DataFrame")`.)

**Comment by hadley** [comment]
I think it would be most appropriate to implement that in another package, since I won't know enough to maintain it.
