### ISSUE TITLE
Is select_impl() overly conservative regarding duplicate colnames?

### ISSUE THREAD

**Issue by WilDoane** [hadley/dplyr#1436]
At https://github.com/hadley/dplyr/blob/master/src/select.cpp#L74 select_impl() checks whether there are duplicate column names and stops, if there are. Is this too conservative?

Suppose I've read in data in some way that results in duplicated column names (readxl or forced names, as below). There are colnames that are duplicates. I want to select some subset of columns that (at least potentially) doesn't include any of the duplicated columns.

```{r}
df <- read.csv(text = "a,a,b
1,2,3")

colnames(df) <- c("a", "a", "b")

dplyr::select(df, b)
```

> Error: found duplicated column name: a

What bad things would happen were select_impl() less restrictive? Suppose a new rule that only the colnames you're selecting had to be unique within the data.frame. E.g., given colnames == "a", "a", "b", you would only be able to select column "b" without an error.

One could go further and say that select_impl() would select all columns with matching names... but that's probably too unintuitive and likely to result in unexpected results for casual users.

**Comment by hadley** [comment]
I don't think that's unreasonable, but we implemented the current approach to fail early. That makes life a lot easier for us, because we can always rely on getting a valid dataframe.
