### ISSUE TITLE
An option to retain non-duplicated rows for function distinct

### ISSUE THREAD

**Issue by zhilongjia** [hadley/dplyr#1440]
Here is an enhancement.

From the manual of __distinct__: If there are multiple rows for a given combination of inputs, only the first row will be preserved.

It's useful only to get the non-duplicated rows (based a column) for function __distinct__. Here the non-duplicated rows is not as same as _unique_ because _unique_ keeps non-duplicated rows and representatives for duplicated rows. the problem for unique is the data is not true or paradoxical for the duplicated rows. 

For example:

a 1
b 1
c 2
s 4

distinct (only for 2nd column) will get 

a 1
c 2
s 4

distinct with the proposed option (only for 2nd column) will get 

c 2
s 4

Thank you.

**Comment by hadley** [comment]
I think you could just do that with `n()`:

```R
df %>% 
  group_by(x) %>%
  filter(n() > 1)
```
