### ISSUE TITLE
No date field in DESCRIPTION

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1442]
Not a huge problem, but `citation("dplyr")` warns about this and returns a string with a blank year and empty parentheses.  

    Hadley Wickham and Romain Francois (). dplyr: A Grammar of Data Manipulation. R package version
    0.4.3.9000. https://github.com/hadley/dplyr

So you might want to either add the date field in or provide a `CITATION` file.

**Comment by hadley** [comment]
I don't use date fields in any packages because they're a hassle to maintain and pointless (because CRAN adds a built date field). I think the bug is that citation() doesn't use that field.

**Comment by richierocks** [comment]
Fair enough.  Filed as a bug in R.

[citation behaves awkwardly when a package has no Date field](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16550)
