### ISSUE TITLE
Poor performance on dates compared to base R

### ISSUE THREAD

**Issue by uptownfunk** [hadley/dplyr#1444]
I've been using dplyr with lubridate-parsed date values. Everything is functional, but performance pales in comparison to base R when I've run the two side-by-side. If I'm doing a summarise or mutate to get the #of days between transactions, I could run:

```r
df <- df %>% 
  group_by(PERSON_ID) %>% 
  mutate(DAYS_TO_LAST_TX = (TX_DATE - lag(TX_DATE) / edays(1)))
```

This code takes a while to run, whereas I could write equivalent base-R code and get it done much quicker, but with more lines of code.

**Comment by stanstrup** [comment]
Seems similar to #1395.

**Comment by hadley** [comment]
Please provide a minimal reprex
