### ISSUE TITLE
bind_rows() for list of vectors

### ISSUE THREAD

**Issue by mschubert** [hadley/dplyr#1450]
Is there a reason that `bind_rows()` works for a list of lists but not for a list of (named) vectors?

```r
> bind_rows(list(list(a=3,b=5), list(a=16)))
Source: local data frame [2 x 2]
      a     b
  (dbl) (dbl)
1     3     5
2    16    NA
> bind_rows(list(c(a=3,b=5), c(a=16)))
Error: cannot convert object to a data frame
```

**Comment by jennybc** [comment]
This would be really nice. Possibly useful in simplifying list-columns that hold (named) atomic vectors.

**Comment by hadley** [comment]
I think this is pushing `bind_rows()` too far - you can either give it lists or data frames. Otherwise you need to coerce yourself.

**Comment by artemklevtsov** [comment]
Coerce list of vectors to a list or data.frame will be too slow.

**Comment by romainfrancois** [comment]
I'm with @hadley here. supporting lists was already a stretch. I'm not necessarily opposed to offer some way of doing this, but the logic in bind_rows is already way too complicated as it is.

**Comment by Fablepongiste** [comment]
I had exactly same issue and it worked amazingly well using smartbind of gtools package ?
