### ISSUE TITLE
Unclear limitations on the calculations that can be performed in mutate.

### ISSUE THREAD

**Issue by tmalsburg** [hadley/dplyr#1452]
I’d like to use `mutate` to create a new column but the calculations are not entirely trivial.  Here is one example illustrating the kind of things I would like to do:

``` R
d %>%
  group_by(tid) %>%
  mutate(before.event = {
    idx <- which(diff(chars) < 0)[1]
     c(rep(T, idx), rep(F, n()-idx))
  })
```

This code produces an error message saying that assignments are forbidden.  So I tried the following work-around:

``` R

f <- function(x) {
  idx <- which(diff(x) < 0)[1]
  c(rep(T, idx), rep(F, n()-idx))
}

d %>%
  group_by(tid) %>%
  mutate(before.event = f(chars))
```

but this also produces an error message:

```
Error: This function should not be called directly
```

This is fairly surprising because I can of course use other functions in mutate, e.g:

``` R
d %>%
  group_by(tid) %>%
  mutate(test = min(chars))
```

I looked in various places for an explanation but couldn’t find one (man pages, GitHub page, introduction to dplyr, …).  There clearly seem to be limitations as to which things can be done and which functions can be used but it is not clear what these limitations are.  This can be of course be a little discouraging for new users.  So I’d say there is at least a documentation issue here.

While this issue could be addressed by improving the documentation, it would of course be much better if there weren’t any limitations in the first place.  I can think of many situations where it would be extremely useful if assignments and user-defined functions were allowed.  I really like dplyr's interface but the ability to use arbitrary code-blocks to carry out calculations in conjunction with `mutate` but also `summarise` would clearly set dplyr apart from alternative solutions like reshape and data.table.

**Comment by andrewla** [comment]
The problem is that `n()` is being called inside your function; that's the function that `cannot be called directly`.  You can pass it in as an extra parameter as a workaround, but this is not really specific to mutate/summarise.  The error message could probably be improved, though.

**Comment by tmalsburg** [comment]
Ah, R's error messages!  Thanks for clarifying.  The main question is then: Why do we have to wrap some computations in functions but not others?  And how can we decide whether a computation needs to be wrapped?  Is the rule basically that we have to wrap any computation that consists of more than one statement?

**Comment by tmalsburg** [comment]
> Is the rule basically that we have to wrap any computation that consists of more than one statement?

No, it's not.  I just checked and a code block with multiple statements works.  From a user perspective, it seems fairly arbitrary that we can do anything but not assign variables.

**Comment by hadley** [comment]
It's called a bug.

**Comment by tmalsburg** [comment]
Well, the error message ("assignments are forbidden") made it sound as if it was a feature.

**Comment by hadley** [comment]
@romainfrancois could you review this in the context of general improvements to the hybrid evaluator? It would be nice if we could allow `<-` when used inside `{`.  If it's going to be a lot of work, we don't have to do it, but we need to at least document better.

**Comment by romainfrancois** [comment]
I think it is some work, but not necessarily a huge amount. And hybrid evaluation is on my imminent list of things to deal with.

**Comment by antoine-lizee** [comment]
FYI, it seems that using soft assignments work as needed (which kinda makes sense):
```
iris %>%
  mutate(test = {
    idx = which(diff(Petal.Width) < 0)[1]
    c(rep(T, idx), rep(F, n()-idx)) })
```

**Comment by krlmlr** [comment]
There's `local()`, the contents of which are exempt of analysis. Unfortunately:

```R
> iris %>%
+   mutate(test = local({
+     idx <- which(diff(Petal.Width) < 0)[1]
+     c(rep(T, idx), rep(F, n()-i .... [TRUNCATED] 
Error in eval(substitute(expr), envir, enclos) : 
  object 'Petal.Width' not found
```

How about fixing `local()` so that it picks up column names?

**Comment by hadley** [comment]
@krlmlr the approach outlined in #1719 would also fix this case
