### ISSUE TITLE
glimpse vs str on factors

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/dplyr#1454]
currently, `glimpse` just gives `(fctr)` (keeping to the "4 or less" rule) for `factor` columns but with `str` you at least have an idea of the # of levels for the factor. is it worth violating the "4 or less" rule for factors by doing something like `(fctr:3)` or `(fctr:10)` so there is slightly more info? It's an easy tweak and I could PR that + #1325 if no one is currently working on `glimpse.default`.

**Comment by hadley** [comment]
Hmmmm - I'd prefer to keep it short so it can also go in the row header etc.

**Comment by hrbrmstr** [comment]
possibly, then, controlled via an `option` with the default being the current short standard? or make it a `glimpse`-only behavior (I realize that wld be a tiny bit more plumbing). No worries either way, it just came up in a few conversations over the past few weeks and most recently today on SO.

**Comment by hadley** [comment]
I really hate options. Another possibility would be to come up with a shorter form: maybe `<fac:3>` or even `<fc:3>`, or _even_ `<f:3>`? I suspect those are all getting a bit obscure though.

Yet another possibility would be to have another function for secondary info: could be number of factors, TZ for date times etc.

**Comment by hrbrmstr** [comment]
I like the secondary one. Perhaps a `peruse` (implying more than a `glimpse`) that provides just slightly more info for each type?

**Comment by hadley** [comment]
It would need to be parallel to `type_sum` not `glimpse`, so maybe `type_attr` ?

**Comment by hadley** [comment]
I'd be happy to review a PR for this.
