### ISSUE TITLE
[Request] bind_rows for the list of atomic vectors

### ISSUE THREAD

**Issue by artemklevtsov** [hadley/dplyr#1456]
Hi,

Now  `bind_rows()` supports only a list of data frames. It would be nice if `bind_rows()` will work with the list of matrices or vectors.

```r
dplyr::bind_rows(lapply(1:10, function(x) runif(n = 10)))
#> Error: cannot convert object to a data frame
```

**Comment by jennybc** [comment]
duplicate of #1450
