### ISSUE TITLE
group_by() and select() interaction surprising and inconsistent with doco

### ISSUE THREAD

**Issue by MilesMcBain** [hadley/dplyr#1457]
In the dplyr introduction we have: 
> Grouping affects the verbs as follows:
>     * grouped select() is the same as ungrouped select(), except that grouping variables are always retained.

Which is more than a little surprising to anyone used to SQL. Anyhow, in reality this does not prove strictly true (dplyr 0.4.3):

```R
mtcars %>% 
  group_by(cyl) %>%
  summarise(mpg = mean(mpg)) %>%
  select(mpg)
```
gives:
```
Source: local data frame [3 x 1]

       mpg
     (dbl)
1 26.66364
2 19.74286
3 15.10000
```
What happened to `cyl`? Okay:
```R
mtcars %>% 
  group_by(cyl,gear) %>%
  summarise(mpg = mean(mpg)) %>%
  select(mpg)
```
gives:
```
Source: local data frame [8 x 2]
Groups: cyl [3]

    cyl    mpg
  (dbl)  (dbl)
1     4 21.500
2     4 26.925
3     4 28.200
4     6 19.750
5     6 19.750
6     6 19.700
7     8 15.050
8     8 15.400
```
Now we have ```cyl``` but no ```gear``` which looks weird with the duplicate ```cyl``` entries. The pattern continues:
```R
mtcars %>% 
  group_by(cyl,gear, am) %>%
  summarise(mpg = mean(mpg)) %>%
  select(mpg)
```
gives:
```
Source: local data frame [10 x 3]
Groups: cyl, gear [8]

     cyl  gear      mpg
   (dbl) (dbl)    (dbl)
1      4     3 21.50000
2      4     4 23.60000
3      4     4 28.03333
4      4     5 28.20000
5      6     3 19.75000
6      6     4 18.50000
7      6     4 21.00000
8      6     5 19.70000
9      8     3 15.05000
10     8     5 15.40000
```
This doesn't feel right.

**Comment by felasa** [comment]
This is normal. summarising "peels" the grouped variables one by one.

```r
mtcars %>% 
    group_by(cyl) %>%
     summarise(mpg = mean(mpg))
```

produces an ungrouped tbl where as

```r
mtcars %>% 
    group_by(cyl, gear) %>%
    summarise(mpg = mean(mpg))
```

returns a tbl grouped by cyl so that using select on it will keep cyl.

**Comment by MilesMcBain** [comment]
Okay, output makes more sense now thank you. Although peeling the last group works feels like a bit of a kludge to enable summarise() to be chained. Let's look at output for your example 2:
```
Source: local data frame [8 x 3]
Groups: cyl [?]

    cyl  gear    mpg
  (dbl) (dbl)  (dbl)
1     4     3 21.500
2     4     4 26.925
3     4     5 28.200
4     6     3 19.750
5     6     4 19.750
6     6     5 19.700
7     8     3 15.050
8     8     5 15.400
```
So its obvious the data are grouped by two things even though the output is saying it's only one. Maybe the thinking is since `cyl` is the only named group we're to understand only it will be carried forward to chained functions. Okay, but this leads to some weirdness in my second select example, when the mpg data are obviously not grouped by `cyl` alone.

The question is why have this kludge at all? Why not have summarise() obliterate all groups and just report the resulting data frame? To do additional summaries one would create additional groups to summarise over using subsequent group_by() calls. What happens if you call summarise() on a df with no groups? Error most likely.... or you could group by all vars not in the summarise().

But this is off topic for this issue. As is why we need select() to insist on including all groups. There seems to be no conflict with the doco.

**Comment by felasa** [comment]
I've found the peeling very useful. It allows for neater code. Its purpose seems to be to eliminate repeated 'group_by' statements. 

A simple example that i use often-ish:

```r
 mtcars %>%
  group_by(cyl, gear) %>% 
  summarise(N = n()) %>% 
  mutate(prop = N/sum(N))

Source: local data frame [8 x 4]
Groups: cyl

  cyl gear  N       prop
1   4    3  1 0.09090909
2   4    4  8 0.72727273
3   4    5  2 0.18181818
4   6    3  2 0.28571429
5   6    4  4 0.57142857
6   6    5  1 0.14285714
7   8    3 12 0.85714286
8   8    5  2 0.14285714
```
As to why select has to include the grouped variable I'm not so sure, there may some well-though-of workflow related reason but you're correct that the documentation doesn't cover this.

**Comment by hadley** [comment]
How could dplyr group by something that isn't there?
