### ISSUE TITLE
column names vs column index

### ISSUE THREAD

**Issue by davidrengel** [hadley/dplyr#1462]
Hi,

This is not an isue as such, but a question. I am new to dplyr and I find it very useful and handy, except when I have to do things on a loop. Imagine I am on filter(df,colname=="whatever"). My question is: is it possible to provide not the colname but the column index? This would be vey helpful when you need succesive actions on one column at the time. For instance:
for (i in 1:ncol(df))
df.filter[[i]] <- filter(df,colnames(df)[i]=="whatever")

I have not found a way round to implement such "colnames(df)[i]". Am I missing something?

Thanks a lot for you reply and I apologize if usin this "issues" forum to address such a question is not the right conduct.

David

**Comment by hadley** [comment]
No, because in general I think it's a bad idea to work with column indices.

I don't know what larger problem you're trying to solve, but I suspect there's an alternative way to attack it. You might want to try the manipulatr mailing list.

**Comment by davidrengel** [comment]
Thanks Hadley
