### ISSUE TITLE
Feeding string into arrange makes R 3.1.2 crash

### ISSUE THREAD

**Issue by oganm** [hadley/dplyr#1464]
The R crashing problems with arrange and potentially some other functions seems to linger with R 3.1.2.
For arrange doing `diamonds %>% arrange('cut')` crashes instead of returning an error. This problem does not exist in the newest R

**Comment by oganm** [comment]
R console output on crash
```
 *** caught segfault ***
address (nil), cause 'unknown'
Segmentation fault
```

**Comment by hadley** [comment]
Unfortuntately we don't have the resources to support older versions of R.
