### ISSUE TITLE
`bind_rows()` should work  on attribute data frames

### ISSUE THREAD

**Issue by npjc** [hadley/dplyr#1467]
could `bind_rows()` could also bind attribute `tbl_df`s (as in `attr(x, problems)` say when you read in many files with `readr::read_*()` into a list?

**Comment by hadley** [comment]
Hmmm, this actually seems like something readr should do - it would have to give objects an additional class, and then define a `bind_rows()` method.  But we'd also need to make `bind_rows()` generic, and that's hard because it dispatches on `...`.  Let me think about it.

**Comment by hadley** [comment]
The obvious solution is to have a fast path if all inputs share a common base type, otherwise reduce.
