### ISSUE TITLE
Hybrid handler needs way to use environment, not df

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1469]
To disambiguate:

```R
vs <- 4
filter(mtcars, cyl == vs)
filter(mtcars, cyl == global(vs))
```

This is particularly important for functions.

Moved from #126. cc @romainfrancois @kevinushey @hs3180

**Comment by kevinushey** [comment]
I'd hope something like this would work:

```r
library(dplyr)

global <- function(x, envir = parent.frame())
  get(as.character(substitute(x)), envir = envir)

filter(mtcars, cyl == global(vs))
```

but I get a pretty strange error:

```r
> library(dplyr)
> 
> global <- function(x, envir = parent.frame())
+   get(as.character(substitute(x)), envir = envir)
> 
> filter(mtcars, cyl == global(vs))
Error: object '0' not found
```

I guess it would need a specialized internal implementation like for `n()`?

**Comment by romainfrancois** [comment]
Yes this needs to be handled internally. I'd also like the reverse, to make SE easier: 

```
var <- "disp"
filter( mtcars, local(var) < 150 )
```

...

**Comment by romainfrancois** [comment]
Does `global` imply global environment or the parent frame ? or do we need two notations ?
