### ISSUE TITLE
False positive table already exists error with Postgres schemas

### ISSUE THREAD

**Issue by momeara** [hadley/dplyr#1470]
SUMMARY:
    `db_has_table.PostgresSQLConnection` returns true when a table exists a schema that that is not on the search path, making `dplry::copy_to()` fail when it doesn't need to.

EXAMPLE:

```
library(dplyr)
library(DBI)
data_repo <- src_postgres(...)
con <- data_repo$con

# create decoy table in schema1
dbGetQuery(con, "CREATE SCHEMA schema1;")
dbGetQuery(con, "SET search_path TO \"$user\",schema1,public;")
dbGetQuery(con, "CREATE TABLE my_table (key INTEGER);")

# try to use dplyr::copy_to to create my_table in schema2
dbGetQuery(con, "CREATE SCHEMA schema2;")
dbGetQuery(con, "SET search_path TO \"$user\",schema1,public;")
my_table <- data.frame(key=c(1,2,3))
data_repo %>% copy_to(my_table, temporary=F)
## fails saying that my_table already exists.
```

DIAGNOSING THE ISSUE:
Before copying, `copy_to.sql_src` first checks if the table exists,

```
if (isTRUE(db_has_table(dest$con, name))) {
  stop("Table ", name, " already exists.", call. = FALSE)
}
```

Here, `db_has_table(con, name)` checks if `name` is in `db_list_tables(con)`. But `db_list_tables(con)` calls `DBI::dbListTable`, which returns tables in all schemas, not just the visible ones.

PROPOSED SOLUTION:
Make a `db_list_tables.PostgreSQLConnection` that instead calls

```
dbGetQuery(
    con,
    "SELECT relname FROM pg_class WHERE relkind IN ('r', 'v') AND pg_table_is_visible(oid);")[,1]
```

Using `pg_table_is_visible` is idiomatic for PostgreSQL (http://stackoverflow.com/questions/5062533/postgres-select-all-tables-in-the-current-search-path), and also returns temporary tables.

**Comment by hadley** [comment]
This feels like this should naturally get fixed once dplyr switches to use RPostgres instead of RPostresSQL

**Comment by krlmlr** [comment]
I think dplyr should be more permissive and not assume that it knows about all existing tables. We could give a warning/message if we attempt to access a table that we *think* is missing, the query will fail soon enough if the table/view is missing indeed.

**Comment by hadley** [comment]
@krlmlr I think that's a reasonable solution.
