### ISSUE TITLE
copy_to for PostgreSQLConnections fails for copying large tables to databases

### ISSUE THREAD

**Issue by momeara** [hadley/dplyr#1471]
SUMMARY:
Add a `fast` parameter to `copy_to` so that for PostgreSQLConnections, it uses `RPostgreSQL::postgresqlCopyInDataframe` rather than `INSERT INTO ...`.

EXAMPLE:
```
library(dplry)
library(RPostgreSQL)
data_repo <- src_postgres(...)
n <- 10000000
df <- data.frame(x=1:n, y=runif(n))
system.time({data_repo %>% copy_to(df, "test_tbl")})
```
returns this:
```
 Error in postgresqlExecStatement(conn, statement, ...) :
   RS-DBI driver: (could not Retrieve the result : server closed the connection unexpectedly
         This probably means the server terminated abnormally
         before or while processing the request.
 )
 Error: C stack usage  308954544 is too close to the limit
 Error in postgresqlExecStatement(conn, statement, ...) :
   RS-DBI driver: (could not run statement: no connection to the server
 )
 Timing stopped at: 350.127 37.36 551.529
```

DIAGNOSING THE PROBLEM:
`db_insert_into`, called by `copy_to`, attempts to create a string of the values to insert,
```
values <- paste0("(", rows, ")", collapse = "\n, ")
```
This can be slow and consume lots of memory, causing `copy_to` to fail for copying tables of millions of rows to a database.

PROPOSED SOLUTION:
Its recognized that the fastest way to insert data into a Postgres database is to use the `COPY` command (http://stackoverflow.com/questions/758945/whats-the-fastest-way-to-do-a-bulk-insert-into-postgres). Indeed, `RPostgreSQL` has a poorly documented command `postgresqlCopyInDataframe` that does just that.

Adding a `fast` argument to `copy_to` and replacing the `db_insert_into(con, name, df)` line in `copy_to.src_postgres` with with this:
```
if(fast){
  #http://james.hiebert.name/blog/work/2011/10/24/RPostgreSQL-and-COPY-IN/
  #warning this doesn't report any errors on failure!
  field_names <- escape(ident(names(types)), collapse = NULL, con = con)
  fields <- dplyr:::sql_vector(field_names, parens = TRUE, collapse = ", ", con = con)
  sql <- build_sql(
    "COPY ", ident(name), " ", fields, " FROM STDIN;",
    con=con)
  dbSendQuery(con, sql)
  postgresqlCopyInDataframe(con, df)
} else {
  db_insert_into(con, name, df)
}
``` 

Then calling
```
system.time({data_repo %>% copy_to(df, "test_tbl", fast=T)})
```
return the impressively fast time of
```
    user  system elapsed
   9.906   0.368  13.788
```

Since `postgresqlCopyInDataframe` currently doesn't do very good error reporting (http://james.hiebert.name/blog/work/2011/10/24/RPostgreSQL-and-COPY-IN/), it's probably best to make it optional rather than the default.

**Comment by krlmlr** [comment]
This might work for Postgres, but will it work the same for MySQL, SQLite, MonetDB, ...? A simple solution would be to import in chunks of, say, (10000 / ncol) rows.

**Comment by hadley** [comment]
This should be fixed in underlying DBI implementations

**Comment by krlmlr** [comment]
Current implementation is a bit inconsistent: MySQL has `LOAD DATA INFILE` (pretty much the same as suggested here), Postgres has a bunch of `INSERT` statements, only SQLite forwards to `dbWriteTable()`. I think this deserves a closer look.

**Comment by cronacronis** [comment]
Is there (`DBI`) a new issue for that?

**Comment by momeara** [comment]
It looks like the `rpostgresql` package is in archive mode over on code.google.com and aught to be ported to GitHub before new issues are reported. The owner is @eddelbuettel, so perhaps he would have an idea of the current plans for the package.

**Comment by eddelbuettel** [comment]
@momeara Nope, I am not the owner of RPostgreSQL.  

I was its first (co-)maintainer and author when I mentored it for Google Summer of Code, but Tomoaki took over years and [_is listed as the Maintainer_](https://github.com/cran/RPostgreSQL/blob/master/DESCRIPTION#L7)   in the DESCIPTION file.

But for the record I disagree with this being closed. You correctly identified a bug, and @hadley merely "wished it away".  To me it is still there.  But not my project so :expressionless: ...

**Comment by momeara** [comment]
Ok thanks for the heads up. I'll contact Tomoaki.

**Comment by eddelbuettel** [comment]
Let me know how it goes. He has been somewhat silent of late...

**Comment by cronacronis** [comment]
FYI
```
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname = "coredata", host = , user = , password = )
dbSendQuery(con, 'DELETE FROM "CoreDataCommon";')
dbSendQuery(con, "SET log_statement = 'all';")
dbWriteTable(con, "CoreDataCommon", dt_cases, append = TRUE, row.names = FALSE)`

```
Shows in the log `/var/log/postgresql/postgresql-9.4-main.log` trace of `COPY`
```
2015-11-25 16:42:01 UTC [60369-12] pgadmin@coredata LOG:  statement: SELECT current_schema()
2015-11-25 16:42:01 UTC [60369-13] pgadmin@coredata LOG:  statement: select tablename from pg_tables where schemaname !='information_schema' and schemaname !='pg_catalog' and schemaname='public' and tablename='CoreDataCommon'
2015-11-25 16:42:01 UTC [60369-14] pgadmin@coredata LOG:  statement: select attnotnull from pg_attribute where attrelid=11171 and attnum='2'
2015-11-25 16:42:01 UTC [60369-15] pgadmin@coredata LOG:  statement: SELECT current_schema()
2015-11-25 16:42:01 UTC [60369-16] pgadmin@coredata LOG:  statement: select tablename from pg_tables where schemaname !='information_schema' and schemaname !='pg_catalog' and schemaname='public' and tablename='CoreDataCommon'
2015-11-25 16:42:01 UTC [60369-17] pgadmin@coredata LOG:  statement: select attnotnull from pg_attribute where attrelid=11171 and attnum='2'
2015-11-25 16:42:01 UTC [60369-18] pgadmin@coredata LOG:  statement: SHOW client_encoding
2015-11-25 16:42:01 UTC [60369-19] pgadmin@coredata LOG:  statement: SET CLIENT_ENCODING TO 'UTF8'
2015-11-25 16:42:01 UTC [60369-20] pgadmin@coredata LOG:  statement: COPY "CoreDataCommon" FROM STDIN
2015-11-25 16:42:01 UTC [60369-21] pgadmin@coredata LOG:  statement: SET CLIENT_ENCODING TO 'UTF8'
```

**Comment by iangow** [comment]
If the code uses `sql <- build_sql("INSERT INTO ", ident(table), " VALUES ", sql(values))` instead of `dbWriteTable`, then it seems it would be difficult for the "underlying DBI implementations" to fix this.
