### ISSUE TITLE
dplyr sp integration

### ISSUE THREAD

**Issue by bramtayl** [hadley/dplyr#1473]
I'm not sure if this should be properly under dplyr or under sp. But it would be great to be able to integrate functionality. For example, this doesn't work:

```{r}
library(dplyr)
library(sp)

data_frame(x = 1, y = 1, z = 1) %>%
  `coordinates<-`(~x + y) %>%
  slice(1)
```

**Comment by romainfrancois** [comment]
`dplyr` uses S3, and so the inheritance relationship is not formalized, I guess you could do: 

```
`coordinates<-.tbl_df` <- getMethod( "coordinates<-", "data.frame" )
slice_.SpatialPointsDataFrame <- function(x, ...) slice_( as.data.frame(x),  ... )
> data_frame(x = 1, y = 1, z = 1) %>% `coordinates<-`(~x + y) %>% slice(1)
  x y z
1 1 1 1
```

**Comment by romainfrancois** [comment]
Or perhaps: 

```
setOldClass( c("tbl_df", "tbl", "data.frame" ) )
```

This only works for `coordinates<-` though, not automatically for `slice`.

**Comment by bramtayl** [comment]
Wouldn't you also need to modify slice to return an sp object as well?

**Comment by hadley** [comment]
I think this more of an sp issue - unfortunately I don't have the time to adapt the data frame variations used by other packages to work with dplyr.

**Comment by mdsumner** [comment]
I don't want prolong a closed thread, but fwiw the setOldClass approach does remove the most fundamental limitations in bringing dplyr to sp-related data. I didn't understand this until yesterday. 

https://gist.github.com/mdsumner/3f1cc24306dc6a55a5b526d440d5c04c

I've put this into my spbabel package, which also outlines other non-sp relational-data approaches. 

https://github.com/mdsumner/spbabel

It's very much in flux, and progress is pretty slow and I'm still not absolutely sure on what the best way/s forward are, but I'm pretty sure we need more than one way. Very keen to have input from others on what is going to work best.
