### ISSUE TITLE
logic behind sql_translate(1e-10) == sql("0.0")?

### ISSUE THREAD

**Issue by momeara** [hadley/dplyr#1479]
Even though Postgres can handle arbitrary floating point numbers, sql_translate converts small but reasonable floating point numbers to zero.

If `is.wholenumber(x)` then `sql_translate` evaluates `x` as `sprintf("%.1f", x)`.

I found this logic surprising. Is there a reason for this behaviour? If so, perhaps it could be documented more prominently?

**Comment by hadley** [comment]
Hmmm, I think I was trying to be too clever here while trying to produce "nice" output.

**Comment by hadley** [comment]
Oooooh, no the problem is that `as.character(1)` produces "1", which would be an integer in SQL.

**Comment by hadley** [comment]
Do you have a real example where this caused problems? I don't see an easy fix.

**Comment by momeara** [comment]
Yes, I have a table of associations between genes with their p-values. I would like to filter for all significant genes using a stringent P-value threshold of 1e-10. But when I put in  `filter(p_value < 1e-10)` it silently converts it to `filter(p_value < 0)`, which excludes all of the relevant hits.

My work around has been to use `filter(p_value < sql("1e-50"))`, which works but took me a while to figure out.

**Comment by hadley** [comment]
Hmmm, if you really care about small p values, I think you'd be better off working on the log scale.
