### ISSUE TITLE
Segfault caused by min function in summarise function

### ISSUE THREAD

**Issue by Fija** [hadley/dplyr#1481]
When apply min function on summarizing an empty data.frame, it would lead to segfault.
```R
df <- tbl_df(data.frame(A=c(1)))
df <- df %>% filter(A > 1)
df %>% summarise(Min=min(A, na.rm=T))
```
more details see this [StackOverflow Question](http://stackoverflow.com/questions/32603843/dplyr-min-function-in-summarise-function-causes-r-crash)

**Comment by romainfrancois** [comment]
@hadley should I also throw a warning like R does ?

**Comment by hadley** [comment]
I don't think so - R isn't consistent anyway compare `sum()` and `max()`

**Comment by bwlewis** [comment]
+/- Inf is not always expected; sorry I'm not good enough w/c++ to write a sol'n but I can give an example:

```r
min(1[-)],na.rm=TRUE)
[1] Inf
Warning message:
In min(1[-1], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf

>  min("a"[-1],na.rm=TRUE)
[1] NA
Warning message:
In min("a"[-1], na.rm = TRUE) : no non-missing arguments, returning NA
```
But in dplyr with the current commit:

```r
> summarise(data.frame(A=1[-1]), Min=min(na.rm=TRUE))
  Min
1 Inf
Warning message:
In min(na.rm = TRUE) : no non-missing arguments to min; returning Inf

> summarise(data.frame(A="a"[-1]), Min=min(na.rm=TRUE))
  Min
1 Inf
Warning message:
In min(na.rm = TRUE) : no non-missing arguments to min; returning Inf
```

**Comment by bwlewis** [comment]
For the record I think R is idiosyncratic here. I kind of wish min(numeric()) returned numeric(0), and so on for other types. Oh well.

**Comment by hadley** [comment]
I think the contract for `min()` (and all other summary functions is that they always return a numeric vector of length 1, so I think returning a 0-length vector would be less helpful, not more.

**Comment by bwlewis** [comment]
Yes, that's what I meant by idiosyncratic. Mathematically, the minimum of a set S is the intersection of S with infimum(S), a.k.a. the smallest value in the set.  Mathematica, Matlab, etc.  return min(empty set) = empty set, consistent with that definition, R does not.
