### ISSUE TITLE
bind_rows() silently converts factor to character

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1485]
``` r
library(dplyr)
class(iris$Species)
#> [1] "factor"
iris2 <- bind_rows(head(iris, 1),
                   tail(iris, 1) %>% mutate(Species = as.character(Species)))
class(iris2$Species)
#> [1] "character"
```

The joins issue a warning whenever they do this.

**Comment by romainfrancois** [comment]
Right. @hadley do we need a warning here ?

**Comment by romainfrancois** [comment]
```
> d1 <- head(iris, 1)
> d2 <- tail(iris, 1) %>% mutate(Species = as.character(Species))
> res <- bind_rows(d1,d2)
> str(res)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	2 obs. of  5 variables:
 $ Sepal.Length: num  5.1 5.9
 $ Sepal.Width : num  3.5 3
 $ Petal.Length: num  1.4 5.1
 $ Petal.Width : num  0.2 1.8
 $ Species     : chr  "setosa" "virginica"
```

**Comment by hadley** [comment]
Yeah, we should be consistent wherever we do coercion.

**Comment by RichardJActon** [comment]
I think it would be nice to have a 'refactor' option on this function so that you get a new factor with levels from both of the previous data objects instead of a character vector, a choice of what to coerce to as it where.

**Comment by batpigandme** [comment]
Hi @RichardJActon,

Just a heads up: comments on old, closed issues have pretty low-visibility, and (depending on the package and age of the issue) may not be consistent with current versions.

If this is something you think needs serious reconsideration, please open a new issue that follows the [tidyverse guidelines](https://www.tidyverse.org/contribute/#issues).

Thanks

**Comment by RichardJActon** [comment]
Hi @batpigandme  Thanks for the heads up, 

This is more a suggested feature, the standard format for raising issues seems quite tailored for bug reports, are suggested features welcome via issues?

Thought I'd raise it here in case someone who knew what they were talking about could shoot it down on grounds that would be inconsistent with some standard behaviour in the tidyverse, before I went any further with it.

**Comment by batpigandme** [comment]
@RichardJActon,
You can certainly submit feature requests— the format should be similar to an issue in the sense that you show the difference between the current behaviour and the desired one. 

If you're reopening something for discussion, you should probably address whatever concerns were previously mentioned (speaking abstractly here). I recommend browsing through some of the existing issues with the <kbd>feature</kbd> label ([here](https://github.com/tidyverse/dplyr/issues?q=is%3Aopen+is%3Aissue+label%3Afeature)) to get a sense of what the maintainers ask for, etc. — I'd avoid using the ones submitted by the maintainers (e.g. hadley, krlmlr), as they tend not to follow form in the same way.

**Comment by RichardJActon** [comment]
Ah, I think I found an existing open issue to which this is applicable: #3278. Thanks for the help @batpigandme.
