### ISSUE TITLE
bind_all() for matrices

### ISSUE THREAD

**Issue by thomasp85** [hadley/dplyr#1486]
Migrated from #803 

When initially posted I contemplated on making a matrix dispatch into the same functionally as used for bind_all(). Currently though I do it with pure R code, as matrices are simpler structures that requires less checks as they are simple vectors. With that in mind i propose a construct such as this

```r
rbindMat <- function(x, ..., fill = NA) {
    if (inherits(x, 'matrix')) x <- list(x, ...)
    if (length(x) == 1) return(x[[1]])
    cols <- unique(unlist(lapply(x, colnames)))
    rows <- seq(sum(sapply(x, nrow)))
    ans <- matrix(fill, ncol = length(cols), nrow = length(rows), 
                  dimnames = list(NULL, cols))
    currentEnd <- 1
    rowN <- FALSE
    for (i in 1:length(x)) {
        rowInd <- seq(currentEnd, length.out = nrow(x[[i]]))
        ans[rowInd, colnames(x[[i]])] <- x[[i]]
        if (!is.null(rownames(x[[i]]))) {
            if (!rowN) {
                rowN <- TRUE
                rownames(ans) <- 1:nrow(ans)
            }
            rownames(ans)[rowInd] <- rownames(x[[i]])
        }
        currentEnd <- currentEnd + nrow(x[[i]])
    }
    ans
}
```

It contains a very un-R loop but the chance of this being used with huge numbers of matrices, triggering a slowdown, is slim.

Most of the logic is actually concerned with handling row names. This could be alleviated by requiring all or no input to have row names.

How does this approach suit you? I think most time is spend allocating space for the final matrix, and this can just as well be done in R than C++...

**Comment by hadley** [comment]
As is, this isn't really suitable for dplyr since it's only to do with matrices (and dplyr is all about data frames). I'd be willing to accept modifications to `bind_rows()` to add support for matrices.

**Comment by thomasp85** [comment]
My thought was to make a dispatch in bind_rows() to rbindMat in case it was called with matrix input (so rbindMat was not a user visible function)

**Comment by hadley** [comment]
For now, I'd prefer to keep this out of dplyr, but I'll bear in mind if I hear other requests.

**Comment by anhqle** [comment]
@hadley Would you still consider modifications to `bind_rows()` to add support for matrices?

Currently there's still no good option to `rbind` matrices with different column names. Every time I want to do that, I instinctively reach for `bind_rows()` only to be reminded that it doesn't support matrices.
