### ISSUE TITLE
rowwise_df fails when there is some element whose name is the same as some existing function

### ISSUE THREAD

**Issue by yutannihilation** [hadley/dplyr#1491]
In the code below, `mean` of `result$mean` seems to be evaluated as `base::mean()`, not the column of a data.frame passed via pipe. I guess this is a problem related to hybrid evaluation.

```r
iris %>%
  group_by(Species) %>%
  do(result=list(mean = mean(.$Sepal.Length))) %>%
  summarise(Species, mean=result$mean)
#> Error: invalid subscript type 'closure'
```

Here is a simpler example; the element `n` is interpreted as `dplyr::n()`

```r
data_frame(x = replicate(5, list(n= 1), simplify = FALSE)) %>%
  rowwise() %>%
  summarise(s = x$n)
#> Error: invalid subscript type 'closure'
```

These are OK:

```r
# Use quotes
data_frame(x = replicate(5, list(n= 1), simplify = FALSE)) %>%
  rowwise() %>%
  summarise(s = x$"n")

# Use [[]]
data_frame(x = replicate(5, list(n= 1), simplify = FALSE)) %>%
  rowwise() %>%
  summarise(s = x[["n"]])
```

**Comment by romainfrancois** [comment]
This is definitely part of the big rework on hybrid evaluation. Started that in the `hybrid` branch.

**Comment by antoine-lizee** [comment]
Might be related to #1400

**Comment by hadley** [comment]
We're moving away from rowwise, so I think this now is unlikely to happen given how much other stuff we need to get done.
