### ISSUE TITLE
Add index option to compute()

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1499]
It would be great if `collect()` could be accompanied by the creation of indexes for performance.

**Comment by hadley** [comment]
Not sure how that would help - `collect()` bring all the data into R, where there aren't indices.

**Comment by iangow** [comment]
Sorry. I think I should've said `compute()`.

But `collect()` is what I've ended up doing.

I am merging A with B to produce AB, which is bigger than either, then merging with C to produce something smaller. I figure a server-side merge of AB with C assisted by an index would be faster than bringing the data to R. But if I'm using RStudio Server, then it's no big deal for the data I'm working with. (If I were using RStudio with a remote database, then there'd be more of a difference.)

(Of course, if one could slip arbitrary SQL in through the `dplyr`-constructed connections, then one could make indexes "by hand".)

**Comment by hadley** [comment]
Ah yes, there should be an option to do that - it's easy to add.

**Comment by krlmlr** [comment]
Checking that a column is unique is another possible application. Perhaps `compute()` can be taught to create both unique and non-unique indexes. Mind that indexes can include multiple columns.
