### ISSUE TITLE
Allow sending of arbitrary SQL to database

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1500]
It would be great if one could execute arbitrary SQL against a database source. For example, 

```
pg <- src_postgres()
execute(pg, sql("SET work_mem='3GB'"))
```
(Adding working memory can dramatically enhance the performance of PostgreSQL by allowing it to use memory for temporary tables, common table expressions, etc.).

**Comment by hadley** [comment]
I think should just use the existing DBI tools for that.

**Comment by iangow** [comment]
But is there not a way to pass SQL through the connection set up using `pg <- src_postgres()` so that the benefits can flow to one when using the `dplyr` approach? I figure `dplyr` is using DBI behind the scenes, but (as far as I can tell) I would have to switch a workflow entirely to using `RPostgreSQL` (e.g., `dbGetQuery`, `dbWriteTable` rather than `tbl(pg, sql("..."))`) to be able to say `SET work_mem='3GB'` for the benefit of other queries.

**Comment by hadley** [comment]
You can just sneak the connection object out `pg$con` and use it with `dbSendQuery()` etc.

**Comment by iangow** [comment]
Great!

So this probably addresses my other issue (#1499). My apologies if this is already covered by the documentation and I missed it (I guess I could've just read the source code, but I'm an amateur).
