### ISSUE TITLE
Support predicates in *_each()

### ISSUE THREAD

**Issue by yutannihilation** [hadley/dplyr#1501]
purrr's `map_if()` is very useful when we want to apply a function to multiple columns which satisfy some conditions.

Here is a line of code shown in the `summarise_each`'s example:

```r
summarise_each_(iris, funs(max), names(iris)[-5])
```

If I use `map_if()` to do the same manipulation, the code would be something like this:

```r
as.list(iris) %>% map_if(is.numeric, max)
#> $Sepal.Length
#> [1] 7.9
#> 
#> $Sepal.Width
#> [1] 4.4
#> 
#> $Petal.Length
#> [1] 6.9
#> 
#> $Petal.Width
#> [1] 2.5
#> 
#> $Species
#>   [1] setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa     setosa    
#> ...snip...
```

But I feel it would be great if I use predicate function with some version of `summarise_*()` like bellow:

```r
summarise_if(iris, is.numeric, funs(max))
```

Are there any plan to introduce predicates to `summarise_*`/`mutate_*` family?

**Comment by romainfrancois** [comment]
I'd say, this is more a `select` thing, so that we could `select` first based on some predicate, and then use `summarise_each` as is.

**Comment by yutannihilation** [comment]
Thanks for your comment.

Sorry, the example may not be a good case where we need predicates....
I agree with you about `summarise_each()`; when we want to `summarise()`, we can use `select()` since we don't need unselected columns anymore at the end of the function chain.

But, what about `mutate_each()`? I guess we want to preserve unselected columns as is when we try to `mutate()` some column. For example, in order to `round()` all numeric columns, we can do like this with `purrr`:

```r
diamonds %>%
  purrr::map_if(is.numeric, round, digits = 1) %>%
  tbl_df()
#> Source: local data frame [53,940 x 10]
#> 
#>    carat       cut  color clarity depth table price     x     y     z
#>    (dbl)    (fctr) (fctr)  (fctr) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl)
#> 1    0.2     Ideal      E     SI2  61.5    55   326   4.0   4.0   2.4
#> 2    0.2   Premium      E     SI1  59.8    61   326   3.9   3.8   2.3
#> 3    0.2      Good      E     VS1  56.9    65   327   4.0   4.1   2.3
#> 4    0.3   Premium      I     VS2  62.4    58   334   4.2   4.2   2.6
#> 5    0.3      Good      J     SI2  63.3    58   335   4.3   4.3   2.8
#> 6    0.2 Very Good      J    VVS2  62.8    57   336   3.9   4.0   2.5
#> 7    0.2 Very Good      I    VVS1  62.3    57   336   4.0   4.0   2.5
#> 8    0.3 Very Good      H     SI1  61.9    55   337   4.1   4.1   2.5
#> 9    0.2      Fair      E     VS2  65.1    61   337   3.9   3.8   2.5
#> 10   0.2 Very Good      H     VS1  59.4    61   338   4.0   4.0   2.4
#> ..   ...       ...    ...     ...   ...   ...   ...   ...   ...   ...
```

**Comment by hadley** [comment]
It's starting to feel to me that functions like this should belong in purrr.
