### ISSUE TITLE
Support cut for sql databases

### ISSUE THREAD

**Issue by jmh530** [hadley/dplyr#1517]
The ntile function is the primary way in dplyr to create an index of groups based on the values of some series. However, ntile does not support custom break points. 

Base R has a function called cut that provides similar functionality as ntile, but it can have custom break points be passed to it. Within dplyr, this works for local data frames, but it does not work for SQL databases.

I suggest adding support for cut so that you can create indices with custom break points and SQL databases in dplyr.

**Comment by hadley** [comment]
How would you implement cut in SQL?

**Comment by jmh530** [comment]
I'm not sure how to generate an SQL command to do it. I'm also not really sure how dplyr is implemented at a low level. So feel free to close if this is not a reasonable enhancement. 

If I were trying to implement it, I would use percent_rank in dplyr to get a part of the information needed. Then, I would write a C++ function to process the information the same way that R's cut works. I don't know if that's do-able. 

I added this based on <a href="http://stackoverflow.com/questions/21714457/is-cut-style-binning-available-in-dplyr">this</a> stackoverflow question where you comment that they are thinking about adding support for cut-style binning. I figured that if ntile was not available at the time, then it could be that this is what your answer was referring to as on the to-do list.

**Comment by joranE** [comment]
I'm also not terribly well versed in the SQL translation code in dplyr, but my naive assumption is that you'd translate a call to cut() into a CASE statement. For example,

    x <- runif(10)
    cut(x,breaks = c(0,0.3,0.6,1),labels = c("low","mid","high"))

would be turned into

    case
      when x > 0 and x <= 0.3 then 'low'
      when x > 0.3 and x <= 0.6 then 'mid'
      when x > 0.6 and x <= 1 then 'high'
      else null
    end

...but I have no idea how feasible that is to implement.

**Comment by jmh530** [comment]
The breaks can be arbitrarily long, so I figure it would be better to do some kind of loop. I wrote some c++ code, just for one value of x. Then, the function could be applied to a whole array or something. Disclaimer: I didn't test that it actually works. 

#include <vector>
using namespace std;

int cut_i(double x, vector<double>& breaks)
{
	breaks = sort(breaks);
	for(auto i = 0; i != breaks.size(); i++) {
		if (x > breaks[i]) {
			break;
		}
	}
	return i--;
}

**Comment by krlmlr** [comment]
@jmh530: It appears that a SQL translation is really necessary to make it work for SQL backends.

@joranE: One can even implement binary search, this might save the SQL engine some computation effort:

```
case
  when x <= 0.3 then
    case when x <= 0 then NULL
    else 'low'
    end
  when x <= 1 then
    case when x <= 0.6 then 'mid'
    when x <= 1 then 'high'
    else NULL
  end
end
```

I remember a limit for the nesting of `CASE` expressions, at least for T-SQL.

**Comment by voxnonecho** [comment]
@joranE @krlmlr Both methods seem to yield similar results: http://stackoverflow.com/questions/33573077/create-groups-based-on-percent-rank-in-dplyr/

**Comment by jmh530** [comment]
@voxnonecho In the stackoverflow answer, you create a tbl from a raw sql database by using an sql query. Is there any way to use sql queries with tbl's that already exist? 

In my actual application, I do this operation following a number of other dplyr commands. I don't see an obvious way to do it. For instance, the last line of the code below fails: 

    library(dplyr)
    library(RSQLite)

    n <- 100
    set.seed(42)
    df <- data.frame(idx = 1:n, x = rnorm(n))

    my_db <- src_sqlite("my_db.sqlite3", create = T)
    copy_to(my_db, df, "df")
    my_tbl <- tbl(my_db, from="df")
    my_tbl <- my_tbl %>%
    			select(x)

    q1 <- "SELECT x,
        CASE
          WHEN x <= 0.3 THEN
            CASE WHEN x <= 0 THEN NULL
            ELSE 1
            END
          ELSE
            CASE WHEN x <= 0.6 THEN 2
            WHEN x <= 1 THEN 3
            ELSE NULL
          END
        END
        FROM df"

    krlmlr <- tbl(my_tbl, sql(q1))

My sense is that if I can't get this to work, then I have two options: 1) convert all the dplyr steps required to get this variable into raw sql (I can get them from show_query), 2) convert to data frame and use the cut function (which is basically what the other answer does).

**Comment by hadley** [comment]
Given that there isn't a natural analog to `cut()` in SQL, this is beyond the scope of dplyr.
