### ISSUE TITLE
Using mutate is slower than bind_cols

### ISSUE THREAD

**Issue by ljos** [hadley/dplyr#1520]
I am not sure this is an issue as mutate might have to do more than bind_cols and therefore will be slower, but naively it seems to me that they should not be so far apart as they are basically doing the same thing.

```R
library(microbenchmark)
library(nycflights13)
library(dplyr)
tails <- select(flights, tailnum)

microbenchmark(
  mutate(tails, ind = row_number()), 
  bind_cols(tails, data.frame(ind = 1:nrow(tails)))
)
```

```
                                              expr     min       lq     mean   median       uq      max neval
                 mutate(tails, ind = row_number()) 609.273 1067.378 1788.613 1748.354 1821.378 73323.87 10000
 bind_cols(tails, data.frame(ind = 1:nrow(tails))) 409.534  681.706 1043.150 1005.199 1079.717 10024.25 10000
```

R version:
x86_64, darwin15.0.0
R version 3.2.2 (2015-08-14)
Fire Safety
(Built with openblas)

dplyr version:
0.4.3.9000
(Installed with devtools::install_github() on 2015.11.08)

**Comment by hadley** [comment]
It's a small difference and they're doing relatively different things
