### ISSUE TITLE
bind_rows() fails on empty named list

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1522]
```R
bind_rows(setNames(list(), character()), id = "name")
```

**Comment by romainfrancois** [comment]
Hmm I though this had been fixed. Perhaps I did not take care of the code path that used id=

**Comment by hadley** [comment]
I think it's a bug in my `has_names()` function - should be `||` not `&&`

**Comment by romainfrancois** [comment]
Well it works with .id="name"

**Comment by romainfrancois** [comment]
Closing this as it just looks like user typo using `id` instead of `.id`.
