### ISSUE TITLE
base::getElement fails on tibbles

### ISSUE THREAD

**Issue by mplourde** [hadley/dplyr#1523]
```{r}
library(dplyr)
data.frame(a=1:10) %>% getElement('a')
#  [1]  1  2  3  4  5  6  7  8  9 10
data_frame(a=1:10) %>% getElement('a')
# Error during wrapup: unused argument (exact = TRUE)
```

**magrittr** provides `extract2`, which can be used in place `getElement`, however, **magrittr**'s naming is in general at odds with the **dplyr**/**tidyr** framework, since `magrittr::extract` conflicts with `tidyr::extract`.

**Comment by romainfrancois** [comment]
We just need to add the exact argument to [[.tbl_df, i.e. 

function(x, i, exact){
  # same code as we have because we always use exact matching for tbl_df
}

**Comment by hadley** [comment]
Moved to tibble.
