### ISSUE TITLE
[[ method for tbl_df doesn't work with i, j

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1525]
I use this a lot when inspecting list-columns.

``` r
suppressPackageStartupMessages(library(dplyr))
x <- data_frame(a = 1:3, b = lapply(a, seq_len))
x[[3, 2]]
#> Error in `[[.tbl_df`(x, 3, 2): unused argument (2)
```

It works if I install from the commit just prior to https://github.com/hadley/dplyr/commit/d5c1a63215c38a1ed67b7ddb3e081dd4bfcbaa57.

**Comment by hadley** [comment]
Bummer, I didn't think anyone used that :(

**Comment by jennybc** [comment]
All these list-columns have driven me to it :)

**Comment by hadley** [comment]
Can you please refile in tibble?
