### ISSUE TITLE
Consider adding a ``drop'' rows operation 

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1527]
I know that ``filter`` can easily achieve this, but it is error prone when there are ``NA`` values.

Dropping using ``filter(!condition)`` drops ``NA``s but ``drop(condition)`` would keep them.

Hope this helps.

**Comment by krlmlr** [comment]
Something like `drop()` has been discussed in #741. You could write a tiny helper that achieves this effect.

**Comment by hadley** [comment]
Duplicate of #741
