### ISSUE TITLE
Convert list with unequal vectors by as_data_frame

### ISSUE THREAD

**Issue by zhilongjia** [hadley/dplyr#1528]
Writing a list with unequal vectors into a file is a common task and can not be implemented simply so far as I knew (See example below). One of solutions is `sapply(aa, "length<-", max(lengths(aa)))` (See reference 1 below), but not as sim
The `dplyr::as_data_frame` only supports the input of list with equal vectors. It will be convenient if it can be done by `dplyr::as_data_frame`. This is an enhancement. Thank you.

Example:

    aa <- list(A=c(1, 3, 4), B=c(3,5,7,7,8))
  
Result wanted:

    A B
    1 3
    3 5
    4 7
    NA 7
    NA 8

 reference: 
1. http://stackoverflow.com/questions/33613337/the-simplest-way-to-convert-a-list-with-various-length-vectors-to-a-data-frame-i/33622855#33622855

**Comment by hadley** [comment]
The goal of `as_data_frame()` is to be convert things that are already basically data frames to data frames. Unequal lengths is out of scope.
