### ISSUE TITLE
Warning message: "package ‘dplyr’ was built under R version 3.2.2"

### ISSUE THREAD

**Issue by mbkranz** [hadley/dplyr#1530]
Hi,

I just wanted to make sure that using dplyr in 3.2.1 would not cause any major problems. If it does, then how would I go about upgrading to R 3.2.2 given that I do not have the option to upgrade my Mac operating system past 10.7.

Best,
Mike

**Comment by hadley** [comment]
You'll need to verify for yourself. Unfortunately I don't have the resources to test with previous version of R
