### ISSUE TITLE
head.tbl_sql doesn't respect existing limit

### ISSUE THREAD

**Issue by jarodmeng** [hadley/dplyr#1531]
I attempted to implement simple `sample_n` (without replacement or weighting) for SQL backends by using `RAND`, `ORDER BY` and `LIMIT`. However, I discovered that `head.tbl_sql` doesn't work on the sampled table because the `LIMIT` created by `sample_n` is overwritten by `head` (by [this line](https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/tbl-sql.r#L160) of code). Perhaps we can use the min of the existing limit in the query and the computed limit.

```r
build_query(x, min(x$query$limit, limit))$fetch()
```

**Comment by jarodmeng** [comment]
Actually I realized after writing the issue report that `LIMIT` information is not stored in the query object. It's consumed on the fly by `sql()` in `build_query`. This means that there's no easy way of getting the current `LIMIT` of a query, if any.

**Comment by krlmlr** [comment]
Another side effect: head.tbl_sql() returns a data.frame, not a tbl_df. Is there a reason why the "LIMIT" setting is not part of the "tbl_sql" object?

**Comment by hadley** [comment]
In general, I don't think you should think of LIMIT as a tool you use for generating queries - it's only really useful for limiting what the database returns to you.
