### ISSUE TITLE
Optional parameter to control length of summarise

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#154]
It would be useful to have a parameter that states the number of values the function should return. It's sometimes useful to have a summary function that returns multiple values, like if you're computing a fixed set of quantiles. The values should run down the column, and the grouping variables should be repeated.

For example:

``` R
summarise(group_by(mtcars, cyl), mpg = quantile(mpg), .n = 5)
```

We don't need to label the values, since the user could always do that themselves:

``` R
qs <- c(0, 0.5, 1)
summarise(group_by(mtcars, cyl), mpg = quantile(mpg, qs), q = qs, .n = 3)
```

When `n > 1`, `summarise()` shouldn't drop the last group from the grouping, since you might want to summarise the values you just computed.

**Comment by brianstamper** [comment]
I came across this problem today, and found to get the effect of "flatten" described above I could use the composition of t() and as.data.frame():

```R
library("dplyr")
df <- data.frame(foo = rep(c("a", "b", "c"), 4), bar = 1:12)
```
```
> df
   foo bar
1    a   1
2    b   2
3    c   3
4    a   4
5    b   5
6    c   6
7    a   7
8    b   8
9    c   9
10   a  10
11   b  11
12   c  12
```
```R
df.q <- df %>%
  group_by(foo) %>%
  summarise(quantiles = list(quantile(bar)))
q <- t(as.data.frame(df.q$quantiles))
row.names(q) <- NULL
df.q <- cbind(df.q, q)
df.q$quantiles <- NULL
```
```
> df.q
  foo 0%  25% 50%  75% 100%
1   a  1 3.25 5.5 7.75   10
2   b  2 4.25 6.5 8.75   11
3   c  3 5.25 7.5 9.75   12
```

**Comment by petersmp** [comment]
I am not sure that  a separate row per output is the best approach here. Following from @brianstamper , I occasionally find myself doing things like this:


```
df %>%
  group_by(foo) %>%
  summarise_(.dots = setNames(paste0("summary(bar)[",1:6,"]"), names(summary(1:5))))
```

To get outputs like this:

```
# A tibble: 3 × 7
     foo  `Min. bar` `1st Qu. bar` `Median bar`  `Mean bar` `3rd Qu. bar`  `Max. bar`
  <fctr> <S3: table>   <S3: table>  <S3: table> <S3: table>   <S3: table> <S3: table>
1      a           1          3.25          5.5         5.5          7.75          10
2      b           2          4.25          6.5         6.5          8.75          11
3      c           3          5.25          7.5         7.5          9.75          12
```

I have found workarounds like this often (this is actually perhaps the cleanest I have found), but they never seem quite satisfying. It would be nice if I could use something like `summarise` directly, particularly when I want to also calculate other summaries (e.g., the mean of some other variable). Perhaps `summarise_` is the right approach, but there may be value in making this more straightforward.

**Comment by hadley** [comment]
Now part of #2326
