### ISSUE TITLE
Requiring correctly classed NA is unpleasent

### ISSUE THREAD

**Issue by ringprince** [hadley/dplyr#1542]
[ This is a version of http://stackoverflow.com/questions/33783501/summarise-each-from-dplyr-gives-error-on-characters ]

I am seeing an error when using
`dplyr::summarise_each` to summarise character
vectors in a data.frame.

For a simple example, consider this sample data.frame

    tmp <- data.frame(A=c("a", "b", "b", "c", "c", "d", "d"),
    		  B=c("u", "v", "v",  NA,  NA, "x", "y"),
    		  stringsAsFactors = FALSE)
    tmp

    | A | B   |
    |---+-----|
    | a | u   |
    | b | v   |
    | b | v   |
    | c | nil |
    | c | nil |
    | d | x   |

Now, I want to group this data.frame by "A" and run this little
function on the remaining column:

    uniqueorna <- function(x) {
      if (length(unique(x)) == 1) {
        unique(x)[1]
      } else {
        NA
      }
    }

Using `dplyr::summarise_each` works fine on the
first rows:

    library("dplyr")
    tmp[1:6,] %>% group_by(A) %>% summarise_each(funs(uniqueorna(.)))

    | A | B   |
    |---+-----|
    | a | u   |
    | b | v   |
    | c | nil |
    | d | x   |

But it fails on the full data.frame

    tmp[1:7,] %>% group_by(A) %>% summarise_each(funs(uniqueorna(.)))

    Error: expecting a string

As was suggested in the comments, returning `NA_character_` rather than just `NA` works.  But that requires me to return different NAs conditional on the class of the column.  Is there a(nother) way around this?

**Comment by hadley** [comment]
`x[NA]` should give you a correctly classed NA
