### ISSUE TITLE
row_number() ordered by multiple columns

### ISSUE THREAD

**Issue by mtreadwell** [hadley/dplyr#1543]
I am looking to filter on a row number whose order is determined by two columns instead of just one:
```R
pg <- src_postgres()
dat <- tbl(pg, 'table')

rows <- dat %>%
  group_by(dimension) %>%
  filter(row_number(date1, date2) == 1)
```
This way produces the error:
`Error in row_number(date1, date2) : unused argument (date2)`

I could accomplish the above without error by reworking the problem as seen below but that seems like overkill, especially if I need to order by 3+ columns. Is there some functionality to row_number that I am missing that would make this less verbose?

```R
rows <- dat %>%
  group_by(dimension, date1) %>%
  filter(row_number(date2) == 1) %>%
  group_by(dimension) %>%
  filter(row_number(date1 == 1)
```

**Comment by hadley** [comment]
I think you could do `ROW_NUMBER()` so dplyr doesn't try and translate, and instead just spits out the SQL.

Otherwise, I don't currently have the resources to support ranking on multiple variables.

**Comment by krlmlr** [comment]
This should be easier with vctrs and straightforward in dbplyr, can we revisit?
