### ISSUE TITLE
dplyr::union weird error message

### ISSUE THREAD

**Issue by achekroud** [hadley/dplyr#1544]
Hi team,

I'm trying to use the dplyr::union function, which I understand is the same as rbind (but I am hoping that it matches colnames). 

Anyway, I just got the following error message:
Error: cannot join on columns 'CIGEVER' x 'CIGEVER': Can't join on 'CIGEVER' x 'CIGEVER' because of incompatible types (numeric / numeric) 

Not sure what I did wrong (indeed, the error message is also confusing bc the types are clearly the same...)

Any ideas? Data set is pretty large so not sure how I could paste reproducible example. Error happened again after restarting session (latest R version, running Rstudio server, packages up to date as far as I can see)...

Thanks
Adam

**Comment by hadley** [comment]
It's not the same as `rbind()`. You want `bind_rows()`. If that doesn't work, please supply a minimal reproducible example - probably just taking the first row from each df will work.
