### ISSUE TITLE
Group_By + Mutate with NA misses groups

### ISSUE THREAD

**Issue by acjackman** [hadley/dplyr#1545]
I seem to be having a similar issue. I think that it seems to be the NA values that cause the problem. I've also had a problem with summarize in addition to mutate. They seem to run the functions twice for some groups and miss others completely.

A sample from a real life data set is included (
[na_trbl.txt](https://github.com/hadley/dplyr/files/39758/na_trbl.txt)
):

    dta <- read.csv("na_trbl.csv")
    dta
       cid nc
    1    1 NA
    2    1 NA
    3    1 NA
    4    2 NA
    5    2 NA
    6    3 24
    7    3 24
    8    3 NA
    9    3 NA
    10   4 15
    11   4 26
    12   4 15
    13   5 28
    14   5 22
    15   5 40
    16   6 NA

I created a function that prints each time it is run to see how the group_by was affecting mutate.

    trbl <- function(value,print){
        cat(print, " - ", value, "\n")
        value
    }

Running the following code provides some interesting results.

    trbl_mutate <-
        dta %>%
        filter(cid != 1) %>%
        dplyr::group_by(cid) %>%
        dplyr::mutate(
            mutatevar = trbl(nc, cid)
        )

The `trbl` function prints this to the console:

    1 1 1  -  NA NA NA 
    1 1 1  -  NA NA NA 
    2 2  -  NA NA 
    3 3 3 3  -  24 24 NA NA 
    5 5 5  -  28 22 40 
    6  -  NA 

Notice that the group `1` is duplicated, while `4` isn't printed at all.

Looking at the results, we see that the variable `mutatevar`  for group `4` has `NA` values where it should have just copped the values across.

    R> trbl_mutate
    Source: local data frame [16 x 3]
    Groups: cid [6]
         cid    nc mutatevar
       (int) (int)     (int)
    1      1    NA        NA
    2      1    NA        NA
    3      1    NA        NA
    4      2    NA        NA
    5      2    NA        NA
    6      3    24        24
    7      3    24        24
    8      3    NA        NA
    9      3    NA        NA
    10     4    15        NA
    11     4    26        NA
    12     4    15        NA
    13     5    28        28
    14     5    22        22
    15     5    40        40
    16     6    NA        NA

It might be helpful to know that the summarise function also has the group duplication issue. A reproducible example:

    trbl_summarise <- 
        dta %>%
        dplyr::group_by(cid) %>%
        dplyr::summarise(
            summarisevar = mean(trbl(nc, cid), na.rm=TRUE)
        )

The `trbl` function prints:

    1 1 1  -  NA NA NA 
    2 2  -  NA NA 
    3 3 3 3  -  24 24 NA NA 
    3 3 3 3  -  24 24 NA NA 
    4 4 4  -  15 26 15 
    5 5 5  -  28 22 40 
    6  -  NA 

While the output of the computation

    R> trbl_summarise
    Source: local data frame [6 x 2]
        cid sumarisevar
      (int)       (dbl)
    1     1          NA
    2     2          NA
    3     3    24.00000
    4     4    18.66667
    5     5    30.00000
    6     6         NaN

Any help or explanation if this functionality is expected would be greatly appreciated!

**Comment by dgrtwo** [comment]
I believe this behavior is now fixed on the dev version. I suspect it's from the addition of [this line](https://github.com/hadley/dplyr/commit/8691bce9370d81900c95148f5f78fce763225d2e#diff-3e9f2fe3fe00f9343478a1d105eadf0bR32) in 8691bce9370d81900c95148f5f78fce763225d2e.
