### ISSUE TITLE
Rename variables with special characters

### ISSUE THREAD

**Issue by aaronxf** [hadley/dplyr#1547]
Dear Dr. Wickham, 

I am trying to replace all plyr function calls with dplyr ones in my legacy code. One  scenario that cannot be translated directly or addressed elegantly is when the renamed variable names contain special characters such as '%', '$', ' ', etc as dplyr::rename requires "Arguments to rename must be unquoted variable names." 

Is there a good way to translate function calls such as 

DF %>% plyr::rename( c("Currency 1" = "Currency #1", "M30Y+"="30Y+"))

within dplyr? Or do you plan to add support for quoted variable names? I am sorry if I have missed such feature in your packages. 

Thank you,

**Comment by krlmlr** [comment]
Does any of the following work for you:

```
DF %>% plyr::rename_( "Currency 1" = "Currency #1", "M30Y+"="30Y+")
DF %>% plyr::rename( "Currency 1" = `Currency #1`, "M30Y+"=`30Y+`)
```
