### ISSUE TITLE
dplyr frame_data errors with “Columns are not all same length”

### ISSUE THREAD

**Issue by drolejoel** [hadley/dplyr#1552]
as per http://stackoverflow.com/questions/33929112/dplyr-frame-data-errors-with-columns-are-not-all-same-length

When I copy and paste the example from the Help page, this works OK:
   
    dplyr::frame_data( 
       ~Club, ~Compensation,
       "a",   1,
       "b",   2
    )

Yet when I try to input my own data I get the error "Columns are not all same length".

    dplyr::frame_data( 
       ~Club, ~Compensation,
       "a",   1,
       "b",   2
    )

Here's another example with 2 rows of data:

    soccer <- dplyr::frame_data( 
       ~A,   ~B,    ~C,        ~D,   ~E,    ~E2,
       "NY", "ABc", "Anatole", "BB", 50000, 50000,
       "NY", "CDe", "Saad",    "D",  60000, 73750
    )

**Comment by sumprain** [comment]
try downloading the latest branch from github and the bug is solved.
