### ISSUE TITLE
Sorting broken with arrange and group_by

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1553]
For some reason, I cannot get `arrange`  to work properly with a particular data set I am working with. It seems that `desc(quarter)` works, but `desc(year)` does not. Below is code that reproduces this issue (using current GitHub version of `dplyr` and an older version from CRAN):

```
library(dplyr) 

# Make some fake data
df <- tbl_df(expand.grid(1990:2000L, 1:4L, 1:50L))
names(df) <- c("year", "quarter", "id")
df$value <- rnorm(n=dim(df)[1])

# This works
df %>% arrange(desc(year), desc(quarter))

# But group_by breaks it
df_summ <- df %>%
    group_by(year, quarter) %>%
    summarize(average=mean(value)) 

df_summ %>%
    arrange(desc(year), quarter)

df_summ %>%
    arrange(desc(year), desc(quarter))

df_summ %>%
    arrange(desc(quarter), desc(year))

df_summ %>%
    arrange(year, quarter)
```

**Comment by bbTomas** [comment]
After group_by(), you have to do ungroup(). Unless, arrange() is performed in each group separately.

```{r}
df_summ <- df %>%
    group_by(year, quarter) %>%
    summarize(average=mean(value)) %>%
    ungroup()
```

**Comment by iangow** [comment]
I see. I guess this driven by the desire to support behaviour such as *implicit* unpeeling of `group_by`, one layer at a time, etc. Coming at this from SQL, that the equivalent of `GROUP BY year, quarter` gives different results from  `GROUP BY quarter, year` is novel.

To my mind the insertion of `ORDER BY "year"` in the second query (`df_summ_sorted`) is unexpected. Would it not make more sense to override this behavior if a `group_by` variable is explicitly passed to `arrange`? Comparing the first (`df_summ`) and second queries, there's evidently already some processing going on in the SQL relative to the `group_by` clause when `arrange` is used.

```
> library(dplyr) 
> 
> # Make some fake data
> df_r <- tbl_df(expand.grid(1990:2000L, 1:4L, 1:50L))
> names(df_r) <- c("year", "quarter", "id")
> df_r$value <- rnorm(n=dim(df_r)[1])
> 
> pg <- src_postgres()
> 
> df <- copy_to(pg, df_r)
Error: Table df_r already exists.
> 
> # This works
> df_sorted <- df %>% arrange(desc(year), desc(quarter))
> 
> df_summ <- df %>%
+     group_by(year, quarter) %>%
+     summarize(average=mean(value)) 
> 
> df_summ_sorted <- 
+     df_summ %>%
+     arrange(desc(year), quarter)
> 
> df_summ_sorted_2 <- 
+     df_summ %>%
+     ungroup() %>%
+     arrange(desc(year), quarter)
> 
> show_query(df_summ)
<SQL>
SELECT "year", "quarter", "average"
FROM (SELECT "year", "quarter", AVG("value") AS "average"
FROM "df_r"
GROUP BY "year", "quarter") AS "zzz8"
> show_query(df_summ_sorted)
<SQL>
SELECT "year", "quarter", "average"
FROM (SELECT "year", "quarter", AVG("value") AS "average"
FROM "df_r"
GROUP BY "year", "quarter") AS "zzz8"
ORDER BY "year", "year" DESC, "quarter"
> show_query(df_summ_sorted_2)
<SQL>
SELECT "year", "quarter", "average"
FROM (SELECT "year", "quarter", AVG("value") AS "average"
FROM "df_r"
GROUP BY "year", "quarter") AS "zzz8"
ORDER BY "year" DESC, "quarter"
```

**Comment by hadley** [comment]
Yes, I'll probably be changing the behaviour of `arrange()` back to ignoring grouping in the next version.
