### ISSUE TITLE
add_rownames enhancement

### ISSUE THREAD

**Issue by zhilongjia** [hadley/dplyr#1564]
Currently, `add_rownames` add rownames as an explicit variable (default rowname). Can `add_rownames` or another function in dplyr add rownames for data.frame or tbl if there is a column named `rowname` or by assigning a column? This is a reverse operation of the current `add_rownames`. And actually `add_rownames` means add rownames for its literal meaning. Though `dplyr` wants no rowname for `data.frame`, it's necessary in many cases especially interacting with other packages in R. Usually I have to add the rowname, and delete the rowname column. It's related with #884. Thank you.

**Comment by hadley** [comment]
Moved to tibble.
