### ISSUE TITLE
failwith incompatible with piping

### ISSUE THREAD

**Issue by mplourde** [hadley/dplyr#1566]
`failwith` leads to an error when applied using `%>%`.

```r
library(dplyr)
packageVersion('dplyr')
# [1] '0.4.3.9000'

myfun <- function(x) x

myfun_safe <- failwith(myfun, default=NA)
myfun_safe2 <- myfun %>% failwith(default=NA)

myfun_safe(1)
# [1] 1
myfun_safe2(1)
# Error in try(out <- f(...), silent = quiet) : could not find function "f"
# [1] NA
```

**Comment by krlmlr** [comment]
I think there's nothing dplyr (or magrittr, which implements this operator) can do about it. The call to myfun() already has happened before failwith is even reached.

**Comment by kevinushey** [comment]
Are you sure? The issue here is that the wrong `f` is resolved:

```
library(dplyr)
fn <- function(x) x
f <- function(...) print("Ouch!")
call <- fn %>% failwith(default = NA)
call(1)
[1] "Ouch!"
```

**Comment by kevinushey** [comment]
I think the `f` function needs to be forced in the `failwith` definition; otherwise it will later be resolved in the wrong context:

```
> failwith
function (default = NULL, f, quiet = FALSE)
{
    function(...) {
        out <- default
        try(out <- f(...), silent = quiet)
        out
    }
}
<environment: namespace:dplyr>
```

E.g. this works:

```
failwith <- function(default = NULL, f, quiet = FALSE) {
    force(f)
    function(...) {
        out <- default
        try(out <- f(...), silent = quiet)
        out
    }
}
```
cc: @hadley

**Comment by krlmlr** [comment]
FGITW problem here. Sorry.

It seems to work with the "simplified" branch of magrittr, though, because the evaluation logic is different there: https://github.com/smbache/magrittr/tree/simplified.

**Comment by jennybc** [comment]
The `possibly()` function from `purrr` works with piping:

``` r
library(purrr)
myfun_safe3 <- myfun %>% possibly(otherwise = NA)
myfun_safe3(1)
#> [1] 1
```
