### ISSUE TITLE
problem when anti_join()ing with a factor

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1571]
`anti_join()` isn't working right when `by` is a factor. The wrong rows are being retained and, despite what the warning says, the factor-ness of the `by` variable persists. I discovered this in a much larger example and the results, while always wrong, are not deterministic.

``` r
library(dplyr)
(big <- data.frame(letter = rep(c('a', 'b'), each = 2),
                   number = 1:2))
#>   letter number
#> 1      a      1
#> 2      a      2
#> 3      b      1
#> 4      b      2
(small <- data.frame(letter = 'b'))
#>   letter
#> 1      b
(aj_result <- big %>%
  anti_join(small))
#> Joining by: "letter"
#> Warning in anti_join_impl(x, y, by$x, by$y): joining factors with different
#> levels, coercing to character vector
#>   letter number
#> 1      b      2
#> 2      b      1
#> 3      a      1
str(aj_result)
#> 'data.frame':    3 obs. of  2 variables:
#>  $ letter: Factor w/ 2 levels "a","b": 2 2 1
#>  $ number: int  2 1 1
```

I'm running the current development version.

**Comment by coolbutuseless** [comment]
Confirming that I see this behaviour as well.  
If you force "stringsAsFactors=FALSE" the error disappears.  (Not that that's the solution - just confirming that it's a factors thing)

**Comment by hadley** [comment]
@romainfrancois can you take a look please?

**Comment by romainfrancois** [comment]
Pretty sure the underlying issue has been fixed while tackling #1712

**Comment by romainfrancois** [comment]
@hadley @jennybc let me know what you think, but I kept the column letter as a factor because my understanding of `anti_join(x,y)` is that it produces a subset of `x`. 

I eliminated the warning though. 

```
> big <- data.frame(letter = rep(c('a', 'b'), each = 2), number = 1:2)
> small <- data.frame(letter = 'b')
>
> anti_join(big, small) %>% str
Joining by: "letter"
'data.frame':	2 obs. of  2 variables:
 $ letter: Factor w/ 2 levels "a","b": 1 1
 $ number: int  1 2
```

Also I wanted to test the absence of that warning, but I can't use `expect_silent` because of the "Joining by" message. Is there a way to test for "this does not produce a warning".

**Comment by jennybc** [comment]
It seems fixed for me 🙂 and I certainly like that `letter` is still a factor! But it does feel inconsistent with the other joins, which always take unequal factor levels as excuse to convert character to factor.

**Comment by hadley** [comment]
@jennybc `semi_join()` and `anti_join()` are more like `filter()` than `mutate()` so here I think it makes sense to preserve the original types.

@romainfrancois two options: `expect_warning(..., NA)` or use `by = "letter"` to suppress the message

**Comment by romainfrancois** [comment]
Thanks, and sorry I missed what was right there in the documentation of `expect_warning`. 
Would it be overkill to have: 

```r
expect_no_warning <- function( object, ...) expect_warning( object, NA, ...)
```

for expressiveness

**Comment by hadley** [comment]
@romainfrancois I think I decided against that because asserting that warnings are "missing" seemed relatively clear for me (and starts to get a bit grammatically complicated because I think it would need to be `expect_no_warnings()`)

**Comment by krlmlr** [comment]
The test `left_join handles mix of encodings in column names (#1571)` fails on my system (Ubuntu 15.10, 3074cf7bfa41c690e).

Perhaps related: https://github.com/hadley/dplyr/issues/1507#issuecomment-217857642
