### ISSUE TITLE
non overwriting update set where

### ISSUE THREAD

**Issue by ggrothendieck** [hadley/dplyr#1573]
In this SO post: 

http://stackoverflow.com/questions/34096162/dplyr-mutate-replace-on-a-subset-of-rows/34096575

it is pointed out that there is no good way to `mutate` on a subset of rows.  In SQL it would be done with something like `update mytable set a = 1, b = 2 where c > 0`  and a, b, c are columns in  mytable.  For dplyr a non-overwriting version would be needed to maintain the functional flavor.

One answer at that link proposes %<>% from magrittr but this is overwriting and not really consistent with the functional nature of dplyr.  

In an answer at the same link, I had posted code and a test run for `mutate_cond` (data frames only) which is like `mutate` but also adds a condition such that the mutate only operates on rows satisfying that condition.

I had also posted there code and a test run for `mutate_last` (data frames only) which is used within `group_by` and is like `mutate` except it only acts on the last group (whereas ordinary `mutate` acts on every group).  Since TRUE > FALSE if we group by a condition it only acts on rows satisfying that condition.   

Yet another another possibility would be to allow `mutate` to specify which group or groups are to be acted on or to have a variation of `mutate` that does this.   Alternately `group_by` could specify which groups are to be acted upon or a `filter`-like command could restrict subsequent commands until it was cancelled.

Something along the above lines would be nice to add to dplyr and would make dplyr more expressive in such cases.

**Comment by jennybc** [comment]
This is connected to an existing long thread "Vectorised switch()": https://github.com/hadley/dplyr/issues/631.
