### ISSUE TITLE
Reusing variables in summarize fails for data.tables

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1574]
To reproduce:

```{r}
library(dplyr)
library(data.table)

# This works as expected
data.frame(x = 1:6, grp = gl(2, 3)) %>% 
  group_by_(~ grp) %>% 
  summarize_(minX = ~ min(x), minXPlus1 = ~ minX + 1)

# Changing to a data.table causes an error
data.table(x = 1:6, grp = gl(2, 3)) %>% 
  group_by_(~ grp) %>% 
  summarize_(minX = ~ min(x), minXPlus1 = ~ minX + 1)
## Error in `[.data.table`(`_dt`, , list(minX = min(x), minXPlus1 = minX +  : 
##   object 'minX' not found
```

----

This was tested using CRAN `dplyr`; today's devel version gives me the error:

```{r}
## Error in .Call("dplyr_resolve_vars", PACKAGE = "dplyr", new_groups, names) : 
##   "dplyr_resolve_vars" not available for .Call() for package "dplyr"
```
in both the data.frame and data.table cases.

Possibly related to https://github.com/hadley/dplyr/issues/883

**Comment by richierocks** [comment]
Presumably caused by this `data.table` issue https://github.com/Rdatatable/data.table/issues/659, though I don't know if you want to work around it on a `dplyr` level.

**Comment by krlmlr** [comment]
I'm seeing this in 4f2d7f8959f88; however, with the `minX` error. Not sure how to work around it, though.
