### ISSUE TITLE
NA's introduced during mutate when the grouping_by variable's smallest value causes an NA

### ISSUE THREAD

**Issue by gforge** [hadley/dplyr#1575]
It seems that group_by introduces NA's together with mutate if the first mutate gives an NA. Although similar in nature to the #1545 and the #1556 issues - I think this is unrelated. Se below examples:

```
test_df <- structure(list(StudyID = c(10L, 1L, 2L, 31L,
                                      11L, 9L),
                          Side = c("left", "unspecified", "left",
                                   "left", "right", "right")),
                     .Names = c("StudyID",
                                "Side"),
                     class = "data.frame",
                     row.names = c(NA, -6L)) 

test_df %<>%
  mutate(
    B4_group =  tolower(Side) %>%
      gsub(".*(right|left).*", "\\1", .) %>%
      factor(levels = c("right", "left"))) %>% 
  group_by(StudyID) %>%
  mutate(
    After_group =  tolower(Side) %>%
      gsub(".*(right|left).*", "\\1", .) %>%
      factor(levels = c("right", "left")))

knitr::kable(test_df)
```

Gives:

| StudyID|Side        |B4_group |After_group |
|-------:|:-----------|:--------|:-----------|
|      10|left        |left     |left        |
|       1|unspecified |NA       |NA          |
|       2|left        |left     |left        |
|      31|left        |left     |left        |
|      11|right       |right    |right       |
|       9|right       |right    |NA          |

This behavior disappears when the StudyID for the missing group is no longer the smallest:

```
test_df <- structure(list(StudyID = c(0L, 1L, 2L, 31L,
                                      11L, 5L),
                          Side = c("left", "unspecified", "left",
                                   "left", "right", "right")),
                     .Names = c("StudyID",
                                "Side"),
                     class = "data.frame",
                     row.names = c(NA, -6L)) 

test_df %<>%
  mutate(
    B4_group =  tolower(Side) %>%
      gsub(".*(right|left).*", "\\1", .) %>%
      factor(levels = c("right", "left"))) %>% 
  group_by(StudyID) %>%
  mutate(
    After_group =  tolower(Side) %>%
      gsub(".*(right|left).*", "\\1", .) %>%
      factor(levels = c("right", "left")))

knitr::kable(test_df)
```

| StudyID|Side        |B4_group |After_group |
|-------:|:-----------|:--------|:-----------|
|       0|left        |left     |left        |
|       1|unspecified |NA       |NA          |
|       2|left        |left     |left        |
|      31|left        |left     |left        |
|      11|right       |right    |right       |
|       5|right       |right    |right       |

I'm using dplyr 0.4.3 on Linux (Ubuntu), R 3.2.2

**Comment by krlmlr** [comment]
I can replicate this in 4f2d7f8959f88. The first script also gives the following warnings when printing the data frame:

```
Warning messages:
1: In format.data.frame(df, justify = "left") :
  corrupt data frame: columns will be truncated or padded with NAs
2: In format.data.frame(df[, !too_wide, drop = FALSE]) :
  corrupt data frame: columns will be truncated or padded with NAs
```

**Comment by hadley** [comment]
Fixed now.
