### ISSUE TITLE
filter() errors when header has empty cell, common with data exported with write.csv

### ISSUE THREAD

**Issue by steventsimpson** [hadley/dplyr#1576]
I have same problem as this StackO post: http://stackoverflow.com/questions/31385976/error-attempt-to-use-zero-length-variable-name.  The first response by *hackR* gave me the clue to look at how `read_csv` and `filter` are related. It appears that filter errors when data that includes rownames without header is read in after `read_csv`; a column of rownames without headers commonly occurs with csv created using `write.csv`. Thus, `readr` reads that column in without a header, and then `filter` errors on the empty header cell while search for the column name to subset by.

In such cases, using read_csv(...) [-1] or read.csv() will get rid of the problem. But maybe there's a filter solution that takes these into account. I've posted this same response at the StackO link.

```r
# write_csv to read_csv or read.csv
# both work fine with filter
mtcars %>% readr::write_csv("~/Desktop/test.csv")
test_r <-  readr::read_csv("~/Desktop/test.csv") %>% filter(hp>100)
test.r <-  read.csv("~/Desktop/test.csv") %>% filter(hp>100)

# write.csv introduces a column of rownames w/o a header
# and read_csv doesnot add a header but read.csv imputes an X
# thus when filter works on read.csv imports, it has all headers with filled cells
# but filter after read_csv has an empty header cell
mtcars %>% write.csv("~/Desktop/test1.csv")
test1_r <- readr::read_csv("~/Desktop/test1.csv") 
test1_r %>% str() 
test1_r %>% filter(hp>100)

test1.r <- read.csv("~/Desktop/test1.csv")
test1.r %>% str() 
test1.r%>% filter(hp>100)


#error occurs at
#> test1_r %>% filter(hp>100)
Error in filter_impl(.data, dots) : 
  attempt to use zero-length variable name
 ```

**Comment by hadley** [comment]
Can you please provide a minimal reprex using a small made up data frame?

**Comment by steventsimpson** [comment]
The code above was a reprex, excepting I forgot to add library call to `dplyr`. My bad. I've improved typesetting to hopefully make its reprex nature more apparent.


```
library(dplyr)

# write_csv to read_csv or read.csv
# both work fine with filter
mtcars %>% 
       readr::write_csv("~/Desktop/test.csv")

test_r <-  readr::read_csv("~/Desktop/test.csv") %>% 
                    filter(hp>100)
test.r <-  read.csv("~/Desktop/test.csv") %>% 
                    filter(hp>100)

# write.csv introduces a column of rownames w/o a header
# and read_csv doesnot add a header but read.csv imputes an X
# thus when filter works on read.csv imports, it has all headers with filled cells
# but filter after read_csv has an empty header cell
mtcars %>% 
           write.csv("~/Desktop/test1.csv")

test1_r <- readr::read_csv("~/Desktop/test1.csv") 
test1_r %>% str() 
test1_r %>% 
           filter(hp>100)     # error occurs here

test1.r <- read.csv("~/Desktop/test1.csv")
test1.r %>% str() 
test1.r %>% 
           filter(hp>100)
```

**Comment by hadley** [comment]
Here's a minimal reprex

```R
data_frame(x = 1:3, y = 1:3) %>% 
  setNames(c("x", "")) %>% 
  filter(x > 1)
```

**Comment by steventsimpson** [comment]
library(dplyr)

mtcars %>% 
           write.csv("~/Desktop/test1.csv")

test1_r <- readr::read_csv("~/Desktop/test1.csv") 
test1_r %>% 
           filter(hp>100)     # error occurs here

**Comment by hadley** [comment]
Actually I'd rather fix this in readr

**Comment by ianderson44** [comment]
I am experiencing this error message at startup (prior to any scripts run) and the error is generated over and over until R Studio freezes and needs a hard shut down.  Since the error happens without any command, I do not have a reproducible example.

I have tried uninstalling and installing latest versions of R and R Studio as well as removing and reloading all packages.  Nothing has fixed this issue.

Has anyone ever experienced this?
