### ISSUE TITLE
dplyr mutate to replace a subset of rows

### ISSUE THREAD

**Issue by vergilcw** [hadley/dplyr#1577]
A colleague of mine posted the following on SO:
http://stackoverflow.com/questions/34096162/dplyr-mutate-replace-on-a-subset-of-rows
He includes a reproducible example of the problem.

Is there any plan to implement mutate multiple columns in place by a condition? 

This is a similar issue to https://github.com/hadley/dplyr/issues/631 but with the emphasis on changing multiple columns based on one condition, rather than changing a single column based on multiple conditions (vectorized switch).

**Comment by hadley** [comment]
There are no current plans.

**Comment by alistaire47** [comment]
I think this is a case where the base idiom is still much simpler than any current dplyr option, as it's really easy to assign to a subset in base. In cases like when [you're using an API to geocode](http://stackoverflow.com/a/39176792/4497050), it can be really important, too, if you want to avoid unnecessary API calls.

Ultimately it still comes back to the #631 issue where people use a crazy amount of `ifelse` (or variants) in `mutate` with one of the cases as a straight copy of the variable being mutated. A trivial example easily dealt with with existing functions:

```r
iris %>% mutate_if(is.factor, as.character) %>% 
    mutate(Species = ifelse(Species == 'virginica', 'virg.', Species))
```

as opposed to base:

```r
data(iris)
iris$Species <- as.character(iris$Species)
iris[iris$Species == 'virginica', 'Species'] <- 'virg.'
```

Ultimately, this `ifelse` usage is primarily replacing data with the exact same data. Once you hit weird classes or multiple columns, more esoteric workarounds are necessary (`do`, list columns, self-joins), while the base stays exactly the same.

I understand the goal of keeping each verb operating on only one dimension, but everybody is already working around that limitation in less-straightforward ways. I'm not sure there's an easy answer here, but I think it's at least important to think about a better, generalizable approach to `mutate_where`.
