### ISSUE TITLE
option to clean/normalize data.frames?

### ISSUE THREAD

**Issue by r2evans** [hadley/dplyr#1587]
(Migrated from [rvest #116](https://github.com/hadley/rvest/issues/116).)

When `dplyr` is used with `rvest`, some HTML tables do not provide sufficient information to generate legitimate data.frames in R. Specifically, the following will fail:

```r
library(dplyr)
library(rvest)
HTML <- read_html('<table><tr><th>Var1</th><th> </th></tr><tr><td>1</td><td>2</td></table>')
HTML %>%
    html_node('table') %>%
    html_table() %>%
    tbl_df()
## Error: All columns must be named
```

The discussion started with a suggestion to add an option to `html_table` to check the column header names, but it has shifted to putting the data.frame validation into `dplyr`.

Perhaps something like:

```r
#' Check validity/format of a data.frame or tbl.
#'
#' Ensure the data.frame or tbl has legitimate and optionally unique column names.
#' @param x data.frame
#' @param check.names logical, whether to check/fix the column names
#' @param unique logical, force column names to be unique (\code{TRUE}) or
#'     allow duplicates (\code{FALSE}); ignored if \code{check.names} is \code{FALSE}
#' @return data.frame, with optionally different column names
#' @export
fix_df <- function(x, check.names=TRUE, unique=TRUE) {
  if (check.names) {
    col_names <- make.names(colnames(x), unique=unique)
    colnames(x) <- col_names
  }
  x
}
```

Use case, taking from the `rvest` example above:

```r
HTML %>%
    html_node('table') %>%
    html_table() %>%
    fix_df() %>%
    tbl_df()
## Source: local data frame [1 x 2]
##    Var1     X
##   (int) (int)
## 1     1     2
```

Perhaps, since it is currently just working on column names, it should be named `fix_df_names` or even `fix_df_colnames`.

**Comment by hadley** [comment]
I think this is outside the scope of dplyr, but is a good fit for tibble.

**Comment by r2evans** [comment]
Already discussed and submitted for merge, [tibble/pull/15](https://github.com/krlmlr/tibble/pull/15).
