### ISSUE TITLE
Need to convert dplyr output back to single class data frame in order to avoid errors with some functions

### ISSUE THREAD

**Issue by eipi10** [hadley/dplyr#1594]
I'm experiencing an issue where feeding a data frame created using `dplyr` to a function causes that function to throw an error unless I first use `as.data.frame` to convert the multi-class dplyr-created data frame back to a single-class data frame. 

I've had this problem with a number of functions on various occasions, but haven't kept track of which ones until now. I happened to have this issue today with the `likert` function from the `likert`package, so here's an example using that function and a small subset of my real data. Based on the error message displayed below, I'm wondering if some functions look only at the first class of the data object and throw an error if that class isn't data frame.

```r
# Data sample
dat=structure(list(v29 = structure(c(1L, 5L, 2L, 4L, 4L, 4L, 2L, 
5L, 5L, 2L), .Label = c("Not prepared at all", "Not very well prepared", 
"Don't know", "Well prepared", "Very well prepared"), class = "factor"), 
    v30 = structure(c(5L, 5L, 4L, 4L, 5L, 4L, 4L, 4L, 5L, 4L), .Label = c("Not prepared at all", 
    "Not very well prepared", "Don't know", "Well prepared", 
    "Very well prepared"), class = "factor")), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -10L), .Names = c("v29", 
"v30"))

library(likert)
library(dplyr)
```

`likert` throws an error with this data frame:

```r
likert(dat)
Error in likert(dat) : 
  The items parameter must be a data frame. If trying to subset a data frame to analyze only one 
column, try: items=mydf[,1, drop=FALSE].
In addition: Warning message:
In if (class(items) != "data.frame") { :
  the condition has length > 1 and only the first element will be used
```

Converting back to data frame-only class gets rid of the error.

```r
likert(dat %>% as.data.frame)

  Item Not prepared at all Not very well prepared Don't know Well prepared Very well prepared
1  v29                  10                     30          0            30                 30
2  v30                   0                      0          0            60                 40 
```

**Comment by hadley** [comment]
That's pretty clearly a bug in the likert package - can you please file a bug with the maintainer?

**Comment by eipi10** [comment]
Sure, will do. Thanks Hadley.

**Comment by kevinushey** [comment]
For reference, the buggy code in the `likert` package:

```
if (class(items) != "data.frame") {
      stop(paste0("The items parameter must be a data frame. If trying ", 
        "to subset a data frame to analyze only one column, try: ", 
        "items=mydf[,1, drop=FALSE]."))
    }
```

This check should probably just be `is.data.frame()`. Perhaps it can be reported at https://github.com/jbryer/likert/issues?
