### ISSUE TITLE
self-join corrupts grouped_df

### ISSUE THREAD

**Issue by bergsmat** [hadley/dplyr#1597]
Consider:

``` r
library(devtools)
install_github('hadley/dplyr',ref='4f2d7')
library(dplyr)
library(magrittr)

# Select subjects with any conc >= 9
Theoph %<>% group_by(Subject,Time)
Theoph %>% 
  semi_join(
    Theoph %>%
      filter(conc >= 9) %>%
      ungroup %>%
      select(Subject)
  ) %>% filter(Subject == 1)

# Joining by: "Subject"
# Error: corrupt 'grouped_df', contains 55 rows, and 132 rows in groups
```

I get around this by writing a `semi_join` method for `grouped_df` that ungroups / regroups. But it seems like something that should work natively.

**Comment by hadley** [comment]
Could you please provide a simpler reprex using a made up data frame and avoiding `%<>%`?

**Comment by bergsmat** [comment]
library(devtools)
install_github('hadley/dplyr',ref='4f2d7')
library(dplyr)
data <- data.frame(
  id = c('a','a','a','b','b','b'),
  val = c(1,2,3,0,1,2)
)
#select all records for any id with any val >= 3
data <- group_by(data,id)
crit <- filter(data, val >= 3)
crit <- ungroup(crit)
crit <- select(crit, id)
data <- semi_join(data,crit)
filter(data,id==1)
#Error: corrupt 'grouped_df', contains 3 rows, and 6 rows in groups

**Comment by hadley** [comment]
For future reference, this is what a minimal reprex should look like:

```R
data <- data_frame(
  id = c('a', 'a', 'b', 'b'),
  val = c(1, 2, 0, 1, 2)
)

data %>% 
  group_by(id) %>% 
  semi_join(data_frame(id = "a")) %>% 
  filter(id == 1)
```

**Comment by krlmlr** [comment]
I'm still seeing a failure from @bergsmat's example, @hadley's code gives:

```
Error: Variables must be length 1 or 5.
Problem variables: 'id'
```

**Comment by krlmlr** [comment]
Fixed reprex:

```r
data <- data_frame(
  id = c('a', 'a', 'b', 'b'),
  val = c(1, 2, 0, 1)
)

data %>% 
  group_by(id) %>% 
  semi_join(data_frame(id = "a")) %>% 
  filter(id == 1)
## Joining, by = "id"
## Error in filter_impl(.data, dots) : 
##   corrupt 'grouped_df', contains 2 rows, and 4 rows in groups
```

**Comment by krlmlr** [comment]
@hadley: Maintaining the grouping after a join is doable, but will take some time to implement. `anti_join()` and `full_join()` seem to be broken as well. It's way easier to just ungroup. Please advise.

``` r
library(dplyr, warn.conflicts = FALSE)
data <- data_frame(
  id = c('a', 'a', 'b', 'b'),
  val = c(1, 2, 0, 1)
)

data %>% 
  group_by(id) %>% 
  full_join(data_frame(id = "c"))
#> Joining, by = "id"
#> Source: local data frame [5 x 2]
#> Groups: id [?]
#> 
#>      id   val
#>   <chr> <dbl>
#> 1     a     1
#> 2     a     2
#> 3     b     0
#> 4     b     1
#> 5     c    NA

data %>% 
  group_by(id) %>% 
  anti_join(data_frame(id = "a"))
#> Joining, by = "id"
#> Source: local data frame [2 x 2]
#> Groups: id [2]
#> 
#>      id   val
#>   <chr> <dbl>
#> 1     b     0
#> 2     b     1

data %>% 
  group_by(id) %>% 
  semi_join(data_frame(id = "a"))
#> Joining, by = "id"
#> Source: local data frame [2 x 2]
#> Groups: id [2]
#> 
#>      id   val
#>   <chr> <dbl>
#> 1     a     1
#> 2     a     2
```

**Comment by hadley** [comment]
Can't we just leave as a "lazy" grouping? i.e. delete the indices, and have then recomputed as needed? (I forget exactly how that works behind the scenes)

**Comment by krlmlr** [comment]
We'd have to store the indices in an environment then. This does seem brittle to me.

**Comment by hadley** [comment]
This is an existing feature, not something new.

**Comment by krlmlr** [comment]
The group indexes are currently stored in an attribute. Are you suggesting to update that attribute in-place if we want to cache the indexes that are now computed lazily?

**Comment by hadley** [comment]
There is already a way to maintain the attributes that record the grouping, without maintaining the attributes that specify the indexes

**Comment by krlmlr** [comment]
Computing the index is expensive, and should be done only once per grouped df. How do we cache the computed index?

**Comment by hadley** [comment]
We don't currently.

**Comment by krlmlr** [comment]
Simply removing the `"indices"` attribute breaks things:

``` r
library(dplyr, warn.conflicts = FALSE)
x <- group_by(mtcars, cyl)
attr(x, "indices")
#> [[1]]
#>  [1]  2  7  8 17 18 19 20 25 26 27 31
#> 
#> [[2]]
#> [1]  0  1  3  5  9 10 29
#> 
#> [[3]]
#>  [1]  4  6 11 12 13 14 15 16 21 22 23 24 28 30
x %>% summarize(mean(mpg))
#> # A tibble: 3 × 2
#>     cyl `mean(mpg)`
#>   <dbl>       <dbl>
#> 1     4    26.66364
#> 2     6    19.74286
#> 3     8    15.10000
attr(x, "indices") <- NULL
x %>% summarize(mean(mpg))
#> Error in summarise_impl(.data, dots): not compatible with requested type
```

I'd rather compute correct indexes after the join, or remove the grouping.

**Comment by hadley** [comment]
I thought this worked because `print.grouped_df` has:

```R
  grps <- if (is.null(attr(x, "indices"))) "?" else length(attr(x, "indices"))
```

Maybe it used to work but doesn't any more?

**Comment by krlmlr** [comment]
I'm not sure. I think the safest path is just to recompute the indices, and to consider a grouped df without `indices` attribute broken. Recomputing should be much cheaper to implement than some clever logic to maintain the indices.

**Comment by hadley** [comment]
In that case, `ungroup()`ing is fine.

**Comment by hadley** [comment]
@krlmlr here's an example that produces a "lazily" grouped df:

```R
 diamonds %>% group_by(color, cut) %>% summarise(n = n()) %>% str()
```
