### ISSUE TITLE
error if function supplied to mutate contains conditional

### ISSUE THREAD

**Issue by david-romano** [hadley/dplyr#1598]
Here's an example:
> df <- data.frame(x = rep("a",4), y = 1:2)
> df
  x y
1 a 1
2 a 2
3 a 1
4 a 2
> ff <- function(x) if (x<2) "one" else "two"
> df %>% mutate(new = ff(y))
  x y new
1 a 1 one
2 a 2 one
3 a 1 one
4 a 2 one
Warning message:
In if (x < 2) "one" else "two" :
  the condition has length > 1 and only the first element will be used

Why is the condition interpreted as length > 1?

Thanks,
David

**Comment by hadley** [comment]
Because the function needs to be vectorised. Try ifelse instead
