### ISSUE TITLE
Join on a column whose name is in a variable

### ISSUE THREAD

**Issue by giacecco** [hadley/dplyr#1599]
This may not be a dplyr issue but rather me not getting the syntax right. I need to _left\_join_ two tables _a_ and _b_, on a column whose name is in a variable, as in the example below

```
variable_column_name_of_table_a <- "foo"
a %>% left_join(b, c(variable_column_name_of_table_a = "static_column_name_of_table_b"))
```

This does not work and I get an error like:

```
Error in View : cannot join on columns 'variable_column_name_of_table_a' x 'static_column_name_of_table_b': index out of bounds 
```

What am I doing wrong? In the meantime, merry Christmas everybody!

**Comment by docendodiscimus** [comment]
@giacecco see https://stackoverflow.com/questions/28125816/r-standard-evalation-for-join-dplyr

**Comment by giacecco** [comment]
Great thanks!
