### ISSUE TITLE
bind_cols example not works

### ISSUE THREAD

**Issue by artemklevtsov** [hadley/dplyr#1610]
Hi.

Example not work:

```r
dplyr::bind_cols(data.frame(x = 1), data.frame(y = 1:2))
#> Error: incompatible number of rows (2, expecting 1)
packageVersion("dplyr")
#> [1] ‘0.4.3’
```

**Comment by hadley** [comment]
Because there are different numbers of rows.

**Comment by artemklevtsov** [comment]
I know, but this example from the ``dplyr` documentation.

**Comment by hadley** [comment]
To me it seems clear from the context that the example is illustrating a problem.
