### ISSUE TITLE
filter not working when dplyr preloaded in .Rprofile

### ISSUE THREAD

**Issue by mct941** [hadley/dplyr#1611]
I'm running R v3.2.2 or v3.2.3 in RStudio v0.99.473.  Recently, the filter command doesn't work when dplyr is preloaded in my .Rprofile.  I thought that there may be some conflict with other packages, so I unloaded everything except for dplyr.  See attachment for an example.  It works when I manually load the dplyr package.

![image](https://cloud.githubusercontent.com/assets/7346432/12083106/776f3858-b262-11e5-9a6a-9784482724af.png)

**Comment by hadley** [comment]
Because packages loaded in `.Rprofile` are loaded before the standard packages like stats. This is one (of many) reasons that you shouldn't load packages in your `.Rprofile`

**Comment by mct941** [comment]
It was never come up as an issue before. But I will try to find another workaround. Thanks. 





On Mon, Jan 4, 2016 at 7:00 AM -0800, "Hadley Wickham" <notifications@github.com> wrote:












Because packages loaded in .Rprofile are loaded before the standard packages like stats. This is one (of many) reasons that you shouldn't load packages in your .Rprofile

**Comment by abresler** [comment]
If you do load packages in your .Rprofile just make sure you use the package namespace reference, if you use RStudio autocomplete is very very good and makes this task far less painless.  To get around this problem whenever I reference filter I just use:

```
dplyr::filter()
```

That's the best work around
