### ISSUE TITLE
Problems with filter() and "!=" and "|" operators

### ISSUE THREAD

**Issue by jflanaga** [hadley/dplyr#1613]
Sorry, I'm not sure if this is a bug, and, if it is, whether it already has been reported. I'm having problems using `filter` with the `!=`  and `|` logical operators.

```
    n <-  c(2, 3, 5) 
    s <-  c("aa", "bb", "cc") 
    b <-  c(TRUE, FALSE, TRUE) 
    df <-  data.frame(n, s, b) 
```
This filters correctly, so the problem isn't with `==`
```
    df %>% 
        filter(s == "aa" | b == FALSE)
```
This filters correctly, so the problem isn't with `!=` by itself
```
df %>% 
    filter(s != "aa")
```

This filters correctly, so the problem isn't with `&` and `!=`
```
df %>% 
    filter(n != 2 & b != TRUE)
```
Problem begins here. This filters for `n` but not for `b`
```
    df %>% 
    filter(n != 2 | b != TRUE)
``` 
This doesn't filter any of the variables
```
df %>% 
    filter(s != "aa" | b != FALSE)
 ```

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)
dplyr_0.4.3 
```
I originally tested this with Cran version but just tested it with developer's version as well and had the same problems.

**Comment by hadley** [comment]
Looks fine to me:

```R
df %>% mutate(x = s != "aa", y = b != FALSE, x | y)
```

Your expression is true for every row.

**Comment by jflanaga** [comment]
Maybe I'm just confusing myself. I thought that I used to get a dataset that would only return the third row by using the following: 
 
```df %>% 
  filter(s != aa  | b != FALSE)```
```
However, what I get is this: 

```
   n  s     b
1 2 aa  TRUE
2 3 bb FALSE
3 5 cc  TRUE
```
Shouldn't only the third row be returned, since value of `s` in the first row is `aa` and the value of `b` in the second row is `FALSE`? I had older code that I could have sworn used to filter out rows using a similar operation but now only returns the original dataset. 

I thought I had code that used to work using the same principle, that is, this

```
voice %>%
    filter(age != "unknown" | occupation != "missing data" | occupation != "unknown")
```
used to filter our rows where either `age` was unknown or the `occupation` was `missing data` (or `unknown`). Now it returns the original dataset. I guess I was mistaken about what my code used to do?

**Comment by hadley** [comment]
`s != aa  | b != FALSE` is equivalent to `s != aa  | b == TRUE` which is equivalent to `s != aa | b`. The first condition is true for every row except the first; the second condition is true for the first and third rows. 

For your second example, I think it's easy to think first of selecting the rows you don't want: `age == "unknown" | occupation == "missing data" | occupation == "unknown"`. Then use De Morgans rule to find the opposite: `age != "unknown" & occupation != "missing data" & occupation != "unknown"`.

**Comment by jflanaga** [comment]
Thanks. Sorry for wasting your time.
