### ISSUE TITLE
group_by, summarise returns unexpected value

### ISSUE THREAD

**Issue by joel23888** [hadley/dplyr#1614]
I get an unexpected result in the following example. Can anyone reproduce this?

I have two variables `v1` and `avgV1`, and I want to summarize them by calculating the mean in each group. The result below in `avgAvgV1` wrongly reflects the result for `avgV1`.

```R
> x <- data_frame(symbol = rep(c("AAA", "BBB"), 2), v1 = runif(4), avgV1 = runif(4) * 100)
> x
Source: local data frame [4 x 3]

  symbol        v1     avgV1
   (chr)     (dbl)     (dbl)
1    AAA 0.3978305 87.035240
2    BBB 0.9269147 78.596363
3    AAA 0.5058466  6.431127
4    BBB 0.8204960 31.284582
> x %>% group_by(symbol) %>% summarise(avgV1 = mean(v1), avgAvgV1 = mean(avgV1))
Source: local data frame [2 x 3]

  symbol     avgV1  avgAvgV1
   (chr)     (dbl)     (dbl)
1    AAA 0.4518386 0.4518386
2    BBB 0.8737054 0.8737054
```

If I rename `avgV1` to something else like `v2` the problem goes away.

```R
> x %>% rename(v2 = avgV1) %>% group_by(symbol) %>% summarise(avgV1 = mean(v1), avgV2 = mean(v2))
Source: local data frame [2 x 3]

  symbol     avgV1    avgV2
   (chr)     (dbl)    (dbl)
1    AAA 0.4518386 46.73318
2    BBB 0.8737054 54.94047
```

Also if I just rename the variable but keep the output variable name the same in summarise, the problem goes away.

```R
> x %>% rename(v2 = avgV1) %>% group_by(symbol) %>% summarise(avgV1 = mean(v1), avgAvgV1 = mean(v2))
Source: local data frame [2 x 3]

  symbol     avgV1 avgAvgV1
   (chr)     (dbl)    (dbl)
1    AAA 0.4518386 46.73318
2    BBB 0.8737054 54.94047
```

Info:
R version 3.2.3
dplyr version 0.4.3      2015-09-01 CRAN (R 3.2.3)

**Comment by hadley** [comment]
Yes, because you've replaced the old values

**Comment by joel23888** [comment]
@hadley When I ran the following code:

```R
x %>% group_by(symbol) %>% summarise(avgV1 = mean(v1), avgAvgV1 = mean(avgV1))
```

I expected the result to summarize the original data i.e. `avgV1` as the mean of `v1` and `avgAvgV1` as the mean of `avgV1`. Or am I missing something?

**Comment by hadley** [comment]
You just replaced `avgV1` with a new value

**Comment by joel23888** [comment]
I understand what is happening but is it preferable that for summarise (in contrast to mutate) the variables passed to functions refer to the underlying data that is being summarized?

**Comment by hadley** [comment]
It behaves this way in order to be consistent with mutate.

**Comment by joel23888** [comment]
I see, so in this case I should use summarise without replacing `avgV1`, then use rename after summarise if I want to call it `avgV1` in the summarized data. For example:

```R
x %>% group_by(symbol) %>% summarise(avgV1Temp = mean(v1), avgAvgV1 = mean(avgV1)) %>% rename(avgV1 = avgV1Temp)
```

I still think it would be more intuitive if summarise worked the way I had expected. I cannot think of why it would need to be consistent with mutate in this case.
