### ISSUE TITLE
joining to NULL

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1615]
All of the joins error if one of the inputs is `NULL`, whereas `base::merge()` returns a 0-row data frame with variables taken from the non-`NULL` input, if such exists, or with 0 columns, if it's also `NULL`. If this is how it's supposed to be, then just close this.

``` r
library(dplyr)
inner_join(NULL, iris)
#> Error in UseMethod("inner_join"): no applicable method for 'inner_join' applied to an object of class "NULL"
merge(NULL, iris)
#> [1] Sepal.Length Sepal.Width  Petal.Length Petal.Width  Species     
#> <0 rows> (or 0-length row.names)
merge(NULL, NULL)
#> data frame with 0 columns and 0 rows
```

**Comment by hadley** [comment]
I think this is how its supposed to be. (But please open an issue if one of my packages is returning a NULL when it should return an empty data frame)
