### ISSUE TITLE
Printing data_frame with multiple empty column names gives wrong output

### ISSUE THREAD

**Issue by huftis** [hadley/dplyr#1621]
When a data_frame has *multiple* columns with an empty column name, printing the data_frame results in very strange column names being printed. The following works fine:

    library(dplyr)
    d = as_data_frame(head(iris))
    names(d)[2] = ""
    d

The output is

      Sepal.Length       Petal.Length Petal.Width Species
             (dbl) (dbl)        (dbl)       (dbl)  (fctr)
    1          5.1   3.5          1.4         0.2  setosa
    2          4.9   3.0          1.4         0.2  setosa
    3          4.7   3.2          1.3         0.2  setosa
    4          4.6   3.1          1.5         0.2  setosa
    5          5.0   3.6          1.4         0.2  setosa
    6          5.4   3.9          1.7         0.4  setosa

But when a second column also gets an empty name

    names(d)[4] = ""
    d

the column name show for the second column is the content* of the column:

      Sepal.Length       Petal.Length structure(c("(dbl)", "0.2", "0.2", "0.2", "0.2", "0.2", "0.4" Species
             (dbl) (dbl)        (dbl)                                                         (dbl)  (fctr)
    1          5.1   3.5          1.4                                                           0.2  setosa
    2          4.9   3.0          1.4                                                           0.2  setosa
    3          4.7   3.2          1.3                                                           0.2  setosa
    4          4.6   3.1          1.5                                                           0.2  setosa
    5          5.0   3.6          1.4                                                           0.2  setosa
    6          5.4   3.9          1.7                                                           0.4  setosa

**Comment by romainfrancois** [comment]
Looks like a bug borrowed from R's `print.data.frame` : 

```
> as.data.frame(d)
  Sepal.Length     Petal.Length structure(c("0.2", "0.2", "0.2", "0.2", "0.2", "0.4"), class = "AsIs") Species
1          5.1 3.5          1.4                                                                    0.2  setosa
2          4.9 3.0          1.4                                                                    0.2  setosa
3          4.7 3.2          1.3                                                                    0.2  setosa
4          4.6 3.1          1.5                                                                    0.2  setosa
5          5.0 3.6          1.4                                                                    0.2  setosa
6          5.4 3.9          1.7                                                                    0.4  setosa
```

**Comment by hadley** [comment]
Reported on r-devel
