### ISSUE TITLE
Add option to obtain indexes from elements joined

### ISSUE THREAD

**Issue by nuno-agostinho** [hadley/dplyr#1623]
dplyr does many common join operations on two tables, but it doesn't return the indexes of the elements that match from each table… Maybe this could be returned by adding an optional boolean argument in the join functions? The package already calculates these indexes so it would be just a question of allowing the user to get them.

**Comment by hadley** [comment]
Why do you want/need the indices?

**Comment by nuno-agostinho** [comment]
I'm working with multiple tables and I'd like to find matches between them based on select columns. Having a matrix with the indexes of the matching rows across the different tables would mean I can keep my tables separated (instead of joining them all together which is harder to manipulate them afterwards).

There are other ways to do what I'm asking but all the solutions I've found are slower than this function and that's why I'm asking for this.

**Comment by hadley** [comment]
Hmmmm, that doesn't seem like a particularly good idea to me - you'll have to be very careful not to filter or arrange the data frames or the indices will no longer line up correctly.  I rather get to the bottom of why you find working with the joined data frames hard.

**Comment by nuno-agostinho** [comment]
The original data frames are not supposed to be altered during all the analysis, so that shouldn't be an issue.

The problem is that I'd like to show the large data frames I have separately in a Shiny app and I don't like the idea of having repeated information on memory. Of course, I could delete the original data frame and only have a full joined data frame with the information of all data frames and then subset the data frame to get the original table when the user needs it.

Anyway, thanks for your time! :)

**Comment by hadley** [comment]
This just seems slightly too specialised to make it onto my todo list, sorry.

**Comment by nuno-agostinho** [comment]
All right, thanks for your time!
