### ISSUE TITLE
is there a way to use rpostgres library with dplyr ?

### ISSUE THREAD

**Issue by sandys** [hadley/dplyr#1624]
The information is in bits and pieces and am having a hard time trying to figure it out.
RPostgreSQL seems to be last updated in 2013 on CRAN
RPostgres seems to be a more recent project and has the same authors as dplyr
All code examples seem to RPostgreSQL . Attempting to use RPostgres throws the error "Error: RPostgreSQL package required to connect to postgres db"

**Comment by hadley** [comment]
Not currently.
