### ISSUE TITLE
is_row_wise option for filter?

### ISSUE THREAD

**Issue by jhofman** [hadley/dplyr#1630]
filtering a data frame with many groups can often be unnecessarily slow because filter has no way of knowing if the filtering condition is row-wise, and so it repeats each filtering operational within each group.

ungrouping solves the problem, but this may not be obvious to many users.

would it make sense to add an argument to filter to give users control over this option, or at least to add a note in the documentation about this?

sample code below demonstrates the issue.

``` r
# create a dummy dataframe with 100,000 groups and 1,000,000 rows
# and partition by group_id
df <- data.frame(group_id=sample(1:1e5, 1e6, replace=T),
                 val=sample(1:100, 1e6, replace=T)) %>%
      group_by(group_id)

# filter rows with a value of 1 naively
system.time(df %>% filter(val == 1))

#   user  system elapsed
#  1.447   0.017   1.476

# ungroup before filtering for a huge speedup
system.time(df %>% ungroup() %>% filter(val == 1))

#   user  system elapsed
#  0.007   0.003   0.010
```

**Comment by romainfrancois** [comment]
Would be great for `filter` to recognize that `val==1` can just be evaluated for the whole data set. That is kind of tricky, for example `max(val)==1` can't because `max(val)` has to be evaluated within each group.

**Comment by jhofman** [comment]
absolutely. since it's a difficult problem to solve generically, here are simpler possibilities:

1. warn users about the issue in the documentation and recommend ungroup()-ing as a best practice

2. add a flag so users can manually override things

3. try to recognize the simplest conditions that don't have any function calls and execute on the whole dataset for these, at least

would any of those be feasible?

**Comment by hadley** [comment]
@romainfrancois doesn't it seem like the performance is particularly bad? Why does evaluating on a per group basis cause such a slow down?
