### ISSUE TITLE
Use of magrittr's compound assignment operator inside mutate

### ISSUE THREAD

**Issue by jamespmcguire** [hadley/dplyr#1632]
I use dplyr a lot for cleaning data.  No idea if feasible, but a feature I would find useful, that would allow for more concise code, would be to enable something like magrittr's compound assignment operate `%<>%` within mutate:
```r
data.frame(long.variable.name = c("2015-12-01", "2015-12-02")) %>% 
    mutate(long.variable.name = as.Date(long.variable.name))

data.frame(long.variable.name = c("2015-12-01", "2015-12-02")) %>% 
    mutate(long.variable.name %<>% as.Date)
```

**Comment by hadley** [comment]
I'm not a huge fan of that operator, and it would be a lot of work to implement.
