### ISSUE TITLE
glimpse() should show data groupings

### ISSUE THREAD

**Issue by dalejbarr** [hadley/dplyr#1634]
It would be nice if the display of data groupings was consistent across `print()` and `glimpse()`.  Currently, `print()` shows data groupings but `glimpse()` does not.

    iris %>% group_by(Species) %>% print()
    ## Source: local data frame [150 x 5]
    ## Groups: Species [3]
    ##
    ##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
    ##          (dbl)       (dbl)        (dbl)       (dbl)  (fctr)
    ## 1           5.1         3.5          1.4         0.2  setosa
    ## (etc)

    iris %>% group_by(Species) %>% glimpse()
    ## Observations: 150
    ## Variables: 5
    ## $ Sepal.Length (dbl) 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4,...
    ## $ Sepal.Width  (dbl) 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7,...
    ## $ Petal.Length (dbl) 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5,...
    ## $ Petal.Width  (dbl) 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2,...
    ## $ Species      (fctr) setosa, setosa, setosa, setosa, setosa, setosa, setos...

**Comment by hadley** [comment]
I'd be happy to review a PR that implemented this.
