### ISSUE TITLE
error in right_join when both by variables have label attributes

### ISSUE THREAD

**Issue by ikkyle** [hadley/dplyr#1636]
I'm getting the error:

`Error: cannot join on columns 'i' x 'i': Can't join on 'i' x 'i' because of incompatible types (numeric / numeric) `

When the by variable `i` from both datasets have a label attribute pulled in from `haven::read_sas`.

Reproducible example via attached .sas7bdat files:

``` r
options(stringsAsFactors=FALSE)
library(haven)
library(dplyr)

tbl_right <- read_sas('right.sas7bdat')
tbl_left  <- read_sas('left.sas7bdat')

right_join(tbl_right, tbl_left, by='i')

attr(tbl_right$i, 'label') <- NULL
attr(tbl_left$i, 'label') <- NULL

right_join(tbl_right, tbl_left, by='i')
```

``` 
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3 haven_0.2.0

loaded via a namespace (and not attached):
[1] assertthat_0.1 DBI_0.3.1      magrittr_1.5   parallel_3.1.2 R6_2.1.0       Rcpp_0.11.6   
[7] tools_3.1.2
```

[example_files.zip](https://github.com/hadley/dplyr/files/101180/example_files.zip)

**Comment by romainfrancois** [comment]
Can you make this reproducible. We don't have your `.sas7bdat` files

**Comment by ikkyle** [comment]
I attached a .zip file. Are they not in there?

**Comment by romainfrancois** [comment]
Ok thanks. I did not see the attachment before.

**Comment by romainfrancois** [comment]
Ok so what happens is that we don't know how to join these so it fails. We could instead drop attributes, but maybe this would lead to other issues. ping @hadley ?

**Comment by huftis** [comment]
When the attributes are *identical* (which they typically are if the two data frames come from the same source), this could be handled gracefully, by just including the attributes on the resulting data frame.

If they are not identical, keep the first set of attributes (i.e. the ones from the source data frame) and issue a warning that the second ones have been dropped?

**Comment by hadley** [comment]
@ikkyle can you please make an inline reproducible example? You shouldn't need to use haven or external data

**Comment by ikkyle** [comment]
``` r
library(dplyr)

# I had to make the "by" variables numeric rather than integer--it works fine when they're integers
tbl_left <- tbl_df(data.frame(i = rep(c(1.0, 2.0, 3.0), each = 2),
                              x1 = letters[1:6]))
tbl_right <- tbl_df(data.frame(i = c(1.0, 2.0, 3.0),
                               x2 = letters[1:3]))

left_join(tbl_left, tbl_right, by = 'i')

attr(tbl_left$i, 'label') <- 'iterator'
attr(tbl_right$i, 'label') <- 'iterator'

left_join(tbl_left, tbl_right, by = 'i')
```

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.2       assertthat_0.1 parallel_3.2.3 DBI_0.3.1      tools_3.2.3    Rcpp_0.12.3   
```

**Comment by hadley** [comment]
* For future reference, please don't include session info unless explicitly asked
* Can you please use `data_frame()` instead of `tbl_df()` + `data.frame()`

**Comment by ikkyle** [comment]
``` r 
library(dplyr)

tbl_left <- data_frame(i = rep(c(1.0, 2.0, 3.0), each = 2),
                              x1 = letters[1:6])
tbl_right <- data_frame(i = c(1.0, 2.0, 3.0),
                               x2 = letters[1:3])

left_join(tbl_left, tbl_right, by = 'i')

attr(tbl_left$i, 'label') <- 'iterator'
attr(tbl_right$i, 'label') <- 'iterator'

left_join(tbl_left, tbl_right, by = 'i')
```

**Comment by romainfrancois** [comment]
This might need some extra testing or better choices of error messages in fail cases but basically I implemented @huftis suggestion about letting pass when attributes are identical. And error when not.

**Comment by LaDilettante** [comment]
I would suggest an error message indicating that the reason for failure is due to differing attributes. Currently there is no indication that points towards attributes.
