### ISSUE TITLE
Would it be a good idea for dplyr verbs to propagate NULL data frames?

### ISSUE THREAD

**Issue by skranz** [hadley/dplyr#1638]
I just wonder whether perhaps one could make dplyr verbs to act more like base R and propagate NULL data frames instead of throwing an error. Here is a simple example:

```r
  # Assume you sometimes have no data
  # and df is NULL
  df = NULL
  
  # Base R does not throw errors quickly
  # but conveniently propagates NULL
  df[df$a==1,]
  ## NULL
  
  # dplyr verbs are not as tolerant...
  filter(df, a==1)
  ## Error in UseMethod("filter_") : 
  ## no applicable method for 'filter_' applied to an object of class "NULL"
```

Returning NULL instead of an error could probably be easily implemented by adding functions like:
```r
filter_.NULL = function(...) return(NULL)
``` 
While this is not a big issue, I would find NULL propagation quite convenient, since one can get rid of some case distinctions and dplyr would probably behave more like base R.

Conceptually it also seems sound to me to return NULL:
If I filter something from NULL, it seems intuitive that the result is NULL.
If I arrange NULL the result should also be NULL.
If I mutate NULL the result should also be NULL.
... and so on...

**Comment by krlmlr** [comment]
In the `tibble` package, `tbl_df(NULL)` returns an empty data frame (https://github.com/krlmlr/tibble/pull/17). So, inserting `tbl_df` early in your pipeline should help for your use case. It will be imported by default when #1595 is merged.

**Comment by hadley** [comment]
I think it's a bad idea to silently coerce NULL (which is not a data frame) into a data frame.

You'd be better off using an empty data frame, i.e. `data_frame()`

**Comment by krlmlr** [comment]
What about explicit coercion using tbl_df() or as_data_frame()?

**Comment by hadley** [comment]
It's probably reasonable for `as_data_frame` to have a `NULL` method
