### ISSUE TITLE
'group_by %>% summarise' inconsistent about returning grouped_df

### ISSUE THREAD

**Issue by kurtosis-color** [hadley/dplyr#1640]
I think this may be intentional but it threw me for a loop. Using `group_by %>% summarise` returns a `tbl_df` if there is one grouping variable and a `grouped_df` if there are two grouping variables. This caused a problem downstream b/c I was using `select` to drop a column, which does not work on `grouped_df`s. Solution was to add an `ungroup` but I think this is new behavior, as my code was previously working without it prior to upgrading dplyr. Using `dplyr_0.4.3`.

```r
library(dplyr)
set.seed(111)
dat1 = data.frame(group1=sample(LETTERS[1:3], 1000, replace=TRUE),
                   group2=sample(LETTERS[1:3], 1000, replace=TRUE),
                   y=rnorm(1000))
one_grouping = group_by(dat1, group1) %>%   summarise(orders = n())
two_groupings = group_by(dat1, group1, group2) %>%   summarise(orders = n())
```

```
> class(one_grouping)
[1] "tbl_df"     "tbl"        "data.frame"
> class(two_groupings)
[1] "grouped_df" "tbl_df"     "tbl"        "data.frame"
```

**Comment by romainfrancois** [comment]
`one_grouping` is no longer grouped, whereas `two_groupings` remains grouped on the `group2` variable. This works as it is supposed to.
