### ISSUE TITLE
vignettes/databases.html bad link 

### ISSUE THREAD

**Issue by EconomiCurtis** [hadley/dplyr#1646]
Link to 
- "10 easy steps to a complete understanding of SQL" 
- at http://tech.pro/tutorial/1555/10-easy-steps-to-a-complete-understanding-of-sql 
is defunct. 

You might contact the author (https://github.com/lukaseder) about a new home. 

Here's the original version if you're interested in recreating it:
https://web.archive.org/web/20150312161417/http://tech.pro/tutorial/1555/10-easy-steps-to-a-complete-understanding-of-sql

**Comment by hadley** [comment]
@lukasedar do you have a new home for your excellent article?

**Comment by hadley** [comment]
@lukaseder do you have a new home for your excellent article?

**Comment by lukaseder** [comment]
Oh crap, completely forgot about that - it was on my TODO list to recover that article and put it back online on the jOOQ blog (after getting permission by the owners). Will do and send you notification on this issue. The post should go live again next week. Hope that's soon enough.

**Comment by hadley** [comment]
@lukaseder no problems - actual release process want start for at least a week.

**Comment by lukaseder** [comment]
Finally, here it is:
http://blog.jooq.org/2016/03/17/10-easy-steps-to-a-complete-understanding-of-sql

**Comment by hadley** [comment]
@lukaseder thanks - and thanks for writing such an awesome tutorial!
