### ISSUE TITLE
Select Also Returns Grouping Variables

### ISSUE THREAD

**Issue by DarioS** [hadley/dplyr#1647]
The documentation writes that "`select()` keeps only the variables you mention". However,

```r
    dataset <- data_frame(A = 1:10, B = 10:1, group = sample(LETTERS[25:26], 10, TRUE))
    dataset <- group_by(dataset, group)
    select(dataset, B)
```

shows that it also keeps the grouping variable. Should the documentation be modified or the result of the function to make the result consistent with the documentation ?

**Comment by jennybc** [comment]
duplicate of #1511
