### ISSUE TITLE
bind_rows Not Equivalent to rbind

### ISSUE THREAD

**Issue by DarioS** [hadley/dplyr#1649]
The [blog](http://blog.rstudio.org/2015/01/09/dplyr-0-4-0/) states "If `x` is a list of data frames, `bind_rows(x)` is equivalent to `do.call(rbind, x)`"

However, consider:

    dataList <- list(data.frame(A = 1:5, row.names = 0:4), data.frame(A = 6:7, row.names = 88:89))
    do.call(rbind, dataList)
    bind_rows(dataList)

`bind_rows` changes the row numbers, unlike `rbind` which preserves the user's numbering, so the two approaches are not entirely equivalent.

It also converts factors to characters when the levels are unequal, unlike `rbind`.

**Comment by romainfrancois** [comment]
Sure. All of this is by design.
