### ISSUE TITLE
Link in databases vignette broken, this might be a replacement

### ISSUE THREAD

**Issue by masalmon** [hadley/dplyr#1654]
Broken link: <http://tech.pro/tutorial/1555/10-easy-steps-to-a-complete-understanding-of-sql> ("Tech.pro has been temporarily deactivated. We will bring Tech.pro back online after our team has grown in sufficient size to support the community. ")

This <http://blog.csdn.net/dgly1611/article/details/18355593> seems to be the same content? And it's very useful indeed.

**Comment by hadley** [comment]
Duplicate of #1646
