### ISSUE TITLE
glimpse() detects incorrect display width

### ISSUE THREAD

**Issue by drewgendreau** [hadley/dplyr#1662]
Hi,

No matter my data, glimpse incorrectly detects my console width leading to a spillover of exactly an ellipses every time:

[<a href="http://tinypic.com?ref=f9drt0" target="_blank"><img src="http://i67.tinypic.com/f9drt0.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

I've been manually passing a width, but wondering if there is a more permanent solution.  I'm running RStudio on Linux Mint 17.3.

Thanks!

**Comment by krlmlr** [comment]
glimpse() attempts to use all of the available width. Have you tried a different font in RStudio?

**Comment by drewgendreau** [comment]
I tried this morning changing both the font and the font size in R studio (several different options for each) and none seemed to work unfortunately

**Comment by drewgendreau** [comment]
Looks like this was an issue with RStudio, not dplyr

Fixed in RStudio 99.878

https://support.rstudio.com/hc/en-us/community/posts/205590078-console-width-incorrectly-detected-in-RStudio-Server-
