### ISSUE TITLE
Segfault with "mutate"

### ISSUE THREAD

**Issue by lgautier** [hadley/dplyr#1668]
The following one line is consistenly endind with a segfault here:

```r
dplyr::mutate(group_by(mtcars, gear), foo=sum)
```

The call to `mutate()` should certainly not succeed without error but I wish that `dplyr` would show mercy and respond with something gentler, such as a call to `stop()`.

**Comment by hadley** [comment]
@romainfrancois looks like we're missing a check

**Comment by hadley** [comment]
I now get: " Error: unsupported type for column 'foo' (BUILTINSXP, classes = function) "
