### ISSUE TITLE
summarise_each_, mutate_each_ require vars and that all variables be named

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1674]
#1170 plus more

`summarise_each_` and `mutate_each_` require that `vars` must be specified. If one of the variable names is `NA`, it is impossible to successfully specify `vars`. Example below plays out same w/ either function.

``` r
library(dplyr)
x <- frame_data(
  ~colA, ~colB,
  1,   4,
  3,   6
)
# this works
# x %>% summarise_each_(funs(median), c("colA", "colB"))
x %>% summarise_each_(funs(median))
#> Error in colwise_(tbl, funs_(funs), vars): argument "vars" is missing, with no default
names(x)[2] <- NA
x %>% summarise_each_(funs(median), c("colA", NA))
#> Error: All select() inputs must resolve to integer column positions.
#> The following do not:
#> *  NA
```

**Comment by hadley** [comment]
I'd rather fix it upstream, ensuring that you don't have missing values. Is there a specific reason you want these functions to working with missing variable names?

**Comment by jennybc** [comment]
Absolutely not. I don't want the missing variable names, so an upstream fix would be even better. They're coming from something produced by `readr::read_csv()` or `readr::type_convert()`.
