### ISSUE TITLE
crash with filter and summarize with min

### ISSUE THREAD

**Issue by JanSchulz** [hadley/dplyr#1677]
The following code crashes an irkernel (jupyter notebook, uses evaluate in the background to execute the code) and makes the rsession in rstudio take 100% CPU (of one core):

```
library("dplyr")
df <- data.frame(x=c(1, 2), y=c(NA, NA))
df %>% filter(x > 10)
df %>% filter(x > 10) %>% summarize(x_min=min(x) )
```

Windows 7, 64bit, dplyr 0.4.3, R version 3.2.3

**Comment by hadley** [comment]
I now get:

```
> df %>% filter(x > 10) %>% summarize(x_min=min(x) )
  x_min
1   Inf
```
