### ISSUE TITLE
Make SQL version of signif for backends that support it

### ISSUE THREAD

**Issue by momeara** [hadley/dplyr#1681]
Feature request:

make sql versions of `signif`. This might be useful,

`round(x*power(10, sd-1-floor(log(abs(x))))) / power(10, sd-1-floor(log(abs(x))))` where x is your number and sd is significant digits. 

http://stackoverflow.com/questions/35752542/round-to-significant-number-of-digits-in-postgres?noredirect=1#comment59179003_35752542

**Comment by hadley** [comment]
This is out of scope for dplyr - we only translate where there's something existing that's close.
