### ISSUE TITLE
Error in UseMethod("escape") :    no applicable method for 'escape' applied to an object of class "function"

### ISSUE THREAD

**Issue by peterparkerspicklepatch** [hadley/dplyr#1684]
I received a similar error found [here](https://github.com/hadley/dplyr/issues/857) but in the form of `Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"` after `filter(year == 2016, month == 1 | 2)`. I am using an impalaDB with `dplyrimpaladb` and the GitHub version of `dplyr`.

Here is the traceback,
```
24: escape(val, con = con)
23: FUN(X[[i]], ...)
22: vapply(dots(...), escape_expr, character(1))
21: build_sql(x, " ", sql(f), " ", y)
20: function (x) 
    UseMethod("year") == 2016
19: eval(expr, envir, enclos)
18: eval(x, envir = env)
17: FUN(X[[i]], ...)
16: lapply(expr, function(x) {
        if (is.atomic(x)) 
            return(escape(x, con = con))
        env <- sql_env(x, variant, con, window = window)
        eval(x, envir = env)
    })
15: translate_sql_q(expr, tbl = x, env = NULL, ...)
14: translate(x$where)
13: build_query(object)
12: update.tbl_sql(.data, where = c(.data$where, input))
11: update(.data, where = c(.data$where, input))
10: filter_.tbl_sql(.data, .dots = lazyeval::lazy_dots(...))
9: filter_(.data, .dots = lazyeval::lazy_dots(...))
8: filter(., year == 2016, month == 2 | 3)
7: function_list[[i]](value)
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: bbd %>% tbl("sys_level_up") %>% select(level = `_level_s`, 
       time_t, device_token = device_token_s) %>% filter(year == 
       2016, month == 2 | 3) %>% collect() %>% mutate(date = as.Date(as.POSIXct(time_t/1000, 
       origin = "1970-01-01", tz = "UTC"))) %>% group_by(device_token) %>% 
       summarise(last_level = max(level))
```

And the session info,
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sqldf_0.4-10         RSQLite_1.0.0        gsubfn_0.6-6         proto_0.3-10        
 [5] RImpala_0.1.6        devtools_1.10.0      assertthat_0.1       lubridate_1.5.0     
 [9] scales_0.4.0         ggplot2_2.1.0        RJDBC_0.2-5          rJava_0.9-8         
[13] DBI_0.3.1            lazy_1.2-15          lazyeval_0.1.10.9000 dplyrimpaladb_0.0.6 
[17] dplyr_0.4.3.9000    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      magrittr_1.5     munsell_0.4.3    colorspace_1.2-6 R6_2.1.2        
 [6] stringr_1.0.0    plyr_1.8.3       tools_3.2.3      grid_3.2.3       gtable_0.2.0    
[11] pacman_0.3.0     digest_0.6.9     memoise_1.0.0    stringi_1.0-1    chron_2.3-47
```

**Comment by hadley** [comment]
That's an invalid expression: you need `month == 1 | month == 2`

**Comment by peterparkerspicklepatch** [comment]
I still recieve this error when running `sku_dist <- bb %>%
  tbl('_dd') %>%
  select(`_number`, `_g`, `_s`, `_hq`, time_t) %>%
  filter(build_type_n == 1, year == 2016, month > 2, day >= 26) %>%
  collect()`

Traceback
`24: escape(val, con = con)
23: FUN(X[[i]], ...)
22: vapply(dots(...), escape_expr, character(1))
21: build_sql(x, " ", sql(f), " ", y)
20: function (x) 
    UseMethod("year") == 2016
19: eval(expr, envir, enclos)
18: eval(x, envir = env)
17: FUN(X[[i]], ...)
16: lapply(expr, function(x) {
        if (is.atomic(x)) 
            return(escape(x, con = con))
        env <- sql_env(x, variant, con, window = window)
        eval(x, envir = env)
    })
15: translate_sql_q(expr, tbl = x, env = NULL, ...)
14: translate(x$where)
13: build_query(object)
12: update.tbl_sql(.data, where = c(.data$where, input))
11: update(.data, where = c(.data$where, input))
10: filter_.tbl_sql(.data, .dots = lazyeval::lazy_dots(...))
9: filter_(.data, .dots = lazyeval::lazy_dots(...))
8: filter(., build_type_n == 1, year == 2016, month > 2, day >= 
       26)
7: function_list[[i]](value)
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: bb %>% tbl("_dd") %>% select(`_number`, 
       `_g`, `_s`, `_hq`, time_t) %>% 
       filter(build_type_n == 1, year == 2016, month > 2, day >= 
           26) %>% collect()`

**Comment by hadley** [comment]
Please provide a reproducible example - I suspect it's because you have lubridate loaded and one of year, month, or day is not a column in your dataframe.
