### ISSUE TITLE
collapse undoes order

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1693]
I was wondering why order disappears after a `collapse`. From the baseball dplyr examples

```
players$order
[[1]]
playerid
[[2]]
yearid
[[3]]
teamid

collapse(players)$order
NULL
```

The reason to do this is that I was adding some `collapse` calls to chains of mutate, as the backend am I working on doesn't directly support the use of new cols to define new cols. One workaround was to always collapse the result of a mutate. Unfortunately, that removes order which makes using win function on the result impossible (unless one applies a new arrange. Not sure it's a bug, but I am struggling with this. I'd like order to stay the same until I change it explicitly, like any other property of the data. Thanks

**Comment by hadley** [comment]
It's because it's been collapsed to a single opaque (from dplyr's point of view) subquery. I think anything else is out of scope for dplyr (but you could writer a helper to remove the order, collapse, and then restore)

**Comment by piccolbo** [comment]
Thanks for the clarification.
