### ISSUE TITLE
writing into MySQL DB using dplyr without pulling down data into R

### ISSUE THREAD

**Issue by vsagar19** [hadley/dplyr#1694]
Hi,
How can I  write into DB after some data filtering and without pulling data into R. 
Let the table name to be written in database is xyz

`conn= src_mysql(dbname = myDbname, host =  myHost,user = myUsername, password = myPassword, port = myPort)`
`remote<-conn %>% `
  `tbl("database_table_name") %>%` 
  `select(everything()) %>%` 
  `filter(price >= '2000')`
`cached<-compute(remote)`

Thanks in advance!!!
 
`

**Comment by hadley** [comment]
`compute(remote, name = "xyz", temporary = FALSE)`
