### ISSUE TITLE
Is there a typo in the dplyr inner join documentation?

### ISSUE THREAD

**Issue by doveIn** [hadley/dplyr#1699]
The documentation of dplyr's inner join states

> inner_join: return all rows from x where there are matching values in __x__, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned.

Is that bolded x a typo? I thought it was supposed to return all rows in x where there are matching values in y. I'm not really sure what the former means otherwise.

**Comment by hadley** [comment]
All ready fixed in dev
