### ISSUE TITLE
arranging a table with non-existent column crashes R

### ISSUE THREAD

**Issue by ziggystar** [hadley/dplyr#1702]
R crashes with bad_alloc when executing the code below.

## Rant/Feedback
(Supposedly) dplyr keeps crashing my R every 5 minutes, and I found this while hunting a different bug that didn't involve a misspelled column name, but also involving `arrange`. I'm experiencing **a lot** of other crashes, too – not involving `arrange`. 

It would be helpful to have some sort of (more) stable version besides the most recent (semi-stable) version. I love dplyr, but having it crash my session every minute makes it unusable.

## Versions
 - dplyr version `0.4.3`

 - R version

    > R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
    > Platform: x86_64-pc-linux-gnu (64-bit)

### Reproducible example
It is also attached as text file.

```
require(dplyr)

x <- structure(list(method = structure(1:6, .Label = c("pr-top-ref.base.mln", 
                                                  "pr-top-ref.train-0.mln", "pr-top-ref.train-1.mln", "pr-top-ref.train-2.mln", 
                                                  "pr-top-ref.train-3.mln", "pr-top-ref.train-4.mln", "pr-top-ref.train-5.mln", 
                                                  "pr-top-ref.train-6.mln", "pr-top-ref.train-7.mln", "pr-top-ref.train-8.mln", 
                                                  "pr-top-ref.train-9.mln", "ground-truth", "pr-top-ref", "pr-top"
), class = "factor"), surprise.mean = c(0.771258672043512, 0.770618774877413, 
                                        0.775799506161349, 0.769689759312016, 0.767670417106677, 0.774334097220559
)), .Names = c("method", "surprise.mean"), class = c("tbl_df", 
                                                     "data.frame"), row.names = c(NA, -6L))

#this still works
x %>% arrange(desc(surprise.mean))

#this crashes R
x %>% arrange(desc(surprise.meanf))

```

[dplyr-bug-arrange.txt](https://github.com/hadley/dplyr/files/168766/dplyr-bug-arrange.txt)

**Comment by hadley** [comment]
In the dev version this gives me:

```R
> x %>% arrange(desc(surprise.meanf))
Error: object 'surprise.meanf' not found
```
