### ISSUE TITLE
Trying to extract list elements from newly created list in summarise() crashes R

### ISSUE THREAD

**Issue by huftis** [hadley/dplyr#1705]
The following code consistently crashes R:

```
library(dplyr)
d = data_frame(gr=c(1,1,2,2), x=1:4)
d %>%
  group_by(gr) %>%
  summarise(ki=list(t.test(x)$conf.int),
            low=ki[1], high=ki[2])
```

Note that the list have to be created in the same `summarise()` operation to cause the crash. The following works fine (i.e., doesn’t crash R):

```
d2 = d %>%
  group_by(gr) %>%
  summarise(ki=list(t.test(x)$conf.int))
d2 %>% summarise(low=ki[1], high=ki[2])
d2 %>% group_by(gr) %>% summarise(low=ki[1], high=ki[2])
```

(I observe the problem with dplyr 0.4.3 in R 3.2.3 on Windows.)

**Comment by hadley** [comment]
Looks like another hybrid eval bug

**Comment by krlmlr** [comment]
Can replicate with dplyr 0.4.3, but not with 0.5.0.
