### ISSUE TITLE
arrange crashes R

### ISSUE THREAD

**Issue by ziggystar** [hadley/dplyr#1706]
I think this bug is different from #1702, because here there is no typo in the arrange call. And the other bug does not show if the typo is corrected (as demonstrated in the example there).

To reproduce this bug, I had to `save` the object – file `dplyr-bug.data` in archive below.
Then you can execute the R script `dplyr-bug.txt` to crash R on a call to `arrange`.

## Broken object?
If I `dput` the object (instead of `save`ing it), I get an R error (no crash) on reading the `dput` output. This might indicate that the object itself is broken.

### How to create the defective object?

The object is produced within the following code block, before the commented out `arrange`. The result of the pipeline (after `summarise`) is contained in the attached R `save` file `dplyr-bug.data`.

```{r}
activity.surprise %>%
  group_by(method) %>%
  summarise(surprise.mean = mean(surprise), surprise.sd = sd(surprise)) %>%
  #the following arrange crashes
  #arrange(desc(surprise.mean)) %>%
  pandoc.table
```

### Input to pipeline

The input to the pipeline looks like this

```
> str(activity.surprise)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	81838 obs. of  5 variables:
 $ seq.user.type: Factor w/ 4 levels "BC3","MC3","SC3",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ seq.id       : Factor w/ 20 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ time         : num  1 1 1 1 1 1 1 1 1 1 ...
 $ method       : Factor w/ 14 levels "pr-top-ref.base.mln",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ surprise     : num [1, 1] 0.0282 0.029 0.0235 0.0303 0.0335 ...
```

### `dput` of broken object

```
structure(list(method = structure(1:14, .Label = c("pr-top-ref.base.mln", 
"pr-top-ref.train-0.mln", "pr-top-ref.train-1.mln", "pr-top-ref.train-2.mln", 
"pr-top-ref.train-3.mln", "pr-top-ref.train-4.mln", "pr-top-ref.train-5.mln", 
"pr-top-ref.train-6.mln", "pr-top-ref.train-7.mln", "pr-top-ref.train-8.mln", 
"pr-top-ref.train-9.mln", "ground-truth", "pr-top-ref", "pr-top"
), class = "factor"), surprise.mean = structure(c(0.771258672043512, 
0.770618774877413, 0.775799506161349, 0.769689759312016, 0.767670417106677, 
0.774334097220559, 0.770304959883198, 0.769689759312016, 0.769091345657951, 
0.76938843813321, 0.773976997326324, 0, 1.08646172653852, 37.1775041894159
), .Dim = c(1L, 1L)), surprise.sd = structure(c(1.75530246991514, 
1.75245575460632, 1.77418123680801, 1.74821500780028, 1.73845804212238, 
1.76830387585708, 1.75103825265454, 1.74821500780028, 1.74540750230473, 
1.74680928321187, 1.76684397221053, 0, 0.759755149155994, 69.6513791912517
), .Dim = c(1L, 1L))), class = c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -14L), .Names = c("method", "surprise.mean", 
"surprise.sd"))
```

On sourcing this again, you get
> Error in structure(c(0.771258672043512, 0.770618774877413, 0.775799506161349,  : 
>  dims [product 1] do not match the length of object [14]

## Archive containing repex
[dplyr-bug.zip](https://github.com/hadley/dplyr/files/168852/dplyr-bug.zip)

**Comment by hadley** [comment]
I now get:

```R
Error: matrix column with incompatible number of rows (1), expecting : 14
```

**Comment by ziggystar** [comment]
I think that's indeed the problem; even with the dev version of some hours ago it didn't crash R anymore. 

But I think this might be caused by another bug in dplyr, which generates this invalid object.

If you agree that it's a bug in dplyr I can file a ticket with a reproducible example.

## Structure of `activity.surprise`

I think the `num [1,1]` for `surprise` might be the problem. I have no idea what it means. If I inspect the column I see only one value, although I see many values in the output of `str`. The `str` output is what I would expect.

> str(activity.surprise)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	81838 obs. of  6 variables:
 $ seq.user.type: Factor w/ 4 levels "BC3","MC3","SC3",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ seq.id       : Factor w/ 20 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ time         : num  1 1 1 1 1 1 1 1 1 1 ...
 $ method       : Factor w/ 14 levels "pr-top-ref.base.mln",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ value        : Factor w/ 13 levels "DC2","MC2","NONE",..: 7 7 7 7 7 7 7 7 7 7 ...
 $ surprise     : num [1, 1] 0.0282 0.029 0.0235 0.0303 0.0335 ...

## Code that generates it
I get the same results with and w/o the `ungroup`.
```
activity.surprise <- data.perform %>% 
  filter(true >= 1) %>%
  group_by(seq.user.type,seq.id,time,method,value) %>% 
  summarise(surprise = true %*% -log(prob + 1e-100)) %>% ungroup
```

**Comment by ziggystar** [comment]
Uhm, ok I got it. It's a 1x1 matrix as the result of vector multiplication and R didn't convert it into a scalar.
