### ISSUE TITLE
Improve compilation time

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1713]
On my four-core machine, dplyr compiles in just above one minute. Tried precompiled headers, but this doesn't reduce compilation time much.

The compiler state after including `dplyr.h` is roughly 200 MB; ~~this means that it essentially doesn't matter how large a `.cpp` module is. The only thing that can help is to reduce the number of modules by merging some of the smaller ones into larger ones. A amalgamation ("unity build", like sqlite) would build fastest, but the code doesn't support this yet because of inconsistent `using namespace` statements~~.

Current lines per module:

```
    19 strings_addresses.cpp
    20 test.cpp
    27 distinct.cpp
    37 init.cpp
    42 address.cpp
    50 between.cpp
    69 arrange.cpp
    74 group_indices.cpp
    74 matrixToDataFrame.cpp
    76 window.cpp
    80 select.cpp
   115 summarise.cpp
   148 combine_variables.cpp
   283 bind.cpp
   295 filter.cpp
   303 api.cpp
   384 join.cpp
   616 RcppExports.cpp
  2085 dplyr.cpp
```

Compile time per module follows. Not surprising, dplyr.cpp takes the longest time and should probably be even split.

**Comment by hadley** [comment]
I'd think you'd actually want to split the modules into smaller pieces so that incremental builds are faster.

**Comment by krlmlr** [comment]
R never seems to make use of compiled object files when I update from upstream: Each change in `inst/include` triggers a full rebuild. This would be easier if source modules avoided including `<dplyr.h>` but included smaller pieces instead.

That alone won't help much -- Rcpp is a beast with about 140 MB of compiled state already. This has to be processed for each and every source module; this means an overhead of ~5s for each module. Adding modules increases overall build time with (currently) no benefits.

Merging and splitting dplyr.cpp gets me to 40s build time using four threads with `-O2`, less with `-Og`. Not sure you can do much faster in the current state of the code. The following script does almost all of the work; `dplyr.cpp` needs to be split, e.g. at the first definition of the `subset()` function.

```
#!/bin/sh

set -e

git checkout .

sed -i "1,/^$/d;/^using namespace/d;$ s/$/\n/" *.cpp
git checkout api.cpp dplyr.cpp RcppExports.cpp test.cpp matrixToDataFrame.cpp

cat address.cpp strings_addresses.cpp between.cpp >> api.cpp
rm address.cpp strings_addresses.cpp between.cpp

(
  echo
  cat init.cpp
) >> dplyr.cpp
rm init.cpp

(
  echo "#include <dplyr.h>"
  echo
  echo "using namespace Rcpp;"
  echo "using namespace dplyr;"
  echo
  cat select.cpp filter.cpp arrange.cpp summarise.cpp group_indices.cpp distinct.cpp join.cpp window.cpp combine_variables.cpp bind.cpp
) > dataframe.cpp

rm select.cpp filter.cpp arrange.cpp summarise.cpp group_indices.cpp distinct.cpp join.cpp window.cpp combine_variables.cpp bind.cpp
```

**Comment by kevinushey** [comment]
The problem is definitely because of the large size of the dplyr / Rcpp headers, and since each compilation unit requires a full re-parse of all those headers it takes a long time.

I used a similar strategy to @krlmlr in Kmisc to speed up compile time (concatenate all the source files into one monolithic file on build) and it does cut down compilation time dramatically.

Also, to make use of precompiled headers, you need to explicitly add an `-include` flag, e.g.

    -include path/to/Rcpp.h

Did you try that @krlmlr? (You might not be able to do this with `dplyr.h` because of all the `#define`s that get set by `Makevars`)

**Comment by krlmlr** [comment]
I did check .pch usage with the `-H` flag. My most recent timings are ~3s for a parse of Rcpp.h, and ~1.5s for loading it from a precompiled header. Not a dramatic difference to me.

**Comment by hadley** [comment]
Just to confirm my understanding, there's effectively two ways to make compilation faster, right:

1. Put everything in one giant header that only needs to get compiled once

1. Split everything out into much finer pieces so that each .cpp only needs to include exactly what it uses.

**Comment by kevinushey** [comment]
Right, although if you split things out into separate files then you need to make sure to include only what you use. Unfortunately, it's a bit difficult to use Rcpp piecemeal (`Rcpp.h` is the only guaranteed available / stable header)

**Comment by krlmlr** [comment]
1. I have `Sys.setenv(MAKE = "make -k -j 4")` in my `.Rprofile`, this uses at most four parallel processes when compiling code in R packages. The ideal situation here are four .cpp modules with approximately the same workload; one big module would be slower.

2. There's a minimum cost associated with each compilation unit.

Best option would be a few modules grouped by functionality/headers used.

**Comment by krlmlr** [comment]
@kevinushey: Minor catch: It's not only the *size* of the headers (that's what I thought first), it appears to be related also with their *complexity*. Looks like simple classes can be compiled much faster than template magic, and there's plenty of the latter in both Rcpp and dplyr.

**Comment by kevinushey** [comment]
Yeah, that's definitely true -- Rcpp and (I'm guessing) dplyr both make use of template meta-programming techniques, which implies the compiler is executing a lot of code at compile time to figure things out (e.g. with expression templates, type traits, and so on)

**Comment by krlmlr** [comment]
This [SO post](http://stackoverflow.com/a/33683596/946850) (and the other answers) contains a few valuable hints that may be relevant here or for Rcpp. For now, I'm fine with

```
CC := ccache $(CC)
CXX := ccache $(CXX)
```

in my `.R/Makevars`.
