### ISSUE TITLE
dplyr fatal crash when trying arrrange() in small data frame

### ISSUE THREAD

**Issue by montoyah** [hadley/dplyr#1714]
This is only happening  so far with arrange. Other functions, like select(), work normally. The problem started happening just today, I reinstalled most updated version of dplyr but the problem continues. Any help on this matter will be much appreciated.

Thanks in advance,

Oscar.

**Comment by hadley** [comment]
Please provide a reproducible example

**Comment by montoyah** [comment]
Hi Hadley,

I solved the crashing issue by converting the two new columns (group and replicate_number) into factors after strsplit() column group (original), and that fixed the problem. I cannot reproduce the code that cause the crash anymore...Sorry. This is part of my data frame anyway: [sample_data_arrange_crash.pdf](https://github.com/hadley/dplyr/files/174421/sample_data_arrange_crash.pdf)

> str(raw_data)
'data.frame':	168 obs. of  8 variables:
 $ day     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ station : int  407 407 407 435 435 435 535 535 535 407 ...
 $ redox   : Factor w/ 2 levels "aerobic","anaerobic": 1 1 1 1 1 1 1 1 1 2 ...
 $ group   : Factor w/ 13 levels "sterile 1","sterile 2",..: 6 10 12 7 8 11 6 10 13 4 ...
 $ area_co2: num  123.3 46.8 90.2 23 125.5 ...
 $ area_o2 : num  4288 1414 1347 662 971 ...
 $ area_n2 : num  19456 9274 10216 2877 6170 ...
 $ area_ch4: num  111.4 50 108.6 27 80.8 ...

Trying to arrange my data (after spiting) with "arrange(raw_data, day, station, redox, group, replicate_number)" was what caused the crash several times. I hope you still can finding out why the abort session happened with this too loose info. Next time I'll try to be more attentive to make notes of the problem before troubleshooting.

Thanks,

Oscar.
