### ISSUE TITLE
Support for ranges in recode.numeric

### ISSUE THREAD

**Issue by dgromer** [hadley/dplyr#1715]
What do you think about functionality for `recode.numeric` like

```r
recode(x, `c(1, 3, 5)` = "odd", `c(2, 4, 6)` = "even")
recode(x, `1:5` = "small", `6:10` = "large")
recode(x, `. < 2 || . > 8` = NA, .default = x)
```

(For similar function see https://github.com/dgromer/psymisc/blob/master/R/recode.R)

**Comment by hadley** [comment]
I loathe quoting code, so I really don't like this. You also need to automatically impute which comparison function to use (at least `==` vs `%in%`), which seems fragile.

I think these problems are already pretty natural to solve with `case_when()`:

```R
case_when(
  x %in% c(1, 3, 5) ~ "odd",
  x %in% c(2, 4, 6) ~ "even"
)

case_when(
  x < 2 || x > 8 ~ NA,
  TRUE ~ x
)
```
