### ISSUE TITLE
dbSendQuery doesn't act consistently with all drivers; may force full extraction

### ISSUE THREAD

**Issue by msjgriffiths** [hadley/dplyr#1725]
#### Situation

  * Redshift returns *all* results immediately when you invoke `dbSendQuery`. It does not wait for `dbFetch`.
  * Invoking `head` on a `tbl_sql` will invoke `collect`, and thus `dbSendQuery`.
  * Large tables will ... try to return all their rows. If the table is large enough, R will run out of RAM and crash. 
  * This is a breaking change from the previous version of dplyr, which employed a `limit` clause.

#### Story

I'm using `dplyr` to connect to a Postgres-type database (Redshift) and pull everything into a nice, neat report. It's a great experience.

Now, I happened to want a *very* recently added feature (`union_all`), and, since I like to live dangerously, I updated this afternoon :)

However, upon rendering my Rmarkdown document, it hung on `head(tmp_table)`. For a very long time.

After leaving it alone for an hour, I decided to check the running queries table in Redshift. It turns out it was running `select * from tmp_table`. The only problem is that the table has > 12 billion rows. 

#### Workaround

I've just [stolen most of the collect function](https://github.com/hadley/dplyr/blob/ec74316dcfb7a91002d8465d0d548498296946d4/R/tbl-sql.r#L387) and added a `LIMIT` clause manually.

```r
dhead <- function(table, n = 10){
  if (n < 0 | n == Inf){
    n = -1
  }
  query = sprintf("%s LIMIT %s", sql_render(table), n)
  res = dbSendQuery(table$src$con, query) 
  on.exit(dbClearResult(res))
  dbFetch(res, n) %>%
    return
}
```

**Comment by hadley** [comment]
This seems more like a bug with the database driver to me :/

**Comment by msjgriffiths** [comment]
Well, you'd certainly know better than me, since I have basically no knowledge of DBI. My own reading is a little ambiguous - 

https://cran.r-project.org/web/packages/DBI/DBI.pdf

> #### dbSendQuery

> ##### Side Effects

> The statement is submitted for synchronous execution to the server connected through the conn object. The DBMS executes the statement, possibly generating vast amounts of data. Where these data reside is driver-specific: some drivers may choose to leave the output on the server and transfer them piecemeal to R, others may transfer all the data to the client – but not necessarily to the memory that R manages. See the individual drivers’ dbSendQuery method for implementation details.

That implies that `dbSendQuery` is meant to execute the entire query, and not delay execution until a `dbFetch` is issued (and then only execute until nrows is hit).

... but if that's an optimization the driver should be performing, than it's just a matter of forking a `RRedshift` DBI driver off of the `RPostgreSQL` driver that implements the appropriate behavior.

**Comment by mwilliams2921** [comment]
I have the same issue in Greenplum. Thanks for the workaround.

**Comment by hadley** [comment]
@javierluraschi this argues that maybe you are right, and limit should be baked in

**Comment by javierluraschi** [comment]
@hadley We could still keep `LIMIT` turned off for every DBI instance and opt-in for `src_postgres`. I'll be happy to make the change, let me know if you want a PR for this.

**Comment by krlmlr** [comment]
Can head() be implemented as a lazy operation?

**Comment by hadley** [comment]
Oh hmmm, that's a good idea.

**Comment by hhoeflin** [comment]
I aslo had the same issue - with the additional problem that after the workaround above, I wasn't warned of incomplete results anymore. Here an alternative that worked for me

```
collect.tbl_sql <- function (x, ..., n = 1e+05, warn_incomplete = TRUE) {
    
    assert_that(length(n) == 1, n > 0L)
    if (n == Inf) {
        n <- -1
    }
    sql_query <- sql_render(x)
    sql_query <- sprintf("%s LIMIT %s", sql_query, n + 1)
    res <- dbSendQuery(x$src$con, sql_query)
    on.exit(dbClearResult(res))
    out <- dbFetch(res, n)
    out2 <- dbFetch(res, 1)
    if (warn_incomplete) {
        if(nrow(out2) > 0) {
            warning("Did not retrieve complete table in collect. Rerun with n = Inf to ensure all are collected")
        }
    }
    grouped_df(out, groups(x))
}

```

**Comment by hadley** [comment]
This requires rolling back https://github.com/hadley/dplyr/commit/d3731ea9

And then rewriting `head.tbl_sql()` as per https://github.com/hadley/dplyr/commit/52934e70d66fce5f91647832c0b0a43b12d3bce6#diff-7ce7e496e1ebf6a668326daf0c482dcbR82

**Comment by hadley** [comment]
Please try this out and let me know if it fixes the problem.

**Comment by stevenfazzio** [comment]
I'm not OP, but this fixed the problem for me (I'm also using Redshift/Postgres).
