### ISSUE TITLE
Segfault from 'memory not mapped'

### ISSUE THREAD

**Issue by kozross** [hadley/dplyr#1728]
I am getting an issue that appears to be the same as issue #322. Specifically, this happens:

     > library("dplyr")

     Attaching package: ‘dplyr’

     The following objects are masked from ‘package:stats’:

         filter, lag

     The following objects are masked from ‘package:base’:

        intersect, setdiff, setequal, union

    > db <- src_sqlite("survey.db")
    > db
    src:  sqlite 3.8.6 [survey.db]
    tbls: clinics, doctors, metadata, patients, responses, sqlite_sequence
    > md <- tbl(db, "metadata")

     *** caught segfault ***
     address 0x58, cause 'memory not mapped'

    Traceback:
      1: .Call(rsqlite_query_send, con@Id, as.character(statement), bind.data)
      2: sqliteSendQuery(conn, statement)
      3: .local(conn, statement, ...)
      4: DBI::dbSendQuery(con, build_sql("SELECT * FROM ", sql))
      5: DBI::dbSendQuery(con, build_sql("SELECT * FROM ", sql))
      6: db_query_fields.SQLiteConnection(object$src$con, object$from)
     7: db_query_fields(object$src$con, object$from)
     8: update.tbl_sql(tbl)
     9: update(tbl)
    10: tbl_sql("sqlite", src = src, from = from, ...)
    11: tbl.src_sqlite(db, "metadata")
    12: tbl(db, "metadata")

My ``sessionInfo()`` is as follows:

     > sessionInfo()
     R version 3.2.3 (2015-12-10)
     Platform: x86_64-pc-linux-gnu (64-bit)
     Running under: Parabola GNU/Linux-libre

     locale:
      [1] LC_CTYPE=en_NZ.UTF-8       LC_NUMERIC=C              
      [3] LC_TIME=en_NZ.UTF-8        LC_COLLATE=en_NZ.UTF-8    
      [5] LC_MONETARY=en_NZ.UTF-8    LC_MESSAGES=en_NZ.UTF-8   
      [7] LC_PAPER=en_NZ.UTF-8       LC_NAME=C                 
      [9] LC_ADDRESS=C               LC_TELEPHONE=C            
     [11] LC_MEASUREMENT=en_NZ.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
     [1] stats     graphics  grDevices utils     datasets  methods   base     

     other attached packages:
    [1] dplyr_0.4.3

     loaded via a namespace (and not attached):
     [1] magrittr_1.5   R6_2.1.2       assertthat_0.1 parallel_3.2.3 tools_3.2.3   
     [6] DBI_0.3.1      Rcpp_0.12.3

Should I try and build from GitHub via ``devtools`` to resolve this?

**Comment by hadley** [comment]
It actually appears to be a completely different problem. It's likely an RSQLite bug and we'll probably need the database to debug it.

**Comment by krlmlr** [comment]
I can't see RSQLite in the sessionInfo(), and you seem to be using the CRAN version of DBI. Does the issue still occur if you install both from GitHub?

```
devtools::install_github(c("rstats-db/DBI", "rstats-db/RSQLite"))
```

**Comment by kozross** [comment]
@krlmlr When I try that command, I get this:

```
* installing *source* package ‘DBItest’ ...
** R
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘testthat’ 0.11.0 is being loaded, but >= 0.11.0.9000 is required
ERROR: lazy loading failed for package ‘DBItest’
* removing ‘/usr/lib/R/library/DBItest’
Error: Command failed (1)
```

Does that mean I need ``testthat`` from Github as well?

**Comment by krlmlr** [comment]
Need `devtools::install_github(c("hadley/testthat"))` as well.

**Comment by kozross** [comment]
@hadley and @krlmlr : That fixes it. I guess I should stick to ``devtools`` from now on to avoid this kinda thing?

**Comment by krlmlr** [comment]
Actually, DBItest (and hence the development version of testthat) should *not* be needed. It is installed unnecessarily in this case, https://github.com/hadley/devtools/pull/1067 resolves this (CC @jimhester).

Eventually, RSQLite will be updated on CRAN, for now you can use the dev version.

**Comment by kozross** [comment]
Thanks for that! Gonna close this now.
