### ISSUE TITLE
Filter with SQL backend only allows filters with selected columns

### ISSUE THREAD

**Issue by bernardocaldas** [hadley/dplyr#1731]
When I try to filter a data frame with SQL backend, if I try to filter it using a column that hasn't been selected before, I get an error. This appears to be happening because dplyr creates an outer select statement and uses all the filters at that level. At that time, we may not have all the columns.

**Comment by hadley** [comment]
Fixed in dev.

In future, please provide a minimal reproducible example.

**Comment by bernardocaldas** [comment]
@hadley Same thing happened in the last version. Do you want me to provide an example?
