### ISSUE TITLE
foreach package and dplyr don't play well.

### ISSUE THREAD

**Issue by grepinsight** [hadley/dplyr#1732]
When I load `dplyr` along with `foreach`, I can't run foreach command.

```
library(randomForest)
library(foreach)

run_parallel_rf <- function() {
  rf <- foreach(ntree=rep(250, 4), .combine=combine) %do% randomForest(iris[,1:4], factor(as.integer(iris$Species),levels=sort(unique(as.integer(iris$Species)))), ntree=ntree)
  rf
}

run_parallel_rf() #Runs fine

library(dplyr)

run_parallel_rf() # CRASHES.

```
This is the error message I get:

```
Assertion failed!

Program: C:\Program Files\RStudio\bin\x64\rsession.exe
File: d:/Rcompile/CRANpkg/lib/3.2/BH/include/boost/smart_ptr/scoped_ptr.hpp, Line 105

This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
```

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3
```

**Comment by hadley** [comment]
I'd recommend restarting R, and then reinstalling both dplyr and randomForest. The most likely explanation is that they link against different versions of Rcpp.

**Comment by kevinushey** [comment]
Would be good to reinstall all of `BH`, `dplyr` and `foreach` (in that order), just to make sure everyone is linking to the same `BH` as well.

**Comment by grepinsight** [comment]
Thank you for the quick reply. I did follow your suggestions by removing and reinstalling "BH", "dplyr", "foreach", and "randomForest".

It works when I load the library in the following order:

1. library(dplyr)
2. library(randomForest)
3. library(foreach)

But for FYI, it fails with this order

1. library(randomForest)
2. library(dplyr)
3. library(foreach)

**Comment by hadley** [comment]
It works for me, so it's most likely to be something on your computer.

**Comment by gmatasci** [comment]
Thanks for bringing up this issue. Just loading "dplyr" before "foreach" solved the (very annoying) problem for me.
