### ISSUE TITLE
Standard Evaluation “could not find function”

### ISSUE THREAD

**Issue by klmr** [hadley/dplyr#1733]
Standard Evaluation, according to the [NSE vignette][], understands three forms of quoted expressions:

> 1. With a formula, `~ mean(mpg)`.
> 2. With `quote()`, `quote(mean(mpg))`.
> 3. As a string: `"mean(mpg)"`.

It is understood that these three are different, because formulae capture the environment. Nevertheless, I’m puzzled why the following yields different results:

```r
library(dplyr)

mtcars %>% rowwise() %>% summarize_(x = ~prop.test(mpg, disp)$p.value)
mtcars %>% rowwise() %>% summarize_(x = quote(prop.test(mpg, disp)$p.value))
```

I’d expect the same result for both. Instead, I only get the expected result (a `tbl_df` of p-values) for the first statement; for the second statement, I get:

> Error: could not find function "prop.test"

The only reason for this that I can think of is that `prop.test` is defined in `package:stats`, and maybe for some weird reason that package (though attached) isn’t visible from wherever the expression is evaluated). However, this doesn’t seem to be the case, because other functions from within the same package *are* found:

```r
mtcars %>% summarize_(x = ~sd(mpg))
mtcars %>% summarize_(x = quote(sd(mpg)))
```

These two lines yield the same result. What causes the difference in behaviour between the call to `prop.test` and the call to `sd`?

[NSE vignette]: https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html

**Comment by hadley** [comment]
When used with `quote()`, lazyeval sets the env to `baseenv()` to basically force you to use formulas. I now don't think this is a good default, but I'm going to completely replace the NSE/SE system anyway. You can see http://rpubs.com/hadley/lazyeval for my latest (published) thoughts. The big picture is going to stay the same, but the details will change. Goal is to roll out a more consistent, easier to use, and more powerful system across all of my packages by the end of the year.

**Comment by klmr** [comment]
That’s what I was thinking (more or less) but then why does the example with `sd` work?

**Comment by kevinushey** [comment]
I think the `dplyr` hybrid handler takes over and does its own thing for that: https://github.com/hadley/dplyr/blob/a7528c23c495ae288f549fde695b146bf60ab360/src/dplyr.cpp#L398-L436
