### ISSUE TITLE
Window functions not translated to sql correctly after group_by() followed by an aggregation

### ISSUE THREAD

**Issue by Vestaxis** [hadley/dplyr#1739]
In the current master branch of dplyr, window functions include PARTITION BY in the query after a group_by statement followed by an aggregation although they shouldn't. As expected, the aggregation drops the grouping variable but PARTITION BY is still included in the sql statement. 

Since SQlite doesn't support windows function I haven't been able to reproduce this using memdb_frame. 

This works as expected: 
`library(nycflights13)
flights_sqlite <- copy_to(db, flights, temporary = TRUE, indexes = list(
  c("year", "month", "day"), "carrier", "tailnum"))
flights_sqlite %>% group_by(carrier) %>%  mutate(rank = rank(desc(sumdelay))) %>% show_query()
`
```
<SQL>
SELECT "year", "month", "day", "dep_time", "dep_delay", "arr_time", "arr_delay", "carrier", "tailnum", "flight", "origin", "dest", "air_time", "distance", "hour", "minute", rank() OVER (PARTITION BY "carrier" ORDER BY "sumdelay" DESC) AS "rank"
FROM "flights"
```

This pipeline should drop PARTITION BY from the query: 
`flights_sqlite %>% group_by(carrier) %>% summarise(sumdelay = sum(arr_delay)) %>% mutate(rank = rank(desc(sumdelay))) %>% show_query()`
```
<SQL>
SELECT "carrier", "sumdelay", rank() OVER (PARTITION BY  ORDER BY "sumdelay" DESC) AS "rank"
FROM (SELECT "carrier", SUM("arr_delay") AS "sumdelay"
FROM "flights"
GROUP BY "carrier") "pjwhowndgm"
```

If I specify multiply groups the translation to sql works fine: 
`flights_sqlite %>% group_by(carrier, year) %>% summarise(sumdelay = sum(arr_delay)) %>% mutate(rank = rank(desc(sumdelay))) %>% show_query()`
```
<SQL>
SELECT "carrier", "year", "sumdelay", rank() OVER (PARTITION BY "carrier" ORDER BY "sumdelay" DESC) AS "rank"
FROM (SELECT "carrier", "year", SUM("arr_delay") AS "sumdelay"
FROM "flights"
GROUP BY "carrier", "year") "fxffgnvxvt"
```

**Comment by hadley** [comment]
A minimal reprex (using internal functions and no database) is:

```
lazy_frame(g = 1, x = 1) %>% 
  group_by(g) %>% 
  summarise(x = sum(x)) %>% 
  mutate(rank = rank(x)) %>% 
  show_query()
```
