### ISSUE TITLE
Document change in behaviour of as_data_frame()

### ISSUE THREAD

**Issue by aphalo** [hadley/dplyr#1744]
`as_data_frame()` no longer strips derived S3 classes.

The example from 'dplyr' is for version 0.4.3, obviously 'dplyr' 0.4.3.9000 behaves as 'tibble'.
```{r}
> class(photobiology::sun.spct)
[1] "source_spct"  "generic_spct" "tbl_df"       "tbl"          "data.frame"  
> class(dplyr::as_data_frame(photobiology::sun.spct))
[1] "tbl_df"     "tbl"        "data.frame"
> class(tibble::as_data_frame(photobiology::sun.spct))
[1] "source_spct"  "generic_spct" "tbl_df"       "tbl"          "data.frame"  
> 
```
I am unsure about which behaviour is best, however, the one in 'dplyr' 0.4.3 seems more consistent with R:
```{r}
> class(as.data.frame(photobiology::sun.spct))
[1] "data.frame"
```
(I have now updated package 'photobiology' to work correctly with either version of 'dplyr', but this could potentially break other code.)

**Comment by hadley** [comment]
@krlmlr was this deliberate?

**Comment by krlmlr** [comment]
This was introduced pre-tibble, in 9a23e869a02786.

**Comment by hadley** [comment]
I guess the question is whether coercing to a superclass should strip subclasses. I don't think it's obvious which behaviour is correct (and base R should only be a loose guide since it's probably not consistent across functions)

**Comment by kevinushey** [comment]
It should definitely strip those classes.

**Comment by hadley** [comment]
@kevinushey in this case the object is _already_ a subclass of foo, so it should already satisfy those guarantees

**Comment by kevinushey** [comment]
@hadley doh, you're right -- I think I misunderstood the issue and I agree with you. Sorry!

**Comment by krlmlr** [comment]
In C++:

```
class A { virtual void foo(); }; class B : public A { virtual void foo(); };
A* a = new A();
B* b = new B();
a->foo(); // calls A::foo()
b->foo(); // calls B::foo()
((A*)b)->foo(); // calls B::foo()
b->A::foo(); // calls A::foo()
```

The third call would correspond to `as.A()` in R. But the fourth call corresponds to `foo.A()` or `getS3Method("foo", "A")()`. 

According to this analogy, `as.A()` should leave objects of class `B` untouched.
