### ISSUE TITLE
cannot find "median" in `summerise_`

### ISSUE THREAD

**Issue by koaning** [hadley/dplyr#1747]
We can use `summarise_` in those pesky situations in Shiny when we want to select a function to apply to a dataframe. This often works just fine, like below; 

```
ChickWeight %>% 
  group_by(Diet) %>% 
  summarise_("mean(weight)")
```

Here the string `mean(weight)` gets handled appropriately and we get a nice summary back for every `Diet`. The mean works just fine, the median function however gives an odd error; 

```
ChickWeight %>% 
  group_by(Diet) %>% 
  summarise_("median(weight)")
```

This returns a `Error: could not find function "median"` error. The normal `summarise` (without `_`) does work and other aggregation functions seem to work as well. Any idea what might be causing this? 

I also notice that the `summarise_` approach does not seem to work on user defined functions. Is `dplyr` using internal Rcpp functions when it sees `mean`/`var`/`max`/`min`? If thats the case it might need to have `median` added.

**Comment by hadley** [comment]
It's better to do:

```R
ChickWeight %>% 
  group_by(Diet) %>% 
  summarise_(~ median(weight))
```

**Comment by xk-zhou** [comment]
Hi Hadley, after reading [NSE Vignettes](https://cran.r-project.org/web/packages/dplyr/vignettes/nse.html), I agree that ```summarise_(~ median(weight))``` is a better thing to do in general.

However, sometimes people need to put the following in a function 
```summarise_(paste("median(", variable, ")"))``` 
and pass value to ```variable``` from argument; as @koaning pointed out, ```median``` does not work here. 

I would appreciate your thoughts on why this happens, and it would help me better understand ```summarise_()``` function. Thank you.

**Comment by cronacronis** [comment]
@xk-zhou can you make an example? what do you mean by *sometimes people need to put the following in a function *?

**Comment by dgromer** [comment]
@xk-zhou you can construct a formula and pass it to the `.dots` argument:

```r
summarise_(mtcars, .dots = as.formula(paste0("~ median(", "disp", ")")))
```
