### ISSUE TITLE
distinct() does not work without explicit specification of all column names?

### ISSUE THREAD

**Issue by gtumuluri** [hadley/dplyr#1751]
I swear it worked in prior version of the package, but it gives me an error unless I explicitly specify each of the column names in version:

```
packageVersion('dplyr')
[1] ‘0.4.3.9001’

```

Here is a simple reproducible example:
```
df <- data.frame(x = rep(1, 10), y = rep(2, 10))
distinct(df)
Error: No variables selected
distinct(df, everything())
Error: wrong result size (0), expected 10 or 1
distinct(df, x, y)
  x y
1 1 2
```

**Comment by hadley** [comment]
Yes, this changed in the API - see NEWS.md.

**Comment by hadley** [comment]
That might be a mistake though - it's possible the behaviour with no variables specified should be to use all variables (I need to think if that's consistent with grouped vars)

**Comment by gtumuluri** [comment]
Variable list was optional, and doc still says so. I am working around it. Either explicitly specifying all column names or ```distinct_(df, .dots = names(df))```. I did notice some problem with group variables although don't have a reproducible example yet.

**Comment by hadley** [comment]
And this breaks tidyr, so I definitely think I should revert to the previous behaviour where an empty column list computes distinct on all variables.

**Comment by krlmlr** [comment]
I'd be fine if the more explicit `distinct(everything())` worked.

**Comment by janschulz** [comment]
The current versions now takes "no argument = every column" (https://github.com/hadley/dplyr/commit/51b4b3ae4d0eaf51fe305fcc18ef45c3ebc77590). Coming from the python pandas world, I like that :-) (e.g. pandas `df.drop_duplicates()` would use all columns to find duplicates).

Nevertheless: I was also surprised that `distinct(everything())` or better `distinct(starts_with("PREFIX_"))` doesn't work...

**Comment by hadley** [comment]
@janschulz That's because `distinct()` (for better or worse), has `mutate()` semantics so you can do `distinct(df, diff = abs(x - y))`
