### ISSUE TITLE
Implement as_data_frame.tbl() and as.data.frame.tbl()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1752]
- [ ] forwarded to collect() + consider deprecating collect()
- [ ] to throw an error asking about explicit collect()

Other data.frame-like accessors like [ and [[ should perhaps throw an error, too.

This can't be in the tibble package, because the collect() method isn't defined there.

**Comment by hadley** [comment]
I much prefer `collect()` (even though it does the same thing), because it makes it more clear why you are calling it (in the same way it's useful to have both `identity()` and `force()` even though they do the same thing)

**Comment by krlmlr** [comment]
Okay to forward as_data_frame() to collect() then?

**Comment by hadley** [comment]
I think so

**Comment by krlmlr** [comment]
- Default to n=Inf? -> Depends on if interrupt checking is done properly, or if we have a progress bar

**Comment by hadley** [comment]
Want to do a PR for this?

**Comment by krlmlr** [comment]
as_data_frame.tbl() will be forwarded to as.data.frame.tbl() by hadley/tibble#71, I think -- this should be explicitly tested in dplyr, which I'll do once the tests pass again on Travis.

How about moving the logic for chunked fetches to a separate package/module, e.g. https://github.com/krlmlr/pumpr?
