### ISSUE TITLE
FR: compute() should store (and make available) the actual number of rows

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1758]
~~Accessible from DBI with dbGetRowsAffected().~~ dbGetRowsAffected() returns 1 for RSQLite. Could count rows in newly created table, though.

**Comment by hadley** [comment]
I think  we should do this in the same place where we cache variable names, i.e. `op_base_remote()`. But you would only cache in the case where `x` is an identifier, not arbitrary sql.  Would require extend `op_base` class with an `nrows()` field and then exposing that number (where available) in `dim.tbl_sql()`.

**Comment by krlmlr** [comment]
User tables can easily change, so showing a (wrong) row number here may be misleading. It still might be reasonably safe to assume that temporary tables created by compute() are immutable.

**Comment by hadley** [comment]
Ah yeah - I think this just makes it too special purpose.
