### ISSUE TITLE
Consider sql alias functionality

### ISSUE THREAD

**Issue by trinker** [hadley/dplyr#1759]
It might be nice to have the ability to read a data frame in and assign it an alias like SQL.  Just a random thought and quick mock up.  If this is not useful or in the package's philosophy feel free to close:

```
alias <- function(.data, ...){
    makeActiveBinding(..., function(){ .data}, .GlobalEnv) 
    .data
}

mtcars %>%
    alias('mt') 

mt
```

This makes the most sense for cases when a data set has been read in and the object name can not be specified by the user.  This happens when reading in a .RData file with `load` or working with data sets from an add on package.

**Comment by hadley** [comment]
There's no advantage to this over simply doing `mt <- mtcars`

**Comment by trinker** [comment]
Gotcha.  Thanks for the reply.

Can you help me with my thinking?  I thought if you do `mt <- mtcars` there is a pointer from `mt` to `mtcars` but if you alter `mt` then there was now a copy of `mt` and `mtcars` in memory.  But I thought with `makeActiveBinding` there was just one copy, both are the same object in the way you are Hadley to some but Dr. Wickham to others but the same person.  

I was hoping for large objects these could be a way to reduce clutter.  Sounds like this is not true.  I have read: http://adv-r.had.co.nz/Environments.html on `makeActiveBinding` but it seems I am not getting it.

Also it appears you can't alter mt directly:

```

**Comment by hadley** [comment]
R always copies on modify, regardless of how you create the binding. And as you've noticed, if you use active bindings, you'll need to jump through hoops in order to support modification.

You can not (i.e. should not) try to have two names that can be used interchangeably for the same object.

**Comment by trinker** [comment]
Thanks I appreciate the insight.
