### ISSUE TITLE
Need methods package on the search path

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1760]
```
> Rscript -e "dplyr::memdb_frame(a=1)"
Error in UseMethod("db_has_table") : 
  no applicable method for 'db_has_table' applied to an object of class "SQLiteConnection"
Calls: <Anonymous> ... copy_to -> copy_to.src_sql -> isTRUE -> db_has_table
5: db_has_table(dest$con, name)
4: isTRUE(db_has_table(dest$con, name)) at tbl-sql.r#334
3: copy_to.src_sql(src_memdb(), data_frame(...), name = .name) at copy-to.r#14
2: copy_to(src_memdb(), data_frame(...), name = .name) at src-sqlite.r#135
1: dplyr::memdb_frame(a = 1)
> Rscript -e "library(methods); dplyr::memdb_frame(a=1)"
Source:   query [?? x 1]
Database: sqlite 3.11.1 [:memory:]

      a
  <dbl>
1     1
```

Importing all symbols from `methods` in the `NAMESPACE` does **not** seem to change this behavior.

**Comment by hadley** [comment]
This came up with another package I was debugging in person - I could've sworn this used to work. Is it a regression in R?

**Comment by krlmlr** [comment]
I'll bisect R later today.

**Comment by krlmlr** [comment]
Looks like this particular problem is not a regression with R. I tried trunk~1000 (mid-August last year), with the same symptoms. Now trying trunk~3000 (from 2014), will report here if anything changes.

This will be a *lot* of fun to track down :-o

I can replicate in a similar setting when implementing an S3 method for class "Matrix"; it is also not dispatched for Matrix::Matrix() (which has class "lsyMatrix"):

```
#' @export
test <- function(x) UseMethod("test", x)

#' @export
test.Matrix <- function(x) "Hi!"
```

**Comment by kevinushey** [comment]
Why not just add `methods` to the `Depends:` field?

**Comment by krlmlr** [comment]
Will this fix the example where dplyr is loaded not attached?

**Comment by kevinushey** [comment]
Ah, you're right :/ It would need to be more aggressive, e.g. call `library(methods)` in `.onLoad()`.

FWIW, `Rscript` is weird compared to e.g. `R -e` in that it explicitly does not attach `methods`, but I'm guessing you've bumped into this before as well?

**Comment by krlmlr** [comment]
Yes, even [asked on SO](http://stackoverflow.com/q/19680462/946850)  a couple of years ago ;-)

A workaround would be to up the affected methods to S4 generics. Still, I'm curious why the current code doesn't work, even when all of "methods" is imported into the NAMESPACE.

**Comment by krlmlr** [comment]
After adding this for db_has_table() and importing "methods", I'm getting an error about another method:

```
#' @export
setGeneric("db_has_table",
           def = function(con, ...) standardGeneric("db_has_table")
)

#' @export
setMethod("db_has_table", signature("DBIConnection"),
          function(con, table) dbExistsTable(con, table))
```

In the [C code for UseMethod](https://github.com/wch/r-source/blob/4bb73f54081e00b65f2b9e0c404f89b00d4f1cb7/src/main/objects.c#L342-L475), there are too many uses of R_GlobalEnv for my taste, but I haven't investigated further.

**Comment by krlmlr** [comment]
It works flawlessly if `methods::extends` is copied into the global environment:

```
Rscript -e "extends <- methods::extends; dplyr::memdb_frame(a = 1)"
```

But it also works if `extends` is assigned an arbitrary value:

```
Rscript -e "extends <- 42; dplyr::memdb_frame(a = 1)"
```

To me, it looks like (at least) [this code in R](https://github.com/wch/r-source/blame/780021752eb83a71e2198019acf069ba8741103b/src/main/attrib.c#L655-L656) is responsible for this behavior. Weird...

**Comment by kevinushey** [comment]
It sounds like it's worth reporting to R-devel, or filing a bug -- likely that sanity check could just check that `methods` is within the set of loaded namespaces?

**Comment by krlmlr** [comment]
Done: https://stat.ethz.ch/pipermail/r-devel/2016-April/072592.html

**Comment by krlmlr** [comment]
Should be fixed upstream eventually.
