### ISSUE TITLE
This code produces fatal errors instead of errors

### ISSUE THREAD

**Issue by estebanmend** [hadley/dplyr#1761]
I ran this code. While I would expect this to produce an error it produces a fatal error and forces RStudio to restart the session.
```
library(dplyr)
x <- data.frame(a = 1:10, b = rep(c("a", "b"), each = 5), stringsAsFactors = FALSE)
x <- group_by(x, b)
```
I made a mistake while writing and hitted enter before writing the arguments in the function `first`. This produced a fatal error. As I later checked, any of these lines produces fatal errors:
```
mutate(x, id = nth)
mutate(x, id = first)
mutate(x, id = last)
```
It's important to mention that the fatal errors are produced if x _is_ grouped. Normal errors are thrown if it's not.

- R version: 3.2.4 Revised
- `dplyr` version: 0.4.3

**Comment by hadley** [comment]
Fixed the dev version
