### ISSUE TITLE
FR: time aware mutate

### ISSUE THREAD

**Issue by sabraham** [hadley/dplyr#1764]
I would love to see a flavor of `mutate` that only allows mutation within a time window. For example, for a 2 time unit tolerance

```
foo <- data.frame(time=c(as.Date("2016-01-01"), as.Date("2016-01-01"), as.Date("2016-01-02"), as.Date("2016-01-07")),
                  vals=c(1,2,3,4))

foo %>% tmutate(time, 2, tvals=sum(vals))
```

would give

```
        time vals tvals
1 2016-01-01    1     3
2 2016-01-01    2     3
3 2016-01-02    3     6
4 2016-01-07    4     4
```

**Comment by mebaran** [comment]
I don't think a new verb for mutate is necessary.  For my work, it would be incredibly helpful if there were a version of lead and lag that was time / date aware.

**Comment by sabraham** [comment]
This is actually a `summarize` over a fixed-time window. A better verb would be `summarize_window`.

**Comment by hadley** [comment]
It's actually a variation on a window function.

**Comment by hadley** [comment]
This is unlikely to happen in the short term, but you might be able to use RcppRoll instead.
