### ISSUE TITLE
recode() improvements

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#1767]
##### Create factors

`recode_factor()` would be handy to create factors with levels ordered as they appear in the recode call.

```{r}
recode_factor <- function (.x, ..., .default = NULL, .missing = NULL) {
  levels <- c(...)
  recoded <- recode(.x, ..., .default = .default, .missing = .missing)
  factor(recoded, levels)
}
```

##### Pronoun

Do we need a pronoun for `.x`? Would be useful for default values when mapping over the columns of a data frame.

```{r}
df %>% dmap(recode, `99` = NA_real_, .default = .x)
```

##### `labelled` method

Alias for `recode.numeric()`? Or would it make sense to have a default method that dispatches on vector type?

**Comment by hadley** [comment]
Want to do a PR for `recode_factor()`?

Instead of a pronoun, maybe the default value for `.default` should be an NA, and then `NULL` would mean use instead? Or is there another sentinel value that would make sense?

I think it's reasonable for haven to define `recode.numeric()`. I'm not a huge fan of implementing special dispatch rules.

**Comment by lionel-** [comment]
> Want to do a PR for recode_factor()?

yup I'll do it tomorrow.

> maybe the default value for .default should be an NA, and then NULL would mean use instead?

I like this as well. Which one do you prefer for a PR?

**Comment by hadley** [comment]
I think it's reasonable for `NULL` to mean use `.x` as default

**Comment by hadley** [comment]
And maybe that should be the default behaviour? It seems reasonable that recode leaves unspecified values the same by default.

**Comment by lionel-** [comment]
I think so too. Will change that as well in the forthcoming PR

**Comment by GarciaRios** [comment]
`recode`  is great! it nicely recodes from character to numeric...So this works:

```
x <- c("a", "b", "c")
y <- recode(x, a = 1, b = 2, c= 3)
y 
```
But  it won't work with factors even using `recode_factor`

```
xf <- factor(c("a", "b", "c"))
yf <- recode(xf, a = 1, b = 2, c= 3)
Error: `a` has type 'double' not 'character'

yf <- recode_factor(xf, a = 1, b = 2, c= 3)
Error: `a` has type 'double' not 'character'
```


You have to treat it as character and use recode_factor so that it goes back to factor. Seems pretty verbose

```
recode_factor(as.character(xf), a = 1, b = 2, c= 3)
[1] 1 2 3
Levels: 1 2 3
```
