### ISSUE TITLE
SQLite type conversion on first element when pulling data to R

### ISSUE THREAD

**Issue by Zsedo** [hadley/dplyr#1771]
When pulling data from sqlite database to R, it seems to decide the column class based on the first element. This means if I have a decimal(18,4) type on a column, but the first element is 18, then it will convert to integer.

Example:
So in the sqlite database I have the following column:
4|Low|decimal (18, 4)|0||0

The first 5 rows are:
sqlite> SELECT Low FROM daily LIMIT 5;
18
22.5
24.55
24.1301
24.38

Now pulling this into R, we get the following result:
tbl(db,sql("SELECT Low FROM daily LIMIT 5"))
Low
1  18
2  22
3  24
4  24
5  24

If we offset the first row we get the expected numeric dbl class:
tbl(db,sql("SELECT Low FROM daily LIMIT 5 OFFSET 1"))

Low
1 22.5000
2 24.5500
3 24.1301
4 24.3800
5 24.0600

Is this intended? If so, what is the best way to prevent this?

EDIT: As a workaround, we can multiply the column by 1.0:
con %>% tbl(sql("SELECT Low\*1.0 FROM daily"))
Low*1.0
(dbl)
1  18.0000
2  22.5000
3  24.5500
4  24.1301
5  24.3800

Still, maybe having a way of forcing the table column types when pulling to R would be a preferred way of doing this.

**Comment by hadley** [comment]
This is a RSQLite issue - see https://github.com/rstats-db/RSQLite/issues/74
