### ISSUE TITLE
Convert tbl_cube to table

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1775]
I'm using tbl_cube as intermediate step in the conversion of a three-dimensional tidy data frame to an ftable. (The value is of type character, xtabs() and table() don't seem to work.) I'm missing an obvious way to convert a measure of a cube to a table.

I know I can access the measures via `cube$mets`, but I still need to set the dimnames. The code below works for me, how about adding it to dplyr:

```
as_table <- function(x, measure = 1L) {
  ret <- x$mets[[measure]]
  dimnames(ret) <- x$dims
  ret
}
```

**Comment by krlmlr** [comment]
as.table()

**Comment by hadley** [comment]
This feels like it should be `as.table.tbl_cube`
