### ISSUE TITLE
Can not create a reference table using  the function tbl() in deployer

### ISSUE THREAD

**Issue by DSHossein** [hadley/dplyr#1777]
I have established a successful connection to a database when I'm trying to create a table reference by using the functiontbl(). Here's the code which I used:

 myredshiftconn<-src_postgres('nexus' , 
                             host = 'xxxxxxx.yyyyy-1.redshift.amazonaws.com',
                             port=5439,
                             user="xxxx",
                             password="yyyyy")
Means that the connection establishes successfully.

However, after running the following code to create a table refrence another error occurs:

succesful_sales=tbl(myredshiftconn,"x_succesful_sales")

1.Here's error:
Error in postgresqlExecStatement(conn, statement, ...) : 
RS-DBI driver: (could not Retrieve the result : ERROR:  relation "x_succesful_sales" does not exist

tried 
 myredshiftconn2<-src_postgres('nexus' , 
                             host = 'xxxxxxx.yyyyy-1.redshift.amazonaws.com',
                             port=5439,
                             user="xxxx",
                             password="yyyyy")options = "-c search_path=myschema")

but still the same error.

even tried

 my_tbl = tbl(myredshiftconn2, dplyr::sql('SELECT * FROM myschema.x_succesful_sales'))

but this time i get following error:

2.Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  permission denied for schema myschema
)

I was wondering if you could give me some hints about the reasons of errors mainly first one(

**Comment by hadley** [comment]
It suggests that the table doesn't exist?  I'd recommend asking for help on stackoverflow or in the manipulatr mailing list, not in the github issues (since as you see it might be a while before you get a response here).
