### ISSUE TITLE
combine() result varies by input lengths

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1780]
I get different results from `combine()` depending on the lengths of the elements inside the input list:

``` r
library(dplyr)
yes <- list(alpha = letters[1:3], omega = letters[25:26])
combine(yes)
#> [1] "a" "b" "c" "y" "z"
no <- list(alpha = letters[1:3], omega = letters[24:26])
combine(no)
#> [[1]]
#> [1] "a" "b" "c"
#> 
#> [[2]]
#> [1] "x" "y" "z"
```

which I found because sometimes I can't unnest things with tidyr:

``` r
library(tidyr)
x <- c(alpha = "a.b.c", omega = "x.y.z")
data_frame(x) %>% 
  mutate(letters = strsplit(x, "\\.")) %>% 
  unnest(letters)
#> Error: incompatible number of rows (2, expecting 6)

x <- c(alpha = "a.b.c", omega = "y.z")
data_frame(x) %>% 
  mutate(letters = strsplit(x, "\\.")) %>% 
  unnest(letters)
#> Source: local data frame [5 x 2]
#> 
#>       x letters
#>   <chr>   <chr>
#> 1 a.b.c       a
#> 2 a.b.c       b
#> 3 a.b.c       c
#> 4   y.z       y
#> 5   y.z       z
```

*UPDATE: I should be concrete about the numerology of failure: AFAICT `combine()` is a no-op when the list contains atomic vectors, all of length `n`, but works as you'd expect as long as vector length varies.*

**Comment by romainfrancois** [comment]
@hadley I think it is related to `list_or_dots`: 

```
> combine
function(...) {
  x <- list_or_dots(...)
  combine_all(x)
}
<environment: namespace:dplyr>
>
> combine_all(yes)
[1] "a" "b" "c" "y" "z"
> combine_all(no)
[1] "a" "b" "c" "x" "y" "z"
```

**Comment by romainfrancois** [comment]
Perhaps the internal code should hunt down until it gets something that can be combined : 

```
> combine_all(list(yes))
[[1]]
[1] "a" "b" "c"

[[2]]
[1] "y" "z"
```

**Comment by jennybc** [comment]
Names also matter. `combine()` works just fine when the lengths are equal, as long as at least one element is not named. Bottom line: it's very easy to get on the wrong side of [is_data_list()](https://github.com/hadley/dplyr/blob/bd372a4d625b225a40354a9a091b9185c7736dae/R/bind.r#L110).

``` r
library(dplyr)
no          <- list(alpha = letters[1:3], omega = letters[24:26])
yes_no_name <- list(alpha = letters[1:3],         letters[24:26])
yes_diff_n  <- list(alpha = letters[1:3], omega = letters[25:26])
combine(no)
#> [[1]]
#> [1] "a" "b" "c"
#> 
#> [[2]]
#> [1] "x" "y" "z"
combine(yes_no_name)
#> [1] "a" "b" "c" "x" "y" "z"
combine(yes_diff_n)
#> [1] "a" "b" "c" "y" "z"
```

**Comment by hadley** [comment]
Is this new behaviour in the dev version or has it always been this way?

**Comment by jennybc** [comment]
If you're asking me, I don't know. I only noticed because I have more list-columns now (not necessarily created with `nest()`) and sometimes this prevents `unnest()`ing.

**Comment by hadley** [comment]
Ugh I have no idea what I was thinking with `is_data_list()`. It nows seems like a baaaaad idea.

Maybe it only (marginally) makes sense for `bind_rows()` and `bind_cols()` (pending #1676), and I can just drop it for `combine()`?
