### ISSUE TITLE
FR: Optional "hard" check that join operations are explicit

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1783]
Currently, a message is given. I'd like to suggest a custom condition instead, or perhaps a warning. Alternatively, dplyr could isolate the code that gives this specific message/warning into a separate function, which then could be trace()'d.

Fixing the join operation could be made easier, too:

```
Joining, by = c("col1", "col2", "col3")
```

**Comment by krlmlr** [comment]
message() can be traced already. Just change the wording of the join notification.

**Comment by krlmlr** [comment]
Similar: #1791.

**Comment by hadley** [comment]
I'm happy with the current convention of emitting messages when computing non-trivial default values.

I'd happily review a PR that gave an error message that was easier to copy and paste.
