### ISSUE TITLE
Filter is slower with multiple rules at once vs multiple filter statements

### ISSUE THREAD

**Issue by zross** [hadley/dplyr#1788]
This may be a common and well known behavior but I find that a filter with multiple rules can be much slower than several filters each with one rule. 

In this toy example the multi-filter version is twice as fast. In most cases I imagine this is not an issue since it would be fast enough. In a big Shiny app online, though, I was finding that if I did couple of filters I could get the speed down substantially (10x). 

```r
dat<-data.frame(country = sample(LETTERS, 30000000, replace=TRUE), 
                country2 = sample(LETTERS, 30000000, replace=TRUE),
              data = rnorm(30000000))

ptm <- proc.time()[3]
x <- filter(dat, country=="A")
x <- filter(x, country2=="B")
proc.time()[3]-ptm
# 2.28

ptm <- proc.time()[3]
x <- filter(dat, country=="A",  country=="B")
proc.time()[3]-ptm
#4.65
```

**Comment by hadley** [comment]
Unfortunately we don't have the resources to tackle performance issues like this at the moment.
