### ISSUE TITLE
RScript Postgresql

### ISSUE THREAD

**Issue by athompson1991** [hadley/dplyr#1790]
# Description

I have a script that takes credentials, reads a query from a .sql file, then queries my database. It works in RStudio but produces this error when run from a terminal with RScript:

```
Error in UseMethod("sql_subquery") :
  no applicable method for 'sql_subquery' applied to an object of class "PostgreSQLConnection"
Calls: <Anonymous> -> tbl.src_postgres -> tbl_sql -> sql_subquery
Execution halted
```

I can't find anything online and it looks like it might be a package specific error.

# Reproducible Example

```
library(dplyr)
library(xts)
library(ggplot2)

public_rs <- src_postgres(  
                             "db_name"
                            ,host = "hostname"
                            ,port = 8192
                            ,user = "alex"
                            ,password = "my_password"
                            ,options = "-c search_path=public")

sql_query <- paste(readLines('hc_query.sql'), collapse = '\n')
my_data <- tbl(public_rs, sql(sql_query))
```

In terminal,
```
Rscript hc_grouping.R
```

**Comment by kevinushey** [comment]
This is an issue with `Rscript` + the `methods` package not being loaded.

A simple workaround is to just use `R -f hc_grouping.R` instead, or force a load of the `methods` package. See https://github.com/hadley/dplyr/issues/1760 for some more details.

**Comment by athompson1991** [comment]
Thanks a lot Kevin, much appreciated.
