### ISSUE TITLE
select_vars_ breaks when var name contains comma

### ISSUE THREAD

**Issue by holstius** [hadley/dplyr#1793]
`parse(text = x)` is where the failure occurs. (Try `parse(text = "1,3")` and you'll get `Error in parse(text = x) : <text>:1:2: unexpected ','`.)

So this fails: 

    df <- data.frame(`1,3-Butadiene` = 0.3, `Benzene` = 0.1, check.names = FALSE)
    select_vars_(names(df), vars = "Benzene")

You might think people never use punctuation in column names ... but they do. :-)

**Comment by krlmlr** [comment]
I think the syntax is `select_vars_(vars = names(df), "Benzene")` .
