### ISSUE TITLE
Consider adding a drop_na verb

### ISSUE THREAD

**Issue by janschulz** [hadley/dplyr#1797]
pandas has the [pandas.DataFrame.dropna()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html) which lets you drop rows which have NAs in it but also let you specify subset of columns (-> `subset`) to be looked at for NAs.

A similar dplyr verb would be 

```R
drop_na <- function(data, ...){
    if (missing(...)){
        f = complete.cases(data)
    } else {
        f <- complete.cases(select_(data, .dots = lazyeval::lazy_dots(...)))
    }
    filter(data, f)
}
```

Examples: 
```R
> df <- data.frame(a=c(1,2,3,4,NA), b=c(NA,1,2,3,4), ac=c(1,2,NA,3,4))
> df %>% drop_na(a,b)
  a b ac
1 2 1  2
2 3 2 NA
3 4 3  3
> df %>% drop_na(starts_with("a"))
  a  b ac
1 1 NA  1
2 2  1  2
3 4  3  3
> df %>% drop_na()
  a b ac
1 2 1  2
2 4 3  3
```

I can clean the above up and submit a PR if such a verb would be considered.

**Comment by krlmlr** [comment]
Maybe a more generic filter_each() verb would also be useful?

**Comment by janschulz** [comment]
What I'm not so sure about is the general way to treat "empty variable lists": eg. distinct will error when it doesn't get variable names (at least if I interprete the tests in https://github.com/hadley/dplyr/commit/b3179f9a1c22f67519d37fdf95cf8c1914481add right), but the above would treat an empty list as "look at all variables" (similar to the way pandas does it both with `df.dropna()` and `df.drop_duplicates()`). Someone with a better understanding of the API goals should have a look at this... :-)

**Comment by krlmlr** [comment]
The _each() functions require a variable list; I think drop_na() and filter_each() should raise an error (as should distinct(), #1751).

**Comment by hadley** [comment]
This feels more like a tidyr verb to me.
