### ISSUE TITLE
dplyr GPF case

### ISSUE THREAD

**Issue by smckinney2718** [hadley/dplyr#1798]
```R
foo <- data.frame(a = letters[c(1,2)])
bar <- tbl_df(foo)
unlist(distinct(bar[, "a"][bar[, "a"]!=""]))
```

**Comment by hadley** [comment]
Looks like this is actually a tibble issue.

**Comment by krlmlr** [comment]
@smckinney2718: Note that `bar["a"]` and `bar[, "a"]` still return a data frame, use `bar[["a"]]` to return an atomic vector.

Corrupt data frames may come from elsewhere. It would be good if all verbs checked consistency of the input:

- Do all columns have the same length?
- Is the row.names attribute consistent?

I remember seeing something along these lines in the code, but I'm not sure. At the very least the check doesn't seem to be active for distinct().
