### ISSUE TITLE
Performance suffers when comparing to double

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1799]
Here is the issue in a nutshell: Adding `L` in the second query (i.e., making the value an integer) allows PostgreSQL to use the index. Omitting it (so it gets passed as a numeric/floating point) makes performance just awful. (This is really a PostgreSQL issue that pops up when running from `dplyr` rather than an issue with `dplyr` per se.)

```
> dsf %>% 
+     filter(permno==21793) %>%
+     select(date, ret) %>%
+     explain()
<SQL>
SELECT "date" AS "date", "ret" AS "ret"
FROM (SELECT * FROM crsp.dsf) AS "zzz12"
WHERE "permno" = 21793.0


<PLAN>
Seq Scan on dsf  (cost=0.00..3281261.04 rows=443932 width=12)
  Filter: ((permno)::numeric = 21793.0)
> dsf %>% 
+     filter(permno==21793L) %>%
+     select(date, ret) %>%
+     explain()
<SQL>
SELECT "date" AS "date", "ret" AS "ret"
FROM (SELECT * FROM crsp.dsf) AS "zzz12"
WHERE "permno" = 21793


<PLAN>
Index Scan using dsf_permno_idx on dsf  (cost=0.57..323.47 rows=6280 width=12)
  Index Cond: (permno = 21793)
```

I'm not sure how this should be handled. Should the documentation point this out and encourage use of `L` when the columns being considered are integers? Or should something more automatic take place?

It is interesting to note that in SQL, the `WHERE` clause is simply `WHERE "permno" = 21793`, so this might be a "gotcha" for people naively translating the SQL to `filter(permno==21793)`.

**Comment by krlmlr** [comment]
Is it always safe to omit the ".0" in the generated SQL if the number is in fact an integer?

**Comment by hadley** [comment]
Yeah, that's how integers are defined in SQL. It's important to translate floating point "integers" as currently done otherwise when you do `x / 2` you get integer division.

**Comment by krlmlr** [comment]
I'd argue that this could also be fixed by implementing division differently.

**Comment by hadley** [comment]
I'd just rather not paper over this difference - I'm worried that in the long-run it will cause more problems than it solves.

**Comment by iangow** [comment]
Looking [here](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html) under **SQL Translation**, I see:
```
# R and SQL have different defaults for integers vs reals.
# In R, 1 is a real, and 1L is an integer
# In SQL, 1 is an integer, and 1.0 is a real
translate_sql(1)
#> <SQL> 1.0
translate_sql(1L)
#> <SQL> 1
```

I guess this is a bit of an edge case in the sense that if `permno` (in my query above) is floating point, then PostgreSQL (don't know about "SQL") will coerce the right-hand side accordingly:

```
crsp=# SELECT 1.0=1;
 ?column? 
----------
 t
(1 row)
```

But if `permno` is an integer type and I ask `WHERE permno=1.0`, I guess the LHS gets coerced to floating point, hence the performance hit.

So it might be "safe" in `where` to generate `WHERE permno=x` without ".0" if `x=as.integer(x)`.

But it's obviously easier just to be aware of this issue and make sure I'm using integers in R before asking `where`.

**Comment by krlmlr** [comment]
@hadley: Forcing literals to numbers solves only part of the problem:

```
> memdb_frame(a = 5L, b = 2L) %>% mutate(c = a / b)
Source:   query [?? x 3]
Database: sqlite 3.8.6 [:memory:]

       a     b     c
   <int> <int> <int>
1      5     2     2
```

@iangow: To me. it looks like PostgreSQL could handle this better. Perhaps submit to the PostgreSQL folks? What DB version are you using?

**Comment by iangow** [comment]
@krlmlr: I guess you have in mind that `memdb_frame(a = 5L, b = 2L) %>% mutate(c = a / b)` would give a different result.

Basically the generated SQL asks `permno = 1.0`, so I think PostgreSQL has to assume that `.0` means I want to compare as floating-point. I use PostgreSQL 9.5.2.

**Comment by iangow** [comment]
Sorry, I copied the wrong code: `memdb_frame(a = 5L, b = 2L) %>% collect() %>% mutate(c = a / b)` gives a different result.

**Comment by iangow** [comment]
But the first result is SQL standard, so I guess users just need to be aware that the "same" question gets different answers according to where it's asked.

```
2009-Mac-Pro:~ igow$ psql
psql (9.5.2)
Type "help" for help.

crsp=# SELECT 5/2 AS c;
 c 
---
 2
(1 row)
```

**Comment by iangow** [comment]
@hadley @krlmlr 

Alternatively, perhaps "/" should get translated so that it has the same meaning in both places. Specifically, R's `/` should get translated to something with the same effect in SQL. If I mean to get truncated division (i.e., use the specific SQL meaning), I could use `%/%`):

```
> pg <- src_postgres()
> stuff <- tbl(pg, sql("SELECT 5 AS a, 2 AS b"))
> stuff
Source: postgres 9.5.2 [igow@localhost:5432/crsp]
From: <derived table> [?? x 2]

       a     b
   (int) (int)
1      5     2
..   ...   ...
> stuff %>% mutate(c = a %/% b)
Source: postgres 9.5.2 [igow@localhost:5432/crsp]
From: <derived table> [?? x 3]

       a     b     c
   (int) (int) (int)
1      5     2     2
..   ...   ...   ...
```

**Comment by hadley** [comment]
Hmmm, that's not a bad idea, but what should it get translated to?

**Comment by iangow** [comment]
Alas, I can see [no operator in PostgreSQL](http://www.postgresql.org/docs/current/static/functions-math.html) that would do this.

Translating `/` as `%::float /%` works (in *this* case, but is PostgreSQL-specific I believe):

```
stuff %>% mutate(c = a %::float /% b)
```

**Comment by iangow** [comment]
This (`%* 1.0 /%`) might be more universal:
```
> stuff %>% mutate(c = a %* 1.0 /% b)
Source: postgres 9.5.2 [igow@localhost:5432/crsp]
From: <derived table> [?? x 3]

       a     b     c
   (int) (int) (dbl)
1      5     2   2.5
..   ...   ...   ...
```

**Comment by krlmlr** [comment]
For the reverse (`%/%`), the closest translation would be trunc(a / b), but trunc itself would be backend-specific I guess.

**Comment by hadley** [comment]
I think that this is just one of the hiccups of R -> SQL translation. It's not obvious to me that either dplyr or postgres is at fault, and I don't think documenting it will be that useful because it's (a) esoteric and (b) how would anyone know to look up this problem?

**Comment by iangow** [comment]
I think a few words in the "databases" [vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html) on this under **SQL Translation** in addition to what's there would suffice. I will make a note to propose some text.

I think this isn't too esoteric, as it will affect performance of joins, whether an index gets used or not, whether values get returned as integers or floating point (e.g., `mutate(c=a*2L)` versus `mutate(c=a*2)`), and whether functions work as expected (e.g., `mutate(a_lag_2=lag(a, 2)` gives an error in PostgreSQL, which expects what is produced by `mutate(a_lag_2=lag(a, 2L)`).
