### ISSUE TITLE
segfault with (admittedly incorrect) usage of summarize()

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1800]
I was sort of nesting a data frame but didn't want to use `tidyr::nest()` because I didn't want the other variables buried in a data frame -- I wanted them as individual list columns. Sthg like this:

``` r
library(dplyr)
mtcars %>%
  group_by(cyl) %>%
  summarize(gear = split(gear, cyl),
            wt = split(wt, cyl))
#> Source: local data frame [3 x 3]
#> 
#>     cyl       gear         wt
#>   <dbl>     <list>     <list>
#> 1     4 <dbl [11]> <dbl [11]>
#> 2     6  <dbl [7]>  <dbl [7]>
#> 3     8 <dbl [14]> <dbl [14]>
```

*~~btw I feel like there must be a better way to do that?~~ that Q now posed on tidyr*

Along the way, I created a truly stupid call to `split()` inside `summarize()`, which is reliably punished with segfault + RStudio crash.

``` r
library(dplyr)
cyl_df <- mtcars %>%
  group_by(cyl) %>%
  summarize(gear = split(gear, cyl),
            wt = split(gear, wt))
```

**Comment by hadley** [comment]
Do you mind filing the better way to do question this on tidyr?

**Comment by hadley** [comment]
@krlmlr would you mind taking a look at this? I suspect there's a missing check somewhere for the case where the summarise column is a list with length != 1.

**Comment by romainfrancois** [comment]
Now getting this, which I think is fine: 

```
> cyl_df <- mtcars %>%
+   group_by(cyl) %>%
+   summarize(gear = split(gear, cyl),
+             wt = split(gear, wt))
Error: expecting a single value
In addition: Warning message:
In split.default(list(c(4, 4, 4, 4, 4, 4, 3, 4, 5, 5, 4)), c(2.32,  :
  data length is not a multiple of split variable
```

**Comment by hadley** [comment]
Yeah, that seems reasonable to me.
