### ISSUE TITLE
Failing tests on R 3.3.0

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1806]
See https://github.com/hadley/dplyr/issues/1507#issuecomment-217857642 and references.

I think the problem boils down to:

```
> match("l\u00f8penummer", iconv(  "l\u00f8penummer", to  = "latin1" ))
[1] NA
> match(iconv(  "l\u00f8penummer", to  = "latin1" ), "l\u00f8penummer")
[1] NA
```

I'm taking a closer look.

**Comment by krlmlr** [comment]
Looks like this problem was introduced in R 3.3.0 -- I'm seeing the same problem here. NB: I think the code used in the tests need to be changed anyway.

```
> match("l\u00f8penummer", iconv(  "l\u00f8penummer", to  = "latin1" ))
[1] NA
> match(iconv(  "l\u00f8penummer", to  = "latin1" ), "l\u00f8penummer")
[1] NA
```

I haven't found anything in the NEWS about it, is this a true regression?

**Comment by krlmlr** [comment]
Unfortunately, yes:

```
> match(iconv(  c("A", "l\u00f8penummer"), from = "UTF8", to  = "latin1" ), "l\u00f8penummer")
[1] NA  1
> match(iconv(  c("l\u00f8penummer"), from = "UTF8", to  = "latin1" ), "l\u00f8penummer")
[1] NA
```

This might be related to

> match(x, table) is faster (sometimes by an order of magnitude) when x is of length one and incomparables is unchanged, thanks to Peter Haverty (PR#16491).

Will post to R-devel.

**Comment by yutannihilation** [comment]
FYI: the bug is reported below and the fix is already committed. 

16885 – bug in match (I think it's related to PR#16491)  
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16885
