### ISSUE TITLE
No warning when selecting out a grouping variable

### ISSUE THREAD

**Issue by rgknight** [hadley/dplyr#1807]
I would expect this to give me a 'cannot modify grouping variables' error, similar to what happens when you try to mutate a grouping variable. 

names(iris %>% group_by(Species) %>% select(-Species))

I am running 0.4.3

**Comment by krlmlr** [comment]
In dev dplyr, I'm seeing:

```
> iris %>% group_by(Species) %>% select(-Species) %>% names
Adding missing grouping variables: `Species`
[1] "Species"      "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width" 
```

**Comment by rgknight** [comment]
Thanks, that looks much better -- I am closing this.
