### ISSUE TITLE
all_equal() behavior for more than one difference

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1819]
```
> all.equal(data_frame(a=1, b=2), data_frame(a=1L, b=2L))
[1] "Incompatible type for column a: x numeric, y integerIncompatible type for column b: x numeric, y integer"
```

Should return a character vector instead.

Need to fix compatible_data_frame().

**Comment by hadley** [comment]
This would require quite a bit of re-engineering in the C++ code, and it's relatively low-priority so lets put off until the next version (unless you've already started on it)
