### ISSUE TITLE
Unable to select columns

### ISSUE THREAD

**Issue by prdprm** [hadley/dplyr#1823]
New to dplyr and also R.

**Problem statement:**
Unable to select only the columns I need from a data frame. dplyr shows other columns.

**Example :** I've a df called chamber2. 
str(chamber2) shows the following:
> str(chamber2)
Classes 'grouped_df', 'tbl_df', 'tbl' and 'data.frame': 2056 obs. of  5 variables:
 $ lot      : chr  "956522" "952" "95652" "9k002" ...
 $ step     : chr  "0CHA" "12THK" "123HK" "12HK" ...
 $ equipment: chr  "L9330" "R00312" "RS300_312" "R2700_Wafe312" ...
 $ parent   : chr  "L00" "R00" "RS00" "R200" ...
 - attr(*, "vars")=List of 3
  ..$ : symbol lot
  ..$ : symbol step
  ..$ : symbol equipment
 - attr(*, "drop")= logi TRUE

When I select just the column step from above, I get the following:
> select(chamber2,step)
Source: local data frame [2,056 x 3]
Groups: lot, step, equipment [2056]

           lot                          equipment
         (chr)                              (chr)
1  9562                         L2EX2J9330
2  9502                          R12
3  9002                          RS12
                                                 step
                                                (chr)
1                                             02HA
2                                             1HK
3                                             12HK

..                                                ...

As you can see, lot and equipment are also selected.

**Reason :** 
When I create chamber2 through dplyr functions, it automatically adds an attribute called vars for lot,step and equipment. 

chamber2 <- chamber2 %>% arrange(lot,step,equipment,date,parent)  %>% group_by(lot,step,equipment,parent) %>% summarise(wafer_seq=paste(wafer,collapse=","));

This somehow prevents it from selecting just the step column. So when I run the following, the select statement above returns just the step and hence works correctly:
attr(chamber2,"vars") <- NULL

**Questions:**
How does these attributes get added? Is there any documentation?
Why does the select statement not work with the attributes? Is this a bug? If so, whats the recommendation for the right way to fix it in my code?

Regards,
Pradeep

**Comment by joel23888** [comment]
Your data frame is grouped, and will always return all columns you have grouped by. Try ungrouping it. Here is a simple example:
```
> d <- data_frame(v1 = letters[1:2], v2 = letters[3:4], v3 = 1:2, v4 = 3:4) %>% group_by(v1, v2)
> d %>% select(v2)
Source: local data frame [2 x 2]
Groups: v1, v2 [2]

     v1    v2
  (chr) (chr)
1     a     c
2     b     d
> d %>% ungroup() %>% select(v2)
Source: local data frame [2 x 1]

     v2
  (chr)
1     c
2     d
```
