### ISSUE TITLE
[ for tbl_df  is inconsistent with data.frame behavior

### ISSUE THREAD

**Issue by twolodzko** [hadley/dplyr#1827]
`tbl_df` object inherits `data.frame` class, but it's behaviour is inconsistent with the generic R object:

```
library(dplyr)

dat <- data.frame(
  chr = letters[1:5],
  num = 1:5,
  stringsAsFactors = FALSE
)

dat2 <- tbl_df(dat)

class(dat[, 1])
## [1] "character"
class(dat2[, 1])
## [1] "tbl_df"     "data.frame"

is.character(dat[,1])
## TRUE
is.character(dat2[,1])
## FALSE
```

Imagine a real-life situation that dplyr is used at some part of the code, after that at some point automated checks are made against columns:

```
for (i in 1:ncol(dat2)) {
   if( is.character(dat2[, i]) ) {
      warning("Not a char!")
   }
}
```

User shouldn't expect anything strange from such code, but if dplyr was used that it would not return expected output.

The daily workaround for this problem is to add `%>% as.data.frame()` at the end of EVERY dplyr code, but this is inconvenient.

**Comment by hadley** [comment]
Yes, this is by design.  If you want to extract a single element, use `[[`

**Comment by twolodzko** [comment]
OK, get it and I understand the rationale behind it (`drop = TRUE` by default) but still this is painfully inconsistent. Consider the following example:

```
dat1 <- data.frame(
  chr = letters[1:2],
  num = 1:2,
  stringsAsFactors = FALSE
)

dat2 <- data.frame(
  chr = letters[3:4],
  num = 3:4,
  stringsAsFactors = FALSE
)

dat3 <- bind_rows(dat1, dat2)

is.character(dat1[,1])
is.character(dat2[,1])
is.character(dat3[,1])
```

The problem is that this happens implicitly. In this case replacing `rbind` with `bind_rows` leads to dramatic difference in the output while the functions _seem_ to do the same thing.

This is a possible candidate for R inferno!

**Comment by krlmlr** [comment]
The development version of dplyr returns the same type as the first input for bind_rows(). Is this different for other functions?
