### ISSUE TITLE
tbl_df loses rownames

### ISSUE THREAD

**Issue by alexey-larionov** [hadley/dplyr#1830]
Row names are lost after conversion of data frame to table. 
If this is a feature, then it would be nice to add an option of preserving the row names.
Similarly, row names are lost after "separate" in tidyr. 

Minimal code for dplyr:

library(dplyr)
data.df <- data.frame( F1 = c(1, 2, 3), F2 = c("one", "two", "three"), row.names = c("A", "B", "C"))
data.df
data.tb <- tbl_df(data.df)
data.tb
rownames(data.df)
rownames(data.tb)

**Comment by hadley** [comment]
None of my packages support row names - I don't think they're a good idea because they are not inline with the principles of tidy data, i.e. that there is a single way to represent a variable in your data.

**Comment by krlmlr** [comment]
Use tibble::rownames_to_column() and tibble::column_to_rownames() to convert row names to a regular column and vice versa. The latter works best for a "regular" data frame.
