### ISSUE TITLE
Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x0000000003d0c478

### ISSUE THREAD

**Issue by idavydov** [hadley/dplyr#1832]
R crashes with the following code:
```
a=data.frame(A=c(1,2,3,1,2,3), B=c(1,1,2,2,1,1), val=1:6)
a %>% group_by(A,B) %>% filter(which.max(val))
```
This is obviously incorrect code, but still R shouldn't crash.

**Comment by hadley** [comment]
(deleted the uninformative stack trace and session info - generally you don't need to supply these unless asked)

**Comment by earcanal** [comment]
Similarly this typo

```library(dplyr); group_by(mtcars, cycl)```

gives

```*** Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x0000000001a4bbd8 ***
Aborted (core dumped)```

**Comment by pkoki** [comment]
This could be related to RStudio handles errors in dplyr code - see also issue #1835.

Both example here crash R when running in RStudio, but return an error as expected in RGui.

version info:
RStudio Version 0.99.902
R: "R version 3.3.0 (2016-05-03)", "i386-w64-mingw32"
dplyr: Version: 0.4.3.9001, Built: R 3.3.0; i386-w64-mingw32; 2016-05-24 13:18:12 UTC; windows

**Comment by idavydov** [comment]
@pkoki, I doubt it. In vanilla R on my system (no GUI at all), I am still getting a crash.

**Comment by pkoki** [comment]
I get "Error: filter condition does not evaluate to a logical vector." when running your example in the windows RGui and in the console.

In RStudio I get this pop-up: "R Session Aborted. R encountered a fatal error. The session was terminated", and in the R console "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

This under windows 7, 32 bit R 3.3.0 with the github version of dplyr.

**Comment by kevinushey** [comment]
If the code involves invalid pointer access / use, you're essentially getting 'undefined' behavior on the C++ side. Sometimes you're 'lucky' and nothing bad happens; other times (more often) you get a crash.

In other words, I doubt this is related to whether the code is being executed within a vanilla R console vs. RStudio; it's more likely a bug in `dplyr`. If it's an issue due to memory protection the error will be trickier to reproduce, but likely reproduces more reliably when using e.g. `gctorture()`.

**Comment by hadley** [comment]
In the dev version, I get: "Error: filter condition does not evaluate to a logical vector. "

**Comment by osmanir** [comment]
I am compiling the box R for data science and get this error. I am using R 3.2.3 in Linux Mint Sarah 64 bits. Compiling with knit I get 

*** Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x00000000048261c8 ***
======= Backtrace: =========
.....
Aborted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile tidy.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted

**Comment by jlegewie** [comment]
This error is back for me on R 3.3.2 in the current dev version on github (0.5.0.9004 at this commit https://github.com/tidyverse/dplyr/commit/70fa0135ccc9810df6d8a9cbb07348b775e77fa8)

The same example from above
```
a=data.frame(A=c(1,2,3,1,2,3), B=c(1,1,2,2,1,1), val=1:6)
a %>% group_by(A,B) %>% filter(which.max(val))
```

Leads to this error:

```
Error in `/share/apps/r/3.3.2/intel/lib64/R/bin/exec/R': free(): invalid pointer: 0x0000000059a49eb8
...
```
