### ISSUE TITLE
slice command causing corrupt 'grouped_df' error

### ISSUE THREAD

**Issue by hardwhack** [hadley/dplyr#1833]
I am using dplyr 0.4.3 on R v 3.3.0. I've seen mention of the corrupt 'grouped_df' error elsewhere on closed tickets-- one said it was fixed, another said it was associated with use of rbind. I am still getting errors. Here is a minimal example using mtcars:

mtcars %>% group_by (cyl) %>% slice(1) %>% select(-vs)

As others have mentioned, you can get the expected behavior by inserting an ungroup command:
mtcars %>% group_by (cyl) %>% slice(1) %>% ungroup %>% select(-vs)

**Comment by hadley** [comment]
Fixed in dev
