### ISSUE TITLE
in group_by, NA_character_  replaced by "" (empty string)

### ISSUE THREAD

**Issue by Bart6114** [hadley/dplyr#1839]
relates to #1671

Apparently this bug is still here. Consider this adapted example from #1671:

```
test <- data.frame(id = rep(1:4, each = 3), grade = rep(c(NA, "a", NA, "b"), each = 3), stringsAsFactors = FALSE)

test %>% 
  group_by(id) %>% 
  dplyr::summarise(test = grade[1])

```
Results in:
```
     id  test
  (int) (chr)
1     1      
2     2     a
3     3    NA
4     4     b

```

Installing the latest dev version, as well as the suggested commit 9bae2aa, doesn't fix this issue.

**Comment by hadley** [comment]
You mean replaced by "", right? (in the title)

**Comment by Bart6114** [comment]
Ahum... Indeed, edited the title.

**Comment by hadley** [comment]
@romainfrancois can you take a look at this one too please?

**Comment by soniampub** [comment]
@hadley I can look into this issue but I am a beginner to open source. If anyone can guide me here I would like to contribute more and more on dplyr. Please let me are there any other issues for beginner that you would like me to start on. I really appreciate your suggestions.
