### ISSUE TITLE
summarize zero rows crashes R 

### ISSUE THREAD

**Issue by giko45** [hadley/dplyr#1840]
with R  3.2.4 and dplyr 0.4.3

The following chrashes R

`data.frame(y=0)%>% filter(y==1)%>%summarise(x=max(y))
`

 *** caught segfault ***
address 0x7ffaf89d7c28, cause 'memory not mapped'

Traceback:
 1: .Call("dplyr_summarise_impl", PACKAGE = "dplyr", df, dots)
 2: summarise_impl(.data, dots)
 3: summarise_.tbl_df(tbl_df(.data), .dots = dots)
 4: summarise_(tbl_df(.data), .dots = dots)
 5: as.data.frame(summarise_(tbl_df(.data), .dots = dots))
 6: summarise_.data.frame(.data, .dots = lazyeval::lazy_dots(...))
 7: summarise_(.data, .dots = lazyeval::lazy_dots(...))
 8: summarise(., x = max(y))
 9: function_list[[k]](value)
10: withVisible(function_list[[k]](value))
11: freduce(value, `_function_list`)
12: `_fseq`(`_lhs`)
13: eval(expr, envir, enclos)
14: eval(quote(`_fseq`(`_lhs`)), env, env)
15: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
16: data.frame(y = 0) %>% filter(y == 1) %>% summarise(x = max(y))

**Comment by hadley** [comment]
Fixed in dev

**Comment by giko45** [comment]
great  :)
