### ISSUE TITLE
NATURAL JOIN when there are no common elements is not allowed by dplyr

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1841]
In the following query tables `sdata` and `fdata` have no common columns, but PostgreSQL will happily execute the query:

```
# EXPLAIN SELECT *
     FROM fdata 
     INNER JOIN sdata 
     ON fyear >= byear AND fyear < eyear;
                                  QUERY PLAN                                   
-------------------------------------------------------------------------------
 Nested Loop  (cost=0.00..50886.88 rows=322722 width=40)
   Join Filter: ((fdata.fyear >= sdata.byear) AND (fdata.fyear < sdata.eyear))
   ->  Seq Scan on fdata  (cost=0.00..28.50 rows=1850 width=16)
   ->  Materialize  (cost=0.00..33.55 rows=1570 width=24)
         ->  Seq Scan on sdata  (cost=0.00..25.70 rows=1570 width=24)
(5 rows)
```

One way (in principle) to do this in `dplyr` would be

```
fdata %>%
    inner_join(sdata) %>%
    filter(fyear >= byear, fyear < year)
```

But this gives the complaint ``Error: No common variables. Please specify `by` param.``

A workaround suggested in my answer [here](http://stackoverflow.com/questions/37289405/dplyr-left-join-by-less-than-greater-than-condition) works as follows:

```
fdata %>% 
    mutate(dummy=TRUE) %>%
    inner_join(sdata %>% mutate(dummy=TRUE)) %>%
    filter(fyear >= byear, fyear < eyear) %>%
    select(-dummy)
```
Note that the `dummy` variable comes for free in SQL (PostgreSQL, at least); see [here](http://stackoverflow.com/questions/37289405/dplyr-left-join-by-less-than-greater-than-condition) for evidence.

But a more elegant approach would exist if `dplyr` allowed a join of two tables without common fields. The documentation claims "if [`by` is] `NULL`, the default, `join` will do a natural join ..." but note that 

```sql
SELECT *
FROM fdata 
NATURAL JOIN sdata 
WHERE fyear >= byear AND fyear < year;
```
works fine in SQL (PostgreSQL). 

I can see merit in not allowing users to do a Cartesian product of two tables accidentally due to unanticipated absence of common columns. But I wonder if there isn't an elegant way to get this if that is what is intended.

**Comment by hadley** [comment]
Part of #557
