### ISSUE TITLE
*_join functions don't work when by columns have different attributes

### ISSUE THREAD

**Issue by wangyuchen** [hadley/dplyr#1844]
When joining two data frames, it seems like the *_join functions not only check for the types of the `by` columns, but also check the attributes of them. Sometimes the columns are imported from different sources and may have incompatible attributes (for example read in from SPSS by `haven`), users have to manually delete/unify the attributes before merging. It gives the Error message of incompatible types even though the types are the same.

```
df1 <- data.frame(id = c(1, 2), value = rnorm(2))
df2 <- data.frame(id = c(1, 2), value2 = rnorm(2))
attr(df1$id, "label") <- "label for df1 id"
dplyr::left_join(df1, df2, by = "id")
```

**Comment by yutannihilation** [comment]
I believe this should be already fixed in dev version :) This is the same issue as https://github.com/hadley/dplyr/issues/1507.

```r
dplyr::left_join(df1, df2, by = "id")
#>   id      value    value2
#> 1  1 -2.1075902 0.3358275
#> 2  2  0.6327259 0.5052420
```
