### ISSUE TITLE
New family to replace summarise_each/mutate_each

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#1845]
```R
by_cyl <- mtcars[1:5] %>% group_by(cyl)
by_cyl %>% summarise_all(mean)
by_cyl %>% summarise_if(is.numeric, mean)
by_cyl %>% summarise_at(cols(cyl, mpg, wt), funs(mean, median), na.rm = TRUE)

by_cyl %>% mutate_all(scale)
by_cyl %>% mutate_if(is.numeric, scale)
by_cyl %>% mutate_at(cols(cyl, mpg, wt), funs(scale, rescale01))
by_cyl %>% mutate_at(c("cyl", "mpg", "wt"), funs(scale, rescale01))
```

`summarise_each()` and `mutate_each()` would be deprecated in favour of this new approach. And this would replace (e.g) `purrrr::dmap()`.

And cols would be something along the lines of:

```R
cols <- function(...) eval(subsitute(alist(...)))
```

(but with a special class)

**Comment by hadley** [comment]
@lionel- would this be a complete replacement for the current purrr functions that work with rows/dataframes? Or would there still be somethings that you couldn't do?

**Comment by lionel-** [comment]
> would this be a complete replacement for the current purrr functions that work with rows/dataframes?

Yes, expect for column collation, which is probably not that important. 

And list collation would be handled with `tidyr::nest()` + `dplyr::mutate()` + `purrr::map()` if you want to remove `by_slice()` from purrr as well.

**Comment by lionel-** [comment]
do you need me to take a look at this @hadley?

**Comment by hadley** [comment]
Yes, that would be great!

**Comment by guscampbell** [comment]
I was just attempting to  use `summarise_at()` or `mutate_at()` as referenced above, with the 'cols' argument used to pass the column names. When reopening a clean R session, loading dplyr 0.5.0, and running the four lines of code from the original comment, I get an error on the following line: 
`by_cyl %>% summarise_at(cols(cyl, mpg, wt), funs(mean, median), na.rm = TRUE)`

**Error in select_colwise_names(.tbl, .cols) : 
  could not find function "cols"**

I don't know if I am missing another prerequisite package or there is another issue, but I would appreciate any feedback on this error. Thank you.

---
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.2       assertthat_0.1 tools_3.3.1    DBI_0.4-1     
[6] tibble_1.1     Rcpp_0.12.6   
```
