### ISSUE TITLE
mapvalues - 

### ISSUE THREAD

**Issue by djambar** [hadley/dplyr#1849]
HI,

I get this error message : 

> The following `from` values were not present in `x`: aujourd’hui 

when I run this code :
dtAnnonces$Parution <- mapvalues(x = dtAnnonces$Parution, from = c( "aujourd’hui ", " hier "), to = c("0","1"))

the encoding seems ok (UTF-8)

str(dtAnnonces)
Classes ‘data.table’ and 'data.frame':  30 obs. of  3 variables:
 $ CleanParution1: chr  "aujourd’hui par hébergement H.IN.C.S" 
 $ Parution      : chr  "aujourd’hui " "aujourd’hui " "hier " "hier " 
 $ Annonceur     : chr  " hébergement H.IN" " hébergement H.IN.C.S" 

 _hier_ is mapped correctly, but not _aujourd’hui_

Thanks for your help

**Comment by hadley** [comment]
Maybe you meant to file this in plyr?
