### ISSUE TITLE
coercion for single `tbl_df` column

### ISSUE THREAD

**Issue by LiNk-NY** [hadley/dplyr#1856]
Coercion of a data_frame column is not the same as that of data.frame. 
##### Example: 
```
library(dplyr)
a <- data_frame(Code = letters[1:10])
b <- data.frame(Code = letters[1:10], stringsAsFactors = FALSE)
```
To get a character vector, user has to enter:

```
select(a, Code) %>% unlist
## compared to
as.character(b[, "Code"])
## or 
b[, "Code", drop = TRUE]
```

Can there be something comparable to drop arguments in the data.frame bracket (`[`) method or `as.character`, `as.*` methods for the `tbl_df` class?
Such that the following works: 
```
\dontrun{
select(a, Code, .drop = TRUE)
select(a, Code) %>% as.character
}
```
```
packageVersion("dplyr")
[1] ‘0.4.3’
```
Thanks

**Comment by hadley** [comment]
You should use `[[` to get a single column
