### ISSUE TITLE
meaning of dplyr's name

### ISSUE THREAD

**Issue by enesn** [hadley/dplyr#1857]
Hi,
Is dplyr a abbreviation? If is not what is the meaning of name and how can i pronounce?

**Comment by hadley** [comment]
The d is for dataframes, the plyr is to evoke pliers. Pronounce however you like.

**Comment by kartiksubbarao** [comment]
The precursor to dplyr was called plyr. The 'ply' in plyr comes from an expansion/refining of the various "apply" functions in R as part of the "split-apply-combine" model/strategy. Here's a good slideset that provides more insight into the plyr name:

https://www.slideshare.net/hadley/plyr-one-data-analytic-strategy

And yes, the name evokes pliers :-)
