### ISSUE TITLE
dplyr crash with arrange on R 3.3.0

### ISSUE THREAD

**Issue by RobertMyles** [hadley/dplyr#1870]
Any idea why this might be happening?

I'll use a reprex from Hadley's R for Data Science book, Exercise 4.4.1, 1: put NA at the top of the flights dataframe with `arrange()`.

    library(dplyr)
    library(nycflights13)

Any of these causes a crash:

    arrange(flights, is.na(flights))
    arrange(flights, desc=is.na(flights))

But not this:

    arrange(flights, is.na(arr_delay))

**Comment by hadley** [comment]
(For future reference please don't include `sessionInfo()` unless it's requested)

**Comment by hadley** [comment]
Reprex that illustrates the basic problem:

```R
dplyr::arrange(mtcars, is.na(mtcars))
```

@krlmlr do you have time in the next week or so to dig into this? I assume we're missing a check for matrices somewhere

**Comment by krlmlr** [comment]
What is this operation supposed to do? `is.na(mtcars)` is an all-FALSE logical matrix...

**Comment by hadley** [comment]
@krlmlr sorry - it should throw an error. This is just another check on the input type

**Comment by stephenjjohnson** [comment]
I think this may be a symptom of the same bug. If I run the following code line by line it gives the expected output of df1 - a data frame containing 2 observations of 4 variables, and df2 - 3 obs of 2 vars.

However, if I source the entire script then the 'select' operation works as expected but the 'filter' operation gives a df1 containing 0 observations.

I have confirmed this behaviour in RStudio 0.99.902 with R 3.3.0 and dplyr 0.4.3 on Win7 (32bit), Win10 (64bit) and Ubuntu 16.04 LTS (64-bit)

    library(dplyr)
    df <- read.csv(text = '"a", "b", "c", "d"
                       "beef", 1, 2, 3
                       "beef", 4, 5, 6
                       "chicken", 7, 8, 9')
    df1 <- df %>% filter(a == "beef")
    df2 <- df %>% select(c(a, b))

**Comment by hadley** [comment]
I very much doubt it's the same issue - it's much more likely to be because you're dplyr is in a different place on the search path. Please file a separate issue - I'll delete you comment to keep this thread clean.

**Comment by krlmlr** [comment]
Could #1878 help?

**Comment by krlmlr** [comment]
No, same behavior with #1878.

**Comment by mjpdenver** [comment]
(I don't know if it is appropriate to add a comment to a closed topic or start a new one, but I am having similar problems with summarise crashing R.  I am running  R version 3.3.3 and Rstudio version 1.0.136. )

I just started using updated versions of R and Rstudio yesterday and have been getting frequent crashes with summarise.   The following examples cited earlier here causes a crash.  

tst <- data.frame(
  grp = c(rep("A", 16), rep("B", 16), rep("C", 16)),
  x   = rnorm(16*3),
  y   = rnorm(16*3)
)
tst %>% 
  mutate(corr = cor(x, y, na.rm =  TRUE))

As well as 

dplyr::arrange(mtcars, is.na(mtcars))

**Comment by hadley** [comment]
If you have any doubt, file a new issue.
