### ISSUE TITLE
n_distinct() with null crashes R

### ISSUE THREAD

**Issue by gtumuluri** [hadley/dplyr#1871]
I ran into this problem a couple of times when feeding a non-existent column (by mistake) to n_distinct(). It totally crashes R (or hangs RStudio when operating on a large data frame. Re-starting RStudio only recourse.

```
packageVersion('dplyr')
[1] ‘0.4.3.9001’
```

Steps to reproduce problem:

```
x <- NULL
n_distinct(NULL)
```

My real case:

```
df <- data.frame(x = 1:100, y = 1:100)
n_distinct(df$x) # Works fine
n_distinct(df$z) # Crashes
```

**Comment by hadley** [comment]
Will fixed in dev dplyr

**Comment by gtumuluri** [comment]
Sorry, I should have checked on latest dev branch. Thought I was at latest. I tried installing later, but get failure, which must be some other issue with my network connection where I am at.

```
devtools::install_github("hadley/dplyr")
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Error in download(dest, src, auth) : Forbidden (HTTP 403).
```
