### ISSUE TITLE
Problem with encoding dplyr 0.4.3

### ISSUE THREAD

**Issue by gabrakadabra** [hadley/dplyr#1877]
I have a problem with mixed encoding of dataframe names when using dplyr 0.4.3.
When changing the columnnames I get an error
`Error: object 'Column_name' not found`

This works:
`Encoding(names(iris))`

    [1] "unknown" "unknown" "unknown" "unknown" "unknown"

`iris %>% group_by(Species) %>% summarise(mean(`Sepal.Width`))`

      Source: local data frame [3 x 2]

         Species mean(Sepal.Width)
            (fctr)             (dbl)
     1     setosa             3.428
     2 versicolor             2.770
     3  virginica             2.974

and this:
`iris %>% select(-Species) %>% summarise_each(funs(mean))`

     Sepal.Length Sepal.Width Petal.Length Petal.Width
     1     5.843333    3.057333        3.758    1.199333

But not after I change the column names:
`iris_renamed <- iris %>% rename('Sepäl.Width' = Sepal.Width)`
`Encoding(names(iris))`

      [1] "unknown" "UTF-8"   "unknown" "unknown" "unknown"

`iris_renamed %>% group_by(Species) %>% summarise(mean(`Sepäl.Width`))`

      Error: object 'Sepäl.Width' not found

My session info output:

> sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    > LC_MONETARY=Swedish_Sweden.1252
> [4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] dplyr_0.4.3
> 
> loaded via a namespace (and not attached):
>  [1] lazyeval_0.1.10.9000 magrittr_1.5         R6_2.1.2             assertthat_0.1       rsconnect_0.4.3     
>  [6] parallel_3.3.0       DBI_0.4-1            tools_3.3.0          memoise_1.0.0        crayon_1.3.1        
> [11] Rcpp_0.12.5          digest_0.6.9         testthat_1.0.2

**Comment by jmorten** [comment]
Try the dev version.
