### ISSUE TITLE
funs could accept a list of functions

### ISSUE THREAD

**Issue by dfalbel** [hadley/dplyr#1884]
Suppose I want to calculate one column for each quantile of a variable:

```
q_factory <- function(q){
  sapply(q, function(q){
    function(x) {quantile(x, probs = q, na.rm = T)}
  })
}

quantiles <- q_factory(1:9/10)

data_frame(x = 1:100, y = 1:100) %>%
  summarise_each(funs(quantiles))
```

What do you think?

**Comment by hadley** [comment]
What you probably want is the unexported `as.fun_list()`.  I could export it, but I don't want because in the next version of dplyr, `funs()` is likely to get overhauled to use my new lazyeval approach (http://rpubs.com/hadley/lazyeval)
