### ISSUE TITLE
Strings with and without encoding are not matched when joining

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1885]
```
encoded <- function(x) {
  Encoding(x) <- "UTF-8"
  x
}

unencoded <- function(x) {
  Encoding(x) <- "unknown"
  x
}

dplyr::left_join(tibble::data_frame(a = encoded("ä")),
                 tibble::data_frame(a = unencoded("ä"), b = 1))
##       a     b
##   <chr> <dbl>
## 1     ä    NA
```

Expected: `b == 1` in the result.

This can be mitigated by using r_match() instead of match() in the JoinStringStringVisitor, but I wonder if dplyr should warn instead.

**Comment by hadley** [comment]
Maybe tibble should force encoding to utf-8? Dplyr would still need to warn but that would mitigate some of the hassle

**Comment by krlmlr** [comment]
In my case, data came from a CSV file read using read.csv(); but readr already takes care of the encoding. If this done by tibble, perhaps readr doesn't have to do it anymore.

match() is Rcpp::match(), and Rcpp seems to respect the declared encoding (https://github.com/RcppCore/Rcpp/issues/189, https://github.com/RcppCore/Rcpp/issues/466). To me, r_match() looks like a safe, if perhaps slower, alternative. Or we fix upstream.

**Comment by hadley** [comment]
Would be good to fix upstream

**Comment by krlmlr** [comment]
Doesn't look like an upstream fix will become available soon. We should just make sure that column data is always UTF-8.

**Comment by krlmlr** [comment]
Related: #1950, column names with non-native encoding.
