### ISSUE TITLE
Add UNION ALL

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#1890]
There is no verb for `UNION ALL` in `dplyr`. For R data frames, `bind_rows()` likely works. Even if rows are unique `UNION` generally does not yield the same result as `UNION ALL` (e.g., rows get resorted).

If `union_all(x, y)` were implemented it could be translated as `SELECT * FROM x UNION ALL SELECT * FROM y` for SQL and (I guess) `bind_rows(x, y)` for R. (An alternative might be to have `bind_rows(x, y)` translate into `SELECT * FROM x UNION ALL SELECT * FROM y` if `x` and `y` are in an SQL source.)

**Comment by iangow** [comment]
Actually, `bind_rows` is more like `UNION CORRESPONDING`, which is *not* implemented in PostgreSQL (and other systems). So equating the two would therefore not make sense.

**Comment by hadley** [comment]
All ready implemented in dev version
