### ISSUE TITLE
mutate with column whose name is non-ascii ends up with duplicated columns

### ISSUE THREAD

**Issue by hidekoji** [hadley/dplyr#1891]
To Reproduce the issue

- create a data frame which has one variable (non-ascii name) and 2 observations

```{r}
> 防御率 <- c("1","2")
> df <- as.data.frame(防御率)
> df
  防御率
1      1
2      2
```

- mutate with same column name to convert character to number

```{r}
> df2 <- df %>% mutate(防御率 = as.numeric(防御率))
> df2
  防御率 防御率
1      1      1
2      2      2
```

Then it ends up with duplicated columns

**Comment by hadley** [comment]
Minimal reprex:

```R
df <- data_frame(防御率 = c("1","2"))
mutate(df, 防御率 = as.numeric(防御率))
```

which works for me in the dev version.

**Comment by hidekoji** [comment]
Thank you for the update! So the fix will be included in the next dplyr release ? (0.4.4 ?)

**Comment by hadley** [comment]
Yes, in 0.5

**Comment by hidekoji** [comment]
Cool, thank you !
