### ISSUE TITLE
group_by prevents correct formatting with pandoc

### ISSUE THREAD

**Issue by clayms** [hadley/dplyr#1893]
After using `group_by`, cannot output table with pandoc correctly with the `digits=` or `round=` parameters.  

Take the `group_by` out of the chain and pandoc displays the table just fine.  Add the `group_by` in and the number of decimal places of the floating point numbers is way to big to display.

**Comment by clayms** [comment]
[Sven](http://stackoverflow.com/users/1627235/sven-hohenstein) posted a work around on [StackOverflow](http://stackoverflow.com/questions/37673437/group-by-prevents-correct-formatting-with-pandoc).

**Comment by hadley** [comment]
Fortunately knew what you meant here, but in the future, please include a minimal reproducible example.
