### ISSUE TITLE
Changing a variable value for specific rows 

### ISSUE THREAD

**Issue by aalhadab** [hadley/dplyr#1897]
I have a PK dataset and I want to change the value of a specific variable for specific row only (dosing records) whiling leaving the rest the way they are. For example, I want to change II and ADDL variable from 24 and 5 to 12 and 10 only when AMT variable is not ".". How can I do that?

For example 
ID  TIME DV AMT  II    ADDL 
**1     0       0   100  24     5**
1     0       50   0    0       0 
.      .          .     .     .       .
**2     0       0   100  24     5**
2     0       50   0    0       0 
.      .          .     .     .       .

**Comment by hadley** [comment]
See discussion at #425
