### ISSUE TITLE
dplyr crashes r session with incorrect filter() syntax

### ISSUE THREAD

**Issue by ronammar** [hadley/dplyr#1900]
Couldn't figure out if this had already been resolved, so posting:

```r
library(dplyr)
mtcars %>% filter(mpg > 8)  # works
mtcars %>% filter(mtcars, mpg > 8)  # crashes
```
Thanks!

**Comment by hadley** [comment]
Basically a duplicate of #1870

**Comment by krlmlr** [comment]
Not anymore, with the most recent dev version I'm getting:

```
> mtcars %>% filter(mtcars, mpg > 8) 
Error: incorrect length (352), expecting: 32
```

We could explicitly test for a matrix, but at least it doesn't crash anymore.
