### ISSUE TITLE
summarise_all() column name fixed formatting option

### ISSUE THREAD

**Issue by stevenfazzio** [hadley/dplyr#1902]
Currently, the format of the output column names produced by `summarise_all()` depends on the number of number of columns in the input, as well as the number of aggregation functions used (I belive the logic for this is located in the `colwise_()` function). This is good for interactive use, but it would be useful to have a way to fix the output format (preferably as input column name underscore aggregation function, e.g. `mpg_mean`) for non-interactive use where the number of columns/functions might vary.

Below are some examples of how the column names vary. Each example produces the `mean()` of `mpg`, but calls it something different depending on what other columns/functions are used.

1. If only one aggregation function is used, then the output column names are the same as the input column names:
``` r
mtcars %>% 
  summarise_all(funs_('mean'))
#>        mpg    cyl     disp       hp     drat      wt     qsec     vs
#> 1 20.09062 6.1875 230.7219 146.6875 3.596563 3.21725 17.84875 0.4375
#>        am   gear   carb
#> 1 0.40625 3.6875 2.8125
```
2. If multiple aggregation functions are used, but only one column is selected, then the output column names are the same as the function names:
``` r
mtcars %>% 
  select_(.dots = c('mpg')) %>% 
  summarise_all(funs_(c('mean', 'sum')))
#>       mean   sum
#> 1 20.09062 642.9
```
3. If multiple aggregation functions are used, and multiple columns are selected, then the output column names are the input column names underscore the aggregation function names:
``` r
mtcars %>% 
  select_(.dots = c('mpg', 'cyl')) %>% 
  summarise_all(funs_(c('mean', 'sum')))
#>   mpg_mean cyl_mean mpg_sum cyl_sum
#> 1 20.09062   6.1875   642.9     198
```

**Comment by hadley** [comment]
Fixed in dev

* The naming behaviour of `summarise_each()` and `mutate_each()` has been
  tweaked so that you can force inclusion of both the function and the
  variable name: `summarise_each(mtcars, funs(mean = mean), everything())`
  (#442).

**Comment by fkgruber** [comment]
Hi Hadley,
can we get the everything option in summarise_all since summarise_each is deprecated?
Or is there an alternative way to achieve the same effect?

thanks
Fred
