### ISSUE TITLE
wrong top_n results

### ISSUE THREAD

**Issue by ronencozen** [hadley/dplyr#1903]
Hi,

I encountered wrong top_n results.

In the following example i would expect to get two rows per group_by key, which is not the case.

# data simulation
set.seed(123)
x <- data.frame(replicate(2,sample(1:5,50,rep=TRUE)))

# get top_n
y <- x %>%
  group_by(X1) %>%
  top_n(2,X2)

# count rows per group_by key
z <- y %>%
  group_by(X1) %>%
  summarize(n=n())

**Comment by hadley** [comment]
See the docs: "Will include more than n rows if there are ties."
