### ISSUE TITLE
install_github fails, circular dependency?

### ISSUE THREAD

**Issue by cboettig** [hadley/dplyr#1904]
dplyr declares `hadley/dtplyr` in `Remotes:` and vice versa, which appears to lead to a continual stream of this:

```r
devtools::install_github("hadley/dplyr")
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
```

**Comment by kevinushey** [comment]
This should be resolved with the development version of `devtools` -- try re-installing the latest version of `devtools` and then installing `dplyr`.

**Comment by cboettig** [comment]
Perfect, thanks!

**Comment by zkamvar** [comment]
This fix appears only to work when devtools is loaded.

**Comment by kevinushey** [comment]
Sorry; yes, you'll need to restart your R session after re-installing `devtools` (to ensure the newly downloaded package gets loaded).

**Comment by tungmilan** [comment]
@hadley Everyday there's someone reporting this, maybe it's a good idea to update the front page Readme.md?

```
if (packageVersion("devtools") < 1.6) {
  devtools::install_github("hadley/devtools")
}

Then restart R session

devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")
```

**Comment by achubaty** [comment]
@tungmilan the check for `devtools < 1.6` should be tweaked or omitted since I was still having the problem with v1.11.1. Reinstalling the development version of `devtools` did solve the problem though. Thanks.
