### ISSUE TITLE
unique_columns parameter for join functions

### ISSUE THREAD

**Issue by mienkoja** [hadley/dplyr#1906]
As discussed on stackoverflow [here](http://stackoverflow.com/questions/37753452/can-i-join-more-than-4-dataframes-in-dplyr), I am curious about the possibility of an option to avoid unique columns in `dplyr` join functions. 

I realize that in R, we would generally prefer to avoid duplicate column headings, but since the join functions are attempting to replicate SQL functionality, it might be occasionally desirable to allow for duplicate column names. 

I believe the stack question referenced above gives an example of an instance in which a `unique_columns=FALSE` parameter might be useful in all of your join functions.

**Comment by mienkoja** [comment]
I'll add that this may be a bigger request than what's feasible. At a minimum, it seems that dplyr's column naming logic should scale to an arbitrary number of joins.

**Comment by hadley** [comment]
Already fixed in dev (scheduled for CRAN release in two weeks, June 23)
