### ISSUE TITLE
Group_by + mutate gives incorrect results with knock-on effect if NAs are present

### ISSUE THREAD

**Issue by pfabri** [hadley/dplyr#1908]
Dear Hadley and contributors,

I've stumbled upon a problem whereby using `mutate` on a grouped dataframe in which there is a group containing `NA` values only results in erroneous calculation for **other groups** too. The behaviour certainly seems to be inconsistent with other functions in `dplyr`, and also base R. 

I believe the issues is related to #489 from 10 July 2014 and that it is a bug. Please see the details below and many thanks for your help in advance,

Peter

### Repex

**Data**

    test.df <- tbl_df(data.frame(id = rep(1:4, each = 2),
                           value = c(NA, NA, 2, 3, 3, 5, 21, 0)))
    > test
    id value
    1  1    NA
    2  1    NA
    3  2     2
    4  2     3
    5  3     3
    6  3     5
    7  4    21
    8  4     0

**Problem demonstration**

    mean.mutate <- test %>% 
                   group_by(id) %>% 
                   mutate(mean = mean(value, na.rm = TRUE)) %>% 
                   print()

    Source: local data frame [8 x 3]
    Groups: id [4]
        
        id value  mean
        (int) (dbl) (dbl)
    1     1    NA    NA
    2     1    NA    NA
    3     2     2   2.5
    4     2     3   2.5
    5     3     3    NA  # mean should be 4 for this group
    6     3     5    NA
    7     4    21  10.5
    8     4     0  10.5

**Alternatives, which do work**

Using `do`:

    mean.do <- test %>%
               group_by(id) %>% 
               do(mutate(., mean = mean(value, na.rm = TRUE))) %>% 
               print()

        Source: local data frame [8 x 3]
        Groups: id [4]
        
        id value  mean
        (int) (dbl) (dbl)
    1     1    NA   NaN  # notice that NaN is returned, not NA as above
    2     1    NA   NaN
    3     2     2   2.5
    4     2     3   2.5
    5     3     3   4.0  # correct
    6     3     5   4.0
    7     4    21  10.5
    8     4     0  10.5

Using `summarise`:

    mean.summary <- test %>% 
                    group_by(id) %>% 
                    summarise(mean = mean(value, na.rm = TRUE)) %>% 
                    print()

        Source: local data frame [4 x 2]
        
        id  mean
        (int) (dbl)
    1     1   NaN  # as above
    2     2   2.5
    3     3   4.0  # correct
    4     4  10.5

Using base R's `ave`:

    within(test, mean <- ave(value, id, FUN = function(x) mean(x, na.rm = TRUE)))

    id value mean
    1  1    NA  NaN  # as above
    2  1    NA  NaN
    3  2     2  2.5
    4  2     3  2.5  # correct
    5  3     3  4.0
    6  3     5  4.0
    7  4    21 10.5
    8  4     0 10.5

### Other observations

The error doesn't occur if at least one value is NOT `NA` in the group.

### Session info

> sessionInfo()
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 15.10
    
    locale:
    [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
    [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] ggrepel_0.5     lubridate_1.5.6 tidyr_0.4.1     ggplot2_2.1.0   dplyr_0.4.3    
    
    loaded via a namespace (and not attached):
    [1] Rcpp_0.12.4      digest_0.6.9     assertthat_0.1   grid_3.2.2       R6_2.1.2         plyr_1.8.3       gtable_0.2.0     DBI_0.3.1       
    [9] magrittr_1.5     scales_0.4.0     stringi_1.0-1    lazyeval_0.1.10  labeling_0.3     tools_3.2.2      stringr_1.0.0    munsell_0.4.3   
    [17] parallel_3.2.2   rsconnect_0.4.3  colorspace_1.2-6 knitr_1.12.3

**Comment by hadley** [comment]
Should be fixed in dev. 

Thanks for the reproducible example! But for future reference please don't include session info unless explicitly asked, and when the answer is obviously incorrect you don't need to include multiple ways to compute the correct answer.

**Comment by pfabri** [comment]
Confirmed: using the current development versions **resolves the problem.**
