### ISSUE TITLE
Feature request: sql_render_final

### ISSUE THREAD

**Issue by hhoeflin** [hadley/dplyr#1917]
Hi,

I wanted to ask if a sql_render_final operation could be broken out separately. 

In my implementation, I would like to post-process the sql right before it is being sent to the database (e.g. for inserting a comment with additional usage information) into the sql itself. As sql_render is being called recursively, I thought maybe a sql_render_final operation that is only used by function that are supposed to write the "final" sql, e.g. show_query and when fetching the final data.

Thanks

**Comment by hadley** [comment]
Why not just add a method for you `tbl` class that does that?

**Comment by hhoeflin** [comment]
It is what I did - but that then also requires additional changes to several other functions like show_query (that then wouldn't show the actual SQL being sent to the database), collect (which only calls sql_render) etc. 

An additional side-effect this can be used for are "WITH" queries. This produces much more readable SQL with less nesting due to subqueries or that uses a query in more than one location (can improve performance).

**Comment by hadley** [comment]
Both `show_query()` and `collect()` call `sql_render()` on the tbl: your generic can do whatever it wants with it.
