### ISSUE TITLE
In tally_ and count_, support programmatic specification of wt

### ISSUE THREAD

**Issue by holstius** [hadley/dplyr#1919]
Passing the name(s) of variables (as character) "just works" in most underscored ("programmatic") dplyr functions. For example:

```
tally(group_by_(my_data, "foo"), wt = bar)
```

But, it looks like this has yet to be supported in `tally_` (and hence, also in `count_`).

Proposed: these should also work:

```
tally_(my_data, wt = "bar")
count_(my_data, vars = "foo", wt = "bar")
```

Happy to construct test cases, pull request, etc. but not sure if this might be intended behavior — or if/how it intersects with the intended behavior of `lazyeval::interp` (relied upon by `tally_`).

**Comment by krlmlr** [comment]
@hadley: I agree that this is inconsistent, and wt should accept both character and formula in tally_(). The inconsistencies are even more severe in tidyr.

**Comment by hadley** [comment]
@krlmlr yes, I think we'll definitely want to take another pass at this for the next release (using everything we've learned in lazyeval etc)

**Comment by hadley** [comment]
@lionel- another one for you

**Comment by lionel-** [comment]
Should this be `tally(my_data, wt = !! symbol("bar"))`?

@hadley what's the rule for which verbs should support strings? `group_by()` supports strings but `select()` does not.

**Comment by hadley** [comment]
Yes, I think so.

I think generally verbs shouldn't support strings without some syntactic signal. `select()` has `one_of()`, and with tidyeval we can now use `!!`.

**Comment by lionel-** [comment]
sounds good, closing this then.
