### ISSUE TITLE
Install failure, devtools::install_github("hadley/dplyr")

### ISSUE THREAD

**Issue by arestrom** [hadley/dplyr#1922]
When running devtools::install_github("hadley/dplyr") (Windows 7 & 10, R 3.3.0, devtools 1.11.1 in RStudio  0.99.902) a loop is reliably commenced terminating only when github API limit is reached. Behavior appears to be limited to dplyr installation attempts. Same result in R 3.3.0 64 bit Rgui.exe. 

Example:
> devtools::install_github("hadley/dplyr")
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master

**Comment by kevinushey** [comment]
You need the development version of `devtools` to resolve this. Try installing it with:

    devtools::install_github('hadley/devtools')

and then restarting the R session and trying again.

(If that installation fails, you might need to manually clone the repository and install from the command line)

**Comment by arestrom** [comment]
That worked. Thank you.
