### ISSUE TITLE
filter, distinct, group_by produces different results under new version of R (3.3.0)

### ISSUE THREAD

**Issue by cathgr** [hadley/dplyr#1923]
Hello,
I have wrote a code to subset a dataset of 668,400 rows using `filter` `distinct` `group_by` under the last version of R (3.2.4). Now that I have updated to the newest version 3.3.0, I run my code and got different subset with a larger amount of observations. For example, the subset created under the last version of R was with 276,643 rows. Now since the update it is at 315,910 rows. 
Is there any explanation for the difference in the accuracy of those functions?
Thank you very much,

**Comment by hadley** [comment]
Please provide a reproducible example.

**Comment by krlmlr** [comment]
Could you please also try R 3.3.0-patched? What data source are you using -- data frames, data tables, SQL?
