### ISSUE TITLE
rename_ cannot handle nonstandard names

### ISSUE THREAD

**Issue by billdenney** [hadley/dplyr#1926]
When a data.frame has a nonstandard name, with a space in it for example, rename_ gives an error.

An example is:

```
> tmp <- data.frame(x=1:4)
> rename_(tmp, "y" = "x")
  y
1 1
2 2
3 3
4 4
> names(tmp) <- "a b"
> rename_(tmp, "y" = "a b")
Error in parse(text = x) : <text>:1:3: unexpected symbol
1: a b
      ^
> 
```

This is with dplyr 0.4.3 and R 3.3.0.

**Comment by npjc** [comment]
+1.

## One-way works:
```r
library(dplyr)
iris %>% 
rename_(.dots = list("Sepal:Length" = "Sepal.Length"))  %>% 
glimpse()
#> Observations: 150
#> Variables: 5
#> $ Sepal:Length (dbl) 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8...
#> $ Sepal.Width  (dbl) 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0, 3.0, 4.0...
#> $ Petal.Length (dbl) 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2...
#> $ Petal.Width  (dbl) 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2...
#> $ Species      (fctr) setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, ...
```

## round trip attempt = sadness
```r
iris %>% 
rename_(.dots = list("Sepal:Length" = "Sepal.Length")) %>% 
rename_(.dots = list("Sepal.Length" = "Sepal:Length"))
#> Error: Arguments to `rename()` must be unquoted variable names.
#> Argument `Sepal.Length` is not.
```

**Comment by krlmlr** [comment]
Thanks, confirmed. Would you like to contribute a testthat test?

**Comment by billdenney** [comment]
I think that the testthat test would be what I gave above:

```
tmp <- data.frame(x=1:4)
names(tmp) <- "a b"
expect_equal(rename_(tmp, "y" = "a b"), data.frame(y=1:4))
```

**Comment by krlmlr** [comment]
Thanks. Closing in favor of #2243, which will group all related issues.

**Comment by krlmlr** [comment]
`rename()` actually works, but you have to do one of:

```
tmp <- data.frame(x=1:4)
names(tmp) <- "a b"
rename_(tmp, "y" = ~`a b`)
rename(tmp, "y" = `a b`)
```

**Comment by billdenney** [comment]
Thanks for this workaround.  Is it feasible to capture the string case and convert it to the backtick case?  To convert this

```
rename(tmp, "y" = "a b")
```
to
```
rename(tmp, "y" = `a b`)
```

I think that always converting strings to backticks for rename should always work, but I may not be thinking of an edge case.

**Comment by krlmlr** [comment]
Unfortunately not, please see https://github.com/hadley/lazyeval/issues/89 for the fine print. I'm working on a better API for this as part of #2243.

**Comment by billdenney** [comment]
Thinking about it a bit more, you could always wrap character strings in backticks for rename_.  Looking into the issue you linked, this would not be a general solution that should be applied to the lazy_.character function, but it could be applied to the rename_ function.  The following works:

```
tmp <- data.frame(x=1:4)
names(tmp) <- "a b"
rename_(tmp, "y" = "a b") # fails
rename_(tmp, "y" = "`a b`") # works
```

I think that could be implemented as simply as adding the following to the rename_ functions:

```
.dots <- append(.dots,
  lapply(X=list(...), FUN=function(x) {
    if (is.character(x)) {
      x <- paste0("`", x, "`")
    } else {
      x
    }
  })
```

(That was typed directly into GitHub, but it hopefully communicates the intent.)

**Comment by krlmlr** [comment]
@billdenney: Thanks. Please see #2386 for a sketch that addresses the problems with `select()`. The `rename()` case should be solvable in a very similar way.
