### ISSUE TITLE
non existing column returns Error and not NULL

### ISSUE THREAD

**Issue by ckluss** [hadley/dplyr#1927]
Hi

I would expect NULL and no error message  :(

There seems to be an update in an imported package?

```
test <- data.frame()
test$x
NULL

test <- data_frame()
test$x
Error: Unknown column 'x'
```
 
Best wishes
Christof

**Comment by hadley** [comment]
This is a feature of tibble.

**Comment by ckluss** [comment]
ok, do not see the feature  :(

I created some factors with mutate(x = paste(.[["a"]],.[["b"]],.[["c"]])) and that crashes now ;)

But, of couse, that may be a little bit dirty ...

Best wishes
Christof

**Comment by krlmlr** [comment]
See https://github.com/hadley/tibble/issues/91 for discussion and workarounds.
