### ISSUE TITLE
recode suggestions

### ISSUE THREAD

**Issue by itsdalmo** [hadley/dplyr#1931]
In my experience, the current version of `recode` is a little bit inflexible and I figured I'd make some suggestions which I think could help improve it. If you agree (perhaps has to be @lionel-), I could eventually make a pull request if you'd like.

#### Why?

As an example, imagine that you'd like to convert a likert scale to NPS (group 1 = 0 to 6, group 2 = 7 to 8, group 3 = 9 to 10). Currently, this would be very tedious:
```R
v <- 1:10
recode(v, `0` = "detractor", `1` = "detractor", `2` = "detractor",  `3` = "detractor", etc.
```

#### Reverse order of recodes

To make any of the following suggestions possible, one would have to switch the way new values and old values are specified. Currently it is `old_value = new_value`. Reversing this means that we could supply multiple `old_value`'s (or logical vectors as indicies) to recode to `new_value`. 

#### 1. Recode multiple values

With the above in place, users could specify multiple values to recode to the same `new_value`:

```R
v <- 1:3
# We could write:
recode(v, low = 1:2, high = 3)
#> low low high

# Instead of:
recode(v, `1` = "low", `2` = "low", `3` = "high")
#> low low high
```

#### 2. Accept logical vectors

If `recode` accepted logical vectors (same length as `.x`), users could specify the subsets to be recoded directly, and we would be able to do the following:

```R
v <- 1:3
recode(v, low = v <= 2, high = v == 3)
#> low low high
```
#### 3. Allow dot notiation

The above might be tedious if `v` had a really long name to begin with, so another suggestion might be to allow a `.`-notation as a reference to `.x` and replace it before evaluating the call. This would allow:

```R
verylongname <- 1:3
recode(verylongname, low = . <= 2, high = . == 3)
#> low low high
```

To make this possible, the current version of recode would have to be renamed to `recode_` and then we'd need another implementation of `recode` which uses lazyeval. 

#### Thanks

I might have missed obvious ways to do the above, or perhaps some sort of limitation if `recode` is meant to work with all kinds of backends? If not, hopefully the suggestions make sense/can be of use.

-Kristian

**Comment by hadley** [comment]
I think you're looking for `case_when()`
