### ISSUE TITLE
Bug installing development version?

### ISSUE THREAD

**Issue by mconsidine** [hadley/dplyr#1934]
Hi,
I am trying to install the development version of dplyr, using these instructions
`if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")`
from the main page here
  https://github.com/hadley/dplyr

However the last line results in an endless looping, like this :
`> devtools::install_github("hadley/dtplyr")
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
Installing dtplyr
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr`

Is there a different way to install the development version?  I am hoping that it deals with the "shutdown" bug when "mutate" is invoked (in my case : R-3.3.0 32 bit Windows)

TIA

**Comment by kevinushey** [comment]
You'll need to install the development version of `devtools`:

```
devtools::install_github('hadley/devtools')
```

**Comment by mconsidine** [comment]
Okay.  Is there a place I can download that as a ZIP file, as I know have apparently hit some API rate limit due to the looping?  "Check out the documentation for more details" is a bit too ambiguous as there doesn't seem to be any reference to authenticating requests in the devtools docs, that I can see anyway.

**Comment by hadley** [comment]
You might be better off waiting for a CRAN release, will be happening in ~ one week.

**Comment by kevinushey** [comment]
On the GitHub page, you can manually download a tarball of the master release, e.g. the `Clone or Download` icon at the top right of the page:

![screen shot 2016-06-16 at 11 49 49 am](https://cloud.githubusercontent.com/assets/1976582/16129137/7c685c2c-33b8-11e6-85c8-2e683f22e6ac.png)

After downloading that, you should be able to install it with `R CMD INSTALL` or `install.packages(<pathToZipball>, repos = NULL)`
