### ISSUE TITLE
Problem installing development version from github

### ISSUE THREAD

**Issue by rsuhada** [hadley/dplyr#1935]
Due to the constant crashing of 0.4.3 (likely bug #1870 also for filter, mutate), I've tried to install the dev version via:

```
if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")
```
This results into a loop (until exceeding the API limit):

```
Downloading GitHub repo hadley/dplyr@master
from URL https://api.github.com/repos/hadley/dplyr/zipball/master
Installing dplyr
Downloading GitHub repo hadley/dtplyr@master
from URL https://api.github.com/repos/hadley/dtplyr/zipball/master
```

Thank you!

**Comment by hadley** [comment]
You need install the dev version of devtools.  But if it is crashing for every operation, it's more like you need to reinstall dplyr and all it's dependencies.
