### ISSUE TITLE
subsetting errors with tbl_df

### ISSUE THREAD

**Issue by royelis** [hadley/dplyr#1951]
I'm finding an error when subsetting a _tbl_df_.  Here's a reproducible example using the **mtcars** data:

```
> df <- tbl_df(mtcars)
> names(df)
 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear" "carb"
```
Subsetting with a $ works, but not with brackets.  For example:

```
> length(df$mpg)
[1] 32
> length(df[,1])
[1] 1
```
Contrast the subsetting behavior using the original dataset.

```
> length(mtcars$mpg)
[1] 32
> length(mtcars[,1])
[1] 32
```

The error is not limited to length().  Another example:

```
> mean(df$mpg)
[1] 20.1
> mean(df[,1])
[1] NA
Warning message:
In mean.default(df[, 1]) : argument is not numeric or logical: returning NA
```

As far as I can tell, all datasets read into R using **readR** (read_delim, read_rds, etc) are read in as _tbl_df_, so this problem is pervasive.   

Using R 3.3.0 and RStudio Version 0.99.902 on Intel Mac OS X 10_10_5

**Comment by krlmlr** [comment]
`df[,1]` returns a one-column data frame for class `tbl_df`, this is by design. Use `df[[1]]` instead, or coerce to a "plain old" data frame using `as.data.frame()`. See also [the tibble vignette](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html).

**Comment by royelis** [comment]
Thank you! That's really helpful.  

Your comment also makes me realize that it would be helpful if the R documentation for **readR** made clear that it differs from other methods of reading data into R in that it produces class  `tbl_df` rather than "plain old" data frames.
