### ISSUE TITLE
Slow performance of filter

### ISSUE THREAD

**Issue by evodevosys** [hadley/dplyr#1953]
I am getting very slow performance of filter compared with the base R functionality.  This may be related  to issues #984 and #879.  In contrast to #879, however, I have lots of rows but few columns.  In this example, filter should pick out 203,110 rows of the 1,544,454 row data frame.

```
with_filter=function(mydata){
     x=mydata %>% filter(uID==22)
 }
without_filter=function(mydata){
     x=mydata[mydata$uID==22,]
}
> dim(sub.exp)
[1] 1544454      11
> system.time(with_filter(sub.exp))
   user  system elapsed 
 11.815   0.159  11.973 
> system.time(without_filter(sub.exp))
   user  system elapsed 
  0.223   0.056   0.279 
```
Running: dplyr 0.4.3, R 3.2.4

**Comment by hadley** [comment]
Impossible to know without a reprex, but probably you have a grouped dataset, so ungroup to get better perf.
