### ISSUE TITLE
Lead/lag inside dplyr mutate results in inexplicable error when using functions to create default

### ISSUE THREAD

**Issue by rickdonnelly** [hadley/dplyr#1956]
The default value in dplyr's lead and lag works fine when a constant as coded for it, but returns an error message saying it expects a single value if I try to use a function or select the first element of a different field in the data frame. Here is the code I am using:

```
library(dplyr)

# Create simple data frame to illustrate the problem
argh <- data.frame(
  tourID = c("123", "123", "123", "456", "456"),
  tour_start = c(8.16, 8.16, 8.16, 10.1, 10.1),
  travel_time = c(12.8, 29.5, 37.7, 45.8, 51.7),
  stop_duration = c(44.2, 12.3, 0, 212.3, 0)
)

# Try to use R evaluation of function to get default for lag(depart)
eh <- group_by(argh, tourID) %>%
  mutate(depart = 0, arrive = lag(depart, default = min(tour_start)))

# Try to use first() instead
eh <- group_by(argh, tourID) %>%
  mutate(depart = 0, arrive = lag(depart, default = first(tour_start)))
```

Note that the intent here is to use the value of tour_start specific to each tourID as the default value for lag(depart), which is defined in the mutate statement. However, using either min(tour_start) or first(tour_start) for the default value results in:

```
Error: expecting a single value
```

Both min() and first() unambiguously return a single value. Thus, there is a bug in dplyr, or the documentation and error message should be updated to state that you can only use constants for default values. The latter would be tragic if true, for it would greatly reduce the utility of dplyr. So I'm hoping that neither is applicable, and that I'm simply doing something stupid. Any ideas on how to get this to work?

I'm using dplyr_0.4.3 running under R 3.2.4 on OS X El Capitan 10.11.5.

**Comment by hadley** [comment]
As mentioned in other thread this is fixed in dev
