### ISSUE TITLE
dplyr/as.integer/group_by: Cannot mutate NA integers to zeroes (incompatible types)

### ISSUE THREAD

**Issue by sebastianbafoodora** [hadley/dplyr#1961]
My session:

> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

The following code results in an error (initially I wanted to replace 
NAs in a dataframe with zeroes)

```
df <- data.frame(a = as.integer(c(3, NA)))
df %>%
    group_by(a) %>% 
    mutate(new = ifelse(is.na(a), 0, a)) -> d
```

results in

`Error: incompatible types, expecting a integer vector`

PS: Awesome packages!  :+1:

**Comment by hadley** [comment]
So give it an integer 😉  `0L`  (we might work around this in the future)

**Comment by sebastianbafoodora** [comment]
Haha, thanks for the quick reply.
I added to examples where it is working, just in case ;-)
