### ISSUE TITLE
rename over group_by column fails for sql backends

### ISSUE THREAD

**Issue by javierluraschi** [hadley/dplyr#1962]
While trying to rename over a `group_by` column against sql backends:

``` r
db <- src_sqlite("test.sqlite", create = TRUE)
copy_to(db, flights)
tbl(db, "small_flights") %>% 
  group_by(tailnum) %>%
  rename(tailnum2 = tailnum)
```

results in:

```
Source:   query [?? x 16]
Database: sqlite 3.8.6 [test.sqlite]
Groups: tailnum

Error: unknown column 'year' 
```

However, this would work as expected for local data frames:

``` r
flights %>% 
  group_by(tailnum) %>%
  rename(tailnum2 = tailnum)
```

@hadley found this while trying to implement a workaround for unsupported `USING` statements in Spark < 2.0.

**Comment by imanuelcostigan** [comment]
@hadley related to #709 ?

**Comment by krlmlr** [comment]
Thanks. No, #1997 (which is pointed to by #709) doesn't resolve this issue:

```r
memdb_frame(a=1, b=2) %>% group_by(a) %>% rename(c=a)
```

**Comment by hadley** [comment]
Same basic problem as #2156.

Needs two fixes:

* in `collect.tbl_sql()` only group based on columns that are actually present
* need `op_grps.op_rename()` method
