### ISSUE TITLE
nrow on computed table on 0.5

### ISSUE THREAD

**Issue by kismsu** [hadley/dplyr#1966]
Hi, I've noticed that on 0.5 nrow function on computed table with PostgreSQL back end returns NA if the table is empty. Is this by design or it is a bug?

**Comment by hadley** [comment]
It always returns NA because determine the number of rows in a query is an expensive operation.

**Comment by kismsu** [comment]
No, it used to return 0, which was very handy for testing. Not a big deal, just have to update lots of code
