### ISSUE TITLE
Cross join

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#197]
Often needed when you want to implement custom merge criteria across two tables.
- http://stackoverflow.com/questions/19552104
- http://stackoverflow.com/questions/21226269

For this use case (which I think is the most common for cross_joins) ideally need to avoid materialising the complete table.

**Comment by hadley** [comment]
@romainfrancois can you add this on the C++ side please?

**Comment by franknarf1** [comment]
Fyi also here: http://stackoverflow.com/q/42165365

**Comment by hadley** [comment]
Moving all future discussion to #2240
