### ISSUE TITLE
na_if: Support multiple values that are replaced with NA 

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#1972]
The additions in 0.5 are great!! A lot of dataset contain multiple missing codes for a single variable though and I think it would be much more useful if the user could pass multiple values to `na_if`. For example, `1:10 %>% na_if(2, 4)` or even `1:10 %>% na_if(1:5, 10)` would both be useful. Maybe it's not desired because `na_if` is supposed to work like `NULL_IF` but I do think it's much more useful. So I propose modifying  `na_if` or adding a function `na_codes` that supports multiple values. Of course, `na_if(1:5, 5:1)` would lead to different results. If this is desired, I could submit a pull request.

Here are two example implementations:

#### Version 1 with support for vectors
```
na_codes <- function(x, ...) {
	x[x %in% c(...)] <- NA
	x
}
1:10 %>% na_codes(1:5, 10)
letters %>% na_codes("a", "b", c("z", "y"))
```
#### Version 2 without support for vectors
```
na_codes2 <- function(x, ...) {
	for(y in list(...))
		x[x == y] <- NA
	x
}
1:10 %>% na_codes(1, 2, 3, 4, 5, 10)
letters %>% na_codes("a", "b", "z", "y")
```

#### Performance comparison
Version 1 is slower but also supports vector arguments. Version 2 is as fast as `dplyr::na_if` with support for multiple arguments.

```
library("rbenchmark")
x <- rbinom(1e6, size = 1, prob = 0.5)
benchmark(dplyr::na_if(x, 1), na_codes(x, 1), na_codes2(x, 1))
#                test replications elapsed relative user.self sys.self user.child sys.child
#1 dplyr::na_if(x, 1)          100   2.870    1.000     2.138    0.468          0         0
#2     na_codes(x, 1)          100   4.895    1.706     4.150    0.518          0         0
#3    na_codes2(x, 1)          100   3.098    1.079     2.318    0.481          0         0
```

**Comment by hadley** [comment]
The second argument is vectorised along x - I don't think it's possible to change this because it would break the symmetry with `coalesce()` and with SQL's `NULL_IF`

**Comment by hadley** [comment]
You could have another function with the behaviour that you wanted though.

**Comment by jlegewie** [comment]
That's what I thought. Would `na_codes` be a welcome addition to `dplyr` or too redundant with `na_if`?

**Comment by hadley** [comment]
It feels like a function like that would be more suitable for tidyr, but a tidyr function would more naturally operate on multiple columns simultaneously.

**Comment by nalimilan** [comment]
Couldn't `na_if(x, "a", "b")` simply be equivalent to  `na_if(na_if(x, "a"), "b")`? That would easily translate to SQL.

**Comment by ahcyip** [comment]
@jlegewie Does recode() work for what you are suggesting here?
