### ISSUE TITLE
*_if .predicate function semantics

### ISSUE THREAD

**Issue by alistaire47** [hadley/dplyr#1977]
I've been checking out the 0.5.0 updates (which are awesome) and noticed an incongruity in the "Summarise and mutate multiple columns" family. While `funs()` has long allowed abbreviated anonymous functions with `.` to `.funs`, e.g.

``` r
mtcars %>% summarise_each(funs(mean(.) < 4))
#     mpg   cyl  disp    hp drat   wt  qsec   vs   am gear carb
#1 FALSE FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE
```

and now `vars()` enables a parallel process, where `.predicate` is used (`summarise_if`, `mutate_if`, `select_if`), it is very much limited to either a function name, as in the docs:

``` r
by_species <- iris %>% group_by(Species)
by_species %>% summarise_if(is.numeric, mean)
# Source: local data frame [3 x 5]
#
#      Species Sepal.Length Sepal.Width Petal.Length Petal.Width
#       <fctr>        <dbl>       <dbl>        <dbl>       <dbl>
#1     setosa        5.006       3.428        1.462       0.246
#2 versicolor        5.936       2.770        4.260       1.326
#3  virginica        6.588       2.974        5.552       2.026
```

or a full-on anonymous (or saved) function:

``` r
mtcars %>% summarise_if(function(x){mean(x) < 4}, mean)
#       drat      wt     vs      am   gear   carb
#1 3.596563 3.21725 0.4375 0.40625 3.6875 2.8125
```

which leaves `.predicate` taking a more limited set of function notations than `.funs`, which seems arbitrary and somewhat limiting. Thus, is possible to add a predicate-specific helper parallel to `funs()` and `vars()` allowing `.` notation like `funs()`, enabling something like:

``` r
mtcars %>% summarise_if(ifs(mean(.) < 4), mean)
```

(I suppose `preds()` would be more parallel than `ifs()`, but it just sounds scary.) Or is this pointless, because everything eventually going to move to `purrr`'s `~.x` style notation anyway?

**Comment by krlmlr** [comment]
Thanks. I think we might be able to just reuse funs() here, but I'm not too familiar with that code. @hadley: Could you please comment?

**Comment by hadley** [comment]
This is mostly @lionel-

**Comment by lionel-** [comment]
We could take a list of functions returned by `funs()` and check that all of them return TRUE.

**Comment by vspinu** [comment]
The semantics of `...` in `xyz_at` and `xyz_if` are not quite in line with neither `subset/mutate/sumarise` familly, nor with `purrr` (though it's closer to purrr). 

As a user I would expect the dots in `mutate_at` and `summarise_at` to have similar meaning to dots in `mutate` and `summarise`.  In all `xyz_at/all/if` cases this would probably amount to not using `.funs` argument and passing `...` to `funs` internally. One can have an `args` parameter for common arguments as `funs_` does. Frankly, using `...` for extra args always felt like a waste to me.

> everything eventually going to move to purrr's ~.x style notation anyway?

Is this grand plan systematically discussed anywhere?

**Comment by lionel-** [comment]
> As a user I would expect the dots in mutate_at and summarise_at to have similar meaning to dots in mutate and summarise.

Dots in `mutate()` / `summarise()` are specifying columns whereas the colwise family is about applying an expression/function to a prespecified set of columns. So the semantics for dots are necessarily different.


> Frankly, using ... for extra args always felt like a waste to me.

Maybe this is because you use anonymous closures defined locally, which don't require argument passing? I tend to use named functions as it makes it easier to see what a map does at a glance. This is probably a matter of personal coding style. Also I think it's a good thing for dplyr mapping functions to have similar semantics to `map()` and `lapply()`.

Note that the colwise family has already been redesigned recently so we are not about to change it again.

**Comment by vspinu** [comment]
> Dots in mutate() / summarise() are specifying columns whereas the colwise family is about applying an expression/function to a prespecified set of columns.

I think "specifying columns" is not that essential and it's only for mutate (dots in summarise specify names of the computations). The essential part, IMO, is the declaration of quoted transformation. In all cases -  `...` in `mutate/summarise`, and `.funs` in `xyz_if` -  quote a computation on the data columns. 

This change basically enforces two nse mechanisms (`xyz/xyz_` and quoters a la `funs/vars/aes`) for very similar purpose. Some folks might wonder what happened to `mutate_if_`?

BTW, are different quoting functions really necessary? Wouldn't one (say `.()`) be enough for all purposes?  

> because you use anonymous closures defined locally, 

Precisely. 

> Note that the colwise family has already been redesigned recently so we are not about to change it again.

I see. I wasn't really hoping for a change, but rather for a future convergence of purrr & dplyr nse syntax. Would be nice if .cols, .pred and .funs arguments were accepting formula definition a la purrr style.

**Comment by hadley** [comment]
I think going forward both `funs()` and `vars()` should have "function semantics": each argument needs to be either a string giving the name of a function, a function, or formula describing an anonymous function (using the same approach as in purrr).  

We'll need to continue to support the bare expression with a warning and automatic translation.

**Comment by alistaire47** [comment]
Couldn't those options be passed to `.funs` unwrapped? I guess `funs` is necessary for specifying multiple functions (because `...` is already claimed) or changing names, e.g. `mtcars %>% summarise_all(funs(avg = mean, sd))`, but as an end-user, avoiding these helpers is always preferable.

On that note, `.cols` currently seems backwards given the rest of the API; I usually opt-in to using SE, not have the parameter without `vars` wrapping take strings/indices. I'd be fine with `~` quoting, though, e.g. `mtcars %>% summarise_at(~disp:qsec, mean)`, particularly if it's part of unifying the larger tidyverse API to one (or two, if necessary for SE) syntax.
