### ISSUE TITLE
Indexing (non)missing values using first() inside of summarise() no longer works.

### ISSUE THREAD

**Issue by iron0012** [hadley/dplyr#1980]
I used to be able to use the following code to get the first non-missing value within a group, but it no longer works. Now I get "Error: Unsupported vector type language." 
Rolling back to 0.4.3 confirms that it was the update to 0.5 that caused this change in behavior.

``` R
ids <- c(1,1,2,2,3,3)
data_column <- c(NA,1,2,3,3,NA)
df <- data.frame(ids,data_column)

df %>% 
group_by(ids) %>% 
summarise(data_column_first = first(data_column[!is.na(data_column)]))
```

What I wanted the code above to return is something like:

| ids | data_column_first |
| --- | --- |
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |

I don't know if this is a bug, a feature, a problem with the configuration of my environment, or if it's just a specific manifestation of some more general bug or feature, but it also occurs when trying to use last() in the same context instead of first().

Also, if you were to tell me a better alternative way to accomplish what I'm trying to do, I wouldn't complain!  :D

**Comment by the-knife** [comment]
Hello,

I have the same problem.
This doesn't seem to be related to NAs in the data.

**Comment by alexsanjoseph** [comment]
👍 Have the same issue

**Comment by julou** [comment]
same problem here with other single-table verbs (mutate, filter) since upgrading to dplyr0.5
the current workaround is obviously to use `head`, `tail` and `[[`…
A fix would be really helpful though!

**Comment by krlmlr** [comment]
Thanks, confirmed. Would you like to contribute a testthat test?

**Comment by iron0012** [comment]
Hi, thanks for your response. I'm still interested in a fix, but don't currently know enough about testing to contribute a testthat test, sorry.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1:3) %>%  summarise(f = first(x[-1]))
#> Error in summarise_impl(.data, dots): Unsupported vector type language
```

**Comment by hadley** [comment]
@krlmlr I assume this is the same root cause as #946 - we should not use the hybrid evaluator here. How hard is it to add a branch for these cases?
