### ISSUE TITLE
RStudio crash instead of error with dplyr 0.5.0

### ISSUE THREAD

**Issue by arestrom** [hadley/dplyr#1983]
The following example will crash RStudio when using 32-bit R 3.3.1 and dplyr 0.5.0. When running the same code on the 64-bit side I get the expected "Error: non-numeric argument to binary operator"

dat <- data_frame(id = seq(1, 3), expns = c("2.1", "3.4", "4.2"))
dat <- dat %>% 
  mutate(expns <- expns * -1)

A number of other similar scenarios will trigger a crash rather than the expected error message when using 32-bit R.

**Comment by kevinushey** [comment]
Does it help if you reinstall both `dplyr` and its dependencies? E.g.

```
db <- available.packages()
deps <- tools::package_dependencies("dplyr", db = db)$dplyr
install.packages(deps)
install.packages("dplyr")
```

**Comment by mcjudd** [comment]
Chiming in to confirm the same experience as @arestrom but with a different scenario.

```
data(iris)
library(dplyr)
sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
[1] magrittr_1.5    R6_2.1.2        assertthat_0.1  rsconnect_0.4.3 DBI_0.4-1       tools_3.3.1     tibble_1.0      Rcpp_0.12.5   
```
```
iris %>% filter(WrongVariable > 100)
```
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```



Reinstalling both `dplyr` and its dependencies via the method above does not resolve this issue.

**Comment by arestrom** [comment]
Unfortunately it still crashes after reinstalling. Prior to submitting the
issue I did a clean install of R, RStudio, RTools. The suggested reinstall
did not fix the issue.

**Comment by kevinushey** [comment]
Thanks for testing -- I'm guessing that this is a bad interaction with the new toolchain used to build R 3.3.0 + RStudio. I'll file an issue on the RStudio side to further investigate.

Are you able to switch to R 64bit in the interim?

**Comment by arestrom** [comment]
Thanks...no worries. I do need to use 32-bit for some DBs, but can work
around this..

**Comment by mcjudd** [comment]
The same issue is present in the interaction between R 3.3.1 and RStudio. Thanks for investigating.

**Comment by sjPlot** [comment]
That would be great, because I just have a 32bit Windows-OS.

**Comment by hadley** [comment]
@sjPlot please try out the [RStudio preview release](https://www.rstudio.com/products/rstudio/download/preview/) where this problem should now be fixed

**Comment by sjPlot** [comment]
Yes, thanks to you at RStudio, works again now!
