### ISSUE TITLE
mutate() drops attributes

### ISSUE THREAD

**Issue by t-kalinowski** [hadley/dplyr#1984]
Not sure if this is intended behavior, but i didn't see any notes about it in the news and this is a change with 0.5.

small example:

```
df <- data_frame(x = 1:2)
attr(df, "my_attr") <- "test"

df %>% str
#Classes ‘tbl_df’, ‘tbl’ and 'data.frame':  2 obs. of  1 variable:
# $ x: int  1 2
# - attr(*, "my_attr")= chr "test"

df %>%
  mutate(y= x) %>%
  str
#Classes ‘tbl_df’, ‘tbl’ and 'data.frame':  2 obs. of  2 variables:
# $ x: int  1 2
# $ y: int  1 2
```

**Comment by krlmlr** [comment]
I'm still not sure it's a good idea to carry along all attributes, for reasons outlined in the linked tibble issue.

**Comment by paulponcet** [comment]
Wouldn't a simple workaround be to add a '.keep_attributes' to dplyr verbs, and implement it in the following fashion? Enabling attributes propagation would very useful... 

    mutate_.tbl_df  <- function(.data, ..., .dots, .keep_attributes = getOption("keep_attributes")) {
      at <- attributes(.data)
      dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
      .data <- mutate_impl(.data, dots)
      shield(.data, at, .keep_attributes)
    }

    shield <- function(.data, at, .keep_attributes = "no") {
      stopifnot(is.character(.keep_attributes))
      low_keep = tolower(.keep_attributes)[[1L]]
      if (low_keep=="all") {
        attributes(.data) <- at # a bit dangerous, one has to be warned of this
      } else if (low_keep %in% c("most", "yes")) {
        attributes(.data) <- rlist::list.merge(at, attributes(.data))
      } else if (!low_keep %in% c("no", "none")) {
        attributes(.data) <- at[intersect(names(at), .keep_attributes)]
      }
      .data
    }

**Comment by hadley** [comment]
@paulponcet for now, if you add additional attributes, it's up to add a subclass and provide methods that preserve the attributes. We may reconsider in the future as part of a re-thinking of how S3 methods and subclasses should interact.

**Comment by paulponcet** [comment]
Thanks. In-between I have created a package [tribe](https://github.com/paulponcet/tribe) (still quite experimental), that includes this `shield()` function, plus a new pipe operator `%@>%` made for attributes propagation.

**Comment by maurolepore** [comment]
RE
> @paulponcet for now, if you add additional attributes, it's up to add a subclass and provide methods that preserve the attributes. We may reconsider in the future as part of a re-thinking of how S3 methods and subclasses should interact.

Here is an example: https://adv-r.hadley.nz/s3.html#inheritance
