### ISSUE TITLE
Error with non-ASCII characters in column names with `summarise_each`

### ISSUE THREAD

**Issue by jiho** [hadley/dplyr#1986]
When using a non-ASCII character and a non-valid character (space, parenthesis, etc.) in a column name and `check.names=TRUE`, the non-ASCII character is not replaced, the non-valid one is replaced and summarise_each is lost. Examples:

``` r
library(dplyr)
x <- 1:10

d <- data.frame(foo=x, `foo º`=x)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# NO

d <- data.frame(foo=x, `foo é`=x)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# NO

d <- data.frame(foo=x, `foo º`=x, check.names=F)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# OK

d <- data.frame(foo=x, `foo é`=x, check.names=F)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# OK

d <- data.frame(foo=x, `fooé`=x)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# OK

d <- data.frame(foo=x, `foo `=x)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# OK

d <- data.frame(foo=x, `foo )`=x)
summarise_each(d, funs=funs(mean(., na.rm=T)))
# OK
```

**Comment by krlmlr** [comment]
Can't replicate on Ubuntu 16.04 with UTF-8 locale nor on Windows with Latin-1 locale. Could you please show devtools::session_info()?

**Comment by hadley** [comment]
I think we have a big meta issue for all character encoding related issues, so I'm going to close this

**Comment by krlmlr** [comment]
This looks like #2243 to me.
