### ISSUE TITLE
Implement tibble::tbl_sum.grouped_df()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#1990]
for printing grouped data frames etc., requires tibble >= 1.1.

**Comment by hadley** [comment]
This should look like:

```R

#' @export
tbl_sum.grouped_df <- function(x, ..., n = NULL, width = NULL) {
  indices <- attr(x, "indices")
  if (is.null(indices)) {
    n <- ""
  } else {
    n <- paste0(" [", big_mark(length(indices)), "]")
  }

  c(
    NextMethod(),
    paste0("Groups: ", commas(group_vars(x)), n)
  )
}
```

But it doesn't currently work because tibble defines `tbl_sum.grouped_df` which is found first by S3 method dispatch. I'm not sure what we can do here apart from updating tibble first.

**Comment by krlmlr** [comment]
I think we should redesign the tibble output routines in the next versions of tibble and dplyr (tidyverse/tibble#228). Do we have a meta issue in the dplyr repo?
