### ISSUE TITLE
Suggestion: interjection function(s)

### ISSUE THREAD

**Issue by jonocarroll** [hadley/dplyr#1991]
Admittedly this is simple enough to just write and source every time it's wanted, but perhaps there's some more sophistication to add to it. Also, apologies if this already exists and I simply failed to find it.

I'd be interested in a simple function, mainly for interactive use, that is able to print a message in the middle of a chain. This would take data as an input as normal, print a `message` to the console, then output the data unmodified to the rest of the chain. A nearly trivial version might be 

```
say <- function(.data, .message) {
  message(.message)
  return(.data)
}
```

which I would use as:

```
mtcars %>% 
   group_by(cyl) %>% 
   say("caution, grouped data!") %>% 
   summarise(abc = mean(mpg))

caution, grouped data!
#> Source: local data frame [3 x 2]
#> 
#>     cyl      abc
#>   <dbl>    <dbl>
#> 1     4 26.66364
#> 2     6 19.74286
#> 3     8 15.10000
```

or involving the data somehow:

```
mtcars %>% 
   group_by(cyl) %>% 
   say(paste(nrow(.), "data points")) %>% 
   summarise(abc = mean(mpg))

32 data points
#> Source: local data frame [3 x 2]
#> 
#>     cyl      abc
#>   <dbl>    <dbl>
#> 1     4 26.66364
#> 2     6 19.74286
#> 3     8 15.10000
```

"`interject`" seems like a more appropriate name but it's not as simple as "`say`". "`interrupt`" would have been nice if it weren't for the other meaning within R.

An improvement on this would allow interjecting with an interstitial cut of the data within the chain, such as

```
peek <- function(.data, .message, .expr, ...) {
  message(.message)
  print(do.call(.expr, list(.data, ...)))
  return(.data)
}
```

(no doubt this requires some `lazyeval` treatment of `...` but that's above my pay grade). This would play out as

```
mtcars %>%
  peek("checkpoint 1", head, n=10) %>%
  filter(cyl < 6) %>%
  peek("checkpoint 2", head, n=3) %>%
  summarise(meanMPG = mean(mpg))

checkpoint 1
#>                    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
#> Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
#> Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
#> Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
checkpoint 2
#>    mpg cyl  disp hp drat   wt  qsec vs am gear carb
#> 1 22.8   4 108.0 93 3.85 2.32 18.61  1  1    4    1
#> 2 24.4   4 146.7 62 3.69 3.19 20.00  1  0    4    2
#> 3 22.8   4 140.8 95 3.92 3.15 22.90  1  0    4    2
#>    meanMPG
#> 1 26.66364
```

The advantage of this would be the ability to see what's happening in the middle of a chain without having to comment out various parts. This could also be useful for inspecting where a chain is up to for lengthy processing. When it's time to clean up the code, it's as simple as commenting out the `say`/`peek` lines.

I haven't added any considerations for edge-cases such as missing arguments, etc... as it's just a spur-of-the-moment thought.

**Comment by jonocarroll** [comment]
Actually, `peek` is probably too restrictive; it's the first use-case I had in mind, but it could be more general. Perhaps `also`?

```
mtcars %>% 
  group_by(cyl) %>%
  also("saving intermittent data to disk", write.csv, file = "mtcars.csv") %>%
  summarise(meanMPG = mean(mpg))
```

This could certainly be useful for checkpointing.

**Comment by hadley** [comment]
I think you're looking for the tee operator which is (I think) `%T>%` in magrittr.

**Comment by jonocarroll** [comment]
I was not aware of that one, and it's close but not really the same since `%T>%` can't take arguments, so the RHS evaluation needs to be a function of only the data. Plus, some functions seem to require a `print` (e.g. `head`) and a composite function can't be built for the same reason as above. I don't see an easy way to replicate my `message` example above using this either. My version captures the `.data` argument and makes it available to reference via `.`. `%T>%` seems really useful for `ggplot` side-effects. A `dplyr::tee` operator could therefore be a useful addition.

In any case, if it's not a fit for `dplyr` I'll just add it to my own processing.
