### ISSUE TITLE
distinct() drops columns

### ISSUE THREAD

**Issue by kakes-candy** [hadley/dplyr#1994]
In dplyr 0.5.0 distinct seems to drop colums if I don't specify .keep_all = TRUE. 

    `df <- data.frame(category = c("a", "a", "b"), value =  c(1, 2, 1))
     df %>% distinct(category)`

gives

```
  category
1        a
2        b
```

before, didn't it give:

```
  category value
1        a     1
2        b     1
```

**Comment by hadley** [comment]
Yes this is a deliberate change - see the release notes.
