### ISSUE TITLE
Feature request: sample_group

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#1995]
Like sample_n, but takes a grouped df and returns a random entire group.

**Comment by krlmlr** [comment]
Interesting idea. You could also do

```r
df %>% tidyr::nest(-g1, -g2) %>% sample_n(...) %>% tidyr::unnest
```

where `g1` and `g2` are your grouping variables.

@hadley: Is this a particularly common use case?

**Comment by kendonB** [comment]
I would encourage a purpose-built function as nest is slow for medium sized data. My use case is selecting a unit in a panel and plotting its time series of some variable or the residuals from a model.

**Comment by hadley** [comment]
I think you're best off creating a summarise data frame that has one row per group, sampling from that, and then anti joining.

I currently think it's a bit too specific for dplyr.
