### ISSUE TITLE
query about scoping for case_when()

### ISSUE THREAD

**Issue by nicholasjhorton** [hadley/dplyr#1996]
Am I missing something obvious regarding the scoping of case_when() in the development version of dplyr?

library(dplyr)   # development version 0.5.0.9000 installed 7/5/2016

# this doesn't work
cars <- cars %>%
  mutate(mpggrp = case_when(
    mpgCity < 20 ~ "low mpg",
    mpgCity >= 20 & mpgCity < 30 ~ "medium mpg",
    mpgCity >= 30 ~ "high mpg"
  ))

# this does
cars <- cars %>%
  mutate(mpggrp = case_when(
    cars$mpgCity < 20 ~ "low mpg",
    cars$mpgCity >= 20 & cars$mpgCity < 30 ~ "medium mpg",
    cars$mpgCity >= 30 ~ "high mpg"
  ))
glimpse(cars)

P.S. The same issues arise with recode()

**Comment by hadley** [comment]
Yes, as per the release notes `case_when()` currently doesn't work with `mutate()`  (but `recode()` does)
