### ISSUE TITLE
Filter on src_sql loss precision

### ISSUE THREAD

**Issue by andremrsantos** [hadley/dplyr#2004]
Dear staff,

I was doing some analysis when I found following issue. When I run `filter` on sql tbl, corresponding SQL query losses precision, rounding the number 1E-8 to 0.0. Right now I can avoid this issue, but some analysis might face difficulties to detect this bug on their analysis.

Follows, attached the `explain` result on my query.

> gwas %>% filter(pval <= 0.00000001) %>% select(pval) %>% explain
> <SQL>
> SELECT "pval" AS "pval"
> FROM (SELECT *
> FROM (SELECT \* FROM "diagram_gwas") AS "_W83"
> WHERE ("pval" <= 0.0)) AS "_W84"

<PLAN>
[1] pval
<0 rows> (or 0-length row.names)

> gwas %>% filter(pval <= 0.00000001) %>% select(pval) %>% explain
> <SQL>
> SELECT "pval" AS "pval"
> FROM (SELECT *
> FROM (SELECT \* FROM "diagram_gwas") AS "_W87"
> WHERE ("pval" <= 0.0)) AS "_W88"

<PLAN>
[1] pval
<0 rows> (or 0-length row.names)

I hope this help further improve this awesome package.

**Comment by krlmlr** [comment]
Thanks, confirmed:

```r
memdb_frame(a = 1e-9) %>% filter(a < 1e-8)
```

**Comment by hadley** [comment]
Minimal reprex:

```R
translate_sql(x < 1e-9)
#> <SQL> "x" < 0.0
```
