### ISSUE TITLE
Problems in handling encodings on Windows

### ISSUE THREAD

**Issue by r-suzuki** [hadley/dplyr#2005]
Hi, this would be related to #866 and #1555, but seems to be somewhat different.

### Example
Basically encodings are shown as "unknown" on Windows with Japanese locale. For example:

    > x <- transform(iris, test = Sepal.Length + 10, テスト = Petal.Width * 10)
    > Encoding(names(x)) # All "unknown"
    [1] "unknown" "unknown" "unknown" "unknown" "unknown" "unknown" "unknown"

However if we use `mutate` to create new variables, non-English column names are in UTF-8:

    > x.dp <- iris %>% mutate(test = Sepal.Length + 10, テスト = Petal.Width * 10)
    > Encoding(names(x.dp)) # Non-english column is now in UTF
    [1] "unknown" "unknown" "unknown" "unknown" "unknown" "unknown" "UTF-8"  

It does not happen if we make the same variable by `data_frame`:

    > data_frame(test = 1:3, テスト = 1:3) %>% names %>% Encoding
    [1] "unknown" "unknown"

`select` can handle UTF-8 variables:

    > select(x.dp, テスト) %>% head(3)
      テスト
    1      2
    2      2
    3      2

However `group_by` fails:

    > x.dp %>% group_by(テスト) %>% head(3)
    Error: unknown column 'テスト' 

The data made by `transform` has no problem on this:

    > x    %>% group_by(テスト) %>% head(3)
    Source: local data frame [3 x 7]
    Groups: テスト [1]
    
      Sepal.Length Sepal.Width Petal.Length Petal.Width Species  test テスト
             <dbl>       <dbl>        <dbl>       <dbl>  <fctr> <dbl>  <dbl>
    1          5.1         3.5          1.4         0.2  setosa  15.1      2
    2          4.9         3.0          1.4         0.2  setosa  14.9      2
    3          4.7         3.2          1.3         0.2  setosa  14.7      2

### Problem
At first I thought that this is a problem in `group_by` function, but the fundamental problem seems to be that the column names created by `mutate`  are in UTF-8 encoding.

### Environment

    > sessionInfo()
    R version 3.3.1 (2016-06-21)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=Japanese_Japan.932 
    [2] LC_CTYPE=Japanese_Japan.932   
    [3] LC_MONETARY=Japanese_Japan.932
    [4] LC_NUMERIC=C                  
    [5] LC_TIME=Japanese_Japan.932    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets 
    [6] methods   base     
    
    other attached packages:
    [1] dplyr_0.5.0
    
    loaded via a namespace (and not attached):
    [1] lazyeval_0.2.0    magrittr_1.5      R6_2.1.2         
    [4] assertthat_0.1    rsconnect_0.4.2.2 DBI_0.4-1        
    [7] tools_3.3.1       tibble_1.1        Rcpp_0.12.5

**Comment by r-suzuki** [comment]
As a workaround `names(x) <- enc2native(names(x))` fixed the problem in my case.

**Comment by hadley** [comment]
It's the same bug.
