### ISSUE TITLE
erroneous query causes a hang to the R interpreter 

### ISSUE THREAD

**Issue by mgacc0** [hadley/dplyr#2006]
Not sure if this is an issue in RStudio or in dplyr.

When writing a erroneus `dplyr` query, if it contains `n` instead of `n()`, the R interpreter in RStudio hangs (showing the bomb symbol).
The issue doesn't happen in RGui: it shows the message `Error: comparison (6) is possible only for atomic and list types`.

Example:
```r
df1 <- data.frame(group1=c('a', 'a', 'b'), value=c(1, 2, 3))
```
if you pretend to execute this query
```r
df1 %>%
  group_by(group1) %>%
  filter(n()>1)
```
but erroneously you execute this
```r
df1 %>%
  group_by(group1) %>%
  filter(n>1)
```
the R interpreter in RStudio hangs.

**Comment by ToledoEM** [comment]
Do not happens with RStudio Version 0.99.902 in         
`R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
[1] lazyeval_0.2.0 magrittr_1.5   R6_2.1.2       assertthat_0.1 tools_3.3.1    DBI_0.4-1      tibble_1.1    
[8] Rcpp_0.12.5 `

**Comment by kevinushey** [comment]
This is a bad interaction between 32bit versions of R 3.3.x, dplyr, and RStudio. The fix needs to occur on the RStudio end; we'll hopefully have a candidate fix for this soon.

For now, you'll need to either switch to the 64bit version of R, or switch back to R 3.2.x. (Assuming that you are indeed using the 32bit version of R; you did not post `sessionInfo()`)

**Comment by hadley** [comment]
There's now a fix available - please try the preview release of RStudio

**Comment by mgacc0** [comment]
+1
