### ISSUE TITLE
mutate_if unexpected result when no columns match criteria

### ISSUE THREAD

**Issue by derekholmes** [hadley/dplyr#2009]
mutate_if seems to apply an operation to all columns if none qualify:
`> data_frame(a=1:2,b=3:4) %>% mutate_if(is.factor,as.character) %>% str`
'data.frame':	2 obs. of  2 variables:
 $ a: chr  "1" "2"
 $ b: chr  "3" "4"

am I missing something?

**Comment by hadley** [comment]
@lionel- can you please take a look when you have a minute?

**Comment by derekholmes** [comment]
My apologies, I just realized this was the same issue as #1989
