### ISSUE TITLE
Inconsistent handling of compound assignment pipe operator

### ISSUE THREAD

**Issue by dkassler** [hadley/dplyr#2014]
When magrittr's compound assignment pipe-operator (`%<>%`) is used as part of a dplyr pipeline it works even if magrittr itself isn't attached.

    library(dplyr)
    x <- 1:4
    x %<>% `+`(1) %>% mean
    x
    ## [1] 3.5

But if the `%<>%` operator is the only operator in the pipeline and magrittr hasn't been attached, it results in an error:

    x %<>% mean
    ## Error: could not find function "%<>%"

This is easy to resolve on the user end (by simply attaching magrittr in addition to dplyr), but can lead to some confusing behavior if you aren't expecting it. Might it make more sense to export `%<>%` from dplyr to avoid this inconsistency?

```
Session info ---------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.5 (2016-04-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.893)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-07-11                  

Packages -------------------------------------------------------------------------------------------------------
 package       * version date       source        
 devtools        1.11.1  2016-04-21 CRAN (R 3.2.5)
 digest          0.6.9   2016-01-08 CRAN (R 3.2.5)
 memoise         1.0.0   2016-01-29 CRAN (R 3.2.5)
 RevoUtilsMath * 3.2.5   2016-05-03 local         
 withr           1.0.1   2016-02-04 CRAN (R 3.2.5)
```

**Comment by hadley** [comment]
This is more of a magrittr bug - can you please file it there?

**Comment by peterdesmet** [comment]
I'm running into the same problem, seems like the bug has not been reported at https://github.com/tidyverse/magrittr, so I created an issue: https://github.com/tidyverse/magrittr/issues/151
