### ISSUE TITLE
In 32-bit, left_join with incorrect "by" column names causes R / Rstudio to crash

### ISSUE THREAD

**Issue by cam333** [hadley/dplyr#2016]
The below code will cause R to crash if using 32-bit:
```
library(dplyr)
x <- data.frame(ID = c("A","B","C"), value = c(1:3))
y <- data.frame(ID2 = c("A","A","A"), value2 =c(1:3)*2)
left_join(x,y, by=c("ID"="ID")
```
I purposely made the `by` equal to the incorrect column names. I expected an error to be thrown. 

session info:

> R version 3.3.0 (2016-05-03)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Works fine with 64: 

> R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by hadley** [comment]
You need to install the preview version of RStudio
