### ISSUE TITLE
convert_class - the missing function

### ISSUE THREAD

**Issue by ikashnitsky** [hadley/dplyr#2017]
As far as I know, there is no perfect way to deal with classes of multiple variables of a dataframe easily. Just check the [variety of options at SO](http://stackexchange.com/search?q=%5Br%5D+class+for+multiple+columns). 
The ideal function I'm looking for would work like this.
```
df_converted <- df_init %>% convert_class(factor = 1:4, 
                                          character = c("Name","Brand"), 
                                          numeric = c(12,14,28))
```
So, the idea is that you can easily assign what format you prefer for specific columns. 
Does it make sense?

**Comment by hadley** [comment]
This is a job for `read::convert_types()` and the yet to be implemented https://github.com/hadley/readr/issues/250

**Comment by ikashnitsky** [comment]
May be I'm doing some things wrong in R, but quite often I face the need to convert the variables of some data sets **after** they are read. I still think the function, that I described, would be really useful.

**Comment by hadley** [comment]
That is exactly the point of `type_convert()`
