### ISSUE TITLE
Feature request: option to tell summarise to include constant variables

### ISSUE THREAD

**Issue by tmalsburg** [hadley/dplyr#2019]
Following scenario:

``` R
d %>%
 group_by(trial) %>%
 filter(region > n) %>%
 summarize(
   mean.rt = sum(rt),
   subject.id = first(subject.id),
   sentence = first(sentence),
   ...)
```

It happens all the time that I have a to include variables using `first` and usually there are many such variables.  Somewhat annoying and error prone, too.  I think it would be useful to have an option that tells `summarize` to include all columns in the output whose values are constant inside the levels of the grouping variable (or globally if there is no grouping).

**Comment by hadley** [comment]
If they're constant in your groups, I think it's easier to pull out into a separate table and re-join post summarise.  (i.e. you have the "Multiple types in one table" problem described in https://www.jstatsoft.org/article/view/v059i10)

**Comment by tmalsburg** [comment]
Yes, joining after summarize is another technique that I often use depending on the count of columns but it's just as tedious and error prone.  I know the tidy paper and about different tables for different types of data. But I'm working with complex data sets and often have ad-hoc types. In these cases, it doesn't make sense to create a separate table for that ad-hoc type when I need it only once.
