### ISSUE TITLE
matches not working in dplyr 0.5 if testthat is loaded

### ISSUE THREAD

**Issue by mheiser-md** [hadley/dplyr#2020]
matches seems to get confused with the testthat::matches in the new dplyr update:

Error message:

```r
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  matches("h")
```

Example (run in new session)
```r
> library(dplyr)

Attache Paket: ‘dplyr’

Die folgenden Objekte sind maskiert von ‘package:stats’:

    filter, lag

Die folgenden Objekte sind maskiert von ‘package:base’:

    intersect, setdiff, setequal, union

Warning message:
Paket ‘dplyr’ wurde unter R Version 3.2.5 erstellt 
> mtcars %>% 
+   select(cyl, matches("h")) %>%
+   head()
                  cyl  hp
Mazda RX4           6 110
Mazda RX4 Wag       6 110
Datsun 710          4  93
Hornet 4 Drive      6 110
Hornet Sportabout   8 175
Valiant             6 105
> 
> library(testthat)

Attache Paket: ‘testthat’

Das folgende Objekt ist maskiert ‘package:dplyr’:

    matches

Warning message:
Paket ‘testthat’ wurde unter R Version 3.2.5 erstellt 
> mtcars %>% 
+   select(cyl, matches("h"))
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  matches("h")
```

**Comment by holstius** [comment]
+1. Breaks my tests too :-/

**Comment by toonenrb** [comment]
Here's another example:
`bt <- data_frame (ba_1 = 1:3, ba_2 = 4:6, ba_3 = 2:4, at1 = 8:10, af1 = 12:14)`
This works:
`select (bt,` af1, `matches (paste0("^","ba")))`
`> # A tibble: 3 x 4
    af1  ba_1  ba_2  ba_3
  <int> <int> <int> <int>
1    12     1     4     2
2    13     2     5     3
3    14     3     6     4
`

This doesn't:
`select (bt, af1, matches (paste0("^","ra")))`
`# A tibble: 3 x 0`


` sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0    vimcom_1.2-5   setwidth_1.0-3

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.0.1        assertthat_0.1  DBI_0.4-1       tools_3.3.1     tibble_1.1     
[8] Rcpp_0.12.5 `

**Comment by hadley** [comment]
Yes, unfortunately you'll need to use `dplyr::matches()` to be explicit. It should've been this way from the beginning, but I made a mistake when designing `select()`.

(BTW please don't include session info unless explicitly requested - it's not usually helpful and just clutters up the issue)

**Comment by toonenrb** [comment]
Using `dplyr::matches()` did not solve the issue for me:

``` 
bt <- data_frame (ba_1 = 1:3, ba_2 = 4:6, ba_3 = 2:4, at1 = 8:10, af1 = 12:14)
select (bt, af1, dplyr::matches ("^ra"))
# A tibble: 3 x 0
select (bt, af1, dplyr::matches ("^ba"))
# A tibble: 3 x 4
    af1  ba_1  ba_2  ba_3
  <int> <int> <int> <int>
1    12     1     4     2
2    13     2     5     3
3    14     3     6     4
```

**Comment by hadley** [comment]
@toonenrb that's a complete different bug: #1834

**Comment by toonenrb** [comment]
Ok, thanks for the quick responses.
As a workaround I will put the `matches` as the first entry in the `select` statements. With only one `matches` in the list this will work fine, I think.
