### ISSUE TITLE
Nolonger able to access subquery object values in sql_join()

### ISSUE THREAD

**Issue by piersharding** [hadley/dplyr#2022]
Hi -
some time ago I had an issue with ambiguous column references (https://github.com/hadley/dplyr/issues/383) in table joins with the impaladb data source.  In order to get around this I wrapped the left and right sub queries with a table alias and then explicitly referenced the fully qualified column names in the join result set.  I was able to do this in the sql_join() function of the connection subclass where x and y were references to an object that contained the unformatted SQL query components including the list of column names (eg: auto_names(x$select)).

The internals of this seems to have changed quite a lot between dplyr 0.4.3 and up, so I can no longer do this.  Is there any other way that  I can influence the qualification of join result set columns without ending up doing something crude like parsing the SQL of the subqueries to find what columns they generate etc?

Thanks,
Piers Harding.

**Comment by hadley** [comment]
Does #1997 help?

**Comment by piersharding** [comment]
Yes - that should do it, although with ImpalaDB I have just managed to make it work with USING by over-riding sql_subquery (tag sql object with generated tablename) and sql_join (run equivalent of db_query_fields on left and right to determine result sets).

Thanks,
Piers Harding.

**Comment by krlmlr** [comment]
Can we close this?

**Comment by piersharding** [comment]
I'm happy for this to close as my work around still stands, although I have not tested #1997 as it has not landed in master yet.

Thanks,
Piers.

**Comment by krlmlr** [comment]
Thanks. You could try:

```r
devtools::install_github("hadley/dplyr#1997")
```
