### ISSUE TITLE
Feature Request (or Bug): Allow character vectors for group specification in group_by_

### ISSUE THREAD

**Issue by billdenney** [hadley/dplyr#2024]
Currently (version 0.4.3), group_by_ silently ignores subsequent entries in a character vector given as input:

```
library(dplyr)
mydata <- data.frame(a=rep(1:3, each=4), b=rep(1:6, each=2), c=1:12)
group_by_(mydata, c("a", "b"))
group_by_(mydata, "a", "b")
```

The first group_by_ above gives no warning or error and silently ignores group "b" and has 3 groups.  The second group_by_ above gives the expected 6 groups.

Can you please either:
1. Add the feature that character vectors are allowed as input to group_by_, or
2. Give a warning or error that only the first value is used when a vector of length >1 is given for the ... arguments.

Thanks!

**Comment by hadley** [comment]
This is all going to get ripped out and replaced with the new lazyeval stuff, so I probably won't fix, but it will be much better once that's done!
