### ISSUE TITLE
Data table memory allocation changed by dplyr::select and dplyr::one_of

### ISSUE THREAD

**Issue by utalo** [hadley/dplyr#2026]
Using this code:
```
data <- data.frame(
  a = 1:10,
  b = 10:1,
  c = 15:24)

setDT(data)
head(data)
data_sub <- dplyr::select(data,dplyr::one_of("a","b"))

data_sub[,sum:=a+b]
dplyr::select(data,dplyr::one_of("a","b"))[,sum:=a+b]
```

I get an unexpected warning:

Warning message:
In `[.data.table`(dplyr::select(data, dplyr::one_of("a", "b")),  :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.

I suspect this only happened after upgrading to dplyr 0.5.0 as earlier my code was working without the warning. I'm using data.table version 1.9.6 and R version 3.2.3.

**Comment by hadley** [comment]
Please file on the dtplyr repo.
