### ISSUE TITLE
mutate converts data.table to (only) data.frame

### ISSUE THREAD

**Issue by dxf1david** [hadley/dplyr#2028]
Hi - I use data.tables and dplyr together.  In going from v 0.4.3 to 0.5.0, it appears that using mutate on a data.table converts it to a data.frame - it's no longer a data.table.  Is this an oversight or was this planned?  I realize that I could always use setDT(df), but this would require many changes in many programs. 

Is there any possibility that mutate with a data.table could output an object that is both a data.frame and a data.table as in dplyr v0.4.3?

Thanks, David Freedman

**Comment by hadley** [comment]
This better filed on the dtplyr repo.

**Comment by dxf1david** [comment]
Thanks - I've been on vacation for a few weeks and didn't know there was a 'dtplyr' package.  Everything's hunky-dory now.
