### ISSUE TITLE
`first` and `last` fail for factors

### ISSUE THREAD

**Issue by tmalsburg** [hadley/dplyr#2029]
``` R
> first((1:3)[integer(0)])
[1] NA
> first(factor(1:3)[integer(0)])
Error: Don't know how to generate default for object of class factor
```

I would expect to get an `NA` for factors, too.  Same problem for `last`.

**Comment by krlmlr** [comment]
Thanks, confirmed. Internally, we check `is.vector(factor(letters)[0])` which is `FALSE` but should not be.

Would you like to contribute a testthat test?

**Comment by hadley** [comment]
Similar problem for POSIXct and Date. Fix should be to make `default_missing` a generic. I'll do that tomorrow.
