### ISSUE TITLE
add a default behaviour to dplyr functions to stop proceed if previously filtered data has nrow = 0

### ISSUE THREAD

**Issue by happyshows** [hadley/dplyr#2032]
Hi,

I am using dplyr with shiny in majority cases. Due to the variety of source data, the chained functions work on majority but throw out error on the rest. And my code looks more and more clumsy when I have to break the chain from time to time to inject checks function like below

when src data works fine
dat <- src %>% filter() %>% mutate() ..%>% filter() %>%. etc

not fine
dat <- src %>% filter() 
if(nrow(dat) == 0){
   return(dat)
} else{
   dat <-  dat %>% mutate() ..%>% filter() %>%. etc
  return(dat)
}

what I wish to have
dat <- src %>% filter() %>% mutate() ... etc
the chain will break and print a message on which filter condition caused the nrow = 0  instead of throwing an error like something is not found.
wrapping the whole chunk with trycatch maybe a workaround, but I don't want to miss a true error on the data transformation itself.

**Comment by hadley** [comment]
Please provide a reproducible example. dplyr should already work with 0-row data frames.

**Comment by happyshows** [comment]
While I try to recreate the issue, I realized my problem is between dplyr & tidyr, sorry about that:

mtcars %>% mutate(model = rownames(.)) %>%
  mutate(cyl = paste0('X',cyl)) %>%
  filter(grepl('Merc',model)) %>%
  spread(cyl,'cyl') %>%
    select(-X8)

mtcars %>% mutate(model = rownames(.)) %>%
  mutate(cyl = paste0('X',cyl)) %>%
  filter(grepl('VW',model)) %>%
# I created a non-exist VW model for illustration purpose
  spread(cyl,'cyl') %>%
  select(-X8)

I frequently use dplyr+tidyr together to shape the dataset. And IMHO, the second chunk could stop executing after the nrow() = 0, as there's no point to further spread the data. And when I tried to remove a col which I expected to have on majority of the data, it throws an error to "End User" whose root cause it there's no VW model, however the error msg looks like below:
Error in enc2utf8(col_names(col_labels, sep = sep)) : 
  argumemt is not a character vector

**Comment by aosmith16** [comment]
This works with `drop = FALSE` in `spread` as long as your key variable is a factor.  Your new `cyl` variable is a character variable coming out of `mutate`, so you'd need to make it a factor.

```
mtcars %>% mutate(model = rownames(.)) %>%
	mutate(cyl = factor(paste0('X',cyl))) %>%
	filter(grepl('VW', model)) %>% 
	spread(cyl, cyl, drop = FALSE) %>%
	select(-X8)
```

**Comment by hadley** [comment]
In that case, could you please fill in the tidyr repo? (Including the fully reproducible example that I made in your comment)

**Comment by shashi108** [comment]
`for(i in c("B1","B2","B3","B4")){
    
    dataset_miss_sc<-sprintf("t_%s",i)
    
    dataset_miss_sc<-subset(SCIM_Data_Analysis_L4121,Visit == i)
    
    
    dataset_set_sc<-sprintf("sc_%s",i)  
    dataset_set_co_sc<-dataset_set_sc
    dataset_set_sc<-dataset_miss_sc %>%
      gather(key = variable, value = value, SCIM_SelfCare_SubScore:SCIM_TotalScore) %>%
      group_by(Visit, variable) %>%
      summarise(mean =paste(sum(is.na(value)),"/",nrow(dataset_miss_sc),"(",round(sum(is.na(value))*100/nrow(dataset_miss_sc),digit=1),"%)"))%>%
      spread(variable, mean,drop=F)
    
    assign(dataset_set_co_sc,dataset_set_sc,.GlobalEnv)
  }`


I got error " Error in enc2utf8(col_names(col_labels, sep = sep)) :  argumemt is not a character vector "

**Comment by hadley** [comment]
@shashi108 I don't know why you filed that comment here. I'm deleting it because it doesn't seem relevant.
