### ISSUE TITLE
joins match rows on NA across datasets

### ISSUE THREAD

**Issue by garrettgman** [hadley/dplyr#2033]
Below, `inner_join()` matches two rows that each have an `NA` for the key. This seems to violate the intuition about NA's (and leads to an incorrect result). 

This seems to happen for all of the joins.

```
library(dplyr)
​
songs <- data_frame(song = c("Do-Re-Mi", "A Spoonful of Sugar"), movie = c("The Sound of Music", NA))
songs
##                  song              movie
##                 <chr>              <chr>
## 1            Do-Re-Mi The Sound of Music
## 2 A Spoonful of Sugar               <NA>
​
singers <- data_frame(movie = c(NA, "The Sound of Music"), singer = c("Arnold Schwarzenegger", "Julie Andrews"))
singers
##                movie                singer
##                <chr>                 <chr>
## 1               <NA> Arnold Schwarzenegger
## 2 The Sound of Music         Julie Andrews
​
songs %>% inner_join(singers, by = "movie")
##                  song              movie                singer
##                 <chr>              <chr>                 <chr>
## 1            Do-Re-Mi The Sound of Music         Julie Andrews
## 2 A Spoonful of Sugar               <NA> Arnold Schwarzenegger
```

**Comment by krlmlr** [comment]
Thanks. This is clearly something that SQL does differently:

```r
memdb_frame(a=c(1, NA), b = 1:2) %>% left_join(memdb_frame(a = c(1, NA), c = 2:3))
```

@hadley: Can we safely change the NA behavior for joins?

**Comment by hadley** [comment]
Yeah, an NA should never match another NA.

I have a vague memory that this has come up in the past, and some issue may have yielded the current behaviour.

**Comment by krlmlr** [comment]
See also examples in #2272.

**Comment by krlmlr** [comment]
This is fixable, but getting it right for all data types in all combinations will take some time.

**Comment by krlmlr** [comment]
@hadley: Should `NaN` match another `NaN`? We have `is.na(NaN)` in R, but current dplyr code considers `NA_real_ != NaN` but `NA_real_ == NA_real_` and `NaN == NaN`.

**Comment by krlmlr** [comment]
Joins on NA strings were deliberate at some point (#892), and are tested explicitly. This might be a breaking change unless we introduce some kind of compatibility argument. I still think we shouldn't treat NA as equal for joining.

**Comment by hadley** [comment]
I'd say `NaN` shouldn't match anything (like NA), and the string issue must've been= confusion on my part.

**Comment by krlmlr** [comment]
Joins are also used to test data frame equality. I'll add a template parameter to control this.

**Comment by hadley** [comment]
Ah, I bet that's why

**Comment by iangow** [comment]
> Yeah, an NA should never match another NA.

But SQL's `EXCEPT` behaves *as though* one is treating `NA` as matching `NA` in a join. See #2527. I guess the question is whether this kind of behaviour should be the result of some verb and, if so, whether `anti_join` (as opposed to, say, "`except`") is that verb.

**Comment by iangow** [comment]
Oh. I now see that `setdiff` is the verb that produces the desired behaviour.
