### ISSUE TITLE
coalesce for data frames?

### ISSUE THREAD

**Issue by joethorley** [hadley/dplyr#2034]
The coalesce function is fantastic - however as far as I am aware it only works on vectors

```
y <- c(1, 2, NA, NA, 5)
z <- c(NA, NA, 3, NA, 5)
z2 <- c(0, 0, 0, 0, 0)

coalesce(y, z, z2)
```

To update a column in a data frame with values from other columns in the data frame (the most likely use of the coalesce) the following code is needed
```
data <- data_frame(y = y, z = z, z2 = z2)

data$y %<>% coalesce(data$z, data$z2)
```

It would be great if coalesce was extended to data frames so one could use
```
data %<>% coalesce(y, z, z2)
```

**Comment by hadley** [comment]
Right because where would you stop? Do you want a data frame version for every vectorised function? I'll keep thinking about it - maybe an adverb would be a general approach.

**Comment by joethorley** [comment]
Yes please...
