### ISSUE TITLE
tbl_sql() slow on large tables in Monetdb

### ISSUE THREAD

**Issue by Torenable** [hadley/dplyr#2036]
OS: OS X 10.11
R: 3.3.1
dplyr: 0.5
MonetDBLite: 0.3.1
DBI: 0.4-1
database: Monetdb

**Symptom**
It took me at least 10 mins, before stopped the action, to create an `tbl` object on a large table (125M rows, 12G in size).

**My test**
My process to create the `tbl`

``` r
mdb_conn <- MonetDBLite::src_monetdb("db_name")
target_tbl <- tbl(mdb_conn, "target_table")
```

I did a little research, and my test showed that the process "hangs" at `vars <- db_query_fields(src$con, x)`, in `op_base_remote()`. It seems like `db_query_fields` request the whole table in my case.

It works as I expected if I replace `db_query_fields(src$con, x)` by `db_query_fields(src$con, build_sql(x, " limit 1"))`

An interest finding is that `db_query_fields.DBIConnection()` works well if I run it step-by-step, like

``` r
conn <- MonetDBLite::src_monetdb("db_name")
con <- conn$con
sql <- sql("select * from \"target_table\"")

# mimic the flow in db_query_fields()
sql_select(con, sql("*"), sql_subquery(con, sql), where = sql("0 = 1")) %>% 
  DBI::dbSendQuery(conn = con) %>% 
  DBI::dbFetch(0)

# output like this in my console
#  [1] col1  col2  col3 ...
# <0 rows> (or 0-length row.names)
```

Update:
I ran the same on Windows today. No issue.

**Comment by krlmlr** [comment]
@hannesmuehleisen: Could you please take a look? db_query_fields() runs the query with `WHERE 0 = 1`.

**Comment by hannesmuehleisen** [comment]
Yes will have a look dplyr 0.5 seems to have broken more than that anyway.

**Comment by hannesmuehleisen** [comment]
@krlmlr  found it :)

**Comment by hannesmuehleisen** [comment]
@Torenable hey, which dataset did you use for this?

**Comment by Torenable** [comment]
@hannesmuehleisen 1987-2008 airlines from [Data expo ‘09](http://stat-computing.org/dataexpo/2009/the-data.html)

**Comment by hannesmuehleisen** [comment]
I believe this is fixed in the dev version of MonetDBLite with dev dplyr. Could you try that perhaps?
