### ISSUE TITLE
Using %in% with databases fails when there is only one element on the rhs of %in%

### ISSUE THREAD

**Issue by Tutuchan** [hadley/dplyr#2039]
The MWE is as follows: 
```r
library(dplyr)

src <- lahman_sqlite()

# playerIDs is a vector, this works
playerIDs <- c("bemisha01", "bendech01")
tbl(src, "Batting") %>% 
  filter(playerID %in% playerIDs) %>% 
  explain()
# <SQL>
#   SELECT *
#   FROM `Batting`
# WHERE (`playerID` IN ('bemisha01', 'bendech01'))

# playerIDs is a scalar, it does not
playerIDs <- "bemisha01"
tbl(src, "Batting") %>% 
  filter(playerID %in% playerIDs) %>% 
  explain()
# <SQL>
#   SELECT *
#   FROM `Batting`
# WHERE (`playerID` IN 'bemisha01')
```

According to [this code](https://github.com/hadley/dplyr/blob/d2a34e7112fe479d2ba3d8aef16735407eb751a1/R/translate-sql.r#L204-L206) `%in%` is transformed into the SQL `IN` operator regardless of the size of the elements on the right hand side of the %in% operator. 

This is a problem when working programmatically when the length of `playerIDs` may vary.

**Comment by hadley** [comment]
Duplicate issue
