### ISSUE TITLE
Export dplyr:::replace_with function

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#2040]
I think `dplyr:::replace_with` can be useful and should be exported...
`if_else` uses it, `coalesce` uses it and probably other internal functions as well. It's a useful way to recode data even though similar things can be achieved with `if_else`.

It should work with typed NAs though but #2038 covers that, I think.

**Comment by krlmlr** [comment]
@hadley: Maybe in vctrs?

**Comment by hadley** [comment]
Yes, can you please move there?

**Comment by jlegewie** [comment]
I created an issue at hadley/vctrs. Closing this.
