### ISSUE TITLE
*_join(x, y, by=c()) should do a cross join

### ISSUE THREAD

**Issue by crowding** [hadley/dplyr#2041]
It makes sense that inner_join with no `by` or `by=NULL` will do natural join, but if I explicitly specify a join on no keys i.e. `inner_join(x, y, by=c())` I think it should produce the Cartesian product.

**Comment by krlmlr** [comment]
To me, a separate verb looks like a cleaner solution, and `by = c()` should perhaps raise an error.

**Comment by crowding** [comment]
Perhaps for interactive analysis. But when I am using dplyr in a reusable function, mathematical consistency trumps "looks cleaner."

**Comment by krlmlr** [comment]
Which result do you expect for a left join of a nonempty data frame with an empty data frame with `by = c()`?

```r
left_join(iris, mtcars[0,], by = c())
```

By definition we'd need to return all of `iris` plus the `mtcars` column filled with `NULL`-s. This means we can't simply forward this case to a (future) `cross_join()` function. I'm also not aware of any SQL DBMS that supports this corner case.

**Comment by crowding** [comment]
I agree with that test case. The SQL implementations I've checked with so
far did in fact produce that result from either LEFT JOIN or LEFT JOIN ON
1=1.

**Comment by krlmlr** [comment]
Then it might be worthwhile indeed to support it in dplyr. Nice `1=1` trick!

**Comment by krlmlr** [comment]
We should clearly think of this test if/when we do #557. Currently this looks like a lot of effort for little gain especially on the C++ side.

**Comment by hadley** [comment]
Part of more general #2240
