### ISSUE TITLE
dplyr 0.4.3 not compiling

### ISSUE THREAD

**Issue by sdhrm22** [hadley/dplyr#2042]
I am trying to load RSQLServer package on R version 3.3.1 but I am getting the following error:

Error : object ‘src_translate_env’ is not exported by 'namespace:dplyr'
Error: package or namespace load failed for ‘RSQLServer’

I came to know about the compatibility issues between dplyr version 0.5.0 and RSQLServer. I was advised to downgrade dplyr by installing version 0.4.3 (which seems to be a compatible version with RSQLServer package). 

[https://github.com/imanuelcostigan/RSQLServer/issues/68#issuecomment-234708377](url)

When i try to install 0.4.3, I get following compile error:

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dplyr.dll" OBJECTS="RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o dplyr.o filter.o group_indices.o init.o join.o select.o strings_addresses.o summarise.o test.o window.o"' had status 127

ERROR: compilation failed for package 'dplyr'

removing 'C:/Users/Admin/Documents/R/win-library/3.3/dplyr' Warning in install.packages : running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Admin\Documents\R\win-library\3.3" "C:/Users/Admin/AppData/Local/Temp/Rtmp0OvKbD/downloaded_packages/dplyr_0.4.3.tar.gz"' had status 1 Warning in install.packages : installation of package ‘C:/Users/Admin/AppData/Local/Temp/Rtmp0OvKbD/downloaded_packages/dplyr_0.4.3.tar.gz’ had non-zero exit status

**Comment by marcolle1** [comment]
I'm having the same error, any comments?

**Comment by datanerd10** [comment]
I get the same issue as well, any solution @hadley ?
![image](https://cloud.githubusercontent.com/assets/15335680/17414285/b148969e-5a39-11e6-94c9-ae85ecce34ca.png)

**Comment by howdark** [comment]
How about running codes below? I resolve the same issue with this way.

library(devtools)
pkg_url <- "https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_0.4.3.tar.gz"
install_cran(pkg_url, repos=NULL, type="source")

This way takes some time, but installation has done without error in my case.
Also loading "RSQLServer" package works well.

**Comment by kevinushey** [comment]
That error usually indicates you don't have Rtools set up correctly, which is needed when installing R packages from sources on Windows. See https://cran.r-project.org/bin/windows/Rtools/ for more information.

**Comment by ouzor** [comment]
Neither of the above tips worked for me. Instead, I downloaded the file dplyr_0.4.3.zip from MRAN (https://mran.microsoft.com/timemachine/) which hosts daily snapshots from CRAN. So no need to build from source.
