### ISSUE TITLE
count(x, wt) output misleading

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [hadley/dplyr#2043]
The following should give the total miles flown by each tail number.

``` r
flights %>% 
  count(tailnum, wt = distance)
```

However the formatting of the output suggests the summary statistic given is counts (labeled `n`) not sums.

```
# A tibble: 4,044 x 2
   tailnum      n
     <chr>  <dbl>
1   D942DN   3418
2   N0EGMQ 250866
3   N10156 115966
4   N102UW  25722
5   N103US  24619
6   N104UW  25157
7   N10575 150194
8   N105UW  23618
9   N107US  21677
10  N108UW  32070
# ... with 4,034 more rows
```

This seems misleading to me. 

Some potential solutions:
- Match to the output of

``` r
flights %>% 
  group_by(tailnum) %>% 
  summarise(sum(distance))
```

which is

```
# A tibble: 4,044 x 2
   tailnum sum(distance)
     <chr>         <dbl>
1   D942DN          3418
2   N0EGMQ        250866
3   N10156        115966
4   N102UW         25722
5   N103US         24619
6   N104UW         25157
7   N10575        150194
8   N105UW         23618
9   N107US         21677
10  N108UW         32070
# ... with 4,034 more rows
```
- Label it `sum` instead of `n`
- Label it something else that wouldn't in any other context mean sample size/count.

**Comment by krlmlr** [comment]
Changing this now would break existing code, but we could add an argument to count() that specifies the name of the n column:

```r
count <- function(x, ..., wt = NULL, sort = FALSE, n = default_n_name(x)) ...

default_n_name <- function(x) {
  ...
  message("Using n as count column name")
  ...
}
```

@hadley: Your thoughts?

**Comment by hadley** [comment]
I'm not sure. I'd almost be inclined to leave it as is, but document the behaviour better. At some point you're better off just using `summarise()` yourself.
