### ISSUE TITLE
Selecting within mutate

### ISSUE THREAD

**Issue by dhagmann** [hadley/dplyr#2050]
With dplyr 0.5.0 and R 3.3.1:

When taking the mean across a subset of columns, the calculation works when selecting the rows using ``contains()``, but not when using the range notation.

````
set.seed(5)
df <- data.frame(A  = rnorm(5),
           B1 = rnorm(5),
           B2 = rnorm(5),
           B3 = rnorm(5),
           C  = rnorm(5)) 

>            A       B1         B2          B3           C         avg
> 1 -0.2934818 0.315915  0.9515738  1.55006037  0.56222336  0.93918308
> 2  1.4185891 1.109694 -1.0095326 -0.80242318 -0.88700851 -0.23408722
> 3  1.4987738 2.215461 -2.0004727 -0.07457892 -0.46024458  0.04680297
> 4 -0.6570821 1.217104 -1.7621859  1.89566795 -0.72432849  0.45019524
> 5 -0.8527954 1.479222 -0.1426081 -0.45656894 -0.06921116  0.29334824
````

This works fine:
````
df %>%
    dplyr::mutate(avg = dplyr::select(., dplyr::contains("B")) %>% rowMeans())
````

This returns an error:
````
df %>%
    dplyr::mutate(avg = dplyr::select(., B1:B3) %>% rowMeans())
````

````
> Error: Each argument must yield either positive or negative integers
> In addition: Warning messages:
> 1: In c(-0.602907981454667, -0.472166385166945, -0.635371312524283,  :
>   numerical expression has 5 elements: only the first used
> 2: In c(-0.602907981454667, -0.472166385166945, -0.635371312524283,  :
>   numerical expression has 5 elements: only the first used
````

**Comment by hadley** [comment]
There's no reason to expect either of these to work currently.  It's definitely not supported by design.

**Comment by dhagmann** [comment]
Is there a preferred way for taking the mean of a subset of columns? This works and avoids the pipe, but I wanted to avoid referring to columns numerically:

````
df %>% dplyr::mutate(avg = rowMeans(.[2:4]))
````

**Comment by hadley** [comment]
Not currently - I have yet to figure out how functions like `rowMeans()` fit naturally into the dplyr philosophy

**Comment by cderv** [comment]
Regarding selecting within mutate, it works with standard evalutation

``` r
library(dplyr)
set.seed(5)
df <- data.frame(A  = rnorm(5),
                 B1 = rnorm(5),
                 B2 = rnorm(5),
                 B3 = rnorm(5),
                 C  = rnorm(5)) 

df %>%
  dplyr::mutate(avg = dplyr::select_(., ~ dplyr::contains("B")) %>% rowMeans())
#>             A         B1         B2         B3         C         avg
#> 1 -0.84085548 -0.6029080  1.2276303 -0.1389861 0.9005119  0.16191207
#> 2  1.38435934 -0.4721664 -0.8017795 -0.5973131 0.9418694 -0.62375298
#> 3 -1.25549186 -0.6353713 -1.0803926 -2.1839668 1.4679619 -1.29991022
#> 4  0.07014277 -0.2857736 -0.1575344  0.2408173 0.7067611 -0.06749691
#> 5  1.71144087  0.1381082 -1.0717600 -0.2593554 0.8190089 -0.39766907

df %>%
  dplyr::mutate(avg = dplyr::select_(., ~ B1:B3) %>% rowMeans())
#>             A         B1         B2         B3         C         avg
#> 1 -0.84085548 -0.6029080  1.2276303 -0.1389861 0.9005119  0.16191207
#> 2  1.38435934 -0.4721664 -0.8017795 -0.5973131 0.9418694 -0.62375298
#> 3 -1.25549186 -0.6353713 -1.0803926 -2.1839668 1.4679619 -1.29991022
#> 4  0.07014277 -0.2857736 -0.1575344  0.2408173 0.7067611 -0.06749691
#> 5  1.71144087  0.1381082 -1.0717600 -0.2593554 0.8190089 -0.39766907
```

**Comment by hadley** [comment]
It works by coincidence, not by design. I wouldn't rely on it.

**Comment by paulstillman** [comment]
Apologies for dredging up a closed topic, but I was wondering if there was any further consideration for something like this. In my field it is highly common to give individuals questionnaires with 30+ items which are then averaged together to get variables of interest (for our field, creating variables like this are much more common than the examples given in dplyr using mathematical operators on individual columns). This can get ugly quickly, especially when there are multiple such 30+ item questionnaires. It would be very helpful to have a command wherein you take (for each row) the mean of columns specified by something like select. I know this is doable in base R but the code that dhagmann suggested seems more elegant than the apply/map functions that I would otherwise use. Apologies if you've already addressed this elsewhere.
