### ISSUE TITLE
win_rank, win_recycled, and win_cumulative should be exported

### ISSUE THREAD

**Issue by adamcataldo** [hadley/dplyr#2051]
I'm extending window function support for a SQL database I work with. When I add new scalar and aggregate functions, I can use sql_prefix and sql_infix. I should be able to do the same with win_rank, win_recycled, and win_cumulative. My workaround is to replicate this functionality, but this feels ugly.

**Comment by krlmlr** [comment]
Thanks. #2126 is a similar request.
