### ISSUE TITLE
[SQL] Backends without intrinsic support for logical columns

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2052]
mutate() to a constant TRUE or FALSE currently breaks with hard-to-identify errors. In SQLite:

``` r
> memdb_frame(a = 1) %>% mutate(b = TRUE) %>% sql_render()
<SQL> SELECT `a`, TRUE AS `b`
FROM `vcdulhlkre`
> memdb_frame(a = 1) %>% mutate(b = TRUE)
Source:   query [?? x 2]
Database: sqlite 3.11.1 [:memory:]

Error: no such column: TRUE
```

I think this can be fixed in `escape.logical()`, the information how to treat logical constants can be encoded in the `sql_variant()`, perhaps with a "special" function similarly to `__dplyr_colwise_fun`.

Surprisingly, logical expressions are auto-coerced to numbers with SQLite:

``` r
> memdb_frame(a=1) %>% mutate(b = 2 == 2)
Source:   query [?? x 2]
Database: sqlite 3.11.1 [:memory:]

      a     b
  <dbl> <int>
1     1     1
```

From my experience this also affects SQL Server,  CC @imanuelcostigan.

**Comment by imanuelcostigan** [comment]
Confirm the same sql query fails when executing natively with the following error:

```sql
SELECT 'a', TRUE AS 'b'
# Msg 207, Level 16, State 1, Line 1
# Invalid column name 'TRUE'.
```

Through dplyr:

```R
ss <- RSQLServer::src_sqlserver("TEST", database = "DBItest")
dbWriteTable(ss$con, "dplyr#2052", data.frame(a = 1))
tbl(ss, "dplyr#2052") %>% mutate(b = TRUE)
# Source:   query [?? x 2]
# Database: SQLServer 13.0.1601 [sqluser@XXX/DBItest]
# 
# Show Traceback
# 
# Rerun with Debug
# Error: Unable to retrieve JDBC result set for SELECT TOP (10) *
#  FROM (SELECT  "a", TRUE AS "b"
#  FROM "dplyr#2052") "cybctqvlti": Invalid column name 'TRUE'. 
```

**Comment by hadley** [comment]
* SQLite: no support
* [MySQL](https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html): BOOL is synonym for TINYINT(1)
* [Postgres](https://www.postgresql.org/docs/9.1/static/datatype-boolean.html): BOOLEAN. Can set with 0/1
* [SQL server](https://msdn.microsoft.com/en-us/library/ms177603.aspx): BIT.
* Oracle: no support

So it looks like best approach will be to just convert TRUE to 1 and FALSE to 0. That works with all databases that have a custom type, and will work fail back to numeric for others.

**Comment by hadley** [comment]
As per #2614, this turns out to not work so well in general, so I've introduced a new generic, `db_escape_logical()` that you can override to control how literal logicals are translated.

**Comment by imanuelcostigan** [comment]
@hadley where have you introduced this generic? I can't find it in latest versions of dplyr or dbplyr

**Comment by hadley** [comment]
Oops sorry
