### ISSUE TITLE
group_if, group_at, group_all

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2053]
`group_by(everything())` doesn't work, probably because `group_by()` has `mutate()` semantics.

``` r
group_by_all <- function(.data) group_by_(.data, .dots = colnames(.data))
```

This is different from `rowwise()` iff the data contains duplicate rows.

**Comment by hadley** [comment]
I wonder if we should just provide a variant with `select()` semantics. `group_by_select()`, `group_by_where()`?

**Comment by krlmlr** [comment]
`set_group_vars()` and `add_group_vars()`? Simply `group()`?

**Comment by hadley** [comment]
I think it needs to have a similar grammatical form to `group_by()`

**Comment by hadley** [comment]
It now seems obvious that this should be `group_by_at()` and `group_by_if()`, and so I'll give it to @lionel- 🙂
