### ISSUE TITLE
pull() to collect a single column

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2054]
For regular data sources, I can do the following to obtain a count as an atomic value:

``` r
> data_frame(1:3) %>% tally %>% as.numeric
[1] 3
```

For SQL sources, I have to insert a `collect()`:

``` r
> memdb_frame(a=1:3) %>% tally %>% as.numeric
Error in magrittr(.) : (list) object cannot be coerced to type 'double'
3: traceback(1)
2: magrittr(.) at pipe.R#6
1: memdb_frame(a = 1:3) %>% tally %>% as.numeric
> memdb_frame(a=1:3) %>% tally %>% collect %>% as.numeric
[1] 3
```

Perhaps we can implement `as.numeric.tbl_lazy()` and others?

**Comment by hadley** [comment]
I think we should implement `pull()` from lplyr: https://github.com/paulponcet/lplyr. It could default to the first column.

**Comment by krlmlr** [comment]
What's special about the first column? Often you want to pull data after applying mutate(), which adds columns at the end.

The verb itself could also have more general mutate semantics: `iris %>% pull(Sepal.Length * Sepal.Width)` .

**Comment by hadley** [comment]
It's just a reasonable default because you often have a single column data frame. 

I think I like the idea of allowing it to do inline mutation too.

**Comment by krlmlr** [comment]
If the last column is the default, it will still work for one-column data frames.

**Comment by hadley** [comment]
Hmmmm, that just somehow feels less predictable to me. It probably doesn't really matter if we support inline mutate.
