### ISSUE TITLE
[SQL] FR: union_all() with more than two tables

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2055]
Doesn't work as expected.

``` r
> union_all(memdb_frame(a = 1), memdb_frame(a = 2), memdb_frame(a = 3))
Source:   query [?? x 1]
Database: sqlite 3.11.1 [:memory:]

      a
  <dbl>
1     1
2     2
```

`?union_all` mentions that `...` is "passed on to methods", but it actually doesn't seem to be used at all. I guess it might be safe to allow `union_all()` (and perhaps also `union()` and `intersect()`) for more than two tables.

**Comment by iangow** [comment]
Coming at this from an R perspective, I think this *does* work as expected in the sense that `memdb_frame(a = 3)` goes nowhere, as there's only two slots for positional arguments (`x` and `y`).

One already gets a natural implementation of this using pipes:

```r
> memdb_frame(a = 1) %>% 
+     union_all(memdb_frame(a = 2)) %>%
+     union_all(memdb_frame(a = 3))
Source:   query [?? x 1]
Database: sqlite 3.8.6 [:memory:]

      a
  <dbl>
1     1
2     2
3     3
```
Note that the resulting SQL is what you might've expected for the first approach:

```r
> memdb_frame(a = 1) %>% 
+     union_all(memdb_frame(a = 2)) %>%
+     union_all(memdb_frame(a = 3)) %>% 
+     show_query()
<SQL>
SELECT *
FROM `rtnbggkqou`
UNION ALL
SELECT *
FROM `jinkacdinp`
UNION ALL
SELECT *
FROM `ibvwziehaz`
```
It even works for four-tables:

```r
memdb_frame(a = 1L) %>% 
    union_all(memdb_frame(a = 2L)) %>%
    union_all(memdb_frame(a = 3L)) %>% 
    union_all(memdb_frame(a = 4L)) %>%
    show_query()
```


As an aside, this approach also works with inherently two-table verbs like `left_join` or `right_join`:

```r
> memdb_frame(a = 1L, x = 1L) %>% 
+     left_join(memdb_frame(a = 1L, y = 2L)) %>%
+     left_join(memdb_frame(a = 2L, z = 3L))
Joining, by = "a"
Joining, by = "a"
Source:   query [?? x 4]
Database: sqlite 3.8.6 [:memory:]

      a     x     y     z
  <int> <int> <int> <int>
1     1     1     2    NA
```

**Comment by krlmlr** [comment]
To me, `union_all()` is one of the operations where piping doesn't come as natural as supplying the input as variables or results of function calls. `bind_rows()` also accepts arbitrarily many input data frames.

**Comment by iangow** [comment]
My claim that it "works as expected" only makes sense if reading the help for the function:

> ### Usage

> ```
> intersect(x, y, ...)
> union(x, y, ...)
> union_all(x, y, ...)
> ```

It seems to make sense for these functions to be (like `bind_rows(...)`):

```
intersect(...)
union(...)
union_all(...)
```

**Comment by krlmlr** [comment]
@hadley: I still think we should support arbitrarily many arguments with set functions for data frames/SQL sources.

**Comment by hadley** [comment]
Possibly, if we can resolve the method dispatch issues for `bind_rows()` — then we could apply the same principles here.

**Comment by krlmlr** [comment]
dplyr creates generics for the set functions, the base functions have two arguments only. Is there some hidden dispatch going on?

**Comment by hadley** [comment]
If you want to deal with `n` data frames instead of just 2, we'll need to completely overhaul how dispatch works.

**Comment by hadley** [comment]
Closing this in favour of #2457

**Comment by nalimilan** [comment]
As a semi-related issue, it seems that when the order of columns differs, the generated SQL code is much less efficient. Is that something which could be improved?
```
> memdb_frame(a = 1L, b = 2L) %>% 
+     union_all(memdb_frame(b = 1L, a = 1L)) %>%
+     union_all(memdb_frame(b = 1L, a = 3L)) %>% 
+     show_query()
<SQL>
SELECT `a` AS `a`, `b` AS `b`
FROM (SELECT `a` AS `a`, `b` AS `b`
FROM (SELECT *
FROM `kjcbnxjagt`)
UNION ALL
SELECT `a` AS `a`, `b` AS `b`
FROM (SELECT *
FROM `htqwetonhi`))
UNION ALL
SELECT `a` AS `a`, `b` AS `b`
FROM (SELECT *
FROM `gqlduhkshb`)
```
