### ISSUE TITLE
"bind_rows" does not discard names from null values

### ISSUE THREAD

**Issue by mgperry** [hadley/dplyr#2056]
When given a list containing `NULL`s and `data.frame`s, bind_rows will keep the names of the `NULL`-valued entries in the list, and silently drop names from the end of the list.

Quick example, tested using R 3.1.1 and dplyr 0.5.0. This results in `virginica` entries incorrectly being labelled as `versicolor` by bind_rows.

``` r
library(dplyr)
data(iris)

iris_list = iris %>% group_by(Species) %>% sample_n(3) %>% split(.$Species)
iris_list["versicolor"] = list(NULL)
bind_rows(iris_list, .id="bind_rows_id")
```

I came across this bug using `purrr::map` with a function which returned either a data.frame or NULL. This behaviour appears to be new since 0.4.x

**Comment by krlmlr** [comment]
Thanks, confirmed. Would you like to contribute a testthat test?

**Comment by mgperry** [comment]
I've added a test at mgperry/dplyr@2132b408f. Do you have a preferred format for PRs ?

**Comment by krlmlr** [comment]
Thanks. The test looks good, just needs a skip("Currently failing") at the top. No preferred PR format, at least not for test-only PRs.
