### ISSUE TITLE
Runtime error when variables are missing in mutate() on Windows

### ISSUE THREAD

**Issue by pierucci** [hadley/dplyr#2064]
R fails with a runtime error when I launch the following code:

```r
tab <- data.frame(x = 1:5)
dplyr::mutate(tab, a = 1 - b)
```

System info:
  * R 3.3.1, `dplyr` and `lazyeval` freshly installed from Github with `devtools`.
  * MS Windows 7 32 bits.

Here are the debug files generated by Windows to describe the problem: [Temp.zip](https://github.com/hadley/dplyr/files/411612/Temp.zip).

On Ubuntu Server 16.04 this code generates the expected error: `Error: object 'b' not found`.

**Comment by hadley** [comment]
You need to install the preview edition of RStudio

**Comment by pierucci** [comment]
Upgrading RStudio to version 0.99.1281 indeed solved the problem. Thanks a lot.
