### ISSUE TITLE
tbl_sql: Can't dynamically mutate variable

### ISSUE THREAD

**Issue by matmo** [hadley/dplyr#2066]
Example:

```{r}
pg <- src_postgres(...)
tbls <- list()
for(y in 2000:2010) {
    tbls[[paste(y)]] <- tbl(pg, paste0("data_", y))) %>% mutate(year=y)
}
tbls <- lapply(tbls, collect)

tbls
$`2000`
Source:   query [?? x 2]
Database: postgres 9.4.5 [***]
   id  year
<int> <dbl>
    1  2010
    2  2010
...
$`2001`
Source:   query [?? x 2]
Database: postgres 9.4.5 [***]
   id  year
<int> <dbl>
    1  2010
    2  2010
...
```

As of `dplyr 0.5` year is always set to `2010` (last iteration of for loop), before (`0.4.3`) y was correctly resolved for each list object (`2000, 2001, ..., 2010`). 

It seems that `collect()` now uses `y` from the global environment to form the sql query when executed instead of `mutate()` replacing it with the value during the loop.

**Comment by hadley** [comment]
The problem is there aren't four ys in four different environments, there's only one. Trying putting the inside of the loop in a function
