### ISSUE TITLE
copy_to with mysql table replace NA with 0

### ISSUE THREAD

**Issue by denrou** [hadley/dplyr#2067]
Here's a simple example:

``` r
library(dplyr)
dbmysql <- src_mysql(dbname, host, user, password)
df <- data_frame(x = c(1L, 2L, NA))

copy_to(dbmysql, df, "test_fail_na")
```

The `tbl` object in the remote source does not contain the missing value, but 0 instead.

The temporary file created by `db_insert_into.MySQLConnection` is correct, so I assume the problem happens in `DBI::dbGetQuery()` call. However, I have no clue to how to fix it.

Note also that the problem seems to occur only with `mysql`.

**Comment by krlmlr** [comment]
Thanks. Does #1975 resolve this issue?

```r
devtools::install_github("hadley/dplyr#1975")
```

**Comment by denrou** [comment]
Yes #1975 resolve this issue, thanks a lot.
