### ISSUE TITLE
Negaiton of logical vector behaves strangely with pipes

### ISSUE THREAD

**Issue by UpsideDownRide** [hadley/dplyr#2070]
So I run into an issue when trying to pipe a negation of logical vector.

c(TRUE, FALSE, TRUE) %>% which
[1] 1 3

!c(TRUE, FALSE, TRUE) %>% which
[1] FALSE FALSE

which(!c(TRUE, FALSE, TRUE) )
[1] 2

**Comment by hadley** [comment]
Operator precedence.  You're evaluating `!(c(T, F, T) %>% which)`
