### ISSUE TITLE
Support for connecting to HP Vertica database.

### ISSUE THREAD

**Issue by hannesroos** [hadley/dplyr#2072]
So far dplyr includes great connectors to MySQL and PostgreSQL databases for example, however it lacks a connector to HP Vertica database. There is a separate package called [vertica.dplyr](https://github.com/vertica/vertica.dplyr) which makes that possible, though it is not compatible with dplyr 0.5.0 (it does works with dplyr 0.4.3). Perhaps it would be possible to integrate the functionality of vertica.dplyr to dplyr proper? 

Thanks,
Hannes

**Comment by hadley** [comment]
dplyr will not include any more backends, and in the future the built-in ones are likely to move to other packages.
