### ISSUE TITLE
cannot get parameter name via pipe %>%

### ISSUE THREAD

**Issue by lujiacn** [hadley/dplyr#2073]
When using %>%, cannot get parameter name, please refer the code below

`
> test_func <- function(x, name = deparse(substitute(x))) {print(name)}
> test_func(mtcars)
[1] "mtcars"
> 
> mtcars %>% test_func()
[1] "."
> 
`

**Comment by hadley** [comment]
See http://r4ds.had.co.nz/pipes.html for an explanation of how pipes work

**Comment by lujiacn** [comment]
Thank you, Hadley :)
I post the issue link to the ggvis add_data function, which intend to name the data from the parameter name. 
https://github.com/rstudio/ggvis/issues/462

Regards,
Jia
