### ISSUE TITLE
FR: UPDATE- and UPSERT-like functionality 

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2075]
Sometimes I need to update a bunch of observations in a target table with information from a second table. Currently, I'm doing something like

``` r
library(tibble)
library(dplyr)

original <- tribble(
  ~id, ~attr1, ~attr2,
    1,      1,      3,
    2,      2,      4)

new <- tribble(
  ~id, ~attr1, ~attr2,
  2,      5,      6)

combined <-
  original %>%
  left_join(new, by = "id") %>%
  transmute(id,
            attr1 = coalesce(attr1.y, attr1.x),
            attr2 = coalesce(attr2.y, attr2.x))
```

It would be great if dplyr offered a verb that does this for me. Unlike #1736 and #1216, that verb would create a new table. The code above implements UPDATE, if full_join() is used instead, it's more like UPSERT.

**Comment by krlmlr** [comment]
@hadley: Is that something we want here or in tidyr?

**Comment by hadley** [comment]
This feels more like dplyr to me, although there's clearly some connection to https://github.com/tidyverse/tidyr/issues/183

**Comment by sandys** [comment]
hey guys - is there going to be DB update built into dplyr ? if not, can someone talk about the best alternative to use ? we are using dplyr extensively... but not able to figure out what is the best way to update the db

**Comment by hadley** [comment]
@sandys updating a database table is outside the scope of dplyr. Use DBI instead.

**Comment by hadley** [comment]
Do you think a single verb `upsert()` would be sufficient?  I imagine it would have the same syntax as a  join function, although you'd have to supply the keys.

**Comment by krlmlr** [comment]
I think a single verb that always does a full join should be sufficient. See #1792 for a discussion about keys. We'd have to assume (or check) that the join keys are unique for both datasets (#1619).

Treating NA on the RHS as literal NA feels difficult to implement for SQL sources. All in all, because this functionality can be implemented completely using existing `dplyr` verbs, it may be more suitable for `tidyr`. (https://github.com/tidyverse/tidyr/issues/183 contains a lot more discussion, too.)

**Comment by hadley** [comment]
Ok, lets keep discussion there
