### ISSUE TITLE
To obtain much faster result for collect() in postgresDB

### ISSUE THREAD

**Issue by alberthkcheng** [hadley/dplyr#2083]
My remote query returned >40,000,000 row.
When I used `collect(n = 1)`, it took infinitely long to get the single result.
However, if I use `head(1) %>% collect()`, it is super quick.

I wonder does 'n' in collect() actually speed things up or just save memory?

**Comment by krlmlr** [comment]
Thanks. We can really do better here by adding head(n) if `n < Inf` .

**Comment by hadley** [comment]
I don't think we can - not all database support LIMIT, and it's really the job of `dbFetch()` to do the minimum amount of work needed to fetch `n` rows.

**Comment by krlmlr** [comment]
The work happens on the database, as soon as the query is submitted. The database can't know we only need `n` rows, unless we specifically ask for it.

Relevant question about availability of `LIMIT`: http://stackoverflow.com/q/1528604/946850.

We already have `head.tbl_lazy()` which effectively leads to adding a `LIMIT` clause in `sql_select.default()`. How should a backend for a DBMS without a `LIMIT` equivalent act here?

**Comment by hadley** [comment]
That's not my understand of how most databases work. They only compute lazily as needed as the records are retrieved.

**Comment by krlmlr** [comment]
The execution plan may vary substantially depending on how many records you ask for. Some plans are very fast at retrieving the first few rows but are slower for retrieving everything, compared to alternative plans. I could dig up an example, but I don't have one at hand.

**Comment by hadley** [comment]
I'm reasonably certain RPostgreSQL does this wrong, so I'd rather start there for `collect()`.

**Comment by krlmlr** [comment]
I have a simple example with PostgreSQL:

- A table with two columns, each with an index
- Filter on first column, arrange by second

For reading all rows, PostgreSQL performs a sequential scan with filter, because it's faster in total (but requires scanning the entire table even if later only a few rows are retrieved). With `LIMIT`, an index is used, and the result is obtained much faster. Either way, it looks like it's not only `RPostgreSQL` that can be improved in this particular case.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
N <- 1e4
db_table <-
  data_frame(a = sample.int(N), b = sample.int(N)) %>%
  copy_to(src_postgres(), ., name = dplyr:::random_table_name(), indexes = list("a", "b"))
db_table %>% filter(a < N / 10) %>% arrange(b) %>% explain
#> <SQL>
#> SELECT *
#> FROM (SELECT *
#> FROM "nqawgkkovo"
#> WHERE ("a" < 10000.0 / 10.0)) "pufefpbanw"
#> ORDER BY "b"
#> 
#> <PLAN>
#> Sort  (cost=390.02..398.36 rows=3333 width=8)
#>   Sort Key: nqawgkkovo.b
#>   ->  Seq Scan on nqawgkkovo  (cost=0.00..195.00 rows=3333 width=8)
#>         Filter: ((a)::numeric < 1000.0000000000000000)
db_table %>% filter(a < N / 10) %>% arrange(b) %>% head %>% explain
#> <SQL>
#> SELECT *
#> FROM (SELECT *
#> FROM (SELECT *
#> FROM "nqawgkkovo"
#> WHERE ("a" < 10000.0 / 10.0)) "rnjktfuzbl"
#> ORDER BY "b") "otkvhtwfuc"
#> LIMIT 6
#> 
#> <PLAN>
#> Limit  (cost=0.29..1.25 rows=6 width=8)
#>   ->  Index Scan using nqawgkkovo_b on nqawgkkovo  (cost=0.29..500.28 rows=3333 width=8)
#>         Filter: ((a)::numeric < 1000.0000000000000000)
```

**Comment by hadley** [comment]
Ok, that's compelling.
