### ISSUE TITLE
Misleading results when using identical() within mutate()

### ISSUE THREAD

**Issue by rappster** [hadley/dplyr#2088]
I'm guessing it has something to do with the way vectorization works within `mutate` and there's probably a reason for the way it's implemented, but IMO this can lead to pretty/dangerous results.

Consider the following example:

`dat <- data.frame(x = 1:4, y = c(1, 2, 10, NA))`

I'd like to check if `y` differs from `x`:

```
mutate(dat, diff = x != y)
# x  y  diff
# 1 1  1 FALSE
# 2 2  2 FALSE
# 3 3 10  TRUE
# 4 4 NA    NA
```

Has "problems" with `NA`, so I turned to `identical`:

```
mutate(dat, diff = !identical(x, y))
# x  y diff
# 1 1  1 TRUE
# 2 2  2 TRUE
# 3 3 10 TRUE
# 4 4 NA TRUE
```

Hm, that's kinda strange >> investigated and found out it had to do with diverging data types:

```
class(dat$x)
# [1] "integer"
class(dat$y)
# [1] "numeric"
```

So let's take care of aligning that:

```
dat$x <- as.numeric(dat$x)
dat$y <- as.numeric(dat$y)
```

Now, I would intuitively think that `mutate` would give me the same result as this:

```
sapply(1:nrow(dat), function(ii) {
  !identical(dat[ii, "x"], dat[ii, "y"])
})
# [1]  FALSE FALSE TRUE TRUE
```

But it still gives me this:

```
mutate(dat, diff = !identical(x, y))
# x  y diff
# 1 1  1 TRUE
# 2 2  2 TRUE
# 3 3 10 TRUE
# 4 4 NA TRUE
```

while I'd expect this 

```
# x  y diff
# 1 1  1 FALSE
# 2 2  2 FALSE
# 3 3 10 TRUE
# 4 4 NA TRUE
```

Wouldn't you aggree that this is at best misleading/dangerous if not even completely undesired?

**Comment by hadley** [comment]
It's not wonderful but it's a natural result of mutate expecting you to call a vectorised function, and automatically recycling scalars.

**Comment by rappster** [comment]
Aha! Thanks, got it. But wouldn't it maybe make sense to implement the typical "be aware, I'm recycling something" warning in such cases?

**Comment by hadley** [comment]
No, because there are lots of useful cases, i.e. `mutate(df, n = n(), mean = mean(x))`

**Comment by rappster** [comment]
Ok
