### ISSUE TITLE
No sanity check for 'by' argument in _join functions

### ISSUE THREAD

**Issue by drknexus** [hadley/dplyr#2091]
Given that many of the dplyr functions operate according to NSE it might be nice if the `by` argument of the _join functions did some sanity checking of type to be `character` or `NULL`.  This error message is a bit unclear (to me at least):

```
> iris$id <- 1:nrow(iris)
> left_join(iris[,c(6, 1:3)], iris[,c(6,4:5)], by = id)
Error in duplicated.default(by) : duplicated() applies only to vectors
```

**Comment by krlmlr** [comment]
The error message is different in the current dev version:

```
Error in UseMethod("common_by", by) : 
  no applicable method for 'common_by' applied to an object of class "function"
```

It changes to `object ... not found` if there is no function of that name. It looks difficult to fix this if we don't want to break working code (that might use a real variable to specify "by").

@hadley: Do we want to introduce a new argument `by_cols` and deprecate `by`, perhaps in the context of #557?

**Comment by hadley** [comment]
For now, we could just add a `common_by.default` with nicer text.

**Comment by krlmlr** [comment]
```r
#' @export
common_by.default <- function(by, x, y) {
  stop("by must be a (named) character vector, a list, or NULL for natural joins (not recommended in production code)",
       call. = FALSE)
}
```
