### ISSUE TITLE
wish list: example data sets that work with the basic verbs

### ISSUE THREAD

**Issue by garrettgman** [hadley/dplyr#2094]
Can we import into dplyr some of the example data sets from _R for Data Science_ or the Data Wrangling Cheatsheet? This will make it more straightforward to teach dplyr. 

The current data set, nasa, is a tbl_cube, which doesn't have a complete set of methods for the basic verbs and can't be used in two table examples.

**Comment by hadley** [comment]
I almost always use nycflights13. I'll think about something smaller to include in dplyr

**Comment by garrettgman** [comment]
Thanks. Feel free to close this issue.
