### ISSUE TITLE
mutate, etc. changes the src type of a data.table

### ISSUE THREAD

**Issue by alanpaulkwan** [hadley/dplyr#2096]
I just upgraded to the most recent version of dplyr, involving tibble. The prior version was based on the Microsoft R snapshot as of 11/30.

I don't know if it is intended, but it doesn't seem desirable that if I mutate a data.table, a base R data.frame is returned. For example, this following line of code produces a data.frame, not a data.table. 

data.table(1:50) %>% mutate(V2=1:50)

I recently discovered from Twitter that the dplyr philosophy is to copy not operate on a reference, suggesting dplyr is, while grammatically elegant and fast generally, not ideal for memory management. Fine, whatever, I've got too much RAM to g-a-f and functional-style, common-grammar coding is awesome.

Most of all, it breaks prior code, forcing me to go back and nauseatingly cast my src over and over and over in every single one of my scripts that does not presuppose a src type change using dplyr. Unbelievable. Is this intended, and is there a good reason why?

Thank you for reading.

**Comment by hadley** [comment]
Please file a bug in dtplyr

**Comment by alanpaulkwan** [comment]
I'm confused. Why is this dtplyr? I don't have dtplyr installed

**Comment by alanpaulkwan** [comment]
Oh, actually, I see. If I require dtplyr all is good. Okay, I'll just do that

**Comment by kevinushey** [comment]
`dtplyr` is the new auxiliary package that houses the `dplyr` interface for `data.table`, so if you want to use `dplyr` with `data.table`s you'll need `dtplyr` installed.
