### ISSUE TITLE
filter function  issue for multiple observations using boolean operator and logical comparison

### ISSUE THREAD

**Issue by abiyug** [hadley/dplyr#2099]
When attempting to exclude multiple observations using the Boolean operator "|" and logical comparison "!=" ,  the filter function doesn't exclude the observations.  

```
library(maps)
library(dplyr)

R version 3.3.1 (2016-06-21)
dplyr_0.5.0
```

This doesn't exclude either HI or AK   <---*******
`us.cities %>% filter(country.etc != "HI" | country.etc != "AK") %>%   subset(pop > 100000)`

Back to back filter function application works
`us.cities %>%  filter(country.etc != "HI")  %>% filter(country.etc != "AK")  %>%   subset(pop > 100000)`

A single filter with single observation exclusion also works 
`us.cities %>%  filter(country.etc != "HI") %>% subset(pop > 100000)`

**Comment by kevira** [comment]
It works according to De Morgan laws (Boolean algebra). So in you example above only observations that belong to both Ak and Hi would be excluded.

**Comment by abiyug** [comment]
They are supposed to be excluded - but they are not.  It is reproducible.
That is why I filed the case.

*'Abiyu Giday | Data Scientist*

*Antex Ultimate Solutions | abiyug.github.io <http://abiyug.github.io>(O)
703-372-1165** | (C)  703-459-0943 (e) abiyu@antexu
<http://goog_1484985646/>solutions.com <http://solutions.com/>*



This message may contain information which is confidential and subject to
legal privilege. If you are not the intended recipient, you may not peruse,
use, disseminate, distribute or copy this message. If you have received
this message in error, please notify the sender immediately by email,
facsimile or telephone and return and/or destroy the original message. The
views and/or opinions expressed within the contents of his message are not
necessarily those of Antex Ultimate Solutions Group or their affiliates and
subsidiaries.

**Comment by kevira** [comment]
According to boolean algebra De Morgan laws, this function works properly. The way you are using it, it will only exclude cities in both, Ak and Hi. If you want to exclude all Ak and Hi cities, you need to use & and not |. Please look up De Morgan laws and you will understand why.

**Comment by abiyug** [comment]
I looked it up and see that in De Morgan rule `(not a) **AND** (not b)` is the same as `'not(a **OR** b)'`. On this case (as best practice) to make it consistent with dplyr logical Boolean documentation - it is better to use  the latter. 
`us.cities %>% filter(**!(country.etc == "HI" | country.etc == "AK")**) %>% subset(pop > 100000)`

**Comment by krlmlr** [comment]
`filter(country.etc != "HI" & country.etc != "AK")` would be the right expression for your use case. Can we close this issue?

**Comment by abiyug** [comment]
Yes, we can close it.
