### ISSUE TITLE
Disconnector/finalizer for SQLite connections

### ISSUE THREAD

**Issue by bborgesr** [hadley/dplyr#2100]
Why is there no `disco` specified for sqlite connections?

As defined [here](https://github.com/hadley/dplyr/blob/master/R/src-sqlite.r#L106), `src_sqlite` returns:

``` r
src_sql("sqlite", con, path = path)
```

while [here](https://github.com/hadley/dplyr/blob/master/R/src-mysql.r#L105), `src_mysql` returns:

``` r
src_sql("mysql", con,
    info = info, disco = db_disconnector(con, "mysql"))
```

and similarly [here](https://github.com/hadley/dplyr/blob/master/R/src-postgres.r#L109), `src_postgres` returns:

``` r
src_sql("postgres", con,
    info = info, disco = db_disconnector(con, "postgres"))
```

(I also don't know why there is no `info` param to `src_sqlite`, but that is not as important to me as having a finalizer for all db connections.)

The `db_disconnector` function only requires that the underlying driver be DBI-compliant (in this case, has an implementation for `dbDisconnect`). From [here](https://github.com/hadley/dplyr/blob/master/R/dbi-s3.r#L270):

``` r
db_disconnector <- function(con, name, quiet = FALSE) {
  reg.finalizer(environment(), function(...) {
    if (!quiet) {
      message("Auto-disconnecting ", name, " connection ",
        "(", paste(con@Id, collapse = ", "), ")")
    }
    dbDisconnect(con)
  })
  environment()
}
```

This is clearly true for `RSQLite`. So is there another reason that these type of connections are not disconnected/finalized?

**Comment by krlmlr** [comment]
RSQLite connections are relatively cheap compared to a connection to a dedicated file server, but we should still close them eagerly, if only because of locking.

**Comment by hadley** [comment]
Because RSQLite connections automatically close themselves on gc()
