### ISSUE TITLE
Distinct .keep_all parameter

### ISSUE THREAD

**Issue by rrremedio** [hadley/dplyr#2107]
Would not it be more natural to the parameter ".keep_all" in distinct function to be value as TRUE? I mean, as the 'd' of dplyr denotes, i'd like to subset the data.frame (here comes the 'd') based on a set of unique values of certain variables or in all of them and keep all columns, that is, keep the data.frame.

**Comment by Artjom-Metro** [comment]
Actually as far as I understand it was the default for distinct to keep all variables until dplyr version 0.5 ([release notes](https://github.com/hadley/dplyr/releases/tag/v0.5.0)). This [issue](https://github.com/hadley/dplyr/issues/1110) contains more information why they changed the behavior.

**Comment by krlmlr** [comment]
It's probably not worth the effort to change that, as it's easy to change the behavior or write your own wrapper. @hadley: Please comment.

**Comment by hadley** [comment]
I don't think it is more natural because the values of the other columns are essentially arbitrary (because row order generally shouldn't be considered meaningful)
