### ISSUE TITLE
Feature request: anti_distinct ?

### ISSUE THREAD

**Issue by JakeRuss** [hadley/dplyr#2115]
We have `anti_join` that makes finding non-matches easier. I often find myself wanting to check which rows are being removed by a call to `distinct`. What about a complement to `distinct` that instead preserved the duplicates?

**Comment by FrankPortman** [comment]
@JakeRuss Do you mind spinning up a quick reproducible example with what you do now and what you hope to accomplish?

**Comment by JakeRuss** [comment]
@FrankPortman Sure.

```
library(dplyr)

data(mtcars)

df <- mtcars %>% distinct(mpg, cyl, .keep_all = TRUE)
```
By calling `distinct` on `mtcars` we go from 32 rows to 27. What I'd like to do is quickly switch between distinct and anti_distinct to see either (a) the 5 rows that were dropped or (b) the 10 rows with duplicates. Ideally (a) would be the default but I could see a toogle over to behavior (b) being useful too to compare potential duplicates. You might run `anti_distinct` first, look at a third column of interest, add an `arrange` to your chain, and then switch `anti_distinct` to `distinct` to finish off the sequence.

Currently, in order to get these I would rely on 
```
a <- mtcars[duplicated(mtcars[c("mpg", "cyl")]), ]

b <- mtcars[duplicated(mtcars[c("mpg", "cyl")]) | duplicated(mtcars[c("mpg","cyl")], fromLast = TRUE), ]
```

**Comment by krlmlr** [comment]
The latter can be achieved with a grouped count and a filter for n > 1. For the former it's also a filter for row_number() > 1.

@hadley: I think this is important for data cleaning, but I can't think of a good name for the verb(s).

**Comment by hadley** [comment]
Alternatively, you could add an id column, and then use `anti_join`. It seems a bit too specialised to be worth adding as a top-level dplyr verb IMO (but it would be useful in another package).

**Comment by JakeRuss** [comment]
Thanks all! 

I'll talk to @sfirke about including functions that perform a) and b) in his package `janitor`. He already has a `get_dupes` function, so he's part of the way there now.
