### ISSUE TITLE
rename_all, rename_if, rename_at

### ISSUE THREAD

**Issue by mgacc0** [hadley/dplyr#2120]
When reading CSV or Excel files, it's very common to change all column names to lowercase or apply to them some transformation (some `sub`, `gsub`, `str_replace`...).

It's possible to use the traditional syntax:

``` r
colnames(df1) <- tolower(colnames(df1))
```

It would be desirable that dplyr could have a function for it.
I have just discovered this:

``` r
df1 <- df1 %>% 
  `names<-`(tolower(names(.)))
```

( from here https://github.com/romainfrancois/budflights/blob/master/gen/gen.R )

But wouldn't it be better to have an specific function with a better syntax (more legible)?

**Comment by gorcha** [comment]
Hey, using [magrittr](https://github.com/smbache/magrittr) (from which dplyr borrows the `%>%`) it's possible to do this using the "Compound assignment pipe" operator (`%<>%`) in a very clean way:
```
names(df1) %<>% tolower
```
or
```
colnames(df1) %<>% tolower
```

**Comment by romainfrancois** [comment]
Also you can use `setNames` instead of `names<-`. Maybe this syntax would be nice: 

```r
> rename_all <- function(df, fun){ setNames(df, fun(names(df))) }
> df <- data_frame( XX = 1:10, YY=letters[1:10])
> df %>% rename_all(tolower)
# A tibble: 10 x 2
      xx    yy
   <int> <chr>
1      1     a
2      2     b
3      3     c
4      4     d
5      5     e
6      6     f
7      7     g
8      8     h
9      9     i
10    10     j
```

Using `magrittr` lambdas we could even chain operations: 

```
> df %>% rename_all(. %>% tolower %>% gsub(" ", "_", .))
# A tibble: 10 x 2
      xx   y_y
   <int> <chr>
1      1     a
2      2     b
3      3     c
4      4     d
5      5     e
6      6     f
7      7     g
8      8     h
9      9     i
10    10     j
```

but I guess something like this would be more desirable: 

```
df %>% rename_all( gsub(" ", "_", tolower(.) ) )
```

**Comment by mgacc0** [comment]
`rename_all` would be great!  :+1:

**Comment by krlmlr** [comment]
How about calling the new function `rename_each`, to match the summarise and mutate variants? @hadley: Thoughts?

**Comment by hadley** [comment]
Makes sense
