### ISSUE TITLE
query 'attribute' is NULL

### ISSUE THREAD

**Issue by itcarroll** [hadley/dplyr#2122]
I'm not getting anything about the SQL that constructed a tbl_df() using `$query`. Looks like the [database vignette](https://github.com/hadley/dplyr/blob/6153e136fa9397e88478fa6270d9d1f02eb5153e/vignettes/databases.Rmd#L105) has the same `NULL` response I'm getting at the call to `c4$query`.

**Comment by krlmlr** [comment]
Does `sql_render(c4)` work for you?

**Comment by itcarroll** [comment]
No, not in the order documented anyway. Seems to work as documented only before using `collect` on snakes (which has classes "tbl_sql", "tbl_postgres", "tbl_lazy", and "tbl")

```
> dplyr::sql_render(snakes)
<SQL> SELECT *
FROM "host_sp"
WHERE ("family" ="Colubridae")
```

```
> dplyr::sql_render(collect(snakes))
Error in UseMethod("sql_render") : 
  no applicable method for 'sql_render' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

**Comment by krlmlr** [comment]
collect() returns a data frame, sql_render() works only for SQL operations, before calling collect(). There's no way to get to the SQL statement after you have called collect(), you'll have to record it beforehand.
