### ISSUE TITLE
Requesting an update to Problem to load RSQLServer after updating dplyr to 0.5.0 

### ISSUE THREAD

**Issue by ajaykumarmvk0712** [hadley/dplyr#2123]
Hi. I am Ajay Kumar.
Is there a newer version of RSQLServer available yet which resolved the namespace issue.

I am writing in reference to the issue #1976 

Looking forward to your response.

**Comment by krlmlr** [comment]
Please look up https://cran.r-project.org/package=RSQLServer for the latest version of RSQLServer.

CC @imanuelcostigan.

**Comment by imanuelcostigan** [comment]
Waiting for #1997 to be merged and released to CRAN before releasing updated RSQLServer to CRAN.
