### ISSUE TITLE
dplyr::mutate: invalid subscript type 'closure' when using $ inside expression

### ISSUE THREAD

**Issue by ecerulm** [hadley/dplyr#2125]
I was told that maybe this behaviour is a bug in my [stackoverflow question](http://stackoverflow.com/questions/39494445/why-is-this-construct-not-allowed-in-dplyrmutate):

```
library(dplyr)
df = data.frame(col1=rep(1:5, c(3,3,2,1,1)))
df <- df %>%
     mutate(rle=sequence(rle(col1)$lengths)) 
```

fails with 

```
Error in eval(expr, envir, enclos): invalid subscript type 'closure'
```

Using `mutate(rle=sequence(rle(col1)[["lengths"]])` works so it seems that the problem is the use of `$lengths` vs `[["lenghts"]]`.

**Comment by krlmlr** [comment]
Works with #2190, which will be merged soon.
