### ISSUE TITLE
need function export in order to create redshift backend

### ISSUE THREAD

**Issue by mtreadwell** [hadley/dplyr#2126]
In reference to Issue #962

As suggested, I've been working to create a new database backend for Redshift. That part is complete and now I need to create a method for sql_translate_env to work with the RedshiftSQLConnection class created with the help of RRedshiftSQL: https://CRAN.R-project.org/package=RRedshiftSQL

In order to create those methods in a new package I need the functions partition_group(), partition_order(), and over() exported from dplyr.

Is this possible?

**Comment by krlmlr** [comment]
The partitioning code currently works with a private environment to handle state. It looks like a fair bit of refactoring will be necessary beforehand. @hadley, could you please comment?

**Comment by hadley** [comment]
I think the private environment + call stack is this right approach. Shouldn't be too hard to export the needed functions when I'm next working on dplyr.
