### ISSUE TITLE
na_if documentation incomplete

### ISSUE THREAD

**Issue by mdlincoln** [hadley/dplyr#2127]
The [current documentation](https://github.com/hadley/dplyr/blob/master/R/na_if.R#L6-L7) for the `y` parameter for `na_if` seems to stop mid-thought:

```
#' @param x Vector to modify
#' @param y If th
```

**Comment by soniampub** [comment]
@hadley I would like to take this. I am a newbie in open source. Please let me know what should be the correct description for y parameter.

**Comment by hadley** [comment]
Maybe "Replacement values for missing \code{x}"?

**Comment by soniampub** [comment]
@hadley Or May be "Value in  \code{x} to be replaced" As we can replace any value with NA, and not necessarily value that are missing in x, it can be 0 or empty string. Please suggest.

**Comment by soniampub** [comment]
@mdlincoln @hadley let me know what is the right str according to you guys and I will create a PR.

**Comment by hadley** [comment]
Looks like this got merged
