### ISSUE TITLE
dplyr::filter()

### ISSUE THREAD

**Issue by biadias** [hadley/dplyr#2128]
Hi, I am trying to filter some arguments on a data.frame. However the function is not working properly.

This is what I am using as code:

cod_M<-dplyr::filter(TLdecfilter, source== c("Cod-M_CAB","Cod-M_RAB"))

it gives me:
cod_M<-dplyr::filter(TLdecfilter, source==c("Cod-M_CAB", "Cod-M_RAB"))
> cod_M
     source target    value
1 Cod-M_CAB     IV 0.128000
2 Cod-M_CAB     VI 0.009500
3 Cod-M_CAB   VIII 0.000188
4 Cod-M_CAB      X 0.000001
5 Cod-M_RAB     IV 0.231000
6 Cod-M_RAB     VI 0.013600
7 Cod-M_RAB   VIII 0.000250
8 Cod-M_RAB      X 0.000001
> 

However, it is cutting part of the data that I want to filter. 
If I use just:

cod_MCAB<-dplyr::filter(TLdecfilter, source=="Cod-M_CAB")

> cod_MCAB
     source target    value
1 Cod-M_CAB    III 0.103000
2 Cod-M_CAB     IV 0.128000
3 Cod-M_CAB      V 0.049900
4 Cod-M_CAB     VI 0.009500
5 Cod-M_CAB    VII 0.001500
6 Cod-M_CAB   VIII 0.000188
7 Cod-M_CAB     IX 0.000017
8 Cod-M_CAB      X 0.000001
> 

%and 

 cod_MRAB<-dplyr::filter(TLdecfilter, source=="Cod-M_RAB")
> cod_MRAB
     source target    value
1 Cod-M_RAB    III 0.189000
2 Cod-M_RAB     IV 0.231000
3 Cod-M_RAB      V 0.077500
4 Cod-M_RAB     VI 0.013600
5 Cod-M_RAB    VII 0.002020
6 Cod-M_RAB   VIII 0.000250
7 Cod-M_RAB     IX 0.000021
8 Cod-M_RAB      X 0.000001

do you have any idea why when I am pulling two arguments I am having this problem?

Thank you,

**Comment by the-knife** [comment]
Hello,

It looks like you made a basic syntax error.
Try `source %in% c("Cod-M_CAB", "Cod-M_RAB")`

Maybe you should be more cautious before  claiming a function is "not working properly".
