### ISSUE TITLE
Bug Report: funs with colon operator fails (e.g. `funs(base::mean(.,na.rm = TRUE))`)

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#2140]
Using `funs` (as part of `mutate_at` and other functions ) with colon operator fails.

```
funs(mean(.,na.rm = TRUE))
funs(base::mean(.,na.rm = TRUE))
# Error in vapply(dots[missing_names], function(x) make_name(x$expr), character(1)) : 
#  values must be length 1,
# but FUN(X[[1]]) result is length 3
```

**Comment by krlmlr** [comment]
`funs(base::mean)` also doesn't seem to work (I tried `funs(forcats::fct_inorder)`).

**Comment by krlmlr** [comment]
Is this a duplicate of #2057 and #2089?

**Comment by jlegewie** [comment]
Yes, looks like a duplicate. I will close. Just reopen if you think this issue still makes sense. The minimal reproducible example is easier here.
