### ISSUE TITLE
R session aborted

### ISSUE THREAD

**Issue by yannpaulo** [hadley/dplyr#2142]
The following error always occur when using select this way
data2 <- select(data, -Selection:p1h18l)

But not this way:
data2 <- select(data, -Selection, p1h18l)
thanx!

![image](https://cloud.githubusercontent.com/assets/7464255/18771615/b6063b60-8116-11e6-8282-320bfbc07655.png)

**Comment by hadley** [comment]
Update your RStudio

**Comment by yannpaulo** [comment]
That solution didn't solved the problem...
