### ISSUE TITLE
Feature Request: swap_if(), conditional swapping of values between columns

### ISSUE THREAD

**Issue by bhive01** [hadley/dplyr#2149]
Made a mistake in a partial dataset of a very manual experiment (costly to redo) and realized I needed a conditional swap between two columns. 

I envision it looking something like this in practice. I wish I could figure out how to include it in a mutate(), but it requires returning two columns at once. 

``` r
dt %>%
    swap_if(., condition, Column1, Column2)
```

My attempt at implementation leaves a lot to be desired and is hacked entirely from if_else/replace_with in dplyr. 

``` r
library(tidyverse)

dt <- tibble(V1=c(1,2,4), V2=c("a","a","b"), V3=c(2,3,1))

swap_if<- function (condition, val1, val2, missing = NA) 
{
    if (!is.logical(condition)) {
        stop("`condition` must be logical", call. = FALSE)
    }
    out1 <- val1[rep(NA_integer_, length(condition))]
    out2 <- val2[rep(NA_integer_, length(condition))]

    out1[condition & !is.na(condition)] <- val2[condition & !is.na(condition)]
    out2[condition & !is.na(condition)] <- val1[condition & !is.na(condition)]

    out1[!condition & !is.na(condition)] <- val1[!condition & !is.na(condition)]
    out2[!condition & !is.na(condition)] <- val2[!condition & !is.na(condition)]

    tibble(out1, out2)
}

#swaps, but want to use in a mutate call
swap_if(dt$V2=="b", dt$V1, dt$V3)
```

**Comment by bhive01** [comment]
Current workaround is the following as suggested by @bpbond 
Clear, but not concise. I have to swap many columns sadly so this explodes quickly.
```
df %>% 
    mutate(newV1=ifelse(V2=="b",V3,V1),
                 newV3=ifelse(V2=="b",V1,V3),
                 V1=newV1,
                 V3=newV3) %>%
    select(-newV1, -newV3)
```

**Comment by krlmlr** [comment]
@hadley: Is this a particularly common use case we want to support?

**Comment by hadley** [comment]
No, I don't think so.  

However, there is a general pattern that would help resolve this issue: if `summarise()` and `mutate()` could accept data.frames/tibbles as return values, you could do this in a single step:

```R
swap_if <- function(cond, x, y) {
  out_x <- ifelse(cond, y, x)
  out_y <- ifelse(!cond, x, y)
  
  setNames(tibble(out_x, out_y), c(expr_name(x), expr_name(y))
}

df %>% mutate(swap_if(V2 == "b", V1, V3))
```

I don't think the code for getting the names is quite right, but it should be something along those lines.

That would also simplify the implementation of `tidy::separate()`, `tidyr::unite()` etc because you'd be able to make use of `mutate()`.

**Comment by krlmlr** [comment]
Returning a tibble is related with #2171.

**Comment by krlmlr** [comment]
But I was confused I think. @hadley: Wouldn't your code work with do()?

**Comment by hadley** [comment]
Yes, but `do()` is very inefficient.

**Comment by krlmlr** [comment]
Groupwise do(), yes. But isn't do() over the entire data frame just a single vectorized function call?

The syntax with the dot is a bit awkward, though.

**Comment by hadley** [comment]
Oh indeed, it's just that with `mutate()` you get the nicer implicit scoping.
