### ISSUE TITLE
Documentation request re helper verbs: mutate_helpers, summarize_helpers, etc

### ISSUE THREAD

**Issue by AHoerner** [hadley/dplyr#2150]
A request : The dplyr reference manual has an entry for select_helpers, but no equivalent entry for mutate_helpers, summarize_helpers, arrange_helpers, etc. I would find that useful, especially since the identity and workings of the helper verbs seems like the thing that changes fastest between versions. The RStudio Data Wrangling Cheatsheet, for example, reflects none of the 0.5 changes in helper verbs.

**Comment by hadley** [comment]
That's because there aren't helpers for `mutate()` etc in the same sense.
