### ISSUE TITLE
Documentation problem and request re arrange & 0.5

### ISSUE THREAD

**Issue by AHoerner** [hadley/dplyr#2151]
I am not quite sure of this, but it appears to me that the vignette has not kept up with all the changes made in version 0.5. In particular, the 0.5 documentation says that arrange ignores grouping, while the vignette says that arrange sorts first by group. I am guessing that you want the vignette to match the current version. There are other 0.5 changes you may or may not want to check -- I think the original version mentioned nearly all the helper verbs then in place, but I do not believe this is still true.

Also, a related **documentation** (not functional change) request: It seems clear that different people have different intuitions about how arrange should work. I am one of those whose intuitions match with the "arrange affects all the row-related verbs equally" rational. But this is not another request for change. I assume you have thought about these things more deeply than I, and have selected the current set of rules for reasons that are good and sufficient. However, as someone who has not followed the controversy blow by blow, I am not sure what those good and sufficient reasons are. So my request is, either in the vignette or in the manual, one or two sentences about the rationale for the current rule would make it easier for me to understand that rule, remember it, and use it effectively; and I think this may be true for many of those whose intuitions run that way.

**Comment by hadley** [comment]
I'll take on updating the documentation as part of #2318
