### ISSUE TITLE
failed to assign NativeSymbolInfo for rhs since rhs is already defined in the ‘lazyeval’ namespace

### ISSUE THREAD

**Issue by RMHogervorst** [hadley/dplyr#2153]
I'm having a random recurring warning. It happens sometimes, and sometimes not. 

```
dataset20132014clean %>% filter(cijfernl == 7.5)
Warning message:
failed to assign NativeSymbolInfo for rhs since rhs is already defined in the ‘lazyeval’ namespace
```

I am unable to reproduce it, but it occurs every day and I don't know how. 
The function still produces valid output. But this warning bugs me.

**Comment by RMHogervorst** [comment]
i'm using dplyr 0.5.0 on a windows 10 64bit pc.
I will update tibble and see if that changes anything

**Comment by RMHogervorst** [comment]
Got the same error after updating.

```
> devtools::session_info()
Session info -----------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  Dutch_Netherlands.1252      
 tz       Europe/Berlin               
 date     2016-09-27                  

Packages ---------------------------------------------------------
 package    * version date       source        
 assertthat   0.1     2013-12-06 CRAN (R 3.3.0)
 colorspace   1.2-6   2015-03-11 CRAN (R 3.3.0)
 DBI          0.5-1   2016-09-10 CRAN (R 3.3.1)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 dplyr      * 0.5.0   2016-06-24 CRAN (R 3.3.1)
 ggplot2    * 2.1.0   2016-03-01 CRAN (R 3.3.0)
 ggvis        0.4.3   2016-07-22 CRAN (R 3.3.1)
 gtable       0.2.0   2016-02-26 CRAN (R 3.3.0)
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.0)
 httpuv       1.3.3   2015-08-04 CRAN (R 3.3.0)
 lazyeval     0.2.0   2016-06-12 CRAN (R 3.3.0)
 magrittr     1.5     2014-11-22 CRAN (R 3.3.0)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.0)
 mime         0.5     2016-07-07 CRAN (R 3.3.1)
 munsell      0.4.3   2016-02-13 CRAN (R 3.3.0)
 pacman       0.4.1   2016-03-30 CRAN (R 3.3.1)
 plyr         1.8.4   2016-06-08 CRAN (R 3.3.0)
 R6           2.1.3   2016-08-19 CRAN (R 3.3.1)
 Rcpp         0.12.7  2016-09-05 CRAN (R 3.3.1)
 rsconnect    0.4.3   2016-05-02 CRAN (R 3.3.1)
 scales       0.4.0   2016-02-26 CRAN (R 3.3.0)
 settings     0.2.4   2015-10-27 CRAN (R 3.3.1)
 shiny        0.14    2016-09-10 CRAN (R 3.3.1)
 tibble       1.2     2016-08-26 CRAN (R 3.3.1)
 validate     0.1.5   2016-06-24 CRAN (R 3.3.1)
 VGAM         1.0-2   2016-05-27 CRAN (R 3.3.0)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)
 xtable       1.8-2   2016-02-05 CRAN (R 3.3.0)
 yaml         2.1.13  2014-06-12 CRAN (R 3.3.0)
```

**Comment by RMHogervorst** [comment]
I found a way to reproduce this behavior 
and I have reduced it to one project where this happens

It happens every time I step back in the project. or restart the R session
1. I close the project.
2. Save to .RData
3. reopen Rstudio project
4. load dplyr (library(dplyr) )
5. Use the select /filter command
```
iris %>% select(1:3)  %>% View()
iris %>% select(1:3)
mtcars %>% filter(mpg < 20) 
```

**Comment by krlmlr** [comment]
@kevinushey: Does this ring a bell?

**Comment by kevinushey** [comment]
Unfortunately no, and I wasn't able to reproduce with the steps described by @RMHogervorst.

If this only occurs within one R project, it's possible that project has some object in the global environment (that gets restored on load; ie, in the `.RData`) that's causing this interaction.

**Comment by RMHogervorst** [comment]
Yeah it seems to be in one project, but I dont know how to inspect the
.Rdata object. I ll be back

Op 7 nov. 2016 19:10 schreef "Kevin Ushey" <notifications@github.com>:

**Comment by kevinushey** [comment]
@RMHogervorst: after loading the project, you can look at the items in the Environment pane; or with `ls()` (although it's hard to know if anything would be useful from that output).

Are you able to reproduce if you move that `.RData` object away? If so, are you able to share that `.RData` object?

**Comment by RMHogervorst** [comment]
Well it's kind of hard to do, because I deleted everything in my user space
rm(list = ls() ) and that did remove the problem. I have to think how I'm
going to reproduce this problem.

Op 7 nov. 2016 20:55 schreef "Kevin Ushey" <notifications@github.com>:

**Comment by hadley** [comment]
Closing here - please see discussion at linked lazyeval issue.
