### ISSUE TITLE
Get rid of can_promote()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2155]
in C++ code; just try to promote and stop or return NULL in case of failure.

Motivation: Avoid situations where can_promote() returns true but promote() or promote_collecter() fails. 
Also, DelayedProcessor and Collecter seem to share some common concepts, both probably belong in vctrs.

**Comment by hadley** [comment]
Can we just lump this into the changes we'll need to implement in vctrs?

**Comment by krlmlr** [comment]
I think so (#2432).
