### ISSUE TITLE
collect() on RPostgres fails if grouped and zero rows in output

### ISSUE THREAD

**Issue by mtreadwell** [hadley/dplyr#2156]
I am seeing a lot of these errors. I cannot provide reproducibility because they occur when I connect to a database using `src_postgres()`. Specifically, they always seem to occur after an `inner_join()` followed by a `filter()`.

The 'xxx' in the error message always changes. I have seen NULL, 'promise', among others.

```
Error in grouped_df_impl(data, unname(vars), drop) : 
  CHAR() can only be applied to a 'CHARSXP', not a 'xxx'
```

**Comment by kevinushey** [comment]
The error probably implies that there is some memory protection issue in `dplyr` itself. Can you provide a reproducible example? In particular, you might find that running your code with `gctorture(TRUE)` makes the problem manifest earlier (although the code will run much more slowly).

**Comment by data-raccoon** [comment]
I get those errors mostly when the filter matches no lines - so your output should be empty - but other commands like grouping and summarizing are scheduled.

**Comment by karldw** [comment]
Here's a reproducible example.  Note that the `ct` variable is never greater than 4, so the output table is empty.  When it's not empty, the code runs, as in the second example.

```r
mtcars2 <- copy_to(src_postgres(), mtcars)

# Raises the grouped_df_impl error:
mtcars2 %>% 
  select(cyl, carb) %>%
  distinct(cyl, carb) %>%
  group_by(cyl) %>%
  mutate(ct = n()) %>%
  filter(ct > 4) %>%
  collect()

# Runs fine:
mtcars2 %>% 
  select(cyl, carb) %>%
  distinct(cyl, carb) %>%
  group_by(cyl) %>%
  mutate(ct = n()) %>%
  filter(ct > 0) %>%
  collect()
```

It's something to do with the grouping; adding `ungroup` makes the example work as well.

```r

# This works:
mtcars2 %>% 
  select(cyl, carb) %>%
  distinct(cyl, carb) %>%
  group_by(cyl) %>%
  mutate(ct = n()) %>%
  filter(ct > 4) %>%
  ungroup() %>%
  collect()
```

**Comment by hadley** [comment]
When I run this code I see the error "unknown column 'cyl'", so at least that's better.

Otherwise I think the source of the bug is the RPostgreSQL package — when there are 0 rows it is also returning 0 columns. I'll be able to prevent the error easily once #2388 is merged, but a full fix will have to wait for the completion of RPostgres.
