### ISSUE TITLE
filter_first()

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#2158]
Version of `filter()` that would stop at first occurrence.

**Comment by krlmlr** [comment]
Hmm... How do we make this substantially more efficient than

```r
first <- function(x) { w <- head(which(x), 1); x[] <- FALSE; x[w] <- TRUE; x }
filter(data, first(...))
```

in the case of data frames? SQL engines should be able to optimize `. %>% filter %>% head` by themselves.

**Comment by hadley** [comment]
You can also use `cumany()` or `cumall()` for this sort of selection
