### ISSUE TITLE
Should arrange respect ordered factors?

### ISSUE THREAD

**Issue by puterleat** [hadley/dplyr#2161]
I just came across this...

```
data_frame(x=ordered(c("First", "Second", "Third", "Fourth"))) %>% 
  arrange(x)
```
Which produces:

```
# A tibble: 4 × 1
       x
   <ord>
1  First
2 Fourth
3 Second
4  Third
```

My feeling is that it would be nicer if arrange worked with respect to the ordering of the factor, rather than the alphanumeric sort. Is there a simple workaround though?

**Comment by romainfrancois** [comment]
Consider this: 

```
> o <- ordered(c("First", "Second", "Third", "Fourth"))
> o
[1] First  Second Third  Fourth
Levels: First < Fourth < Second < Third
```

So not really a `dplyr` problem.
