### ISSUE TITLE
Error with joins when using numeric and integer ID columns with column attributes

### ISSUE THREAD

**Issue by dannyparsons** [hadley/dplyr#2164]
When I try to join on an integer column with a numeric column, if the joining columns have attributes added to them it gives an **incompatible types (integer / numeric)** error. 
Example:

```
require(dplyr)
df1 <- data.frame(V1 = c(1, 2, 3), V2 = letters[1:3])
df2 <- data.frame(V1 = 1:3, V3 = LETTERS[1:3])
full_join(df1, df2)
# (Runs correctly)
attr(df1$V1, "foo") <- "bar"
full_join(df1, df2)
# Joining, by = "V1"
# Error: Can't join on 'V1' x 'V1' because of incompatible types (integer / numeric)
```

Also note that plyr::join does not give an error in the same situation:  

```
require(plyr)
df1 <- data.frame(V1 = c(1, 2, 3), V2 = letters[1:3])
df2 <- data.frame(V1 = 1:3, V3 = LETTERS[1:3])
plyr::join(df1, df2)
# (Runs correctly)
attr(df1$V1, "foo") <- "bar"
plyr::join(df1, df2)
# (Runs correctly)
```

I use column attributes quite a lot so it would be good if this didn't give an error. I think this might be related to #228.

**Comment by krlmlr** [comment]
Confirmed, but I'm not sure we can change this behavior. As a work-around, you could create a temporary column for the duration of the join.
