### ISSUE TITLE
Compound assignmet pipe not found when there's only one verb on rhs

### ISSUE THREAD

**Issue by 3inar** [hadley/dplyr#2165]
I get a "could not find function" error when there's only one verb on right-hand side of the `%<>%` operator. Reproducible example:

``` r
library(tidyverse)
data(iris)
iris %<>% select(-Species)    # won't work
## Error: could not find function "%<>%"
iris %<>% filter(Sepal.Length < 5)    # won't work
## Error: could not find function "%<>%"

iris %<>% filter(Sepal.Length < 5) %>% select(-Species)  # works fine
```

Session info:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0     purrr_0.2.2     readr_1.0.0     tidyr_0.6.0     tibble_1.2      ggplot2_2.1.0   tidyverse_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6      assertthat_0.1   R6_2.1.3         grid_3.3.1       plyr_1.8.4       gtable_0.2.0    
 [7] DBI_0.5          magrittr_1.5     scales_0.4.0     lazyeval_0.2.0   tools_3.3.1      munsell_0.4.3   
[13] colorspace_1.2-6
```

**Comment by krlmlr** [comment]
@smbache: Any idea?

**Comment by smbache** [comment]
That's weird: can reproduce the issue on r-fiddle, but not on my own machine, with magrittr 1.5; can you reproduce using the 1.6 ("update") branch? It's a better tokenizer for the chain.

**Comment by 3inar** [comment]
Can confirm that I get the same behavior with the `update` branch

**Comment by smbache** [comment]
I think it's simple: tidyverse does not (yet) attach magrittr, and dplyr only exports `%>%`. The reason that it works with more pipes is that `%>%` will know about `%<>%` and construct the pipeline accordingly. 
Makes sense?

**Comment by 3inar** [comment]
That seems to be it. This works fine:
```{r}
library(magrittr)
library(dplyr)
iris %<>% select(-Species)
```

This does not:
```{r}
library(dplyr)
iris %<>% select(-Species)
## Error: could not find function "%<>%"
```

Should I maybe close this as not a bug? Not sure whether one should expect dplyr to export `%<>%`, and if, as you seem to imply, tidyverse will attach magrittr in later versions it might be fine.

**Comment by smbache** [comment]
I'm pretty sure it will not appear in dplyr. But it's not a bug - if anything it's a bit that it works when there are more pipes... but yes - this could be closed.
