### ISSUE TITLE
Summarise nth & order_by crashes R (on Windows)

### ISSUE THREAD

**Issue by avsmith** [hadley/dplyr#2166]
A combination of 'summarise', 'nth', and 'order_by' crashes R on Windows (but not Mac).

Make sample data

``` r
library(dplyr)

set.seed(42)

# Simulate data
# obs is the total number of observations
# ninds is the number of unique individuals
obs <- 25000
ninds <- 5000

# Simulate BP data
id <- sample(1:ninds,obs,replace=TRUE)
SBP <- as.integer(rnorm(obs, 120, 15))
DBP <- as.integer(rnorm(obs,90,10))

# Put all into a data frame, adding a value for the visit number
bppheno <- data_frame(id,SBP,DBP) %>% 
  group_by(id) %>% 
  mutate(visit=row_number())
```

The following statement crashes R 3.3.1 on Windows (but not Mac). [dplyr 0.5.0]

``` r
bppheno_characteristics <- bppheno %>%
  dplyr::group_by(id) %>%
  dplyr::summarise(N_BP=n(), FIRST_SBP_DPLYR=first(SBP, order_by=visit))
```

The following variant without the wrapper does not crash R (on Windows)

``` r
bppheno_characteristics <- bppheno %>%
  dplyr::group_by(id) %>%
  dplyr::summarise(N_BP=n(),FIRST_SBP_RAW=SBP[[order(visit)[1]]])
```

Also, the following variant (explicitly calling dplyr::first) does not crash R (on Windows)

``` r
bppheno_characteristics <- bppheno %>%
  dplyr::group_by(id) %>%
  dplyr::summarise(N_BP=n(), FIRST_SBP_DPLYR=dplyr::first(SBP, order_by=visit))
```

**Comment by kevinushey** [comment]
Are you running this code within RStudio? There's a known bad interaction between R 3.3.x and RStudio that can cause crashes like this. You might want to try updating to the [preview release](https://www.rstudio.com/products/rstudio/download/preview/), which contains a fix for this.

**Comment by avsmith** [comment]
No, I can get the behavior independently of RStudio.

**Comment by krlmlr** [comment]
Thanks, confirmed, I'm getting a SIGSEGV on Ubuntu 16.04. 

Would you like to contribute a testthat test?

**Comment by krlmlr** [comment]
Other hybrid functions are affected by similar problems, #2299 is the canonical issue.

**Comment by stephematician** [comment]
I assume I am having the same problem. I find that the following works fine in Windows:

    data.frame(x=c(1,2,3)) %>% summarise(b=first(x, order_by=c(-2,-3,1)))

As does this:

    data.frame(x=c(1,2,3), z=c(-2,-3,1)) %>% summarise(b=first(x, order_by=z+0))

But this does not:

    data.frame(x=c(1,2,3), z=c(-2,-3,1)) %>% summarise(b=first(x, order_by=z))

**Comment by krlmlr** [comment]
Have you tried the development version? An update should hit CRAN soon.
