### ISSUE TITLE
Replacement of table in remote src by copy_to function

### ISSUE THREAD

**Issue by akaever** [hadley/dplyr#2167]
It would be really useful having support (e.g. an additional parameter) for the replacement of an existing table in a remote src when using the dply::copy_to function. Currently, execution stops when the corresponding table exists (dplyr::db_has_table check). Depending on the additional parameter, the table can be dropped (possibly using CASCADE) and re-created in the same transaction block. 

However, there's an issue with this procedure and concurrent sessions: When trying to access a large remote table (tested in PostgreSQL) while the table is re-created in another process, the operation is delayed (as expected) but finally results in an error:

ERROR:  could not open relation with OID 321732

While the table is deleted and re-created, other processes try to access the old OID, which doesn't exist any more when the first transaction is finished. 

I have tried to drop and re-create columns instead of dropping the entire table. However, in PostgreSQL, this results in references to dropped columns (e.g. ........pg.dropped.1........ when executing DBI::dbListFields) and the table returned by dplyr::tbl() contains additional rows filled with NAs (likely the rows from the old dropped columns).

Creating views on the original table (which is then dropped and re-created) results in the same problem with missing OIDs...

Is there a way to circumvent this issue with the old/new OID?

**Comment by akaever** [comment]
The OID error can be avoided (PostgreSQL) when using multiple renames and splitting into multiple transactions (see also http://dba.stackexchange.com/questions/55661/how-to-duplicate-huge-postgres-table):

Transactions:

1. Copy local df to database (table_copy)
2. Rename table to be replaced (table_old) and table_copy (table)
3. Drop table_old
4. Create indexes and analyze table

**Comment by krlmlr** [comment]
I'm not sure we can implement this reliably across all back-ends. Can you share an implementation that wraps `copy_to()` to achieve the behavior you're looking for?

**Comment by akaever** [comment]
Here's our postgres-specific workaround. I'm not sure how this works with other backends. The pure SQL statements may be replaced by more advanced functions (I'm not so sure about the CASCADE).

```
#' Delete existing table in database and copy new table 
#' 
#' Deletes/Resets an existing table in a database and instead copies a new table 
#' to the database. This function is a clone of \code{\link[dplyr]{copy_to}} which 
#' automatically deletes an existing table. Tested only with PostgreSQL backends.
#' 
#' @export  
delete_and_copy_to <- function(dest, df, name = deparse(substitute(df)), types = NULL, 
                               temporary = TRUE, unique_indexes = NULL, indexes = NULL, 
                               analyze = TRUE, ...) {
  assertthat::assert_that(is.data.frame(df), is.character(name), is.logical(temporary))
  
  if (is.null(types))
    types <- dplyr::db_data_type(dest$con, df)
  names(types) <- names(df)
  con <- dest$con
  df <- as.data.frame(df)
  
  # first copy df to this table 
  copyName <- paste0(name, "_copy")
  # rename original table to this name
  oldName <- paste0(name, "_old")
  
  ## First transaction: Copy df into database
  dplyr::db_begin(con)
  on.exit(dplyr::db_rollback(con))
  
  # delete previous copy (pure SQL for CASCADE)
  s <- dplyr::build_sql("DROP TABLE IF EXISTS ", dplyr::ident(copyName), " CASCADE")
  DBI::dbExecute(con, s)
  # re-create
  dplyr::db_create_table(con, copyName, types, ...)
  # insert into new table
  dplyr::db_insert_into(con, copyName, df)
  
  dplyr::db_commit(con)
  on.exit(NULL)
  
  ## Second transaction: Rename tables 
  dplyr::db_begin(con)
  on.exit(dplyr::db_rollback(con))
  
  # rename original table (pure SQL for CASCADE)
  s <- dplyr::build_sql("DROP TABLE IF EXISTS ", dplyr::ident(oldName), " CASCADE")
  DBI::dbExecute(con, s)
  if (dplyr::db_has_table(con, name)) {
    s <- dplyr::build_sql("ALTER TABLE ", dplyr::ident(name), " RENAME TO ", ident(oldName))
    DBI::dbExecute(con, s)
  }
  # rename copy to original name
  s <- dplyr::build_sql("ALTER TABLE ", dplyr::ident(copyName), " RENAME TO ", ident(name))
  DBI::dbExecute(con, s)
  
  dplyr::db_commit(con)
  on.exit(NULL)
  
  ## Third transaction: Drop previous version
  dplyr::db_begin(con)
  on.exit(dplyr::db_rollback(con))
  
  s <- dplyr::build_sql("DROP TABLE IF EXISTS ", dplyr::ident(oldName), " CASCADE")
  DBI::dbExecute(con, s)
  
  dplyr::db_commit(con)
  on.exit(NULL)
  
  ## Fourth transaction: Create indices and analyze new table
  dplyr::db_begin(con)
  on.exit(dplyr::db_rollback(con))
  
  dplyr::db_create_indexes(con, name, unique_indexes, unique = TRUE)
  dplyr::db_create_indexes(con, name, indexes, unique = FALSE)
  if (analyze) 
    dplyr::db_analyze(con, name)
  
  dplyr::db_commit(con)
  on.exit(NULL)
  
  dplyr::tbl(dest, name)
}
```

**Comment by hadley** [comment]
I think this is out of scope for dplyr, because it treats databases as immutable.
