### ISSUE TITLE
Bug: order of elements in summarise changes output

### ISSUE THREAD

**Issue by nuskcalb** [hadley/dplyr#2169]
The order of the elements in summarise changes the output. So:

_BUG 1_
**Works fine**
`a %>% summarise(sd = sd(VD), VD = mean(VD))`

**Different output each time is ran**
`a %>% summarise(VD = mean(VD), sd = sd(VD))`

_BUG 2 - grouping_
**Works fine**
`a %>% group_by(Condition)  %>% summarise(sd = sd(VD), VD = mean(VD))`

**sd = NA**
`a %>% group_by(Condition)  %>% summarise(VD = mean(VD), sd = sd(VD))`

I attach a reproducible example in both .R and R Notebook.

[BUG sumarise.zip](https://github.com/hadley/dplyr/files/520445/BUG.sumarise.zip)

**Comment by krlmlr** [comment]
Thanks. Do I really need data that "big" to reproduce the problem? If not, it would be great if you could make the example more minimal. Even better if you could contribute a testthat test.

**Comment by nuskcalb** [comment]
Sorry for the late reply. Here it is a very simple way to reproduce the bug:

```
# We create a tibble
a = as_tibble(seq(1:10))

# Works OK; sd = 3.02; value = 5.5
a %>% summarise(sd = sd(value), value = mean(value))

# BUG; sd = 1.73 (or Inf, or NaN, ...); value = 5.5
a %>% summarise(value = mean(value), sd = sd(value))
  
# Changing "value = mean(value)" to "mean = mean(value)" makes the BUG disappear
a %>% summarise(mean = mean(value), sd = sd(value))
```

So, as weird as it sounds, it seems that when the label of mean(x) is x, there is a problem with the calculation of sd(x).

**Comment by hadley** [comment]
Yes, because you've replaced the existing variable with `mean(value)`

**Comment by nuskcalb** [comment]
Thanks for the prompt response. Oh, I thought all the operations were performed on the %>% passed value, not sequentially... 

A question though, if a %>% summarise(value = mean(value), sd = sd(value)) calculates sd as  sd(mean(value)), why it gives different results (e.g. 1.73, Inf, or NaN) if you run it multiple times? For example:

`  for (i in 1:50) print( a %>% summarise(value = mean(value), sd = sd(value)) )
`

**Comment by hadley** [comment]
Can you please create a reprex that clearly shows the problem using the reprex package?

**Comment by krlmlr** [comment]
@hadley: I'll add a reprex to #2404.
