### ISSUE TITLE
Recycling a single value for a list column

### ISSUE THREAD

**Issue by lepennec** [hadley/dplyr#2171]
Hi,

I'm working with list column and was trying to assign a list column with a constant value with the straightforward:

```
tmp <- tibble(a = c(1,2), b = list(tibble(x = 1:2), tibble(y = 1:3)))
tmp %>% mutate(c = list(1:3))
```

Unfortunately this does not work and I have an errpr `Error: not compatible with STRSXP`. The only way I have found are
    tmp %>% mutate(c = rep(list(1:3), nrow(tmp)))
    tmp %>% mutate(c = map(b, ~ 1:3))

Is there a more natural way to recycle a single value?

Erwan

**Comment by lepennec** [comment]
As a side note,
    tmp <- tibble(a = c(1,2), b = list(tibble(x = 1:2), tibble(y = 1:3)), c = list(1:3))
works as expected

**Comment by krlmlr** [comment]
@hadley: We should probably make the following work as expected:

```r
tmp %>% mutate(c = list(list(1:3)))
```

Anyway, the error message is not helpful.

**Comment by hadley** [comment]
@krlmlr agreed. This is a clear bug
