### ISSUE TITLE
copy_to: progress bar?

### ISSUE THREAD

**Issue by Deleetdk** [hadley/dplyr#2174]
`copy_to` is great for easily copying large amounts of data to a remote SQL. However, there is no progress bar as far as I can tell. I had to copy about 3 GB of data yesterday to a remote server, and the lack of a progress bar made me wonder how the operation was going (stuck?) and how long it would take in total.

For reference, I was using a command like this:

```
#connect
sql = src_mysql("dbname", host = "1.2.3.4", user = "user", password = "pass")

#insert iris
sql_iris = copy_to(sql, iris, name = "iris", temporary = FALSE)
```

Is there a way to turn on a progress bar for this operation? If not, I'd like to request that feature.

**Comment by krlmlr** [comment]
Currently there's no option to show a progress bar. For MySQL, the data is written to a temporary CSV, and adding a progress bar looks difficult at the very least.

**Comment by hadley** [comment]
I think this has to be the responsibility of the individual DBI backends, because dplyr has no access to the internals of the query process.
