### ISSUE TITLE
Filtering without having to pull unnecessary data from mysql

### ISSUE THREAD

**Issue by hherrada** [hadley/dplyr#2176]
Hi, I am currently pulling data from a mysql db to be used in a shiny app. There is a drag in performance when having to bring to R data that I do not actually need. This is what I am doing and what I would like to do:

`
Tickers <- collect(src_pool(patagonDB) %>% 
                    tbl("symbols") %>% 
                    select(ticker, SPX500, DJIA, NDX, RU2000) %>% 
                    filter(SPX500 == TRUE | DJIA == TRUE | NDX == TRUE | RU2000 == TRUE)) [,1]
`

and what I am hoping dplyr can do (Note that dplyr is pulling four columns that I do not actually need):

`
Tickers <- collect(src_pool(patagonDB) %>% 
                    tbl("symbols") %>% 
                    select(ticker) %>% 
                    filter(SPX500 == TRUE | DJIA == TRUE | NDX == TRUE | RU2000 == TRUE))
`

Do you think is this something that can be added to the queue? Thank you

**Comment by krlmlr** [comment]
You could add a second `select()` after the `filter()`.

**Comment by krlmlr** [comment]
@hadley: I just realized that I'm often using this filter-select pattern, too. With #2190, we could easily implement a clever filter verb that removes all columns used for filtering.

**Comment by hadley** [comment]
Are you thinking of something like `transfilter()` which would be `transmute()` column preserving semantics for `filter()`?

**Comment by krlmlr** [comment]
Perhaps `purge()`? @hherrada's code would be then:

```r
Tickers <- collect(src_pool(patagonDB) %>% tbl("symbols") %>% select(ticker, SPX500, DJIA, NDX, RU2000) %>% purge(SPX500 == TRUE | DJIA == TRUE | NDX == TRUE | RU2000 == TRUE))
```

**Comment by hadley** [comment]
Yeah, it'd be a bit harder for SQL. I quite like `refine()` as a name.

**Comment by krlmlr** [comment]
Same for a mutate() variant that gets rid of the columns it has used for computation: `transmogrify()`? Or perhaps better `transfigure()`...

**Comment by hadley** [comment]
I was thinking that might be better left to the individual vectorised function (i.e. they would return a tibble with NULL columns if `drop = TRUE`.

**Comment by krlmlr** [comment]
Can you give an example? I was thinking about

```r
iris %>%
  transfigure(Sepal.Area = Sepal.Width * Sepal.Height)
```

as a substitute for

```r
iris %>%
  mutate(Sepal.Area = Sepal.Width * Sepal.Height) %>%
  select(-Sepal.Width, -Sepal.Height)
```

**Comment by hadley** [comment]
Maybe we'll need both, but I was thinking of more complex mutations like those present in tidyr. i.e. instead of

```R
df %>%
  unite(x, y, z)
```

You'd be able to write

```R
df %>%
  mutate(unite(x, y, z))
```

(except obviously the function name would need to be different so it's backward compatible)

You could use the same idea to make a `transfigure` "vectorised" function:

```R
iris %>%
  mutate(transfigure(Sepal.Area = Sepal.Width * Sepal.Height))
```

But that doesn't look so good (and I can see an obvious better way to define the new variable name since `transfigure` would need to return `tibble(Sepal.Area = Sepal.Width * Sepal.Height, Sepal.Width = NULL, Sepal.Height = NULL)`. And it would have less information about where the names are bound to their values.

I think adding tibble support to mutate/summarise will be generally useful. `transfigure()` seems less generally useful, although it certainly would be handy.

**Comment by krlmlr** [comment]
Does that fit in the context of lazy operations, #2241?

**Comment by hadley** [comment]
@krlmlr I don't think so

**Comment by hadley** [comment]
@hherrada You can solve your original problem just by rearranging your pipe to do the filter before the select:

```R
Tickers <- src_pool(patagonDB) %>% 
  tbl("symbols") %>% 
  filter(SPX500 == TRUE | DJIA == TRUE | NDX == TRUE | RU2000 == TRUE) %>%
  select(ticker)
```

I think the general problem is still a bit too vague, and it's unlikely that it will be added to dplyr in the near term.
