### ISSUE TITLE
lm() within mutate() in group_by()

### ISSUE THREAD

**Issue by b1azk0** [hadley/dplyr#2177]
lm() function within mutate in group_by() computes results for entire dataset

[stack link for example](http://stackoverflow.com/a/40061201/6925293)

**Comment by slayah** [comment]
@b1azk0  Can you provide an example? I am not sure what you mean.
My guess is: You want to group by a certain column, perform linear regression for each group. But it is not allowing you to do so and performing linear regression on the entire dataset. Is that correct?

**Comment by puterleat** [comment]
If you wanted to extract the coefficients for each group from the lm you can do this:

```
library(dplyr)
library(tidyr)
data_frame(y=rnorm(100), x=y+rnorm(100), g=rep(1:10, 10) ) %>% 
  group_by(g) %>% 
  do(lm(y~x, data=.) %>% coef %>% as_data_frame)
```

**Comment by b1azk0** [comment]
@slayah I eventually used code similar to what @puterleat provided.
lm() for each group defined in group_by() works fine with do() but for some reason it fails with mutate()

**Comment by puterleat** [comment]
I think mutate requires a single return value from the function, whereas do requires a dataframe returned.

**Comment by cderv** [comment]
You are right . It is not a bug. 
`mutate` is for adding a new variable from a function with a single return value. `do` could play well with function that return list, creating list-column. 
Give a look to [purrr](https://github.com/hadley/purrr) for more power over list manipulation and to [broom](https://github.com/dgrtwo/broom) that helps working with dplyr for modeling.

For example of broom:

```r
linear_models <- cleaned_data %>%
  group_by(name, systematic_name, nutrient) %>%
  do(broom::tidy(lm(expression ~ rate, .)))
```
([source](http://varianceexplained.org/r/tidy-genomics-broom/))

See [here](http://ijlyttle.github.io/isugg_purrr/presentation.html#%281%29) for example of `purrr`, `tidyr` and `dplyr`.

**Comment by randomgambit** [comment]
Hello there, 

I just came across this question. Being able to run linear models by groups using `dplyr` is very important to me as well. 

Could someone please explain to me why the syntax  `mutate(Zre=residuals(lm(log(rt)~trial)))` is not correct and why should someone use `do` instead?

Thanks a lot!!!

**Comment by b1azk0** [comment]
Here are my two pieces of code:
This one works with mutate:
`df_long %<>%  group_by (Subject) %>%  
  mutate(subjMean = mean(rt1LN)
         ,subjSD = sd(rt1LN)
         ,rLN = r*subjSD+subjMean
         ,rmsec=exp(rLN))`

but for this piece I had to use do()

`df.clear %<>% 
    group_by(Subject) %>%  do(
{
    rt.zlog.trial <- rstandard(lm(log(rt) ~ trial, data = .));
    data.frame(., rt.zlog.trial)
})`

If there is a reason for lm() not work within mutate with group_by - that's OK with me - as long as the do() version does what I wanted I don't mind using it.
I posted this issue only because it didn't feel intuitive (but I'm a complete newbie at R and coding, do please forgive me)

@cderv thank you for the links! I will surely give it a try.

**Comment by b1azk0** [comment]
ps. I'm new to github as well  - shall I close this thread or it's ok if I leave it be?

**Comment by randomgambit** [comment]
dont close it dude? what are u doing?

**Comment by puterleat** [comment]
@randomgambit I think this discussion is probably better done on a support forum; both do and mutate are working as expected. The issue here is the return value: mutate requires a single value, whereas mutate requires a list or dataframe. If you follow the links provided by @cderv it should make more sense. lm returns a fit object which isn't suitable for either, but you can define a function to either extract a single statistic from the fit to use with mutate, or to return  a list (e.g. coefficients) to use with do.
