### ISSUE TITLE
Possible bug when joining and specifying empty suffix for LHS variables

### ISSUE THREAD

**Issue by puterleat** [hadley/dplyr#2182]
This causes my session to hang:

`
left_join(data_frame(a=1:2, b=1:2), data_frame(a=1:2, b=2:3),  by="a", suffix=c("", ".y"))
`

But this doesn't:

`
left_join(data_frame(a=1:2, b=1:2), data_frame(a=1:2, b=2:3),  by="a", suffix=c(".x", ".y"))
`

**Comment by PascalKieslich** [comment]
Just ran into the same issue with `inner_join`. The problem occurs for me whenever one of the elements in suffix contains an empty string (and only occurs when there actually are non-joined duplicate variables in `x` and `y`).

**Comment by krlmlr** [comment]
Thanks. #2228 is a more recent duplicate.

**Comment by krlmlr** [comment]
Closing in favor of #2228.
