### ISSUE TITLE
one_of() with arguments whose names are used in the columns of results an error

### ISSUE THREAD

**Issue by ngr-t** [hadley/dplyr#2184]
When I use a variable name used as a column name of .data, select() and one_of() raises an error.
Below is an example. 

``` R
> library(dplyr)
> col <- Species <- "Sepal.Width"
> # variable name "Species" (of course it's one of a column name of iris data) is invalid
> iris %>% select(one_of(Species))
Error: `c(...)` must be a character vector
> iris %>% select(one_of(col)) %>% head
  Sepal.Width
1         3.5
2         3.0
3         3.2
4         3.1
5         3.6
6         3.9
```

**Comment by krlmlr** [comment]
Thanks, confirmed. Would you like to contribute a testthat test?

**Comment by ngr-t** [comment]
I'd gladly to do so.
I feel that the test should be included in [tests/testthat/test-select-helpers.R](https://github.com/hadley/dplyr/blob/master/tests/testthat/test-select-helpers.R), is it OK?

**Comment by krlmlr** [comment]
I was confused. I think you need to do `one_of("Species")`.

**Comment by ngr-t** [comment]
Not. Sorry for poor explanation.
In the example above, the expected return value is a data.frame which has one column of "Sepal.Width" because the content of `Species` is "Sepal.Width".
My point is that accessing with a variable whose name is included by the column names causes an error.
It might be problematic when we write some function which takes data.frames as its parameters and don't know the column names of them.

**Comment by krlmlr** [comment]
I see:

```r
iris %>% select(one_of(Species))
```

doesn't work (and isn't supposed to) if there is no `Species` variable. But as soon as you assign a value to `Species`, it's supposed to work, but doesn't:

```r
Species <- "Petal.Width"
iris %>% select(one_of(Species))
```

It works if you use a variable that doesn't match the column name:

```r
col <- "Petal.Width"
iris %>% select(one_of(col))
```

I think test-select-helpers.R is a good place.

**Comment by krlmlr** [comment]
Are other select helpers affected?

**Comment by hadley** [comment]
It's not actually clear that this is a bug. Generally, you should avoid naming the variables you use inside `one_of()` the same as variables in your data frame. But @lionel- will take a deeper look.

**Comment by lionel-** [comment]
I fixed it by evaluating all calls supplied to `select_vars()` in the calling environment. Except for calls known to work with columns like `:`.

**Comment by lionel-** [comment]
Now fixed on master
