### ISSUE TITLE
Can I use dplyr to join two tibbles by "inner_join"ing on one column and "full_join"ing on the other?

### ISSUE THREAD

**Issue by conansi** [hadley/dplyr#2191]
The task I want to do is, as the title suggests, to join two tibbles by "inner_join"ing them on one column and, at the same time, "full_join"ing them on the other. 

To illustrate, please consider two tibbles as following.

``` R
    x = tribble(
        ~Date, ~Name, ~X,
        20100101, 'A', 2,
        20100101, 'B', 3,
        20100201, 'A', 1,
        20100201, 'C', 4,
        20100215, 'A', 2
    )

    y = tribble(
        ~Date, ~Name, ~Y,
        20100101, 'A', 0.1,
        20100101, 'B', 3.2,
        20100201, 'A', 1.1,
        20100201, 'B', 4.5
    )
```

The tibble I want to get is like this:

``` R
    A tibble: 5 × 4
          Date  Name     X     Y
         <dbl> <chr> <dbl> <dbl>
    1 20100101     A     2   0.1
    2 20100101     B     3   3.2
    3 20100201     A     1   1.1
    4 20100201     C     4    NA
    5 20100201     B    NA   4.5
```

The meaning of this tibble is a collection of all observations that happened on common dates.

Currently, I can get the expected answer in this way:

``` R
    full_join(x,y,by = c("Date", "Name") %>%
        filter(Date %in% intersect(x$Date, y$Date))
```

or this way:

``` r
semi_join(full_join(x,y), inner_join(x,y), by = 'Date')
```

However, I find these solutions kind of slow and unextendable. 
Is it possible to implement a general join function in a faster and more elegant way using a syntax like the following?

``` r
join(x, y, by = c('Date', 'Name'), methods = c('inner', 'full'))
```

I believe it would be very useful. 
Many Thanks!

**Comment by krlmlr** [comment]
I suspect this would add too much complexity to the joins, which are already complicated enough.
