### ISSUE TITLE
Is slice() meant to give the same results as filter with row_number() on grouped data frames?

### ISSUE THREAD

**Issue by alexfun** [hadley/dplyr#2192]
From:

http://stackoverflow.com/questions/40187530/in-dplyr-0-5-0-why-does-slice1-not-give-the-same-results-as-filterrow-number?noredirect=1#comment67643041_40187530

Using example data

`tmp_df2 <- data.frame(a = c(1, 3, 2, 4), b = c(1, 2, 3, 4))`

The operations

```

tmp_df2 %>%
    group_by(a) %>%
    slice(1)
```

produces a different row order to

```
tmp_df2 %>%
    group_by(a) %>%
    filter(row_number() == 1)
```

**Comment by krlmlr** [comment]
Confirmed. @hadley: Do we guarantee any particular row order after group_by()?

**Comment by hadley** [comment]
I think we should preserve the existing order of the rows (i.e. it's a "stable" split)

**Comment by krlmlr** [comment]
@alexfun: Would you like to contribute a testthat test?

**Comment by alexfun** [comment]
@krlmlr I would be happy to. Let me know if you have any specific requests.

**Comment by krlmlr** [comment]
@hadley @alexfun: I was confused.

The following two give identical results (ordered by the grouping variable):

```r
tmp_df2 <- data.frame(a = c(1, 3, 2, 4), b = c(1, 2, 3, 4))

tmp_df2 %>%
  group_by(a) %>%
  slice(1) %>% 
  ungroup

tmp_df2 %>%
  group_by(a) %>%
  summarize(b = b[[1]]) %>% 
  ungroup
```

The filter example returns the data in order of appearance:

```r
tmp_df2 %>%
    group_by(a) %>%
    filter(row_number() == 1)
```

The question is: Is the slice() a summarize-like or a filter-like operation? I tend to think it's more like a filter operation, in this case the observed behavior is a bug.

**Comment by alexfun** [comment]
I would argue that summarise should also return the grouping variables in the original order presented.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(a = c(2, 1), b = c("x", "y")) %>% group_by(a)

df %>% slice(1)
#> Source: local data frame [2 x 2]
#> Groups: a [2]
#> 
#>       a     b
#>   <dbl> <chr>
#> 1     1     y
#> 2     2     x
df %>% filter(row_number() == 1)
#> Source: local data frame [2 x 2]
#> Groups: a [2]
#> 
#>       a     b
#>   <dbl> <chr>
#> 1     2     x
#> 2     1     y
```

Thinking on it more, I don't think there's any guarantee that the row order should be the same. Relying on row order (instead of doing a join) is extremely dangerous because it will silently fail. So I don't think this is like to get high enough up on my priority list to be fixed.
