### ISSUE TITLE
S4 object inheriting from data.frame: filter() gives a warning

### ISSUE THREAD

**Issue by otoomet** [hadley/dplyr#2193]
A tiny example:

```
setClass("Foo", contains="data.frame")
x <- new("Foo", data.frame(a=1:2))
dplyr::filter(x, a > 1)
```

works but gives a warning:

```
Warning message:
In class(x) <- c("tbl_df", "tbl", "data.frame") :
  Setting class(x) to multiple strings ("tbl_df", "tbl", ...); result will no longer be an S4 object
```

(see also http://stackoverflow.com/questions/40187093/s4-object-inheriting-from-data-frame-remove-warning-in-dplyrfilter)
I suspect filter simply assumes that `x` is an S3 object and behaves accordingly...  I haven't tested other functions.

dplyr 0.5.0, R 3.3.1, various linuxes.

Why I think this is a problem: I want to use S4 objects (for multiple dispatch, validation) while inheriting the methods from data.frame.  The warning suggests that the code is not tested for such a usage case (and it obscures more important messages by this warning.)  I can get around of it by defining my own `filter` method for `Foo` where I drop the S4 class, but this seems to void much of the point with inheritance...

**Comment by krlmlr** [comment]
Is this a problem for the other verbs, e.g., mutate()? Could you implement `filter.Foo()` to wrap `filter.data.frame()` ?

**Comment by otoomet** [comment]
```mutate()``` gives the same warning.  ```rename()```, ```group_by()``` (and ```ungroup()```) work.

Sure, one can create a "Foo"-method for filter & friends.  There are two reasons I am not fan of this solution:
 1. this is against the logic of inheritance.  An important reason I make Foo to contain data.frame is to inherit the superclass methods with no extra work.
 2. ```dplyr::filter```** (and ```dplyr::mutate```) is not generic.

A side note to 1: inheritance may not work for Foo objects if the result should also be a Foo.  As ```dplyr::filter``` has no way to know whether the result is a valid Foo, it has to return a data.frame, no matter if the original object was Foo.

**Comment by krlmlr** [comment]
Right, I forgot -- you should implement `filter_.Foo()` and friends, which are generics.

Some say aggregation is better than inheritance, in part for the reasons you state in your footnote.

**Comment by hadley** [comment]
Yeah, this is out of scope for now

**Comment by otoomet** [comment]
BTW, why is this out-of-scope?

If inheritance works correctly, I can rely on "data.frame" method of filter.  The result may not be what I want (if probably won't be "Foo") but it should not give a warning.  I may want to implement the method for "Foo" if I wish additional functionality.

**Comment by hadley** [comment]
We are not currently prepared to support non-S3 data frames.

**Comment by otoomet** [comment]
OK.  Should it be stated somewhere in the documentation?  I haven't noticed it although there may be...

Do you know if there are any serious issues with S4 objects?  This particular problem can easily be solved with a slightly different way to handle the class.

**Comment by krlmlr** [comment]
We have an issue open in the tibble repo (https://github.com/tidyverse/tibble/issues/275) to add documentation, a statement about S4 should be part of this. How would you suggest to handle the class?

**Comment by hadley** [comment]
I don't think we need to take a public position on it at this point in time.

**Comment by otoomet** [comment]
If you ask me--I think a note about S4 classes should be prominently present in documentation where  dplyr and classes are discussed (not sure about R6).  I have to admit though that so far I have not stumbled onto such topic. Even better if the errors/warning can be tailor-made for such cases although this particular warning is clear enough.

I'd be happy to know if there are any major issues with supporting other classes.
