### ISSUE TITLE
all_equal/equal_data_frame throws an error with list columns

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#2194]
Given two identical `data_frame`s with a list column,

``` r
d1 <- d2 <- tibble::data_frame(x = list(1))
```

I expected `all_equal` to return `TRUE`.  Instead, I got an error:

``` r
dplyr::all_equal(d1, d2)
## Error: Can't join on 'x' x 'x' because of incompatible types (list / list)
```

The problem appears to originate in the Rcpp code called from `equal_data_frame`.

**Comment by krlmlr** [comment]
When are two elements of a list column equal? For n_distinct(), it's reference equality (#2222); we could certainly implement this, but object equality is going to be difficult.

**Comment by hadley** [comment]
Now part of #2355
