### ISSUE TITLE
Filtering with a non-existent variable crashes rstudio

### ISSUE THREAD

**Issue by expersso** [hadley/dplyr#2196]
On 32-bit Windows, this reliably crashes Rstudio, but not RGui:

```
library(dplyr)
iris %>% filter(abc == "def")

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by AdeelK93** [comment]
I'm able to get an error out of this on macOS and Ubuntu (which is good), but on Shiny Server, using a nonexistent variable will always cause a segfault that results in a crash. Would it be possible to have this as an error rather than a crash?

Can provide logs and stack traces if it helps any

**Comment by expersso** [comment]
Updating RStudio to v. 1.044 appears to solve this issue.
