### ISSUE TITLE
if_else() returns weird error messages with factors as return values

### ISSUE THREAD

**Issue by LCHansson** [hadley/dplyr#2197]
Under certain circumstances `if_else()` returns a bad error message when handed a factor as one of the output values. Specifically, it (strangely) complains about the factor being of type integer when one of the output values is a factor and the other is neither a factor nor an integer. OTOH if one of the output values is a factor and the other _is_ an integer it (reasonably) complains about the factor being of class factor.

Is this the desired behaviour? IMHO it would make a lot more sense if `if_else()` complained about the factor being a factor in all cases. In my specific case the error message about the factor being an integer led me to believe I had accidentally converted my factor to an integer which confused me for quite a while before I realised I was trying to pass a character variable (and not a factor) as the "alternate" output.

Reprex:

```
library(dplyr); library(tibble)
df <- tibble(
  a = factor(1:3, labels = letters[1:3])
)

# This returns the confusing error message
df %>% mutate(b = if_else(a == 'a', 'b', a))

# This returns a more resonable error message
df %>% mutate(b = if_else(a == 'a', 1L, a))

# For comparison: This returns a comprehensible result
df %>% mutate(b = if_else(a == 'a', factor('b', levels = letters[1:3]), a))
```

**Comment by krlmlr** [comment]
Confirmed. Would you like to contribute a testthat test?

**Comment by LCHansson** [comment]
Sure! Am I correct in assuming you mean a test to ensure that `if_else()` leaves a more informative error message (i.e. the second example in the reprex above) instead of the less informative and confusing message (like the one in the first example in the reprex)?

**Comment by krlmlr** [comment]
Right.

**Comment by LCHansson** [comment]
Done. HTH and feel free to correct me if there's anything wrong with the PR!

**Comment by hadley** [comment]
This is going to be difficult to fix with a few small patches here. We'll fix it fully once dplyr uses vctrs for class coercion.
