### ISSUE TITLE
SE version of dplyr functions can't see %>%

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#2199]
My motivation for using SE is to avoid R CMD CHECK notes - described here: http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when#comment20826625_12429344

My actual use case is a several function long set of pipes in a mutate call, which, when de-piped, is quite difficult to read.

```
library(magrittr)
# Works
iris <- iris %>% 
  dplyr::mutate(new_var = Sepal.Length %>% lapply(function(x) x + 1))

# Breaks
iris <- iris %>% 
  dplyr::mutate_(new_var = "Sepal.Length %>% lapply(function(x) x + 1)")

# Error in eval(substitute(expr), envir, enclos) : 
#  could not find function "%>%"

# Works
iris <- iris %>% 
  dplyr::mutate_(new_var = "lapply(Sepal.Length, function(x) x + 1)")
```
Is it possible to get SE dplyr functions to see %>%?

**Comment by zeehio** [comment]
Using a formula like this works to me, hopefully this solves your issue:

```r
iris <- iris %>% 
  dplyr::mutate_(new_var = ~"Sepal.Length %>% lapply(function(x) x + 1)")
```
