### ISSUE TITLE
[Feature] Would be nice to have a simple diagnosis after a join

### ISSUE THREAD

**Issue by pachevalier** [hadley/dplyr#2202]
Imagine you perform a left_join : 

table_a %>% left_join(table_b, by = "id") 

Everytime I do this, I just run some checking afterwards for counting the number of rows which have not been joined.

It would be nice to have a simple diagnosis tool giving the number of rows successfully joined and the number of rows which have not been joined.

**Comment by randomgambit** [comment]
cannot agree more https://github.com/hadley/dplyr/issues/2183

**Comment by krlmlr** [comment]
#2183 seems to be a more complete description, can we discuss there?
