### ISSUE TITLE
joins with non-standard characters

### ISSUE THREAD

**Issue by MansMeg** [hadley/dplyr#2210]
I realized that if I join two tables by a character vector with non-standard characters (Swedish letters in my case) and the encoding is not set similar they do not match in the final table. I guess there should be a warning that this can happen or an assertion that only basic characters can be used in a merge (probably the safest choice).

**Comment by krlmlr** [comment]
Thanks. We're working on providing better warning mechanisms. In general, column data should always be UTF-8 encoded, but column *names* should be in the native encoding (which is always different on Windows, and may be different on other systems, too).

**Comment by krlmlr** [comment]
Closing, duplicate of #1885.
