### ISSUE TITLE
Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x00000000048261c8

### ISSUE THREAD

**Issue by osmanir** [hadley/dplyr#2212]
I am compiling the box R for data science and get this error. I am using R 3.2.3 in Linux Mint Sarah 64 bits. Compiling with knit I get

Conflicts with tidy packages ----------------------------------------------
**\* Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x00000000048261c8 ***
======= Backtrace: =========
.....
Aborted
Error in Rscript_render(f, render_args, render_meta) :
Failed to compile tidy.Rmd
Calls: ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted

**Comment by krlmlr** [comment]
Thanks for reporting. What do you see when you run

```r
library(tidyverse)
```

in an R session on the console?

**Comment by osmanir** [comment]
I see this

Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ---------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats

**Comment by krlmlr** [comment]
This is strange. Which command do you use to render the book, and in which environment (R console / RStudio / ...)?

**Comment by osmanir** [comment]
I am using RStudio 1.0.35. When I compile the book project and I get

==> rmarkdown::render_site(encoding = 'UTF-8')

Error in rmarkdown::render_site(encoding = "UTF-8") : 
  No site generator found.
Execution halted

Exited with status 1.

Then I try build the book compiling the index.rmd file and I get that error.

**Comment by krlmlr** [comment]
Thanks, I missed your reply. How do you "compile the index.rmd file" -- is it just opening it in RStudio and hitting Ctrl+Shift+K?

**Comment by osmanir** [comment]
Thanks, for your help. Yes, I am using Ctrl+Shift+K (Knit button).

**Comment by osmanir** [comment]
When, I use the Build Website button, I get the next error

==> rmarkdown::render_site(encoding = 'UTF-8')

Error in rmarkdown::render_site(encoding = "UTF-8") : 
  No site generator found.
Execution halted

Exited with status 1.

**Comment by hadley** [comment]
This doesn't seem like a dplyr issue?
