### ISSUE TITLE
Filtering dates contained inside a vector

### ISSUE THREAD

**Issue by jpryda** [hadley/dplyr#2216]
If we can filter a date by comparison to a string e.g.

`filter(yearMonth=='2016-09-01' || yearMonth=='2016-10-01') %>%`

it would be make sense if we could select a bunch of dates in a character vector using `%in%` e.g.

`filter(yearMonth %in% c('2016-09-01','2016-10-01')) %>%`

However one is forced to wrap `as.Date()` around the vector of dates which is a little unintuitive if the previous syntax is permitted?

**Comment by krlmlr** [comment]
I'm getting the same behavior outside of filter():

```r
as.Date("2016-11-07") %in% c("2016-11-07")
## FALSE
```
