### ISSUE TITLE
Document row_number()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2218]
Currently, the documentation of row_number() only gives the version with one argument; but inside mutate() et al., row_number() without arguments works fine (and may be faster).

**Comment by CarrKnight** [comment]
row_number() without arguments stopped working within mutate. Was it replaced by anything else?

**Comment by krlmlr** [comment]
@CarrKnight: Could you please provide a reproducible example? `row_number()` definitely should work.

**Comment by CarrKnight** [comment]
@krlmlr 
My bad, sorry, i must have screwed up the library loading order before calling it since I can't reproduce it again. Sorry for the false alarm.

**Comment by holgerbrandl** [comment]
Even with the updated documentation I still  don't see where `row_number` gets its `x` argument from. Could you point me to the corresponding code bit?  

Is there a listing of dplyr methods that are formally defined of requiring an argument but work without?

**Comment by krlmlr** [comment]
There are two versions of `row_number()`: one in R code with a mandatory argument, and one in the hybrid evaluator that doesn't require arguments. Look for `row_number_prototype` in the C++ code.

**Comment by holgerbrandl** [comment]
Thanks. Are the handlers listed under https://github.com/tidyverse/dplyr/blob/14b5d128c303fd9af0fca4ab6f1fa17ede5c9bf4/src/hybrid_window.cpp#L158-L163
the only methods that have this duality in dplyr?
Is this a common R approach or something very specific for/in dplyr?
