### ISSUE TITLE
length(unique(x)) and n_distinct(x) return different answers for some lists

### ISSUE THREAD

**Issue by jgabry** [hadley/dplyr#2222]
The documentation for `n_distinct` says that it's an "equivalent of length(unique(x))"
but it gives a different answer than `length(unique(x))` if `x` is a list with multiple (identical) elements.

```r
library(dplyr)  # I checked versions 0.5.0 and 0.5.0.9000
x <- list(1,1)
length(unique(x)) # result: 1
n_distinct(x) # result: 2
```

Is this a bug or is there just a missing caveat in the doc?

**Comment by krlmlr** [comment]
This is because values in list columns are compared by reference, so n_distinct() treats them as different unless they really point to the same object:

```r
a <- 1
n_distinct(list(a,a))
## [1] 1
```

Would you like to contribute documentation?

**Comment by jgabry** [comment]
Thanks for the explanation. That makes sense. I'd be happy to submit a PR
that clarifies this in the doc and adds an example demonstrating. Can
hopefully do this today.

**Comment by hadley** [comment]
I think this is more of a bug than something we need to document

**Comment by jgabry** [comment]
When I originally opened the issue it was because it seemed like a bug.
Kirill's explanation of the behavior makes sense but it does seem
preferable to have it behave like the base R equivalent than to have to
explain the unexpected deviation.

On Tue, Jan 31, 2017 at 6:45 PM Hadley Wickham <notifications@github.com>
wrote:

I think this is more of a bug than something we need to document

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hadley/dplyr/issues/2222#issuecomment-276530534>, or mute
the thread

**Comment by hadley** [comment]
Now part of #2355
