### ISSUE TITLE
group_by executes column names as code

### ISSUE THREAD

**Issue by davharris** [hadley/dplyr#2224]
*Previously posted as  hadley/purrr#257; @lionel- said it was a dplyr::group_by issue, so reposting it here*

Column names can be executed as code when `group_by` & related operations are used. I initially discovered this problem because I had a column name with a space in it:

```
x = mtcars
colnames(x) = paste(colnames(x), 1:ncol(x))
slice_rows(x, 1)

# Error in parse(text = x) : <text>:1:5: unexpected numeric constant
#1: mpg 1
```

After I looked at the traceback information, I found that purrr (via dplyr) was actually using lazyeval to parse and run the column names as code. That seems unsafe to me (analogous to SQL injection, but possibly worse because R can call system).

**Comment by krlmlr** [comment]
Confirmed, using:

```r
x = mtcars
colnames(x) = paste(colnames(x), 1:ncol(x))
group_by_prepare(x, .dots = names(x))
```

We should coerce to names first.

@davharris: Would you like to contribute a testthat test?

**Comment by davharris** [comment]
Sure.  To clarify, did you mean that `names` should be coerced to character? Or is there a `names` class?

**Comment by krlmlr** [comment]
dplyr should take care of the coercion, our code should work as is.

**Comment by davharris** [comment]
Submitted a failing test in #2235.

**Comment by hadley** [comment]
But this is actually correct behaviour so you can do:

```R
mtcars %>% group_by(cut(mpg, 3))
```

`group_by()` has `mutate()` semantics, not `select()` semantics.

**Comment by krlmlr** [comment]
There are so many issues about columns with spaces. Should we give a nicer error message if it turns out that there is actually a column by that name?

**Comment by davharris** [comment]
Also, it's probably a bad idea for column names to be executed as code if they aren't explicitly typed in by the user.  This is basically SQL injection, but for R.

**Comment by davharris** [comment]
It looks like `group_by` can also produce other unexpected behavior when executing column names as code.

```
df <- data_frame(`warning("column name executed as code")` = 1:3, b = 1:3)
group_by(df, `warning("column name executed as code")`) # groups correctly; no warning
group_by(df, warning("column name executed as code"))    # mutates the first column; warning
```

Again, this behavior can be triggered without the user being aware that the column name is anything unusual: `slice_rows(df, 1)` returns instead of 

```
Source: local data frame [3 x 2]
Groups: warning("column name executed as code") [1]

  `warning("column name executed as code")`     b
                                      <chr> <int>
1              column name executed as code     1
2              column name executed as code     2
3              column name executed as code     3
Warning message:
In eval(substitute(expr), envir, enclos) : column name executed as code
```

instead of


```
Source: local data frame [3 x 2]
Groups: warning("column name executed as code") [3]

  `warning("column name executed as code")`     b
                                      <int> <int>
1                                         1     1
2                                         2     2
3                                         3     3
```

**Comment by krlmlr** [comment]
If we can go back to the original code -- I still think that giving an error is not justified. #2243 will contain a bullet point for this case. I was confused: It was my code that works as expected, but the error is further up the call chain.

As for mutate semantics of group_by() -- the upside is that computed columns automatically receive a nice name. Changing that would be too late now IMO.
