### ISSUE TITLE
names of list columns

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#2231]
There seems to be something wrong about list columns. 

Here I'm creating a list column that contains named integer vector :

```r
> d <- data_frame( x = rep(c(1,2), c(2,4)), y = 1:6, names = letters[1:6] )
> d
# A tibble: 6 × 3
      x     y names
  <dbl> <int> <chr>
1     1     1     a
2     1     2     b
3     2     3     c
4     2     4     d
5     2     5     e
6     2     6     f
> res <- d %>% group_by(x) %>% summarise( y = list( setNames(y, names) ) )
> res$y[[1]]
c d 
1 2 
> res$y[[2]]
c d e f 
3 4 5 6 
> names( res$y[[1]])
[1] "c" "d" "e" "f"
> names( res$y[[2]])
[1] "c" "d" "e" "f"
```

I'd expect `names( res$y[[1]])` to be `c("a", "b")`.

**Comment by romainfrancois** [comment]
I suspect this is hybrid using the same data multiple times, i.e. if I force creation of a new `names` with `paste0` it's fine: 

```
> res <- d %>% group_by(x) %>% summarise( y = list( setNames(y, paste0("", names)) ) )
> res$y
[[1]]
a b 
1 2 

[[2]]
c d e f 
3 4 5 6 
```

**Comment by krlmlr** [comment]
Does this still happen with https://github.com/hadley/dplyr/pull/2190?

**Comment by krlmlr** [comment]
Confirmed even with #2190.

**Comment by hadley** [comment]
This might be related to #1689

**Comment by krlmlr** [comment]
I suspect the use of shrinkable vectors causes the behavior we're seeing here. Need to investigate more.

**Comment by krlmlr** [comment]
It looks similar, but fixing #1689 doesn't fix this reprex yet.
