### ISSUE TITLE
dplyr + spark

### ISSUE THREAD

**Issue by katgit** [hadley/dplyr#2236]
I am following the sparklyr tutorial (http://spark.rstudio.com/) and the very first command there fails.
I believe the function comes from dplyr package, though:

> iris_tbl <- copy_to(sc, iris)
The following columns have been renamed:
- 'Sepal.Length' => 'Sepal_Length' (#1)
- 'Sepal.Width'  => 'Sepal_Width'  (#2)
- 'Petal.Length' => 'Petal_Length' (#3)
- 'Petal.Width'  => 'Petal_Width'  (#4)
Error: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://scc/scratch/Rtmpj0TgKc/file6cf236120d3.csv;

The temporary csv file has been created in the local file system:
> tempdir()
[1] "/scratch/Rtmpj0TgKc"

> list.files(tempdir())
[1] "file6cf216a40471_spark.log" "file6cf236120d3.csv"

However after that copy_to is trying to read it from the HDFS filesystem:
hdfs://scc/scratch/Rtmpj0TgKc/file6cf236120d3.csv
and does not find that file there.

Which environment variables or configurations need to be changes?

Thank you, 
--Katia

**Comment by hadley** [comment]
Please ask on the sparklyr repo.
