### ISSUE TITLE
Lazy data frames

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2241]
Similar to #2190, perhaps using promises instead of active bindings in a first iteration: https://github.com/krlmlr/bindr/issues/1.

Memory management will be a challenge, unless we teach the user to call collect() for large analyses. Caching to disk may be an option. We don't need to make all operations lazy, too. Some light query optimization may also help.

The following operations will benefit, and should be implemented first:

- [ ] select()
- [ ] filter() with multiple conditions or with subsequent select (refine(), #2176)
- [ ] *_join(), in particular the cross join (#197)
- [ ] slice()
- [ ] ...

**Comment by hadley** [comment]
I'd rather put this in separate package. I think this is sufficiently low priority that it's unlikely to get implemented and it would be clearer to just close the issue.

**Comment by krlmlr** [comment]
Can we aggregate these low-priority wishes in some issue/wiki page?
