### ISSUE TITLE
Suggestion: recode improvements

### ISSUE THREAD

**Issue by methodds** [hadley/dplyr#2250]
Hi,

I would like to suggest adding another ``recode`` function or adjusting existent ones. I was not able to reproduce the functionality of  [car](https://cran.r-project.org/web/packages/car/index.html)   ```Recode``` which works like this:

````
> x <- sample(1:7, 10, replace=T)
> x
 [1] 2 1 6 7 5 3 3 2 4 4
> 
> Recode(x, "1:2=1; 3:4=2;5=3; else=NA")
 [1]  1  1 NA NA  3  2  2  1  2  2
````
Being able to recode multiple values without specifying each one separately would be really handy, especially for people working with survey data.

In addition, would it maybe even possible to coordinate this with the ``labelled`` function from ```haven```? The result would be a clone of Stata's recode, which is what most people switching from there to ``R`` are currently missing:
![image](https://cloud.githubusercontent.com/assets/7460499/20217950/ab820b3c-a822-11e6-8447-b20ac9cdfc25.png)

**Comment by krlmlr** [comment]
Have you seen `case_when()`?

**Comment by GarciaRios** [comment]
with `case_when`  you would do

```
y <- case_when(
  x <= 2 ~ 1,
  x >= 3 & x <= 4 ~ 2,
  x == 5 ~ 3
)
```
It's  more verbose than `car::recode` but it's still being developed...

**Comment by hadley** [comment]
I'm not a fan of specifying everything in one giant string.
