### ISSUE TITLE
coalesce to follow coercion rules?

### ISSUE THREAD

**Issue by rgknight** [hadley/dplyr#2254]
`coalesce` doesn't coerce an integer to a double
```
coalesce(as.integer(1), 0)
```
The conversation rules here seem to suggest that integer to double should be allowable? https://github.com/hadley/vctrs/issues/7

`bind_rows` does coerce integers to doubles, which is what initially confused me about which coercions allowed. 
```
df1 <- data.frame(a = as.integer(1))
df2 <- data.frame(a = 0)
tmp <- bind_rows(df1, df2)
class(tmp$a)
```
coalesce also doesn't follow the factor conversion rules outlined at the link
```
# Factor + Character doesn't work
a <- c("first", "second", NA) %>% as.factor()
b <- "third"
coalesce(a, b)
# The warning message is also confusing here: Error: Vector 1 has type 'character' not 'integer'

# Factor + factor with different levels returns a warning but doesn't do anything
b <- as.factor(b)
coalesce(a, b)
```

**Comment by krlmlr** [comment]
Thanks, confirmed. We should be more consistent here.

**Comment by hadley** [comment]
This will be implemented in vctrs, not dplyr.
