### ISSUE TITLE
Translate semi_join to SQL IN tuple statement

### ISSUE THREAD

**Issue by creager** [hadley/dplyr#2257]
It would be nice if the semi_join function could translate to something like WHERE (var1,var2) IN ((a,b),(c,d)) when (a) the user is accessing a table in a remote database and (b) the second argument to semi_join is a local data source.   This would prevent the need to copy the local data source to the remote database.  This would be helpful when (a) copying is an expensive operation and/or (b) the user has read only permissions from the database.

If this doesn't jive with the join() model, an alternative approach would be to add the ability to filter() by tuples and translate to the IN tuple statement when filtering by tuples.

**Comment by krlmlr** [comment]
Thanks. Could you please provide a code example?

**Comment by creager** [comment]
Is this helpful?

``` r

require(dplyr)

# Creates a conditional SQL IN statement using tuples, e.g. "(courseid, userid)
# IN ((1, 100), (1, 104), (2, 100))".  Names of the input data frame must match 
# names in the SQL local.table.  Each row in the input data frame specifies tuple 
# values.
BuildSQLTupleCondition = function(tuple.df) {
  # Format variables and values
  for (col.name in names(tuple.df)) {
    # Convert factors to strings
    if (is.factor(tuple.df[[col.name]])) {
      tuple.df[[col.name]] = as.character(tuple.df[[col.name]])
    }
    # Quote strings and cast all non-strings to strings.
    if(is.character(tuple.df[[col.name]])) {
      tuple.df[[col.name]] = paste0("'", tuple.df[[col.name]], "'")
    } else {
      tuple.df[[col.name]] = as.character(tuple.df[[col.name]])
    }
  }
  
  # Create a vector of tuples, where each tuple is a row of the input tuple.df
  tuples = c()
  for (i in 1:nrow(tuple.df)) {
    tuples = append(tuples, 
                    sprintf('(%s)', paste(tuple.df[i,], collapse = ', ')))
  }
  
  # Compile tuples into SQL condition
  c = sprintf("(%s) %s (%s)",
              paste(names(tuple.df), collapse = ', '),
              'IN',
              paste(tuples, collapse = ', '))
  return(c)
}

# Assuming you have some db connection
db = src_mysql(
  host = 'host', 
  port = 3306
  user = 'user', 
  password = 'password',
  dbname = 'dbname'
)

# These are the conditions by which you want to join/filter
tuples = data.frame(
  courseid = c(1, 2),
  userid = c(100, 104)
)

# Using current semi_join
tbl(db, 'dbtable') %>%
  semi_join(tuples, by = c('courseid', 'userid')) %>%
  collect()

# Alternative, which could be implemented through the same semi_join statement
q = paste('SELECT * FROM dbtable WHERE', BuildSQLTupleCondition(tuples))
tbl(db, sql(q)) %>%
  collect()

# The remote table might look like this
db.table = data.frame(
  courseid = c(1, 1, 2, 2),
  userid = c(100, 104, 100, 104),
  score = c(80, 85, 90, 95)
)

# The result would look like this
semi_join(db.table, tuples, by = c('courseid', 'userid'))

```

**Comment by krlmlr** [comment]
Thanks. I don't see the generation of SQL from a vector/matrix/data frame in the scope of dplyr, but this is up to @hadley to decide.

Either way, creating a temporary table is not very expensive, and it can be reused; whereas the generated SQL may need to be parsed for every query.

**Comment by creager** [comment]
@krlmlr: Thanks for looking into this.  Also, a general word of encouragement:  I appreciate how active you are in the development of dplyr.  I use dplyr regularly, and I'm very thankful that it works so well.  I'm sure the high quality package is the result of you and the rest of the team being so diligent with issues and requests.

In regard to the temporary table, my database permissions prevent me from creating temporary tables.  Thus, I will probably have to continue building my own SQL conditions.  This leads to a follow up question:  Is there a nice way for me to insert my custom SQL WHERE condition in the middle of a series of database-oriented dplyr commands, e.g. select and filter?

**Comment by krlmlr** [comment]
Thanks. I didn't do much for dplyr until very recently, credit goes to @hadley and @romainfrancois for designing and implementing the package.

Would talking to your DBA be a way of action?

We could consider supporting anonymous inline tables, like

```sql
SELECT 1 AS a, 2.0 AS b, "3" AS c
UNION ALL
SELECT 2 AS a, 3.0 AS b, "4" AS c
...
```

But these may not work everywhere.

For now, I guess you could use the result of sql_render() and build your query around it, along these lines:

```r
paste0("SELECT * FROM (", sql_render(...), ") WHERE ...")
```

But I haven't tried that.

**Comment by creager** [comment]
Thanks for the tips.  I'll talk to the DBA and see what I can do.

**Comment by hadley** [comment]
This is out of scope for dplyr - the assumption that you can make temporary tables is fairly deeply embedded in dplyr.
