### ISSUE TITLE
dplyr installation of package ‘dplyr’ had non-zero exit status in ubuntu

### ISSUE THREAD

**Issue by Rahulvks** [hadley/dplyr#2261]
Updated - Rcpp
Installation from Cran treid getting same error.

R Studio - version 1.0.44

Kindly help

**Comment by krlmlr** [comment]
Works on my system. Could you please post logs?

**Comment by Rahulvks** [comment]
Issue is solved :)

Command
if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")

**Comment by krlmlr** [comment]
Why did you install lazyeval from GitHub? If this is required, we should add this to the "Remotes" section of DESCRIPTION.
