### ISSUE TITLE
Alternate column ordering from left and right joins on mysql sources makes union misaligned by columns. 

### ISSUE THREAD

**Issue by sarveshpradhan** [hadley/dplyr#2262]
Left and right join ordering on mysql sources is swapped making union operations incorrect. Especially relevant when the underlying database does not support full joins (mySQL). Or am I using the library incorrectly?

Pretty sure my example in terms of being reproducible is poor, but here goes:

`pincode1 <- tbl(db,"pincode_state_mapping") %>% select(id,pincode,state)`
`pincode2 <- tbl(db,"pincode_state_mapping") %>% select(state,pincode,id)`

`left_join(pincode1,pincode2,by="state",suffix=c(".1",".2"))`
`Output columns:`

| state | id.1 | pincode.1 | pincode.2 | id.2 |
|-------|------|-----------|-----------|------|

`right_join(pincode1,pincode2,by="state",suffix=c(".1",".2"))`
`Output columns:`

| state | pincode.2 | id.2 | id.1 | pincode.1 |
|-------|-----------|------|------|-----------|

A union operation here will merge id.1 and pincode.2 etc.

Here is the result on non SQL sources
`test <- data_frame(Greek = c("Alpha", "Beta", "Gamma"), Letters = LETTERS[1:3],Numbers = seq(1:3))`
`lookup <- data_frame(Greek = c("Alpha","Gamma","Epsilon"),Numbers = seq(4:6),Letters = c("C", "B", "C"))`
Joining:
`left_join(test,lookup,by=c("Greek"),suffix=c(".test",".lookup"))`
`Output columns:`

| Greek Letters.test | Numbers.test | Numbers.lookup | Letters.lookup |
|--------------------|--------------|----------------|----------------|

`right_join(test,lookup,by=c("Greek"),suffix=c(".test",".lookup"))`
`Output columns:`

| Greek Letters.test | Numbers.test | Numbers.lookup | Letters.lookup |
|--------------------|--------------|----------------|----------------|

A union operation will be correct here

**Comment by krlmlr** [comment]
@hadley: Do we guarantee a specific column order after a join?

**Comment by hadley** [comment]
No guarantees currently.

**Comment by sarveshpradhan** [comment]
Current workaround for emulated full join with union is:
`union(leftJoinResult,select_(rightJoinResult,.dots=colnames(leftJoinResult)))`
