### ISSUE TITLE
inconsistent behavior in database dplyr commands

### ISSUE THREAD

**Issue by RMHogervorst** [hadley/dplyr#2265]
the db_drop_table command needs a connection, that is db_name$con
`db_drop_table(db_name$con, "df")`

but other commands need the entire thing
`copy_to(db_name, df, ...)`

`no applicable method for 'copy_to' applied to an object of class "c('SQLiteConnection', 'DBIConnection', 'DBIObject')" `

**Comment by krlmlr** [comment]
Thanks. Could you please provide a reproducible example?

**Comment by RMHogervorst** [comment]
Yeah sure,
This example displays the inconsistency.
I thing if every command works with dbname$con , this would be more consistent with
other database tools such as the DBI package. 

```
library(dplyr)
db <- src_sqlite(path = tempfile(), create = TRUE)
copy_to(db, iris,temporary = FALSE)
db_drop_table(db, "iris")  # doesn't work
db_drop_table(db$con, "iris") # does work
```

**Comment by RMHogervorst** [comment]
Although the readme of DBI says otherwise:
https://cran.r-project.org/web/packages/DBI/README.html
``` 
con <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")

dbListTables(con)
```

**Comment by hadley** [comment]
The db function are not really for external use - since they were written a lot of effort has going into standardising the DBI backends.
