### ISSUE TITLE
It would be nice if min/max used lexical order in summarize_each

### ISSUE THREAD

**Issue by JohnMount** [hadley/dplyr#2269]
It would be nice if min/max used lexical order in summarize_each (instead of refusing to compare).

Example below (and also linked).

```
library('dplyr')
 #  
 #  Attaching package: 'dplyr'
 #  The following objects are masked from 'package:stats':
 #  
 #      filter, lag
 #  The following objects are masked from 'package:base':
 #  
 #      intersect, setdiff, setequal, union
R.Version()$version.string
 #  [1] "R version 3.3.2 (2016-10-31)"
packageVersion('dplyr')
 #  [1] '0.5.0'
d1 <- data.frame(y=c('a','b'),stringsAsFactors = FALSE)
d1 %>% dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
 #    lexmin lexmax
 #  1      a      b
d2 <- data.frame(y=c('a','b'),stringsAsFactors = TRUE)
d2 %>% dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
 #  Error in eval(expr, envir, enclos): 'min' not meaningful for factors
```

https://github.com/WinVector/replyr/blob/master/issues/factorissue.md

**Comment by krlmlr** [comment]
This is expected behavior: `min(factor(letters))` raises the same error you're seeing with dplyr. I'm actually surprised to see that `min(letters)` works, even more so that it works in dplyr.

**Comment by JohnMount** [comment]
krlmlr, Ah you are correct (of course).  I was hasty and didn't notice it was `base::min` raising the exception, so that would in fact be expected behavior on native `data.frame`s.   However many of the remote `dplyr` implementations (databases) do support comparison on character types and also coerce factors to characters.  For example the following works:

```
my_db <- dplyr::src_sqlite("replyr_sqliteEx.sqlite3", create = TRUE)
dplyr::copy_to(dest=my_db,df=d1,name='d1',overwrite=TRUE) %>% 
  dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
dplyr::copy_to(dest=my_db,df=d2,name='d2',overwrite=TRUE) %>% 
  dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
```

**Comment by krlmlr** [comment]
Thanks. That's interesting (I didn't know) but the R -> SQL translation is just a rough approximation anyway -- within R we should stick to what R does and doesn't. Of course you can always work around with `function(x) min(as.character(x))`.
