### ISSUE TITLE
mutate_at transforms column to matrix

### ISSUE THREAD

**Issue by karchjd** [hadley/dplyr#2274]
``` r
library(dplyr)
dataSet <- iris
print(class(dataSet$Sepal.Length))
```

    ## [1] "numeric"

``` r
data <-  mutate_at(iris,vars(Sepal.Length),scale)
print(class(data$Sepal.Length))
```

    ## [1] "matrix"

I guess this is the desired behavior. However, I would consider this a bug. It also caused some problems with other packages that assume that each colum in a data.frame is a numeric vector. Maybe I am just being stupid and not using the package in the correct way.

**Comment by krlmlr** [comment]
This is because `scale()` returns a matrix.

**Comment by karchjd** [comment]
Thanks for the clarification!
