### ISSUE TITLE
Hybrid version of uq()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2283]
so that `mutate_(., f = ~mean(uq(var))` still uses the hybrid evaluator. (This requires that we switch to the "new" lazyeval first.)

Do we need hybrid handlers of uqs() and uqf()?

**Comment by hadley** [comment]
Adding @lionel- just so we talk about this when he implements tidyeval in dplyr.

**Comment by lionel-** [comment]
I think we'd want to only use the hybrid evaluator if we unquote a formula. So no hybrid versions of unquoting operators would be needed since the unquoted formulas get evaluated in the evaluation environment where hybrid functions are defined.

**Comment by krlmlr** [comment]
Hybrid versions are needed only for performance. I still see a case here with rlang and tidyeval, but this may not be top priority.
