### ISSUE TITLE
Would be nice to have an arrange annotation to show if a `dplyr::arrange` is active

### ISSUE THREAD

**Issue by JohnMount** [hadley/dplyr#2287]
`dplyr `has an annotation and function `dplyr::groups()` that tells you what `dplyr::group_by` is active.  It seems to not have a similar indication as to what `dplyr::arrange` is active.  It would be nice if their was such an annotation.  

Side note: `dplyr`'s `PostgreSQL` backend seems to have such an annotation (or more likely the database does) as functions like `cumsum` usefully warn when applied to pipelines with no ordering constraint active.

Example showing why I think there is no `dplyr::arrange` annotation:

```
library('dplyr')
d <- as.tbl(data.frame(x=1))
d <- arrange(d,x)
unclass(d)

 # $x
 # [1] 1
 # 
 # attr(,"row.names")
 # [1] 1

d <- group_by(d,x)
unclass(d)

 # $x
 # [1] 1
 # 
 # attr(,"row.names")
 # [1] 1
 # attr(,"vars")
 # attr(,"vars")[[1]]
 # x
 # 
 # attr(,"drop")
 # [1] TRUE
 # attr(,"indices")
 # attr(,"indices")[[1]]
 # [1] 0
 # 
 # attr(,"group_sizes")
 # [1] 1
 # attr(,"biggest_group_size")
 # [1] 1
 # attr(,"labels")
 #   x
 # 1 1
```

**Comment by r2evans** [comment]
Annotations would need to be uber-wusses (meaning they disappear as soon as any modifying-verb comes along):

```r
library("dplyr")
data.frame(x = -1:1) %>%
  arrange(x) %>%
  mutate(x = abs(x))
```

The only way to guarantee that an `Arranged: x` annotation would work is to remove it with anything that modifies the structure (such as `mutate*` or `summarize*` functions).

`group_by`'s annotation is persistent because its grouping is enforced (`cannot modify grouping variable`). Since you can't do the same with ordering, you would need to modify any function that modifies the data.frame, so that either (a) no modification of the ordered column(s) is permitted; or much more palatable, (2) immediately remove the hint of the annotation when the ordered column is touched in any way; or much-more expensively (3) re-order after every modifying verb.

(3) has some benefits but is (in my opinion) not behavior I would expect to see. (1) is a huge change, and I'm not certain the annotation is worth the change. If anything were to be changed in this effort, I would have to say (2) is the only viable option, and even then I don't see enough payoff (in my use).

Is there a use-case where this is something more than "slightly informative"?

**Comment by krlmlr** [comment]
@r2evans: We certainly could have an `arranged_df` class; for SQL data sources the situation seems to be different, because there the order is known.

**Comment by JohnMount** [comment]
I agree the grouping annotation would have to be weak (be removed at the slightest provocation).  But without knowing if it there are not you can't tell if a pipe line is correct.

With the annotation present you can assure yourself that `data.frame(x=1:5) %>% arrange(x) %>% mutate(cs=cumsum(x))` does what you expect.  Right now there is no way to check if `data.frame(x=1:5) %>% arrange(x) %>% mutate(y=1) %>% mutate(cs=cumsum(x))` performs essentially the same calculation (summing x in order) as the data appearing to be in order is different than knowing the data is guaranteed to be in order.  As I filed in issue 2281  ( https://github.com/hadley/dplyr/issues/2281 ) even introduction of `dplyr::compute` or even `dplyr::collapse` can break the above pipeline for many data services.

As a matter of practice I always put the `arrange` as late as possible in real code (so after the `mutate(y=1)`).  Even the annotation appearing and disappearing would make teaching this precaution easy (it would allow us to show even though the data appears ordered for local data frames, it is not longer so guaranteed).  It also gives us a basis for even documenting which operators preserve or do not preserve the order annotation.

I don't consider checking if `dplyr` itself thinks the `arrange` has survived (a one-sided test, if `dplyr` says it is there it is still there) to be a small thing.  It is crucial in checking if fairly simple pipelines containing `arrange` have the expected meaning.

**Comment by r2evans** [comment]
(I agree, and I often do the same.) Thoughts.

Let's say we have something like:

```r
arrange(tbl_df(mtcars), cyl, qsec)
# Source: local data frame [32 x 11]
# Ordered: cyl, qsec
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
# *  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
# 1   21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
# 2   21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
# 3   22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
```

- if `arrange` is called again, it just updates the `$arranged_by` attribute
- `mutate*` and `summarise*` functions check if any of the arranged columns are changed; if so, it removes that grouping, such as:

```r
arrange(tbl_df(mtcars), cyl, qsec) %>%
  mutate(cyl = cyl + 1)
# Warning: dropping arranged columns: 'cyl'
# Source: local data frame [32 x 11]
# Ordered: qsec
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
# 1   26.0     5 120.3    91  4.43 2.140 16.70     0     1     5     2
# 2   30.4     5  95.1   113  3.77 1.513 16.90     1     1     5     2
# 3   30.4     5  75.7    52  4.93 1.615 18.52     1     1     4     2
```

- `select` ensures the dropped columns are removed from `$arranged_by`
- `filter` does nothing
- do we put any logic into `do`?
- `*_join` ...?
    - if `x` is arranged in `left_join`, `inner_join`, and `semi_join`, then order should be maintained (but I haven't verified it)
    - if `x` is arranged in `right_join`, `anti_join`, or `full_join`, arrangement is not guaranteed
    - if `y` is also arranged, "it depends"

**Comment by JohnMount** [comment]
Perhaps lose the arrange annotation in many cases (especially joins) to error on the side of caution.  And let the user supply an optional argument "preserveArrangement=TRUE" which tells the back-end to try to copy the "ORDER BY" clause forward to see if it can preserve the arrangement.  The idea being if preserving the arrangement has cost, don't do it.  If the user is willing to pay the cost let them so-specify.  I had been collecting my thoughts and work-arounds here: http://www.win-vector.com/blog/2016/12/parametric-variable-names-and-dplyr/

**Comment by hadley** [comment]
This could only apply to databases. If you want to be careful about the order of window functions otherwise, you'll have to use `order_by()`

**Comment by hadley** [comment]
I don't have time implement an `arranged_df` that preserves some arrangement attribute, but there's no reason it couldn't be done in another package.
