### ISSUE TITLE
Unexpected behavior with `log` used in a postgres database versus in R.

### ISSUE THREAD

**Issue by austenhead** [hadley/dplyr#2288]
If you use `log` in a postgres database, it flips the names of the input parameters for the base and the value to take the log of. This might be because the order of variables as defined by psql https://www.postgresql.org/docs/current/static/functions-math.html is "`log(b numeric, x numeric)` numeric logarithm to base b" as opposed to in R where it is `log(x, base = exp(1))`.

Below is a minimal example showing how this might cause confusion for a user:

```
> con <- src_postgres("junk_db", "localhost")
> copy_to(con, data_frame(a = 2:5), "temp_dat")
Source:   query [?? x 1]
Database: postgres 9.5.3 [austen@localhost:5432/junk_db]

      a
  <int>
1     2
2     3
3     4
4     5
```

If you take the log of each value in `a` you expect it to be increasingin `a`, and that is in fact what happens with a local data_frame.
```
> tbl(con, "temp_dat") %>% collect %>% mutate(b = log(a))
# A tibble: 4 x 2
      a            b
  <int>        <dbl>
1     2 0.6931471806
2     3 1.0986122887
3     4 1.3862943611
4     5 1.6094379124
```

If you do not bring it locally, then it flips the parameters `x` and `base`:
```
> tbl(con, "temp_dat") %>% mutate(b = log(a))
Source:   query [?? x 2]
Database: postgres 9.5.3 [austen@localhost:5432/junk_db]

      a            b
  <int>        <dbl>
1     2 1.4426950409
2     3 0.9102392266
3     4 0.7213475204
4     5 0.6213349346
```

For your reference:
```
> log(x = 2, base = exp(1))
[1] 0.6931471806
> log(x = exp(1), base = 2)
[1] 1.442695041
```
you can see the first row those two previous code blocks for column `b`.

When we define the parameter names we see that this is still an issue:
```
> # expect `b` to be increasing in `a`
> tbl(con, "temp_dat") %>% mutate(b = log(a, base = exp(1)))
Source:   query [?? x 2]
Database: postgres 9.5.3 [austen@localhost:5432/junk_db]

      a            b
  <int>        <dbl>
1     2 1.4426950409
2     3 0.9102392266
3     4 0.7213475204
4     5 0.6213349346
>
> # expect `b` to be decreasing in `a`
> tbl(con, "temp_dat") %>% mutate(b = log(base = a, exp(1)))
Source:   query [?? x 2]
Database: postgres 9.5.3 [austen@localhost:5432/junk_db]

      a            b
  <int>        <dbl>
1     2 0.6931471806
2     3 1.0986122887
3     4 1.3862943611
4     5 1.6094379124
```

If this is the intended result, it might help users to specify in the databases vignette that the order of the parameters may correspond to the order of the parameters in the database rather than the standard order as in R.

**Comment by krlmlr** [comment]
Ouch. MySQL behaves the same, RSQLite doesn't know a two-argument log() function.

@hadley: log(b, x) in SQL is like log(x, b) in R. Do we continue passing through arguments for log(), or do we swap (potentially breaking existing code)?

```r
src <- src_mysql("test", user = "xxx")
name <- dplyr:::random_table_name()
DBI::dbWriteTable(src$con, name, data_frame(a = 2:5))
data <- src %>% tbl(name)
data %>%
  mutate(b = log(a), c = log(exp(1), a)) %>%
  mutate(d = b * c)
```

**Comment by hadley** [comment]
Blech, I'd rather provide a consistent wrapper. I think this might break some existing code, but it's likely to be relatively small, and it think it's the best of bad options.  

For SQLite we should translate manually (i.e. to `log(x) / log(b)` or whatever the correct algebra is)
