### ISSUE TITLE
Use window functions in summarise()

### ISSUE THREAD

**Issue by karldw** [hadley/dplyr#2290]
This issue is almost identical to #531, but the trouble is with `summarize` instead of `mutate`.  The issue for `mutate` was fixed in commit f633484109d343dca62af69dff234e455e9d2ef0.
(This is not a regression; using `mutate` instead of `summarize` works as expected.)

Here's a reproducible example:
```r
mtcars2 <- copy_to(src_postgres(), mtcars)
mtcars2 %>%
  group_by(cyl) %>% 
  summarize(mpg2 = first(mpg))

Error in eval(expr, envir, enclos) : could not find function "first"

# Expected result:
mtcars %>%
  group_by(cyl) %>% 
  summarize(mpg2 = first(mpg))
# A tibble: 3 × 2
    cyl  mpg2
  <dbl> <dbl>
1     4  22.8
2     6  21.0
3     8  18.7
```

I'm using dplyr 0.5.0 (I also tested the development version, 0.5.0.9000), RPostgreSQL 0.4-1, and Postgres 9.5.5.

Thanks for the great package!

**Comment by krlmlr** [comment]
Thanks, confirmed. I also wonder why mutate(... = first()) doesn't issue a warning, because the data aren't ordered explicitly.

**Comment by hadley** [comment]
This is actually a new feature - currently dplyr does not support using window functions in aggregation. I didn't realise this immediately because it does the opposite - it does support aggregate functions in a windowed context.

**Comment by hadley** [comment]
@karldw do you have an example of the SQL you'd expect that to generate?  It's not obvious to me how the `GROUP BY` and window functions would interact here.

**Comment by karldw** [comment]
@hadley, sorry, bringing in window functions is messier than I realized, and probably not worth the hassle.  I was imagining [something like this](https://wiki.postgresql.org/wiki/First/last_%28aggregate%29), which defines `FIRST()` and `LAST()` as postgres aggregation functions.  

The use-case I had in mind was using `first()` as a way to include values from a variable outside the set of group-by variables.  For that purpose any value will due, so `min()` or `max()` would work equally well.
```r
mtcars2 <- copy_to(src_postgres(), mtcars)
mtcars2 %>%
  group_by(cyl) %>% 
  summarize(mpg2 = min(mpg))
```
_______________________
In other cases the difference between `min`/`max`/`first`/`last` will matter.  Is it worth defining these  postgres-specific `first` and `last` functions to make the database syntax match the data.frame syntax?

Otherwise, the user could always do something like this:
```r
library(RPostgreSQL)
first_cmd <- "CREATE OR REPLACE FUNCTION public.first_agg ( anyelement, anyelement )
RETURNS anyelement LANGUAGE SQL IMMUTABLE STRICT AS $$
        SELECT $1;
$$;
 
-- And then wrap an aggregate around it
CREATE AGGREGATE public.FIRST (
        sfunc    = public.first_agg,
        basetype = anyelement,
        stype    = anyelement
);"
dbExecute(mtcars2$src$con, first_cmd)

# Now these are the same:
# (arrange because this only matters if we care about row order)
x <- mtcars %>%
    group_by(cyl) %>% 
    arrange(wt) %>%
    summarize(mpg2 = first(mpg))

y <- mtcars2 %>%
    group_by(cyl) %>% 
    arrange(wt) %>%  
    summarize(mpg2 = FIRST(mpg)) %>%
    collect()

identical(x, y)
```

**Comment by hadley** [comment]
This now feels very postgres specific to me, so I'd say it's outside the scope of dplyr.  It's a bit mystifying why SQL doesn't define `first()` and `last()` as standard aggregate functions though (well I guess it's because SQL doesn't care about order, so they're not well defined in a group by)

**Comment by iangow** [comment]
> This now feels very postgres specific to me, so I'd say it's outside the scope of dplyr. It's a bit mystifying why SQL doesn't define `first()` and `last()` as standard aggregate functions though (well I guess it's because SQL doesn't care about order, so they're not well defined in a group by)

I think SQL powers-than-be dislike the idea of "includ[ing] values from a variable outside the set of group-by variables … [where] any value will d[o]." The `first()` and `last()` functions would seem to be rather non-deterministic. And I think that is something that standard SQL is not happy with (SAS SQL *will* do this, but often at the cost of suppressing data issues).

This produces the same as the above example using the user-defined `first` SQL aggregate:

```r
mtcars2 %>%
    group_by(cyl) %>% 
    summarize(wt = min(wt)) %>%
    inner_join(mtcars2) %>%
    select(cyl, mpg)
```

But I think it has the advantage of being more explicit about what is being done. If there are multiple values of `mpg` for a given element of `{ (cyl, wt): wt == min(wt) | cyl}`, then which one will be chosen? One approach is to make an explicit choice:

```r
mtcars2 %>%
    group_by(cyl) %>% 
    summarize(wt = min(wt)) %>%
    inner_join(mtcars2) %>%
    group_by(cyl) %>%
    summarize(mpg = min(mpg))
```
