### ISSUE TITLE
databases vignette recommends sql() instead of build_sql() for raw SQL

### ISSUE THREAD

**Issue by byandell** [hadley/dplyr#2291]
https://github.com/hadley/dplyr/blob/master/vignettes/databases.Rmd

Reading the manual page for `build_sql()` would indicate this is strongly preferred over `sql()` for raw SQL. However, the databases vignette still contains the following:

You can also use arbitrary SQL:

```{r, eval = FALSE}
tbl(my_db, sql("SELECT * FROM flights"))
```

Perhaps it would be helpful to replace with `build_sql()` and to caution readers about [SQL injection attacks](https://xkcd.com/327/)

**Comment by hadley** [comment]
You want `sql()` if you have written the SQL yourself.
