### ISSUE TITLE
src_postgres doesn't accept service argument

### ISSUE THREAD

**Issue by timabe** [hadley/dplyr#2292]
I connect to a lot of different postgres databases, so I find it useful to use the [pg_service.conf](https://www.postgresql.org/docs/9.4/static/libpq-pgservice.html) file.

`src_postgres` doesn't accept service as one of the `...` arguments. I looked into it and it appears it's because the driver is created using `RPostgreSQL::PostgreSQL()`, whereas if it was using `RPostgres::Postgres()` instead it would accept the service argument. [Here's the line I'm referring to.](https://github.com/hadley/dplyr/blob/master/R/src-postgres.r#L105)

I don't know much about how solid the [RPostgres](https://github.com/rstats-db/RPostgres) package is, so maybe the fix isn't as simple as changing the function call for the driver but perhaps we can discuss here.

**Comment by krlmlr** [comment]
You should be able to create your own private version of `src_postgres()`. Unfortunately, it will probably take some time until RPostgres hits CRAN; dplyr might switch to using RPostgres then.

```r
library(DBI)
library(dplyr)
"%||%" <- function(x, y) if(is.null(x)) y else x

db_disconnector <- function(con, name, quiet = FALSE) {
  reg.finalizer(environment(), function(...) {
    if (!quiet) {
      message("Auto-disconnecting ", name, " connection ",
              "(", paste(con@Id, collapse = ", "), ")")
    }
    dbDisconnect(con)
  })
  environment()
}

src_postgres2 <- function(dbname = NULL, host = NULL, port = NULL, user = NULL,
                         password = NULL, ...) {
  if (!requireNamespace("RPostgres", quietly = TRUE)) {
    stop("RPostgres package required to connect to postgres db", call. = FALSE)
  }

  user <- user %||% ""

  con <- dbConnect(RPostgres::Postgres(), host = host %||% "", dbname = dbname %||% "",
                   user = user, password = password %||% "", port = port %||% "", ...)
  info <- dbGetInfo(con)

  src_sql("postgres", con,
          info = info, disco = db_disconnector(con, "postgres"))
}

src_postgres2()
```
