### ISSUE TITLE
order_by() silently fails with a 'complex' call argument

### ISSUE THREAD

**Issue by adder** [hadley/dplyr#2293]
Hi,
Order_by() is wrong when using more then 1 function in the 'call' argument.
It does not order the data anymore.
I demonstrate this with a modified version of the example given in the help of order_by().

```
set.seed(10)
df <- data.frame(year = 2000:2005, value = (0:5) ^ 2)
scrambled <- df[sample(nrow(df)), ]
wrong <- mutate(scrambled, running = cummax(cumsum(value)))
arrange(wrong, year)
year value running
## 1 2000     0      30
## 2 2001     1      10
## 3 2002     4      30
## 4 2003     9       9
## 5 2004    16      26
## 6 2005    25      55
right <- mutate(scrambled, running = order_by(year, cummax(cumsum(value))))
arrange(right, year)
  year value running
## 1 2000     0      30
## 2 2001     1      30
## 3 2002     4      30
## 4 2003     9      30
## 5 2004    16      30
## 6 2005    25      55
right2 <- arrange(scrambled,year) %>%mutate(running = cummax(cumsum(value)))
arrange(right2, year)
  year value running
## 1 2000     0       0
## 2 2001     1       1
## 3 2002     4       5
## 4 2003     9      14
## 5 2004    16      30
## 6 2005    25      55

```
One would expect that `right == right2` since you would expect that in both `right1` and `right2` `cummax(cumsum(value))` is evaluated on a dataframe ordered by year.

Best

**Comment by krlmlr** [comment]
Thanks. Could you please make the example reproducible by setting the random seed? I don't understand why `right` should be the same as `right2`, could you please explain?

**Comment by adder** [comment]
Updated issue with your requests

**Comment by krlmlr** [comment]
Thanks, confirmed. Currently, `order_by()` doesn't support anything that is not a simple function call, the following two should work as expected:

```R
mutate(
  scrambled,
  running1 = order_by(year, cumsum(value)),
  running2 = order_by(year, cummax(running1))) %>%
  arrange(year)

cumsummax <- function(x) cummax(cumsum(x))
mutate(
  scrambled,
  running = order_by(year, cumsummax(value))) %>%
  arrange(year)
```

We should throw an error here or provide a working (perhaps also hybrid) implementation. Related: #2297.

**Comment by adder** [comment]
Thanks for the answer!

Note that in your first suggestion you will need to order twice (once for `cumsum` and once for `cummax`) which can be expensive when you have a very big dataframe.
(Therefore my suggestion to add an `order_by()` argument to `mutate()` in #2294 )

**Comment by krlmlr** [comment]
Can we close this again and continue the discussion in #2297?

**Comment by adder** [comment]
Sure! 
I accidentally miss clicked couple of times on the `Close` button. But it can be closed :)

**Comment by adder** [comment]
Just realised there is still this bug here that i fails silently in the complex case so reopen if you want.

**Comment by krlmlr** [comment]
Thanks. I think we'll handle both in #2297, the issues are very closely related.
