### ISSUE TITLE
add 'order_by' argument to mutate()

### ISSUE THREAD

**Issue by adder** [hadley/dplyr#2294]
HI
This can be considered as a feature request.
I feel that mutate() could benefit from an 'order_by' argument.
This would benefit when multiple window functions are used inside mutate while you still want to preserve the overall ordering of the data frame. (Something I encountered recently in my own work)

Following example should work.
```
df = data_frame(x = 10:1, y = 1:10, z = 11:20)
df2 = mutate(df, y2 = order_by(x,cumsum(y)), y3 = order_by(x,cummean(y2)), z2 = order_by(x,cumsum(z)))
df3 = mutate(df, y2 = cumsum(y), y3 = cummean(y2), z2 = cumsum(z), order_by = x)
df2 == df3
#TRUE
```
When implemented properly, df3 could be faster then df2 for large dataframes since you only have to order once internally.
This would also allow to get around the bug in issue  #2293 because then you can call multiple functions sequentially on the same column in mutate().

Or is there some other (efficient) way to achieve this?

**Comment by krlmlr** [comment]
@hadley: Given that `order_by()` only works for simple cases with data frames (#2293), we might want to consider a new verb that allows specifying an order in which the mutation occurs. How about `mutate_ordered()`?

**Comment by hadley** [comment]
dplyr should already respect the ordering of the data if present. So you can already do:

```R
df <- data_frame(x = 10:1, y = 1:10, z = 11:20)

df %>%
  arrange(x) %>%
  mutate(y2 = cumsum(y), y3 = cummean(y2), z2 = cumsum(z))
```

**Comment by krlmlr** [comment]
The only difference I see is that the new verb would preserve the original order. @adder: Could you describe why/when preserving the original order is important?

**Comment by adder** [comment]
Yes, I had to use case of preserving the original order in mind without having to use `arrange()` twice on big data frames.
I my use case, I have function in a package that is exposed to users that takes a dataframe as input and outputs that dataframe with some extra columns in the same order as input. That same function is also sometimes used in simulations where it's called many times (where the computation time of 2 arranges is more clear)

**Comment by hadley** [comment]
Basically, I think it's a reasonable idea, but I don't like the proposed syntax, and it's sufficiently low priority that it's unlikely to ever get fixed, so I'm just going to close the issue now.
