### ISSUE TITLE
Why is there no option overwrite=TRUE in dplyr's copy_to function ? 

### ISSUE THREAD

**Issue by pachevalier** [hadley/dplyr#2296]
The sparklyr package has a copy_to function with option overwrite = TRUE/FALSE. I think it would be nice to have the same option in dplyr's copy_to function. Is there any reason why this option doesn't exist ?

**Comment by krlmlr** [comment]
@hadley: Adding an `overwrite` argument to `copy_to()` should be easy enough to implement.

> The sparklyr package has a copy_to function with option overwrite = TRUE/FALSE. I think it would be nice to have the same option in dplyr's copy_to function. Is there any reason why this option doesn't exist ?

**Comment by hadley** [comment]
Yeah I think that's reasonable.

**Comment by mbojan** [comment]
I think it would be also useful in `compute()`
