### ISSUE TITLE
Several functions (with prepending) won't work if you don't load dplyr

### ISSUE THREAD

**Issue by johneverettkoo** [hadley/dplyr#2297]
Because of namespace conflicts, I typically avoid `library` and instead prepend everything (e.g., either `dplyr::mutate` or `dp <- loadNamespace('dplyr')` and `dp$mutate`). If I don't want to prepend, I'll use `import` (e.g., ``import::from(magrittr, `%>%`)``). Sometimes this doesn't work because of unaccounted dependencies and such, but most of the tidyverse packages seem to work perfectly with these. The two issues I've run into so far are `dplyr::order_by` and `dplyr::data_frame`. I noticed that `dplyr::order_by` work as expected if I first run `import::from(dplyr, with_order)` and `dplyr::data_frame` will work as expected if I first run `import::from(tibble, as_tibble)`, but it would be nice if I could avoid that.

**Comment by krlmlr** [comment]
Thanks. This makes sense, but could you please provide a reproducible example?

**Comment by johneverettkoo** [comment]
The example for `order_by` doesn't work:

```
> dplyr::order_by(10:1, cumsum(1:10))
Error in eval(expr, envir, enclos) : could not find function "with_order"
```

You have to first `library(dplyr)` (which can lead to namespace conflicts) or:

```
> import::from(dplyr, with_order)
> dplyr::order_by(10:1, cumsum(1:10))
 [1] 55 54 52 49 45 40 34 27 19 10
```

And I just tried `dplyr::data_frame` and that one seems to work as expected (maybe I updated something recently).

**Comment by krlmlr** [comment]
Thanks, confirmed. `order_by()` is performing nonstandard evaluation and currently expects `with_order()` to be accessible from the caller's environment.

**Comment by krlmlr** [comment]
Need to make it work with complex calls or throw an error, see #2293.

**Comment by johneverettkoo** [comment]
Thank you!

**Comment by hadley** [comment]
Adding @lionel- since this is NSE related
