### ISSUE TITLE
is.null & is.na are missing parentheses

### ISSUE THREAD

**Issue by JohnMount** [hadley/dplyr#2302]
Using the RSQLite dplyr adaption of tbl dplyr::mutate I am seeing previous values of the left-hand side of assignments lost in certain situations.  I think it has to do with types (int/double/logical) causing some confusion.

Example below (and [here](https://github.com/WinVector/replyr/blob/master/issues/SQLiteColtypes.md)):

```{r lclob}
library('dplyr')
d <- data.frame(x=c(1,2,2),y=c(3,5,NA),z=c(NA,'a','b'),
                rowNum=1:3,
                stringsAsFactors = FALSE)
print(d)

fnam <- tempfile(pattern = "dplyr_doc_narm", tmpdir = tempdir(), fileext = "sqlite3")
my_db <- dplyr::src_sqlite(fnam, create = TRUE)
class(my_db)
dRemote <- copy_to(my_db,d,'d',rowNumberColumn='rowNum',overwrite=TRUE)


# correct calculation
dRemote %>% mutate(nna=0) %>%
  mutate(nna=nna+ifelse(is.na(x),1,0)) %>% 
  mutate(nna=nna+ifelse(is.na(y),1,0)) %>% 
  mutate(nna=nna+ifelse(is.na(z),1,0))  
 
# incorrect calculation (last step seems to always clobber the previous result)
dRemote %>% mutate(nna=0) %>%
  mutate(nna=nna+is.na(x)) %>% 
  mutate(nna=nna+is.na(y)) %>% 
  mutate(nna=nna+is.na(z))

# clean up
rm(list=setdiff(ls(),'fnam'))
if(!is.null(fnam)) {
  file.remove(fnam)
}
gc()
```

**Comment by krlmlr** [comment]
Thanks, confirmed. Need to add parens in the [SQL rendering of is.null() and is.na()](https://github.com/hadley/dplyr/blob/30da3a0a3367b30b865629b95412838f1459eefc/R/translate-sql-base.r#L98-L103). Would you like to contribute a fix?

**Comment by JohnMount** [comment]
krlmlr, I'd be thrilled to.  Your diagnosis plus `dplyr::explain` made the problem very clear.  My pull request is here: https://github.com/hadley/dplyr/pull/2307 .
