### ISSUE TITLE
Hybrid version of max(NA_real_, na.rm = TRUE) returns NA

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2305]
```r
data_frame(a = NA_real_) %>% summarise(a = max(a, na.rm = TRUE))
## # A tibble: 1 × 1
##       a
##   <dbl>
## 1    NA
```

**Comment by krlmlr** [comment]
@hadley: I wonder what the behavior of the following should be:

```r
data_frame(a = NA_integer_) %>% summarise(a = max(a, na.rm = TRUE))
data_frame(a = integer()) %>% summarise(a = max(a))
```

Current code sets `a` to `NA_integer_`. It would be more consistent with base R to return `-Inf` instead, but this requires promoting to `numeric`.

**Comment by hadley** [comment]
Does base R always return a numeric? That might be a consistent principle. What does/should `max(NA)` return?

**Comment by krlmlr** [comment]
`max(int_arg)` returns an integer in base R.

The hybrid version of `max(NA_integer_)` returns `NA_integer_`, with both `na.rm = TRUE` or `= FALSE`.
