### ISSUE TITLE
Rule for old = new versus new = old? Currently inconsistent in rename vs recode

### ISSUE THREAD

**Issue by rgknight** [hadley/dplyr#2314]
The ship has probably sailed on this one, and this is just a shout into the wind, which is fine. 

For what it's worth, `rename` uses the `new = old` pattern and `recode` uses `old = new`.

These are conceptually similar tasks, and I always have to look up which uses which pattern.

Is there a principle behind why the patterns are different that would help me keep them straight?

**Comment by hadley** [comment]
Oh bummer :(  I didn't notice that - there's definitely no underlying principle.

**Comment by bjoerm** [comment]
Hey guys,
I wanted to raise the same thing as I also found recode's syntax counter-intuitive and wanted to add some more points on that:

Generally in dplyr and in R generally, the syntax is: new <- old.

Examples:
* ```rename(iris, petal_length = Petal.Length) ``` [new = old]
* ```mutate(iris, Petal.Length.New = Petal.Length*2) ``` [new = old]
* ```iris$Petal.Length.New <- iris$Petal.Length*2) ``` [new <- old]
* ...

So, on the left hand side, the new variable is set/defined and on the right hand side the old variable / or input for it is defined.

In my humble opinion recode acts counterituitively related to this. In dplyr's recode it is the "old" variable on the left hand side while the "new" variable is on the right hand side.

**Is:**
 ```recode(iris$Species, "versicolor" = "new_value_name")  ``` **[old = new]**

**Expected syntax (switch of "old" and "new" values:**
```recode(iris$Species, "new_value_name" = "versicolor") ``` [new = old]

As @rgknight already stated this input might be too late as costs of changing this now - and breaking people's code might be higher than the gain. Thus, feel free to ignore this post. ;-)
