### ISSUE TITLE
group_by_ + arrange_

### ISSUE THREAD

**Issue by mplourde** [hadley/dplyr#2318]
`arrange_` used to respect groupings. Now I often find myself using the idiom ` do(arrange_(., ~cpm))` to order groups individually for, say, a cumulative sum along time within groups.

Would it be feasible to add an argument to `arrange_` or create a new function, say, `group_arrange_` to encapsulate this?

Thank you.

**Comment by hadley** [comment]
Yeah, I'll bring this back as an option.

**Comment by hadley** [comment]
Adding this will need to wait until after the NSE rewrite since additional arguments to the generic are currently captured in `.dots`
