### ISSUE TITLE
Improve output of check_supported_type()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2319]
https://github.com/krlmlr/dplyr/commit/fe6bf8cc4443e0d4e4a9520bbdb50c4e31313db1#commitcomment-20176973

Perhaps include check for POSIXlt column.

@hadley: What should the error messages look like? Currently: `Unsupported type CLOSXP for column "foo"`

**Comment by hadley** [comment]
I'm not exactly sure but more like: ``Column `foo` is a function, not an atomic vector``

I'm not sure the best way of phrasing error messages:

*  ``Column `foo` is a function, not an atomic vector``
*  ``Column `foo` is not an atomic vector (currently a function)``
* ``Column `foo` must be an atomic vector, not a function``

Maybe the last one?
