### ISSUE TITLE
[Request] Function to remove constant columns

### ISSUE THREAD

**Issue by kendonB** [hadley/dplyr#2320]
This seems like a common operation when subsetting a table with a large number of identifier columns.

This is my current function for this (only problem I can see is that it depends on ``purrr``:

```
remove_constants <- function(.data){
  .data %>% 
    purrr::map(function(x){
      if(length(unique(x)) == 1){
        return(NULL)
      } else {
        return(x)
      }
    }) %>% 
    purrr::compact() %>% 
    tibble::as_tibble()
}
```

**Comment by hadley** [comment]
This doesn't feel right for dplyr either, sorry.
