### ISSUE TITLE
mutate() gives an error when using a function with ".data" argument

### ISSUE THREAD

**Issue by sjPlot** [hadley/dplyr#2324]
**This issue applies to the current dev-version 0.5.0.9000!**
```
.data <- mtcars[1:3, ]
mutate(.data, label = colnames(.data)[1:3])

> Error in mutate_impl(.data, dots) : 
>   Unsupported type NILSXP for column "label"

x <- mtcars[1:3, ]
mutate(x, label = colnames(x)[1:3])

# works
```

Not sure, but *might* be related to this issue: https://github.com/hadley/dplyr/issues/2187

**Comment by krlmlr** [comment]
Thanks. `.data` and `.env` are now reserved words in dplyr verbs, see NEWS. Could you please point me to the original use case?

**Comment by krlmlr** [comment]
Just saw it in the referenced issue. After renaming `.data` you should be good.

**Comment by sjPlot** [comment]
Ok, thanks, so this issue can be closed, I guess...
