### ISSUE TITLE
More concise SQL for joins

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2333]
using table aliases (https://github.com/hadley/dplyr/pull/1997#issuecomment-230762351):

```r
left_join(memdb_frame(a=1, b=1), memdb_frame(b=1, c=1)) %>% sql_render()
```

should be rendered as

```sql
SELECT 'a', 'LEFT'.'b', 'c'
FROM 
  'df1' AS 'LEFT'
  LEFT JOIN 'df2' AS 'RIGHT' ON ('LEFT'.'b' = 'RIGHT'.'b')
```

**Comment by hadley** [comment]
I think the full simplification is a bit ambitious. But currently that code generates:

```sql
SELECT `a`, `b.x` AS `b`, `c`
FROM (SELECT * FROM (SELECT `a` AS `a`, `b` AS `b.x`
FROM `zsehqamiji`)

LEFT JOIN

(SELECT `b` AS `b.y`, `c` AS `c`
FROM `voqvboddta`)

ON (`b.x` = `b.y`))
```

which we should at least be able to simplify to:

```sql
SELECT `a`, `b.x` AS `b`, `c`
FROM (
   SELECT `a` AS `a`, `b` AS `b.x` FROM `zsehqamiji`
   LEFT JOIN (SELECT `b` AS `b.y`, `c` AS `c` FROM `voqvboddta`) 
   ON (`b.x` = `b.y`)
)
```

See @javierluraschi's initial work at https://github.com/javierluraschi/dplyr/commit/3d3bec391aa62b1519d264b87eb5dd31d5971ae6

**Comment by hadley** [comment]
Managed to figure out how to do it - variable computation is now moved much further up the stack.
