### ISSUE TITLE
mutate_all doesn't handle NULLs

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#2337]
```R
drop_if_all_na <- function(x) {
  if (all(is.na(x))) {
    NULL
  } else {
    x
  }
}

mtcars$mpg <- NA

mtcars %>% 
  dplyr::mutate_all(drop_if_all_na)
```

cc @lionel-

**Comment by krlmlr** [comment]
@hadley: This looks related to #2187, where we decided that functions that return `NULL` don't remove the column -- only a literal `NULL` does.

**Comment by krlmlr** [comment]
That will be difficult in a grouped operation.

**Comment by hadley** [comment]
But we must already handle that

**Comment by krlmlr** [comment]
We can handle different return values/types per group, but how do we remove a column in some groups only?
