### ISSUE TITLE
Feature request: use "distinct on" from Posgres to allow keeping all columns

### ISSUE THREAD

**Issue by karldw** [hadley/dplyr#2340]
Currently, `distinct(..., .keep_all=TRUE)` only works with local data because standard SQL doesn't know how to look at distinct values of a subset of columns.
However, [Postgres does](https://www.postgresql.org/docs/current/static/sql-select.html#SQL-DISTINCT), with the `DISTINCT ON` syntax, so it should be possible for the postgres SQL generation to allow `.keep_all=TRUE`.

Examples:
```r
library(dplyr)
mtcars2 <- copy_to(src_postgres(), mtcars)

distinct(mtcars,  cyl, .keep_all=TRUE)  # This works

distinct(mtcars2, cyl, .keep_all=TRUE)  # This could work, but doesn't

Error: Can't calculate distinct only on specified columns with SQL unless .keep_all is FALSE
```

**Comment by krlmlr** [comment]
Thanks. So, the corresponding SQL would be

```sql
SELECT DISTINCT ON (cyl) * FROM mtcars
```

? Which other DBMS support this syntax?

**Comment by karldw** [comment]
Yes, that looks like the right syntax.

I don't know any other DBMS that have the `DISTINCT ON` syntax, but it looks like the same thing can be accomplished (for MySQL and SQLite) with a `GROUP BY` and including non-aggregating columns in the select. 

#### Non-aggregating group by
```sql
SELECT * FROM mtcars GROUP BY cyl
```
 (This is non-standard SQL; [some people on the internet are unhappy about it](http://stackoverflow.com/a/3168601).)

I'm less sure about other DBMS, but if there are any that would be particularly worth testing, let me know.

<details>

Here are some examples, stolen from [here](https://bernardoamc.github.io/sql/2015/05/04/group-by-non-aggregate-columns/).
### MySQL example

```sql
CREATE TABLE games (
  game_id int AUTO_INCREMENT ,
  name VARCHAR(18),
  price INT,
  released_at DATE,
  publisher VARCHAR(14),
  PRIMARY KEY (game_id)
);

INSERT INTO games (name, price, released_at, publisher) VALUES
  ('Metal Slug Defense', 30, '2015-05-01', 'SNK Playmore'),
  ('Project Druid', 20, '2015-05-01', 'shortcircuit'),
  ('Chroma Squad', 40, '2015-04-30', 'Behold Studios'),
  ('Soul Locus', 30, '2015-04-30', 'Fat Loot Games'),
  ('Subterrain', 40, '2015-04-30', 'Pixellore');

SELECT * FROM games GROUP BY released_at;
```

### SQLite example

```sql

CREATE TABLE games (
  name VARCHAR,
  price BIGINT,
  released_at DATE,
  publisher TEXT
);

INSERT INTO games (name, price, released_at, publisher) VALUES
  ('Metal Slug Defense', 30, '2015-05-01', 'SNK Playmore'),
  ('Project Druid', 20, '2015-05-01', 'shortcircuit'),
  ('Chroma Squad', 40, '2015-04-30', 'Behold Studios'),
  ('Soul Locus', 30, '2015-04-30', 'Fat Loot Games'),
  ('Subterrain', 40, '2015-04-30', 'Pixellore');

SELECT rowid AS game_id, * FROM games GROUP BY released_at;

```


### PostgreSQL example

```sql
CREATE TABLE games (
  game_id serial PRIMARY KEY,
  name VARCHAR,
  price BIGINT,
  released_at DATE,
  publisher TEXT
);

INSERT INTO games (name, price, released_at, publisher) VALUES
  ('Metal Slug Defense', 30, '2015-05-01', 'SNK Playmore'),
  ('Project Druid', 20, '2015-05-01', 'shortcircuit'),
  ('Chroma Squad', 40, '2015-04-30', 'Behold Studios'),
  ('Soul Locus', 30, '2015-04-30', 'Fat Loot Games'),
  ('Subterrain', 40, '2015-04-30', 'Pixellore');


SELECT DISTINCT ON (released_at) * FROM games;
```

</details>

**Comment by krlmlr** [comment]
@hadley: Would you support `distinct(..., .keep_all = TRUE)` for SQL backends? We'll need to use backend-specific syntax (for PostgreSQL) and nonstandard but documented behavior ([SQLite](https://www.sqlite.org/lang_select.html#resultset) and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html)), we'd still fail in the default case.

**Comment by hadley** [comment]
I'd rather not implement this.  You can always do `df %>% group_by(x) %>% slice(1)` as a work around.

**Comment by krlmlr** [comment]
Will slicing work with SQLite and MySQL? These DBMS don't support window functions.

**Comment by hadley** [comment]
Hmmm, you could also use `summarise_all(first)` but neither SQLite not MySQL support that (although if we really wanted to we could add as an extension function in RSQLite).  We could support something like `memdb_frame(x = c(1, 1, 2), y = 1:3) %>% group_by(x) %>% select(everything())` but that's starting to feel too esoteric for me. 

Generally, I've steered away from implementing database backend stuff that's only well supported by a few databases.

**Comment by karldw** [comment]
Okay, thanks!
