### ISSUE TITLE
Is there any function to update single cell value in a datafrme

### ISSUE THREAD

**Issue by sibojan** [hadley/dplyr#2341]
I normally change a value in a cell at  row x, column y  by usng     **"df[x,y] <- expected_value"**

This seems not work with the chain       **"df %>%  df[x,y] <- expected_value"**

Is there any function in dplyr for that ? 

just like    **XXX_function (df, x, y, expected_value)**

Thanks.

**Comment by krlmlr** [comment]
There's the "tee" pipe in magrittr that may be helpful:

```r
library(magrittr)
df %>T% .[x,y] <- expected_value
```

It is a shorthand for

```r
df %>% { .[x,y] <- expected_value; . }
```

The dot `.` is replaced by the pipe's left-hand side when processing (in your case, `df`).

Actually, this is more a magrittr question, please consider asking on StackOverflow next time.

**Comment by sibojan** [comment]
Thank you so much.  I think a lot of people firstly got to know the pipe operator through the famous package dplyr and thought they may have all the functions for pipe operation.
