### ISSUE TITLE
Different behavior for bind_rows(dfs) vs do.call(rbind, dfs)

### ISSUE THREAD

**Issue by steveharoz** [hadley/dplyr#2343]
When combining multiple data frames, the first one can have a column with overly specific elements (strings that happen to be made entirely of numbers) or overly broad elements (only NAs).

With `do.call(rbind, dfs)`, that doesn't prevent you from combining them.

But with `bind_rows(dfs)`, it throws an error.

Example:
```
df1 = data_frame(a = 1:3, b = c(NA, NA, NA))
df2 = data_frame(a = c('x', 'y'), b = c(TRUE, FALSE))
listOfDFs = list(df1, df2)

bind_rows(listOfDFs) 
# Error in eval(substitute(expr), envir, enclos) : 
# Can not automatically convert from integer to character in column "a".

do.call(rbind, listOfDFs) # works
> # A tibble: 5 × 2
>      a     b
> * <chr> <lgl>
> 1     1    NA
> 2     2    NA
> 3     3    NA
> 4     x  TRUE
> 5     y FALSE
```

**Comment by steveharoz** [comment]
@krlmlr `do.call(bind_rows, listOfDFs)` produces the same error as `bind_rows(listOfDFs)`

**Comment by krlmlr** [comment]
Thanks. Please coerce columns as necessary before binding with `bind_rows()`.

**Comment by hadley** [comment]
Confirming that this is a deliberate design choice
