### ISSUE TITLE
summarize_all and special cases of groups with one row

### ISSUE THREAD

**Issue by liori** [hadley/dplyr#2345]
I'd like to suggest a switch `summarize_all(..., keep.single.rows=F)` which, when set to TRUE, would make `summarize_all` not apply the summary function to groups that only have one row, and instead just copy the value from that row as a result.

Rationale: I have a dataset that defines features for certain objects identified by an `id` column. A small percentage of objects have multiple rows: the process that generated the dataset didn't update a preexisting record for the object, and created a new one instead. I am using `group_by(id) %>% summarize_all` to merge these rows with a function that is basically `sum(., na.rm=T)`, except for returning NA if all values were NAs. After `group_by` roughly 99% of groups contain only one row. I found that `summarize_all` is pretty slow dealing with so many groups, but if I run it only on the groups with at least 2 rows, and then simply append the one-row groups to the result, I get the result 20 times faster. A small test case follows.

```
library(microbenchmark)
library(dplyr)
library(magrittr)
library(digest)

check <- function(x) {
  # simple function to check if the results are the same
  print(digest(as.matrix(x %>% arrange(id)), 'xxhash64'))
}

# comment to enable the above check
check <- function(x) { x }

# construction of the test dataset
set.seed(0)
size.a <- 40000
size.b <- 100
df <- rbind(
  data.frame(
    id=rep(1:size.a),
    c1=rnorm(size.a),
    c2=rnorm(size.a),
    c3=rnorm(size.a)),
  data.frame(
    id=1:size.b,
    c1=5,
    c2=6,
    c3=7
  ))
df[cbind(1:(size.a + size.b), sample(2:4, size.a + size.b, replace=T))] <- NA
df[cbind(1:(size.a + size.b), sample(2:4, size.a + size.b, replace=T))] <- NA

# base case: ifelse
f.base <- function() {
  df %>%
    group_by(id) %>%
    summarise_all(funs(ifelse(all(is.na(.)), NA, sum(., na.rm=T))))
}

# use plain summarize (https://github.com/hadley/dplyr/issues/2273)
f.plain <- function() {
  f <- function(x) ifelse(all(is.na(x)), NA, sum(x, na.rm=T))
  df %>%
    group_by(id) %>%
    summarise(c1=f(c1), c2=f(c2), c3=f(c3))
}

# separate function that defines the summary
f.sepfun <- function() {
  sum.or.na <- function(v) {
    if (length(v) == 1) {
      # most common path
      v
    } else if (all(is.na(v))) {
      NA
    } else {
      sum(v, na.rm=TRUE)
    }
  }

  df %>%
    group_by(id) %>%
    summarise_all(funs(sum.or.na))
}

# splitting the dataset into separate dataframes with groups of size 1 and >1
f.split <- function() {
  df.counts <- df %>%
    group_by(id) %>%
    tally()
  bind_rows(
    inner_join(df, df.counts %>% filter(n == 1), 'id') %>%
      select(-n),
    inner_join(df, df.counts %>% filter(n > 1), 'id') %>%
      select(-n) %>%
      group_by(id) %>%
      summarize_all(funs(ifelse(all(is.na(.)), NA, sum(., na.rm=T)))))
}

print(microbenchmark(
  base=check(f.base()),
  plain=check(f.plain()),
  sepfun=check(f.sepfun()),
  split=check(f.split()),
  times=10))
## Unit: milliseconds
##    expr        min         lq       mean     median         uq        max
##    base 2599.25944 2600.94581 2625.62968 2611.39280 2649.21580 2693.32052
##   plain 2315.16358 2330.13785 2359.65496 2339.89149 2373.36026 2504.77806
##  sepfun 1931.27061 1940.38471 1960.58301 1953.67650 1959.84701 2025.14748
##   split   36.79834   37.72446   38.63369   37.99195   39.09826   43.84651
```

**Comment by krlmlr** [comment]
You could also split the data:

```r
full <- data_frame(group = c(1, 1, 2, 3), data = runif(4)) %>% group_by(group)
groups <- filter(full, n() > 1)
singletons <- filter(full, n() <= 1)
```

The proposed functionality looks very specific to me; you could achieve the same by specifying a function that returns the input if its length = 1, at the expense of calling back to R for each group.

**Comment by liori** [comment]
It's an optimization for a certain common case, and I would really like to avoid calling back into R for this case exactly because it's slow.

**Comment by krlmlr** [comment]
I just saw that you did time the split I suggested, and it appears to be much faster than calling back to R for each group. I'm just not convinced we need to enhance the `summarise()` verb, in particular because the desired optimization can be achieved easily by other means. It's not up to me to decide, though.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself.
