### ISSUE TITLE
compilation failed for package

### ISSUE THREAD

**Issue by vicfg84** [hadley/dplyr#2346]
* installing *source* package 'lazyeval' ...
** package 'lazyeval' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.4/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.4/share/make/winshlib.mk" SHLIB="lazyeval.dll" OBJECTS="expr.o interp.o lazy.o name.o utils.o"' had status 127
ERROR: compilation failed for package 'lazyeval'
* removing 'C:/Users/VICTOR/Documents/R/win-library/3.2/lazyeval'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\VICTOR\Documents\R\win-library\3.2" "C:/Users/VICTOR/Documents/R/Packages/lazyeval_0.2.0.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/VICTOR/Documents/R/Packages/lazyeval_0.2.0.tar.gz’ had non-zero exit status

**Comment by krlmlr** [comment]
This is an installation error for the lazyeval package. Can you install the binary version via `install.packages("lazyeval", type = "binary")` ?
