### ISSUE TITLE
What is the function-search scope for summarize_?

### ISSUE THREAD

**Issue by billdenney** [hadley/dplyr#2348]
This appears to be similar to #456, #474, and maybe #2190.

When I use the `summarize` function, I have the scope search as expected.  When I use `summarize_`, the scope it looks in is not obvious and it does not find functions defined in the current scope.

I initially found this confusion with a function-in-a-function call like:

```
funa <- function(x) {
  funb <- function(y) {
    mean(y)
  }
  summarize(x, result=funb(a))
}

funa(data.frame(a=1:5))
```

That worked as expected, but then when I did a CRAN check on it, the variable "a" wasn't recognized.  So, I changed it to `summarize_` as follows:

```
func <- function(x) {
  fund <- function(y) {
    mean(y)
  }
  summarize_(x, result="fund(a)")
}

func(data.frame(a=1:5))
```

That didn't work with the error 'Error: could not find function "fund"'

I tried an additional variant (below), but it still didn't work.

```
fune <- function(y) {
  mean(y)
}
funf <- function(x) {
  summarize_(x, "result=fune(a)")
}
funf(data.frame(a=1:5))
```

And then, just to make sure I wasn't using `summarize_` incorrectly, I confirmed that it worked in a simpler case (it does):

```
fung <- function(x) {
  summarize_(x, result="mean(a)")
}
fung(data.frame(a=1:5))
```

**Comment by krlmlr** [comment]
The following works for me:

```r
func <- function(x) {
  fund <- function(y) {
    mean(y)
  }

  summarize_(x, result = ~fund(a))
}

func(data.frame(a = 1:5))
```

Can you confirm?

**Comment by billdenney** [comment]
It works for me, too.  

I'm mostly curious why that works, the version with double quotes (") doesn't work with a locally-defined function, but the version with double quotes and a standard function ("mean(y)") works.  The scoping seems odd and non-intuitive with quotes.

**Comment by krlmlr** [comment]
Unlike the string, the `~` formula also records the environment where it is defined.

**Comment by billdenney** [comment]
That the formula records the environment seems reasonable.  In the string form, can the environment be automatically discovered (or make a warning about scoping when using the string form if that's infeasible)?

**Comment by krlmlr** [comment]
@lionel-: I think this is specific to lazyeval/rlang, could you please comment?

**Comment by lionel-** [comment]
That's a defect in `all_dots()`:

```r
# records baseenv() instead of local env
local(lazyeval::all_dots("expr"))
```

But the string form is going to be deprecated soon. @billdenney you should use formula capture since it bundles both a scope and an expression.

**Comment by billdenney** [comment]
@lionel- 
The formula method was my eventual solution, but I didn't find it easily.  As this is going to be deprecated, it's not worth fixing that part.  Perhaps this issue could yield updated documentation of how to use the formula method for specifying the parameters.  I was looking at vignette("nse"), and had to piece it together from there.

**Comment by lionel-** [comment]
Yup we're currently working on better tools and documentation for programming with the tidyverse.
