### ISSUE TITLE
setdiff reverse option

### ISSUE THREAD

**Issue by blablablerg** [hadley/dplyr#2350]
When data cleaning/wrangling, I find myself using set operations in console quite frequently, to do quick checks on vectors/datasets. 

And very often, when I use` setdiff(x,y)`, I also want to see `setdiff(y,x)`.  Now with long variable names (e.g. `setdiff(dataframe$column.x,dataframe$column.y)` ), doing the reverse in console is less cumbersome with a reverse option. You can then just hit arrow up on the keyboard and append the reverse option.

for example: `setdiff(x,y,rev = T) ` ( the same as `setdiff(y,x)` )

Now of course I can make a function which does just that, but I figured I might not be the only one who would be interested in this feature. I hope I placed this request at the right place.

the tidyverse is amazing! keep up the good work :)

**Comment by krlmlr** [comment]
For now, you could use one of:

```r
setdiff(y = dataframe$column.x, dataframe$column.y)
setdiff(dataframe$column.x, x = dataframe$column.y)
```

I'm not sure how useful a `rev` option would be in the general case; if you are interested in both differences, a simple wrapper that computes the difference in both direction and returns e.g. a named list would do a better job IMO.

**Comment by hadley** [comment]
You could also do:

```R
diffset <- function(x, y) setdiff(y, x)
```
