### ISSUE TITLE
Cryptic error message from filter if input has NA in colnames

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#2351]
I know it's undesirable for a data frame to have `NA` in the colnames. But if it unfortunately does, `filter()` could give a more informative error message that indicates why it's failing.

``` r
library(tibble)
library(dplyr)

tb <- tibble(
  x = 1,
  y = 2,
  z = 3
)
colnames(tb)[1] <- NA
tb %>% filter(z > 0)
#> Error in filter_impl(.data, dots): missing value where TRUE/FALSE needed
```

**Comment by krlmlr** [comment]
Very soon, all verbs will be rejecting data frames with non-unique columns or NA columns.

**Comment by hadley** [comment]
@krlmlr can you please collect all these into a meta issue?
