### ISSUE TITLE
joining when a tibble has duplicate column names causes one column to overwrite the others

### ISSUE THREAD

**Issue by sfirke** [hadley/dplyr#2353]
The join operations fails as expected (the desired behavior IMO) when it's a `data.frame` that has duplicated names.  I managed to give myself a tibble that had duplicated names, and then this join succeeded, with undesirable behavior.

```
# Create a tibble with duplicated names
x1 <- data_frame(
  a = 1:5,
  b = 6:10,
  c = 11:15,
  d = 16:20
)
names(x1) <- c("a", "b", "b", "b")

# Same df but as a data.frame
x2 <- data.frame(
  a = 1:5,
  b = 6:10,
  b = 11:15,
  b = 16:20,
  check.names = FALSE
)

y <- data.frame(
  a = 1:4,
  d = letters[1:4]
) 

# the join is completed on the tibble but the first b column values displace the others:
left_join(x1, y, by = "a")

# A tibble: 5 × 5
      a     b   b.x b.x.x      d
  <int> <int> <int> <int> <fctr>
1     1     6     6     6      a
2     2     7     7     7      b
3     3     8     8     8      c
4     4     9     9     9      d
5     5    10    10    10     NA


# with a regular data.frame, the duplicate names are caught and it fails:
left_join(x2, y, by = "a")
```

> Error: Each variable must have a unique name.
> Problem variables: 'b', 'b'

**Comment by krlmlr** [comment]
@hadley: Okay to fail all verbs if duplicate column names found? (That would be alongside the encoding check for #1950.)

**Comment by hadley** [comment]
Yeah, I think so (even `rename()` won't help you get out of that situation)

**Comment by krlmlr** [comment]
We have `tibble::repair_names()` which fixes both cases. I'll raise an error that mentions this function.

**Comment by krlmlr** [comment]
Moving discussion to the canonical issue above.
