### ISSUE TITLE
`select` fails when a variable name occurs multiple times 

### ISSUE THREAD

**Issue by vspinu** [hadley/dplyr#2354]
Two cases I have noticed so far:

```r
# expect to reorder columns
> select(mtcars, carb, -carb) 
data frame with 0 columns and 32 rows

# expect to return same column twice
> select(mtcars, carb, carb) 
                    carb
Mazda RX4              4
Mazda RX4 Wag          4
Datsun 710             1
Hornet 4 Drive         1
Hornet Sportabout      2
Valiant                1
Duster 360             4
Merc 240D              2
Merc 230               2
Merc 280               4
Merc 280C              4
Merc 450SE             3
Merc 450SL             3
Merc 450SLC            3
Cadillac Fleetwood     4
Lincoln Continental    4
Chrysler Imperial      4
Fiat 128               1
Honda Civic            2
Toyota Corolla         1
Toyota Corona          1
Dodge Challenger       2
AMC Javelin            2
Camaro Z28             4
Pontiac Firebird       2
Fiat X1-9              1
Porsche 914-2          2
Lotus Europa           2
Ford Pantera L         4
Ferrari Dino           6
Maserati Bora          8
Volvo 142E             2
> 

```

**Comment by krlmlr** [comment]
This looks like expected behavior to me. @hadley: Please confirm that `select()` is supposed to de-duplicate column names.

**Comment by hadley** [comment]
Yeah, current behaviour is correct.

**Comment by vspinu** [comment]
You probably didn't notice first example:

```
# expect to reorder columns
> select(mtcars, carb, -carb) 
data frame with 0 columns and 32 rows
```

`-carb` stands for all other variables. There is no duplication.

What is the canonical way to re-arange variables in a data.frame?

**Comment by krlmlr** [comment]
The behavior in the first example is correct, because the negation comes after the inclusion and therefore takes precedence. The first argument after `mtcars` decides if it's an inclusive or exclusive select, `-carb` means to remove `carb` from the current set. The call `select(mtcars, -carb)` is only a shortcut for `select(mtcars, everything(), -carb)`. Is the documentation lacking here?

`select()` does rearrange variables.

**Comment by vspinu** [comment]
Ok, so it's some sort of incremental conjunction. I don't remember reading this in the docs. 

> select() does rearrange variables.

Ok, then how do I move `carb` in front then?

**Comment by krlmlr** [comment]
`select(mtcars, carb, everything())`

**Comment by vspinu** [comment]
Thanks! I actually just noticed there is indeed exactly this example in the docs.

**Comment by thackl** [comment]
Hi,

I get the idea of having `select` deduplicate column names/indices, but wouldn't some form of warning make sense? Here one particularly quirky example: the position of the column seems to be determined by the first appearance of the duplicated index, but the name by the last appearance.

```R
tibble(x="A",y="B") %>%
  select(y=2, x=1, z=2)
# A tibble: 1 x 2
  z     x    
  <chr> <chr>
1 B     A 
```

**Comment by lionel-** [comment]
That's a good point, maybe we should throw a warning if the names for selected variables do not agree. Could you file an issue in the tidyselect repo please?
