### ISSUE TITLE
Package Website

### ISSUE THREAD

**Issue by pgensler** [hadley/dplyr#2356]
Is it possible to have a package documentation website for dplyr to use as a reference for the functions? I know some of the tidyverse packages do have one, but it would be really helpful to direct other people to for help on functions such as innner_join or case_when.

**Comment by cderv** [comment]
I am willing to help with that if it is a go. 
However I could understand that some tidyverse website expert could be more efficient. 
Just know I am there to help if needed.

**Comment by hadley** [comment]
This will occur (along with a whole bunch of other changes) when dplyr officially moves into the tidyverse
