### ISSUE TITLE
Summarize cannot work with with $ and a name that is in the global environment but works with [[

### ISSUE THREAD

**Issue by billdenney** [hadley/dplyr#2362]
When I run the code below, the first call to summarize below gives an error `Error: invalid subscript type 'closure'`; the second call to summarize works as expected; and the third call to summarize suggests that the issue is that it's trying to use the time function from the global environment.

This appears to be related to #806 and #1400 though subtly different in aspect.  I think that it is specifically due to the fact that the output name in the data frame is also a function name defined in the global environment ("time").

```
dffun <- function(x) {
  data.frame(a=1, time=3)
}

tmp <- data.frame(d=1:5, e=6:10)

summarize(tmp, d=dffun(b)$time)
summarize(tmp, d=dffun(b)[["time"]])
summarize(tmp, d=dffun(b)$a)
```

**Comment by krlmlr** [comment]
Works for me in the development version of dplyr. Can you confirm?

**Comment by billdenney** [comment]
It works in the development version for me, too.  I'll keep my fingers crossed for a quick transition to CRAN for my production work.
