### ISSUE TITLE
dplyr::coalesce throws error if all elements of vector are NA

### ISSUE THREAD

**Issue by bhanowell** [hadley/dplyr#2363]
The following work fine:

    dplyr::coalesce(c(1, NA), 2)
    # [1] 1 2
    dplyr::coalesce(c(1), 2)
    # [1] 1

But these don't work and should:

    dplyr::coalesce(c(NA, NA), 2)
    # Error: Vector 1 has type 'double' not 'logical'
    dplyr::coalesce(NA, 2)
    # Error: Vector 1 has type 'double' not 'logical'

**Comment by krlmlr** [comment]
We should be more permissive here, but the following should work:

```r
dplyr::coalesce(NA_real_, 2)
```

**Comment by bhanowell** [comment]
Agree that coalesce should be more permissive, embarrassed I didn't just try the more explicit NA

**Comment by krlmlr** [comment]
#2209 might resolve this issue, could you please double-check?

**Comment by zeehio** [comment]
#2209 does not solve this issue, this issue goes through a different code path (this issue happens `R/utils-replace-with.R` while #2209 happens at `inst/include/dplyr/Collecter.h`).

**Comment by hadley** [comment]
I think fixing coercion issues in these less commonly used functions will have to wait for vctrs
