### ISSUE TITLE
arrange change data.table in data.frame in dplyr0.5 - Bug ?

### ISSUE THREAD

**Issue by Fablepongiste** [hadley/dplyr#2364]
Moving here an issue I initially opened in dtplyr. 
https://github.com/hadley/dtplyr/issues/37

Arrange is changing the class of the object it is applied too ? Look weird to me, should just arrange that's it.

dpyr 0.5 :
sdmdt <- split(mdt, mdt$player)

class(sdmdt$p1_id)
[1] "data.table" "data.frame"

sdmdt$p1_id <- arrange(sdmdt$p1_id, game_id)
class(sdmdt$p1_id)
[1] "data.frame"

dplyr 0.4.3
sdmdt <- split(mdt, mdt$player)

class(sdmdt$p1_id)
[1] "data.table" "data.frame"

sdmdt$p1_id <- arrange(sdmdt$p1_id, game_id)
class(sdmdt$p1_id)
"data.table" "data.frame"

**Comment by krlmlr** [comment]
I still think this issue belongs in dtplyr.
