### ISSUE TITLE
Group by adjacent values (i.e. no sort)

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#237]
a la http://stackoverflow.com/questions/21511257. Used to work with only adjacent groups. Easy enough to do with `cumsum()` and `diff()`, but probably not very efficient, and definitively not expressive.

**Comment by hadley** [comment]
This doesn't seem so important to me now. We might come back to again if we invest more in performance.

**Comment by cj-wilson** [comment]
Is there are status or up-vote on this feature?  I would like the ability to capture the next group in a group_by sequence and use that in a summarise or mutate.  Syntax aside, it would be nice to get lead_by(.x, type = group) or lead(group_id + 1) to capture the next group.

I have solved this in data.table with .I before, and similar shaped data frames with rle() and custom functions, but both get ugly switching back and forth.

What I have are long running tasks where I'm trying to create a rollup date.

df <- data.frame(polling_date = c(rep(as.Date("2016-10-16"), 3), 
                                rep(as.Date("2016-10-17"), 3),
                                rep(as.Date("2016-11-18"), 3)),
                 task_id = c(rep(1, 6), rep(2, 3)))
  polling_date task_id
1   2016-10-16       1
2   2016-10-16       1
3   2016-10-16       1
4   2016-10-17       1
5   2016-10-17       1
6   2016-10-17       1
7   2016-11-18       2
8   2016-11-18       2
9   2016-11-18       2

Ideally I'd like to be able to lead to the next group and mutate a complete_date to look like below.

  polling_date task_id completed_date
1   2016-10-16       1     2016-10-17
2   2016-10-16       1     2016-10-17
3   2016-10-16       1     2016-10-17
4   2016-10-17       1     2016-10-17
5   2016-10-17       1     2016-10-17
6   2016-10-17       1     2016-10-17
7   2016-11-18       2     2016-11-18
8   2016-11-18       2     2016-11-18
9   2016-11-18       2     2016-11-18
 
But a naive group_by() and lead() does not work.

df %>% group_by(polling_date) %>%
  mutate(completed_date = as.Date(ifelse(lead(polling_date) <= polling_date + lubridate::days(1),
                                    lead(polling_date),
                                    polling_date)))

 polling_date task_id completed_date
        <date>   <dbl>         <date>
1   2016-10-16       1     2016-10-16
2   2016-10-16       1     2016-10-16
3   2016-10-16       1           <NA>
4   2016-10-17       1     2016-10-17
5   2016-10-17       1     2016-10-17
6   2016-10-17       1           <NA>
7   2016-11-18       2     2016-11-18
8   2016-11-18       2     2016-11-18
9   2016-11-18       2           <NA>
