### ISSUE TITLE
bind_rows should give an error for databases

### ISSUE THREAD

**Issue by karldw** [hadley/dplyr#2373]
Using `bind_rows` or `bind_cols` on database tbls doesn't give the expected results, but also doesn't always raise an error.  Depending on the database backend, different things happen; postgres returns results while sqlite complains about incompatible sizes.  Instead, they could just see the `tbl_sql` class and error out.
```r
mtcars2 <- copy_to(src_postgres(), mtcars)
bind_rows(mtcars2, mtcars2)  # expected to get an error here
#>  A tibble: 6 × 2
#>                          src                ops
#>                       <list>             <list>
#> 1 <S4: PostgreSQLConnection> <S3: src_postgres>
#> 2                 <list [8]>        <S3: ident>
#> 3                      <env>         <chr [11]>
#> 4 <S4: PostgreSQLConnection> <S3: src_postgres>
#> 5                 <list [8]>        <S3: ident>
#> 6                      <env>         <chr [11]>

mtcars3 <- copy_to(src_sqlite(path=tempfile(), create = TRUE), mtcars)
bind_rows(mtcars3, mtcars3)  # expected a more informative error here
#> Error in bind_rows_(x, .id) : incompatible sizes (2 != 1)
```

----

Of course, it would be possible to write SQL translations for these, but I'm not sure they would be widely used.  For `bind_rows` it would be something like:
```sql
SELECT * FROM some_table
UNION ALL
SELECT * FROM some_other_table
```
Binding columns in SQL tables is probably a mistake but could be done by joining row numbers.

**Comment by krlmlr** [comment]
`bind_*()` should definitely do better error checking here.

**Comment by hadley** [comment]
@krlmlr this is actually a data frame bug, because it requires changes to the cpp code. I think the problem is in the `init` method for the `DataFrameable` class — it needs to check for a bare (`!is.object()`) list.
