### ISSUE TITLE
Big database queries require force-quit and lose all work in RStudio

### ISSUE THREAD

**Issue by lukeholman** [hadley/dplyr#2375]
If I accidentally send a big query to a database via dplyr, there seems to be no way to cancel the job (e.g. by pressing escape in R or RStudio) - you just have to wait for it to complete, or force-quit R. What's worse is that you cannot save the currently open scripts in RStudio while it's talking to the database, so if you've made any changes, these will be lost (or, you need to manually copy them into some often software and past them back later). 

I realise there might be limitations on what you can do on the R side (and that this is more of an RStudio than a dplyr question), but this is by far the most time-consuming and difficult aspect of writing some new scripts that use dplyr's awesome database functions. Would love a fix if it's possible.

Thanks!

**Comment by austenhead** [comment]
When dplyr is connected to postgres, I'm able to cancel a query from my database which then frees R back up. I lose my database connection, but then at least I'm able to save my work in R without having to force-quit it. I would expect that to be the case in other databases.

For example in postgres, you can get the process id `pid` by looking at
```sql
select pid, state, query_start, query from  pg_stat_activity;
```

and then terminating the query with
```sql
select pg_terminate_backend(the_pid_from_above);
```

**Comment by lukeholman** [comment]
Interesting, maybe it's just a SQLite3 problem then? I didn't really follow your code - I'm using the dplyr commands to talk to the database. I am instead doing something like this:

    my_db <- src_sqlite("FILENAME", create = F)
    my_tbl <- tbl(my_db, "NAME")
    my_tbl %>% filter(SOMETHING ACCIDENTALLY BIG) %>% collect(n = Inf) # R panics here due to the size of the query, and won't shut down or save

**Comment by austenhead** [comment]
Sorry, I should have mentioned that the commands I was running were in terminal after connecting to the database. I am able to kill the process from within the database itself which then causes an error in R and interrupts the dplyr connection to the database.

```
Austens-MBP:~ austen$ psql ## open postgres from terminal
psql (9.5.3)
Type "help" for help.

austen=# select pid, state, query_start, query from  pg_stat_activity;
<output from postgres>
```

**Comment by lukeholman** [comment]
Thanks, that looks handy! I'll have a go. Maybe this suggests a way to make R able to kill the database request too (much like how RStudio helps you enter Github commands into Terminal).

**Comment by krlmlr** [comment]
@lukeholman: Thanks. Could you please file an issue at the RSQLite repo? I think we need to implement a [query progress handler](https://www.sqlite.org/c3ref/progress_handler.html), but it has to happen in that package.

**Comment by hadley** [comment]
This is the responsibility of individual database backends - we're slowly pushing this behaviour out everywhere.
