### ISSUE TITLE
How to find class of all variables in the data (of type tbl_df) with dplyr

### ISSUE THREAD

**Issue by sergeganakou** [hadley/dplyr#2378]
For example I have:
`dt <- data.table(ID=c(rep("A", 5), rep("B",5)), Quarter=c(1:5, 1:5), value=rnorm(10))`

How can I find class of ID, Carter and value together

**Comment by sergeganakou** [comment]
Please, sommebody can help me.

Thank you

**Comment by krlmlr** [comment]
This kind of question is more suitable for StackOverflow. (What output do you want?)

**Comment by sergeganakou** [comment]
I want for exemple a vector who contains:

factor, factor, integer, numeric

**Comment by krlmlr** [comment]
`vapply(dt, class, character(1))` works, because `class(dt[[1]])` returns the class of the first element as a character, `class(dt[[2]])` of the second, and so on.

**Comment by sergeganakou** [comment]
Thank toi si much

**Comment by sergeganakou** [comment]
Thank you so much
