### ISSUE TITLE
Deprecate groups()

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2385]
Now we have group_vars() which better preserves character encoding (#2384).

**Comment by hadley** [comment]
I no longer think this is necessary due to other solutions to the encoding problem, and since this will still be useful for splicing into a `group_by()` call.

**Comment by krlmlr** [comment]
Should we perhaps remove `group_vars()` again, once we have converted to rlang?

**Comment by hadley** [comment]
I don't think so - it turns out to be useful in a lot of places (i.e. printing messages). Better to have the code in one place.
