### ISSUE TITLE
Renaming variables with rename_

### ISSUE THREAD

**Issue by tchakravarty** [hadley/dplyr#2391]
[_Cross-posted from [here](http://stackoverflow.com/q/41921094/1414455)._]

I am trying to rename several variables in a chain: 

    df_foo = data_frame(
      a.a = 1:10,
      "b...b" = 1:10,
      "cc..d" = 1:10
    )
    
    df_foo %>% 
      rename_(
        .dots = setNames(
          names(.),
          gsub("[[:punct:]]", "", names(.)))
      )

This works fine, but when there is a space in the name of one of the variables: 

    df_foo = data_frame(
      a.a = 1:10,
      "b...b" = 1:10,
      "c c..d" = 1:10
    )
    
    df_foo %>% 
      rename_(
        .dots = setNames(
          names(.),
          gsub("[[:punct:]]", "", names(.)))
      )

I get this error: 

    Error in parse(text = x) : <text>:1:3: unexpected symbol
    1: c c..d
          ^

I am not sure where this stems from since when I run `gsub` directly: 

    setNames(
          names(df_foo),
          gsub("[[:punct:]]", "", names(df_foo)))

I do not get an error. Not sure what is going on here.

**Comment by billdenney** [comment]
This is probably related to #1926 .

**Comment by krlmlr** [comment]
See also the canonical #2243 that collects all issues with spaces in column names.
