### ISSUE TITLE
read_table from a character vector

### ISSUE THREAD

**Issue by neuwirthe** [hadley/dplyr#2393]
read.table from base R allows
mydata <- read.table(text="
var1 var2
1    2
3   4
")

reading data directly embedded in the source code.
Can we get something similar in dplyr?

**Comment by cderv** [comment]
Hi, 
something like that is not included in `dplyr` but you can find such feature in the tidyverse. 
You have to look toward `readr` package. Here is an example: 

``` r
readr::read_delim("var1 var2
1 2
3 4
", delim = " ")
#> # A tibble: 2 x 2
#>    var1  var2
#>   <int> <int>
#> 1     1     2
#> 2     3     4
```

My advice : read the [Data Import Cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-import-cheatsheet.pdf) and look at [readr documentation site](http://readr.tidyverse.org/)

**Comment by neuwirthe** [comment]
Sorry, my fault. I should have read the docs more carefully.

**Comment by cderv** [comment]
No problem.  
Also, do not hesitate to search [Stackoverflow](stackoverflow.com) for such questions - it could help and sometimes more quickly.
