### ISSUE TITLE
left_join suffix

### ISSUE THREAD

**Issue by aetiologicCanada** [hadley/dplyr#2395]
x <-left_join(x,y, by=("ID"), suffix=c(".x", ".y")) # works as you would expect

x <-left_join(x,y, by=("ID"), suffix=c("", ".y")) # cobbles up CPU and memory and then dies badly

Sometimes it would be nice to not have a suffix for df_x, but have a suffix for df_y . 

It could at least trap for this "error"

Many thanks as always to Hadley and associates.

**Comment by krlmlr** [comment]
Thanks. This looks like a duplicate of #2228.
