### ISSUE TITLE
segrfault for bad variable names

### ISSUE THREAD

**Issue by ltierney** [hadley/dplyr#2397]
I get 
```
> group_by(faithful, foo)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort (core dumped)
```
Same for each of
```
mutate(faithful, bar = foo)
summarise(faithful, x = mean(foo))
filter(faithful, bar > 2)
arrange(faithful, foo)
```

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.2.0       assertthat_0.1 tools_3.3.2    DBI_0.5-1     
[6] tibble_1.2     Rcpp_0.12.9   
```

**Comment by lawremi** [comment]
Hit this the first time I tried to use it. Thought it was just me.

**Comment by hadley** [comment]
I get

```R
> group_by(faithful, foo)
Error in resolve_vars(new_groups, tbl_vars(.data)) : 
  unknown variable to group by : foo
```

I'm reasonably certain the crash is caused by a C++ API mismatch somewhere - try reinstalling dplyr + Rcpp.

**Comment by ltierney** [comment]
Thanks. Looks like just reinstalling dplyr was enough. Rather
disconcerting that the need to do this isn't picked up some other way
though.

On Tue, 31 Jan 2017, Hadley Wickham wrote:

> 
> I get
> 
> > group_by(faithful, foo)
> Error in resolve_vars(new_groups, tbl_vars(.data)) :
>   unknown variable to group by : foo
> 
> I'm reasonably certain the crash is caused by a C++ API mismatch somewhere -
> try reinstalling dplyr + Rcpp.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[ADvaVBZUkF1eR0IBzEQ4M4Yt-m3fY4ZNks5rX7rCgaJpZM4Ly6bF.gif]
> 
> 
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   luke-tierney@uiowa.edu
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by krlmlr** [comment]
Please see #2335 for an attempt to work around this problem.

**Comment by hadley** [comment]
Yeah, it is — but we've bought this up a number of times on R-devel and haven't gotten any interest in a general fix.

**Comment by ltierney** [comment]
If the issue is changes in Rcpp requiring a reinstall of dplyr then this seems to be between you and Dirk to resolve how to indicate/check for binary incompatible changes, If it is something else thenit may be a broader issue.

**Comment by hadley** [comment]
It's a broader issue. It also occurs with packages like R6 and memoise that create objects at package build time. The key emails are https://stat.ethz.ch/pipermail/r-devel/2016-December/073505.html (by @krlmlr) and https://stat.ethz.ch/pipermail/r-devel/2016-December/073516.html (by @gaborcsardi).

In an ideal world neither of these problems would occur because people would have better ABI hygiene and implement compile time checking of versions. But currently this problem is affecting a lot of people.
