### ISSUE TITLE
Add compatibility with RPostgres

### ISSUE THREAD

**Issue by jacktanner** [hadley/dplyr#2398]
I'd like to add compatibility with RPostgres. I'd like to add copy `src_postgres.r` to `src_rpostgres.r`, replacing `PostgreSQLConnection` with `PqConnection`, and to make the necessary additions to `API`. 

Would such a patch be accepted?

**Comment by hadley** [comment]
We're going to provide a generic DBI backend in the next release.

**Comment by jacktanner** [comment]
Thanks. Are the changes for this already in git?

**Comment by hadley** [comment]
No
