### ISSUE TITLE
select_if fails with non-standard colnames

### ISSUE THREAD

**Issue by ringprince** [hadley/dplyr#2403]
```
library("dplyr")
dat <- data_frame(`a/b` = 1:3, `b/c` = c("a", "b", "c"))
dat
# # A tibble: 3 × 2
#   `a/b` `b/c`
#   <int> <chr>
# 1     1     a
# 2     2     b
# 3     3     c

dat %>% select_if(is.numeric)
# Error in eval(expr, envir, enclos) (from lazy-eval.R#27) : object 'a' not found
```

**Comment by krlmlr** [comment]
Thanks. #2243 is the canonical ticket for this problem.

**Comment by ringprince** [comment]
Yes, thanks.  I had overlooked that open issue under its old title.  Thanks for updating.

**Comment by krlmlr** [comment]
No worries. I find that searching the GitHub repo (search bar at top) for the function/verb that causes the problem (select_if in this case) often finds the relevant issue(s) if they have been reported already.
