### ISSUE TITLE
New operator for updating of an object

### ISSUE THREAD

**Issue by wgrundlingh** [hadley/dplyr#2405]
I often use the following syntax for updating of an object:

```
x <- x %>% function(y, ...)
```

While the duplication of `x` makes the syntax and operation clear, I'm wondering whether it would be possible to implement an operator that specifically handles this case: An update of an existing variable. The motivation here is akin to what C++ provides with its assignment operators like `+=`, for example

```
x += y // Equivalent to x = x + y
```

Perhaps something like `%<%` which incorporates `<` of the regular assignment `<-` with the pipe `%>%`:

```
x %<% function(y, ...) # Equivalent to x <- x %>% function(y, ...)
```

...or `%<>%`, or `%>>%`, ...?

**Comment by yutannihilation** [comment]
I guess it is `%<>%` operator in [magrittr](https://github.com/tidyverse/magrittr/blob/master/vignettes/magrittr.Rmd#additional-pipe-operators), the package actually providing `%>%` :)

**Comment by wgrundlingh** [comment]
Thanks. Indeed, [`magrittr`](https://cran.r-project.org/package=magrittr) does provide `%<>%` that is compatible with [`dplyr`](https://cran.r-project.org/package=dplyr). Would have been great if this was included natively as part of loading `dplyr` (as part of [`utils.r`](https://github.com/hadley/dplyr/blob/master/R/utils.r)); that is, importing `%<>%` in addition to `%>%` from `magrittr`.
