### ISSUE TITLE
Change the way arrange works whenever it applies to a subquery

### ISSUE THREAD

**Issue by alexfun** [hadley/dplyr#2409]
When using dplyr to connect to (PostgreSQL) databases, it is possible to generate queries using explain that result in ordering subquery tables, e.g.:

```

SELECT * FROM (SELECT *
FROM "dplyr_join_test_2"
ORDER BY "id") "muovbnptiu"

INNER JOIN

(SELECT *
FROM "dplyr_join_test_1"
ORDER BY "id" DESC) "mskvbxbcfj"

USING ("id")
```

The ordering of each subquery table is not guaranteed to be preserved in the final result, however, this behaviour is not consistent with joining tibbles existing in memory. Further, if I am not wrong, unless the ordering is actually required in the subquery (e.g. in conjunction with row limit clauses), it will just cause the database additional overhead.

On my system (postgres 9.5, dplyr_0.5.0), to create the data in postgres:

```
create table dplyr_join_test_1 (
id serial primary key
);

create table dplyr_join_test_2 (
id serial primary key,
var1 serial
);

insert into dplyr_join_test_1 select generate_series(1,10)
insert into dplyr_join_test_2 select generate_series(1,10)

```

Then, in R:

```
tmp_db <- src_postgres(dbname = ..., user = ..., password = ...)


t1 <- 
    tbl(tmp_db, 'dplyr_join_test_1') %>%
    arrange(desc(id))
    
t2 <- 
    tbl(tmp_db, 'dplyr_join_test_2') %>%
    arrange(id)
```

Now, if we do the join in the database, we get:

```
> final_t <-
+     inner_join(t1, t2) 
Joining, by = "id"
> 
> # explain(final_t)
> 
> final_t %>% collect
# A tibble: 10 × 2
      id  var1
*  <int> <int>
1     10    10
2      9     9
3      8     8
4      7     7
5      6     6
6      5     5
7      4     4
8      3     3
9      2     2
10     1     1
```

vs:

```
> final_t_2 <-
+     inner_join(t2, t1)
Joining, by = "id"
> 
> # explain(final_t_2)
> 
> final_t_2 %>% collect
# A tibble: 10 × 2
      id  var1
*  <int> <int>
1     10    10
2      9     9
3      8     8
4      7     7
5      6     6
6      5     5
7      4     4
8      3     3
9      2     2
10     1     1
```

However, if we pull t1 and t2 into memory, then the joins result in the first table's ordering of the join keys being preserved:

```
> t1_col <- collect(t1)
> t2_col <- collect(t2)
> 
> inner_join(t1_col, t2_col)
Joining, by = "id"
# A tibble: 10 × 2
      id  var1
   <int> <int>
1     10    10
2      9     9
3      8     8
4      7     7
5      6     6
6      5     5
7      4     4
8      3     3
9      2     2
10     1     1
> inner_join(t2_col, t1_col)
Joining, by = "id"
# A tibble: 10 × 2
      id  var1
   <int> <int>
1      1     1
2      2     2
3      3     3
4      4     4
5      5     5
6      6     6
7      7     7
8      8     8
9      9     9
10    10    10
```

**Comment by hhoeflin** [comment]
This is simply not supported from PostgreSQL and I don't think a dplyr issue.

http://stackoverflow.com/questions/16248813/is-order-in-a-subquery-guaranteed-to-be-preserved

**Comment by alexfun** [comment]
I acknowledge in my original post: "The ordering of each subquery table is not guaranteed to be preserved in the final result"

What I am worried about is:

1) The ordering in the subquery might lead to excessive overhead.
2) If you did not know sql but were familiar with dplyr, you might have expected the latter results where the ordering does matter.

**Comment by hhoeflin** [comment]
Just to clarify: I understand your post to mean that you would like dplyr to guarantee that in all joins, the resulting table is ordered by the same variables in the same fashion as the left-hand table?

My main worry there would be that databases are burdened with unnecessary ORDER  BY statements that the user never intended and that may slow down query execution. As a note - are you sure that "inner_join" in R is "guaranteed" to preserve the ordering of the left table in the join? This may be the case in the current implementation and the example you chose, but a (I admit very cursory) glance at the manual did not show me a guarantee of such an ordering.

**Comment by hadley** [comment]
Yeah, I think this is just unfortunately a case with R and SQL behaviour have to differ.
