### ISSUE TITLE
Problem with dplyr function in my own function

### ISSUE THREAD

**Issue by RajuKadam** [hadley/dplyr#2411]
Hi,
I am writing my own function using the dplyr function to calculate the mean for DV variable grouped by PROT and TIME. Below is the code .

ds <- data.frame(PROT=c(rep("1001",150), rep("1002",150)), 
                 TIME=rep(1:10, 30), DV=rnorm(n = 300, mean = 5, sd = 2))

simpleFunction <- function(dataset, x, y, z){
  require("dplyr")
  dataset %>% 
    group_by_(x, y) %>%
    summarize(Mean = mean(z, na.rm=T)) -> dataset
  return(dataset)
}
simpleFunction(ds, "PROT", "TIME" ,"DV")

When I run this code I am getting following warning message and not able to get the desired mean  for DV column. 

Source: local data frame [20 x 3]
Groups: PROT [?]

     PROT  TIME  Mean
   <fctr> <int> <dbl>
1    1001     1    NA
2    1001     2    NA
3    1001     3    NA
4    1001     4    NA
5    1001     5    NA
6    1001     6    NA
7    1001     7    NA
8    1001     8    NA
9    1001     9    NA
10   1001    10    NA
11   1002     1    NA
12   1002     2    NA
13   1002     3    NA
14   1002     4    NA
15   1002     5    NA
16   1002     6    NA
17   1002     7    NA
18   1002     8    NA
19   1002     9    NA
20   1002    10    NA
Warning message:
In mean.default(z, na.rm = T) :
  argument is not numeric or logical: returning NA

But when I modify the function and provide "DV" column name  instead of "z" and calculate the mean, I am getting desired output. I have checked the class of ds$DV and is numeric. 

simpleFunction <- function(dataset, x, y){
  require("dplyr")
  dataset %>% 
    group_by_(x, y) %>%
    summarize(Mean = mean(DV, na.rm=T)) -> dataset
  return(dataset)
}
simpleFunction(ds, "PROT", "TIME") 

Source: local data frame [20 x 3]
Groups: PROT [?]

     PROT  TIME     Mean
   <fctr> <int>    <dbl>
1    1001     1 5.362157
2    1001     2 5.264628
3    1001     3 4.813591
4    1001     4 5.633571
5    1001     5 5.812283
6    1001     6 5.495334
7    1001     7 4.936804
8    1001     8 4.770942
9    1001     9 4.247990
10   1001    10 5.124358
11   1002     1 5.325702
12   1002     2 4.903428
13   1002     3 4.965815
14   1002     4 3.841613
15   1002     5 4.923110
16   1002     6 4.972442
17   1002     7 5.111439
18   1002     8 4.792860
19   1002     9 4.715480
20   1002    10 4.479319

**Comment by the-knife** [comment]
Seems to be rather a problem of standard evaluation than dplyr itself.
You are trying to execute this code :
```R
mean("DV", na.rm = T)
```

This workaround should work :
```R
simpleFunction <- function(dataset, x, y, z) {
dataset %>%
  group_by_(x, y) %>%
  summarize_(MEAN = paste0("mean(", z, ", na.rm = TRUE)")) #note underscore after summarize
}
simpleFunction(ds, "PROT", "TIME" ,"DV")
```

Note summarize_ instead of summarize.

Not particularly beautiful, maybe there is a more elegant way in `vignette("nse")`

**Comment by RajuKadam** [comment]
Thanks a lot for your help.

Best Regards,
Raj Kadam
