### ISSUE TITLE
filter_if, filter_at, filter_all

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#2417]
i.e.

```R
filter_all(.tbl, .funs, ...)
filter_if(.tbl, .predicate, .funs,  ...)
filter_at(.tbl, .cols, .funs, ...)
```

**Comment by hadley** [comment]
Probably `.funs` should be a predicate function that's supplied to each column

**Comment by lionel-** [comment]
Should we have `ifs()` and `ifs_any()` functions that would allow creating a "superpredicate" of the intersection or union of supplied predicates?

**Comment by hadley** [comment]
I don't like that as an API. Let's brainstorm some more ideas when we talk next.

**Comment by jonocarroll** [comment]
Could this be capable of conditionally applying the `filter` at all? i.e. whether or not to perform the `filter` operation or just pass along the data? Similar to `ifelse(condition, filter(.data, .pred), .data)`. Or would that be another operation entirely?

**Comment by hadley** [comment]
@jonocarroll no, that's something else completely

**Comment by jonocarroll** [comment]
Ah, fair enough. Cheers.

**Comment by hadley** [comment]
I think the best solution would be to add an argument to filter (and these helpers) like `collapse = c("and", "or"))`.

**Comment by lionel-** [comment]
@hadley are you sure it's not better to have `funs()` variants? I find this much clearer:

```r
filter_if(mtcars, ifs(is_double, is_integer), ifs_any(disp > 300, cyl > 6))
```

than this:

```r
filter_if(mtcars, is_double(.) && is_integer(.), disp > 300, cyl > 6, .collapse = "or")
```

The first one reads like a sentence while the second feels like a rebus.

**Comment by lionel-** [comment]
> The first one reads like a sentence while the second feels like a rebus.

I think that's because surrounding the predicates in a functional form makes the boundaries between arguments (and thus groups of predicates) clearer. And by the same token you immediately know whether it's an union or the intersection thanks to the function name.

**Comment by lionel-** [comment]
Would it make sense to generate calls for each selected column when we detect a `.`, but not otherwise?

Then these two would be equivalent:

```r
filter(iris, Sepal.Length > 4, Sepal.Width > 3)
filter_if(iris, is_double, ifs_any(Sepal.Length > 4, Sepal.Width > 3))
```

but we'd be able to do:

```r
filter_if(iris, is_double, ifs_any(. > 4, Petal.Species == "setosa"))
filter_at(iris, vars(starts_with("Sepal")), ifs(ifs_any(. > 4), Petal.Species == "setosa"))
```

The latter would generate `(Sepal.Length > 4 || Sepal.Width > 4) && Petal.Species == "Setosa"`. I'm not sure this is possible to implement in a principled way though. Hmm maybe with unquoting:

```{r}
filter_at(iris, vars(starts_with("Sepal")), ifs(!! ifs_any(. > 4), Petal.Species == "setosa"))
```

**Comment by hadley** [comment]
Ok, I think you're right about functions being better. I don't like `ifs()` vs `ifs_any()`, but it's the names, not the general idea. Maybe just `if_all()` and `if_any()`?  (Although I don't like the doubling of the if: `filter_if(df, if_all(. > 5))`

I don't think we need special NSE with `.` detection — we should just require an explicit formula function.

**Comment by lionel-** [comment]
> Although I don't like the doubling of the if

How about `all_of()` and `any_of()`?

```r
filter_if(df, is_double, any_of(cyl == 4, am == 1))
```

**Comment by hadley** [comment]
I like it!

**Comment by hadley** [comment]
Although that example doesn't really make sense, I assume you'd either want:

```R
filter(mtcars, any_of(cyl == 4, am == 1))
# or
filter_if(mtcars, is_double, any_of(. < 0, . %% 2 == 0))
```
