### ISSUE TITLE
secure connection DB

### ISSUE THREAD

**Issue by xhudik** [hadley/dplyr#2419]
*Is there a secure way (no listed password in a source code) how to connect to DB?*

I read: https://www.rdocumentation.org/packages/dplyr/versions/0.5.0/topics/src_postgres but didnt find anything like this...

If not specifically Postgres,  do dplyr allow other databases to connect securely?

It would be great to have a possibility to connect via a password file (https://www.postgresql.org/docs/9.1/static/libpq-pgpass.html)

**Comment by ThoDuyNguyen** [comment]
I stored connection information in environment variable and use `Sys.getenv()` to retrieve. 
What is the best practice for now?

**Comment by xhudik** [comment]
Storing this info within environmental variable (especially password) is not very good. Store a path to  particular file (with all connection info) on a save place is a better option...

Therefore, I'm wondering how this is done in dplyr....

**Comment by alexfun** [comment]
Have you seen this: http://stackoverflow.com/questions/13033573/how-to-handle-db-passwords-in-r-connection-strings

**Comment by hadley** [comment]
This is out of scope from dplyr, but RStudio will announce something in the next couple of months.

**Comment by dlebauer** [comment]
@hadley any updates?

**Comment by dlebauer** [comment]
specifically re 

> RStudio will announce something in the next couple of months.

**Comment by hadley** [comment]
The big pieces exist but have not yet been tied together in the IDE:

* https://github.com/rstudio/config
* https://github.com/gaborcsardi/keyring
