### ISSUE TITLE
Lead and lag 'default' argument must be named explicitly in grouped tibble

### ISSUE THREAD

**Issue by alexfun** [hadley/dplyr#2421]
Using sample data:

```
df = data.frame(name=rep(c('Al','Jen'),3),
                score=rep(c(100, 80, 60),2))
```

Doing the following operation produces the wrong result:

```
# incorrect
df %>%
    arrange(name) %>%
    group_by(name) %>%
    mutate(next.score = lead(score, 1, 0),
           before.score = lag(score, 1, 0))

Source: local data frame [6 x 4]
Groups: name [2]

    name score next.score before.score
  <fctr> <dbl>      <dbl>        <dbl>
1     Al   100        100          100
2     Al    60         60           60
3     Al    80         80           80
4    Jen    80         80           80
5    Jen   100        100          100
6    Jen    60         60           60
```

Either explicitly calling the functions with `dplyr::` or naming the argument `default = ` produces the expected result:

```
# correct
df %>%
    arrange(name) %>%
    group_by(name) %>%
    mutate(next.score = lead(score, default = 0),
           before.score = lag(score, default = 0) )

# correct
df %>%
    arrange(name) %>%
    group_by(name) %>%
    mutate(next.score = dplyr::lead(score, 1, 0),
           before.score = dplyr::lag(score, 1, 0) )


Source: local data frame [6 x 4]
Groups: name [2]

    name score next.score before.score
  <fctr> <dbl>      <dbl>        <dbl>
1     Al   100         60            0
2     Al    60         80          100
3     Al    80          0           60
4    Jen    80        100            0
5    Jen   100         60           80
6    Jen    60          0          100
```

Typing `lag` into the console produces the dpylr lag function. and tis is my session info:

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] dplyr_0.5.0     purrr_0.2.2     readr_1.0.0     tidyr_0.6.0     tibble_1.2      ggplot2_2.2.0   tidyverse_1.0.0> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8       lattice_0.20-34   zoo_1.7-13        assertthat_0.1    R6_2.2.0          grid_3.3.2        plyr_1.8.4       
>  [8] DBI_0.5-1         gtable_0.2.0      magrittr_1.5      scales_0.4.1      RPostgreSQL_0.4-1 lazyeval_0.2.0    xts_0.9-7        
> [15] tools_3.3.2       munsell_0.4.3     colorspace_1.3-1

**Comment by krlmlr** [comment]
Thanks. We're planning to improve argument matching in the hybrid evaluator, #2299 is the canonical issue.
