### ISSUE TITLE
Feature request: allow variable as the end of a chain

### ISSUE THREAD

**Issue by tmalsburg** [hadley/dplyr#2433]
It would be convenient to be able to pipe the results of a processing chain into a variable as in the following example:

```r
mtcars %>%
  filter(mpg > median(mpg)) %>%
  efficient.cars
```

Currently this produces an error (`could not find function "efficient.cars"`) but I think it would be very useful if we were able to do this.  There is a simple fix,

```r
mtcars %>%
  filter(mpg > median(mpg)) ->
  efficient.cars
```

but this means that I often have to switch `->` and `%>%` during development (every time, the last step in a chain changes) and this creates unnecessary friction.

I think it would be logically consistent to allow piping into a variable since we also can pipe from a variable.  Thanks for considering this and sorry if this has been discussed previously.

**Comment by tmalsburg** [comment]
Context: http://www.win-vector.com/blog/2016/12/the-case-for-using-in-r/

**Comment by klmr** [comment]
I think this belongs in [magrittr](/tidyverse/magrittr) not dplyr. At any rate it isn’t currently possible because of the reason stated in the error message: if the last identifier in a pipe chain is a name, it’s interpreted as a function name. That is, `… %>% foo` is equivalent to `… %>% foo()`.
