### ISSUE TITLE
I cannot connect postgresql schema.table with dplyr package

### ISSUE THREAD

**Issue by diegogarcilazo** [hadley/dplyr#244]
I wrote this question before to know about GitHub/hadley/dplyr.
http://stackoverflow.com/questions/21592266/i-cannot-connect-postgresql-schema-table-with-dplyr-package

Thanks for dplyr, ggplots, reshape2 and .....

**Comment by hhoeflin** [comment]
Hi Hadley,

I am having the same issue and the nesting seems to be a problem for performance (in my case a serious one as I am working on data with 100s million rows). Could you elaborate on why your last try failed?

Thanks

**Comment by HarlanH** [comment]
FWIW, for some use cases a helpful idiom is:

    dbSendQuery(con$con, build_sql("SET search_path TO ", schema_name))

Then subsequent queries using that connection are within that schema.

**Comment by hhoeflin** [comment]
Hi Harlan,

thanks - and I am using something like that already (except I am expanding the search path by the schema. But it only helps so far. If you have tables with the same names in 2 schemas, it won't.

Anyway, I was wondering why not overload the '$' sign in the base_scalar SQL translator. 

It would even make sense from an r perspective

a$b$c, there a would be an environment (i.e. a schema), b a table and c a column. The only think that has to be fixed then is tbl_sql, that shouldn't check in such a simple fashion if the table_name exists in the database. Instead, it could check if a "SELECT" statement is part of the SQL query and if not, add a SELECT * in front and check the variables this way.

In this case, one could even enable NSE for the tbl function?

**Comment by hhoeflin** [comment]
Oh yes, one more comment:

dbSendQuery 

often does not work for RJDBC (at least with vertica). The query above, i.e. SET search_path TO ...

does not return a result. dbSendQuery does expect one. For vertica, this does not work and one has to use dbSendUpdate. Is that also the case for MySQL (or at least does dbSendUpdate not fail for MySQL)?

**Comment by hadley** [comment]
I like the idea of overloading `$`. I'll definitely think about it when I'm next working on dplyr.

@hhoeflin have you tried RPostgreSQL instead of RJDBC for talking to vertica?

**Comment by hhoeflin** [comment]
No - had no that RPostgreSQL is an option. In any case - the vertica backend is now implemented for RJDBC already.

In any case - I was running into a few performance problems - I think related to the nesting of SELECT statements in SQL and was thinking of rewriting parts of the SQL generator. The idea would be to make joins of all kinds parts of the tbl_sql object (like select clauses, where clauses etc).  and this way one could potentially avoid a lot of subqueries. 

Would be great to get your opinion before I put in the work

P.S. I already have "with" statements implemented. They work similar to collapse, and allows the factoring out of subqueries, which can be beneficial to performance (or so many websites claim). In any case - much easier to read.

**Comment by hadley** [comment]
This is slowly getting resolved through DBI: https://github.com/rstats-db/DBI/issues/24
