### ISSUE TITLE
Hybrid median() should return numeric

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2449]
https://github.com/hadley/dplyr/pull/2436#issuecomment-281115012

**Comment by hadley** [comment]
Do we actually have a hybrid handler for median?

**Comment by romainfrancois** [comment]
Nope. R is inconsistent here: 

```
> x <- 1:4
> str( median( 1:4 ) )
 num 2.5
> str( median( 1:3 ) )
 int 2
```

**Comment by hadley** [comment]
Ok, so this is not dplyr's fault, but base R's 😄 I was confused

**Comment by hadley** [comment]
@romainfrancois btw it's even worse than that: 

``` r
median(FALSE)
#> [1] FALSE
median(c(FALSE, TRUE))
#> [1] 0.5
```
