### ISSUE TITLE
summarise_at does not correctly process select_helpers

### ISSUE THREAD

**Issue by Feakster** [hadley/dplyr#2452]
I'm currently using an NHANES data cut I've made to develop a teaching unit for people to learn to use dplyr for data manipulation. While doing so, I've noticed that the select_helpers do not work correctly for the summarise_at() function. For instance, the commands below return a data frame containing the mean of all variables, as opposed to just those specified by "contains" and "starts_with" helpers:

```r
summarise_at(nhanes, contains("lbd"), funs(mean(., na.rm = TRUE)))
summarise_at(nhanes, starts_with("lbd"), funs(mean(., na.rm = TRUE)))
```

Whereas, what I want is akin to this, which does work, but is not as elegant:

```r
summarise_if(nhanes, grepl("lbd", names(nhanes)), funs(., na.rm = TRUE)))
```

Ben

**Comment by hadley** [comment]
You forgot the `vars()`

**Comment by hadley** [comment]
But needs a better error message

**Comment by Feakster** [comment]
Hi, I've been playing around with the `mutate_at()` and `summarise_at()` commands this morning. The help file for `summarise_all()` states that both `summarise_at()` and `mutate_at()` allow you to select variables using the same name-based `select_helpers` (presumably in place of `vars()` as an alternative means of specifying the variables you wish to summarise or mutate). However, neither command gives the anticipated behaviour.

Assuming I have a database called `nhanes`, consisting of mutiple numeric variables, two of which are called `lbd1` and `lbd2`, and in which no other variables names contain the substring `"lbd"`...

The following two `mutate_at()` commands would be expected to return the same result:

```r
mutate_at(nhanes, vars(lbd1, lbd2), funs(mean(., na.rm = TRUE)))
mutate_at(nhanes, contains("lbd"), funs(mean(., na.rm = TRUE)))
```

While the following two `summarise_at()` commands would be expected to return the same result:

```r
summarise_at(nhanes, vars(lbd1, lbd2), funs(mean(., na.rm = TRUE)))
summarise_at(nhanes, contains("lbd"), funs(mean(., na.rm = TRUE)))
```

However, in both cases the `select_helper` `contains()` does not limit the operation to the variables specified. I've noticed that this problem only seems to be present when specifying `.` within `funs()` in conjunction with `select_helpers`, (but not in conjunction with `vars()`).

i.e., both of these commands work identically, as anticipated:

```r
summarise_at(nhanes, vars(lbd1, lbd2), funs(mean))
summarise_at(nhanes, vars(lbd1, lbd2), funs(mean(.)))
```

... while only the first of these command works as anticipated:

```r
summarise_at(nhanes, contains("lbd"), funs(mean)) # Performs specified function on only vairable names containing "lbd"
summarise_at(nhanes, contains("lbd"), funs(mean(.))) # Performs specifed function on all variables!
```

Ben

**Comment by hadley** [comment]
If you want to use select select, you must use `vars()`.  Have at look at the examples.

**Comment by Feakster** [comment]
If this is the case... could someone please change the wording of the help file for `summarise_all()`. It currently states:

`summarise_at()` and `mutate_at()` allow you to select columns using the same name-based `select_helpers` as with `select()`.

Ben

**Comment by Feakster** [comment]
Ah... just realised that you need to use the `select_helpers` inside the `vars()` argument. Not instead of it.
