### ISSUE TITLE
log() in postgres gives a type error for doubles

### ISSUE THREAD

**Issue by karldw** [hadley/dplyr#2464]
Currently dplyr uses the two-argument `log(base, x)` form (see #2288), but this form raises a type error in postgres when `x` is a double.

```r
df <- data_frame(a = 1:5, b = a + 0.5)  # a is integer, b is double
df_postgres <- copy_to(src_postgres, df)
mutate(df_postgres, log_a = log(a))  # works because a is integer
mutate(df_postgres, log_b = ln(b))   # works because 'ln' gets passed through
mutate(df_postgres, log_b = log(b))  # error
```

Both [mysql](https://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html#function_log) and [postgres](https://www.postgresql.org/docs/current/static/functions-math.html#FUNCTIONS-MATH-FUNC-TABLE) have a `ln()` function, which would work for the default case of natural log.
In postgres, the two-argument form requires numeric or integer  `x` ('numeric' is postgres' arbitrary-precision type).  Additionally `log()` in postgres is base 10, but I don't think that matters here.

Proposal:
- if `base` is *e*, use `ln` in translate-sql-base.r
- Otherwise, calculate `log(x) / log(base)` for postgres, [like src-sqlite.r does](https://github.com/hadley/dplyr/commit/a6ea410ecced3f209a57a761077bcfdcb96364b3#diff-fcfefa82c4b028eeed00b6f149b3a6f1R163).

I can submit a pull request for this.

**Comment by hadley** [comment]
A PR sounds good
