### ISSUE TITLE
filter fails when checking matches with a list

### ISSUE THREAD

**Issue by rheitz1** [hadley/dplyr#2467]
---

dplyr::filter fails when there is a match between column names being compared and a list is being referenced directly via lapply.

```r
#I have a list of two data frames containing cars I wish to remove in two passes.
mtcars$carName = rownames(mtcars)

remove = list('Toyotas' = data.frame('carName' = grep('Toyota',mtcars$carName,value=TRUE)),
              'Mercedes' = data.frame('carName' = grep('Merc',mtcars$carName,value=TRUE)))

#If I invoke lapply on names(remove), the filtering fails:
results_bad = lapply(names(remove),function(y){
  mtcars %>% filter(!(carName %in% remove[[y]]$carName)) %>%
    select(carName)
})
names(results_bad) = names(remove)

#there was no filtering
grep('Toyota',results_bad[['Toyotas']]$carName,value=TRUE)
grep('Merc',results_bad[['Mercedes']]$carName,value=TRUE)



#If I invoke lapply on 'remove' directly, it works:
results_good = lapply(remove,function(y){
  mtcars %>% filter(!(carName %in% y$carName)) %>%
    select(carName)
})

#now the filtering works:
grep('Toyota',results_good[['Toyotas']]$carName,value=TRUE)
grep('Merc',results_good[['Mercedes']]$carName,value=TRUE)


#This is kind of a dangerous error because its hard to know that your filtering isn't working, since the #syntax is certainly correct. Strangely, if I were to rename the df columns such that there was no collision, #the filtering would work in either case.
```

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by dmontaner** [comment]
I am having a similar (or same) problem. filter seems to fail when using `%in%` followed by a vector contained in a list of lists or list of data frames. The funny thing is that it seems to be with the `$` operators. 

If I create a list with  a data frame inside

```
li <- list ()
li$df1 <- iris
```
Then I can run this with no problem: 

    iris %>% filter (Species %in% li[['df1']][,'Species'])

But I get an error if I use the `$` syntax:

    iris %>% filter (Species %in% li$df1$Species)

I am using "R version 3.3.2 (2016-10-31)" and dplyr version "0.5.0"

Thanks

**Comment by hadley** [comment]
Can you _please_ create a reprex that I can easily copy and paste into R?

**Comment by krlmlr** [comment]
I suspect that this is already resolved in the current development version. Could you please double-check?

**Comment by rheitz1** [comment]
Hadley, copy and paste this, then verify that there was no filtering.

mtcars$carName = rownames(mtcars)
remove = list('Toyotas' = data.frame('carName' = grep('Toyota',mtcars$carName,value=TRUE)),
              'Mercedes' = data.frame('carName' = grep('Merc',mtcars$carName,value=TRUE)))

results_bad = lapply(names(remove),function(y){
  mtcars %>% filter(!(carName %in% remove[[y]]$carName)) %>%
    select(carName)
})

**Comment by dmontaner** [comment]
Just copy this:

li <- list ()
li$df1 <- iris
iris %>% filter (Species %in% li[['df1']][,'Species']) %>% head
iris %>% filter (Species %in% li$df1$Species)

**Comment by hadley** [comment]
Works for me. I'm pretty sure this has been fixed in dev

**Comment by dmontaner** [comment]
I have just updated to dplyr version "0.5.0.9000" and now is working fine :) for me too...

Thank you!!!

**Comment by rheitz1** [comment]
I can confirm that the issue is corrected in the current dplyr dev version.
Thanks.
