### ISSUE TITLE
Generalize the limiting mechanism for sql queries?

### ISSUE THREAD

**Issue by shabbybanks** [hadley/dplyr#2470]
I am writing a `src_db2`. It turns out IBM's `db2` does not follow the semi-standard mechanism for limiting results via `LIMIT <n>`. Per [wikipedia on limiting clause](https://en.wikipedia.org/wiki/Select_(SQL)#Result_limits), `db2` is one of the oddballs, as are `MS SQL` and Oracle (hmmm, I can't see what's common among these three...). It would be easier on me, but possibly a hassle for you, if `sql_select.default` called an S3 method like `sql_limit` instead of hard-coding in the `build_sql("LIMIT ",` parts around [here](https://github.com/hadley/dplyr/blob/a35874a4f1c63de948744149d763c6828f145ed1/R/sql-generic.R#L75). Then one could simply overload `sql_limit.db2` as needed.

(I do not fully understand how the `compact` function is ordering the elements of `out` in `sql_select`, so it might be harder than just this, unfortunately.)
(And, again, I understand this is low priority and might just cause more potential harm than gain.)

**Comment by hadley** [comment]
I think for now, my policy is that you should just create your own `sql_select()` method. You can just copy and paste from `sql_select.default()` so it shouldn't be too much work.

**Comment by imanuelcostigan** [comment]
@shabbybanks the [RSQLServer](https://github.com/imanuelcostigan/RSQLServer) dplyr backend has implemented a SQL Server compliant TOP clause (package will be back on CRAN once dplyr update has been released in a few weeks)
