### ISSUE TITLE
Error installation dplyr on ubuntu g++ error 4 

### ISSUE THREAD

**Issue by echaintreau** [hadley/dplyr#2473]
Hi,

Impossible to install 'dplyr' standard CRAN package, it seem the g++ encounter an internal error, and I don't know what to do.

--- Config ----
 Ubuntu 14.04.5 LTS (GNU/Linux 4.4.15-1-pve x86_64)

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

--- R code ---

``` R
install.packages('dplyr')

```
--- Error Message ---
 ```bash
installing *source* package ‘dplyr’ ...
 package ‘dplyr’ successfully unpacked and MD5 sums checked
libs
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"  -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [RcppExports.o] Error 4
ERROR: compilation failed for package ‘dplyr’
removing ‘/home/User/R/x86_64-pc-linux-gnu-library/3.3/dplyr’

The downloaded source packages are in
        ‘/tmp/RtmpdEt1p2/downloaded_packages’
Warning message:
In install.packages("dplyr") :
  installation of package ‘dplyr’ had non-zero exit status
```
Thank by advance. Sincerely

**Comment by hadley** [comment]
GitHub issues use [markdown](https://guides.github.com/features/mastering-markdown/) and they're much easier to read if you learn a little bit about it. The most important thing is to put your R code inside a block that starts with ```` ```R ```` and ends with ```` ``` ````.

**Comment by echaintreau** [comment]
@hadley sure, but for one line don't know if really usefull here. Thanks for the tips

**Comment by hadley** [comment]
This looks like a g++ compiler error so there's nothing that I can do about it.  However, this is sometimes caused by not having enough memory, which is often seen when people try and compile dplyr on a really cheap AWS instance.

**Comment by echaintreau** [comment]
@hadley, Ok, I will look in that direction, thank you for giving me a clue, come back on it if I have some progress on my side.

**Comment by echaintreau** [comment]
# Last update and final close
@hadley **Thank you for your precious advice**, you were totally right, the compilation of dplyr could not be achive cause our RAM memory was too short. Just for info, for the current version of dplyr, **950Mo** of RAM memory are necessary (*1024 Mo if we include the swap memory*). After updating our memory, the package get installed normally.
Thanks again.
