### ISSUE TITLE
Can't use mutate on mutated columns for sql backends

### ISSUE THREAD

**Issue by javierluraschi** [hadley/dplyr#2481]
One can mutate correctly over a mutated column for data frames:

```
df <- data_frame(x = runif(100), y = runif(100))
df %>% mutate(x1 = x, x2 = x1)
```

However, for SQL backends, the following fails:

```
df <- memdb_frame(x = runif(100), y = runif(100))
df %>% mutate(x1 = x, x2 = x1)
```

```
Error in sqliteSendQuery(conn, statement) : 
  error in statement: no such column: x1
```

Related to: https://github.com/rstudio/sparklyr/pull/521

**Comment by hadley** [comment]
Is this something that people actually complained about?

**Comment by javierluraschi** [comment]
I found this myself and therefore, has never been reported by a user of `sparklyr`.

I don't think this feature is a must-have, but it would be nice for some cases. For instance:

```
df %>% transmute(cost = x, monthly = cost / 12, weekly = monthly / 4)
```

Rather than:

```
df %>% transmute(cost = x) %>% mutate(monthly = cost / 12) %>% mutate(weekly = monthly / 4)
```

**Comment by hadley** [comment]
Yeah, that's reasonable.  Should be fairly easy to fix by detecting when a new variable overwrites an existing variable.

**Comment by javierluraschi** [comment]
Sounds good, here is a PR: https://github.com/hadley/dplyr/pull/2483
