### ISSUE TITLE
Issue with do() method for grouped sqlite data + chunking

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#2482]
The `do()` sqlite method for grouped data has two issues:

- `do()` doesn't pass the `chunk_size` to the sql method correctly, since that goes through lazy dots. This is fixed in the tidyeval branch.

- This test fails (currently not triggered on master because of the issue above): https://github.com/hadley/dplyr/blob/8430adca4cc6488689fc08b0f8a40a88371fba2a/tests/testthat/test-do.R#L182

  Computation fails when some groups don't appear in the chunk.

**Comment by hadley** [comment]
Not sure why you were seeing the failure - it looks ok to me.
