### ISSUE TITLE
summarise_each mixing SE and NSE working partially

### ISSUE THREAD

**Issue by DasHammett** [hadley/dplyr#2485]
The following function that mixes SE and NSE in summarise_each is not giving correct results.

```
func <- function(param) {
  mtcars %>%
    group_by(cyl) %>%
    summarise_each(funs_(lazyeval::interp(~(sum(.)/sum(var > 1.5)), var = as.name(param))))
}
```
Below is the output of `func("wt")`
```
# A tibble: 3 × 11
    cyl      mpg     disp        hp     drat       wt   qsec    vs    am  gear  carb
  <dbl>    <dbl>    <dbl>     <dbl>    <dbl>    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
1     4 26.66364 105.1364  82.63636 4.070909 2.285727 210.51    10     8    45    17
2     6 19.74286 183.3143 122.28571 3.585714 3.117143 125.84     4     3    27    24
3     8 15.10000 353.1000 209.21429 3.229286 3.999214 234.81     0     2    46    49
```
Columns from `mpg` up to `wt` are calculated correctly. From `qsec` up to `carb`, function is not calculating correctly as it does not do the division in the function.

**Comment by lionel-** [comment]
That's because the computations are done lazily, and when the value of `wt` changes this is reflected in subsequent computations. The solution is to supply the _value_ of `wt` rather than its symbolic name. This will all be much easier to accomplish in next dplyr version.

**Comment by DasHammett** [comment]
Hi, 

Thank for the reply. Why would `sum(wt > 1.5)` change over the computation? Isn't that value static across the dataset?

I understand your reply if I were to supply only `wt`, but since I am supplying a count of `wt` that meets a criteria, that should not change, right? Also, why it suddenly is `sum(wt > 1.5)` is working for a group of columns and suddenly it becomes 1? If the issue is `wt`changing, shouldn't we see more changes?

Thank you

**Comment by lionel-** [comment]
The columns are changed sequentially by `mutate_each()`, and at some point `wt` is applied the normalisation as well. From then on, its value has changed. This is easier to see with a normal mutate:

```r
mutate(mtcars,
  foo = cyl * wt,
  wt = wt / 100,
  bar = cyl * wt
)
```

**Comment by lionel-** [comment]
@hadley could that be an example that where more pronouns would be useful? E.g. `.orig` would refer to the original dataset throughout the computation.

**Comment by hadley** [comment]
@lionel- I think more pronouns would be useful, but I don't think this is a case where it's that important.
