### ISSUE TITLE
Query optimiser commit breaks some downstream sql_select methods

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/dplyr#2492]
Per [commit discussion](https://github.com/hadley/dplyr/commit/ae202a14e76a86c8bd3cef58119f81b94395a70e#commitcomment-21151559), changes made to `sql_render.tbl_sql()` to optimise query production, breaks downstream `sql_select()` in some circumstances. 

This occurs because the `NextMethod(con = con)` call in `sql_render.tbl_sql()` passes the connection to `sql_render.tbl_lazy()` as part of the dots argument. Where `sql_select()` methods have more arguments than the default implementation, this connection is passed in to the first non-default argument and causes `sql_select()` methods to fail.

This occurs in RSQLServer. A reprex can be found here: https://github.com/imanuelcostigan/RSQLServer/issues/142#issuecomment-284188736

**Comment by imanuelcostigan** [comment]
Let me know if you would like me to submit a PR with different NextMethod call

**Comment by Hong-Revo** [comment]
In addition to those at [the commit](https://github.com/hadley/dplyr/commit/ae202a14e76a86c8bd3cef58119f81b94395a70e#commitcomment-21151559) and [RSQLServer](https://github.com/imanuelcostigan/RSQLServer/issues/142#issuecomment-284188736), here's a very simple reproducible example. You'll need a SQL Server instance for this.

```
library(dplyr)
db <- RSQLServer::src_sqlserver(<login details>)
tab <- tbl(db, <existing table>)
tab

#Error: length(order_by) not greater than 0L
```
Printing a tbl also prints the first few rows, which involves calling `collect` with the number of rows to get. `collect(*, n=n)` is one of the methods affected by this issue, hence the error.

**Comment by Hong-Revo** [comment]
And here's a simple demonstration of the NextMethod problem. I define a generic `f`, and methods for classes `foo` and `bar`. The `foo` method mimics the code in `sql_render.tbl_sql`.
``` r
f <- function(a, b, ...)
{
    UseMethod("f")
}

f.foo <- function(a, b=NULL, ...)
{
    cat("in f.foo\n")
    print(match.call())
    if(is.null(b)) b <- obj$b
    NextMethod(b=b)
}

f.bar <- function(a, b, c, ...)
{
    cat("in f.bar\n")
    print(match.call())
    NULL
}

obj <- structure(list(a=42, b=34), class=c("foo", "bar"))

f(obj, obj$b)

#in f.foo
#f.foo(a = obj, b = obj$b)
#in f.bar
#f.bar(a = obj, b = 34, c = obj$b)
#NULL
```

What's happening here is that the original call to `f` supplies _both_ `a` and `b`, as unnamed arguments. When this happens, `NextMethod(b=b)` adds another argument, this time named.

If instead, I were to do this:
``` r
f(obj)
#in f.foo
#f.foo(a = obj)
#in f.bar
#f.bar(a = obj, b = 34)
```
then it works as expected.

This is the same as what happens with dplyr tbls. The original call to `sql_render` specifies both `qry` and `con` as arguments, which are passed to `sql_render.tbl_sql`. This then calls `NextMethod(con=con)` which results in `con` being duplicated like `b` in the see above.

**Comment by imanuelcostigan** [comment]
@hadley can i get some clarity as to whether or not this issue will be tackled prior to the next release? I'd be a bit disappointed if we were unable to resubmit RSQLServer to CRAN after being unable to work around dplyr internal changes in the last major release. I am happy to submit a PR (and be guided on what i should look into) if necessary.

**Comment by hadley** [comment]
Yes, obviously it will get fixed.

**Comment by hadley** [comment]
Ugh, it's crazy that `NextMethod()` doesn't use `match.call()`
