### ISSUE TITLE
Suggestion: recode to accept named list

### ISSUE THREAD

**Issue by CG1122** [hadley/dplyr#2505]
It would be really convent if recode could accept a named list as an argument instead of having to specify each of the input parameters. 

Currently to use the function you have to do something like 

```r
x <- c( "a" , "b" , "c")
recode( x , a = "1" , b = "2" , c = "3") 
```

I propose that the following be valid 

```r
MAP <- list(
	a = "1" ,
	b = "2" ,
	c = "3"
)

recode( x , MAP )
```

This allows for standardized maps to be setup and used across a project which is useful when  you are dealing with short variable names or coded parameter terms which need to be transformed into more wordy labels later on.

**Comment by hadley** [comment]
Part of #2477

**Comment by ahcyip** [comment]
@hadley Has this been implemented? I've been trying to use named lists in dplyr::recode() but it doesn't seem to work. 
`x <- c("a", "b", "c")
  MAP <- list(a = "1", b = "2", c = "3")
  dplyr::recode(x, MAP)
#> Error: Argument 2 must be named, not unnamed`

**Comment by ahcyip** [comment]
Here is my left_join solution

``` r
  
  x <- c("a", "b", "c")
  MAP <- list(a = "1", b = "2", c = "3")
  dplyr::recode(x, MAP)
#> Error: Argument 2 must be named, not unnamed
  
  x_lj <- tibble::tibble(x = x)
  MAP_lj <- dplyr::bind_cols(x = names(MAP), y = as.character(MAP))
  dplyr::left_join(x_lj, MAP_lj, by = "x")
#> # A tibble: 3 x 2
#>       x     y
#>   <chr> <chr>
#> 1     a     1
#> 2     b     2
#> 3     c     3
```

**Comment by ahcyip** [comment]
I figured it out:
``` r
x <- c("a", "b", "c")
MAP <- list(a = "1", b = "2", c = "3")
dplyr::recode(x, !!!MAP)
#> [1] "1" "2" "3"
```

**Comment by billdenney** [comment]
I was about to suggest a `recode_` function that does what @ahcyip suggested.  Can that example or one largely similar be added to the documentation, please?
