### ISSUE TITLE
Feature Request: Make arrange NA handling more explicit

### ISSUE THREAD

**Issue by billdenney** [hadley/dplyr#2521]
Currently, arrange sorts `NA` to the end as it uses either xtfrm or something equivalent.  It would be beneficial to make `NA` handling more easily/explicitly controllable.  It is currently possible to handle NA sorting with the rank function:

```r
arrange(data.frame(a=c(2, NA, 1)), rank(a, na.last=TRUE))
arrange(data.frame(a=c(2, NA, 1)), rank(a, na.last=FALSE))
```

If that is the preferred solution (I think it is a reasonable), could something like that be added to the documentation.  (I would be happy to create a documentation patch for that.)  But I'm guessing that would not work well for database-backed queries (not something I deal with practically ever).

If there is another preferred solution, it would be good to have that documented.

**Comment by hadley** [comment]
If you want to be explicit about how NAs are sorted, just be explicit about it 😉 

```R
arrange(df, is.na(x), x)
```

**Comment by billdenney** [comment]
I like the `is.na` solution.  Thanks!

**Comment by zx8754** [comment]
@billdenney @hadley `is.na` solution wouldn't look pretty with multiple columns.
