### ISSUE TITLE
empty suffix in join causes infinite loop

### ISSUE THREAD

**Issue by dfrankow** [hadley/dplyr#2522]
If I join using one suffix empty, I get an infinite loop, with my CPU spinning at 100%.

```r
library(dplyr)

d1 = data.frame(f1=c('a','b','c'), f2=c(1,2,3))
d2 = data.frame(f1=c('a','d'), f2=c(4,5), f3=c(1.1, 2.2))

inner_join(d1, d2, by=c('f1'), suffix=c('', '.2'))
```

If I use merge, this works as expected.

```
merge(d1, d2, by=c('f1'), suffixes=c('', '.2'))
```

This is a common case for me, where I don't want to add a suffix to the original fields.

dplyr version 0.5.0, R version 3.3.2.

**Comment by krlmlr** [comment]
Thanks. This looks like #2228. Can you please try the development version?

**Comment by dfrankow** [comment]
I don't know how to try the dev branch without destroying my current install, but I believe you.

Thanks!
