### ISSUE TITLE
Support S3 objects with pull

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#2524]
The new `dplyr::pull` function in the next version does not work with S3 objects even though `[[` does. Maybe that is intended but it would be very convenient if `pull` can be used in other situations as well. I even think support for S4 objects would be great. Here is an example:
```r
# insert reprex here
library("dplyr")
library("lme4")
d <- tibble(y = rnorm(100), x = rnorm(100), j = rbinom(100, 1, 0.5))

# S3 object
m1 <- lm(y ~ x, data = d)
m1[["coefficients"]]
m1 %>% pull("coefficients")

# S4 object
m2 <- lmer(y ~ x + (1|j), data = d)
m2[["lower"]]
m2@lower
m2 %>% pull("lower")
```

**Comment by krlmlr** [comment]
@hadley: Do we support `pull()` for arbitrary objects or S4 objects, e.g., by adding a `pull.default()` implementation?

**Comment by hadley** [comment]
There is some similarity between `dplyr::pull()` and `purrr::extract()`. I am not sure whether we should attempt to combine them, or keep separate.  I'm currently leaning towards keeping separate.

**Comment by hadley** [comment]
I'm going to keep them separate for now.
