### ISSUE TITLE
between should be more surly when encountering bit64::integer64

### ISSUE THREAD

**Issue by HughParsonage** [hadley/dplyr#2529]
`between` appears to be providing the wrong result when `bit64` is mixed with integers.

The following should all be `TRUE`:

```r
library(bit64)

x <- 1870393418
y <- 9999999999

x < y
dplyr::between(x, 1, y)

dplyr::between(as.integer64(x), 1, y)
dplyr::between(as.integer64(x), 1, as.integer64(y))
dplyr::between(as.integer64(x), as.integer64(1), as.integer64(y))

data.table::between(as.integer64(x), 1, y)
data.table::between(as.integer64(x), 1, as.integer64(y))
data.table::between(as.integer64(x), as.integer64(1), as.integer64(y))
```

From browsing the closed issues with `bit64`, I see that `bit64` is not supported. I appreciate this; this issue is not to request that it be supported. I do think though that the function should error if it could give a wrong result. Even prohibiting `integer64` class objects from `dplyr::between` would be acceptable.

**Comment by hadley** [comment]
This is the fundamental drawback of the bit64 approach.

**Comment by krlmlr** [comment]
We could add a bit of error checking to `between()`, which is a C++ function exported to R straight away.

**Comment by hadley** [comment]
This is just a quick fix. A proper fix (i.e. with correct bit64 behaviour) needs to wait for vctrs.

**Comment by ecortens** [comment]
Just updated to the latest dplyr from github, and started seeing this warning. However, I wonder if this is the desired behaviour?

```
> between(as.Date('2017-05-05'), as.Date('2017-05-01'), as.Date('2017-05-10'))
[1] TRUE
Warning message:
between() called on numeric vector with S3 class 
```

I've been using `between()` on vectors with the `Date` class without trouble for quite some time, so I'm not sure that it needs to be the case that _all_ vectors with non-null classes need to trigger this warning? Maybe only in the bit64 situation referenced above...

**Comment by hadley** [comment]
See #2766
