### ISSUE TITLE
dplyr_0.5.0 - slice 

### ISSUE THREAD

**Issue by ronencozen** [hadley/dplyr#2531]
When running the following
```r
iris %>% 
  arrange(desc(Sepal.Length)) %>%
  group_by(Species) %>% 
  slice(1:5)
```
the below error pop up:

> Error  in UseMethod("slice") : 
  no applicable method for 'slice' applied to an object of class "c('grouped_df', 'tbl_df', 'tbl', 'data.frame')"

**Comment by JARS3N** [comment]
I'm unable to reproduce that error with the provided code snippet ,I suggest trying with a clean environment and determining if it is reproducible.

**Comment by ronencozen** [comment]
It's reproducible on a different machine.
