### ISSUE TITLE
mutate and filter drop subclasses

### ISSUE THREAD

**Issue by hughjonesd** [hadley/dplyr#2532]
`mutate` and `filter` remove subclasses from data frames. See also #1984, of which this is presumably a part. But not dropping classes seems important. Indeed, `?filter` and `?mutate` say they return "an object of the same class as `.data`".

 `select` works fine by the way.

```r
foo <- data.frame(a = 1:3, b = 1:3)
class(foo) <- c('bar', class(foo))

class(mutate(foo, a= a+1))
class(filter(foo, a < 3))
class(select(foo, a))
```

**Comment by hadley** [comment]
The current dplyr perspective is that we can't preserve attributes because we don't know if they're vectorised along rows or columns. It's up to individual subclasses to preserve. We may change this in the future, but we'll want to tackle globally, not just for a couple of verbs.

**Comment by vspinu** [comment]
From what I see `arrange` preserves attributes but not the class. The current situation is rather inconsistent. 

I think it makes more sense to leave it to the "subclass" developer to tackle potential inconsistencies introduced by dplyr verbs. Currently all subclassers have to suffer. If attributes were preserved, I bet, only a handful of subclassers would be affected.
