### ISSUE TITLE
[ works differently on tbl_df vs data.frame

### ISSUE THREAD

**Issue by AjarKeen** [hadley/dplyr#2540]
Base subsetting on a `tbl_df` doesn't return a vector if you only selected one column:

``` r
library(dplyr)

f <- data.frame(a = rnorm(10))

dim(f[, 'a'])
#> NULL

dim(as.tbl(f)[, 'a'])
#> [1] 10  1
```

This has downstream effects that are difficult to debug -- for instance:

``` r
library(zoo)
library(dplyr)

f <- data.frame(a = rnorm(10), rep(NA, 10), rnorm(10),
                b = rnorm(5), rep(NA, 20), rnorm(5))

# choose 2 columns and it works fine:
class(na.approx(f[, c('a', 'b')]))
#> [1] "matrix"

class(na.approx(as.tbl(f)[, c('a', 'b')]))
#> [1] "matrix"

# choose 1 column and it doesn't:
class(na.approx(f[, 'a']))
#> [1] "numeric"

class(na.approx(as.tbl(f)[, 'a']))
#> [1] "matrix"
```

This has popped up for me a couple of times, and led me to start wrapping my function returns in  `as.data.frame()` if I would have returned a `tbl_df`. I think `tbl_df` is intended to be a seamless wrapper for `data.frame`, though, so it should probably strive to behave similarly in all cases.

**Comment by hadley** [comment]
This is a deliberate choice. See tibble docs for why.
