### ISSUE TITLE
Error in select_vars(names(.data), ...)  could not find function tidy_quotes

### ISSUE THREAD

**Issue by rontomer** [hadley/dplyr#2550]
Hi

Starting 6 hours ago, I am getting this strange error when using dplyr package.
My current dplyr version is 0.5.0.9000
When using version 0.5.0, it seems to be ok

`
library(dplyr);
df<-data.frame(x=1:10,y=1:10);
df %>% select(x)
`

And this is the output

> Error in select_vars(names(.data), ...) :
  could not find function "tidy_quotes"

Any idea what's wrong?

Thanks
Tomer

**Comment by krlmlr** [comment]
This was a transitional period. Can you please reinstall dplyr again? The rlang should be updated in this process, too.

**Comment by rontomer** [comment]
I did it.
Seems to be working again.
Thanks.
