### ISSUE TITLE
Wrong column selection in mutate_if 

### ISSUE THREAD

**Issue by stefanfritsch** [hadley/dplyr#2561]
Hi,

if you use `mutate_if` (or `mutate_at`) and reference a fixed column in `funs()` then the column selection goes haywire:

MWE
-----------

```r
A <- data.frame(x = 1:10, y = 10:1, z = 21:30, a = 30:21)

mutate_if(A, is.numeric, funs(. / z))
```

What I expect
----------------

All columns are divided by the value in `z`.

What I get
-------------

Only columns `x` and `y` are modified, `a` isn't. This seems to be because `a` comes after `z` in the table. Replace `funs(./z)` with `funs(. / y)` to see the effect.

**Comment by hadley** [comment]
Yes because it's translated to

```
mutate(df, z = z / z, a = a / z)
```

**Comment by stefanfritsch** [comment]
Hi,

1. That's not correct as `a` is not modified as the MWE should show you. Only x, y and z are divided by z.
2. I fail to see how your answer answers my issue.

Regards,
Stefan

**Comment by hadley** [comment]
Because after `z = z / z`, z is 1.

**Comment by stefanfritsch** [comment]
Ah, that makes sense. Thanks a lot
