### ISSUE TITLE
dplyr crash with R 3.3.3

### ISSUE THREAD

**Issue by mjpdenver** [hadley/dplyr#2573]
I just started using updated versions of R and Rstudio yesterday and have been getting frequent crashes with summarise. The following examples cited earlier in issue #1835  causes a crash on R version 3.3.3 both within Rstudio Version 1.0.103 running R  in terminal.

Rstudio Version 99.903  running R 3.2.5  produces the correct behavior which I believe is 
Error: unused argument (na.rm = TRUE)

```r
library(dplyr)

tst <- data.frame(
grp = c(rep("A", 16), rep("B", 16), rep("C", 16)),
x = rnorm(163),
y = rnorm(163)
)
tst %>%
mutate(corr = cor(x, y, na.rm = TRUE))

### the following causes a crash on R 3.3.3 but not earlier version

arrange(mtcars, is.na(mtcars))

```

**Comment by hadley** [comment]
This is probably because you have an incompatible version of dplyr and Rcpp installed. Try re-installing both. (The dev version has a check to hopefully make this more obvious).
