### ISSUE TITLE
Mutate return length where statistics are inside ifelse conditionals

### ISSUE THREAD

**Issue by jpryda** [hadley/dplyr#2575]
---

In order to set the values of a particular group to NA based on a conditional, one must pre-compute and assign the summation to a new field, like so:

```r
group_by(clinic, measure, month) %>%
mutate(pre_value_sum = sum(value),
           value = ifelse(pre_value_sum < min_score_denominator, NA, value)) %>%
select(-pre_value_sum)
```

I would expect the following code to work, however value[1] is returned for *all* rows instead of the *original* vector of values.

```r
group_by(clinic, measure, month) %>%
mutate(value = ifelse(sum(value) < min_score_denominator, NA, value))
```

**Comment by hadley** [comment]
Please provide a reproducible example (as was requested in the instructions that you deleted 😥)

**Comment by jpryda** [comment]
```r
data.frame(clinic = rep(1,6),
           measure = rep('Mq1002', 6),
           month = as.Date('2017-01-01'),
           counts = c('a','b','c','d','e','f'),
           value = sample(c(56, 32, 43, 58, 12, 6))) %>%
    group_by(clinic, measure, month) %>%
    mutate(value2 = ifelse(sum(value) < 10, NA, value),
           pre_value_sum = sum(value),
           value3 = ifelse(pre_value_sum < 10, NA, value))
```

I would have expected the assignment of value2 to be equivalent to value3.

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by jpryda** [comment]
Baby steps, ha, ok.  Updated above.  I have left value2 and value3 separated as the two different methods that I would have expected to yield the same as the original value column.

**Comment by hadley** [comment]
Even simpler, but still the same problem I think:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = c(1:5)
) 

df %>% mutate(x1 = ifelse(FALSE, NA, x))
#> # A tibble: 5 × 2
#>       x    x1
#>   <int> <int>
#> 1     1     1
#> 2     2     1
#> 3     3     1
#> 4     4     1
#> 5     5     1
```

**Comment by jpryda** [comment]
True but note the following does work:

``` r
df %>% mutate(x1 = ifelse(FALSE, NA, x),
              x2 = ifelse(x==7, NA, x))

# A tibble: 5 × 3
#      x    x1    x2
#  <int> <int> <int>
#1     1     1     1
#2     2     1     2
#3     3     1     3
#4     4     1     4
#5     5     1     5

**Comment by hadley** [comment]
@krlmlr this looks like a hybrid evaluator bug to me. Can you please take a look?

**Comment by krlmlr** [comment]
I was stunned to see:

``` r
ifelse(FALSE, NA, 1:5)
#> [1] 1
```

**Comment by hadley** [comment]
Oh of course, `ifelse()` is vectorised according the length of the condition.

And in fact this isn't actually a case where you should use `ifelse`, but instead should use `if`

```R
data.frame(clinic = rep(1, 6),
           value = c(56, 32, 43, 58, 12, 6)) %>%
group_by(clinic) %>%
mutate(value2 = if(sum(value) < 10) NA else value)
```
