### ISSUE TITLE
mutate column in place documentation

### ISSUE THREAD

**Issue by pgensler** [hadley/dplyr#2582]
Is it possible to add some documentation to the mutate function with a MWE that shows how one can mutate a column in place? As an example:

Replacing all cars with 3rd gear with 8 in place. Currently the documentation does not make it seem like mutate is intended to modify a column in-place, and this example is overwriting the object in place.

from ?mutate : 

Adds new variables
>Mutate adds new variables and preserves existing; transmute drops existing variables.

Maybe adding that it can also mutate a variable in-place as well?

Simple example:
mtcars <- mtcars %>%
  mutate(gear = str_replace(gear, "3", "8"))

**Comment by hadley** [comment]
That's the job of `if_else()`.  I'm not quite sure what you're getting at

**Comment by iangow** [comment]
Here's the `if_else` version @hadley probably has in mind:

``` r
library(dplyr, warn.conflicts = FALSE)
mtcars <-  tbl_df(mtcars)
    
mtcars
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#> *  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1   21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
#> 2   21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
#> 3   22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
#> 4   21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
#> 5   18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
#> 6   18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
#> 7   14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
#> 8   24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
#> 9   22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
#> # ... with 22 more rows

mtcars %>%
    mutate(gear = if_else(gear == 3, 8, gear)) 
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1   21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
#> 2   21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
#> 3   22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
#> 4   21.4     6 258.0   110  3.08 3.215 19.44     1     0     8     1
#> 5   18.7     8 360.0   175  3.15 3.440 17.02     0     0     8     2
#> 6   18.1     6 225.0   105  2.76 3.460 20.22     1     0     8     1
#> 7   14.3     8 360.0   245  3.21 3.570 15.84     0     0     8     4
#> 8   24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
#> 9   22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
#> # ... with 22 more rows
```

I suspect the request may simply be to amend the documentation slightly:

> Mutate adds new variables and preserves existing; transmute drops existing variables. Mutate can also be used to alter the values of existing variables. 

Here an example might help (the OP's example is a little lacking in that replacing good data with bad seems to be a strange thing to do).

**Comment by hadley** [comment]
Also to be super pedantic, you're not exactly altering an existing variable so much as replacing it with a new vector that contains different values.

**Comment by pgensler** [comment]
@hadley  You are definitely correct, but I agree with @iangow that an example like this more clearly illustrates my use case, doing simple data munging on a particular column: 

At some point though, you do need to reassign the results back to the object by overwriting it.

test <- data.frame(
  aroma = c("5/10", "2/10", "3/10"),
  taste = c("2/20", "5/20", "15/20"),
  stringsAsFactors = FALSE)
str(test)
df <- df %>%
  mutate(review_aroma =  str_replace_all(review_aroma, "/5", ""))

You could use case_when or if_else to accomplish this, but to me, this seems like a natural fit for mutate. Thoughts? Is this a bad use case of mutate?

**Comment by iangow** [comment]
Your example doesn't work as is.

``` r
library(dplyr, warn.conflicts = FALSE)
library(stringr)

test <- data_frame(
    aroma = c("5/10", "2/10", "3/10"),
    taste = c("2/20", "5/20", "15/20"))
test
#> # A tibble: 3 × 2
#>   aroma taste
#>   <chr> <chr>
#> 1  5/10  2/20
#> 2  2/10  5/20
#> 3  3/10 15/20
test %>%
    mutate(aroma = as.integer(str_replace_all(aroma, "/10", "")))
#> # A tibble: 3 × 2
#>   aroma taste
#>   <int> <chr>
#> 1     5  2/20
#> 2     2  5/20
#> 3     3 15/20
```

**Comment by pgensler** [comment]
@iangow  Sorry about that, I have updated the code. It should work now.

**Comment by iangow** [comment]
It won't quite work *as is*.

1. Install `reprex` package in R (if necessary). This package appears to be the standard for reprexes here. (I learnt about it yesterday.)
2. Copy your code to clipboard.
3. Type `reprex::reprex()`. This will run code on clipboard and put nicely formatted output on clipboard.

Doing those steps, here's what I get with your code:

``` r
test <- data.frame(
aroma = c("5/10", "2/10", "3/10"),
taste = c("2/20", "5/20", "15/20"),
stringsAsFactors = FALSE)
str(test)
#> 'data.frame':    3 obs. of  2 variables:
#>  $ aroma: chr  "5/10" "2/10" "3/10"
#>  $ taste: chr  "2/20" "5/20" "15/20"
test <- test %>%
mutate(aroma = str_replace_all(aroma, "/10", ""))
#> Error in eval(expr, envir, enclos): could not find function "%>%"
```

**Comment by pgensler** [comment]
This is my reprex results, which is what I expected:
```
test <- data.frame(
  aroma = c("5/10", "2/10", "3/10"),
  taste = c("2/20", "5/20", "15/20"),
  stringsAsFactors = FALSE)
str(test)
#> 'data.frame':    3 obs. of  2 variables:
#>  $ aroma: chr  "5/10" "2/10" "3/10"
#>  $ taste: chr  "2/20" "5/20" "15/20"

library("magrittr")
library("stringr")
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

test <- test %>%
  mutate(aroma =  str_replace_all(aroma, "/10", ""))
glimpse(test)
#> Observations: 3
#> Variables: 2
#> $ aroma <chr> "5", "2", "3"
#> $ taste <chr> "2/20", "5/20", "15/20"
```

**Comment by pgensler** [comment]
To make this complete, add the following line  at the end of the pipe to convert the character column to integer. I've updated my code to include this. I do think the clarification in the documentation would help though.
transform(aroma = as.integer(aroma))

**Comment by iangow** [comment]
> transform(aroma = as.integer(aroma))

Ick. I think you want to `mutate(aroma = as.integer(aroma))` to keep within the set of `dplyr` verbs for  `dplyr` documentation. ;-)

Also `data_frame` (reported by `dplyr`) might be considered superior to `data.frame` in the same context.

**Comment by hadley** [comment]
@iangow `data_frame()` is deprecated; you should be using `tibble()` now

**Comment by pgensler** [comment]
@iangow Yes, you are definitely correct.
Building on that, I do think that simple examples like this illustrate the power of mutate_if very well to correct column classes that get imported bad for whatever reason:

``` r
pacman::p_load("lubridate", "dplyr", "magrittr")
test <- data.frame(
  aroma = c("5/10", "2/10", "3/10"),
  taste = c("2/20", "5/20", "15/20"),
  orderdt  = structure(c(1343692800, 1360022400,1381968000), class = c("POSIXct", "POSIXt"), tzone = "UTC"),
  stringsAsFactors = FALSE)

str(test)
#> 'data.frame':    3 obs. of  3 variables:
#>  $ aroma  : chr  "5/10" "2/10" "3/10"
#>  $ taste  : chr  "2/20" "5/20" "15/20"
#>  $ orderdt: POSIXct, format: "2012-07-31" "2013-02-05" ...
test <- test %>% mutate_if(is.POSIXt, as.Date)
glimpse(test)
#> Observations: 3
#> Variables: 3
#> $ aroma   <chr> "5/10", "2/10", "3/10"
#> $ taste   <chr> "2/20", "5/20", "15/20"
#> $ orderdt <date> 2012-07-31, 2013-02-05, 2013-10-17
```

**Comment by glennlawyer** [comment]
Just starting to play with dplyr, after a few years off from R programming (but about 15 years prior history with the language), and need to modify a column in place. The docs are not clear on how to do this.

@iangow's suggestion, to simply update the docs to read
```
Mutate adds new variables and preserves existing; transmute drops existing variables. Mutate can also be used to alter the values of existing variables.
``` 
would be super helpful (though see my final comment), as the wording of the current docs
```
Mutate adds new variables and preserves existing; transmute drops existing variables.
```
do not suggest modifying in place (hence this issue thread)

I am surprised that changing in place is
```
That's the job of if_else(). I'm not quite sure what you're getting at
```
as this seems very against the spirit of Tidyverse.

If `Mutate` leaves the original and creates a new variable, then `Mutate` should NEVER be able to modify a column in place. Because if you modify in place, you are not leaving the original. 
Only `Transmutate` should be able to do this.

Thus while modifying the docs to read (@iangow)
```
Mutate adds new variables and preserves existing; transmute drops existing variables. Mutate can also be used to alter the values of existing variables.
``` 
would solve the immediate issue, there seems an underlying inconsistency.
