### ISSUE TITLE
Fix NZ spelling of preceding

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#2586]
See [here](https://github.com/hadley/dplyr/search?utf8=✓&q=preceeding&type=), where it is spelled "preceeding".

**Comment by hadley** [comment]
That's not the NZ spelling :/

**Comment by iangow** [comment]
Clicking [link](https://github.com/hadley/dplyr/search?utf8=✓&q=preceeding&type=) above suggests  one NZ spelling case remains.

This is in the context of looking at the *window function* vignette. While this obviously isn't the right place for the following, these are just loose musings at this point.

While to implement rolling windows, one can always switch to SQL, a challenge is that it's difficult to do so in pieces. For example, if I've laboured to create a server-side `df` using `dplyr`, I can't (easily) switch to SQL to add a few window functions. (I think the best one could do would be to `compute` the table, give it a name, then do some SQL [`CREATE TEMPORARY TABLE df2 ...`], then return to `dplyr` verbs applied to `df2`.)

I wish I knew enough (and had the time) to work out a way of implementing more general windows (starting with PostgreSQL as the backend with the strongest support for them). But, given the limited vocabulary of windows, it seems like it would not be too difficult:

**Possible translations:**

`PARTITION BY a, b`: `group_by(a, b)` or `partition_by(a, b)` or `group_by = c("a", "b")`. Not sure whether using existing verb helps or hurts.
`ORDER BY x, y DESC`: `arrange(x, desc(y))` or `order_by(x, y)`. Not sure whether using existing verb helps or hurts.
`ROWS BETWEEN frame_start AND frame_end`: `from = frame_start, to = frame_end`
`UNBOUNDED PRECEDING`: `preceding(Inf)`
`value PRECEDING`: `preceding(2L)` for `value` equal to 2.
`CURRENT ROW`: `current_row()`
`value FOLLOWING`: `following(3L)` for `value` equal to 3.
`UNBOUNDED FOLLOWING`: `following(Inf)`.

**Fantasy pseudo-`dplyr` code:**

```r
df %>%
    select(gvkey, datadate, ni) %>%
    add_window(name = "w", group_by = "gvkey", arrange = "datadate",
               from = preceding(1L), to = current_row()) %>%
    mutate(ni_sum = sum(ni, window = "w"))
```
could translate to:

```
SELECT gvkey, datadate, ni, 
    sum(ni) OVER w AS ni_sum
FROM df
WINDOW w AS (PARTITION BY gvkey ORDER BY datadate ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)
```

PostgreSQL offers both `ROW` and `RANGE` modes. But  `ROW` mode seems simpler and the one to focus on.

While having something backend-specific seems to defeat the point of `dplyr`, it might be that something PostgreSQL-specific would offer a chance to figure out the grammar of windows at low cost before implementing something more general at some point in the future. 

If this is not to be classified as "completely out of the question", perhaps I could write up something more substantial and create an issue for it. I think I could program a pretty kludgey `add_window` function that might provide a starting point.

**Comment by hadley** [comment]
I think a better angle of attack would be a vector function with similar arguments to `win_over()` (but translated automatically, not manually)

**Comment by hadley** [comment]
It would be pretty easy to make this work:

```R
df %>%
  select(gvkey, datadate, ni) %>%
  mutate(
    ni_sum = over(
      sum(ni), 
      partition = gvkey, 
      order = datadate, 
      range = c(-1, 0)
    )
  )
```

**Comment by iangow** [comment]
What about something like this?

```r
df %>%
  select(gvkey, datadate, ni, sale, cogs, sga) %>%
  over(
      partition = gvkey, 
      order = datadate, 
      range = c(-3, 0)) %>%
  mutate(
    sale_ttm = sum(sale),
    cogs_ttm = sum(cogs),
    sga_ttm = sum(sga)
  )
```

This looks a little more like `group_by` (which seems to be a benefit in its own right) and allows one to calculate multiple variables in one pass through the data. (In this [hypothetical] case, I'm imagining summing over quarterly financial results to get "trailing twelve-month" figures.) *That* would be awesome.

(The next item on the wish list might allow for multiple windows [e.g., last twelve months, last 24 months], but I can see the additional syntactic complexity that would entail for relatively modest efficiency gains in a relative obscure use case.)

**Comment by hadley** [comment]
If we kept it scoped to individual vectors, it would take ~15 minutes to implement. Adding a new top-level `over()` would be a lot more work, and probably never get far enough up my to do list that I actually do it.

**Comment by iangow** [comment]
OK. Let me main a clean issue for you for the individual-vector case. 

Any issue for a top-level `over` could build on that later on. Maybe one day you will get enough help to work on it (I lack the skills to offer much myself).

A couple of notes

1. One gotcha to watch out for is that (with SQL sources at least). The windowing will override any `arrange` calls preceding it.
2. There seems to be "syntactic sugar" version of the top-level `over` that could be implemented using the individual-vector version (though even I can see issues with this, such as the scope of the `over` if there are multiple `mutate` calls following). 

Specifically, 

```r
df %>%
  select(gvkey, datadate, ni, sale, cogs, sga) %>%
  over(
      partition = gvkey, 
      order = datadate, 
      range = c(-3, 0)) %>%
  mutate(
    sale_ttm = sum(sale),
    cogs_ttm = sum(cogs),
    sga_ttm = sum(sga)
  )
```

could be implemented *by the user* as:

```r
df %>%
  select(gvkey, datadate, ni, sale, cogs, sga) %>%
  mutate(
    sale_ttm = over(sum(sale),
      partition = gvkey, 
      order = datadate, 
      range = c(-3, 0)),
    cogs_ttm = over(sum(cogs),
      partition = gvkey, 
      order = datadate, 
      range = c(-3, 0)),
    sga_ttm = over(sum(sga),
      partition = gvkey, 
      order = datadate, 
      range = c(-3, 0))
  )
```

**Comment by hadley** [comment]
`over()` could inherit the grouping and ordering implied by `group_by()` and `arrange()` so you'd only need:

```R
df %>%
  select(gvkey, datadate, ni, sale, cogs, sga) %>%
  group_by(gvgkey) %>%
  arrange(datadate) %>%
  mutate(
    sale_ttm = over(sum(sale), range = c(-3, 0)),
    cogs_ttm = over(sum(cogs), range = c(-3, 0)),
    sga_ttm = over(sum(sga), range = c(-3, 0))
  )
```
