### ISSUE TITLE
Data shifting between groups when summarizing ordered factors

### ISSUE THREAD

**Issue by alistaire47** [hadley/dplyr#2588]
I came across an odd bug: when summarizing ordered factors, the results are _sometimes_ shifted up to the top, moving any `NA`s to the bottom. Reprex:

``` r
library(dplyr)

df <- data_frame(x = gl(3, 2), 
                 y = ordered(c(NA, NA, NA, 'a', 'b', 'c'))) 

df
#> # A tibble: 6 × 2
#>        x     y
#>   <fctr> <ord>
#> 1      1    NA
#> 2      1    NA
#> 3      2    NA
#> 4      2     a
#> 5      3     b
#> 6      3     c

# shifted up
df %>% group_by(x) %>% summarise(y = y[1])    # same with y[[1]]
#> # A tibble: 3 × 2
#>        x     y
#>   <fctr> <ord>
#> 1      1     b
#> 2      2    NA
#> 3      3    NA

# works fine
df %>% group_by(x) %>% summarise(y = first(y))
#> # A tibble: 3 × 2
#>        x     y
#>   <fctr> <ord>
#> 1      1    NA
#> 2      2    NA
#> 3      3     b

# shifted
df %>% group_by(x) %>% summarise(y = min(y))
#> # A tibble: 3 × 2
#>        x     y
#>   <fctr> <ord>
#> 1      1     b
#> 2      2    NA
#> 3      3    NA
```

I have no idea why there's a difference between the `y[1]` and `first(y)` in particular. If `addNA` is called on `y`, all work properly (though the results change for `min`, as it ignored the `NA` instead of following `na.rm = FALSE`, but that's a base R inconsistency). I'm not wholly sure how ordered factors are stored in R, particularly whether `NA` is a level, which is not displayed in printing, `str`, `summary`, or `levels`, and can't find any documentation, but I suspect it's related.

This is on the newest devel versions of dplyr and rlang.

**Comment by hadley** [comment]
Slightly more minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(
  x = c(1, 1, 2, 2, 3, 3),
  y = factor(c(NA, NA, NA, 2, 3, 3))
) 

# NOT OK
df %>% group_by(x) %>% summarise(y = y[1])
#> # A tibble: 3 × 2
#>       x      y
#>   <dbl> <fctr>
#> 1     1      3
#> 2     2     NA
#> 3     3     NA
# OK
df %>% group_by(x) %>% summarise(y = first(y))
#> # A tibble: 3 × 2
#>       x      y
#>   <dbl> <fctr>
#> 1     1     NA
#> 2     2     NA
#> 3     3      3
```

@krlmlr can you please take a look?

**Comment by krlmlr** [comment]
Bisection says c3a2e49b is the offender. Need to look more closely.
