### ISSUE TITLE
mutate creates attribute when used with a tbl

### ISSUE THREAD

**Issue by tklebel** [hadley/dplyr#2612]
For some reason, mutate is creating an attribute when used in conjunction with a `tbl`: 

```r
library(dplyr, warn.conflicts = FALSE)
data_frame(a = "a") %>% 
  mutate(test = 1) %>%
  str()
#> Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
#>  $ a   : chr "a"
#>  $ test: num 1
#>  - attr(*, "vars")= chr 
```

**Comment by hadley** [comment]
In the future, please use the reprex package, and there's no need to include a correct case when the current behaviour is clearly wrong.
