### ISSUE TITLE
Join function assigning "" as a suffix causes R to crash

### ISSUE THREAD

**Issue by albit3** [hadley/dplyr#2615]
I encounter the following problem while using the left_join function.

Join function assigning "" as the suffix for variables in the first dataset causes R crash. 

 data1 <- left_join(t1, t0, by=c("dep_time"), match="all",suffix = c("","a")) 

Thanks,

Albit

**Comment by hadley** [comment]
Already fixed in dev version

**Comment by albit3** [comment]
Thank you Mr. Wickham.

On Apr 3, 2017, at 7:07 PM, Hadley Wickham <notifications@github.com<mailto:notifications@github.com>> wrote:


Already fixed in dev version
