### ISSUE TITLE
More pronouns

### ISSUE THREAD

**Issue by jimhester** [hadley/dplyr#415]
It would be handy to be able to access what variables are being used as grouping variables from within the execution environment of the do function.  My main use case would be to use to filter out these grouping columns and applying a function to the non-grouping columns.

If you are looking at a grouped tbl you can get this information with `groups`, however this does not work from within a `do` (groups just returns `NULL` in this case).
```
cars_df = tbl_df(mtcars) %>% group_by(cyl, gear)
groups(cars_df)
# [[1]]
# cyl
# [[2]]
# gear

do(cars_df, val=groups(.))$val[1:3]
# [[1]]
# NULL
# 
# [[2]]
# NULL
# 
# [[3]]
# NULL
```

**Comment by hadley** [comment]
I think this is no longer relevant post `tidyr::nest()` + purrr
