### ISSUE TITLE
[FR] mdply equivalent

### ISSUE THREAD

**Issue by baptiste** [hadley/dplyr#441]
It would be great if dplyr had a function similar to mapply, or better yet, mdply. It's just so useful, and clashes between dplyr and plyr mean that we can't use both.

Minimal example,

```
require(plyr)
p = expand.grid(mean=1:5, sd=seq(0, 1, length=10))
mdply(p, rnorm, n=5)
```

**Comment by hadley** [comment]
This now feels more like a job for purrr.
