### ISSUE TITLE
SQL error, when the right hand side of %in% is of length one in filter

### ISSUE THREAD

**Issue by vzemlys** [hadley/dplyr#511]
When filtering the table from the database the error is produced if `%in%` is used and the right hand side fo it is of length one:

```
library(dplyr)
library(DBI)
library(RSQLite)
library(RPostgreSQL)
library(RMySQL)
library(magrittr)

dt <- expand.grid(Year=as.integer(1990:2014),Product=LETTERS[1:8],Country=paste0(LETTERS,"I")) %>% select(Product,Country,Year)
dt$value <- rnorm(nrow(dt))

dt <- dt %>% group_by(Product) %>% mutate(value=value+as.numeric(Product)/10)
dt <- dt %>% group_by(Country) %>% mutate(value=value+as.numeric(Country)/10)
driver = dbDriver("SQLite")
con = dbConnect(driver, dbname = "test.db")
dbWriteTable(con, c("dummy_test"), value=dt %>% data.frame,overwrite=TRUE,row.names=FALSE)
dbDisconnect(con)

my_db <- src_sqlite("test.db")
print(my_db)
dbdt <- tbl(my_db,"dummy_test")

##test1
dbdt %>% filter(Product %in% "A" & Country %in% "AI" & Year %in% 1990 )
##test2
dbdt %>% filter(Product == "A" & Country == "AI" & Year == 1990 )
##test3
dbdt %>% filter(Product %in% c("A", "B") & Country %in% c("AI", "AJ") & Year %in% c(1990, 1991) )


```

The `test1` produces error, while the `test2` and `test3` pass without the problem. In R `test1` and `test2` should produce identical results. The same error is given with PostgreSQL and MySQL databases. Here is my sessionInfo:

```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.0.1  RPostgreSQL_0.4 RSQLite_0.11.4  dplyr_0.2      
[5] RMySQL_0.9-3    DBI_0.2-7      

loaded via a namespace (and not attached):
[1] assertthat_0.1 compiler_3.1.1 parallel_3.1.1 Rcpp_0.11.2    tools_3.1.1   
```

**Comment by zozlak** [comment]
In the current version of dplyr (0.4.1) a `x %in% c(1)` workaround does not work anymore:
```r
translate_sql(x %in% c(1))
# <SQL> "x" IN 1.0
```

This makes impossible to use the %in% operator during non-interactive programming without using some ugly hacks like:
```r
foo = function(tbl, valuesVector){
  valuesVector = rep(valuesVector, 2)
  tbl %>% filter_(~column %in% valuesVector)
}
```

Maybe a sollution will be to adjust the default behaviour of the `dplyr::sql_vector()`, so it will add parens on default. Such modyfication provides a valid SQL translations for cases like:
```r
translate_sql(x %in% 1)
# <SQL> "x" IN (1.0)
translate_sql(x %in% 1:2)
# <SQL> "x" IN (1, 2)
translate_sql(x + 1)
# <SQL> "x" + (1.0)
```

**Comment by wsurles** [comment]
Same issue here. I have a dynamic query to create the list of values for the %in% statement. It will sometimes have one date and sometimes more. We used a similar workaround but this is pretty hacky.
```s
weeks <- c(df$week_start,as.Date('1990-01-01'))

df2 <- tbl(my_db, "my_table") %>%
filter(week_start %in% weeks) %>%
collect()
```
The second date is something we know will not be in the column. We have to add this so the parens show up correctly.

Would love to see this fixed in the nearish future.

**Comment by joranE** [comment]
I have also just been stopped short by this bug. `x == 1` is not a solution when building queries programmatically, and the `x %in% c(1)` hack doesn't work anymore. I would love for this to see a higher priority.

**Comment by hadley** [comment]
@joranE are you sure you can't add the parens yourself? `x %in% (c(1))`

**Comment by joranE** [comment]
_Pretty_ sure...when I do that, if the vector is longer than one element it duplicates the parens and gives me a SQL syntax error. For example, `x %in% (c(1,2,))` yields `"x" IN ((1.0, 2.0))`.

**Comment by finity84** [comment]
I have the same behavior using 0.4.1, adding the parens duplicates it for multiple elements.

**Comment by voxnonecho** [comment]
Reference for workaround in a ShinyApp:

http://stackoverflow.com/questions/37591084/multiple-selectinput-values-create-unexpected-dplyr-postgres-behavior

**Comment by krlmlr** [comment]
Still seeing this in current master.

**Comment by noamross** [comment]
I note that one also gets an error due to incorrect translation when the right-hand side of `%in%` resolves to a zero-length vector:

```
> dplyr::translate_sql(filter(x, test_id %in% integer(0)))
<SQL> FILTER("x", "test_id" IN INTEGER(0.0))
```
