### ISSUE TITLE
equivalent of pig's ILLUSTRATE

### ISSUE THREAD

**Issue by jhofman** [hadley/dplyr#549]
pig has a great command called ILLUSTRATE that demonstrates how a sample of data will be transformed through a series of commands. it's very useful for debugging, and a great educational tool to generate example data transformations.

needless to say, it'd be awesome if dplyr had a similar function.

more info here:

http://pig.apache.org/docs/r0.7.0/piglatin_ref2.html#ILLUSTRATE
http://wiki.apache.org/pig/PigIllustrate

**Comment by datalove** [comment]
I could see this working very well in conjunction with the RStudio's improved data viewer. Perhaps the Viewer would allow us to step through each call one at a time? 

Perhaps another option is to implement an RStudio shortcut to iteratively print each piece of a piped command. For example:

```
new_data <- mtcars %>% filter(cyl == 6) %>% mutate(d_cyl = disp/cyl) 
```
With the cursor over a statement like that, typing `cmd+opt+p` would first print `mtcars`, then typing `cmd+opt+p` again would then print the result of `mtcars %>% filter(cyl == 6)` and then finally it would print the result of `mtcars %>% filter(cyl == 6) %>% mutate(d_cyl = disp/cyl)`

**Comment by GShotwell** [comment]
Interesting packages related to this issue called loopr. http://cran.r-project.org/web/packages/loopr/vignettes/Looping.html

It seems like this would run into some problems with large datasets but still very interesting syntax IMO.

**Comment by jhofman** [comment]
@datalove: that sounds like a great idea.

even an uninformed cmd+opt+p that simply did this with the first n rows of a data frame would be a nice start. then things can get smarter over time to deal with things like joins and filters that would require that consistent subsets are taken to ensure non-trivial output, following the techniques for Pig's ILLUSTRATE.

**Comment by hadley** [comment]
I still think this is a cool idea, but realistically it's unlikely we'll ever have the time to implement in dplyr.
