### ISSUE TITLE
Join on inequality constraints

### ISSUE THREAD

**Issue by gvfarns** [hadley/dplyr#557]
Several issues mention the need to join on inequality constraints, rather than only equality constraints (as well as the ability to join on equality constraints with differently named variables).  

https://github.com/hadley/dplyr/issues/515
https://github.com/hadley/dplyr/issues/177
https://github.com/hadley/dplyr/issues/378

Also for your reference, 

https://groups.google.com/forum/#!topic/manipulatr/gviW8lwCCzI

A join on inequality constraints (of which a rolling join in a special case) is extremely common and useful procedure, and one for which many users use sqldf().

It has been suggested elsewhere that a lazy cross join would be one way to approach this problem.  However, this method results in an inner join only. In addition, it is less parsimonious and transparent than some users may be expecting.    For reference, cross joins are discussed in #197.

Consider instead adding equality/inequality signs to the specification of join conditions.  For example,

```
  FundsWithReturns <- sqldf('select d1.*, d2.ReturnRf
                         from FundMonths d1 left join Returns d2
                         on d1.FundID = d2.FundID
                         and d1.yearmonth - 3 > d2.gmonth
                         and d1.yearmonth - 15 <= d2.gmonth')
```

could be written in dplyr as

```
FundsWithReturns <- left_join(FundMonths, Returns, FundID == FundID, 
                                   yearmonth > gmonth +3, yearmonth <= gmonth + 15)
```

The variable(s) on the right hand side of the equality or inequality come from the first input table and those from the second are on the right hand side.  In addition to permitting left joins and inequality constraints, this would permit users to join on equalities that have different names without the hassle of specifying them in `by.x` and `by.y` style conditions like those in #515.

For backward compatability and ease of use, specifying simply a variable name would mean an equality condition with the specified variable appearing in both datasets.

```
FundsWithReturns <- left_join(FundMonths, Returns, "FundID", 
                                   yearmonth > gmonth +3, yearmonth <= gmonth + 15)
```

This interface would also permit users to conveniently join a table to itself, a common operation that I am sure would be appreciated.  If this method is too difficult to parse, the conditions could be passed as a vector of strings in the `by` parameter.  That would be _really_ backward compatible.

```
    FundsWithReturns <- left_join(FundMonths, Returns, by=c("FundID", 
                                   "yearmonth > gmonth +3","yearmonth <= gmonth + 15"))
```

This enhancement suggestion is that instead of relying on the relatively inflexible lazy cross-join methodology for achieving what users ultimately will want, why not jump straight to an interface that you will be glad of in the long run.

Thanks for your consideration.

Stackoverflow references:

http://stackoverflow.com/questions/21888910/how-to-specify-names-of-columns-for-x-and-y-when-joining-in-dplyr
http://stackoverflow.com/questions/25045630/how-specify-join-variables-with-different-names-in-different-mysql-tables

**Comment by shntnu** [comment]
This is probably obvious, but when implementing the suggestion in https://github.com/hadley/dplyr/issues/557#issuecomment-58387227, ```!=``` should also be permitted:

    left_join( 
      FundMonths, Returns, 
      join_by(FundID != FundID, yearmonth > gmonth + 3, yearmonth <= gmonth + 15)
    )

**Comment by stevencb** [comment]
Has this change been released but I am missing it or is it still be be released ?

**Comment by hxrts** [comment]
The most natural route I've come up with (at least in my case) is grouping, left joining, slicing on a conditional that collapses to 1 row, and ungrouping. However, this gets a bit unwieldy with massive tables so I'd love a more general solution.

**Comment by ywhuofu** [comment]
still no progress on this? This is the ONLY reason that why I am still using SQL.....

**Comment by cwbishop** [comment]
+1 for this feature. I've been leveraging sqldf in the meantime.

**Comment by ywhuofu** [comment]
This feature is recently made available in data.table. 
see [data.table implementation](https://github.com/Rdatatable/data.table/issues/1452)

**Comment by vijayrajesh98** [comment]
Does dplyr:: left_join has this feature now when working with two dataframes? I am looking to join by an inequality. As pointed earlier, I think this would be straight forward in SQL. Here is a MWE to capture my similar dataset. 

       id <- c(1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,5,5,5,5,8,8,8,8,13,13,13)

        fyear <- c(1998,1999,2000,2001,1998,1999,2000,2001,2002,2003,
           1998,1999,2000,2001,2002,2003,1998,1999,2000,2001,
           1998,1999,2000,2001,1998,1999,2000)
 
        byear <- c(1990,1995,2000,2005)
        eyear <- c(1995,2000,2005,2010)
        val <- c(3,1,5,6)

        sdata <- tbl_df(data.frame(byear,eyear,val))

        test1 <- left_join(fdata,sdata, by = c("fyear" >= "byear","fyear" < "eyear")) 

I get the following error.

        Error: cannot join on columns 'TRUE' x 'TRUE': index out of bounds

**Comment by iangow** [comment]
SQL version should be easy to implement (see closed #1841).

**Comment by ywhuofu** [comment]
Will this ever be implemented?

**Comment by dan-svd** [comment]
Oh, inequality joins! Is this a feature that will be implemented ? (thanks for the sqldf and data.table references above!)

**Comment by benmarwick** [comment]
These inequality joins are available in @dgrtwo's [fuzzyjoin](https://cran.r-project.org/web/packages/fuzzyjoin/index.html), here's a nice example: http://stackoverflow.com/q/37289405/1036500

**Comment by hadley** [comment]
Moved into #2240
