### ISSUE TITLE
Make coercion rules explicit and consistent

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#594]
Rules:

* integer + double -> double
* logical NA + anything -> anything
* factor + factor (same levels) -> factor
* factor + factor (diff levels) -> character (WARN)
* factor + character -> character (WARN)
* ... ???

Where this arises:

* grouped summarise
* grouped mutate
* mutating & filtering joins
* `bind_rows()`, `combine()`

```R
# Integer coerced to double
df <- data_frame(x = 1:2) %>%
  group_by(x) %>%
  summarise(y = if (x == 1) 1L else 1)
expect_type(df$y, "double")

df <- data_frame(x = 1:2) %>%
  group_by(x) %>%
  mutate(y = if (x == 1) 1L else 1)
expect_type(df$y, "double")

df1 <- data_frame(x = 1L)
df2 <- data_frame(x = 1)
df <- bind_rows(df1, df2)
expect_type(df$x, "double")
expect_type(combine(df1$x, df2$x), "double")

df <- inner_join(df1, df2, by = "x")
expect_type(df$x, "double")
```

**Comment by krlmlr** [comment]
Should perhaps be discussed in hadley/vctrs#7 now.
