### ISSUE TITLE
R/Rstudio Crashes after running filter

### ISSUE THREAD

**Issue by avwilliams** [hadley/dplyr#602]
System:
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

Kernel
3.8.0-32-lowlatency #24-Ubuntu SMP PREEMPT  x86_64 GNU/Linux

Mem:       6112764

R version 3.1.1 (2014-07-10)
Platform: x86_64-pc-linux-gnu (64-bit)

RStudio
Version 0.98.932

```
library(dplyr)
library(rjson)
library(RJSONIO)
library(jsonlite)

Data Source:
socrata.afl <- fromJSON("https://data.cityofchicago.org/resource/alternative-fuel-locations.json?")
dim(socrata.afl)
## [1] 131  32
str(socrata.afl)
## 'data.frame':  131 obs. of  32 variables:
object_size(socrata.afl)
## 87.3 kB
```

Every time i run this command R/Rstusio Crashes

```R
filter(socrata.afl, fuel_type_code %in% "LPG")
filter(socrata.afl, fuel_type_code == "LPG")
Error:
R Session Aborted
R encountered a fatal error.
The session was terminated
Start New Session
```

These work
```R
subset(socrata.afl, fuel_type_code == "LPG")
subset(socrata.afl, fuel_type_code %in% "LPG")
```

Data Coerced Source:
socrata.afl.dt <- tbl_dt(socrata.afl)
This works:
filter(socrata.afl.dt, fuel_type_code == "LPG")

This does not, but R/Rstudio does not crash.
subset(socrata.afl.dt, fuel_type_code == "LPG")
Error in FUN(X[[2L]], ...) : 
  Invalid column: it has dimensions. Can't format it. If it's the result of data.table(table()), use as.data.table(table()) instead.

Any help kindly appreciated.

**Comment by romainfrancois** [comment]
I'm now getting: 

```
df <- data.frame( a = 1:10, b = 1:10, c = 1:10 )
df$b <- data.frame( x = 1:10, y = 1:10 )
df %>% filter( a < 5 ) %>% str
# Erreur : data_frames can only contain 1d atomic vectors and lists
```

because: 

```
> filter_.data.frame
function(.data, ..., .dots) {
  dots <- lazyeval::all_dots(.dots, ..., all_named = TRUE)
  as.data.frame(filter_(tbl_df(.data), .dots = dots))
}

> tdf <- tbl_df(df)
Erreur : data_frames can only contain 1d atomic vectors and lists
```

ping @hadley.

**Comment by romainfrancois** [comment]
I've put some simple change in the `more_data_frame` branch so that `as_data_frame` does less if the object is already a `data.frame`. 

So I can get to : 

```r
> df <- data.frame( a = 1:10, b = 1:10, c = 1:10 )
> df$b <- data.frame( x = 1:10, y = 1:10 )
> res <- df %>% filter( a < 5 )
> str(res)
'data.frame':	4 obs. of  3 variables:
 $ a: int  1 2 3 4
 $ b:'data.frame':	4 obs. of  2 variables:
  ..$ x: int  1 2 3 4
  ..$ y: int  1 2 3 4
 $ c: int  1 2 3 4
```

So the internal code does the right thing. 

However, we can't print those objects: 

```
> tbl_df(df)
Source: local data frame [10 x 3]

Error in `[.data.frame`(X[[i]], ...) : undefined columns selected
> tbl_df(res)
Source: local data frame [4 x 3]

Error in `[.data.frame`(X[[i]], ...) : undefined columns selected
```

Apparently this happens in `trunc_mat` formatting code. I'm not so familiar with that part of the code. So I'm reassigning this to @hadley

**Comment by hadley** [comment]
I think this is now correct - I get "data_frames can only contain 1d atomic vectors and lists " - the first column of this data frame is another data frame, which dplyr does not support.
