### ISSUE TITLE
mutate(data,mean(numeric))

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#637]
`mutate(data,mean(1))` returns a column equal to 1 when applied to a data.table. But the result seems random when applied to a data.frame. 

````R
library(dplyr)
library(data.table)
as.data.table(mtcars) %>% mutate(mean(1))
mtcars %>% mutate(mean(1))
````

**Comment by romainfrancois** [comment]
This is fixed now. I've added a regression test fr it.
