### ISSUE TITLE
Column class "duration" not allowed

### ISSUE THREAD

**Issue by andrewheiss** [hadley/dplyr#648]
Using R 3.1.1 and dplyr 0.3, dplyr gives an error when sorting a data frame with a column of class duration: 

    library(dplyr)
    library(lubridate)

    test.df <- data.frame(timestamp = mdy_hms(c("9/29/2014 11:41:36", "9/29/2014 15:29:23")),
                          start.time = mdy_hms(c("9/29/2014 10:18:00", "9/29/2014 12:30:00")),
                          end.time = mdy_hms(c("9/29/2014 14:00:00", "9/29/2014 15:15:00")),
                          data1 = rnorm(2),
                          data2 = rnorm(2))

    # Broken
    test.df %>%
      mutate(thing.length = as.duration(interval(start.time, end.time))) %>%
      arrange(start.time)
    # Error: column 'thing.length' has unsupported type

    # Working
    test.df %>%
      mutate(thing.length = as.numeric(as.duration(interval(start.time, end.time)))) %>%
      arrange(start.time)

    #             timestamp          start.time            end.time     data1      data2 thing.length
    # 1 2014-09-29 11:41:36 2014-09-29 10:18:00 2014-09-29 14:00:00 1.8323083 -1.3821700        13320
    # 2 2014-09-29 15:29:23 2014-09-29 12:30:00 2014-09-29 15:15:00 0.2527808  0.2156137         9900

I'm assuming this is related to https://github.com/hadley/dplyr/issues/266, where certain column types aren't whitelisted or allowed in dplyrable data frames.

**Comment by romainfrancois** [comment]
This is fixed in the dev version. Getting this now: 

```
> test.df <- data.frame(timestamp = mdy_hms(c("9/29/2014 11:41:36", "9/29/2014 15:29:23")),
+                       start.time = mdy_hms(c("9/29/2014 10:18:00", "9/29/2014 12:30:00")),
+                       end.time = mdy_hms(c("9/29/2014 14:00:00", "9/29/2014 15:15:00")),
+                       data1 = rnorm(2),
+                       data2 = rnorm(2))
>
>
> test.df %>%
+   mutate(thing.length = as.duration(interval(start.time, end.time))) %>%
+   arrange(start.time)
            timestamp          start.time            end.time     data1
1 2014-09-29 11:41:36 2014-09-29 10:18:00 2014-09-29 14:00:00 1.6456586
2 2014-09-29 15:29:23 2014-09-29 12:30:00 2014-09-29 15:15:00 0.6106942
       data2        thing.length
1 -0.8497158 13320s (~3.7 hours)
2  0.5466572 9900s (~2.75 hours)
```
