### ISSUE TITLE
performance issues (even unneccessary) in dplyrs SQL code

### ISSUE THREAD

**Issue by ringprince** [hadley/dplyr#667]
I do have a performance issue with SQL code generated by dplyr that
seems easily enough to fix (from the viewpoint of a user without
knowledge of dplyr code, that is).

The problem is that all references to tables are wrapped into
`select ` subqueries -- even if the reference is to an existing table
in the database.

If the table is sufficiently big this creates huge performance
problems.

Here is some code to illustrate that.  In this example the performance
is 15 times worse than it would have to be (60 seconds for dplyrs SQL
code, 4 seconds for the version with the simple fix).  In my real
application with hundreds of millions of rows a table, this makes
dplyr unusable.

    library("nycflights13")
    library("plyr")
    library("dplyr")

    ## create database
    my_db <- src_sqlite("my_db.sqlite3", create = T)
    ## check what's there
    dbListTables(my_db$con)

    ## convert to data.frame (as copy_to does not handle tbl_df)
    ## (only use standard characters in the names as copy_to does not
    ##  handle other names)
    flightsdf <- as.data.frame(flights)
    weatherdf <- as.data.frame(weather)

    ## inflate the tables to some bigger size to demonstrate the
    ## performance hit
    flightsdfext <- adply(0:10, 1, function(y)
      {
          flightsl <- flightsdf
          flightsl$year <- flightsl$year + y
          flightsl
      })
    flightsdfext <- flightsdfext[,-1]
    weatherdfext <- adply(0:10, 1, function(y)
      {
          weatherl <- weatherdf
          weatherl$year <- weatherl$year + y
          weatherl
      })
    weatherdfext <- weatherdfext[,-1]

    ## copy to database
    nycflights_sqlite <- copy_to(my_db, flightsdfext, temporary = FALSE)
    nycweather_sqlite <- copy_to(my_db, weatherdfext, temporary = FALSE)

    ## reconnect -- just to be sure...
    dbDisconnect(my_db$con)
    my_db <- src_sqlite("my_db.sqlite3")
    ## check what's there
    dbListTables(my_db$con)
    ## connect to tables
    nycflights_sqlite <- tbl(my_db, "flightsdfext")
    nycweather_sqlite <- tbl(my_db, "weatherdfext")

    timings <-
    adply(1:1, 1, function(x) {
      ## join
      nycflightsweather_sqlite  <- nycflights_sqlite %>% inner_join(nycweather_sqlite)
      (nycquery <- nycflightsweather_sqlite$query)
      time1 <- system.time(test1 <- collect(tbl(my_db, sql(as.character(nycquery$sql)))))
      ##time1 <- system.time(test1 <- collect(nycflightsweather_sqlite))
      test1

      ## remove the unnecessary subquery
      nycquery2 <- 'SELECT "year", "month", "day", "origin", "hour", "dep_time", "dep_delay", "arr_time", "arr_delay", "carrier", "tailnum", "flight", "dest", "air_time", "distance", "minute", "temp", "dewp", "humid", "wind_dir", "wind_speed", "wind_gust", "precip", "pressure", "visib"
      FROM "flightsdf"
      INNER JOIN
      "weatherdf"
      USING ("year", "month", "day", "origin", "hour")'
      (sql(nycquery2))

      time2 <- system.time(test2 <- collect(tbl(my_db, sql(nycquery2))))

      data.frame(time1=time1["elapsed"], time2=time2["elapsed"])
    })
    timings

    ## clean up
    dbDisconnect(my_db$con)

Could dplyr stop putting references to tables present in the database
in artificial (select ....) subqueries?

**Comment by hhoeflin** [comment]
@ringprince 
I just tried to run your code to verify that this is the reason and I see no performance difference.

The first query (despite being wrapped in a select * ) runs in 10 seconds, the second one in 9.3 seconds.

**Comment by hadley** [comment]
I'm going to punt on this - I really believe this is something any sufficiently good db will do for plyr (but unfortunately I don't think MySQL is such a db)
