### ISSUE TITLE
colname V1 x data.table x filter fails

### ISSUE THREAD

**Issue by kohske** [hadley/dplyr#672]
```
library(data.table)
library(dplyr)
df = data.table(V1 = c("A", "A", "B", "B"), V2 = c(1, 100, 2, 100))
df %>%  group_by(V1) %>%  filter(V2 == min(V2))
```

results in a wrong output:

```
## Source: local data table [4 x 2]
## Groups: V1
## 
##   V1  V2
## 1  A   1
## 2  A 100
## 3  B   2
## 4  B 100
```

and 

```
dt = data.frame(V1 = c("A", "A", "B", "B"), V2 = c(1, 100, 2, 100))
dt %>% as.data.table %>% 
  group_by(V1) %>% 
  filter(V2 == min(V2))
```

throws an error.

These are because, in `filter.grouped_dt`

```
indices <- eval(call, env)$V1
out <- .data[indices[!is.na(indices)]]
```

here `V1` sometimes refers to the column that is automatically generated by `[.data.table` , instead of `V1` of the original data table.

Another methods, e.g., `mutate`, `arrange` etc may have the same issue, I've not yet explored though.

This behavior was found by @gghatano, so if this appears in NEWS, credit him please.

http://rpubs.com/gg_hatano/32960 (in JP)

**Comment by hadley** [comment]
This appears to have been fixed already
