### ISSUE TITLE
error with data.table when joining on different variables in x and y tables

### ISSUE THREAD

**Issue by cderv** [hadley/dplyr#694]
Hi, 

Using dplyr 0.3.0.2, I like the new features for *_join : 
* Joins (e.g. `left_join()`, `inner_join()`, `semi_join()`, `anti_join()`)
  now allow you to join on different variables in `x` and `y` tables by
  supplying a named vector to `by`. For example, `by = c("a" = "b")` joins
  `x.a` to `y.b`.

However, it seems not to work the same on data.frame and data.table. For data.table, it gives me an error : 
` #Error: Data table joins must be on same key`
***
Here's a reproductible example : 
```
library(dplyr)
A<-mtcars %>% select(vs,mpg,disp) %>% sample_n(size = 3,replace = T)
B<-mtcars %>% select(vs,mpg,disp) %>% sample_n(size = 3,replace = T)
names(B)<-paste0(names(B),".B")
A_DT<-as.data.table(A)
B_DT<-as.data.table(B)
```
When i tried to do an inner join with data.frame, it's ok
```
A %>>%
  inner_join(B,by=c("vs"="vs.B"))
```
```
#  vs  mpg  disp mpg.B disp.B
#1  0 26.0 120.3  15.8    351
#2  0 15.2 304.0  15.8    351
#3  1 33.9  71.1  22.8    108
#4  0 26.0 120.3  14.7    440
#5  0 15.2 304.0  14.7    440
```
If I tried to do the same with data.table,I get an error. 
```
A_DT %>>%
  anti_join(B_DT,by=c("vs"="vs.B"))
```
```
#Error: Data table joins must be on same key
```
***
I was expected the same result whether my tables are data.frame or data.table.
Apparently, new feature for joining on different variables in `x` and `y` tables are not working with data.table. I do not know if it should, but at least I report it.

If you could do something about it (probably with setkey), it would be great. 

Thank you for your great work. 

Christophe

**Comment by helix123** [comment]
Think the data.table guys now fixed this in devel, see https://github.com/Rdatatable/data.table/issues/637. However, it might take some time until we see a new CRAN release of data.table.

**Comment by lasseklokker** [comment]
Am I correct in thinking that data.table from v1.9.6 now supports what have been the problem for this issue to be solved, as no deep copies are made anymore, or do I not fully understand the problem?

**Comment by Dripdrop12** [comment]
I can confirm that v1.9.6 is still throwing this error.

**Comment by siddhesh1991** [comment]
I am still getting this error. I have 2 data.tables and I am trying left_join on 2 different keys

> a <- b %>% left_join(c, by= c('LEADID.2'='LEADID'))
Error: Data table joins must be on same key

**Comment by Giannettig** [comment]
Me too
