### ISSUE TITLE
Antonym to filter

### ISSUE THREAD

**Issue by matthieugomez** [hadley/dplyr#741]
It would be useful to have a function, say `discard`, that discards rows where the condition evaluates to TRUE. This function would be different from `filter(!condition)` when condition evaluates to NA. Example below

``` R
x <- data.frame(v1 = c(1, 2, NA))
#>  v1
#>1  1
#>2  2
#>3 NA
filter(x, !(v1 == 1))
#>  v1
#>1  2
discard(x, v1 == 1)
#>  v1
#>1  2
#>2 NA
```

**Comment by hadley** [comment]
It's not a bad idea, but realistically it's not going to climb high enough on my priority list to get implemented
