### ISSUE TITLE
structure of summarise_each_() output

### ISSUE THREAD

**Issue by Mullefa** [hadley/dplyr#758]
From programming with `summarise_each_()` (and `mutate_each_()`), I feel it would be very useful to have an option to record the summarised data in new rows, rather than new columns.

For example:

```R
summarise_each(iris, funs(mean, sd), -Species, record_by = "rows")

# output would be equivalent to the following:
data_frame(
  fun          = c("mean", "sd"),
  Sepal.Length = c(5.843333, 0.8280661),
  Sepal.Width  = c(3.057333, 0.4358663),
  Petal.Length = c(3.758, 1.765298),
  Petal.Width  = c(1.199333, 0.7622377)
)
```

This would extend to grouped tables in an obvious manner.

**Comment by hadley** [comment]
That feels like a different verb to me.

**Comment by Mullefa** [comment]
Good point. Completely agree.
