### ISSUE TITLE
cbind on tbl_df should return a tbl_df?

### ISSUE THREAD

**Issue by daattali** [hadley/dplyr#779]
Not sure if this is a feature or a bug - if I cbind two separate tbl_df objects, I expected the result to also be a tbl_df rather than having to cast it myself.

```
df <- tbl_df(data.frame(a = letters))
DF <- tbl_df(data.frame(A = LETTERS))
bound <- cbind(df, DF)
class(bound)
```

**Comment by steromano** [comment]
I'll just comment here instead of opening a new issue, as this is likely a small thing.
Contrary to what the documentation says, `cbind_cols` seems to always return a `data.frame`:

```
x <- as.tbl(iris)
bind_cols(x, x) %>% class  # data.frame
```

**Comment by jennybc** [comment]
:+1: to this thread and proposed enhancement. What @steromano said: when I supply two `tbl_df`s to `bind_cols()`, I get a `data.frame` back. It's unexpected and contradicts the documentation.

**Comment by romainfrancois** [comment]
Now it's always making a `tbl_df` which is harmless anyway, even if both are just `"data.frame"`.
