### ISSUE TITLE
Deprecate rbind_list and rbind_all

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#803]

**Comment by Mullefa** [comment]
What would be used in its place? I love the speed of these function :)

**Comment by hadley** [comment]
`bind_rows()`

**Comment by Mullefa** [comment]
Great - I could never remember whether `rbind_list()` took a list, or coerced its arguments to a list.

**Comment by thomasp85** [comment]
Will `bind_rows()` have support for matrices? I know everything dplyr is data.frame based (sort of) but the utility of the `bind_rows()`/`rbind_all()` is broader than dplyr. The overhead of converting the input to data.frames can be high, so it would be nice to have dispatch for matrices as well...

It seems it seems bind_impl is casting all input to DataFrame anyway so it should be fairly easy to include matrices... I could take a stab at it if you're willing to include it in dplyr. If so please let me know whether you have preferences for the interface...

**Comment by hadley** [comment]
@thomasp85 yes, I'd be willing to review that - please file as a separate issue
