### ISSUE TITLE
Row-wise data frame creation

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#804]
Often when creating example data you want to see a row of data at a time. It would be useful to have an easy way to create this with dplyr. Maybe something like?

```R
rdf(ncol = 4, 
  "a", 1, 3, "b",
  "c", 2, 5, "e"
)
```

?

Have you thought about this at all @kevinushey ?

**Comment by jennybc** [comment]
Hopefully dplyr will eventually have a function like `read_table()` where

dplyr::read_table is to dplyr::data_frame as read.table is to data.frame

in which case it could offer a `text =` argument like `read.table()` does. I use that a lot to do this row-wise creation of data for examples, e.g.:

```r
read.table(text = c("'a' 1 3 'b'",
                    "'c' 2 5 'e'"))
```

**Comment by hadley** [comment]
(That function will be called `fastread::read_table()`)

**Comment by hadley** [comment]
Another option would be

```R
rdf(
  "a" | 1 | 3 | "b",
  "c" | 2 | 5 | "e"
)
```

**Comment by kevinushey** [comment]
I like making tiny DSLs within function calls; I can take a stab at that.

**Comment by hadley** [comment]
@kevinushey that would be great!
