### ISSUE TITLE
double assignment in `data_frame` creates two variables with `var.i` numbering

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#820]
`data_frame(a = runif(10), a = (a-mean(a))/sd(a))` creates a `data.frame` with two columns (`a` and `a.1`). I would expect that `a` is replaced by the second assignment. I also think that would be a useful feature. In the example, I first create a random variable and then standardize the variable.

**Comment by hadley** [comment]
Decided to go with an error - this seems most consistent with what `as_data_frame()` would have to do.
