### ISSUE TITLE
Summarise should allow list outputs

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#832]
e.g. 

```R
library("dplyr")

InsectSprays %>% 
  tbl_df() %>%
  mutate(spray = as.character(spray)) %>% 
  group_by(count) %>% 
  summarize(list(spray))
```

this fits in with the current philosophy because the summary function returns a list of length 1.

**Comment by macielufpr** [comment]
To return everything in one field, you can do
`df %>%
  group_by( key ) %>%
  summarise( summary.field = paste( do.call( rbind, list( character.field ) ), collapse = ", " ) )`
