### ISSUE TITLE
print.tbl_df with encoding

### ISSUE THREAD

**Issue by romainfrancois** [hadley/dplyr#851]
```
> x<-data_frame(name=c("\xC9lise","Pierre","Fran\xE7ois"),score=c(5,7,6) )
> x
Source: local data frame [3 x 2]

Error in nchar(values) : invalid multibyte string 2
> as.data.frame(x)
         name score
1    \xc9lise     5
2      Pierre     7
3 Fran\xe7ois     6
```

**Comment by krlmlr** [comment]
The issue should disappear if `nchar(values)` is substituted by `nchar(encodeString(values))` [in the code](https://github.com/hadley/dplyr/blob/abb45a8c01369a4fb612d559c4707fca71c7328f/R/utils-format.r#L67) (same for `names`). But this `encodeString` looks like a [costly](https://github.com/wch/r-source/blob/b99d403f4b7337553acb2d2108c7a00e6c19f908/src/main/util.c#L1034) operation even for "properly encoded" strings.

**Comment by romainfrancois** [comment]
I don't think the performance penalty is big deal here. Thanks for the hint.
