### ISSUE TITLE
segfault with bind_rows() on empty data frame

### ISSUE THREAD

**Issue by lionelgit** [hadley/dplyr#854]
Reprex:
```
as_data_frame(list(a = NULL)) %>% bind_rows()
```

On the other hand, this causes no crash:
```
as.data.frame(list(a = NULL)) %>% bind_rows()
```
The data frame in the first line has zero row / one variable, while in the second line it has zero row / zero variable.

**Comment by hadley** [comment]
I'm pretty sure I have a better test now - we now only allow 1d atomic vectors and lists to be columns of a data frame.
