### ISSUE TITLE
no applicable method for 'escape' applied to an object of class "c('POSIXct', 'POSIXt')"

### ISSUE THREAD

**Issue by wush978** [hadley/dplyr#857]
At first, I want to thank your hard work of developing `dplyr` package to the R community. This is one of the best package to do data manipulation in R and it does a lot of helps in my work.

Recently, I am trying the database API and filter a datetime column in PostgreSQL. I have the following error message:

```
> filter(hourly_rps_mode, time == time_value)
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('POSIXct', 'POSIXt')"
```

It could be fixed easily by:

```
escape.POSIXt <- dplyr:::escape.Date
```

Could you add this to the package?

**Comment by nelsonauner** [comment]
:+1: I still encounter this error and am able to fix it in the way described by @wush978

**Comment by peterparkerspicklepatch** [comment]
I received a similar error but in the form of `Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"` after `filter(year == 2016, month 1 | 2)`. I am using an impalaDB with `dplyrimpaladb` and the GitHub version of `dplyr`.

**Comment by hadley** [comment]
For maximum compatibility, need to convert to ISO 8601 in UTC.

**Comment by dbuijs** [comment]
Had the error this morning on dplyr 0.4.3, connecting to postgresql 9.3, with RPostgreSQL 0.4, doing a filter operation on a POSIXct column. 

Work around described by @wush978 above addressed the issue. 

If the patch applied on Mar 7 hasn't yet been applied to the CRAN version of dplyr, then please disregard.
