### ISSUE TITLE
`filter` doesn't work when data.frame column has attributes

### ISSUE THREAD

**Issue by kent37** [hadley/dplyr#859]
This seems to be an issue with using `filter` when a column of the data frame has an attribute. For example,

    > df = data.frame(x=1:10, y=1:10)
    > filter(df, x==3) # Works
      x y
    1 3 3

Add an attribute to the `x` column. Notice that `str(df)` shows `x` as `atomic` now, and `filter` doesn't work:

    > attr(df$x, 'width')='broad'
    > str(df)
    'data.frame':	10 obs. of  2 variables:
     $ x: atomic  1 2 3 4 5 6 7 8 9 10
      ..- attr(*, "width")= chr "broad"
     $ y: int  1 2 3 4 5 6 7 8 9 10
    > filter(df, x==3)
    Error: column 'x' has unsupported type

**Comment by grialex** [comment]
I face the same problem having POSIXlt columns in the data frame. Apart from that I like dplyr.

**Comment by hadley** [comment]
@grialex using POSIXlt will eventually cause you pain with or without dplyr - use POSIXct instead.

**Comment by grialex** [comment]
@hadley Thanks for the advice. Now it works.

**Comment by triangle-man** [comment]
The problem is worse than it appears: `filter` fails even if the column with attributes is *not* the column being filtered on. Using @kent37 's example:
```r
df = data.frame(x=1:10, y=1:10)
attr(df$x, 'width')='broad'
filter(df, y == 2)
```
produces the error, even though we're filtering on `y`.

I'd quite like to store values of class `duration` from `lubridate` in one of my data frames, and use `dplyr`, so I'd be happy if the behaviour were to retain attributes, at least optionally.

**Comment by bergsmat** [comment]
I have this problem as well.  Maybe dplyr could define a generic attribute handler and those of us needing special classes could write handling methods.  Else, I'm in favor of preserving attributes (at least length-one attributes).
```
install.packages('metrumrg',repos="http://R-Forge.R-project.org")
library(metrumrg)
library(dplyr)
library(magrittr)
Theoph %<>% mutate(clock = Time %>% as.hour %>% as.second %>% as.mTime)
Theoph %<>% filter(Time == 0)
# Error: column 'clock' has unsupported type : mTime, timepoint, timeline, numeric
```

**Comment by lionel-** [comment]
This poses problem with the haven package:

```
+ Error: column 'demcontrol' of type integer has unsupported attributes: label
```

**Comment by chrisaxelson** [comment]
At the moment I'm also importing with haven and then removing all attributes before going any further with dplyr.
````
df[] <- lapply(df, function(x) {attr(x, 'label') <- NULL; x})
````
I'm personally happy if the attributes aren't kept since you have to remove them anyway.

**Comment by mdsumner** [comment]
Here's another example just in case someone is looking: 

library(rworldmap)
data(countriesLow)
library(dplyr)
as_data_frame(as.list(as.data.frame(countriesLow)))  %>% filter(SOVEREIGNT == "Angola")
Error: column 'ScaleRank' of type integer has unsupported attributes: levels

I fix it with: 

o[] <- lapply(o, function(x) {if(isTRUE(all.equal(attr(x, 'levels'), character(0)))) {attr(x, 'levels')  <- NULL}; x})

I think the right fix is to repair the data in this rworldmap package, which I'll try to do.

**Comment by romainfrancois** [comment]
This is being taking care of in #1105, i.e. in the dealing-custom-classes branch. Could you check if it works with this branch ?

**Comment by mdsumner** [comment]
Yes, it does fix my issue. Thanks!
