### ISSUE TITLE
use mutate_each after grouping and factors after joining 

### ISSUE THREAD

**Issue by ckluss** [hadley/dplyr#860]
Hi,

only comments, not a real problem. 

After `group_by` `mutate` throws an error when no `ungroup` follows but `mutate_each` does nothing (no error, no changes without `ungroup`)

After joining e.g. `full_join` factors or no factors any more (on the one hand it is good that factors are converted to strings before joining but on the other hand it is irritating without an info message)

thank you for this fantastic package
Christof

**Comment by hadley** [comment]
The warning message seems correct to me.
