### ISSUE TITLE
found duplicated column name (warning instead of error?)

### ISSUE THREAD

**Issue by ckluss** [hadley/dplyr#861]
Hi

would be cool, if instead of "Error: found duplicated column name" a warning "Delete columns: ... because of same names" or something like that happens. internally something like

 `data <- data[, !duplicated(colnames(data))] ` or a automatic renaming to ".1", ".2" ...

`read.xlsx` (openxlsx) and `read.xls` (gdata) unfortunately do it not automatically

Christof

**Comment by romainfrancois** [comment]
An error gives you a better chance of fixing the problem with the input data. With a warning you might ignore it and perhaps do something that you did not want. I think it's your job to make sure that you feed dplyr with appropriate data, so do something in between calling `read.xls*` and dplyr functions.
