### ISSUE TITLE
Drop variables that do not exist

### ISSUE THREAD

**Issue by ckluss** [hadley/dplyr#864]
Hi 

dplyr 0.3.0.9000, `select(iris, -starts_with("X"))`

results in 

`data frame with 0 columns and 150 rows`

because there is no column name starting with "X"

I would expect no changes

thx
Christof

**Comment by ckluss** [comment]
Hi

of course the same with `select(iris, -X)`

`Error in eval(expr, envir, enclos) : object 'X' not found`

I would prefer a warning, if it has no disadvantages.

Christof

**Comment by hadley** [comment]
It's unfortunately difficult to cover every possible abuse. I'm pretty happy with the way `select()` operates currently, and the code is already pretty complicated.
