### ISSUE TITLE
Cannot find columns with UTF-8 encoded names (in Windows)

### ISSUE THREAD

**Issue by hkjinlee** [hadley/dplyr#866]
Greetings, I'm a Korean R user using dplyr on both OS/X and Windows. (First of all, I would like to show my appreciation to all the contributors of this elegant package)

Current development version still seems to have some issues with dealing with non-ASCII column names on Windows: dplyr cannot recognize newly created column name.

```
> df <- data.frame(한글=1:3, Eng=2:4)
> df2 <- df %>% mutate(한글2=한글*2)
> df2$한글2 > 2
[1] FALSE  TRUE  TRUE
> df2 %>% arrange(한글2)
Error in arrange_impl(.data, dots) : object '한글2' not found
```

And I suppose this happens due to the different character encoding between old column (not created by dplyr) and new column. You can see only newly created one's name is UTF-8 based.

```
> df2 %>% names %>% { print(.); Encoding(.) }
[1] "한글"  "Eng"   "한글2"
[1] "unknown" "unknown" "UTF-8"  
```

Maybe this issue has something with #633 and #722. dplyr is showing somewhat different results among versions. On v0.2.0, both old and new column names are 'unknown', on v0.3.0 both are 'UTF-8', and on v0.4.0(current development version) old column name is 'unknown' and new one is 'UTF-8'.

From v0.2.0:
```
other attached packages:
[1] dplyr_0.2

loaded via a namespace (and not attached):
[1] assertthat_0.1 devtools_1.6.1 parallel_3.1.2 Rcpp_0.11.3    tools_3.1.2  
d> d <- data.frame(이름=c('홍길동'))
d> d %>% names %>% Encoding
[1] "unknown"
d> d2 <- d %>% mutate(이름2=paste0(이름, '_'))
d> d2 %>% names %>% Encoding
[1] "unknown" "unknown"
```

From v0.3.0:
```
other attached packages:
[1] dplyr_0.3      devtools_1.6.1

loaded via a namespace (and not attached):
 [1] assertthat_0.1 bitops_1.0-6   DBI_0.3.1      httr_0.6.1     magrittr_1.5   parallel_3.1.2 Rcpp_0.11.3  
 [8] RCurl_1.95-4.5 stringr_0.6.2  tools_3.1.2  
d> d <- data.frame(이름=c('홍길동'))
d> d %>% names %>% Encoding
[1] "unknown"
d> d2 <- d %>% mutate(이름2=paste0(이름, '_'))
d> d2 %>% names %>% Encoding
[1] "UTF-8" "UTF-8"
```

I attach my sessionInfo for the information.
```
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949
[4] LC_NUMERIC=C                 LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.0    devtools_1.6.1
```

**Comment by shrektan** [comment]
The problem in issue #722 about Chinese colum name appears again in dplyr 0.4.0~
I've put the reproducible code in the comment.

**Comment by hkjinlee** [comment]
I think I've discovered some hints:

- **dplyr** depends on **lazyeval** on arguments processing (**lazyeval::all_dots**, specifically)
- **lazyeval::all_dots** calls **c()** to combine two lazy dots(internally, list) as below: .dots and ...
```
all_dots <- function(.dots, ..., all_named = FALSE) {
  dots <- as.lazy_dots(list(...))
  if (!missing(.dots)) {
    dots2 <- as.lazy_dots(.dots)
    dots <- c(dots, dots2)
  }

  if (all_named) {
    dots <- auto_name(dots)
  }

  dots

}
```
- It seems that current implementation of R's **c()** sets the encodings of combined lists' name to 'UTF-8', when one or more name contains non-ASCII characters.
```
> Encoding(names(list(한글='K', 中文='C')))
[1] "unknown" "unknown"
> Encoding(names(c(list(한글='K'), list(中文='C'))))
[1] "UTF-8" "UTF-8"
```
- As result, new columns created by **mutate()** are encoded as UTF-8; while inherited columns are still using 'unknown', and **dplyr** cannot lookup newly created columns
```
> data.frame(한='Korea') %>% mutate(한2=한) %>% names %>% Encoding
[1] "unknown" "UTF-8"  
> data.frame(한='Korea') %>% mutate(한2=한) %>% mutate(한3=한2)
 Error: binding not found: '한2' 
```

I suppose there would be some workarounds, but this is all I can get now without any further understanding of Rcpp.

**Comment by romainfrancois** [comment]
Hmm. I get this now: 

```
> data.frame(한='Korea') %>% mutate(한2=한) %>% mutate(한3=한2)
     한   한2   한3
1 Korea Korea Korea
> df2 %>% arrange(한글2)
  한글 Eng 한글2
1    1   2     2
2    2   3     4
3    3   4     6
> df2 %>% arrange(desc(한글2))
  한글 Eng 한글2
1    3   4     6
2    2   3     4
3    1   2     2
```

which looks fine. Can you check again, it might have been fixed by accident.

**Comment by hadley** [comment]
@romainfrancois you might need to be on windows (i.e. that doesn't use utf-8 by default) to see the problem

**Comment by romainfrancois** [comment]
Right. I'll try that.

**Comment by romainfrancois** [comment]
I changed a few things recently about how we deal with column names, it should be more resistant to encoding issue like these. @hkjinlee can you try the dev version please.

**Comment by hkjinlee** [comment]
@romainfrancois You did a fantastic job! Tried dev version and found the encoding issue gone away.
@shrektan Would you try yourself for Chinese column names (for double check)?

```
df <- data.frame(한글=1:3, Eng=2:4)
df2 <- df %>% mutate(한글2=한글*2)
df2 %>% names %>% Encoding
[1] "unknown" "unknown" "unknown"
```

**Comment by romainfrancois** [comment]
Thanks. I'm closing this now. @shrektan let me know if this does not work for you. Very glad this is out of the way.

**Comment by shrektan** [comment]
Just tested it and it works. Thanks!

**Comment by YizhouZheng** [comment]
I found the UTF-8 still problem still alive in group_by(). (Using the newest dev version. 0.4.3.9000)

See below for reproducible code.

Create a dataframe and make the colnames UTF-8.

> library(dplyr)
> df <- data.frame(测试=1:3, Eng=2:4)
> names(df) <- enc2utf8(names(df))
> Encoding(names(df))
[1] "UTF-8"   "unknown"

select() works.

> df %>%   select(测试) 
  测试
1    1
2    2
3    3

group_by doesn't work.

> df %>% group_by(测试) #group_by won't work
Error: unknown column '测试'
> 

group_by work well under native encoding.

> names(df) <- enc2native(names(df))
> df %>% select(测试)
  测试
1    1
2    2
3    3

> df %>% group_by(测试)
Source: local data frame [3 x 2]
Groups: 测试 [3]

   测试   Eng
  (int) (int)
1     1     2
2     2     3
3     3     4
>
