### ISSUE TITLE
[BUG] Encountered Error: "R object not found" if dplyr is performed inside a function

### ISSUE THREAD

**Issue by xiaodaigh** [hadley/dplyr#868]
library(dplyr)
library(data.table)
f <- function(x, y, bad) { 
  z <- data.table(x,y, key = "x")    
  z2 <- z %>% group_by(x) %>% summarise(sum.bad = sum(y == bad))
  z2
}

f(rnorm(100), rnorm(100) < 0, bad = FALSE) 
When I run the above I get

Error in `[.data.table`(dt, , list(sum.bad = sum(y == bad)), by = vars) : 
  object 'bad' not found
However bad is clearly defined and in scope.

See StackOverflow post
http://stackoverflow.com/questions/27773881/r-object-not-found-if-defined-within-a-function-when-using-data-table-dplyr/27774139#27774139

**Comment by hadley** [comment]
Fixed in the dev version
