### ISSUE TITLE
sample_n_groups()?

### ISSUE THREAD

**Issue by Mullefa** [hadley/dplyr#875]
I'd like to make a case for the function `sample_n_groups()` (and its `frac` counterpart).

My use case is that if I'm working with customer data in memory, it's sometimes useful to be able to look at a random subset of customers. Below is the generic function I'm using and the corresponding data frame method, though no doubt it can be improved:

```R
sample_n_groups <- function(tbl, size) {
  UseMethod("sample_n_groups")
}


sample_n_groups.grouped_df <- function(tbl, size) {
  if (size > (n <- n_groups(tbl))) {
    warning(
      sprintf(
        "%s only has %d groups. Setting sample size equal to %d.",
        as.character(substitute(tbl)), n, n
      ),
      call. = FALSE
    )

    size <- n
  }

  indices <- attributes(tbl)$indices
  idx <- sample(length(indices), size)

  tbl[unlist(indices[idx]) + 1, ]
}
```

I also find the following useful, but accept this might be an edge case:

```R
sample_a_group <- function(tbl) {
  ungroup(sample_n_groups(tbl, 1))
}
```

**Comment by hadley** [comment]
Want to do a pull request? (Although it might be a month or so before I can review in detail)

**Comment by Mullefa** [comment]
Will try and find the time to submit a pull request - month till review
suits me as I'm pretty busy atm
