### ISSUE TITLE
Make as_data_frame a generic so can work on matrices?

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#876]
I love love love `data_frame()`. I wish I could get that behaviour when converting an existing matrix to a data.frame.

```r
> foo <- matrix(LETTERS[1:6], nrow = 3)
> data_frame(foo)      # nope
Error: data_frames can not contain data.frames, matrices or arrays
> data.frame(foo)      # this works, BTW
  X1 X2
1  A  D
2  B  E
3  C  F
> as.data.frame(foo)   # but this is probably better
  V1 V2
1  A  D
2  B  E
3  C  F
> str(data.frame(foo)) # but the factor conversion is annoying
'data.frame':	3 obs. of  2 variables:
 $ X1: Factor w/ 3 levels "A","B","C": 1 2 3
 $ X2: Factor w/ 3 levels "D","E","F": 1 2 3


> ## what I WISH I could do -- warning: I made this up!
> (foo_dream <- as_data_frame(foo))
Source: local data frame [3 x 2]
            V1           V2
1            A            D
2            B            E
3            C            F
> str(foo_dream)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3 obs. of  2 variables:
 $ V1: chr  "A" "B" "C"
 $ V2: chr  "D" "E" "F"
```

**Comment by hadley** [comment]
Maybe we need to make `as_data_frame()` generic? But that would make it slower. We could just add a second path for matrices

**Comment by jennybc** [comment]
I have amused myself with this workaround now that I know about existing `as_data_frame()`:

```r
> plyr::alply(foo, 2) %>% as_data_frame
Source: local data frame [3 x 2]

  1 2
1 A D
2 B E
3 C F
```

**Comment by klmr** [comment]
To chime in, I end up doing the following all over the place:

```r
result = some_function_call() %>%
    as.data.frame() %>%
    as_data_frame()
```

Furthermore, I’m not sure don’t understand the need for the function `tbl_df`, which does just one additional check. So I suggest merging the current functionality of `as_data_frame` into `tbl_df`, and providing a more helpful `as_data_frame`.

**Comment by davharris** [comment]
This issue was referenced on @jennybc's Twitter account [today](https://twitter.com/JennyBryan/status/598242239773483008), so I thought now might be a good time to chime in.

I also use @klmr's pattern very frequently (except my code usually looks more like `as.data.frame(stringsAsFactors = FALSE) %>% tbl_df`).

I'm not sure I understand @hadley's concern about speed.  I thought that generics only took a few extra thousandths of a second. Is `as_data_frame` called often enough that this extra time is likely to matter?

If speed is still a concern, then I'd also be nearly as happy with a function like this one:

```
tbl_df_generic = function(x){
    x%>% as.data.frame(stringsAsFactors = FALSE) %>% tbl_df`)
}
```

It would add a *small* amount of cognitive overhead compared to just using a generic `tbl_df`, but it would still be way less overhead than needing to remember `stringsAsFactors = FALSE`.

**Comment by hadley** [comment]
@davharris I'm concerned about speed because sometimes I apply `as_data_frame()` to a list that contains >100,000 things. Some of that might go away if `rbind_rows()` could work with lists directly, but I need to think it through and do some benchmarking.

**Comment by davharris** [comment]
@hadley Okay, I hadn't realized it would be called that many times.

Here's some quick benchmarking that might be useful.

```
# a new generic for as_data_frame
as_data_frame_generic = function(x){
  UseMethod("as_data_frame_generic")
}

# a list method for the new generic
as_data_frame_generic.list = function(x){
  as_data_frame(x)
}

# A small list to use as an example.
# If the list is small, then dispatch will take proportionately longer
my_list = list(
  a = letters,
  A = LETTERS,
  one = 1:26,
  two = 26:1
)

library(microbenchmark)

microbenchmark(
  no_dispatch = as_data_frame(my_list),
  dispatch = as_data_frame_generic(my_list),
  times = 5E5
)
```

Here are the results on my laptop:

```
Unit: microseconds
        expr    min     lq     mean median     uq      max neval
 no_dispatch 40.307 44.849 51.16531 46.135 51.646 88714.88 5e+05
    dispatch 42.263 46.865 53.54021 48.212 54.082 84428.73 5e+05
```

It looks like this dispatch implementation increases the computation time on a half-million lists from 25.6 seconds to 26.8 seconds.

It probably makes sense to do more extensive benchmarking (for example, would things slow down if we added more methods?).  So far, things look pretty good, though.

**Comment by hadley** [comment]
@davharris thanks - that seems reasonable and suggests that I shouldn't worry about it. I'll make the change when I'm next working on dplyr. An efficient implementation of `as_data_frame.matrix()` in C++ should be reasonable simple.

**Comment by davharris** [comment]
@hadley Perfect. Thanks.

**Comment by jennybc** [comment]
Déjà vu: trying to turn a character matrix into a `tbl` and rediscovered my own issue.

Bump.

``` r
library(dplyr)
ip <- installed.packages() %>% as.tbl()
#> Error in UseMethod("as.tbl"): no applicable method for 'as.tbl' applied to an object of class "c('matrix', 'character')"
ip <- installed.packages() %>% as_data_frame()
#> Error: is.list(x) is not TRUE
```

**Comment by hadley** [comment]
I actually just wrote an efficient implementation for this for tidyr - I'll hoist it up into dplyr.
