### ISSUE TITLE
select() with matches() is not case sensitive?

### ISSUE THREAD

**Issue by randArch** [hadley/dplyr#878]
If I create a data frame with names in upper case:

    > example <- 
    +   data.frame(A = rnorm(10), B = rnorm(10), C = rnorm(10))

then select columns with uppercase names:

    > dplyr::select(example, matches("[A-Z]")) %>% names
    [1] "A" "B" "C"

it worked fine, but if I select columns with lowercase names:

    > dplyr::select(example, matches("[a-z]")) %>% names
    [1] "A" "B" "C"

it still selects the uppercase names.

**Comment by ckluss** [comment]
default is ignore.case = TRUE, you have to set it to FALSE, 

    matches(x, ignore.case = TRUE)
