### ISSUE TITLE
as_data_frame doesn't work with coredata

### ISSUE THREAD

**Issue by kismsu** [hadley/dplyr#881]
It's very common to convert time series objects like zoo or xts to data.frame by using ``` coredata ```.
However it doesn't work with as_data_frame. 

```r
x.date <- as.Date(paste(2003, rep(1:4, 4:1), seq(1,20,2), sep = "-"))
x <- zoo(matrix(rnorm(20), ncol = 2), x.date)
as_data_frame(coredata(x))
```

```
Error: is.list(x) is not TRUE
```

**Comment by romainfrancois** [comment]
`coredata` makes a `matrix` so that is a duplicate of #876.
