### ISSUE TITLE
as_data_frame optional adds row names

### ISSUE THREAD

**Issue by sjPlot** [hadley/dplyr#884]
Since row names are dropped when using data_frame, I often use nested commands such as `as_data_frame(add_rownames(mtcars))`. Maybe as_data_frame can get an optional parameter to automatically add row names, like `as_data_frame(mtcars, add.row.names = TRUE)` or so?

**Comment by hadley** [comment]
Why are you calling `as_data_frame()`  on something that's already a data frame?

**Comment by sjPlot** [comment]
1.) I thought for coercion reasons it would make sense to have the object in class "data_frame" and/or "tbl" when working with dplyr? And 2.) this example may be extended to non-data-frames as well, where coercion also makes sense.
I'm wondering whether I am wrong at this point about the benefits of such an option?

**Comment by hadley** [comment]
I'd rather keep it as a separate function.
