### ISSUE TITLE
Melt fails on a tbl

### ISSUE THREAD

**Issue by zozlak** [hadley/dplyr#885]
I have a dplyr's tbl data set obtained from a SQL database using:

`data = tbl(mySource, sql("my query"))`

and it looks fine - `data` gives me:

```
Source: local data frame [100 x 35]

   id_szkoly  rok k_1382 k_1383 k_1384 k_1385 k_1386 k_1387 k_1388 k_1389 k_1390
1      44024 2010      0      0      0      1      0      0      1      0      0
2      35884 2010      1      0      0      0      0      0      0      0      1
3      36943 2010      1      0      0      0      0      0      0      1      0
4      36652 2010      1      0      0      1      1      0      1      0      0
5      43260 2010      1      1      0      1      1      0      0      1      1
6      42950 2010      1      1      0      1      0      0      1      1      1
7      43489 2010      0      0      0      1      0      0      0      0      0
8      34736 2010      0      0      1      1      0      0      0      1      1
9      35762 2010      0      1      1      1      0      0      1      1      1
10     43034 2010      0      0      1      0      0      0      0      1      1
..       ...  ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
Variables not shown: k_1391 (dbl), k_1392 (dbl), k_1393 (dbl), k_1394 (dbl), k_1395
  (dbl), k_1396 (dbl), k_1397 (dbl), k_1398 (dbl), k_1399 (dbl), k_1400 (dbl),
  k_1401 (dbl), k_1402 (dbl), k_1403 (dbl), k_1404 (dbl), k_1405 (dbl), k_1406
  (dbl), k_1407 (dbl), k_1408 (dbl), k_1409 (dbl), k_1410 (dbl), k_1411 (dbl),
  k_1412 (dbl), k_1413 (dbl), k_1414 (dbl)
```

Now I want to melt it to the long format, so I use `melt(data, id.vars = c('id_szkoly', 'rok'))`, but
the result is:
```
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```

On the other hand  `melt(as.data.frame(data), id.vars = c('id_szkoly', 'rok'))` works as expected, so I guess it might be some issue with a dplyr...

You can obtain my tbl dataset from http://zozlak.org/data.RData

**Comment by zozlak** [comment]
I'am not sure if it is the same problem, but maybe this example will help to track it down:
```r
reshape2::melt(data_frame(x = 1:3, y = 1:3, z = 1:3), id.vars = 'x')
# The result is:
# Error in match.names(clabs, names(xi)) : 
#  names do not match previous names
reshape2::melt(data.frame(x = 1:3, y = 1:3, z = 1:3), id.vars = 'x')
# The result is:
#   x variable value
# 1 1        y     1
# 2 2        y     2
# 3 3        y     3
# 4 1        z     1
# 5 2        z     2
# 6 3        z     3
```

**Comment by EasterBeagle** [comment]
@zozlak  I had the same problem and your work around (as.data.frame(df1)) solved my problem.

However, "melt" is from the reshape2 package...my df was a product of an rbind, so I'm wondering if there is some issue with that; when I dput my dataframe and then re-read it back in it melted correctly.

**Comment by KinGUII** [comment]
I have the same problem and this did not occur in a different version(not sure if it is early one) of dplyr and reshape. In other words, the same script runs normally on one computer but has problem on the other.

**Comment by hadley** [comment]
I'd recommend either turning into a data frame or using tidyr
