### ISSUE TITLE
select causes a fatal error when used on ill-formated data frame

### ISSUE THREAD

**Issue by mikaelmoutakis** [hadley/dplyr#887]
#the following data.frame s[[1]] does not have a name for the last 2 cols
#latest R and dplyr from CRAN
url <- "http://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD"
s <- XML::readHTMLTable(url,  stringsAsFactors=F)
df <- s[[1]] %>% select(1,5)

**Comment by hadley** [comment]
Now gives error message.
