### ISSUE TITLE
Version of summarise and/or group_by that resets prior grouping

### ISSUE THREAD

**Issue by deaneckles** [hadley/dplyr#888]
I often chain multiple group_by, summarise, group_by, summarise steps.
I find the fact that summarise only pops off the last grouping key confusing and likely to produce errors. But maybe this isn't possible to change.

Anyway, as a result, I like to always call ungroup after summarise, and often then have 
d %>% group_by(x, y) %>% summarise(...) %>% ungroup() %>% group_by(z) %>% summarise(...)

If I had a version of group_by or summarise (with different names) that would reset the grouping, that could make this a lot more compact and natural IMO. I might try this myself but don't yet understand how all the non-standard eval contexts work. Thanks.

**Comment by hadley** [comment]
`group_by()` now does reset grouping, so you can just do

```R
d %>% group_by(x, y) %>% summarise(...) %>% group_by(z) %>% summarise(...)
```

Can you give me an example where the grouping behaviour of summarise causes problems?

**Comment by deaneckles** [comment]
Oh nice. Somehow I didn't realize that. Or maybe I have an old version of dplyr installed. Sorry!
