### ISSUE TITLE
Inconsistent use of outer_join vs full_join

### ISSUE THREAD

**Issue by nickbond** [hadley/dplyr#889]

**Comment by wbuchanan** [comment]
It also doesn't help that the RStudio cheat sheet (http://www.rstudio.com/wp-content/uploads/2015/01/data-wrangling-cheatsheet.pdf) uses "outer_join" instead of full_join.  At least I know what the resolution to my problem is now.

**Comment by bbolker** [comment]
+1.  I would vote for restoring outer_join as a synonym for full_join, if possible: it fits well with the rest of the (inner, left, right) terminology.

**Comment by bbolker** [comment]
The cheatsheet is now fixed (thanks), but the documentation/naming convention issues are still open

**Comment by hadley** [comment]
Need to check that dplyr docs consistently refer to `full_join()`
