### ISSUE TITLE
select by column sequence no longer works?

### ISSUE THREAD

**Issue by happyshows** [hadley/dplyr#899]
Hi,

It's been a while since I try to select by column sequence, I vaguely remember code likes this use to work select(mtcars,1:3). But the latest version is throwing out such error msg:
Error in .Call("dplyr_combine_vars", PACKAGE = "dplyr", vars, xs) : 
  "dplyr_combine_vars" not available for .Call() for package "dplyr"

Is this intended behaviour? What's the right way to allow user quickly subsetting by column sequence? (as they may not know/care the column names)

Thanks.

**Comment by happyshows** [comment]
The mentioned feature was there: 
"select(mammals, 1:3)"
http://seananderson.ca/2014/09/13/dplyr-intro.html

**Comment by hadley** [comment]
I don't think I ever endorsed that usage of select, it just worked by coincidence. If you want to use numbers to select columns, you can just use `[`: `mtcars %>% .[1:3]`

**Comment by happyshows** [comment]
Thanks, actually I though it was a pretty neat feature. Lots of time I want to quickly select rows, for example, I just did mtcars %>% select(1:2,5,8) after I roll back to the cran version dplyr_0.4.1. 
Imagine you have a very wide table and the names are complicated to spell, this would be really quick for users.
