### ISSUE TITLE
id and id_var fail to handle the drop=FALSE case for empty factors with non-empty levels correctly

### ISSUE THREAD

**Issue by alexbbrown** [hadley/dplyr#904]
The following issue

https://github.com/hadley/tidyr/issues/56

Appears to be caused by a failure of id to behave symmetrically in the drop=FALSE case for the value of it's 'n' attribute.

This causes spread to because inconsistently purely depending upon the specifics of the data supplied at runtime.

Expected behaviour
----

When drop=FALSE, and all columns are factors, n should be equivalent to the count of the interactions between all the factor columns.

This can be simply demonstrated in the fully populated cases:

    # fully populated (all levels actually present) single factor with 3 levels 
    # expect equivalent to -> nlevels(gl(3,1)) == 3
    attr(id(data.frame(factor(1:3,1:3))),"n") # -> 3
    # fully populated 3 factor interaction with 3 levels each
    # expect equivalent to nlevels(gl(3,1):gl(3,1):gl(3,1)) == 27
    attr(id(data.frame(factor(1:3,1:3),factor(1:3,1:3),factor(1:3,1:3))),"n") # -> 27

And in the minimally populated cases

    # minimally populated factors with 3 levels
    # should be same as fully populated
    attr(id(data.frame(factor(1,1:3))),"n") # -> 3
    attr(id(data.frame(factor(1,1:3),factor(1,1:3),factor(1,1:3))),"n") # -> 27

Unexpected behaviour
----

But id fails to be follow the symmetric pattern for the empty cases:

    # unpopulated factors with 3 levels
    # should be same as fully populated
    attr(id(data.frame(factor(c(),1:3))),"n") # -> 0 (oops)
    attr(id(data.frame(factor(c(),1:3),factor(c(),1:3),factor(c(),1:3))),"n") # -> 0 (oops)

Why does this happen?
----

in tidyr::id

    .variables <- .variables[lengths != 0]

the id function which nominally handles a data frame (for which lengths would be a repeated number), is actually capable of handling a list (for which other situations might occur).  It's hard for me to see how that code - filtering out empty columns - would make sense in a data frame.

It continue in tidy::id_var with

        if (length(x) == 0) 
        return(structure(integer(), n = 0L))

which *precedes* the factor handling code:

    if (is.factor(x) && !drop) {
        id <- as.integer(addNA(x, ifany = TRUE))
        n <- length(levels(x))
    }

I suggest that the order of these clauses in id_var be fixed to check factor first.

**Comment by alexbbrown** [comment]
Added patch.  Should probably add regression test too.

**Comment by alexbbrown** [comment]
This change could cause changed behavior in the special case of id applied to a ragged list, so if that's a use case it probably should specialisef this behavior for data franes and other non ragged structured only.

**Comment by hadley** [comment]
`id()` is on its way out, so I'd rather fix this in tidyr.
