### ISSUE TITLE
filter_ with a data.table throws 'argument ".dots" is missing, with no default' error

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#906]
To reproduce:

    library(data.table)
    library(dplyr)
    DT <- data.table(x = rnorm(10))
    DT %>% filter_(~ x > 0)
    ## Error in lazyeval::common_env(.dots) : 
    ##   argument ".dots" is missing, with no default

The error persists if you replace the formula with a string or call:

    DT %>% filter_("x > 0")       # throws same error
    DT %>% filter_(quote(x > 0))  # throws same error

...and if you don't use piping:

    filter_(DT, ~ x > 0)          # throws same error

The interactive version is OK:

    DT %>% filter(x > 0)          # OK

**Comment by jakesherman** [comment]
I am having the same issue. filter_ wasn't working with data.table, but works as intended for data.frame

**Comment by paljenczy** [comment]
Confirmed, same behavior here. Using dplyr 0.4.1 and data.table 1.9.4.

**Comment by richierocks** [comment]
Just had another look at this, and it's an easy fix.  In `filter_data.table`, change the second line 

    env <- lazyeval::common_env(.dots)

to

     env <- lazyeval::common_env(dots)
