### ISSUE TITLE
Crash using group_by and summarise on an empty data frame

### ISSUE THREAD

**Issue by matteodefelice** [hadley/dplyr#910]
I am using Revolution R Open 8.0.1 beta2 and dplyr 0.3.0.2 (0.4 not yet available) on Mac OS X. 
The following crash does not happen on R 3.1.2 + dplyr 0.4.1 on Ubuntu. 

    > d = data.frame()
    > group_by(d, year) %>% summarise(import = sum(value))
    *** caught segfault ***
    address 0x20, cause 'memory not mapped'

    > R.version
    platform       x86_64-apple-darwin13.4.0   
    arch           x86_64                      
    os             darwin13.4.0                
    system         x86_64, darwin13.4.0        
    status                                     
    major          3                           
    minor          1.2                         
    year           2014                        
    month          10                          
    day            31                          
    svn rev        66913                       
    language       R                           
    version.string R version 3.1.2 (2014-10-31)
    nickname       Pumpkin Helmet   

    > print(sessionInfo())
    R version 3.1.2 (2014-10-31)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)

    locale:
    [1] C/UTF-8/C/C/C/C

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] dplyr_0.3.0.2

    loaded via a namespace (and not attached):
    [1] DBI_0.3.1      Rcpp_0.11.3    assertthat_0.1 magrittr_1.5   parallel_3.1.2
    [6] tools_3.1.2

**Comment by hadley** [comment]
Yes, probably because it's fixed in 0.4
