### ISSUE TITLE
Hybrid evaluation of [ fails

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#912]
e.g.

``` R
library("dplyr")
library("nycflights13") 
flights %>% mutate(airport = airports[, "name"]) 
# Error: not compatible with STRSXP 
```

**Comment by statwonk** [comment]
An empty `data.frame` also fails to `arrange` with the same error.  I expect an error in this case, but this one is not informative.

```r
tbl_df(data.frame()) %>% arrange(foo)
# Error: not compatible with STRSXP```

**Comment by romainfrancois** [comment]
The arrange issue seems to have been fixed at least: 

```
> tbl_df(data.frame()) %>% arrange(foo)
Source: local data frame [0 x 0]
```

**Comment by romainfrancois** [comment]
The original issue @hadley logged in is yet again a problem of hybrid.

**Comment by krlmlr** [comment]
What output would you expect?

The following works, but could perhaps be shortened:

```r
flights %>% head %>% rowwise %>%  mutate(airport = list(airports[, "name"]))
```

**Comment by hadley** [comment]
I'd expect it to return an error saying that the output is of the incorrect length (because airports and flights are not the same length)
