### ISSUE TITLE
Bad SQL mapping for "select(column %in% singleValue)"

### ISSUE THREAD

**Issue by zozlak** [hadley/dplyr#913]
At the moment `select(tbl, column %in% 13)` is translated into SQL as `WHERE column IN 13` which is not a proper SQL syntax (at least for PostgreSQL). It should be `WHERE column IN (13)`.

**Comment by hadley** [comment]
I haven't been able to figure out how to make this happen automatically, but you can force dplyr to generate the correct code with `select(tbl, column %in% c(13))`

**Comment by zozlak** [comment]
Sorry, I write down a wrong verb - it should be `select`.
