### ISSUE TITLE
dplyr shouldn't copy when mutating using self assign operator and data.table

### ISSUE THREAD

**Issue by juancentro** [hadley/dplyr#914]
I love data.table and love dplyr, but they don't play nicely along (it's natural because they have different philosophies). One of the huge benefits of data.table is avoiding copies whenever possible, but it goes against dplyr functional philosophy (I know that dplyr tries to be as memory efficient as possible, as the data.frames vignette mentions).
Actually, when you use mutate with a `tbl_dt` (data.table) dplyr makes a copy and then uses data.table's own `:=` operator.
My suggestion is to avoid copying when using dplyr self assign operator, to leverage on existing data.table functionality

**Comment by hadley** [comment]
This is a deliberate design decision. Once data.table exports a `shallow_copy()` function this problem will go away.
