### ISSUE TITLE
Lag behaves differently inside and outside of mutate

### ISSUE THREAD

**Issue by matfournier** [hadley/dplyr#915]
From: 

http://stackoverflow.com/questions/28038370/lag-changed-in-dplyr-0-4-1-default-parameter-not-working-inside-of-mutate

Trivial example that worked in previous dplyr versions but not 0.4.1, as the first row is left as NA rather than the default value: 
    
    blah <- data.frame(x1 = c(5,10,20,27,35,58,5,6))
    blah <- mutate(blah, x2 = x1 - lag(x1, n=1, default=0))

Will return NA on the first row.  Oddly `lag(x1, default=0)` works as intended. 

Doing the above code outside of the mutate function works fine (accepts default=x param): 
e.g. `blah$x2 <- blah$x1 - lag(blah$x1, n=1, default=0)` works as intended. 

Thus lag works differently inside and outside of mutate.

**Comment by hadley** [comment]
Not a crasher, so putting off until 0.5.

**Comment by tentacles-from-outer-space** [comment]
Just to notice. Same thing happens with `order_by`. Following example from `help("lead")`:
```r
right <- mutate(scrambled, prev = lag(value, order_by = year))
arrange(right, year)
```
doesn't work as expected when `n` is added:
```r
right <- mutate(scrambled, prev = lag(value, n=1L, order_by = year))
arrange(right, year)
```
