### ISSUE TITLE
select() with combinations of -matches() and matches() is inconsistent

### ISSUE THREAD

**Issue by holstius** [hadley/dplyr#916]
Here is what I expect:

    library(testthat)
    expect_equal(
        names(select(iris, matches("Sepal"), -matches("Sepal"))),
        c(names(select(iris, matches("Sepal"))), names(select(iris, -matches("Sepal")))))

Instead, the combination of `matches` and `-matches` yields an empty set:

    names(select(iris, matches("Sepal"), -matches("Sepal")))
    ## character(0)

**Comment by hadley** [comment]
That's because it has to use some heuristics to figure exactly what you want when you combine both positive and negative indices. I'm fairly confident that existing behaviour causes the minimum confusion.

**Comment by holstius** [comment]
Ah. Was trying to use it to reorder columns efficiently---moving a group of columns to the leftmost or rightmost position(s), in particular. 

David
