### ISSUE TITLE
Doesn't mutate_each() work with anonymous functions?

### ISSUE THREAD

**Issue by VitorAguiar** [hadley/dplyr#917]
Let's say we want to convert NA values into zeros:

> df <- data.frame(A = c(rnorm(4), NA), B = c(NA, rnorm(4))) 

##### Apply anonymous function
> df %>% mutate_each(funs(function(x) ifelse(is.na(x), 0, x)))
Error: unsupported type for column 'A' (CLOSXP, classes = function)

##### Apply named function
> change_na <- function(x) ifelse(is.na(x), 0, x)
>  df %>% mutate_each(funs(change_na)) #works fine!

**Comment by hadley** [comment]
It doesn't because you don't need them: `funs(ifelse(is.na(.), 0, .))`
