### ISSUE TITLE
top_n has counter-intuitive name

### ISSUE THREAD

**Issue by holgerbrandl** [hadley/dplyr#921]
The method `top_n` does not work as users think it does: It's not getting the top n entries but possibly more than n. Just after studying the docs carefully it becomes clear that it's falling back to use the last column for sorting before extracting top-results, which can be more than n in case of ties.

I think most/many users refer to "top n" to the first n entries in a group with the current sorting. What they (and me) actually need to use is  `grpd_data %>% slice(1:n)` but `top_n` sounds more "promising", and thus leads leads to well hidden errors.

To avoid any confusion about what `top_n` is doing, the sorting column should be a required parameter. Using the last column of a table is not a meaningful default.

**Comment by hadley** [comment]
It seems like reasonable behaviour to me. And it does print a message telling you which column it's using...
