### ISSUE TITLE
Weird behavior of group_by + lag

### ISSUE THREAD

**Issue by tongcx** [hadley/dplyr#925]
```
library(dplyr)
df = read.csv(text ='
   name time
1   Rob    3
2  Pete    2
3   Rob    5
4  John    3
5   Rob    2
6  Pete    3
7  John    2
8  Pete    4
9  John    1
10 Pete    1
11  Rob    4
12  Rob    1
', sep='')
df %>% group_by(name) %>% mutate(lag_time = lag(time))
```
Gets me
```
   name time lag_time
1   Rob    3       NA
2  Pete    2       NA
3   Rob    5        2
4  John    3       NA
5   Rob    2        3
6  Pete    3        2
7  John    2        3
8  Pete    4        2
9  John    1        4
10 Pete    1        1
11  Rob    4        1
12  Rob    1        4
```
Should row 3 be ```Rob 5 3```? Is this a bug or intended behavior?

**Comment by pkanavos** [comment]
I can reproduce the problem. It wasn't there with 0.3.2, appeared after upgrading to 0.4.1

**Comment by alex23lemm** [comment]
I can reproduce the the issue as well.  With the upgrade to version 0.4.1 parts of my code using `lag` started producing wrong results.

Here is [another SO question](http://stackoverflow.com/questions/28235074/dplyr-lead-and-lag-wrong-when-used-with-group-by) showing the current issue.

**Comment by hadley** [comment]
@romainfrancois can you take a look please?
