### ISSUE TITLE
rbind_list kills R when called with data frames containing complex values

### ISSUE THREAD

**Issue by gonike** [hadley/dplyr#933]
Running e.g.

```
df1 <- data.frame(r = c(1+1i, 2-1i))
df2 <- data.frame(r = c(1-1i, 2+1i))
bind_rows(df1,df2)
```

yields "R Session aborted - R encountered a fatal error. The session was terminated."

**Comment by konkam** [comment]
Similar error when using summarize, group_by with complex values :

>a = data.frame(r = 1i*rnorm(1000), k = sample(1:5, 1000, replace = T))
>a %>% group_by(k) %>% summarise(mean(r))

crashes R with

> *** caught segfault ***
> address (nil), cause 'memory not mapped'
>Traceback:
>1: .Call("dplyr_summarise_impl", PACKAGE = "dplyr", df, dots)
>2: summarise_impl(.data, dots)
>3: summarise_.tbl_df(.data, .dots = lazyeval::lazy_dots(...))
>4: summarise_(.data, .dots = lazyeval::lazy_dots(...))
>5: summarise(., mean(r))
>6: function_list[[k]](value)
>7: withVisible(function_list[[k]](value))
>8: freduce(value, `_function_list`)
>9: `_fseq`(`_lhs`)
>10: eval(expr, envir, enclos)
>11: eval(quote(`_fseq`(`_lhs`)), env, env)
>12: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
>13: a %>% group_by(k) %>% summarise(mean(r))
