### ISSUE TITLE
registration.h: multiple definition of build_index_cpp

### ISSUE THREAD

**Issue by emiliotorres** [hadley/dplyr#939]
When I link two compiled cpp files that contains `#include <dplyr.h>` (for instance tablefreq.cpp and RcppExports.cpp 
```
// tablefreq.cpp
#include <Rcpp.h>
#include <dplyr.h>
// [[Rcpp::depends(dplyr)]]
```
and
```
// RccpExports.cpp
// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#include <dplyr.h>
#include <Rcpp.h>
```
I get the following error message: multiple definition of build_index_cpp (resgistration.h:8)

```
* installing *source* package ‘emilioutils’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/emilio/R/library/Rcpp/include" -I"/home/emilio/R/library/dplyr/include"  -UNDEBUG -Wall -pedantic -g -O0 -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/emilio/R/library/Rcpp/include" -I"/home/emilio/R/library/dplyr/include"  -UNDEBUG -Wall -pedantic -g -O0 -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c tablefreq.cpp -o tablefreq.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o emilioutils.so RcppExports.o tablefreq.o -L/usr/lib/R/lib -lR
tablefreq.o: En la función `~PreserveStorage':
/home/emilio/R/library/dplyr/include/dplyr/registration.h:8: definiciones múltiples de `build_index_cpp(Rcpp::DataFrame_Impl<Rcpp::PreserveStorage>)'
RcppExports.o:/home/emilio/R/library/dplyr/include/dplyr/registration.h:8: primero se definió aquí
```
Is it the expected behaviour? Is it possible that an`inline` definition is missing?
Thank you!

(using dplyr_0.4.1.9000 )

**Comment by romainfrancois** [comment]
This goes back to this commit. https://github.com/hadley/dplyr/commit/6464634e789f3a5480b10cfd2e81a70bfc5f87fc

The `inline` was removed after a suggestion by Brian Ripley. There was probably a valuable reason for it, I'll digg in the emails.

**Comment by romainfrancois** [comment]
One workaround is to have this in all files that `#include <dplyr.h>`: 

```
#define COMPILING_DPLYR
#include <dplyr.h>
```

This way the function definition are only included in `RcppExports.cpp`

**Comment by romainfrancois** [comment]
hmm. @jjallaire, perhaps `Rcpp` could define something I can use on top of the `RcppExports.cpp` files, e.g. 

```
#define RCPP_EXPORTS_CPP
```

so that we can disambiguate between when we are compiling `RcppExports.cpp` or something else.

**Comment by romainfrancois** [comment]
@emiliotorres can you try against the development version please and reopen if the problem was not fixed.

**Comment by jjallaire** [comment]
Good idea, I'll try to add that #define soon.
