### ISSUE TITLE
Extracting elements from tbl_df - returns tbl_df not a vector

### ISSUE THREAD

**Issue by BERENZ** [hadley/dplyr#941]
When I extract one element from ```tbl_df``` object I get a ```tbl_df``` object as in the example below.

```
> set.seed(123)
> dt <- data_frame(X = rnorm(2),Y= rnorm(2))
> dt[1,1]
Source: local data frame [1 x 1]

           X
1 -0.5604756
``` 

I wonder if the result should be a ```vector``` object as in the ```data.frame``` object.

```
> set.seed(123)
> dt2 <- data.frame(X = rnorm(2),Y= rnorm(2))
> dt2[1,1]
[1] -0.5604756
```

**Comment by hadley** [comment]
This is by design. Use `[[` to extract single values
