### ISSUE TITLE
Sweep over several columns simultaneously

### ISSUE THREAD

**Issue by klmr** [hadley/dplyr#944]
`sweep` allows sweeping a summary over an array. Example from the help file:

```r
require(stats)
med.att <- apply(attitude, 2, median)
sweep(data.matrix(attitude), 2, med.att) # subtract the column medians
```

In specific cases such as this, there are ways of solving elegantly this in dplyr. However, [the general case, e.g. `scale`, is more complicated](http://stackoverflow.com/q/28298688/1968).

At the moment, the most direct dplyr equivalent of the general `sweep(x, 2, stat, fun)` seems to be:

```r
stat = as.data.frame(t(as.data.frame(stat)))
mutate_each(x, funs(fun(., stat$.))
```

Which is far from intuitive, especially concerning the access to the summary statistic.

**Comment by hadley** [comment]
`sweep()` seems like a fundamentally a matrix type operation to me.

**Comment by klmr** [comment]
I agree that `sweep` is a fundamental operation. But at the moment it’s not usable with dplyr/tidy data style format in any real sense. At the very least, dplyr would need to provide an overload that allows selecting columns in a `select`/`mutate_each` kind of way (e.g. `sweep(…, -A, -B)`). As already mentioned, the `mutate_each` is essentially *incomprehensible* (I *still* don’t know why it works that way).
