### ISSUE TITLE
[Enhancement] Extend dplyr to handle Teradata

### ISSUE THREAD

**Issue by xiaodaigh** [hadley/dplyr#947]
As Teradata is becoming more and more popular it would be nice if dplyr can be extended to deal with Teradata.

There is already a Teradata package for R. See https://github.com/Teradata/teradataR

It defines a near object class called td.data.frames.

**Comment by hadley** [comment]
I'm happy to help someone provide a dplyr backend for teradata, but currently my policy is to only personally implement backends for open source databases.
