### ISSUE TITLE
rbind_list coverts ordered factors to factors

### ISSUE THREAD

**Issue by jonadler** [hadley/dplyr#948]
If you have a variable in a data frame that is an ordered factor, after using an rbind_list call it gets converted into a regular factor. If the factors are the same in the different data frames being binded together, I don't think the ordered component of the factor should be removed.

```
y <- rbind_list(data.frame(x=factor(c(1,2,3),ordered=TRUE)),data.frame(x=factor(c(1,2,3),ordered=TRUE)))

class(y$x)
```

**Comment by romainfrancois** [comment]
This has been fixed. I've added a regression test for it anyway.
