### ISSUE TITLE
UTF-8 problems with summarise_each, other dplyr verbs OK 

### ISSUE THREAD

**Issue by andrewdolman** [hadley/dplyr#951]
Loving dplyr but came across this issue this morning. It seems to have cropped up a few times before and has been mostly fixed, but is still an issue with summarise_each

The problem is with non standard characters in dataframe column names, e.g. µ or ä.

After manipulation with summarise_each() names with these characters have extra characters.

Problem occurs on Windows (have not checked other setups) when names are encoded as UTF-8.

When I first came across this problem I was using dplyr version 0.3.x - all "verbs" cased the problem. After updating to dplyr 0.4.1 the problem was fixed for most dplyr "verbs", but summarise_each still gives me the same issue.

```
## Reproducable example
library(dplyr)

df <- data.frame(Month = c(month.abb[1:3], "März"), a = 1:4, ä = 1:4, b=1:4, µ=1:4)
df

### This works
Encoding(names(df))
df %>% summarise_each(funs(mean)) -> df2
df2
Encoding(names(df2))

### This does not
#### Set encoding of names to UTF-8
names(df) <- enc2utf8(names(df))
Encoding(names(df))
df %>% summarise_each(funs(mean)) -> df2
df2
Encoding(names(df2))


### Encoding to native works
names(df) <- enc2native(names(df))
Encoding(names(df))
df %>% summarise_each(funs(mean)) -> df2
df2
Encoding(names(df2))

## sessionInfo
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1

loaded via a namespace (and not attached):
[1] assertthat_0.1  DBI_0.3.1       lazyeval_0.1.10 magrittr_1.5    parallel_3.1.2  Rcpp_0.11.4     tools_3.1.2    

```

**Comment by gabrakadabra** [comment]
I have the same issue using `select()`. I also noticed that `select()` and `summarise_each()` messes up the characters in different ways.

**Comment by romainfrancois** [comment]
@andrewdolman can you wrap up the code in triple backticks ("`") so that it looks like code please.

**Comment by andrewdolman** [comment]
backticks employed

**Comment by andrewdolman** [comment]
Aslo, I apologise for the use of right had assignment ->

I was influenced by this blogpost, http://rud.is/b/2015/02/04/a-step-to-the-right-in-r-assignments/, which seemed to make a lot of sense on first read. The experiment lasted a couple of days.

**Comment by andrewdolman** [comment]
Another detail.

mutate fails to operate on variables with special characters in the name (like µ) created within the same function call. 

```
library(dplyr)
data(cars)

# works
mutate(cars, 
       v_mg = speed + dist, 
       v2 = speed + v_mg)

# fails
mutate(cars, 
       v_µg = speed + dist, 
       v2 = speed + vµg)
```
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.3.3  beepr_1.1        readr_0.0.0.9000 dplyr_0.4.1.9000

loaded via a namespace (and not attached):
 [1] assertthat_0.1       audio_0.1-5          bitops_1.0-6         DBI_0.3.1            devtools_1.7.0       digest_0.6.4        
 [7] evaluate_0.5.5       formatR_1.0          httr_0.6.1           knitr_1.7            lazyeval_0.1.10.9000 magrittr_1.5        
[13] memoise_0.2.1        parallel_3.1.1       plyr_1.8.1           Rcpp_0.11.5          RCurl_1.95-4.5       stringr_0.6.2       
[19] tools_3.1.1

**Comment by romainfrancois** [comment]
I'm getting this, which looks fine. 

```
> df <- data.frame(Month = c(month.abb[1:3], "März"), a = 1:4, ä = 1:4, b=1:4, µ=1:4)
>
> df
  Month a ä b µ
1   Jan 1 1 1 1
2   Feb 2 2 2 2
3   Mar 3 3 3 3
4  März 4 4 4 4
> names(df) <- enc2utf8(names(df))
>
> df
  Month a ä b µ
1   Jan 1 1 1 1
2   Feb 2 2 2 2
3   Mar 3 3 3 3
4  März 4 4 4 4
>
> Encoding(names(df))
[1] "unknown" "unknown" "UTF-8"   "unknown" "UTF-8"
> df %>% summarise_each(funs(mean)) -> df2
Warning message:
In summarise_impl(.data, dots) :
  argument is not numeric or logical: returning NA
> df2
  Month   a   ä   b   µ
1    NA 2.5 2.5 2.5 2.5
> Encoding(names(df2))
[1] "unknown" "unknown" "UTF-8"   "unknown" "UTF-8"
```

And: 

```
> mutate(cars,
+        v_µg = speed + dist,
+        v2 = speed + v_µg)
   speed dist v_µg  v2
1      4    2    6  10
2      4   10   14  18
3      7    4   11  18
4      7   22   29  36
...
```

which looks fine too. 
@andrewdolman can you check on your end please?

**Comment by andrewdolman** [comment]
Hmm, 

I just updated to the latest version of dplyr with github_install() but I still have the same results as before.

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.2.9001

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10.9000 magrittr_1.5         R6_2.1.0             assertthat_0.1       parallel_3.2.1       DBI_0.3.1            tools_3.2.1          Rcpp_0.11.6

**Comment by romainfrancois** [comment]
Thanks. I'll play with this on windows asap.

**Comment by andrewdolman** [comment]
Thanks for looking.

**Comment by romainfrancois** [comment]
Getting this on windows now: 

```
> df <- data.frame(Month = c(month.abb[1:3], "März"), a = 1:4, ä = 1:4, b=1:4, µ=1:4)
> 
> df
  Month a ä b µ
1   Jan 1 1 1 1
2   Feb 2 2 2 2
3   Mar 3 3 3 3
4  März 4 4 4 4
> names(df) <- enc2utf8(names(df))
> Encoding(names(df))
[1] "unknown" "unknown" "UTF-8"   "unknown" "UTF-8"  
> df %>% summarise_each(funs(mean)) -> df2
Warning message:
In summarise_impl(.data, dots) :
  l'argument n'est ni numérique, ni logique : renvoi de NA
> df2
  Month   a   ä   b   µ
1    NA 2.5 2.5 2.5 2.5
> Encoding(names(df2))
[1] "unknown" "unknown" "UTF-8"   "unknown" "UTF-8"  
> 
> df2
  Month   a   ä   b   µ
1    NA 2.5 2.5 2.5 2.5
```

That looks good. Still getting this though: 

```
> mutate(cars, 
+        v_µg = speed + dist, 
+        v2 = speed + v_µg )
 Error: object 'v_µg' not found 
```

**Comment by romainfrancois** [comment]
Quite a chunk of work later, I've modified how we compare column names, essentially we now let R figure it out, that's probably slower but until c/rapi gives us something better, that's the best I can do. 

Anyway I'm now getting this (with dev version 0.4.2.9002): 

@andrewdolman can you have a look please. 

``` 
> mutate(cars, v_µg = speed + dist,  v2 = speed + v_µg ) %>% head
  speed dist v_µg v2
1     4    2    6 10
2     4   10   14 18
3     7    4   11 18
4     7   22   29 36
5     8   16   24 32
6     9   10   19 28
``` 

... 

```
> session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, mingw32             
 ui       RStudio (0.99.463)          
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                

Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source        
 assertthat   0.1        2013-12-06 CRAN (R 3.2.1)
 BH           1.58.0-1   2015-05-21 CRAN (R 3.2.1)
 crayon       1.3.0      2015-06-05 CRAN (R 3.2.1)
 curl         0.9.1      2015-07-04 CRAN (R 3.2.1)
 DBI          0.3.1      2014-09-24 CRAN (R 3.2.1)
 devtools   * 1.8.0      2015-05-09 CRAN (R 3.2.1)
 digest       0.6.8      2014-12-31 CRAN (R 3.2.1)
 dplyr      * 0.4.2.9002 <NA>       local         
 git2r        0.10.1     2015-05-07 CRAN (R 3.2.1)
 lazyeval     0.1.10     2015-01-02 CRAN (R 3.2.1)
 magrittr     1.5        2014-11-22 CRAN (R 3.2.1)
 memoise      0.2.1      2014-04-22 CRAN (R 3.2.1)
 R6           2.1.0      2015-07-04 CRAN (R 3.2.1)
 Rcpp         0.11.6     2015-05-01 CRAN (R 3.2.1)
 roxygen2     4.1.1      2015-04-15 CRAN (R 3.2.1)
 rversions    1.0.1      2015-06-06 CRAN (R 3.2.1)
 stringi      0.5-5      2015-06-29 CRAN (R 3.2.1)
 stringr      1.0.0      2015-04-30 CRAN (R 3.2.1)
 testthat   * 0.10.0     2015-05-22 CRAN (R 3.2.1)
 xml2         0.1.1      2015-06-02 CRAN (R 3.2.1)
```

**Comment by andrewdolman** [comment]
Both tests work for me now too. Thank you. 

> mutate(cars, v_µg = speed + dist,  v2 = speed + v_µg ) %>% head
  speed dist v_µg v2
1     4    2    6 10
2     4   10   14 18
3     7    4   11 18
4     7   22   29 36
5     8   16   24 32
6     9   10   19 28
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.2.9002

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10.9000 magrittr_1.5         R6_2.0.1             assertthat_0.1       parallel_3.2.0       DBI_0.3.1            tools_3.2.0         
[8] Rcpp_0.11.6

**Comment by romainfrancois** [comment]
Awesome.

**Comment by andrewdolman** [comment]
Hi Romain,

Sorry, I tested the original code that used to cause me problems and I still have trouble with slightly more complicated chains of functions.

This still fails.

```
df <- data.frame(Month = c(month.abb[1:3], "März"), a = 1:4, ä = 1:4, b=1:4, µ=1:4)

#### Set encoding of names to UTF-8
names(df) <- enc2utf8(names(df))

df2 <- df %>% 
  group_by(Month) %>% 
  summarise_each(funs(mean)) 

Error: object 'Ã¤' not found
```

**Comment by romainfrancois** [comment]
I think this commit took care of the `summarise_each` problem. https://github.com/hadley/dplyr/commit/c7c9a6f2ebf89d7fc096aff598040c49a89e99f1

Can you check @andrewdolman please.

**Comment by andrewdolman** [comment]
@romainfrancois Yes this works now. 

I have also tested with other code that used to cause me problems and it all works now. Will get more testing this week. I have a lot of data with German names or µ units in the headers.

**Comment by romainfrancois** [comment]
In that case, let me close it. Please come back here if it's not all fixed.
