### ISSUE TITLE
swapping rows is confusing

### ISSUE THREAD

**Issue by momeara** [hadley/dplyr#953]
It seems like there are at least four ways that one could swap two columns
```
data_frame(x=c(1,2,3), y=c(4,5,6)) %>% rename(x=y, y=x)
data_frame(x=c(1,2,3), y=c(4,5,6)) %>% select(x=y, y=x)
data_frame(x=c(1,2,3), y=c(4,5,6)) %>% transform(x=y, y=x)
data_frame(x=c(1,2,3), y=c(4,5,6)) %>% mutate(x=y, y=x)
```

`rename`, `select`, and `transform` update simultaneously, executing the swap, while `mutate` updates sequentially clobbering `x`.

I get that this is how `mutate` is suppose to work, i believed this was one of the main motivations for making `mutate` rather than just using `transform`. However, please document this potentially surprising behavior.

**Comment by hadley** [comment]
It doesn't seem like a terribly likely failure mode to me, but I'd be happy to review a PR.
