### ISSUE TITLE
n() in dplyr_0.4.1 crashes Rstudio

### ISSUE THREAD

**Issue by wsurles** [hadley/dplyr#957]
I just installed the new version of dplyr

This will crash R
`
df <- iris %>%
  group_by(Species) %>%
  summarise(count = n(Species))
`

This will be fine
`
df <- iris %>%
  group_by(Species) %>%
  summarise(count = length(Species))
`

There is something broken with the n() function?

**Comment by hadley** [comment]
You're not supposed to give `n()` any arguments.

@romainfrancois could you please make sure this doesn't crash?

**Comment by wsurles** [comment]
Ah, good point. I was using it like n_distinct(). It does work fine when just using n(). 

The crash is still a problem. It might be best to just ignore any arguments to n() and give a warning.

**Comment by romainfrancois** [comment]
Hmm. I get: 

```
> iris %>% group_by(Species) %>% summarise(count = n(Species))
Erreur : n does not take arguments
```

which has been added [there](https://github.com/hadley/dplyr/commit/68a45be6174221b279f91eb9ddb53b6376cfa22d)

**Comment by romainfrancois** [comment]
This seems fixed
