### ISSUE TITLE
Group_by stop working after arrange (version 4.0.1)

### ISSUE THREAD

**Issue by pwalaszek** [hadley/dplyr#959]
Dplyr change group_by behavior from version 3.0.2 to 4.0.1. I take me some time to find this bug.

I'll explain it using simple example:
We have two types of logs and you want to compute time that pass from previous log with the same type.

In the 3.0.2 dplyr version I have:

    df = data_frame(Log= c(1,2,1,2,1,2), Time = c(10,1,3,0,15,11))
    df %>% 
         arrange(Time) %>%
         group_by(Log) %>%
         mutate(Diff = Time - lag(Time))

And it gives me correct result:

         Log Time Diff
    1     2    0   NA
    2     2    1    1
    3     1    3   NA
    4     1   10    7
    5     2   11   10
    6     1   15   5

When I run this code in version 4.0.1 I got:

         Log Time Diff
    1     2    0   NA
    2     2    1    1
    3     1    3   NA
    4     1   10    7
    5     2   11    1
    6     1   15    4

__It calculates time to previous log__, but it should to previous log with the same type. It looks like group_by doesn't work. I can fix it changing order in the pipeline to:
    
     df %>% 
       group_by(Log) %>%
       arrange(Time) %>%
       mutate(Diff = Time - lag(Time))

Result is:

       Log Time Diff
    1   1    3   NA
    2   1   10    7
    3   1   15    5
    4   2    0   NA
    5   2    1    1
    6   2   11   10

It's very hard to find this kind of bugs when you have long code. Please add some UT for this case and fix it in the next version.

**Comment by romainfrancois** [comment]
I think it is related to #925, which has been fixed. Can you prepare a pull request with the UT you have in mind. This will get tested automatically by travis, etc ...

**Comment by romainfrancois** [comment]
This appears to have been fixed. 

```
> df = data_frame(Log= c(1,2,1,2,1,2), Time = c(10,1,3,0,15,11))
> df %>%
+      arrange(Time) %>%
+      group_by(Log) %>%
+      mutate(Diff = Time - lag(Time))
Source: local data frame [6 x 3]
Groups: Log

  Log Time Diff
1   2    0   NA
2   2    1    1
3   1    3   NA
4   1   10    7
5   2   11   10
6   1   15    5
```

I've added a unit test.
