### ISSUE TITLE
Example for data_frame_()

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#961]
Could anyone provide a working example of `data_frame_()`? Either provide here or add it to the actual examples for `data_frame()` and `data_frame_()` and point me there?

**Comment by hadley** [comment]
`dplyr::data_frame_(list(x = ~1:10, y = ~x * 2))`

**Comment by hadley** [comment]
Will add to docs next time I'm working on dplyr

**Comment by jennybc** [comment]
Aahh ... twiddles. Thx.
