### ISSUE TITLE
lag() working incorrectly in redshift

### ISSUE THREAD

**Issue by mtreadwell** [hadley/dplyr#962]
When I call lag() in R it issues a query to my data source similar to the following:

SELECT *
LAG(value,1,NULL) over (PARTITION BY thing1, thing2 ORDER BY thing3) AS lagged
FROM table
ORDER BY ...

However, LAG seems to work slightly different in Redshift and will not accept a third parameter for LAG()
See here: http://docs.aws.amazon.com/redshift/latest/dg/r_WF_LAG.html

----------------------

The following:

der %>%
     group_by(thing1, thing2) %>%
     arrange(thing3) %>%
     mutate(change = lag(value,1)

Gives me 

ERROR: Default parameter not be supported for window function lag

Could this just be an issue with slight differences in LAG() between Redshift and PostgreSQL?

**Comment by hadley** [comment]
Yes. Unfortunately I don't have the resources to maintain any more database backends but the process for making a new backend is relatively simple and documented in a vignette. I'm happy to help out.
