### ISSUE TITLE
Chaining desc does not work in arrange for remote tables

### ISSUE THREAD

**Issue by cosinequanon** [hadley/dplyr#963]
It is my understanding that semantically `arrange(col %>% desc)` and `arrange(desc(col))` are equivalent. If this is not actually true then this might not actually be an issue. 

Code to repro:

    library(dplyr)
    my_db <- src_sqlite("my_db.sqlite3", create = T)
    copy_to(my_db, iris)

    myiris <- tbl(my_db, 'iris')

    # this works fine
    myiris %>%
        arrange(desc(Petal.Width))

    # this produces an error
    myiris %>%
        arrange(Petal.Width %>% desc)

The specific error is:

    Error in UseMethod("escape") :
        no applicable method for 'escape' applied to an object of class "function"

This seems to only fail for remote sources.

**Comment by hadley** [comment]
Hmmm, I don't think this is going to be easy to make work for remote sources. For now, just don't do it :/
