### ISSUE TITLE
left_join behaviour with NA values 

### ISSUE THREAD

**Issue by konvas1** [hadley/dplyr#965]
Hello, 
I noticed the following strange behaviour in version 0.4.1:-  `left_join` gives different result when joining on `NA`s, depending on whether the variable is a factor or not (the correct result is when it is a factor). 

    left_join(
        data.frame(b = as.character(NA), stringsAsFactors = FALSE),  
        data.frame(b = as.character(NA),  c = 3, stringsAsFactors = FALSE)
    )
    # Joining by: "b"
    #      b  c
    # 1 <NA> NA
    left_join(
        data.frame(b = as.character(NA)), 
        data.frame(b = as.character(NA),  c = 3)
    )
    # Joining by: "b"
    #      b c
    # 1 <NA> 3

I have tried this with dplyr 0.3.0.9 and both commands give the same (correct) result, i.e. the one in which `c = 3`.

Thanks!
Vasilis

**Comment by romainfrancois** [comment]
This appears to have been fixed: 

```
> left_join(
+     data.frame(b = as.character(NA), stringsAsFactors = FALSE),
+     data.frame(b = as.character(NA),  c = 3, stringsAsFactors = FALSE)
+ )
Joining by: "b"
     b c
1 <NA> 3
>
>
> left_join(
+     data.frame(b = as.character(NA)),
+     data.frame(b = as.character(NA),  c = 3)
+ )
Joining by: "b"
     b c
1 <NA> 3
```

Please reopen if not.
