### ISSUE TITLE
Row names disappear after applying mutate_each()

### ISSUE THREAD

**Issue by kasiajanocha** [hadley/dplyr#973]
Applying mutate_each on a data.frame with named rows results with a data.frame without row names. Not sure if it should work that way.
Specifically, the following script:

<code><pre>
require(dplyr)
Product <- c("A", "B", "C", "Total")<br />
Continent <- c("Africa", "America", "Asia", "Australia", "Europe")<br />
values <- c(0.4, 0.2, 0.4, 0.1, 0.3, 0.4, 0.3, 0.4, 0.5, 0.2, 
            0.3, 0.2, 0.4, 0.3, 0.3, 0.1, 0.4, 0.4, 0.2, 0.2)<br />
M <- matrix(values, ncol=5, dimnames=list(Product, Continent))<br />
df <- as.data.frame(M)<br />
print(df)<br />
stat <- as.data.frame(t(as.data.frame(M[4,])))<br />
print(mutate_each(df, funs(fun(., stat$.))))<br />
</pre></code>

prints out
<code><pre>
      Africa America Asia Australia Europe
A        0.4     0.3  0.5       0.4    0.4
B        0.2     0.4  0.2       0.3    0.4
C        0.4     0.3  0.3       0.3    0.2
Total    0.1     0.4  0.2       0.1    0.2
  Africa America Asia Australia Europe
1    0.5     0.7  0.7       0.5    0.6
2    0.3     0.8  0.4       0.4    0.6
3    0.5     0.7  0.5       0.4    0.4
4    0.2     0.8  0.4       0.2    0.4
</pre></code>

**Comment by hadley** [comment]
Yes, dplyr makes no guarantees that it will preserve row names.
