### ISSUE TITLE
Performance issues with joins

### ISSUE THREAD

**Issue by pimentel** [hadley/dplyr#984]
Hi,

I have two data.frames I want to do an `inner_join` on. [**Here is the data**](http://math.mcb.berkeley.edu/~pimentel/data/dplyr.RData)

```{r}
> nrow(unique_counts)
[1] 3533070
> nrow(intron_targ)
[1] 186838
```

I recently upgrade to v0.4.1 from CRAN. I'm not sure what version I was at before, but v0.4.0 had the same issue, and I couldn't build anything older (I keep getting compilation issues). Anyway, I don't have the old timings, but they certainly weren't anywhere near this long.

```{r}
> load(url("http://math.mcb.berkeley.edu/~pimentel/data/dplyr.RData"), verbose = TRUE)
Loading objects:
  unique_counts
  intron_targ
> class(unique_counts)
[1] "data.frame"
> class(intron_targ)
[1] "data.frame"
>
> system.time(hi <- dplyr::inner_join(unique_counts, intron_targ, by = "target_id"))
   user  system elapsed
115.841   0.183 116.240
```

Casting the data.frames to data.tables is more on par what I remember:

```{r}
> system.time(hi <- inner_join(data.table::data.table(unique_counts),
+         data.table::data.table(intron_targ), by = "target_id"))
   user  system elapsed
  2.751   0.104   2.853
```

Is this expected behavior? Here is the sessionInfo:

```{r}
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] dplyr_0.4.1

loaded via a namespace (and not attached):
 [1] assertthat_0.1   chron_2.3-45     data.table_1.9.4 DBI_0.3.1
 [5] magrittr_1.5     parallel_3.1.2   plyr_1.8.1       Rcpp_0.11.4
 [9] reshape2_1.4.1   stringr_0.6.2    tools_3.1.2
```

I also built d78f5caa136628ae873a2656aa0ac6df25150fd5 and got the same performance.

I'd appreciate any help or tips you might have on speeding this up using regular data.frames.

Thanks a bunch,

Harold

EDIT: Updated URL to faster server

**Comment by kismsu** [comment]
To add to this issue, I've run a test from demo folder and got the following

```r
        tech  inner   left outer right
1       base 787.88 367.07    NA 355.7
2 data.table   8.67   4.66    NA   7.5
3      dplyr 130.40 124.61    NA 134.3
4     pandas  23.71  21.52  22.9  21.9
```
for 
```r
Session info --------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (0.98.1091)         
 language en_GB:en                    
 collate  en_GB.UTF-8                 
 tz       <NA>                        

Packages ------------------------------------------------
 package        * version   date       source        
 assertthat     * 0.1       2013-12-06 CRAN (R 3.1.2)
 chron          * 2.3-45    2014-02-11 CRAN (R 3.1.2)
 colorspace     * 1.2-4     2013-09-30 CRAN (R 3.1.2)
 data.table       1.9.4     2014-10-02 CRAN (R 3.1.2)
 DBI            * 0.3.1     2014-09-24 CRAN (R 3.1.2)
 devtools         1.7.0     2015-01-17 CRAN (R 3.1.2)
 digest         * 0.6.8     2014-12-31 CRAN (R 3.1.2)
 dplyr            0.4.1     2015-01-14 CRAN (R 3.1.2)
 ggplot2        * 1.0.0     2014-05-21 CRAN (R 3.1.2)
 gtable         * 0.1.2     2012-12-05 CRAN (R 3.1.2)
 magrittr       * 1.5       2014-11-22 CRAN (R 3.1.2)
 MASS           * 7.3-37    2015-01-10 CRAN (R 3.1.2)
 microbenchmark   1.4-2     2014-09-28 CRAN (R 3.1.2)
 munsell        * 0.4.2     2013-07-11 CRAN (R 3.1.2)
 plyr           * 1.8.1     2014-02-26 CRAN (R 3.1.2)
 proto          * 0.3-10    2012-12-22 CRAN (R 3.1.2)
 Rcpp           * 0.11.4    2015-01-24 CRAN (R 3.1.2)
 reshape2         1.4.1     2014-12-06 CRAN (R 3.1.2)
 rstudio        * 0.98.1091 2015-02-04 local         
 rstudioapi     * 0.2       2014-12-31 CRAN (R 3.1.2)
 scales         * 0.2.4     2014-04-22 CRAN (R 3.1.2)
 stringr        * 0.6.2     2012-12-06 CRAN (R 3.1.2)
```
I'm struggling to install version 0.3 for some reason, but I remember that dplyr has results better than pandas before.

**Comment by shntnu** [comment]
Perhaps related to this issue: the example below indicates that casting a variable as a factor increases the speed of dplyr::inner_join. But it's a little odd because the factor is in fact coerced to character vector.

    n <- 1000000
    m <- 1000
    d <- data.frame(k = sample(letters, size = n, replace = T),
                    v = sample(n))
    h <- data.frame(k = sample(letters[1:10], m, replace = T))

    system.time(dplyr::inner_join(d, h, by = c("k")))

    ## Warning in inner_join_impl(x, y, by$x, by$y): joining factors with
    ## different levels, coercing to character vector

    ##    user  system elapsed 
    ##   0.990   0.392   1.381

    d$k <- as.character(d$k)
    h$k <- as.character(h$k)

    system.time(dplyr::inner_join(d, h, by = c("k")))

    ##    user  system elapsed 
    ##   8.348   0.434   8.784

    sessionInfo()

    ## R version 3.2.1 (2015-06-18)
    ## Platform: x86_64-apple-darwin13.4.0 (64-bit)
    ## Running under: OS X 10.9.5 (Mavericks)
    ## 
    ## locale:
    ## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] R6_2.1.0        assertthat_0.1  magrittr_1.5    parallel_3.2.1 
    ##  [5] DBI_0.3.1       tools_3.2.1     htmltools_0.2.6 dplyr_0.4.2    
    ##  [9] Rcpp_0.11.6     stringi_0.5-5   rmarkdown_0.7   knitr_1.10.5   
    ## [13] stringr_1.0.0   digest_0.6.8    evaluate_0.7

**Comment by hadley** [comment]
This looks like it's been resolved

``` r
n <- 1e+06
m <- 1000
d <- data.frame(k = sample(letters, size = n, replace = T), v = sample(n))
h <- data.frame(k = sample(letters[1:10], m, replace = T))

system.time(dplyr::inner_join(d, h, by = c("k")))
#> Warning in inner_join_impl(x, y, by$x, by$y): joining factors with
#> different levels, coercing to character vector
#>    user  system elapsed 
#>   0.989   0.442   1.557

d$k <- as.character(d$k)
h$k <- as.character(h$k)
system.time(dplyr::inner_join(d, h, by = c("k")))
#>    user  system elapsed 
#>   1.033   0.425   1.566
```
