### ISSUE TITLE
dplyr crashing in RStudio Server on Linux

### ISSUE THREAD

**Issue by pyltime** [hadley/dplyr#989]
Running faulty dplyr code such as 
```
devtools::install_github("hadley/dplyr@36fa89e4deb630c84656cd9c7c247f4725765920") 
library(dplyr) 
iris %>% group_by(Specis) # intentional misspelling
```
in RStudio Server on Linux can cause dplyr to crash. See the stack trace [here](https://gist.github.com/pyltime/d5627cd540c27be03434) for more information.

**Comment by romainfrancois** [comment]
This has been fixed. With the dev version, I get: 

```
> iris %>% group_by(Specis)
Erreur : unknown column 'Specis'
```
