### ISSUE TITLE
"subscript out of bounds" error with tbl_df

### ISSUE THREAD

**Issue by msonnabaum** [hadley/dplyr#995]
I used summarise to create a new data frame like so:

```r
data <- "
sha1 key
d526f0de4eba76ebe6bc368c62ccf34bcc454df6  A
7c226d14a8461222bcfef3bb1910643ed84af8ad  B
7c226d14a8461222bcfef3bb1910643ed84af8ad  B
ef4e932d716742952a72a5ef23d538f65fcdbf78  C
ef4e932d716742952a72a5ef23d538f65fcdbf78  A
ef4e932d716742952a72a5ef23d538f65fcdbf78  D
"
df <- read.table(text=data, header = TRUE)

filtered <- df %>%
  group_by(key) %>%
  summarise(total = n())
```

My first attempt at plotting it with layer_points worked fine, but then changing it to layer_bars fails with `Error in .subset2(x, i, exact = exact) : subscript out of bounds`:

```r
filtered %>%
  ggvis(x = ~key, y = ~total) %>%
  layer_bars()
```
I figured this was a ggvis issue, but then noticed that it does work if I change the tbl_df that summarise produces back to a data frame:

```r
as.data.frame(filtered) %>%
  ggvis(x = ~key, y = ~total) %>%
  layer_bars()
```

So maybe this is an issue with tbl_df?

**Comment by romainfrancois** [comment]
This works fine for me. Which version of `dplyr` are you using ?

**Comment by msonnabaum** [comment]
Good call.

I had 0.3.0.2. Just upgraded to 0.4.1 and it now works for me as well.

Thanks!
