### ISSUE TITLE
Use a column created in dplyr::do() within same call

### ISSUE THREAD

**Issue by jflournoy** [hadley/dplyr#997]
from my [stackoverflow post](http://stackoverflow.com/questions/28353062/how-do-i-use-a-column-created-in-dplyrdo-within-same-call)

`mutate` has the fantastic capability of being able to refer to columns one has created within the same call (e.g., `mutate(flights, gain = arr_delay - dep_delay, gain_per_hour = gain / (air_time / 60))`).

I'm trying to use the same thing working with `do()` . The following is just a throw away example -- I promise I have a good reason for wanting to do this:

    data.frame(n=round(runif(1000,20,100),0)) %>%
    group_by(n) %>%
    do(
      x=mean(rnorm(.$n,10,1)),
      y=mean(rnorm(.$n,20,x))
    )

Of course, I get the error `Error in rnorm(.$n, 20, x) : object 'x' not found`. If I try to use `.$x` I get `Error in rnorm(.$n, 20, .$x) : invalid arguments`. I haven't been able to find any documentation relating to this, and maybe it's just not possible -- but it seems like it should be.

**Comment by hadley** [comment]
It's not currently possible, and I think it will be quite difficult to implement :/
